### PR TITLE
fix: set organiser email to external id

### LINKED ISSUE #5588: [CAL-399] Events are added twice to calendars
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When an event is created I get two events: one in the default account calendar, and one in the calendar that I have chosen in `cal.com`

☝️
Blue is events added to my default email calendar.
Pink is events added to the secondary calendar I've setup to add events to (`calcom`)

### Steps to Reproduce

1. Setup a secondary calendar as the calendar to add events to.
2. Schedule a meeting
3. Get events in both your default account calendar and the secondary you setup.

### Technical details

* Browser version, screen recording, console logs, network requests: All browsers. Happens with anyone scheduling a meeting with me.

> From [SyncLinear.com](https://synclinear.com)

### LINKED ISSUE #7329: [CAL-1149] Duplicate google event
Booked event is created on both the default calendar and the calendar/email that is associated with the [cal.com](http://cal.com) account under the condition that both of those calendars are within the single connection

Created via Threads. See full discussion: [https://threads.com/34451450211](https://threads.com/34451450211)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1149](https://linear.app/calcom/issue/CAL-1149/duplicate-google-event)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/5588, https://github.com/calcom/cal.com/issues/7329

Do suggest if there are better approach to fix these issues

BEFORE:-
Screenshot 2023-02-25 at 3 18 54 PM

AFTER:-
Screenshot 2023-02-25 at 3 19 16 PM

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

File: packages/app-store/googlecalendar/lib/CalendarService.ts [hunk 1]
```diff
@@ -88,8 +88,11 @@ export default class GoogleCalendarService implements Calendar {
           {
             ...calEventRaw.organizer,
             id: String(calEventRaw.organizer.id),
-            organizer: true,
             responseStatus: "accepted",
+            organizer: true,
+            email: calEventRaw.destinationCalendar?.externalId
+              ? calEventRaw.destinationCalendar.externalId
+              : calEventRaw.organizer.email,
```
Comment (Udit-takkar) [inline packages/app-store/googlecalendar/lib/CalendarService.ts:95]: the event was created twice because google adds the event to all attendees email primary calendar. so if a user has a secondary calendar as destination calendar he would see event created on both primary and secondary calendar. we can avoid adding event to primary calendar by simply not passing email here

**Review by zomars — APPROVED** [review]
LGTM
