### PR TITLE
fix: Embed - Better support for layout config(without flash of default toggle)

### LINKED ISSUE #9715: [CAL-2026] Embed week_view layout not working, if booking page isn't opened directly.
1. Load profile page in embed.
2. Use UI instruction to set the layout to week_view
3. Select an event and notice that default month_view is loaded.

<sub>[CAL-2026](https://linear.app/calcom/issue/CAL-2026/embed-week-view-layout-not-working-if-booking-page-isnt-opened)</sub>

### LINKED ISSUE #9795: [CAL-2050] Unwanted top margin in inline embed in Month View.
Old booker didn't have the margin and any margin if needed should be added by Embed user.

<sub>[CAL-2050](https://linear.app/calcom/issue/CAL-2050/unwanted-top-margin-in-inline-embed-in-month-view)</sub>

### LINKED ISSUE #9796: [CAL-2051] The Embed Snippets for self-hosters aren't directly usable
Embed Snippets fallback to app.cal.com in many cases. They should have hardcoded values for `embedJsUrl` and `embedOrigin`

<sub>[CAL-2051](https://linear.app/calcom/issue/CAL-2051/the-embed-snippets-for-self-hosters-arent-directly-usable)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

- Better supports layout config through layout param and updates the Embed Code Snippets accordingly
- Allows toggling b/w different layout views without any issues

Fixes #9715 
Fixes CAL-2026

Fixes #9795
Fixes Cal-2050

Fixes #9796 
Fixes Cal-2051

Loom: https://www.loom.com/share/838cf145a46d4c4494565ce38b0d688b

## Type of change
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

## How should this be tested?

- See the [loom](https://www.loom.com/share/838cf145a46d4c4494565ce38b0d688b)
- Also test that different codes generated in Embed Snippet Generator are correct for different types of Embeds in HTML and React.
	- [x] Inline Embed - HTML
	- [x] Inline Embed - React
	- [x] Inline Embed - Preview
	- [x] Element Click - HTML
	- [x] Element Click - React
	- [x] Element Click - Preview
	- [x] Floating Popup - HTML
	- [x] Floating Popup - React
	- [x] Floating Popup - Preview

## Mandatory Tasks
- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: apps/web/components/Embed.tsx
Comment (hariombalhara) [inline apps/web/components/Embed.tsx:1]: This file has changes related to generating the Embed Snippet when layout is toggled.

File: apps/web/components/Embed.tsx [hunk 1]
```diff
@@ -175,14 +180,16 @@ const Codes: Record<string, Record<string, (...args: any[]) => string>> = {
       return code`
 import Cal, { getCalApi } from "@calcom/embed-react";
 import { useEffect } from "react";
-function MyComponent() {
+export default function MyApp() {
```
Comment (hariombalhara) [inline apps/web/components/Embed.tsx:183]: Changed it to this, as it makes it easier to just copy paste and get it running on CodeSandbox. I guess it would be easier for others too.

File: packages/embeds/embed-core/index.html [hunk 2]
```diff
@@ -168,7 +168,9 @@ <h3>
           <a href="?only=ns:default">[Dark Theme][Guests(janedoe@example.com and test@example.com)](Default Namespace)</a>
         </h3>
         <button onclick="Cal('ui',{theme:'light'})">Toggle to Light</button>
-
+        <button onclick="Cal('ui',{layout:'week_view'})">Toggle to Week View</button>
+        <button onclick="Cal('ui',{layout:'month_view'})">Toggle to Month View</button>
+        <button onclick="Cal('ui',{layout:'column_view'})">Toggle to Column View</button>
```
Comment (hariombalhara) [inline packages/embeds/embed-core/index.html:173]: Tests toggle layout using UI instruction

File: packages/embeds/embed-core/index.html [hunk 3]
```diff
@@ -253,6 +255,14 @@ <h3><a href="?only=conflicting-theme">You would be able to test out conflicting
       <i>Note that one of the embeds would stay in loading state as they are using the same namespace and it is not supported to have more than 1 embeds using same namespace</i>
       </div>
     </div>
+    <div class="inline-embed-container" id="cal-booking-place-weekView">
```
Comment (hariombalhara) [inline packages/embeds/embed-core/index.html:258]: Tests layout config as in Embed Snippet Generator.

File: packages/embeds/embed-core/src/embed-iframe.ts [hunk 4]
```diff
@@ -23,6 +23,9 @@ export type UiConfig = {
 type SetStyles = React.Dispatch<React.SetStateAction<EmbedStyles>>;
 type setNonStylesConfig = React.Dispatch<React.SetStateAction<EmbedNonStylesConfig>>;
 
+/**
+ * This is in memory persistence needed so that when user browses through the embed, the configurations from the instructions aren't lost.
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed-iframe.ts:27]:
```suggestion
 * This is in-memory persistence needed so that when user browses through the embed, the configurations from the instructions aren't lost.
```

File: packages/embeds/embed-core/src/embed-iframe.ts [hunk 5]
```diff
@@ -183,9 +190,21 @@ export const useEmbedTheme = () => {
...
+ * - Ensures that all the components using useEmbedUiConfig are updated when ui config changes. It is done by maintaining a list of all non-stale setters.
+ */
 export const useEmbedUiConfig = () => {
   const [uiConfig, setUiConfig] = useState(embedStore.uiConfig || {});
-  embedStore.setUiConfig = setUiConfig;
+  embedStore.setUiConfig.push(setUiConfig);
+  useEffect(() => {
+    return () => {
+      const foundAtIndex = embedStore.setUiConfig.findIndex((item) => item === setUiConfig);
+      // Keep removing the setters that are stale
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed-iframe.ts:204]: So that the array doesn't keep on growing.

File: packages/embeds/embed-core/src/embed-iframe.ts [hunk 6]
```diff
@@ -440,6 +458,13 @@ if (isBrowser) {
   log("Embed SDK loaded", { isEmbed: window?.isEmbed?.() || false });
   const url = new URL(document.URL);
   embedStore.theme = window?.getEmbedTheme?.();
+
+  embedStore.uiConfig = {
+    // TODO: Add theme as well here
+    // theme:
+    layout: url.searchParams.get("layout") as BookerLayouts,
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed-iframe.ts:465]: layout can be configured using query param(which is basically `config.layout` in inline instruction) or UI instruction.

File: packages/embeds/embed-core/src/embed.ts [hunk 7]
```diff
@@ -125,10 +127,21 @@ type SingleInstruction = SingleInstructionMap[keyof SingleInstructionMap];
...
 export type PrefillAndIframeAttrsConfig = Record<string, string | string[] | Record<string, string>> & {
+  // TODO: iframeAttrs shouldn't be part of it as that configures the iframe element and not the iframed app.
   iframeAttrs?: Record<string, string> & {
     id?: string;
   };
+
+  // TODO: It should have a dedicated prefill prop
+  // prefill: {},
+
+  // TODO: Move layout and theme as nested props of ui as it makes it clear that these two can be configuring using `ui` instruction as well any time.
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed.ts:142]:
```suggestion
  // TODO: Move layout and theme as nested props of ui as it makes it clear that these two can be configured using `ui` instruction as well any time.
```

File: packages/features/bookings/Booker/Booker.tsx [hunk 8]
```diff
@@ -59,13 +62,10 @@ const BookerComponent = ({
   const extraDays = isTablet ? extraDaysConfig[layout].tablet : extraDaysConfig[layout].desktop;
   const bookerLayouts = event.data?.profile?.bookerLayouts || defaultBookerLayoutSettings;
   const animationScope = useBookerResizeAnimation(layout, bookerState);
-  const isEmbed = typeof window !== "undefined" && window?.isEmbed?.();
 
-  // We only want the initial url value, that's why we memo it. The embed seems to change the url, which sometimes drops
-  // the layout query param.
-  const layoutFromQueryParam = useMemo(() => validateLayout(getQueryParam("layout") as BookerLayouts), []);
```
Comment (hariombalhara) [inline packages/features/bookings/Booker/Booker.tsx:66]: Reading from query param is taken care of by useEmbedUiConfig

File: apps/web/components/Embed.tsx [hunk 9]
```diff
@@ -710,13 +750,13 @@ const EmbedTypeCodeAndPreviewDialogContent = ({
       height: "100%",
     },
     theme: Theme.auto,
+    layout: BookerLayouts.MONTH_VIEW,
```
Comment (hariombalhara) [inline apps/web/components/Embed.tsx:753]: Moved it along with theme because they are both ui config and makes sense to be together.

File: apps/web/pages.js [hunk 10]
```diff
@@ -1,4 +1,6 @@
 const glob = require("glob");
+console.warn(glob.sync("public/embed/*", { cwd: __dirname }));
+console.warn(glob.sync("public/*", { cwd: __dirname }));
```
Comment (hariombalhara) [inline apps/web/pages.js:3]:
```suggestion
```

File: apps/web/components/Embed.tsx [hunk 11]
```diff
@@ -175,14 +183,24 @@ const Codes: Record<string, Record<string, (...args: any[]) => string>> = {
...
       const cal = await getCalApi();
       ${uiInstructionCode}
     })();
   }, [])
-  return <Cal calLink="${calLink}" style={{width:"${width}",height:"${height}",overflow:"scroll"}} />;
+  return <Cal 
+    calLink="${calLink}" 
+    style={{width:"${width}",height:"${height}",overflow:"scroll"}}
+    ${previewState.layout ? "config={{layout: '" + previewState.layout + "'}}" : ""}${
+        IS_SELF_HOSTED
```
Comment (hariombalhara) [inline apps/web/components/Embed.tsx:197]: Adds additional props only for self hosted.

File: apps/web/next.config.js [hunk 12]
```diff
@@ -100,7 +100,7 @@ plugins.push(withAxiom);
 const userTypeRouteRegExp = `/:user((?!${pages.join("/|")})[^/]*)/:type((?!book$)[^/]+)`;
 const teamTypeRouteRegExp = "/team/:slug/:type((?!book$)[^/]+)";
 const privateLinkRouteRegExp = "/d/:link/:slug((?!book$)[^/]+)";
-const embedUserTypeRouteRegExp = `/:user((?!${pages.join("|")}).*)/:type/embed`;
+const embedUserTypeRouteRegExp = `/:user((?!${pages.join("/|")})[^/]*)/:type/embed`;
```
Comment (hariombalhara) [inline apps/web/next.config.js:103]: Makes it similar to userTypeRouteRegex and thus supports /teampro/30min urls too.

File: apps/web/test/lib/next-config.test.ts [hunk 13]
```diff
@@ -94,6 +94,12 @@ describe('next.config.js - RegExp', ()=>{
       type:'30'
     })
 
+    // Edgecase of username starting with team also works
+    expect(embedUserTypeRouteRegExp.exec('/teampro/30/embed')?.groups).toContain({
```
Comment (hariombalhara) [inline apps/web/test/lib/next-config.test.ts:98]: Added test.

**Review by hariombalhara — COMMENTED** [review]
Self reviewed.

**Review by PeerRich — APPROVED** [review]
