### PR TITLE
correction of position on 'Adding events to' button

### LINKED ISSUE #8289: Adding to calendar button not centered
### Issue Summary

Screenshot:

Before

### Steps to Reproduce

I'll fix this in a minute and PR

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### PR DESCRIPTION
**Pull request by hybes**
## What does this PR do?

Add 'items-center' to the Calendar active selection

Fixes #8289 
Before:
Before

After:
After

**Environment**: Staging(main branch) / Production

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by PeerRich** [comment]
i think the problem is the icon is too big

File: apps/web/components/settings/CalendarSwitch.tsx [hunk 1]
```diff
@@ -75,7 +75,7 @@ export function CalendarSwitch(props: {
       />
       {props.defaultSelected && (
         <Badge variant="gray">
-          <div className="flex">
+          <div className="flex items-center">
             <ArrowLeft className="text-default mr-1" /> {t("adding_events_to")}
```
Comment (PeerRich) [inline apps/web/components/settings/CalendarSwitch.tsx:79]:
```suggestion
            <ArrowLeft className="text-default mr-1 h-4 w-4" /> {t("adding_events_to")}
```

**Review by PeerRich — APPROVED** [review]
