### PR TITLE
fix: signing_up_terms i18n

### LINKED ISSUE #15183: [CAL-3798] Error with “By proceeding, you agree to our terms and privacy policy”
We were having this issue on the booking confirmation page: it did not have the word "terms" and now it is fixed, but the “privacy policy” is missing.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3798](https://linear.app/calcom/issue/CAL-3798/error-with-by-proceeding-you-agree-to-our-terms-and-privacy-policy)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

- Fixes CAL-3798 
- Fixes https://github.com/calcom/cal.com/issues/15183

BEFORE:- 
Screenshot 2024-05-22 at 4 25 43 PM

AFTER:-
Screenshot 2024-05-22 at 4 27 08 PM

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [x] N/A I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [x] N/A I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

### CODE REVIEW

File: apps/web/pages/signup.tsx [hunk 1]
```diff
@@ -538,23 +538,25 @@ export default function Signup({
...
-                      className="text-emphasis hover:underline"
-                      href={`${WEBSITE_URL}/privacy`}
-                      target="_blank">
-                      Privacy Policy
-                    </Link>
-                    .
-                  </Trans>
+                  <Trans
+                    i18nKey="signing_up_terms"
+                    components={[
```
Comment (Udit-takkar) [inline apps/web/pages/signup.tsx:543]: https://react.i18next.com/latest/trans-component#alternative-usage-components-array

**Review by keithwillcode — APPROVED** [review]
