### PR TITLE
fix: Custom time input for availability

### LINKED ISSUE #15763: Availability doesnt allow 5 minute steps only 15 minute steps
### Issue Summary
Currently the Availability / Working Hours only allow the usage of 15 Minute steps, so for example:
image

We have some usecases where we would need though 16:10 or 16:05. We would prefer if:
- 5 Minute Steps are choosable
- manual typing orf "16:05" gets accepted

### Steps to Reproduce
1. go to availability
2. add working hours of "08:20 - 11:50" and "13:00 - "16:05"

### Expected Results
- More flexibility on the working hours to respect opening times of local shops / childcare that are not always in 15min steps.

### PR DESCRIPTION
**Pull request by Manas-Kenge**
## What does this PR do?

- Fixes #15763 
- Fixes CAL-4526

#### Video Demo:

- Before

https://github.com/user-attachments/assets/63d8fdde-1f7c-4f2f-8268-fd114d124247

- After

https://github.com/user-attachments/assets/c58cb957-e947-47c0-bc87-cdd6a8b772af

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). N/A 
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

---
## Summary by cubic
Enable custom time entry in the availability time picker with strict 12/24-hour parsing and inline validation. This addresses CAL-4526 and fixes #15763.

- **Bug Fixes**
  - Strictly parse user input (h:mma or HH:mm) and show an inline error for invalid times.
  - Add the typed time to the dropdown when it’s not a preset, and preserve the selection on close.
  - Update filtering to respect min/max bounds and include a temporary option for the current custom time.

<sup>Written for commit 48865199158cc992f59c7b87c08230231d7c6f58. Summary will update on new commits.</sup>

### CODE REVIEW

**Review by dhairyashiil — CHANGES_REQUESTED** [review]
@Manas-Kenge Currently the user cannot enter time in a 24 hour format and we dont display it in the dropdown either. However the validation is checking both 12 hour and 24 hour formats, which feels inconsistent.

It would make sense to align the validation with the available 12 hour time format only. Let me know what you think, and also feel free to check if I am missing anything.

refer: [comment](https://github.com/calcom/cal.com/pull/26373/files#r2656587188)

File: packages/features/schedules/components/Schedule.tsx [hunk 1]
```diff
@@ -404,12 +409,35 @@ const TimeRangeField = ({
   );
 };
 
+function parseTimeString(
```
Comment (dhairyashiil) [inline packages/features/schedules/components/Schedule.tsx]: let's add unit test for the parseTimeString function

**Review by dhairyashiil — APPROVED** [review]
LGTM, thank you for the contribution

**Comment by git-user-hub** [comment]
Great – thanks a lot for implementing!

Just a detail:
Would be great if we could also enter 8.21 which will be automatically converted to 08:21 (24h) or 8.21am to 8:21am and 8.21pm to 8:21pm (12h).
Thanks in advance!
