### PR TITLE
fix: make show more banner static > absolute to allow embed auto height

### LINKED ISSUE #13455: [CAL-3048] Show More button being cut off in embed
Show more button in embed is being cut off on embed and not scaling to the correct size

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3048](https://linear.app/calcom/issue/CAL-3048/show-more-button-being-cut-off-in-embed)</sub>

### PR DESCRIPTION
**Pull request by sean-brydon**
fixes: #13455 

.main class that is used for embed height with this enabled and disabled 

Disabled
CleanShot 2024-01-30 at 13 12 51@2x

Enabled
CleanShot 2024-01-30 at 13 12 36@2x

@ UI team - we need to make sure when adding things to booked like this they are statically positioned so that embed can use them also. @Udit-takkar Instant meetings is also in the same boat - i will create an [issue](https://github.com/calcom/cal.com/issues/13456) and fix this <3

### CODE REVIEW

File: packages/features/bookings/Booker/components/HavingTroubleFindingTime.tsx [hunk 1]
```diff
@@ -25,7 +28,7 @@ export function HavingTroubleFindingTime(props: Props) {
   if (props.isScheduleLoading || !props.dayCount) return null;
 
   return (
-    <div className="bg-default border-subtle absolute bottom-[-120px] flex w-full min-w-0 items-center justify-between rounded-[32px] border p-3 text-sm leading-none shadow-sm">
+    <div className="bg-default border-subtle mt-6 flex w-1/2 min-w-0 items-center justify-between rounded-[32px] border p-3 text-sm leading-none shadow-sm lg:w-1/3">
```
Comment (Udit-takkar) [inline packages/features/bookings/Booker/components/HavingTroubleFindingTime.tsx:31]: Not responsive
Screenshot 2024-01-30 at 11 13 21 AM

Comment (sean-brydon) [reply packages/features/bookings/Booker/components/HavingTroubleFindingTime.tsx:31]: Was meant to be hidden here - will push a fix

**Review by Udit-takkar — DISMISSED** [review]
LGTM. just this small issue https://github.com/calcom/cal.com/pull/13457#discussion_r1470618814

File: packages/features/bookings/Booker/components/HavingTroubleFindingTime.tsx (hunk 1 above)
Comment (sean-brydon) [reply packages/features/bookings/Booker/components/HavingTroubleFindingTime.tsx:31]: Addressed -> https://github.com/calcom/cal.com/pull/13457/commits/8d042dadf7722bfb572dbe34fd89602a27742303

**Review by Udit-takkar — APPROVED** [review]

**Comment by hariombalhara** [comment]
Tested embed, looks good 
image
