### PR TITLE
fix: include app data and credentials from DB

### LINKED ISSUE #11040: refactor: show apps of user query
the current implementation of https://github.com/calcom/cal.com/pull/11036 wont scale and will be slow for showing 

we likely need to add the app data to the user query to not slow down

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

- Includes app data in main team user select query to increase performace.
- Adds connectedApps to member obj and uses map to read app data

Fixes #11040 

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Are there environment variables that should be set? No
- What are the minimal test data to have? You can use teampro | teamfree@example accounts with some installed apps.
- What is expected (happy path) to have (input and output)? Visit Seeded team members page and see installed app in each user.
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/lib/server/queries/teams/index.ts [hunk 1]
```diff
@@ -124,43 +133,39 @@ export async function getTeamWithMembers(args: {
...
-        disableImpersonation: obj.disableImpersonation,
-        avatar: `${WEBAPP_URL}/${obj.user.username}/avatar.png`,
-        connectedApps,
-      };
-      return rest;
-    })
-  );
+
+  // This should improve performance saving already app data found.
+  const appDataMap = new Map();
```
Comment (alannnc) [inline packages/lib/server/queries/teams/index.ts:138]: Using Map here to avoid array look up on already fetched appData

File: packages/lib/server/queries/teams/index.ts [hunk 2]
```diff
@@ -32,7 +31,17 @@ export async function getTeamWithMembers(args: {
     selectedCalendars: true,
     credentials: {
       include: {
-        app: true,
+        app: {
+          select: {
+            slug: true,
+            categories: true,
```
Comment (alannnc) [inline packages/lib/server/queries/teams/index.ts:37]: Only fetch required data

File: packages/lib/server/queries/teams/index.ts [hunk 3]
```diff
@@ -124,43 +133,39 @@ export async function getTeamWithMembers(args: {
...
+        const appSlug = cred.app?.slug;
+        let appData = appDataMap.get(appSlug);
+
+        if (!appData) {
+          appData = getAppFromSlug(appSlug);
+          appDataMap.set(appSlug, appData);
+        }
+
+        const isCalendar = cred?.app?.categories.includes("calendar");
+        const externalId = isCalendar ? cred.destinationCalendars[0]?.externalId : undefined;
```
Comment (alannnc) [inline packages/lib/server/queries/teams/index.ts:157]: Getting [0] index should give us the main destinationCalendar, but I don't think this would be more than 1 item here since it's 1 calendar per credential.

**Review by zomars — APPROVED** [review]
Nice improvements. Thank you @alannnc 🙏🏽
