### PR TITLE
Stops content pushing on windows browsers due to overflow-y

### LINKED ISSUE #5383: No padding on settings page
Found a bug? Please fill out the sections below. 👍

### Issue Summary

What it says on the tin.  The icons on the settings page have no padding on the left side.

### Steps to Reproduce

1. go to cal and login
2. Click on settings
3. refresh if bug 5382 is still unfixed

Notice the padding on the left side is missing.  The icons have no space between the edge and the icon.  

### Technical details

Self hosted, main

### PR DESCRIPTION
**Pull request by alishaz-polymath**
## What does this PR do?

Stops content pushing when vertical scrollbar shows up on some windows browsers

Fixes #5383 

[Loom Video](https://www.loom.com/share/ba1d4cd951b44df9a8b4fea71b6f5e93)

**Environment**: Staging(main branch)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

### CODE REVIEW

**Review by sean-brydon — APPROVED** [review]
LGTM - looks super annoying nice fix :D

File: packages/ui/v2/core/layouts/SettingsLayout.tsx [hunk 1]
```diff
@@ -344,7 +344,7 @@ export default function SettingsLayout({
       SettingsSidebarContainer={
         <div
           className={classNames(
-            "fixed inset-y-0 z-50 m-0 h-screen transform overflow-y-scroll border-gray-100 bg-gray-50 transition duration-200 ease-in-out",
+            "fixed inset-y-0 z-50 m-0 h-screen w-56 transform overflow-x-hidden overflow-y-scroll border-gray-100 bg-gray-50 transition duration-200 ease-in-out",
```
Comment (alishaz-polymath) [inline packages/ui/v2/core/layouts/SettingsLayout.tsx:347]: Providing explicit width same as the parent ensures that it isn't pushed around due to overflow-y scrollbar. But it adds a horizontal scrollbar which is hidden using the `overflow-x-hidden` class

**Review by alishaz-polymath — COMMENTED** [review]
Self review added

**Review by hariombalhara — APPROVED** [review]
