### PR TITLE
fix: Hide branding still retains the space

### LINKED ISSUE #13527: [CAL-3090] Hide branding still retains the space
image

Most of the marked space in the above screenshot is retained even after I hide the branding.
The entire element (with margin/padding) should be hidden instead of only the text.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3090](https://linear.app/calcom/issue/CAL-3090/hide-branding-still-retains-the-space)</sub>

### PR DESCRIPTION
**Pull request by laneme**
Hides the `m.span` instead of its children when `hideBranding` is true.

Fixes: https://github.com/calcom/cal.com/issues/13527

### CODE REVIEW

File: packages/features/bookings/Booker/Booker.tsx [hunk 1]
```diff
@@ -483,15 +483,17 @@ const BookerComponent = ({
...
 
-        <m.span
-          key="logo"
-          className={classNames(
-            "-z-10 mb-6 mt-auto pt-6 [&_img]:h-[15px]",
-            hasDarkBackground ? "dark" : "",
-            layout === BookerLayouts.MONTH_VIEW ? "block" : "hidden"
-          )}>
-          {!hideBranding ? <PoweredBy logoOnly /> : null}
-        </m.span>
```
Comment (Udit-takkar) [inline packages/features/bookings/Booker/Booker.tsx:494]: @laneme was this causing any issue?

**Review by Udit-takkar — APPROVED** [review]

**Comment by Udit-takkar** [comment]
@laneme could you sign https://github.com/calcom/cal.com/pull/13579#issuecomment-1931622150 CLA?

**Comment by laneme** [comment]
> @laneme could you sign [#13579 (comment)](https://github.com/calcom/cal.com/pull/13579#issuecomment-1931622150) CLA?

My commits arent linked to an email, i signed but i dont suppose it worked.

If you have access, please copy the code and push yourself directly.
