### PR TITLE
fix: alert message is not positioned properly

### LINKED ISSUE #15994: Alert message is positioned properly in signup page
### Issue Summary

In signup page closing button in alert component not working ans there is no bottom margin on that component
photo_2024-07-31_00-46-36

### Steps to Reproduce

1. Go to signup page
2. Enter previously used username or old email for which there is already an account exists.

### Expected behavior

on clicking the cross the alert should close 

### Other information

_No response_

### Screenshots

_No response_

### Environment

- [X] app.cal.com
- [X] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS:Linux
- Node:20.12.2
- npm: 10.8.0
```

### PR DESCRIPTION
**Pull request by ymohit1603**
## What does this PR do?

Fixes closing symbol functionality in alert component
- Fixes #15994 

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

File: packages/ui/components/alert/Alert.tsx [hunk 1]
```diff
@@ -19,6 +19,12 @@ export interface AlertProps {
 }
 export const Alert = forwardRef<HTMLDivElement, AlertProps>((props, ref) => {
   const { severity, iconClassName, CustomIcon, customIconColor } = props;
+  const [isVisible, setIsVisible] = useState(true);
+  const handleClose = () => {
+    setIsVisible(false);
+  };
+
+  if (!isVisible) return null;
```
Comment (anikdhabal) [inline packages/ui/components/alert/Alert.tsx:27]: Nah, it's fine currently. We don't want to make the alert component closable on click. we have a toast component for that purpose.

**Review by anikdhabal — CHANGES_REQUESTED** [review]

**Review by anikdhabal — APPROVED** [review]
LGTM!
