### PR TITLE
fix: remove check for location

### LINKED ISSUE #13494: [CAL-3067] Daily webhooks not getting triggered
image

Webhooks stops working after 3 consecutive failures (400s, 500s response).

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3066](https://linear.app/calcom/issue/CAL-3066/[cal-3067]-daily-webhooks-not-getting-triggered)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes: https://github.com/calcom/cal.com/issues/13494

Daily webhooks  404 error 

Screenshot 2024-02-01 at 6 03 14 PM

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: apps/web/pages/api/recorded-daily-video.ts [hunk 1]
```diff
@@ -182,7 +181,7 @@ async function handler(req: NextApiRequest, res: NextApiResponse) {
       },
     });
 
-    if (!booking || !(booking.location === DailyLocationType || booking?.location?.trim() === "")) {
```
Comment (Udit-takkar) [inline apps/web/pages/api/recorded-daily-video.ts:185]: Edge case:- Removed this location check because sometime even when location is google meet, zoom and there is some error creating room then cal video is used as fallback. so if you record a meeting on cal video then this webhook will not execute because it's location is not cal video

**Review by keithwillcode — APPROVED** [review]
