### PR TITLE
chore: fixed enterprise warning and description

### LINKED ISSUE #14790: fix consoleUrl
deprecating console, linking to sales instead

### PR DESCRIPTION
**Pull request by PeerRich**
sending people to cal.com/sales instead of console

### CODE REVIEW

**Review by Udit-takkar — COMMENTED** [review]
Screenshot 2024-04-29 at 4 19 34 PM

should we add hyperlink to "please reach out to our sales team" text instead of contact sales button at the end. 

sure, i dont mind. doenst have to be perfect imo.

**Comment by PeerRich** [comment]
> Screenshot 2024-04-29 at 4 19 34 PM
> should we add hyperlink to "please reach out to our sales team" text instead of contact sales button at the end.
> 
> sure, i dont mind. doenst have to be perfect imo.

this is also temporarily until we figured out the console situation

File: packages/features/ee/common/components/LicenseRequired.tsx [hunk 1]
```diff
@@ -41,15 +40,8 @@ const LicenseRequired = ({ children, as = "", ...rest }: LicenseRequiredProps) =
...
-                <Trans i18nKey="enterprise_license_development">
-                  You can test this feature on development mode. For production usage please have an
-                  administrator go to{" "}
-                  <a href={`${WEBAPP_URL}/auth/setup`} className="underline">
-                    /auth/setup
-                  </a>{" "}
-                  to enter a license key.
-                </Trans>
+                {t("enterprise_license_locally")} {t("enterprise_license_sales")}{" "}
+                <a href="https://cal.com/sales">{t("contact_sales")}</a>
```
Comment (PeerRich) [inline packages/features/ee/common/components/LicenseRequired.tsx:44]:
```suggestion
                <a className="underline" href="https://cal.com/sales">{t("contact_sales")}</a>
```

**Review by Udit-takkar — APPROVED** [review]
