### PR TITLE
fix: Issues in custom event name

### LINKED ISSUE #16770: [CAL-4388] Variable {name} in "with event name" for the calendar does not work
Variable {name} in "with event name" for the calendar does not work.
when booked it says: \[object Object\] and Jose Urena.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4388](https://linear.app/calcom/issue/CAL-4388/variable-name-in-with-event-name-for-the-calendar-does-not-work)</sub>

### LINKED ISSUE #18919: [CAL-5086] Issues with Scheduler name variables in custom event name
There are several issues with the scheduler name variables in the custom event name (`/event-types/<id>?tabName=advanced`)

1. If split name is enabled then {name} variable in Custom event name shows as \[object Object\]. We should instead show first name + last name. 
2. If split name is not enabled {Scheduler last name} doesn't work {Scheduler first name} works
3. The variables {Scheduler first name} {Scheduler last name} are missing in the list of available variables: 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-5086](https://linear.app/calcom/issue/CAL-5086/issues-with-scheduler-name-variables-in-custom-event-name)</sub>

### PR DESCRIPTION
**Pull request by anikdhabal**
- Fixes #18919
- Fixes #16770 
- Fixes CAL-5086
- Fixes CAL-4388

### CODE REVIEW

File: packages/features/eventtypes/components/tabs/advanced/CustomEventTypeModal.tsx [hunk 1]
```diff
@@ -152,6 +152,128 @@ const CustomEventTypeModalForm: FC<CustomEventTypeModalFormProps> = (props) => {
...
+            <div
+              className={classNames(
+                "mb-2.5 flex font-normal",
+                customClassNames?.availableVariables?.variableItem?.container
+              )}>
+              <p
+                className={classNames(
+                  "text-subtle ml-1 mr-5 w-32",
+                  customClassNames?.availableVariables?.variableItem?.variableName
+                )}>
```
Comment (anikdhabal) [inline packages/features/eventtypes/components/tabs/advanced/CustomEventTypeModal.tsx:164]: Missing variables back

**Comment by MehulZR** [comment]
Split name not enabled:
image

Split name enabled:
image

File: packages/core/event.ts [hunk 2]
```diff
@@ -81,21 +81,26 @@ export function getEventName(eventNameObj: EventNameObjectType, forAttendeeView
...
-              fieldValue = field?.toString();
-            }
-          }
-          dynamicEventName = dynamicEventName.replace(`{${variable}}`, fieldValue || "");
+    if (!eventNameObj.bookingFields) return;
+
+    const bookingFieldValue = eventNameObj.bookingFields[variable as keyof typeof eventNameObj.bookingFields];
+
+    if (bookingFieldValue) {
+      console.log({ bookingFieldValue });
```
Comment (MehulZR) [inline packages/core/event.ts:89]: Is this intentional?

File: packages/features/eventtypes/components/tabs/advanced/CustomEventTypeModal.tsx [hunk 3]
```diff
@@ -152,6 +152,128 @@ const CustomEventTypeModalForm: FC<CustomEventTypeModalFormProps> = (props) => {
...
+                className={classNames(
+                  "mb-2.5 flex font-normal",
+                  customClassNames?.availableVariables?.variableItem?.container
+                )}>
+                <p
+                  className={classNames(
+                    "text-subtle ml-1 mr-5 w-32",
+                    customClassNames?.availableVariables?.variableItem?.variableName
+                  )}>
+                  {`{Scheduler last name}`}
```
Comment (anikdhabal) [inline packages/features/eventtypes/components/tabs/advanced/CustomEventTypeModal.tsx:246]: @MehulZR As you can see, the last name variable is only available if split name is enabled

File: packages/core/event.ts (hunk 2 above)
Comment (anikdhabal) [reply packages/core/event.ts]: no, thanks

File: packages/features/eventtypes/components/tabs/advanced/CustomEventTypeModal.tsx (hunk 3 above)
Comment (MehulZR) [reply packages/features/eventtypes/components/tabs/advanced/CustomEventTypeModal.tsx:246]: Doesn't it make sense to disable the first name too in Non-split mode?

File: packages/core/event.ts [hunk 4]
```diff
@@ -81,21 +81,25 @@ export function getEventName(eventNameObj: EventNameObjectType, forAttendeeView
...
+
+    const bookingFieldValue = eventNameObj.bookingFields[variable as keyof typeof eventNameObj.bookingFields];
+
+    if (bookingFieldValue) {
+      let fieldValue;
+
+      if (typeof bookingFieldValue === "object") {
+        if ("value" in bookingFieldValue) {
+          fieldValue = bookingFieldValue.value?.toString();
+        } else if (variable === "name" && "firstName" in bookingFieldValue) {
```
Comment (MehulZR) [inline packages/core/event.ts:94]: I thought the intention of this block is for parsing generic custom question. Do we wanna split the parsing name logic in two places?

We are already parsing names here: 
https://github.com/calcom/cal.com/blob/b06a94ab57594689e2b38c61102aebc687f7e244/packages/core/event.ts#L12-L17

Comment (anikdhabal) [reply packages/core/event.ts:94]: It's fine

**Comment by MehulZR** [comment]
@anikdhabal It's still there.

In #18919 it was stated. 
> 2. If split name is not enabled {Scheduler last name} doesn't work {Scheduler first name} works

Are we not considering it now?

image

File: packages/core/event.ts [hunk 5]
```diff
@@ -81,21 +81,25 @@ export function getEventName(eventNameObj: EventNameObjectType, forAttendeeView
...
-            if (field && typeof field === "object" && "value" in field) {
-              fieldValue = field?.value?.toString();
-            } else {
-              fieldValue = field?.toString();
-            }
-          }
-          dynamicEventName = dynamicEventName.replace(`{${variable}}`, fieldValue || "");
+    if (!eventNameObj.bookingFields) return;
+
+    const bookingFieldValue = eventNameObj.bookingFields[variable as keyof typeof eventNameObj.bookingFields];
```
Comment (TusharBhatt1) [inline packages/core/event.ts:86]: This code only works when variable names exactly match booking field keys, which is much more restrictive and may miss many valid replacements.

File: packages/features/eventtypes/components/tabs/advanced/CustomEventTypeModal.tsx [hunk 6]
```diff
@@ -152,6 +152,128 @@ const CustomEventTypeModalForm: FC<CustomEventTypeModalFormProps> = (props) => {
...
+                )}>
+                {`{Scheduler}`}
+              </p>
+              <p
+                className={classNames(
+                  "text-emphasis",
+                  customClassNames?.availableVariables?.variableItem?.variableDescription
+                )}>
+                {t("scheduler_full_name")}
+              </p>
```
[the remark this answers is not in the document]
Comment (anikdhabal) [reply packages/features/eventtypes/components/tabs/advanced/CustomEventTypeModal.tsx:213]: Don't get it

[the remark this answers is not in the document]
Comment (TusharBhatt1) [reply packages/features/eventtypes/components/tabs/advanced/CustomEventTypeModal.tsx:213]: Unconditional and conditional rendering

File: packages/core/event.ts (hunk 5 above)
Comment (anikdhabal) [reply packages/core/event.ts:86]: What do you mean by 'many valid replacements'? In this case, we only need booking field keys.

File: packages/features/eventtypes/components/tabs/advanced/CustomEventTypeModal.tsx (hunk 6 above)
[the remark this answers is not in the document]
Comment (anikdhabal) [reply packages/features/eventtypes/components/tabs/advanced/CustomEventTypeModal.tsx:213]: that's intentional

File: packages/core/event.ts (hunk 5 above)
Comment (TusharBhatt1) [reply packages/core/event.ts:86]: The old code was checking each variable against ALL booking field keys through nested loops
If it only uses exact key matching, then this implementation is right

Comment (anikdhabal) [reply packages/core/event.ts:86]: Yes

**Review by TusharBhatt1 — APPROVED** [review]
