### PR TITLE
fix: Add feedback when user installs app [CAL-2144]

### LINKED ISSUE #10060: [CAL-2144] /apps - no feedback when I click to install an app - results in multiple installs
[76533f8e-a62d-4b59-952f-da70a92fb84c](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/da1597d5-4150-4423-918c-fc04230339e5/76533f8e-a62d-4b59-952f-da70a92fb84c)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2144](https://linear.app/calcom/issue/CAL-2144/apps-no-feedback-when-i-click-to-install-an-app-results-in-multiple)</sub>

### PR DESCRIPTION
**Pull request by joeauyeung**
## What does this PR do?

This PR adds feedback when a user installs an app when the team dropdown selector is rendered. This also prevents users from clicking the install button multiple times.

This is what the loading state will look like:
CleanShot 2023-07-14 at 22 24 16@2x

Fixes # (issue)

## Type of change

  - [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Create a team / org
- Go to the app store
- Click "Install" on the QR code app (used as an example)
- Choose either the test account or team
    - The loading state should appear
    - You should not be able to close the dropdown menu until the install process returns
- Repeat this for the QR code app page

## Mandatory Tasks

  - [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

File: apps/web/components/apps/App.tsx [hunk 1]
```diff
@@ -441,7 +443,16 @@ const InstallAppButtonChild = ({
         </Button>
       </DropdownMenuTrigger>
       <DropdownMenuPortal>
-        <DropdownMenuContent>
+        <DropdownMenuContent
+        onInteractOutside={(event) => {
+          if (mutation.isLoading) event.preventDefault();
+        }}
```
Comment (joeauyeung) [inline apps/web/components/apps/App.tsx:449]: This prevents the user from closing the dropdown menu until adding the app resolves with a success + redirect or an error message

File: apps/web/components/apps/App.tsx [hunk 2]
```diff
@@ -441,7 +443,16 @@ const InstallAppButtonChild = ({
...
+        >
+          {mutation.isLoading && (
+              <div className="z-1 fixed inset-0 flex items-center justify-center bg-black bg-opacity-50">
+                <Spinner />
+              </div>
+            )}
```
Comment (joeauyeung) [inline apps/web/components/apps/App.tsx:455]: Adding the div above the dropdown menu should prevent users from clicking additional teams when installing an app and waiting for a response. This also informs the user that their chosen install action is currently being processed.

**Review by keithwillcode — APPROVED** [review]
Looks good
