### PR TITLE
fix: Add version to embed.js and preview.js

### LINKED ISSUE #16025: [CAL-4094] Add version to embed.js
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4094](https://linear.app/calcom/issue/CAL-4094/add-version-to-embedjs)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?
Fixes #16025 
Fixes CAL-4094

Add version to embed.js and preview.js

image

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?
- Simply do yarn build and verify version in dist

### CODE REVIEW

File: packages/embeds/embed-core/src/embed.ts [hunk 1]
```diff
@@ -52,6 +52,7 @@ if (!globalCal || !globalCal.q) {
 // TODO: Ideally it should be the version as per package.json and then it can be renamed to version.
 // But because it is built on local machine right now, it is much more reliable to have the commit hash.
 globalCal.fingerprint = process.env.EMBED_PUBLIC_EMBED_FINGER_PRINT as string;
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed.ts:54]: Still keeping the fingerprint as that confirms the commit used to build it. Version could still go wrong but fingerprint can't be wrong.

File: packages/embeds/vite.config.js [hunk 2]
```diff
@@ -6,6 +6,8 @@ process.env.EMBED_PUBLIC_WEBAPP_URL = process.env.NEXT_PUBLIC_WEBAPP_URL;
 process.env.EMBED_PUBLIC_EMBED_LIB_URL = process.env.NEXT_PUBLIC_EMBED_LIB_URL;
 // eslint-disable-next-line turbo/no-undeclared-env-vars
 process.env.EMBED_PUBLIC_EMBED_FINGER_PRINT = process.env.NEXT_PUBLIC_EMBED_FINGER_PRINT;
+// eslint-disable-next-line turbo/no-undeclared-env-vars
+process.env.EMBED_PUBLIC_EMBED_VERSION = process.env.NEXT_PUBLIC_EMBED_VERSION;
```
Comment (hariombalhara) [inline packages/embeds/vite.config.js:10]: Following in the footprints of `EMBED_PUBLIC_EMBED_FINGER_PRINT` to add this new env variable.

**Review by zomars — APPROVED** [review]
