### PR TITLE
fix: Booker shows toggle external calendar on external links

### LINKED ISSUE #13393: [CAL-3014] regression: show "Overlay my calendar" for external links and "Need help?" for my own
this button used to work correctly:

CleanShot 2024-01-24 at 17 50 38@2x

correct:

* my own link: "Need help?"
* everyone elses link: "Overlay my calendar"

make sure to check all layouts (monthly, weekly, column view)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3014](https://linear.app/calcom/issue/CAL-3014/regression-show-overlay-my-calendar-for-external-links-and-need-help)</sub>

### PR DESCRIPTION
**Pull request by ThyMinimalDev**
## What does this PR do?

Fixes #13393 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- go on your booking public page, shows need help button
- go on somebody else's booking public page, shows the overlay calendar button

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: packages/features/bookings/Booker/Booker.tsx [hunk 1]
```diff
@@ -362,7 +364,7 @@ const BookerComponent = ({
                     "bg-default dark:bg-muted sticky top-0 z-10"
                 )}>
                 <Header
-                  isMyLink={Boolean(username === event?.data?.owner?.username)}
```
Comment (keithwillcode) [inline packages/features/bookings/Booker/Booker.tsx:365]: So that means somehow `isMyLink` was getting set to true somehow?

**Review by keithwillcode — APPROVED** [review]
