### PR TITLE
fix: team availability data table scrolling

### LINKED ISSUE #13023: [CAL-2864] Team availability slider overflow
Slider has overflow at unconventional screen sizes 
https://github.com/calcom/cal.com/assets/55134778/6678eacd-4592-4b8a-a0c0-dbf36344ca11

<sub>[CAL-2864](https://linear.app/calcom/issue/CAL-2864/team-availability-slider-overflow)</sub>

### PR DESCRIPTION
**Pull request by PeerRich**
https://github.com/calcom/cal.com/assets/8019099/f6995149-074f-431b-a8a3-999870ddbfc1

### CODE REVIEW

File: packages/features/shell/Shell.tsx [hunk 1]
```diff
@@ -976,7 +976,7 @@ function SideBar({ bannersHeight, user }: SideBarProps) {
                     <div className="flex">{t(item.name)}</div>
                   </span>
                 ) : (
-                  <SkeletonText className="h-[20px] w-full" />
+                  <SkeletonText style={{ width: `${item.name.length * 10}px` }} className="h-[20px]" />
```
Comment (PeerRich) [inline packages/features/shell/Shell.tsx:979]:
```suggestion
                  <SkeletonText className="h-[20px] w-full" />
```

**Review by emrysal — APPROVED** [review]
Tailwind foo
