### PR TITLE
fix: remove double call on useSchedule()

### LINKED ISSUE #11138: [CAL-2404] getSchedule called twice on booking page
Due to recent changes getSchedule get called twice on booking page, we need to investigate further down.

related changes to have in mind: [https://github.com/calcom/cal.com/pull/9815](https://github.com/calcom/cal.com/pull/9815)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2404](https://linear.app/calcom/issue/CAL-2404/getschedule-called-twice-on-booking-page)</sub>

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

Remove double call on useSchedule

Fixes #11138

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Are there environment variables that should be set? No.
- What are the minimal test data to have? Test data any teampro account and 1 event type
- What is expected (happy path) to have (input and output)?  Go to /booking/teampro/30min and see only 1 network call
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/features/bookings/Booker/Booker.tsx [hunk 1]
```diff
@@ -109,7 +109,7 @@ const BookerComponent = ({
       ? totalWeekDays
       : 0;
 
-  //Taking one more avaliable slot(extraDays + 1) to claculate the no of days in between, that next and prev button need to shift.
+  // Taking one more available slot(extraDays + 1) to calculate the no of days in between, that next and prev button need to shift.
```
Comment (alannnc) [inline packages/features/bookings/Booker/Booker.tsx:112]: Typo

File: packages/features/schedules/lib/use-schedule/useSchedule.ts [hunk 2]
```diff
@@ -31,7 +31,7 @@ export const useSchedule = ({
   const nextMonthDayjs = monthDayjs.add(monthCount ? monthCount : 1, "month");
   // Why the non-null assertions? All of these arguments are checked in the enabled condition,
   // and the query will not run if they are null. However, the check in `enabled` does
-  // no satisfy typscript.
+  // no satisfy typescript.
```
Comment (alannnc) [inline packages/features/schedules/lib/use-schedule/useSchedule.ts:34]: typo

File: packages/features/bookings/Booker/Booker.tsx [hunk 3]
```diff
@@ -93,7 +93,7 @@ const BookerComponent = ({
   );
 
   const date = dayjs(selectedDate).format("YYYY-MM-DD");
-  const schedule = useScheduleForEvent({ prefetchNextMonth: true });
```
Comment (alannnc) [inline packages/features/bookings/Booker/Booker.tsx:96]: remove to favour our first useSchedule call

**Review by zomars — APPROVED** [review]
Code LGTM
