### PR TITLE
replaced webhook icon with actual webhook logo

### LINKED ISSUE #6143: [CAL-637] /event-types wrong webhooks icon
this

should be

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-637](https://linear.app/calcom/issue/CAL-637/event-types-wrong-webhooks-icon)</sub>

### PR DESCRIPTION
**Pull request by PeerRich**
before

CleanShot 2022-12-22 at 14 29 25

after

CleanShot 2022-12-22 at 14 28 52

### CODE REVIEW

File: apps/web/components/eventtype/EventTeamWebhooksTab.tsx [hunk 1]
```diff
@@ -9,6 +9,7 @@ import { useLocale } from "@calcom/lib/hooks/useLocale";
 import { Webhook } from "@calcom/prisma/client";
 import { trpc } from "@calcom/trpc/react";
 import { Button, Dialog, DialogContent, EmptyScreen, Icon, showToast } from "@calcom/ui";
+import {TbWebhook} from 'react-icons/tb';
```
Comment (zomars) [inline apps/web/components/eventtype/EventTeamWebhooksTab.tsx:12]:
```suggestion
import { TbWebhook } from 'react-icons/tb';
```

File: apps/web/components/eventtype/EventTypeSingleLayout.tsx [hunk 2]
```diff
@@ -33,6 +33,7 @@ import {
 
 import { ClientSuspense } from "@components/ClientSuspense";
 import { EmbedButton, EmbedDialog } from "@components/Embed";
+import {TbWebhook} from 'react-icons/tb';
```
Comment (zomars) [inline apps/web/components/eventtype/EventTypeSingleLayout.tsx:36]:
```suggestion
import { TbWebhook } from 'react-icons/tb';
```

**Review by zomars — APPROVED** [review]
Fixed linting

Ship it
