### PR TITLE
fix: Bring back dir attr using Intl

### LINKED ISSUE #11805: [CAL-2607] Spacing problems due to lack of `dir="ltr"` attribute
Heads up @grzpab this PR is causing spacing issues on main since we're not setting the html `dir="ltr"` attribute anymore. We're working on a fix.

EDIT: 

image
image

The removal of this is the main cause:

image

_Originally posted by @zomars in https://github.com/calcom/cal.com/issues/11534#issuecomment-1756179968_
            

<sub>[CAL-2607](https://linear.app/calcom/issue/CAL-2607/spacing-problems-due-to-lack-of-dir=ltr-attribute)</sub>

### PR DESCRIPTION
**Pull request by emrysal**
## What does this PR do?

Uses experimental intl features to determine dir, but as it's server only we can depend on it for as long our nodejs version remains the same. Added an internal error to be very vocal when this changes.

Fixes #11805

### CODE REVIEW

File: apps/web/pages/_document.tsx [hunk 1]
```diff
@@ -50,9 +50,20 @@ class MyDocument extends Document<Props> {
 
     const nonceParsed = z.string().safeParse(this.props.nonce);
     const nonce = nonceParsed.success ? nonceParsed.data : "";
+
+    const intlLocale = new Intl.Locale(newLocale);
+    // INFO: Typescript does not know about the Intl.Locale textInfo attribute
+    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
+    // @ts-expect-error
```
Comment (zomars) [inline apps/web/pages/_document.tsx:57]: ts-expect-error doesn't need lint bypassing

```suggestion
    // @ts-expect-error INFO: Typescript does not know about the Intl.Locale textInfo attribute
```

**Review by zomars — APPROVED** [review]
Ship it
