### PR TITLE
fix: booking error in case of no calendar credential but stray destinationCalendar

### LINKED ISSUE #12464: [CAL-2749] Could not book the meeting. Cannot read properties of undefined (reading 'appId')
### Issue Summary

Created a new account. Coud not book any slot

### Steps to Reproduce

1. go to the URL : [https://cal.com/romain.debru-gmail/30min?month=2023-12&date=2023-12-22&slot=2023-12-22T08%3A30%3A00.000Z](https://cal.com/romain.debru-gmail/30min?month=2023-12&date=2023-12-22&slot=2023-12-22T08%3A30%3A00.000Z)
2. Try to book any available slot
   3

### Actual Results

image

* This is an ideal result that the system should get after the tests are performed

### Technical details

* Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
* Node.js version
* Anything else that you think could be an issue.

### Evidence

* How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2749](https://linear.app/calcom/issue/CAL-2749/could-not-book-the-meeting-cannot-read-properties-of-undefined-reading)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #12464

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
1. Install Google Calendar
2. Ensure that it is selected as destinationCalendar for an event
3. Set credentialId to null for the destinationCalendar
4. Delete the Credential - Ensure that app isn't opened in any of the tabs(going to app pages would cleanup the invalid destinationCalendar)
5. Try and do a booking and you would be able to replicate the error.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by hariombalhara** [comment]
Current dependencies on/for this PR:
* main
  * **PR #12680** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/12680?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/calcom/cal.com/12680?utm_source=stack-comment).

File: packages/core/EventManager.ts [hunk 1]
```diff
@@ -574,24 +569,16 @@ export default class EventManager {
             (c) => c.type === destination.integration
           );
           // It might not be the first connected calendar as it seems that the order is not guaranteed to be ascending of credentialId.
-          const firstCalendarCredential = destinationCalendarCredentials[0];
+          const firstCalendarCredential = destinationCalendarCredentials[0] as
```
Comment (hariombalhara) [inline packages/core/EventManager.ts:572]: It could be undefined as well. So, explicitly assert it as TypeScript by default can't do that.

File: packages/core/EventManager.ts [hunk 2]
```diff
@@ -574,24 +569,16 @@ export default class EventManager {
...
-
-          log.warn(
-            "No credentialId found for destination calendar, falling back to first found calendar",
-            safeStringify({
-              destination: getPiiFreeDestinationCalendar(destination),
-              firstConnectedCalendar: getPiiFreeCredential(firstCalendarCredential),
-            })
-          );
-
-          createdEvents.push(await createEvent(firstCalendarCredential, event));
```
Comment (hariombalhara) [inline packages/core/EventManager.ts:594]: We can't use `firstCalendarCredential` if it's undefined. So, this code was stray and invalid now.

**Review by CarinaWolli — APPROVED** [review]
didn't test but code looks good to me
