### PR TITLE
fix: made text dependent on host's refund policy by conditionally rendering text.

### LINKED ISSUE #20135: [CAL-5315] Make text dependent on host's refund policy
@milospuac said:

> Can we make this text dependable on the refund policy of the host, this is confusing

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-5315](https://linear.app/calcom/issue/CAL-5315/make-text-dependent-on-hosts-refund-policy)</sub>

### PR DESCRIPTION
**Pull request by romitg2**
- Fixes #20135  (GitHub issue number)
- Fixes CAL-5315 (Linear issue number - should be visible at the bottom of the GitHub issue description)

#### what is the issue?

- On cancellation of booking, it shows refund is processing irrespective of refund policy.

#### what does this PR fixes:
- On cancellation, conditionally renders weather refund is process or refund won't given based on refund policy.

#### how i fixed the issue?

1. first we need refund policy data, but initially we were not parsing that data, so i changed it to parse it with apps (we need stripe app data)
Screenshot 2025-04-06 at 7 09 01 PM

2.  initially we only had one text that refund is processing, so i added ".. no refund .." text.
Screenshot 2025-04-06 at 7 11 31 PM

3.  then based on this event's refund policy data i conditionally rendered the text. 
Screenshot 2025-04-06 at 7 10 35 PM

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- you should create paid event with stripe app with different refund policies, and then book event and cancel it.

### CODE REVIEW

File: apps/web/modules/bookings/views/bookings-single-view.tsx [hunk 1]
```diff
@@ -505,7 +506,18 @@ export default function Success(props: PageProps) {
...
+                                if (
+                                  refundPolicy === RefundPolicy.DAYS ||
+                                  refundPolicy === RefundPolicy.ALWAYS
+                                ) {
+                                  return t("booking_with_payment_cancelled_already_paid");
+                                }
+                                if (refundPolicy === RefundPolicy.NEVER) {
+                                  return t("booking_with_payment_cancelled_no_refund");
+                                }
+                              })()}
```
Comment (TusharBhatt1) [inline apps/web/modules/bookings/views/bookings-single-view.tsx:520]: I guess there are more conditions to it , you can take a look at `processPaymentRefund.test.ts`

**Review by TusharBhatt1 — CHANGES_REQUESTED** [review]
Added comments

File: apps/web/modules/bookings/views/bookings-single-view.tsx (hunk 1 above)
Comment (romitg2) [reply apps/web/modules/bookings/views/bookings-single-view.tsx:520]: Yes there will be, 
1. when the RefundPolicy is DAYS and we are cancelling after more days passed than RefundPolicy allows.
2. when no TeamId or EventType owner found.

- other checks weather there will be refund or not will be processed on backend asynchronously based on weather booking exist in database, payment credentials exist or not, so we won't handle those case on frontend and we'll show "refund is processing..." in those cases. 

is there anything i am missing?

File: apps/web/public/static/locales/en/common.json [hunk 2]
```diff
@@ -1981,6 +1981,7 @@
   "booking_with_payment_cancelled": "Paying for this event is no longer possible",
   "booking_with_payment_cancelled_already_paid": "A refund for this booking payment is on its way.",
   "booking_with_payment_cancelled_refunded": "This booking payment has been refunded.",
+  "booking_with_payment_cancelled_no_refund": "This booking payment will not be refunded.",
   "booking_confirmation_failed": "Booking confirmation failed",
```
[the remark this answers is not in the document]
Comment (romitg2) [reply apps/web/public/static/locales/en/common.json:1985]: Yes, changing it!

[the remark this answers is not in the document]
Comment (romitg2) [reply apps/web/public/static/locales/en/common.json:1986]: @TusharBhatt1 Fixed!

File: apps/web/modules/bookings/views/bookings-single-view.tsx [hunk 3]
```diff
@@ -505,7 +506,37 @@ export default function Success(props: PageProps) {
...
                               !props.paymentStatus.refunded &&
-                              t("booking_with_payment_cancelled_already_paid")}
+                              (() => {
+                                const refundPolicy = eventType?.metadata?.apps?.stripe?.refundPolicy;
+                                const refundDaysCount = eventType?.metadata?.apps?.stripe?.refundDaysCount;
+
+                                // Handle missing team or event type owner
+                                if (!eventType?.teamId && !eventType?.owner) {
+                                  return t("booking_with_payment_cancelled_no_refund");
+                                }
```
Comment (TusharBhatt1) [inline apps/web/modules/bookings/views/bookings-single-view.tsx:516]: Why we are doing this ?

Comment (romitg2) [reply apps/web/modules/bookings/views/bookings-single-view.tsx:516]: Just an additional check. 
I also think this check is unnecessary, but we were having this check in `packages/lib/payment/processPaymentRefund.ts`. so i added it. 

https://github.com/calcom/cal.com/blob/2b7a87a34ccd19fd10689ae9c21a0bd0565e2681/packages/lib/payment/processPaymentRefund.ts#L29

File: apps/web/public/static/locales/en/common.json [hunk 4]
```diff
@@ -1981,6 +1981,8 @@
   "booking_with_payment_cancelled": "Paying for this event is no longer possible",
   "booking_with_payment_cancelled_already_paid": "A refund for this booking payment is on its way.",
   "booking_with_payment_cancelled_refunded": "This booking payment has been refunded.",
+  "booking_with_payment_cancelled_no_refund": "As per the refund policy, booking payment is non-refundable.",
```
Comment (TusharBhatt1) [inline apps/web/public/static/locales/en/common.json:1984]:
```suggestion
  "booking_with_payment_cancelled_no_refund": "As per the refund policy of this event , booking payment is non-refundable.",
```

File: apps/web/public/static/locales/en/common.json [hunk 5]
```diff
@@ -1981,6 +1981,8 @@
...
+  "booking_with_payment_cancelled_refund_window_expired": "The refund window has expired, so booking payment is non-refundable.",
```
Comment (TusharBhatt1) [inline apps/web/public/static/locales/en/common.json:1985]:
```suggestion
  "booking_with_payment_cancelled_refund_window_expired": "The refund window for this event has expired, so booking payment is non-refundable.",
```

**Review by TusharBhatt1 — DISMISSED** [review]

File: apps/web/modules/bookings/views/bookings-single-view.tsx [hunk 6]
```diff
@@ -507,7 +508,37 @@ export default function Success(props: PageProps) {
                               t("booking_with_payment_cancelled")}
                             {props.paymentStatus.success &&
                               !props.paymentStatus.refunded &&
-                              t("booking_with_payment_cancelled_already_paid")}
+                              (() => {
+                                const refundPolicy = eventType?.metadata?.apps?.stripe?.refundPolicy;
+                                const refundDaysCount = eventType?.metadata?.apps?.stripe?.refundDaysCount;
+
+                                // Handle missing team or event type owner
```
Comment (TusharBhatt1) [inline apps/web/modules/bookings/views/bookings-single-view.tsx:515]:
```suggestion
                                // Handle missing team or event type owner (same in processPaymentRefund.ts)
```

**Review by TusharBhatt1 — APPROVED** [review]
