### PR TITLE
fix: Recurring Booking - Check for conflicts on first 2 slots only

### LINKED ISSUE #11654: [CAL-2563] recurring events: only check for 2 recurrences for conflict, not all of them
lets only check 2 recurrences in advanced, not N

if you are booking an event for 12 weeks, check for 2 weeks, not all 12.

this will make more recurring bookings pass

downside: you recurring event may conflict with your calendar in 3 weeks, but this is fine because people offering recurring events typically clear their schedule anyway:

i.e.: personal tennis training is always Monday 5PM

<sub>[CAL-2563](https://linear.app/calcom/issue/CAL-2563/recurring-events-only-check-for-2-recurrences-for-conflict-not-all-of)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?
Fixes #11654
Demo - https://www.loom.com/share/ed90fa7b3c334d249fab2cf716752668

Also, adds a recurring booking test that verifies
- rrule in ics file

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
See the loom

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: tests/libs/__mocks__/prisma.ts [hunk 1]
```diff
@@ -46,35 +45,6 @@ const handlePrismockBugs = () => {
...
-        if (or.startTime?.lte) {
-          or.startTime.lte = or.startTime.lte.toISOString ? or.startTime.lte.toISOString() : or.startTime.lte;
-        }
-        if (or.endTime?.gte) {
-          or.endTime.lte = or.endTime.gte.toISOString ? or.endTime.gte.toISOString() : or.endTime.gte;
-        }
-        if (or.endTime?.lte) {
-          or.endTime.lte = or.endTime.lte.toISOString ? or.endTime.lte.toISOString() : or.endTime.lte;
-        }
-      });
```
Comment (hariombalhara) [inline tests/libs/__mocks__/prisma.ts:74]: Handled in a better way here https://github.com/calcom/cal.com/pull/11774/files#diff-8a93958cee6c90b2db64a192155f09e89cff776205469e1102a781b25c08ffecR272

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 2]
```diff
@@ -407,22 +403,7 @@ async function ensureAvailableUsers(
...
-        recurringDatesInfo.allRecurringDates
-      ) {
-        const allBookingDates = recurringDatesInfo.allRecurringDates.map((strDate) => new Date(strDate));
-        // Go through each date for the recurring event and check if each one's availability
-        // DONE: Decreased computational complexity from O(2^n) to O(n) by refactoring this loop to stop
-        // running at the first unavailable time.
-        let i = 0;
-        while (!foundConflict && i < allBookingDates.length) {
-          foundConflict = checkForConflicts(bufferedBusyTimes, allBookingDates[i++], duration);
-        }
```
Comment (hariombalhara) [inline packages/features/bookings/lib/handleNewBooking.ts:422]: It was dead code as I mentioned here https://github.com/calcom/cal.com/pull/11747/files#r1349689802

File: apps/web/pages/api/book/recurring-event.ts [hunk 3]
```diff
@@ -49,11 +51,14 @@ async function handler(req: NextApiRequest & { userId?: number }, res: NextApiRe
...
       isNotAnApiCall: true,
+      skipAvailabilityCheck: key >= numSlotsToCheckForAvailability,
     });
 
     createdBookings.push(eachRecurringBooking);
   }
   return createdBookings;
 }
 
+export const handleRecurringEventBooking = handler;
```
Comment (hariombalhara) [inline apps/web/pages/api/book/recurring-event.ts:62]: Make it testable.

File: packages/features/bookings/lib/handleNewBooking/test/recurring-event.test.ts [hunk 4]
```diff
@@ -0,0 +1,804 @@
...
+              },
+            ],
+          });
+
+          expectBookingCreatedWebhookToHaveBeenFired({
+            booker,
+            organizer,
+            location: "integrations:daily",
+            subscriberUrl: "http://my-webhook.example.com",
+            //FIXME: File a bug - All recurring bookings seem to have the same URL. They should have same CalVideo URL which could mean that future recurring meetings would have already expired by the time they are needed.
```
Comment (hariombalhara) [inline packages/features/bookings/lib/handleNewBooking/test/recurring-event.test.ts:200]:
```suggestion
            //FIXME: All recurring bookings seem to have the same URL. https://github.com/calcom/cal.com/issues/11955
```

**Comment by ThyMinimalDev** [comment]
Screenshot 2023-11-09 at 11 16 27
failing unit tests

File: apps/web/pages/api/book/recurring-event.ts [hunk 5]
```diff
@@ -49,11 +51,14 @@ async function handler(req: NextApiRequest & { userId?: number }, res: NextApiRe
 
     const eachRecurringBooking = await handleNewBooking(recurringEventReq, {
       isNotAnApiCall: true,
+      skipAvailabilityCheck: key >= numSlotsToCheckForAvailability,
```
Comment (ThyMinimalDev) [inline apps/web/pages/api/book/recurring-event.ts:54]: just to make sure, the skipAvailabilityCheck will be false for 3 iterations of the loop, it's a bit misleading with the name and value of numSlotsToCheckForAvailability. is it wanted ?

Comment (hariombalhara) [reply apps/web/pages/api/book/recurring-event.ts:54]: No, I think there is some confusion. 

0>=2 & 1>=2 are the only values for which it would be false
2>=2 and 3>=2...... and all other values will have truthy value.

**Comment by hariombalhara** [comment]
> Screenshot 2023-11-09 at 11 16 27 failing unit tests

Ah fixing these. Looks like they started failing after  a merge from main.

File: apps/web/test/utils/bookingScenario/expects.ts [hunk 6]
```diff
@@ -348,16 +348,19 @@ export function expectSuccessfulBookingCreationEmails({
...
-        {
-          href: `${bookingUrlOrigin}/reschedule/${booking.uid}`,
-          text: "reschedule",
-        },
-        {
-          href: `${bookingUrlOrigin}/booking/${booking.uid}?cancel=true&allRemainingBookings=false`,
-          text: "cancel",
-        },
-      ],
+      links: recurrence
```
Comment (hariombalhara) [inline apps/web/test/utils/bookingScenario/expects.ts:351]: Recurrent booking email and non-recurrent booking emails  have different links

File: apps/web/test/utils/bookingScenario/expects.ts [hunk 7]
```diff
@@ -396,16 +399,19 @@ export function expectSuccessfulBookingCreationEmails({
...
+        ? [
+            {
+              href: `${bookingUrlOrigin}/booking/${booking.uid}?cancel=true&allRemainingBookings=true`,
```
Comment (hariombalhara) [inline apps/web/test/utils/bookingScenario/expects.ts:405]: Recurring booking email as` allRemainingBookings=true` otherwise it's false

File: apps/web/pages/api/book/recurring-event.ts [hunk 8]
```diff
@@ -13,29 +13,31 @@ async function handler(req: NextApiRequest & { userId?: number }, res: NextApiRe
...
-            prev[curr.type].failures += curr.failures;
-            prev[curr.type].success += curr.success;
-          } else {
-            prev[curr.type] = curr;
-          }
-          return prev;
-        }, {} as { [key: string]: AppsStatus });
-      appsStatus = Object.values(calcAppsStatus);
-    }
+    // Disable AppStatus in Recurring Booking Email as it requires us to iterate backwards to be able to compute the AppsStatus for all the bookings except the very first slot and then send that slot's email with statuses
```
Comment (hariombalhara) [inline apps/web/pages/api/book/recurring-event.ts:24]: More consensus on getting it removed https://threads.com/thread/34544288912/34544374482?s=rQRaYwqw649z3FYeTDjiZy

File: apps/web/pages/api/book/recurring-event.ts (hunk 5 above)
Comment (ThyMinimalDev) [reply apps/web/pages/api/book/recurring-event.ts:54]: haha yeah my bad I read this too fast

**Review by ThyMinimalDev — APPROVED** [review]
