### PR TITLE
fix: multi-line formatted correctly for sms

### LINKED ISSUE #21679: Workflow editor does not keep the format for sms workflows after saving
Workflow editor does not keep the format for sms workflows after saving

### PR DESCRIPTION
**Pull request by chaitanyya**
## What does this PR do?

Fixes the issue where the text editor for SMS workflow doesn't persist new lines post saving even though they are recorded in the content.

- Fixes #21679 (GitHub issue number)
- Fixes [CAL-5890](https://linear.app/calcom/issue/CAL-5890/workflow-editor-does-not-keep-the-format-for-sms-workflows-after)

## Visual Demo

demo

## Mandatory Tasks

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). N/A
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Create a workflow with SMS task
- Save the text with line breaks
- Save the workflow
- Revisit the page or reload
- The line breaks are handled correctly

    

---

## Summary by cubic
Fixed an issue where SMS workflow text lost line breaks after saving, so multi-line formatting is now preserved.

### CODE REVIEW

File: packages/ui/components/editor/plugins/ToolbarPlugin.tsx [hunk 1]
```diff
@@ -364,11 +365,13 @@ export default function ToolbarPlugin(props: TextEditorProps) {
...
   useEffect(() => {
-    if (props.setFirstRender) {
+    if (props.setFirstRender && !isInitialized.current) {
+      isInitialized.current = true;
       props.setFirstRender(false);
       editor.update(() => {
         const parser = new DOMParser();
-        const dom = parser.parseFromString(props.getText(), "text/html");
+        const content = props.getText().replace(/\n/g, "<br>");
+        const dom = parser.parseFromString(content, "text/html");
```
Comment (Devanshusharma2005) [inline packages/ui/components/editor/plugins/ToolbarPlugin.tsx:374]: Tests units are failing, address this issue, marking it draft until then, feel free to rfr.

**Review by Devanshusharma2005 — CHANGES_REQUESTED** [review]

File: packages/ui/components/editor/plugins/ToolbarPlugin.tsx (hunk 1 above)
Comment (chaitanyya) [reply packages/ui/components/editor/plugins/ToolbarPlugin.tsx:374]: Thanks!

File: packages/ui/components/editor/Editor.test.tsx [hunk 2]
```diff
@@ -7,7 +7,7 @@ import type { TextEditorProps } from "./types";
 
 describe("Editor", () => {
   const defaultProps: TextEditorProps = {
-    getText: vi.fn(),
+    getText: vi.fn(() => ""),
```
Comment (chaitanyya) [inline packages/ui/components/editor/Editor.test.tsx:10]: We should mock the correct behavior by returning a string, it was returning undefined earlier.

**Review by Devanshusharma2005 — APPROVED** [review]
LGTM.

**Review by CarinaWolli — APPROVED** [review]
Thank you @chaitanyya for fixing this 🙏
