### PR TITLE
Hotfix/caldav reschedule jsonerror

### LINKED ISSUE #5221: [CAL-254] Nextcloud CalDAV reschedule fails
Nextcloud CalDAV rescheduling fails (reschedules in Cal but not in the connected calendar) and cancellation doesn't remove the event from the calendar

> From [Linear-GitHub Sync](https://synclinear.com)

### PR DESCRIPTION
**Pull request by alishaz-polymath**
## What does this PR do?

- Fixes json end of line error when rescheduling (can be easily recreated using a CalDAV service that doesn't return any content when using update)
- Fixes reschedule for NextCloud (and potentially other services which function on similar iCal string standard
- Fixes reschedule for Fastmail

Fixes #5221 #4205

[Loom](https://www.loom.com/share/a62fd169f66a4fb49db3bb2846e4ebd7)

**Environment**: Staging(main branch)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

File: packages/lib/CalendarService.ts [hunk 1]
```diff
@@ -189,21 +189,46 @@ export default abstract class BaseCalendarService implements Calendar {
       }
 
       const eventsToUpdate = events.filter((e) => e.uid === uid);
+      let ev = eventsToUpdate[0];
```
Comment (alannnc) [inline packages/lib/CalendarService.ts:192]:
```suggestion
      let [event] = eventsToUpdate;
```
NIT: We can try to be more explicit with variable naming.

File: packages/lib/CalendarService.ts [hunk 2]
```diff
@@ -189,21 +189,46 @@ export default abstract class BaseCalendarService implements Calendar {
...
       return Promise.all(
         eventsToUpdate.map((e) => {
+          ev = e;
```
Comment (alannnc) [inline packages/lib/CalendarService.ts:195]:
```suggestion
        eventsToUpdate.map(({eventItem) => {
          event = eventItem;
```
Here we change e for -> eventItem as some people can use e as error sometimes. With this change we add more readability.

File: packages/lib/CalendarService.ts [hunk 3]
```diff
@@ -189,21 +189,46 @@ export default abstract class BaseCalendarService implements Calendar {
...
               url: e.url,
-              data: iCalString,
+              data: iCalString?.replace(/METHOD:[^\r\n]+\r\n/g, ""),
               etag: e?.etag,
             },
             headers: this.headers,
           });
         })
-      ).then((p) => p.map((r) => r.json() as unknown as NewCalendarEventType));
+      ).then((parameter) =>
```
Comment (alannnc) [inline packages/lib/CalendarService.ts:205]: we receive a parameter but what kind of parameter we receive?

**Review by alannnc — DISMISSED** [review]
Whops it's a draft. Left some nit comments.

**Comment by alishaz-polymath** [comment]
> Whops it's a draft. Left some nit comments.

Haha, that's okay. The points were valid nonetheless, however, it was far from finished 😉

File: packages/lib/CalendarService.ts [hunk 4]
```diff
@@ -190,30 +190,56 @@ export default abstract class BaseCalendarService implements Calendar {
 
       const eventsToUpdate = events.filter((e) => e.uid === uid);
       return Promise.all(
-        eventsToUpdate.map((e) => {
+        eventsToUpdate.map((eventItem) => {
+          event = eventItem;
```
Comment (alishaz-polymath) [inline packages/lib/CalendarService.ts:194]: Update the value of `event` to persist the properties and use them in `.then`

File: packages/lib/CalendarService.ts [hunk 5]
```diff
@@ -190,30 +190,56 @@ export default abstract class BaseCalendarService implements Calendar {
...
           return updateCalendarObject({
             calendarObject: {
-              url: e.url,
-              data: iCalString,
-              etag: e?.etag,
+              url: event.url,
+              data: iCalString?.replace(/METHOD:[^\r\n]+\r\n/g, ""),
```
Comment (alishaz-polymath) [inline packages/lib/CalendarService.ts:198]: Adds the adjustment to comply with iCal2.0 standard which various service providers like nextcloud and fastmail expect

File: packages/lib/CalendarService.ts [hunk 6]
```diff
@@ -190,20 +190,44 @@ export default abstract class BaseCalendarService implements Calendar {
...
+              etag: event?.etag,
             },
             headers: this.headers,
           });
         })
-      ).then((p) => p.map((r) => r.json() as unknown as NewCalendarEventType));
+      ).then((responses) =>
+        responses.map((response) => {
+          if (response.status > 199 && response.status < 207) {
```
Comment (alishaz-polymath) [inline packages/lib/CalendarService.ts:206]: Confirms if the update call went through successfully. Some providers return updated data while the others choose not to (sending 204 instead)

File: packages/lib/CalendarService.ts [hunk 7]
```diff
@@ -190,20 +190,44 @@ export default abstract class BaseCalendarService implements Calendar {
...
+            const ret = {
+              uid,
+              type: this.credentials.type,
+              id: typeof event.uid === "string" ? event.uid : "-1",
+              password: "",
+              url: event.url,
+              additionalInfo: event.additionalInformation,
+            } as NewCalendarEventType;
```
Comment (alishaz-polymath) [inline packages/lib/CalendarService.ts:214]: Since some providers return updated data while the others choose not to (sending 204 instead), we can't really use the return data directly and form a `NewCalendarEventType` object from it, as at times it will be null, thus causing JSON errors. Instead, we build it by utilizing the data we already have direct access to.

File: packages/lib/CalendarService.ts [hunk 8]
```diff
@@ -275,7 +298,7 @@ export default abstract class BaseCalendarService implements Calendar {
     const events: { start: string; end: string }[] = [];
 
     objects.forEach((object) => {
-      if (object.data == null) return;
+      if (object.data == null || JSON.stringify(object.data) == "{}") return;
```
Comment (alishaz-polymath) [inline packages/lib/CalendarService.ts:301]: when the object doesn't contain any data, we return. There will be a follow up on this condition to consider situations when the service providers **do not** send data directly, but that's a solution to a different problem and outside of the scope of this PR.

**Review by alishaz-polymath — COMMENTED** [review]
Self Review Added

**Comment by alishaz-polymath** [comment]
Loom video also added to the description

File: packages/lib/CalendarService.ts [hunk 9]
```diff
@@ -187,23 +187,48 @@ export default abstract class BaseCalendarService implements Calendar {
...
+              data: iCalString?.replace(/METHOD:[^\r\n]+\r\n/g, ""),
+              etag: calendarEvent?.etag,
             },
             headers: this.headers,
           });
         })
-      ).then((p) => p.map((r) => r.json() as unknown as NewCalendarEventType));
+      ).then((responses) =>
+        responses.map((response) => {
+          if (response.status > 199 && response.status < 207) {
```
Comment (emrysal) [inline packages/lib/CalendarService.ts:206]:
```suggestion
          if (response.status >= 200 && response.status < 300) {
```

Everything between 200 and 299 should be considered success.

**Review by emrysal — APPROVED** [review]
Minor feedback, overall approved.
