### PR TITLE
fix: mobile layout for API keys settings and dialog

### LINKED ISSUE #24112: Mobile Layout Issues in API Keys Settings
### Issue Summary

Mobile layout inconsistencies in API Keys settings page and dialog form. The mobile view lacks proper spacing and layout alignment compared to the desktop view, specifically affecting the "Add API key" button positioning and informational boxes spacing in the API key creation dialog.

### Steps to Reproduce

1. Navigate to Settings → Developer → API Keys
2. Observe the mobile view layout (or resize browser to mobile width)
3. Click on "Add" button to open the API key creation dialog
4. Observe the spacing between informational boxes in the dialog

### Actual Results

- What's happening right now that is different from what is expected

Image

Image

### Expected Results

- This is an ideal result that the system should get after the tests are performed

Image

Image

### Technical Details

- **Root Cause:** 
  - `SettingsHeader` component used `block` layout on mobile instead of `flex` with `justify-between`
  - `ApiKeyDialogForm` used `block gap-2 sm:flex` which removed gap spacing on mobile
- **Files Affected:**
  - `packages/features/settings/appDir/SettingsHeader.tsx`
  - `packages/features/ee/api-keys/components/ApiKeyDialogForm.tsx`
- **CSS Classes:** Layout classes needed to be updated to use `flex` with proper responsive behavior

### Evidence

**Before Fix:**
- Mobile view showed stacked layout without proper spacing
- "Add API key" button was centered instead of right-aligned
- Informational boxes in dialog had no spacing between them

**After Fix:**
- Mobile view now uses `flex justify-between` for consistent button positioning
- Dialog form uses `flex flex-col gap-2 sm:flex-row` for proper spacing on all screen sizes
- Layout is now consistent between mobile and desktop views

**Testing:**
- Verified layout works correctly on mobile viewport widths
- Confirmed desktop layout remains unchanged
- Tested responsive behavior across different screen sizes

### PR DESCRIPTION
**Pull request by KartikLabhshetwar**
## What does this PR do?

- Fixes #24112 
- Fixes [CAL-6473](https://linear.app/calcom/issue/CAL-6473/fix-mobile-layout-issues-in-api-keys-settings)

#### Video Demo (if applicable):

before:

https://github.com/user-attachments/assets/1f20dc85-fd23-4cef-af32-b2aed662ede9

after:

https://github.com/user-attachments/assets/80a8cd97-2d42-486c-933d-a677b04fa3c4

#### Image Demo (if applicable):

before:
Screenshot 2025-09-26 at 7 43 56 PM
Screenshot 2025-09-26 at 7 44 12 PM

after:
Screenshot 2025-09-26 at 8 03 03 PM

Screenshot 2025-09-26 at 8 28 33 PM

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

### CODE REVIEW

File: packages/features/ee/api-keys/components/ApiKeyDialogForm.tsx [hunk 1]
```diff
@@ -178,7 +178,7 @@ export default function ApiKeyDialogForm({
             <Controller
               name="note"
               control={form.control}
-              render={({ field: { onChange, value } }) => (
+              render={({ field: { value } }) => (
```
Comment (KartikLabhshetwar) [inline packages/features/ee/api-keys/components/ApiKeyDialogForm.tsx:181]: this is eslint fix

File: packages/features/ee/api-keys/components/ApiKeyDialogForm.tsx [hunk 2]
```diff
@@ -211,7 +211,7 @@ export default function ApiKeyDialogForm({
               </div>
               <Controller
                 name="expiresAt"
-                render={({ field: { onChange, value } }) => {
+                render={({ field: { onChange } }) => {
```
Comment (KartikLabhshetwar) [inline packages/features/ee/api-keys/components/ApiKeyDialogForm.tsx:214]: this is also an eslint fix

**Comment by KartikLabhshetwar** [comment]
@Udit-takkar @kart1ka can someone review this pr and see if everything is right here?

**Review by Devanshusharma2005 — APPROVED** [review]
