### PR TITLE
fix: Default people filter in bookings list for admin

### LINKED ISSUE #18026: [CAL-4851] If you're an admin, automatically filter to show your own bookings
I'm an admin, and now when I go to the bookings page I'm seeing everyone's bookings, but for the most part, I'm just looking to see my own. Meaning that I have to go Bookings > Filters > People > Bailey Pumfleet

This filter should be the default for admins

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4851](https://linear.app/calcom/issue/CAL-4851/if-youre-an-admin-automatically-filter-to-show-your-own-bookings)</sub>

### PR DESCRIPTION
**Pull request by vijayraghav-io**
## What does this PR do?

- Fixes #18026 
- Fixes CAL-4851

https://www.loom.com/share/dea5233306dd436c8e0e974c9dd658f5?sid=074ec548-12f4-47ae-8060-2d1497d99785

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] - N/A - I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by Praashh — CHANGES_REQUESTED** [review]
Would be better, if you have test case for this functionality. @vijayraghav-io can you please add ?

**Comment by vijayraghav-io** [comment]
> Would be better, if you have test case for this functionality. @vijayraghav-io can you please add ?

sure will add

File: apps/web/modules/bookings/views/bookings-listing-view.tsx [hunk 1]
```diff
@@ -73,11 +73,17 @@ const querySchema = z.object({
...
   const { status } = params ? querySchema.parse(params) : { status: "upcoming" as const };
   const { t } = useLocale();
   const user = useMeQuery().data;
   const [isFiltersVisible, setIsFiltersVisible] = useState<boolean>(false);
+  useEffect(() => {
+    if (user?.isTeamAdminOrOwner && !filterQuery.userIds?.length) {
+      setIsFiltersVisible(true);
+      pushItemToKey("userIds", user?.id);
+    }
+  }, [user, filterQuery.status]);
```
Comment (youneshenniwrites) [inline apps/web/modules/bookings/views/bookings-listing-view.tsx:86]: `filterQuery.status` isn't used in the effect, so having it in the dependencies could trigger unnecessary re-runs. This version makes more sense:

```
useEffect(() => {
    if (user?.isTeamAdminOrOwner && (!filterQuery.userIds || !filterQuery.userIds.length)) {
        setIsFiltersVisible(true);
        pushItemToKey("userIds", user?.id);
    }
}, [user?.isTeamAdminOrOwner, filterQuery.userIds, user?.id]);

```

Comment (vijayraghav-io) [reply apps/web/modules/bookings/views/bookings-listing-view.tsx:86]: `filterQuery.status` reflects the status tabs (upcoming, past, recurring,...),
On switching the tabs, the filters are reset.
So on tab change, this has to be re-run to set the default filter.

**Comment by vijayraghav-io** [comment]
@Praashh , added an e2e test

**Review by Praashh — DISMISSED** [review]
Great Work @vijayraghav-io.

**Comment by vijayraghav-io** [comment]
Verified multiple times locally the new test is passing, along with bookings-list.e2e module.
Will figure out and update to remove flakiness on server.

**Comment by vijayraghav-io** [comment]
@Praashh all tests are passing

**Review by Praashh — COMMENTED** [review]
Awesome work.

**Comment by vijayraghav-io** [comment]
Thanks @Praashh may be you have to approve again, as prev approve was staled

**Comment by vijayraghav-io** [comment]
Reminding for review / action.

**Comment by Praashh** [comment]
> Gentle Reminder for review / action.

Cool Sir, I'll give it final touch 🙏 .

**Comment by vijayraghav-io** [comment]
sure Thank you! 🙏

**Review by Praashh — DISMISSED** [review]
LGTM ❤️ !!

**Comment by vijayraghav-io** [comment]
Gentle Reminder!

**Comment by PeerRich** [comment]
hey @vijayraghav-io can you check the merge conflict?

**Review by PeerRich — DISMISSED** [review]
approved on behalf of @Praashh

**Comment by vijayraghav-io** [comment]
resolved merge conflicts

**Review by Praashh — APPROVED** [review]
🚀

**Comment by vijayraghav-io** [comment]
@Praashh,
resolved conflicts again.
Gentle reminder to kindly approve again and take it to merge.

**Review by retrogtx — APPROVED** [review]

**Comment by retrogtx** [comment]
> @Praashh, resolved conflicts again. Gentle reminder to kindly approve again and take it to merge.

I've passed around the message

**Comment by vijayraghav-io** [comment]
🙏
