### PR TITLE
fix: data table toolbar styling

### LINKED ISSUE #25634: Data Table Tooltip Search Field has unnecessary margin causing layout misalignment
### Issue Summary

Image

Image

### Steps to Reproduce

1. visit https://app.cal.com/settings/my-account/out-of-office

### PR DESCRIPTION
**Pull request by abhix4**
## What does this PR do?

**Issue**: 
- class `mx-3` at `<InputField/>` causing shift.

**Fix**: 
- Removed the unnecessary horizontal margin applied to the InputField component to prevent unintended layout shifts.
- Reduced top margin to improve alignment.

- Fixes #25634 (GitHub issue number)
- Fixes [CAL-6872](https://linear.app/calcom/issue/CAL-6872/data-table-tooltip-search-field-has-unnecessary-margin-causing-layout)

## Visual Demo (For contributors especially)

**BEFORE**: 

image

image

**AFTER:**

image

image

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

### CODE REVIEW

File: packages/ui/components/form/inputs/Input.tsx [hunk 1]
```diff
@@ -22,10 +22,6 @@ export function InputLeading(props: JSX.IntrinsicElements["div"]) {
   );
 }
 
-type PasswordFieldTranslations = {
-  showPasswordText?: string;
-  hidePasswordText?: string;
-};
```
Comment (abhix4) [inline packages/ui/components/form/inputs/Input.tsx]: isn't used anywhere

**Review by dhairyashiil — CHANGES_REQUESTED** [review]
Please create an issue and link the PR to it. It would also be really helpful if you could add a description explaining what you're changing and how it addresses the issue, as this will make the review easier.

**Comment by abhix4** [comment]
> Please create an issue and link the PR to it. It would also be really helpful if you could add a description explaining what you're changing and how it addresses the issue, as this will make the review easier.

@dhairyashiil  thank you for the feedback, addressed all.

**Review by dhairyashiil — APPROVED** [review]
Looks good 👍🏼 , thank you for the attention to detail and your contribution.

**Review by keithwillcode — APPROVED** [review]
