### PR TITLE
fix: get llm response schema

### LINKED ISSUE #14671: [CAL-3501] Error in create call handler
Found a bug? Please fill out the sections below. 👍

### Issue Summary

image

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3501](https://linear.app/calcom/issue/CAL-3501/error-in-create-call-handler)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/14671

Before: "Something went wrong"

After:-

Screenshot 2024-04-19 at 8 21 24 PM

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/prisma/zod-utils.ts [hunk 1]
```diff
@@ -750,7 +750,8 @@ export const getRetellLLMSchema = z
           })
           .passthrough()
       )
-      .nullable(),
+      .nullable()
+      .optional(),
```
Comment (Udit-takkar) [inline packages/prisma/zod-utils.ts:754]: the return type changed. earlier it used to always return null when 'states' was not present

**Review by alishaz-polymath — APPROVED** [review]
🚀 
Awesome 👏 @Udit-takkar
