### PR TITLE
fix: paypal minor issues

### LINKED ISSUE #11060: [CAL-2396] Paypal not showing currency on booking page
Verify that paypal event type card saves event type currency.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2396](https://linear.app/calcom/issue/CAL-2396/paypal-not-showing-currency-on-booking-page)</sub>

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

- Fix saving currency for eventType for paypal app
- Fix api handler to redirect to booking/ui page if error occurs

Fixes #11060, #11062 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Are there environment variables that should be set? No
- What are the minimal test data to have? Paypal installed
- What is expected (happy path) to have (input and output)? Install paypal app, setup a payment event with price and currency. When booking said event type currency should appear in page.
For the other when error is encountered after returning from paypal api handler should redirect to booking/uid page.
- Any other important info that could help to test that PR. No

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/app-store/paypal/api/capture.ts [hunk 1]
```diff
@@ -78,12 +77,6 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
     }
     return;
   } catch (_err) {
-    const err = getErrorFromUnknown(_err);
-
-    res.status(200).send({
```
Comment (alannnc) [inline packages/app-store/paypal/api/capture.ts:83]: Not required any more so res.redirect can execute.

File: packages/app-store/paypal/lib/Paypal.ts [hunk 2]
```diff
@@ -173,7 +173,7 @@ class Paypal {
       }
     } catch (error) {
       console.error(error);
-      return false;
+      throw error;
```
Comment (alannnc) [inline packages/app-store/paypal/lib/Paypal.ts:176]: Throwing error so parent try catch runs after this.

File: packages/trpc/server/routers/viewer/eventTypes/update.handler.ts [hunk 3]
```diff
@@ -260,6 +260,9 @@ export const updateHandler = async ({ ctx, input }: UpdateOptions) => {
       const { default_currency } = stripeDataSchema.parse(paymentCredential.key);
       data.currency = default_currency;
     }
+    if (paymentCredential?.type === "paypal_payment" && input.metadata?.apps?.paypal?.currency) {
+      data.currency = input.metadata?.apps?.paypal?.currency.toLowerCase();
+    }
```
Comment (alannnc) [inline packages/trpc/server/routers/viewer/eventTypes/update.handler.ts:265]: If paypal is being saved on input also save eventType.currency field

**Review by joeauyeung — APPROVED** [review]
Changes look like they make sense. LGTM.
