### PR TITLE
fix: Added distinct clause when getting user list in team for insights

### LINKED ISSUE #10059: [CAL-2143] /insights - User filter: Users showing up twice
There is only 3 users in this Org. I see 5 people in the People filter dropdown

Linear-hosted image

[Source image](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/eb70a38e-2a17-4641-865d-376e3b8b1f36/edc827b2-4acd-4d6d-88b3-6714c1664c04)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2143](https://linear.app/calcom/issue/CAL-2143/insights-user-filter-users-showing-up-twice)</sub>

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

- Adds distinct clause to userTeamList

Fixes #10059 

## Type of change

  - [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

  - Are there environment variables that should be set? No
  - What are the minimal test data to have? Creating a team inside an organization with a few members.
  - What is expected (happy path) to have (input and output)? On the user list there shouldn't be any duplicates.
  - Any other important info that could help to test that PR. No.

## Mandatory Tasks

  - [X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/features/insights/server/trpc-router.ts [hunk 1]
```diff
@@ -1239,6 +1239,7 @@ export const insightsRouter = router({
               select: UserSelect,
             },
           },
+          distinct: ["userId"],
```
Comment (alannnc) [inline packages/features/insights/server/trpc-router.ts:1242]: This is due team org members gets double membership to parent and to child team.

**Review by zomars — APPROVED** [review]

**Review by emrysal — APPROVED** [review]
🚀
