### PR TITLE
fix: alignment of icon and title in ConfirmationDialogContent

### LINKED ISSUE #9866: [CAL-2078] title and icon not aligned in ConfirmationDialogContent
### Issue Summary

This is our dialog to confirm if event type should get deleted:

As you can see title and icon are not aligned:

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2078](https://linear.app/calcom/issue/CAL-2078/title-and-icon-not-aligned-in-confirmationdialogcontent)</sub>

### PR DESCRIPTION
**Pull request by ujwalkumar1995**
## What does this PR do?

Fixes the alignment of title and icon in ConfirmationDialogContent

Screenshot 2023-07-01 014216

Fixes #9866 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

This can be tested in various flows as this is a shared component. We could test it when deleting an event, when we are removing an app from installed apps, when we are disbanding a team from settings.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/ui/components/dialog/ConfirmationDialogContent.tsx [hunk 1]
```diff
@@ -57,7 +57,7 @@ export function ConfirmationDialogContent(props: PropsWithChildren<ConfirmationD
           </div>
         )}
         <div>
-          <DialogPrimitive.Title className="font-cal text-emphasis text-xl">{title}</DialogPrimitive.Title>
+          <DialogPrimitive.Title className="mt-2 font-cal text-emphasis text-xl">{title}</DialogPrimitive.Title>
```
Comment (PeerRich) [inline packages/ui/components/dialog/ConfirmationDialogContent.tsx:60]:
```suggestion
          <DialogPrimitive.Title className="font-cal text-emphasis mt-2 text-xl">{title}</DialogPrimitive.Title>
```

**Review by PeerRich — DISMISSED** [review]

**Review by PeerRich — APPROVED** [review]
