### PR TITLE
fix: team invite signup not working

### LINKED ISSUE #13719: [CAL-3153] A regular team invite link doesn't let the user signup.
More details
[https://threads.com/thread/34564782464/34564782466?s=iqPGGjVxpdtuyVZgia5BXp](https://threads.com/thread/34564782464/34564782466?s=iqPGGjVxpdtuyVZgia5BXp)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3153](https://linear.app/calcom/issue/CAL-3153/a-regular-team-invite-link-doesnt-let-the-user-signup)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #13719 

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Mandatory Tasks
- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist
- I haven't added tests that prove my fix is effective or that my feature works

**NOTE**: It isn't possible to test this flow using e2e

### CODE REVIEW

File: packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts [hunk 1]
```diff
@@ -235,10 +235,11 @@ export async function createNewUsersConnectToOrgIfExists({
         const usernameOrEmail = usernamesOrEmails[index];
         const { orgId, autoAccept } = connectionInfoMap[usernameOrEmail];
         const [emailUser, emailDomain] = usernameOrEmail.split("@");
-        const username =
-          emailDomain === autoAcceptEmailDomain
+        const username = input.isOrg
```
Comment (hariombalhara) [inline packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts:238]: For a non sub-team invite, we shouldn't set username during the invite as user is allowed to change the username during the signup.

File: packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts [hunk 2]
```diff
@@ -236,9 +236,11 @@ export async function createNewUsersConnectToOrgIfExists({
         const { orgId, autoAccept } = connectionInfoMap[usernameOrEmail];
         const [emailUser, emailDomain] = usernameOrEmail.split("@");
         const username =
-          emailDomain === autoAcceptEmailDomain
-            ? slugify(emailUser)
-            : slugify(`${emailUser}-${emailDomain.split(".")[0]}`);
+          input.isOrg || parentId
```
Comment (hariombalhara) [inline packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts:239]: Ensures that for a regular team the username isn't set because user is allowed to change the username during signup in that context.

File: packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts [hunk 3]
```diff
@@ -227,22 +227,29 @@ export async function createNewUsersConnectToOrgIfExists({
...
-        const username =
+
+        // An org member can't change username during signup, so we set the username
+        const orgMemberUsername =
           emailDomain === autoAcceptEmailDomain
             ? slugify(emailUser)
             : slugify(`${emailUser}-${emailDomain.split(".")[0]}`);
 
+        // As a regular team member is allowed to change username during signup, we don't set any username for him
+        const regularTeamMemberUsername = null;
```
Comment (hariombalhara) [inline packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts:246]: I think we accidentally started setting it for regular teams by this PR
https://github.com/calcom/cal.com/pull/11238/files
cc @joeauyeung for confirmation

**Review by Udit-takkar — COMMENTED** [review]
LGTM. Regular Team invites are working fine. 

Checking orgs now

**Review by Udit-takkar — APPROVED** [review]
