### PR TITLE
fix: schedule no show webhooks for requires confirmation event

### LINKED ISSUE #17071: [CAL-4506] Automatic no-show missing triggers
Audience @CarinaWolli @Udit-takkar

Regarding the new feature shipped in PR #16727 . Seems like we have some logic gaps on some even type configurations, specifically the webhooks aren't being scheduled when:

* The webhook is setup in the event type itself. On user level works fine (tested).
* When event type has “requires confirmation” enabled.

My suggestion would be to add the scheduling logic to the confirm endpoint. And make sure that webhooks with eventTypeId and without userId are being fetched when scheduling.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4506](https://linear.app/calcom/issue/CAL-4506/automatic-no-show-missing-triggers)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

- Fixes https://github.com/calcom/cal.com/issues/17071 (GitHub issue number)
- Fixes CAL-4506 (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] N/A I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

### CODE REVIEW

File: packages/features/bookings/lib/handleConfirmation.ts [hunk 1]
```diff
@@ -391,6 +407,50 @@ export async function handleConfirmation(args: {
...
+            {
+              triggerEvent: WebhookTriggerEvents.AFTER_HOSTS_CAL_VIDEO_NO_SHOW,
+              bookingId: booking.id,
+              // Prevents null values from being serialized
+              webhook: { ...webhook, time: webhook.time, timeUnit: webhook.timeUnit },
+            },
+            { scheduledAt }
+          );
+        }
+        return Promise.resolve();
```
Comment (Udit-takkar) [inline packages/features/bookings/lib/handleConfirmation.ts:427]: create task for triggerHostNoShowWebhook and triggerGuestNoShowWebhook

Comment (zomars) [reply packages/features/bookings/lib/handleConfirmation.ts:431]: Can we extract this logic and use it both on handleNewBooking and here? To ensure and prevent logic drifts?

Comment (Udit-takkar) [reply packages/features/bookings/lib/handleConfirmation.ts]: done

**Review by zomars — APPROVED** [review]
