### PR TITLE
fix: create event type for a team that you are an owner or admin of

### LINKED ISSUE #12558: Creating event types with team ID is broken for cal.com team users
### Issue Summary

This PR: https://github.com/calcom/cal.com/pull/12482 has broken creating event types as a team member/admin/owner but not global admin. Before I could POST to `/v1/event-types` with:

```
{
  "length": 15,
  "title": "Test title",
  "slug": "rr-slug-test-location",
  "schedulingType": "ROUND_ROBIN",
  "teamId": <TEAM_ID>,
  "hosts": [
    {
      "userId": <USER_ID>,
      "isFixed": true
    }
  ]
}
```

and it would create the event type for my team. Now I get a 401:

```
{
  "message": "ADMIN required for `teamId`"
}
```

### Steps to Reproduce

1. Create a team and note the `teamId`
2. Create an API Key
3. Post to `/v1/event-types` with body:
```
{
  "length": 15,
  "title": "Test title",
  "slug": "rr-slug-test-location",
  "schedulingType": "ROUND_ROBIN",
  "teamId": <TEAM_ID>,
  "hosts": [
    {
      "userId": <USER_ID>,
      "isFixed": true
    }
  ]
}
```

### Actual Results

I'm getting a 401 when I should be allowed to create.

### Expected Results

A 200 is returned and event type created.

### Technical details

Live version of cal.com

### Evidence

Follow steps to reproduce.

### PR DESCRIPTION
**Pull request by nicolls1**
## What does this PR do?

This allows team admins or owners to create event types over the API.

Fixes #12558 

No visual changes

## Requirement/Documentation

https://cal.com/docs/enterprise-features/api/api-reference/event-types

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

I tested locally with user `teampro3@example.com`. Create an API key for this user and then POST to `/v1/event-types` with body: 

```
{
  "length": 15,
  "title": "New title",
  "slug": "rr-slug",
  "schedulingType": "ROUND_ROBIN",
  "teamId": 1,
  "hosts": [
    {
      "userId": 12,
      "isFixed": true
    }
  ]
}
```

Testing this on main will fail but go through on this branch.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

File: apps/api/pages/api/teams/[teamId]/_auth-middleware.ts [hunk 1]
```diff
@@ -23,6 +23,16 @@ export async function checkPermissions(
 ) {
   const { userId, prisma, isAdmin } = req;
   const { teamId } = schemaQueryTeamId.parse(req.query);
+  return canUserAccessTeamWithRole(prisma, userId, isAdmin, teamId, role);
+}
+
+export async function canUserAccessTeamWithRole(
```
Comment (nicolls1) [inline apps/api/pages/api/teams/[teamId]/_auth-middleware.ts:29]: My hope is that this can be used ad a default for checking team access rather than just defaulting to checking if the user is an admin 🙏

**Review by zomars — APPROVED** [review]
Good enough to merge. Thank you for your contribution 🙏

**Comment by swain** [comment]
@zomars When can we expect this to be merged?

**Comment by keithwillcode** [comment]
> @zomars When can we expect this to be merged?

@swain there’s many failing tests. We have to get those fixed up before merging
