### PR TITLE
fix: Improved EventsLimit page for mobile viewports

### LINKED ISSUE #19269: EventsLimits page not optimised for mobile viewports
Found a bug? Please fill out the sections below. 👍

### Issue Summary

- Limit total booking duration overflows for mobile viewports
- Limit future booking not optimised for all viewports

### Steps to Reproduce

1. Go to Event Types ...
2. Clicked Limits...

### Actual Results

https://github.com/user-attachments/assets/8eab91fa-5b65-4f26-a992-12c9693aee8d

Screenshot 2025-02-13 at 3 10 02 AM

### PR DESCRIPTION
**Pull request by harshit078**
## What does this PR do?

- Fixes #19269

Screenshot 2025-02-13 at 3 07 41 AM

 https://github.com/user-attachments/assets/b6decf10-8f6e-4c0e-93aa-cac46733642f

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

File: packages/features/eventtypes/components/tabs/limits/EventLimitsTab.tsx [hunk 1]
```diff
@@ -210,7 +212,7 @@ function RollingLimitRadioItem({
             labelSrOnly
             type="number"
             className={classNames(
-              "border-default my-0 block w-16 text-sm [appearance:textfield] ltr:mr-2 rtl:ml-2",
+              "border-default my-0 !mr-0 block w-16 text-sm [appearance:textfield]",
```
Comment (retrogtx) [inline packages/features/eventtypes/components/tabs/limits/EventLimitsTab.tsx:215]: why is !mr-0 necessary? what are we trying to override?

Comment (harshit078) [reply packages/features/eventtypes/components/tabs/limits/EventLimitsTab.tsx:215]: Added  !mr-0 as a safe check and to remove any right margins being passed . Not overriding anything, removing it wont cause any breakage.

Comment (retrogtx) [reply packages/features/eventtypes/components/tabs/limits/EventLimitsTab.tsx:215]: does it not work without it? just asking

if it's not necessary then please remove it
i tried it locally, works fine without it 

if there is no specific reason to add it then it's better not to keep it

Comment (harshit078) [reply packages/features/eventtypes/components/tabs/limits/EventLimitsTab.tsx:215]: cool, I'll remove it no worries.

**Review by retrogtx — APPROVED** [review]
