### PR TITLE
chore: small fixes to org email

### LINKED ISSUE #12862: [CAL-2822] Organization Onboarding bugs
Use of backtick and &#39

image

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2822](https://linear.app/calcom/issue/CAL-2822/organization-onboarding-bugs)</sub>

### PR DESCRIPTION
**Pull request by PeerRich**

### CODE REVIEW

File: packages/emails/src/templates/TeamInviteEmail.tsx [hunk 1]
```diff
@@ -65,7 +65,7 @@ export const TeamInviteEmail = (
           {props.language(
             `email_user_invite_subheading_${props.isOrg ? "org" : props.parentTeamName ? "subteam" : "team"}`,
             {
-              invitedBy: props.from,
+              invitedBy: props.from.toString(),
```
Comment (PeerRich) [inline packages/emails/src/templates/TeamInviteEmail.tsx:68]: haven't tested this yet, but this could work

Comment (sean-brydon) [reply packages/emails/src/templates/TeamInviteEmail.tsx:68]: `props.from` is a string so not 100% sure what this is trying to do

**Review by emrysal — APPROVED** [review]
Approved, I'm sure you had a reason for the toString()
