### PR TITLE
fix: icon visibility and add up and down icons

### LINKED ISSUE #15542: In Workflows page dropdown icon is not properly visible in the time unit input and request for addition of up and down icons
### Issue Summary
In Workflows page up cursor hiding in the time unit input.
icon hiding

### Steps to Reproduce

1.Try to create a workflow
2. Try selecting the trigger with before or after events
3. How long before or after events time input pops up
4. The dropdown icon is not visible properly

### PR DESCRIPTION
**Pull request by Sahillather002**
## What does this PR do?
Fixed the dropdown icon visibility and added the icon which changes on state of dropdown opens or not.
- Fixes #15542(GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

fix a
fix b

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

### CODE REVIEW

File: packages/features/ee/workflows/components/TimeTimeUnitInput.tsx [hunk 1]
```diff
@@ -39,14 +40,14 @@ export const TimeTimeUnitInput = (props: Props) => {
...
           addOnSuffix={
-            <Dropdown>
+            <Dropdown onOpenChange={setIsDropdownOpen}>
               <DropdownMenuTrigger asChild>
                 <button className="flex items-center">
-                  <div className="mr-1 w-3/4">
+                  <div className="mr-1 w-3/5">
                     {timeUnit ? t(`${timeUnit.toLowerCase()}_timeUnit`) : "undefined"}{" "}
                   </div>
-                  <div className="w-1/4 pt-1">
```
Comment (Ryukemeister) [inline packages/features/ee/workflows/components/TimeTimeUnitInput.tsx:48]: @Sahillather002 you can keep the width here as `w=1/4`

**Review by Ryukemeister — COMMENTED** [review]
Other than the one small change looks great, nice job!

File: packages/features/ee/workflows/components/TimeTimeUnitInput.tsx (hunk 1 above)
Comment (Sahillather002) [reply packages/features/ee/workflows/components/TimeTimeUnitInput.tsx:48]: @Ryukemeister i did it because icon was hiding to that width so gives larger width, or i can reduce the size of icon

**Comment by emrysal** [comment]
Drafting as making a little style update.

**Comment by emrysal** [comment]
Hey @Sahillather002 - I've updated the code to incorporate @Ryukemeister's observations and did a minor re-organisation in order to optimise the component & make it less complex. With these changes the re-render is isolated to the dropdown and certain input is cached (like i18n) whenever the dropdown is opened.

File: packages/features/ee/workflows/components/TimeTimeUnitInput.tsx [hunk 2]
```diff
@@ -12,21 +13,50 @@ import {
...
+
 type Props = {
   form: UseFormReturn<FormValues>;
   disabled: boolean;
 };
 
+const TimeUnitAddonSuffix = ({
+  DropdownItems,
+  timeUnitOptions,
+  form,
```
Comment (Udit-takkar) [inline packages/features/ee/workflows/components/TimeTimeUnitInput.tsx:28]: why are we passing this form object everywhere? we can just use useFormContext ?

**Review by Udit-takkar — APPROVED** [review]
LGTM. we can fix this https://github.com/calcom/cal.com/pull/15543#discussion_r1666010016 in a followup
