### PR TITLE
fix: Dynamic Group Links on vercel

### LINKED ISSUE #9575: [CAL-1970] Dynamic group event types won't open
Created via Threads. See full discussion: [https://threads.com/34482201326](https://threads.com/34482201326)

[https://www.loom.com/share/71312cfb62c94a01b392127d8502870a](https://www.loom.com/share/71312cfb62c94a01b392127d8502870a)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1970](https://linear.app/calcom/issue/CAL-1970/dynamic-group-event-types-wont-open)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #9575
Test on https://web-staging-msw9zb5uo-cal-staging.vercel.app/free+pro/30?duration=30
On local free+pro is available as 'free+pro' in gSSP but on Vercel it sometimes becomes
'free pro' because + is a very confusing thing in URL. Sometimes it's  available as 'free%20pro' and we are expecting a + always.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
- Go to /free+pro/30. Shouldn't be 404

## Mandatory Tasks
- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: apps/web/pages/[user]/[type].tsx [hunk 1]
```diff
@@ -358,9 +359,9 @@ async function getDynamicGroupPageProps(context: GetServerSidePropsContext) {
 }
 
 export async function getServerSideProps(context: GetServerSidePropsContext) {
-  const { user: userParam } = paramsSchema.parse(context.query);
+  const { user: userParam } = paramsSchema.parse(context.params);
```
Comment (hariombalhara) [inline apps/web/pages/[user]/[type].tsx:362]: Made it consistent with new-booker code. Though I don't think it matters(but didn't want to test again as it takes time to build on vercel and then test.)

File: apps/web/pages/[user]/[type].tsx [hunk 2]
```diff
@@ -358,9 +359,9 @@ async function getDynamicGroupPageProps(context: GetServerSidePropsContext) {
...
   // dynamic groups are not generated at build time, but otherwise are probably cached until infinity.
-  const isDynamicGroup = userParam.includes("+");
+  const isDynamicGroup = getUsernameList(userParam).length > 1;
```
Comment (hariombalhara) [inline apps/web/pages/[user]/[type].tsx:364]: getUsernameList handles "+", " ", "%2B"

**Review by emrysal — APPROVED** [review]
