### PR TITLE
Fixes bug when changing the location of a booking

### LINKED ISSUE #3588: Changing location after a booking is made is buggy
### Issue Summary

Bug:

1. The integrated calendar event doesn’t show updated location, but the booking in the cal account does
2. It picks up a random (I guess) event from the list (in my case it was a past event) and sends the email with the updated location to the unintended recipients (Potentially critical)

### Steps to Reproduce

1. Create a booking (hopefully with integrated calendar)
2. Change the location

### PR DESCRIPTION
**Pull request by CarinaWolli**
## What does this PR do?

Fixes the following issues when changing the location of a booking:
- Wrong attendees receive location change email
- Calendar event with old location is not deleted

Loom Video: https://www.loom.com/share/d8c36c4edd5d4817b66d68c989a09af0

Fixes #3588 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Create a booking (with integrated calendar)
- Change the location
- Check if attendees received location change email 
- Check your calendar to see if the event has the new location

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by alishaz-polymath** [comment]
It looks good in terms of taking care of the bug, but adds a new concern of potential confusion for the attendees with cancellation email since we're deleting an event and then adding a new one. I think we should perhaps try to create a more robust solution. I'd let @zomars make the decision on this.

File: packages/trpc/server/routers/viewer/bookings.tsx [hunk 1]
```diff
@@ -69,13 +71,29 @@ export const bookingsRouter = createProtectedRouter()
...
+            destinationCalendar: true,
+            user: {
+              include: {
+                destinationCalendar: true,
+                credentials: true,
+              }
+            },
+            references: true,
+          }
+        })
```
Comment (zomars) [inline packages/trpc/server/routers/viewer/bookings.tsx:92]: We already do a booking find at [Line 32](https://github.com/calcom/cal.com/pull/3585/files#diff-1f41e2e253ba5e8709f8acc2db09d5ed70727be132f7c63d5ad6af734013cac8L32). This would cause a double query for the same booking, let's try to add the necessary logic to the middleware instead.

File: packages/trpc/server/routers/viewer/bookings.tsx [hunk 2]
```diff
@@ -126,7 +144,29 @@ export const bookingsRouter = createProtectedRouter()
...
+              const calendar = getCalendar(credentialsMap.get(bookingRef.type));
+
+              return calendar?.deleteEvent(
+                bookingRef.uid,
+                evt,
+                bookingRef.externalCalendarId
+              );
+            }
+          }
+        });
```
Comment (zomars) [inline packages/trpc/server/routers/viewer/bookings.tsx:168]: Some Qs: Are we returning promises here? Do we want them to run in parallel, on cascade or is it irrelevant?

File: packages/core/EventManager.ts [hunk 3]
```diff
@@ -156,6 +156,42 @@ export default class EventManager {
...
+      const result = await this.createVideoEvent(evt);
+      if (result.createdEvent) {
+        evt.videoCallData = result.createdEvent;
+      }
+
+      results.push(result);
+    }
+
+    // Update the calendar event with the proper video call data
+    results.push(...(await this.updateAllCalendarEvents(evt, booking)));
```
Comment (CarinaWolli) [inline packages/core/EventManager.ts:175]: Not working for Google Meet. Hangout link is not created in updateEvent (https://github.com/calcom/cal.com/blob/fix/location-change/packages/app-store/googlecalendar/lib/CalendarService.ts)

**Review by alishaz-polymath — APPROVED** [review]
Looks good! Amazing @CarinaWolli

**Comment by PeerRich** [comment]
waiting for @zomars for final blessing 🙏

File: packages/trpc/server/routers/viewer/bookings.tsx [hunk 4]
```diff
@@ -13,6 +13,8 @@ import type { AdditionalInformation, CalendarEvent } from "@calcom/types/Calenda
 import { TRPCError } from "@trpc/server";
 
 import { createProtectedRouter } from "../../createRouter";
+import { getCalendar } from "@calcom/app-store/_utils/getCalendar";
```
Comment (zomars) [inline packages/trpc/server/routers/viewer/bookings.tsx:16]:
```suggestion
```

Not being used

File: packages/trpc/server/routers/viewer/bookings.tsx [hunk 5]
```diff
@@ -13,6 +13,8 @@ import type { AdditionalInformation, CalendarEvent } from "@calcom/types/Calenda
...
+import { BookingReference } from "@calcom/prisma/client";
```
Comment (zomars) [inline packages/trpc/server/routers/viewer/bookings.tsx:17]:
```suggestion
```

Not being used either

File: packages/trpc/server/routers/viewer/bookings.tsx [hunk 6]
```diff
@@ -23,36 +25,45 @@ export const bookingsRouter = createProtectedRouter()
...
     if (!webhookIdAndEventTypeId.success) throw new TRPCError({ code: "PARSE_ERROR" });
 
     const { bookingId } = webhookIdAndEventTypeId.data;
     const booking = await ctx.prisma.booking.findFirst({
       where: {
-        OR: [
-          /* If user is organizer */
-          { userId: ctx.user.id, id: bookingId },
-          /* Or part of a collective booking */
+        AND: [
```
Comment (zomars) [inline packages/trpc/server/routers/viewer/bookings.tsx:32]:
```suggestion
        id: bookingId,
        AND: [
```

File: packages/trpc/server/routers/viewer/bookings.tsx [hunk 7]
```diff
@@ -23,36 +25,45 @@ export const bookingsRouter = createProtectedRouter()
...
           {
-            eventType: {
-              schedulingType: SchedulingType.COLLECTIVE,
-              users: {
-                some: {
-                  id: ctx.user.id,
+            id: bookingId
```
Comment (zomars) [inline packages/trpc/server/routers/viewer/bookings.tsx:34]:
```suggestion
```

File: packages/trpc/server/routers/viewer/bookings.tsx [hunk 8]
```diff
@@ -23,36 +25,45 @@ export const bookingsRouter = createProtectedRouter()
...
+          }, {
```
Comment (zomars) [inline packages/trpc/server/routers/viewer/bookings.tsx:35]:
```suggestion
```

**Review by zomars — COMMENTED** [review]
Minor nitpicks but overall LGTM

**Review by zomars — APPROVED** [review]
