### PR TITLE
Embed: Strictly type the codebase and fixes a few bugs found

### LINKED ISSUE #7472: Improve Embed Types
When Embed package was written, TypeScript wasn't the first priority. But now that developers are using it, the DX isn't good enough and can be improved by TypeScript Intellisense

Some of the known/reported things that need to be fixed:

- https://twitter.com/pagebakers/status/1631310598196559872

### LINKED ISSUE #7580: [CAL-1198] Embedded bug : `enabledDateButton` style is not properly re-rendered
### Issue Summary
The `enabledDateButton` style property of inline embedded calendars is properly applied during the first call to the `"ui"` method of a calendar instance, but seems ignored on subsequent calls.

### Steps to Reproduce
1. Initialize an embedded inline calendar instance
2. Call its `"ui"` method a first time with an initial enabled date button's background color, e.g. 
```js
Cal.ns.myCal("ui", {
  styles: {
    enabledDateButton: {
      background: "red",
    }
  }
})
```

Will render :
image

3. Call its `"ui"` method a second time with a different enabled date button's background color, e.g. 
```js
Cal.ns.myCal("ui", {
  styles: {
    enabledDateButton: {
      background: "green",
    }
  }
})
```

Will render :
image

4. As shown on the above screenshots, the enabled date buttons' background remains `red` while a `green` one is excepted.

<sub>[CAL-1198](https://linear.app/calcom/issue/CAL-1198/embedded-bug-enableddatebutton-style-is-not-properly-re-rendered)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #7472 
Fixes #7580. [See loom of how `enabledDateButton`  bg is changing again and again](https://www.loom.com/share/fad1bbb1bcfe4e1bbac80fdcb73baa1b)
- Strictly types Embed code everywhere. No non-null assertions and any usages now.
- Fixes a bug where `branding` and `align` wasn't working.
- Supports `calOrigin` with `modal` and `floatingButton` instructions.
- Supports `calOrigin` prop in `init` instruction(but also keeps `origin` for backward compatibility) to keep it consistent with other places.

**Environment**: Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: apps/web/components/Embed.tsx [hunk 1]
```diff
@@ -167,7 +167,7 @@ const Codes: Record<string, Record<string, (...args: any[]) => string>> = {
       const height = getDimension(previewState.inline.height);
       return code`
 import Cal, { getCalApi } from "@calcom/embed-react";
-
```
Comment (hariombalhara) [inline apps/web/components/Embed.tsx:170]: useEffect was missing in the provided Embed code.

File: apps/web/components/Embed.tsx [hunk 2]
```diff
@@ -187,12 +187,12 @@ function MyComponent() {
...
+import { useEffect } from "react";
 function MyComponent() {
   useEffect(()=>{
     (async function () {
       const cal = await getCalApi();
-      Cal("floatingButton", ${floatingButtonArg});
+      cal("floatingButton", ${floatingButtonArg});
```
Comment (hariombalhara) [inline apps/web/components/Embed.tsx:195]: Typo here

File: packages/embeds/embed-core/index.html [hunk 3]
```diff
@@ -90,6 +90,7 @@
     </div>
     <span style="display: block;" ><a href="?only=all">Render All embeds together</a><small> - It would be slow to load</small></span>
     <div>
+      <a href="?only=ns:floatingButton">Floating Popup</a>
```
Comment (hariombalhara) [inline packages/embeds/embed-core/index.html:93]: There was non dedicated link to reach to test out just the Floating popup(in zen mode)

File: packages/embeds/embed-core/index.html [hunk 4]
```diff
@@ -210,14 +211,13 @@ <h3><a href="?only=hideEventTypeDetails">Hide EventType Details Test</a></h3>
...
           debug: 1,
-          origin: "http://localhost:3000",
+          calOrigin: "http://localhost:3000",
         });
 
         Cal("inline", {
           elementOrSelector: "#cal-booking-place-default .place",
           calLink: "pro?case=1",
           config: {
-            __autoScroll:true,
```
Comment (hariombalhara) [inline packages/embeds/embed-core/index.html:220]: Unused flag now

File: packages/embeds/embed-core/src/FloatingButton/FloatingButton.ts [hunk 5]
```diff
@@ -8,66 +39,69 @@ export class FloatingButton extends HTMLElement {
...
+    return dataAttributes;
   }
 
-  attributeChangedCallback(name: string, oldValue: string, newValue: string) {
+  attributeChangedCallback(name: DataAttributes, oldValue: string, newValue: string) {
+    const buttonEl = this.shadowRoot?.querySelector<HTMLElement>("#button");
+    const buttonWrapperEl = this.shadowRoot?.querySelector<HTMLElement>("button");
+    const buttonIconEl = this.shadowRoot?.querySelector<HTMLElement>("#button-icon");
+
+    if (!buttonEl) {
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/FloatingButton/FloatingButton.ts:56]: Simplified the code

File: packages/embeds/embed-core/src/FloatingButton/FloatingButton.ts [hunk 6]
```diff
@@ -1,5 +1,36 @@
...
+
+type HyphenatedStringToCamelCase<S extends string> = S extends `${infer T}-${infer U}`
+  ? `${T}${HyphenatedStringToCamelCase<CamelCase<U>>}`
+  : CamelCase<S>;
+
+type HyphenatedDataStringToCamelCase<S extends string> = S extends `data-${infer U}`
+  ? HyphenatedStringToCamelCase<U>
+  : S;
+
+const dataAttributes = [
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/FloatingButton/FloatingButton.ts:19]: allows making hyphenated and camelcase accesses of data attributes type safe

File: packages/embeds/embed-core/index.html [hunk 7]
```diff
@@ -189,318 +190,6 @@ <h3><a href="?only=hideEventTypeDetails">Hide EventType Details Test</a></h3>
       <div class="place">
       </div>
     </div>
-    
-
-    <script>
-      const callback = function (e) {
```
Comment (hariombalhara) [inline packages/embeds/embed-core/index.html:195]: Moved it to separate ts file for validate if types are working correctly.

File: packages/embeds/embed-core/src/embed-iframe.ts [hunk 8]
```diff
@@ -2,18 +2,40 @@ import { useRouter } from "next/router";
...
+  // Store all React State setters here.
+  reactStylesStateSetters: {} as Record<keyof EmbedStyles, SetStyles>,
+  reactNonStylesStateSetters: {} as Record<keyof EmbedNonStylesConfig, setNonStylesConfig>,
+  parentInformedAboutContentHeight: false,
+  windowLoadEventFired: false,
+  setTheme: undefined as ((arg0: string) => void) | undefined,
+  theme: undefined as UiConfig["theme"],
+  uiConfig: undefined as Omit<UiConfig, "styles" | "theme"> | undefined,
+  setUiConfig: undefined as ((arg0: UiConfig) => void) | undefined,
+};
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed-iframe.ts:32]: Instead of doing assertion on entire object, do it per property, so that if a property is missing, it can be identified by typescript.

File: packages/embeds/embed-core/src/embed-iframe.ts [hunk 9]
```diff
@@ -120,15 +132,36 @@ const setEmbedStyles = (stylesConfig: UiConfig["styles"]) => {
...
+  if (registration.styles) {
+    embedStore.reactStylesStateSetters[registration.elementName as keyof EmbedStyles] = registration.setState;
+    registration.setState(embedStore.styles || {});
+    return () => {
+      delete embedStore.reactStylesStateSetters[registration.elementName];
+    };
+  } else {
+    embedStore.reactNonStylesStateSetters[registration.elementName as keyof EmbedNonStylesConfig] =
+      registration.setState;
+    registration.setState(embedStore.nonStyles || {});
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed-iframe.ts:159]: nonStyles config wasn't handled correctly. It fixes that bug. Due to this `align` and `branding` wouldn't work correctly.

File: packages/embeds/embed-core/src/embed-iframe.ts [hunk 10]
```diff
@@ -293,7 +322,14 @@ export const methods = {
   },
 };
 
-const messageParent = (data: any) => {
+export type InterfaceWithParent = {
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed-iframe.ts:325]: This gives type-safety to parent code to invoke a particular fn with it's args.

File: packages/embeds/embed-core/src/embed-iframe.ts [hunk 11]
```diff
@@ -393,35 +429,18 @@ if (isBrowser) {
...
       const detail = e.detail;
-      //console.log(detail.fullType, detail.type, detail.data);
       log(detail);
       messageParent(detail);
     });
 
-    // This event should be fired whenever you want to let the content take automatic width which is available.
-    // Because on cal-iframe we set explicty width to make it look inline and part of page, there is never space available for content to automatically expand
-    // This is a HACK to quickly tell iframe to go full width and let iframe content adapt to that and set new width.
-    sdkActionManager?.on("__refreshWidth", () => {
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed-iframe.ts:404]: __refreshWidth event has been deleted now. So, it was dead code.

File: packages/embeds/embed-core/src/embed.ts [hunk 12]
```diff
@@ -1,11 +1,20 @@
...
 import { Inline } from "./Inline/inline";
 import { ModalBox } from "./ModalBox/ModalBox";
-import type { methods, UiConfig } from "./embed-iframe";
+import type { InterfaceWithParent, interfaceWithParent, UiConfig } from "./embed-iframe";
 import css from "./embed.css";
+import type { EventData, EventDataMap } from "./sdk-action-manager";
 import { SdkActionManager } from "./sdk-action-manager";
-import allCss from "./tailwind.generated.css";
-
+import allCss from "./tailwind.generated.css?inline";
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed.ts:9]: New version of Vite has deprecated importing text like this without ?inline parameter.

File: packages/embeds/embed-core/src/embed.ts [hunk 13]
```diff
@@ -18,10 +27,20 @@ customElements.define("cal-inline", Inline);
 declare module "*.css";
 type Namespace = string;
 type Config = {
-  origin: string;
+  calOrigin: string;
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed.ts:30]: Makes the naming for calOrigin consistent. At few places it was being referred as `origin` and at some other places it is `calOrigin`.

File: packages/embeds/embed-core/src/embed.ts [hunk 14]
```diff
@@ -203,23 +258,119 @@ export class Cal {
...
   }
 
-  getConfig() {
-    return this.__config;
+  constructor(namespace: string, q: IArguments[]) {
+    this.__config = {
+      // Use WEBAPP_URL till full page reload problem with website URL is solved
+      calOrigin: WEBAPP_URL,
+    };
+    this.api = new CalApi(this);
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed.ts:288]: Now the public facing api is stored here,

File: packages/embeds/embed-core/src/embed.ts [hunk 15]
```diff
@@ -251,16 +402,13 @@ export class Cal {
...
       },
     });
-    config = config || {};
-    // Keeping auto-scroll disabled for two reasons:
-    // - If user scrolls the content to an appropriate position, it again resets it to default position which might not be for the liking of the user
-    // - Sometimes, the position can be wrong(e.g. if there is a fixed position header on top coming above the iframe content).
-    // Best solution might be to autoscroll only if the iframe is not fully visible, detection of full visibility might be tough
 
-    // We need to keep in mind that autoscroll is meant to solve the problem when on a certain view(which is availability page right now), the height goes too high and then suddenly it becomes normal
-    (config as unknown as any).__autoScroll = !!(config as unknown as any).__autoScroll;
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed.ts:261]: It wasn't being used now. AutoScroll is automatically handled in a better way,

File: packages/embeds/embed-core/src/embed.ts [hunk 16]
```diff
@@ -310,58 +459,73 @@ export class Cal {
...
     if (existingModalEl) {
       existingModalEl.setAttribute("state", "started");
       return;
     }
+    if (typeof config.iframeAttrs === "string" || config.iframeAttrs instanceof Array) {
+      throw new Error("iframeAttrs should be an object");
+    }
     config.embedType = "modal";
-    const iframe = this.createIframe({ calLink, queryObject: Cal.getQueryObject(config) });
+    const iframe = this.cal.createIframe({ calLink, calOrigin, queryObject: Cal.getQueryObject(config) });
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed.ts:507]: Because 'modal' is a method on CalApi now, refer to createIframe through this.cal

File: packages/embeds/embed-core/src/embed.ts [hunk 17]
```diff
@@ -571,38 +643,45 @@ window.addEventListener("message", (e) => {
...
+
   if (!api) {
     throw new Error(`Namespace ${namespace} isn't defined`);
   }
+
   api("modal", {
     calLink: path,
     config,
     uid: modalUniqueId,
+    calOrigin,
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed.ts:685]: modal now supports configuring `calOrigin`.

File: packages/embeds/embed-core/src/preview.ts [hunk 18]
```diff
@@ -2,18 +2,17 @@ const WEBAPP_URL =
   import.meta.env.EMBED_PUBLIC_WEBAPP_URL || `https://${import.meta.env.EMBED_PUBLIC_VERCEL_URL}`;
 const EMBED_LIB_URL = import.meta.env.EMBED_PUBLIC_EMBED_LIB_URL || `${WEBAPP_URL}/embed/embed.js`;
 
-(window as any).fingerprint = import.meta.env.EMBED_PUBLIC_EMBED_FINGER_PRINT as string;
-
 // Install Cal Embed Code Snippet
 (function (C, A, L) {
+  // eslint-disable-next-line @typescript-eslint/no-explicit-any
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/preview.ts:7]: This is the snippet included in preview.ts. It is already typed well in embed-snippet, so no need to focus on types here.

File: packages/embeds/embed-core/src/preview.ts [hunk 19]
```diff
@@ -23,42 +22,49 @@ const EMBED_LIB_URL = import.meta.env.EMBED_PUBLIC_EMBED_LIB_URL || `${WEBAPP_UR
...
+        //@ts-ignore
+        typeof namespace === "string" ? (cal.ns[namespace] = api) && p(api, ar) : p(cal, ar);
         return;
       }
       p(cal, ar);
     };
 })(window, EMBED_LIB_URL, "init");
 
 const previewWindow = window;
+previewWindow.Cal.fingerprint = import.meta.env.EMBED_PUBLIC_EMBED_FINGER_PRINT as string;
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/preview.ts:42]: Store fingerprint on Cal in preview also.

File: packages/embeds/embed-core/src/sdk-action-manager.ts [hunk 20]
```diff
@@ -9,6 +9,53 @@ function _fireEvent(fullName: string, detail: CustomEventDetail) {
   window.dispatchEvent(event);
 }
 
+export type EventDataMap = {
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/sdk-action-manager.ts:12]: This is a map of all events/actions and their data.

File: packages/embeds/embed-core/tsconfig.json [hunk 21]
```diff
@@ -1,6 +1,7 @@
 {
   "extends": "@calcom/tsconfig/base.json",
   "compilerOptions": {
+    "target": "ES2015",
```
Comment (hariombalhara) [inline packages/embeds/embed-core/tsconfig.json:4]: observedAttributes work on ES2015 plus only.

File: packages/embeds/embed-react/floating.html [hunk 22]
```diff
@@ -0,0 +1,10 @@
+<html>
+  <head>
```
Comment (hariombalhara) [inline packages/embeds/embed-react/floating.html:2]: Made a separate test page to test floating popup with embed-react. Earlier it was tested along with inline and it had side effects of inline usage.

**Review by hariombalhara — COMMENTED** [review]
Self review done

**Review by zomars — APPROVED** [review]
LGTM

Testing locally before merging 🙏🏽
