### PR TITLE
fix: cal video recording email

### LINKED ISSUE #12076: [CAL-2645] Daily video recordings email
Sometimes emails are not sent with video recording link

<sub>[CAL-2645](https://linear.app/calcom/issue/CAL-2645/daily-video-recordings-email)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
Fixes https://github.com/calcom/cal.com/issues/12076

2) Show "View Recordings" button only when video recording exist

Added another button "Check for Recordings" just in case isRecorded field in DB is not updated to true due to error or failure. User would still be check if there are any recordings

Email:- 

https://github.com/calcom/cal.com/assets/53316345/75ea94c9-c54b-4ced-a97d-d9e867e0e253

https://github.com/calcom/cal.com/assets/53316345/d913778b-c4d8-45cf-8a16-c1e76efdb0ee

### CODE REVIEW

File: apps/web/pages/api/recorded-daily-video.ts [hunk 1]
```diff
@@ -135,14 +179,33 @@ async function handler(req: NextApiRequest, res: NextApiResponse) {
 
     const attendeesList = await Promise.all(attendeesListPromises);
 
+    console.log("AttendeesList", attendeesList);
```
Comment (emrysal) [inline apps/web/pages/api/recorded-daily-video.ts:182]: Debug artifacts

File: apps/web/pages/api/recorded-daily-video.ts [hunk 2]
```diff
@@ -202,7 +265,7 @@ async function handler(req: NextApiRequest, res: NextApiResponse) {
 
     return res.status(403).json({ message: "User does not have team plan to send out emails" });
   } catch (err) {
-    console.warn("something_went_wrong", err);
+    console.warn("recorded daily video", err);
```
Comment (emrysal) [inline apps/web/pages/api/recorded-daily-video.ts:268]: Non ideal warning message.

**Review by emrysal — DISMISSED** [review]

**Review by emrysal — APPROVED** [review]
Looks good to me :)
