### PR TITLE
fix: fixed language translations

### LINKED ISSUE #20482: [CAL-5394] 'Confirm' to disable emails only working in english
The confirmation to disable emails doesn't work in different languages, you always have to type 'confirm'. It's in the advanced event-type settings in a team event type (only for orgs):

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-5394](https://linear.app/calcom/issue/CAL-5394/confirm-to-disable-emails-only-working-in-english)</sub>

### PR DESCRIPTION
**Pull request by Neon-20**
## What does this PR do?

- Fixes #20482 (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Visual Demo (For contributors especially)

A visual demonstration is strongly recommended, for both the original and new change **(video / image - any one)**.

#### Video Demo (if applicable):

- Show screen recordings of the issue or feature.
- Demonstrate how to reproduce the issue, the behavior before and after the change.

#### Image Demo (if applicable):

- Add side-by-side screenshots of the original and updated change.
- Highlight any significant change(s).

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

### CODE REVIEW

File: packages/features/eventtypes/components/tabs/advanced/DisableAllEmailsSetting.tsx [hunk 1]
```diff
@@ -61,7 +62,7 @@ export const DisableAllEmailsSetting = ({
               "text-default mb-1 mt-2 text-sm",
               customClassNames?.confirmationDialog?.confirmInput?.label
             )}>
-            {t("type_confirm_to_continue")}
+            {t("type_confirm_to_continue", { confirmText: confirmationString })}
```
Comment (retrogtx) [inline packages/features/eventtypes/components/tabs/advanced/DisableAllEmailsSetting.tsx:65]: will this actually work? the locale `type_confirm_to_continue` is already being used, I don't think an extra parameter changes anything.

Comment (Neon-20) [reply packages/features/eventtypes/components/tabs/advanced/DisableAllEmailsSetting.tsx]: fixed it.

**Comment by retrogtx** [comment]
now it works, thanks!

image

**Review by retrogtx — APPROVED** [review]
