### PR TITLE
fix: rate limit auth

### LINKED ISSUE #3819: Rate limiting
### Issue Summary
Rate limit needed  #3820 will fix this

### PR DESCRIPTION
**Pull request by agustif**
## What does this PR do?
Adds rate limiting. (10 tries per minute) to our login./auth process, this applies both to email/password and 2fa totpCode auth. It uses user.email as key for the cache to check if more than the limit has been requested

Fixes #3819

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
- [ ] Try to login, input a bad password 10 times,
- [ ] or try to login with a 2fa enabled account, try to input a random bad 2fa code more than ten times
image

### CODE REVIEW

File: packages/lib/rateLimit.ts [hunk 1]
```diff
@@ -0,0 +1,26 @@
+/* eslint-disable @typescript-eslint/no-explicit-any */
+import LRU from "lru-cache";
```
Comment (zomars) [inline packages/lib/rateLimit.ts:2]: What's the benefit of using this over `memory-cache` ?

**Review by zomars — COMMENTED** [review]
LGTM. Left a Q there 🙏🏽

File: packages/lib/rateLimit.ts (hunk 1 above)
Comment (agustif) [reply packages/lib/rateLimit.ts:2]: I just ported the work from https://github.com/calcom/website/pull/70 

I can replace it for memory-cache =) good catch!

we can look into rate limiting requests later with lru cache or similar for other api endpoints, maybe even a rateLimiting middlware/handler

Comment (agustif) [reply packages/lib/rateLimit.ts:2]: Looking at google because I had no idea but this is the difference over both:
`**Least-recently-used (LRU) evicts the key-value used-the-least when the cache is full and it needs to add a value. Whereas a MemoryCache evicts the oldest key-values, or those past their 'use-by-date' if they happen to have one.Sep 19, 2015**`

Comment (zomars) [reply packages/lib/rateLimit.ts:2]: I'm just trying to keep dependencies as low as possible. Feel free to migrate either of those.

**Review by pumfleet — COMMENTED** [review]
Code looks good to me, needs testing though

File: yarn.lock [hunk 2]
```diff
@@ -17351,7 +17438,7 @@ next-api-middleware@^1.0.1:
   dependencies:
     debug "^4.3.2"
 
-next-auth@^4.10.3:
+next-auth@^4.10.3, next-auth@^4.3.3:
```
Comment (zomars) [inline yarn.lock:17441]: We have a version mismatch here @agustif let's sync all submodules before committing the `yarn.lock` file. Or since we're not adding more dependencies, discard it altogether

Comment (agustif) [reply yarn.lock]: yes, removed all yarn.lock changes since we're not adding a new dep `lru-cache` and its types anymore, good catch thanks zomars

File: packages/lib/rateLimit.ts (hunk 1 above)
Comment (agustif) [reply packages/lib/rateLimit.ts]: Fixed and using memory-cache now!

**Review by zomars — APPROVED** [review]

**Review by zomars — CHANGES_REQUESTED** [review]
Onboarding tests are failing @agustif let's check those first 🙏🏽

**Review by zomars — CHANGES_REQUESTED** [review]
It seems like this PR has a major flaw, I could be wrong tho. It seems like this is limiting the endpoint calls globally instead of per users/requester.

**Comment by agustif** [comment]
> It seems like this PR has a major flaw, I could be wrong tho. It seems like this is limiting the endpoint calls globally instead of per users/requester.

I will test it out more, I'm passing user.email as the -token- to be tracked, so I dont know something could be wrong with the rateLimit util logic tho, thanks for spotting @zomars

**Comment by zomars** [comment]
> > It seems like this PR has a major flaw, I could be wrong tho. It seems like this is limiting the endpoint calls globally instead of per users/requester.
> 
> I will test it out more, I'm passing user.email as the -token- to be tracked, so I dont know something could be wrong with the rateLimit util logic tho, thanks for spotting @zomars

Also I think this is why E2E is failing since logins occur way to fast and they hit the logins per hour limit

**Comment by agustif** [comment]
> > > It seems like this PR has a major flaw, I could be wrong tho. It seems like this is limiting the endpoint calls globally instead of per users/requester.
> > 
> > 
> > I will test it out more, I'm passing user.email as the -token- to be tracked, so I dont know something could be wrong with the rateLimit util logic tho, thanks for spotting Omar López
> 
> Also I think this is why E2E is failing since logins occur way to fast and they hit the logins per hour limit

Should we do more than 10/hour btw? I can sometimes be stubborn forget a password and see myself trying 20 or 30 times... until blocked

File: apps/web/pages/api/auth/[...nextauth].tsx [hunk 3]
```diff
@@ -100,6 +101,16 @@ const providers: Provider[] = [
         }
       }
 
+      const limiter = rateLimit({
+        interval: 60 * 1000, // 1 minute
+        uniqueTokenPerInterval: 100, // Max 10 login retries per minute
```
Comment (zomars) [inline apps/web/pages/api/auth/[...nextauth].tsx:106]: Why do we need `uniqueTokenPerInterval` here? That's a LRU specific thing for setting max cache size. This doesn't apply to `memory-cache`.

File: apps/web/pages/api/auth/[...nextauth].tsx [hunk 4]
```diff
@@ -100,6 +101,16 @@ const providers: Provider[] = [
...
+      });
+      const { isRateLimited } = await limiter.check(100, user.username); // 10 requests per minute
```
Comment (zomars) [inline apps/web/pages/api/auth/[...nextauth].tsx:108]: - Can the make this function throw instead of returning a `isRateLimited`?
- Why it says `10 request per minute` and we're passing a `100` there?

File: apps/web/pages/api/auth/[...nextauth].tsx (hunk 3 above)
Comment (agustif) [reply apps/web/pages/api/auth/[...nextauth].tsx:106]: Will fix, thanks for spotting it @zomars

File: apps/web/pages/api/auth/[...nextauth].tsx (hunk 4 above)
Comment (agustif) [reply apps/web/pages/api/auth/[...nextauth].tsx:108]: Sure, will change and update, I was testing more requests to see if that fixed the onboarding tests, but what should be the limit we allow? Should it be process.ENV based too in case we want to change this without updating the codebase? @zomars

Comment (zomars) [reply apps/web/pages/api/auth/[...nextauth].tsx:108]: > Should it be process.ENV based too in case we want to change this without updating the codebase?

Not now

**Comment by agustif** [comment]
> It seems like this PR has a major flaw, I could be wrong tho. It seems like this is limiting the endpoint calls globally instead of per users/requester.

Hey @zomars I think the issue was the uniqueTokenPerInterval, seems to be working now and all tests/build is passing too!

Leaving tests to be implemented by @alannnc in a new PR in th future!

File: packages/lib/rateLimit.ts [hunk 5]
```diff
@@ -0,0 +1,27 @@
+/* eslint-disable @typescript-eslint/no-explicit-any */
+import cache from "memory-cache";
+
+import { ErrorCode } from "./auth";
+
+const rateLimit = (options: { interval: number }) => {
+  return {
+    check: (limit: number, token: unknown) => {
```
Comment (zomars) [inline packages/lib/rateLimit.ts:8]:
```suggestion
    check: (limit: number, token: string) => {
```

Correct me if I'm wrong @agustif

File: packages/lib/rateLimit.ts [hunk 6]
```diff
@@ -0,0 +1,27 @@
...
+      const tokenCount: any = cache.get(token) || [0];
```
Comment (zomars) [inline packages/lib/rateLimit.ts:9]:
```suggestion
      const tokenCount = cache.get(token) || [0];
```

No unnecessary  `any`s please

File: packages/lib/rateLimit.ts [hunk 7]
```diff
@@ -0,0 +1,27 @@
+/* eslint-disable @typescript-eslint/no-explicit-any */
+import cache from "memory-cache";
+
+import { ErrorCode } from "./auth";
+
+const rateLimit = (options: { interval: number }) => {
```
Comment (zomars) [inline packages/lib/rateLimit.ts:6]:
```suggestion
const rateLimit = (options: { intervalInMs: number }) => {
```

**Review by zomars — APPROVED** [review]
Thanks again @agustif 🙏🏽
