### PR TITLE
fix: add confirm and reject icon in email

### LINKED ISSUE #7456: [CAL-1167] Buttons icons in needs confirmation email
### Issue Summary

Reported by @PeerRich 

image

we should display cross and check icon instead

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

<sub>[CAL-1167](https://linear.app/calcom/issue/CAL-1167/buttons-icons-in-needs-confirmation-email)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
Fixes https://github.com/calcom/cal.com/issues/7456

Screenshot 2023-03-02 at 2 42 51 AM

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

File: packages/emails/src/components/LinkIcon.tsx [hunk 1]
```diff
@@ -1,11 +1,17 @@
-import { BASE_URL, IS_PRODUCTION } from "@calcom/lib/constants";
-
-export const LinkIcon = ({ secondary }: { secondary?: boolean }) => (
+export const LinkIcon = ({ secondary, iconName }: { secondary?: boolean; iconName: string }) => (
   <img
-    src={IS_PRODUCTION ? BASE_URL + "/emails/linkIcon.png" : "https://app.cal.com/emails/linkIcon.png"}
-    srcSet={IS_PRODUCTION ? BASE_URL + "/emails/linkIcon.svg" : "https://app.cal.com/emails/linkIcon.svg"}
+    src={
+      IS_PRODUCTION ? WEBAPP_URL + `/emails/${iconName}.png` : `https://app.cal.com/emails/${iconName}.png`
```
Comment (hariombalhara) [inline packages/emails/src/components/LinkIcon.tsx:4]: I am not sure why we are keeping this IS_PRODUCTION check.
Shouldn't we just use `${WEBAPP_URL}/emails/${iconName}.png`

File: packages/emails/src/components/LinkIcon.tsx [hunk 2]
```diff
@@ -1,11 +1,17 @@
-import { BASE_URL, IS_PRODUCTION } from "@calcom/lib/constants";
```
Comment (hariombalhara) [inline packages/emails/src/components/LinkIcon.tsx:1]: These imports are being used.

**Review by hariombalhara — DISMISSED** [review]

**Comment by PeerRich** [comment]
hey @Udit-takkar can you look into the specs? The idea is that the buttons look identical like they look in the logged in dashboard (app.cal.com/bookings)

**Review by PeerRich — CHANGES_REQUESTED** [review]
buttons dont look like in dashboard yet

**Comment by Udit-takkar** [comment]
Screenshot 2023-03-09 at 3 12 21 AM

Should be fixed now. ( can't use icons from react-icons because they are not being displayed on email for some reason )

**Comment by PeerRich** [comment]
both the text and icon are not centered. can you make sure it looks exactly like the figma?
image

**Comment by Jaibles** [comment]
> both the text and icon are not centered. can you make sure it looks exactly like the figma? image

😢 Great lengths have been gone to to spec these (and all components) in Figma. Please use them! 
CleanShot 2023-03-09 at 11 27 58@2x
https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=309%3A42062&t=7QcNk9ZAlBEvpGAq-1

And when these aren't available, Figma has an inspect panel to see specs yourself: https://www.figma.com/best-practices/tips-on-developer-handoff/an-overview-of-figma-for-developers/

**Comment by Udit-takkar** [comment]
Screenshot 2023-03-11 at 7 13 54 AM

**Review by PeerRich — APPROVED** [review]
great!

**Comment by PeerRich** [comment]
escalated to high priority
