### PR TITLE
fix: Toast Onclose is removing specific toast

### LINKED ISSUE #9947: Toast onClose not removing specific toast
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Toast component's onClick event not removing specific toast. When clicked any specific toast to remove, all of them are overlapped and removed together.

https://github.com/calcom/cal.com/assets/81948346/ced7d5a3-b515-463b-a329-760fadfdd7b6

### Steps to Reproduce

1. Generate more than one toast
2. Click any toast

### PR DESCRIPTION
**Pull request by anikdhabal**
## What does this PR do?

Fixes #9947

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by emrysal — DISMISSED** [review]
This looks good to me but one minor issue is that it should be renamed `toastId` - our codebase uses lowercase throughout for secondary chars like Uid - etc. - once that's done it's perfect

**Comment by anikdhabal** [comment]
> This looks good to me but one minor issue is that it should be renamed `toastId` - our codebase uses lowercase throughout for secondary chars like Uid - etc. - once that's done it's perfect

Okay, Done

**Comment by anikdhabal** [comment]
> This looks good to me but one minor issue is that it should be renamed `toastId` - our codebase uses lowercase throughout for secondary chars like Uid - etc. - once that's done it's perfect

Done, @emrysal pls check it.

**Review by PeerRich — DISMISSED** [review]
great stuff!

**Review by emrysal — DISMISSED** [review]
Great stuff, thanks!

**Comment by PeerRich** [comment]
i think an E2E test related to toasts has to be adjusted, currently failing

**Comment by anikdhabal** [comment]
> i think an E2E test related to toasts has to be adjusted, currently failing

Ahh yes

File: packages/ui/components/toast/showToast.tsx [hunk 1]
```diff
@@ -72,28 +73,28 @@ export function showToast(
   variant: "success" | "warning" | "error",
   duration = TOAST_VISIBLE_DURATION
 ) {
-  const onClose = () => {
-    toast.dismiss();
+  const onClose = (toastId: string) => {
+    toast.remove(toastId);
```
Comment (hariombalhara) [inline packages/ui/components/toast/showToast.tsx:77]: Do we need to switch to remove ? I think we should use dismiss only as using `remove` would cause dismiss animation to not work.

**Review by hariombalhara — DISMISSED** [review]
Thanks @anikdhabal 🙏
There is failing tests plus left a comment

File: packages/ui/components/toast/showToast.tsx (hunk 1 above)
Comment (anikdhabal) [reply packages/ui/components/toast/showToast.tsx:77]: I think we don't need a delay to remove the toaster. If someone wants to remove a toaster, then he/she wants to remove it quickly with a click. What do you think?

Comment (emrysal) [reply packages/ui/components/toast/showToast.tsx:77]: I agree with this statement, removing a toast is something that should happen asap, an animation isn't needed.

**Comment by anikdhabal** [comment]
> i think an E2E test related to toasts has to be adjusted, currently failing

Done!

**Comment by anikdhabal** [comment]
> Thanks @anikdhabal 🙏 There is failing tests plus left a comment

Done.

**Comment by anikdhabal** [comment]
@PeerRich @emrysal @hariombalhara some E2E test related to toasts has been adjusted.

**Review by emrysal — APPROVED** [review]
