### PR TITLE
test: Bring back broken out-of-office tests, prevent modal button clickable before flicker, and fix timezone issue

### LINKED ISSUE #14287: [CAL-3337] Bring back broken out-of-office tests as per @ #14286
Bring back tests @ https://github.com/calcom/cal.com/pull/14286

<sub>[CAL-3337](https://linear.app/calcom/issue/CAL-3337/bring-back-broken-out-of-office-tests-as-per-14286)</sub>

### PR DESCRIPTION
**Pull request by ImBIOS**
## What does this PR do?

- Fixes #14287
- Fixes [CAL-3337](https://linear.app/calcom/issue/CAL-3337/bring-back-broken-out-of-office-tests-as-per-14286)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set? none
- What are the minimal test data to have? none
- What is expected (happy path) to have (input and output)? i don't have idea what is it
- Any other important info that could help to test that PR:

```
yarn e2e out-of-office.e2e.ts
```

image
image
image
image

## Message

Hey everyone! 👋

I'm working on addressing the issue [CAL-3337] to bring back the broken out-of-office tests. Here's the lowdown on what's happening and how we can fix it! 🚀

#### Cause:
- There's a full page flicker during the hydration period, which causes the Modal state to reset. 😵‍💫
- Our e2e test, Playwright, is opening the modal at superhuman speed, but while waiting for the dropdown data to load, the modal gets reset by the flicker. This results in an error when the element isn't found. 😓

#### Known:
- Why does the flicker happen? Still a mystery! 🔍 I suspect this: https://github.com/calcom/cal.com/blob/5b7f2a6ffcfcda3aa9411fe482fd58519a76ed07/packages/ui/components/meta/Meta.tsx#L52

#### Potential Solutions:
1. **Change the test**:
   - Wait for certain text (like the title) to load, indicating the hydration is done and the flicker has passed. ⏳
2. **Change the code**:
   - **Fix the flicker cause**: If we can identify and resolve the root cause of the flicker, the problem will be solved! 🛠️
   - **Change add button with loading skeleton until flicker passes**: This ensures the UX isn't affected by the modal closing unexpectedly and prevents Playwright from picking the modal before flickering. ✨

Let's tackle this issue and make the tests robust again! 💪💻

If you have any ideas or insights on why the flicker happens, feel free to share! Collaboration is key! 🤝🔧

Note: I'm not using this, because it will require the component to become async, which makes me want to write a new component inside this file for this button, but I'm not doing it, I don't know why:

```ts
  const data = await utils.viewer.outOfOfficeEntriesList.ensureData();
```

### CODE REVIEW

File: apps/web/pages/settings/my-account/out-of-office/index.tsx [hunk 1]
```diff
@@ -375,20 +375,30 @@ const OutOfOfficePage = () => {
...
+            <SkeletonText className="h-8 w-20" />
+          ) : (
+            <Button
+              color="primary"
+              className="flex w-20 items-center justify-between px-4"
+              onClick={() => setOpenModal(true)}
+              data-testid="add_entry_ooo">
+              <Icon name="plus" size={16} /> {t("add")}
+            </Button>
+          )
```
Comment (anikdhabal) [inline apps/web/pages/settings/my-account/out-of-office/index.tsx:401]: Nah, this does not look good for rendering the button conditionally. Instead, you should disable the button

**Review by anikdhabal — CHANGES_REQUESTED** [review]

File: apps/web/pages/settings/my-account/out-of-office/index.tsx [hunk 2]
```diff
@@ -375,20 +375,30 @@ const OutOfOfficePage = () => {
   }, [openModalOnStart]);
 
   const [openModal, setOpenModal] = useState(false);
+
+  const { data } = trpc.viewer.outOfOfficeReasonList.useQuery();
```
Comment (anikdhabal) [inline apps/web/pages/settings/my-account/out-of-office/index.tsx:379]: Can we just extract the` isPending` status and use it instead of this: `const isBeforeFlicker = data?.length === undefined || data.length <= 0;`

Also, I found that this query is called from two different components. I think it would be better to pass the data and isPending status to the <OutOfOfficeEntriesList /> component instead of calling it two time.
Lmk what you think

File: apps/web/pages/settings/my-account/out-of-office/index.tsx [hunk 3]
```diff
@@ -375,20 +375,30 @@ const OutOfOfficePage = () => {
...
+  // TODO: The best solution is we should find the cause of full page flicker
+  // Taling about hydration problem, migrating to appDir might solve the problem automatically
+  // which will reset the Modal state, which makes bad UX and fails (superhuman click speed) E2E tests
```
Comment (anikdhabal) [inline apps/web/pages/settings/my-account/out-of-office/index.tsx:382]: Don't add too many comments; only include them if there's a TODO

File: apps/web/pages/settings/my-account/out-of-office/index.tsx (hunk 1 above)
Comment (ImBIOS) [reply apps/web/pages/settings/my-account/out-of-office/index.tsx:401]: Because it's non-interactive due to waiting for several data to be loaded, isn't the loading state better than just the disabled state? LMKWYT.

File: apps/web/pages/settings/my-account/out-of-office/index.tsx [hunk 4]
```diff
@@ -375,20 +375,30 @@ const OutOfOfficePage = () => {
...
+  const isBeforeFlicker = data?.length === undefined || data.length <= 0;
```
[the remark this answers is not in the document]
Comment (ImBIOS) [reply apps/web/pages/settings/my-account/out-of-office/index.tsx:383]: A hydration error from Next.js popped up before this fix sometimes, preventing the playwright from clicking anything and waiting infinitely. I suspect this because it stated it caused a flicker, but further investigation is suggested.
https://github.com/calcom/cal.com/blob/5b7f2a6ffcfcda3aa9411fe482fd58519a76ed07/packages/ui/components/meta/Meta.tsx#L52

File: apps/web/pages/settings/my-account/out-of-office/index.tsx (hunk 2 above)
Comment (ImBIOS) [reply apps/web/pages/settings/my-account/out-of-office/index.tsx:379]: It seems `isPending` is enough, thanks for noticing.

image

I don't think passing tRPC x React-Query data to a component that uses the same endpoint is the wisest decision because React-Query (even the default Next.js default fetch did this too) will handle the de-duplication using its Context. When we passed the value from the parent, the React Query Context and deduplication became useless. As you can see when we installed `react-query-devtools` the endpoint was just called once and distributed to all components using it.

File: apps/web/pages/settings/my-account/out-of-office/index.tsx (hunk 3 above)
Comment (ImBIOS) [reply apps/web/pages/settings/my-account/out-of-office/index.tsx:382]: I'm on it :smile:

**Review by anikdhabal — CHANGES_REQUESTED** [review]
Hey @ImBIOS ooo e2e test is still failing, can you figure it out and make the final thing

**Comment by ImBIOS** [comment]
found the culprit, it's another problem but I'm looking into it:

```
    throw new TRPCError({ code: "BAD_REQUEST", message: "start_date_must_be_in_the_future" });
 ```

File: packages/trpc/server/routers/loggedInViewer/outOfOffice.handler.ts [hunk 5]
```diff
@@ -25,7 +25,7 @@ export const outOfOfficeCreate = async ({ ctx, input }: TBookingRedirect) => {
 
   const inputStartTime = dayjs(startDate).startOf("day");
   const inputEndTime = dayjs(endDate).endOf("day");
-  const offset = dayjs(inputStartTime).utcOffset();
+  const offset = input.offset;
```
Comment (ImBIOS) [inline packages/trpc/server/routers/loggedInViewer/outOfOffice.handler.ts:28]: Damn, e2e test is real. This LOC culprit makes me laugh hard :rofl:

Comment (ImBIOS) [reply packages/trpc/server/routers/loggedInViewer/outOfOffice.handler.ts:28]: Let me check it one more time to be sure.

Comment (ImBIOS) [reply packages/trpc/server/routers/loggedInViewer/outOfOffice.handler.ts:28]: @anikdhabal I confirmed this issue consists of a flicker issue and that time start timezone offset issue. So these 2 fixes are required to enable these tests.

Comment (anikdhabal) [reply packages/trpc/server/routers/loggedInViewer/outOfOffice.handler.ts:28]: yes, please

Comment (anikdhabal) [inline packages/trpc/server/routers/loggedInViewer/outOfOffice.handler.ts:28]: Hey @ImBIOS Isn't both gives the same result? I think it would be better to use server tz here .

Comment (ImBIOS) [reply packages/trpc/server/routers/loggedInViewer/outOfOffice.handler.ts:28]: `inputStartTime` doesn't have timezone offset data in it -it's just date and time-, that might be the purpose of the engineer who created the OOO feature sent this offset data to the server, but somehow he doesn't consume it in the server. This offset data is required to make the server know what's the time in UTC+0 -the server timezone-.

The server timezone is UTC+0 if it's in the GitHub Actions by default, and the frontend should be UTC+1 if it follows the playwright config which is `Europe/London`. This makes the `inputStartTime` generated by `dayjs` always 1 day before (1 hour before today's start time) the server time.

CMIIW.

If you want, I am also able to write more edge cases for this OOO feature so we do not just test the functional, but also the edge cases, e. g. different timezones, so we can test this offset data, if you agree I'll work on adding more tests for it by God's will.

Comment (anikdhabal) [reply packages/trpc/server/routers/loggedInViewer/outOfOffice.handler.ts:28]: Hey, we don't want today to be set as the start time; rather, the start date must be in the future. If we use the client-side generated offset, it will allow me to set today as the start time. That's why we use the server tz here. Let's not change it. Let's find a different way to fix the test.

Comment (anikdhabal) [reply packages/trpc/server/routers/loggedInViewer/outOfOffice.handler.ts:28]: @ImBIOS look the above message

Comment (ImBIOS) [reply packages/trpc/server/routers/loggedInViewer/outOfOffice.handler.ts:28]: Don't worry, I've been dedicating myself to working on it, since morning. I found something new and interesting.

Is it expected to be able to set today as startTime in UTC- but it cannot be set today for the startTime if we in UTC+ ???

Comment (ImBIOS) [reply packages/trpc/server/routers/loggedInViewer/outOfOffice.handler.ts:28]: > Don't worry, I've been dedicating myself to working on it, since morning. I found something new and interesting.
> 
> Is it expected to be able to set today as startTime in UTC- (e.g. America/Phoenix) but it cannot be set today for the startTime if we are in UTC+ (e.g. Asia/Jakarta) ??? Is this inconsistent behavior expected?
> 
> I found this interesting behavior when I was trying to add several E2E edge cases on timezone-difference users. And it happens when I use this:
> 
> ```
>   const offset = dayjs(inputStartTime).utcOffset();
> ```
> 
> I'm not testing with `input.offset` yet because you suggested. I revert to using server tz, so I'm working on testing the behavior when using server tz, to make sure it's working as expected.

Something weird, now I can't reproduce this finding. The tests always fail from morning to afternoon, but since 15 minutes ago, these tests always succeeded no matter what timezone I tested it from.

If God wills, I'll keep update to test it. But for now, et's use the server tz, I'll push it now.

Comment (ImBIOS) [reply packages/trpc/server/routers/loggedInViewer/outOfOffice.handler.ts]: Sorry for the drama, I've figured out the root cause. On my way to pushing it...

Comment (anikdhabal) [reply packages/trpc/server/routers/loggedInViewer/outOfOffice.handler.ts]: All good. You're doing great work

Comment (ImBIOS) [reply packages/trpc/server/routers/loggedInViewer/outOfOffice.handler.ts]: wait.. I wannna add some bonus to prevent this kind of bug happen ever again.

Comment (ImBIOS) [reply packages/trpc/server/routers/loggedInViewer/outOfOffice.handler.ts]: I added tests against this code for all time zones to make sure no timezone facing this issue.

Comment (ImBIOS) [reply packages/trpc/server/routers/loggedInViewer/outOfOffice.handler.ts]: @anikdhabal This bug might be solved and the e2e tests might passed, but for your information... some timezones have a 1-day range (e.g. 3 - 4) as the default value in the modal date range and I noticed some timezones will have a 2-day range (e.g. 3 - 5) as the default value, because it's another issue which -in my opinion- should be a patch bug, I'm not addressing this issue as of right now.

File: apps/web/playwright/fixtures/types.ts [hunk 6]
```diff
@@ -1,4 +1,27 @@
...
+  RUSSIA = "Europe/Moscow", // UTC+3
+  UAE = "Asia/Dubai", // UTC+4
+  PAKISTAN = "Asia/Karachi", // UTC+5
+  BANGLADESH = "Asia/Dhaka", // UTC+6
+  SINGAPORE = "Asia/Singapore", // UTC+8
+  JAPAN = "Asia/Tokyo", // UTC+9
+  AUSTRALIA = "Australia/Sydney", // UTC+10
+  SOLOMON_ISLANDS = "Pacific/Guadalcanal", // UTC+11
+  NEW_ZEALAND = "Pacific/Auckland", // UTC+12
 }
```
Comment (ImBIOS) [inline apps/web/playwright/fixtures/types.ts:27]: @anikdhabal I'm just following the existing naming format for the enums, but I recommend using timezone explicit as the key e.g. `UTC`, `UTC_PLUS_7`, etc. for better readability. Or maybe for this test, we can create new enums (?)

**Comment by ImBIOS** [comment]
@anikdhabal any update on review?

**Review by anikdhabal — APPROVED** [review]
LGTM!!
