### PR TITLE
fix: people filter in /bookings and create OOO modal

### LINKED ISSUE #17402: [CAL-4647] Booking filter by people not working
* Filter by people in /bookings are slow and laggy
* When you filter by a user it also returns booking where user is not not present as it only checks the host in the round robin event type but not every host is organizer.
  
  [https://app.campsite.com/cal/posts/u9r7dbhwwbrp](https://app.campsite.com/cal/posts/u9r7dbhwwbrp)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4647](https://linear.app/calcom/issue/CAL-4647/booking-filter-by-people-not-working)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

- Fixes https://github.com/calcom/cal.com/issues/17402 (GitHub issue number)
- Fixes CAL-4647 (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] N/A I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

1) Go to /bookings/upcoming and use filter by people

2) Go to setting and create an OOO entry and assign it to some one else

### CODE REVIEW

File: packages/features/settings/outOfOffice/CreateOrEditOutOfOfficeModal.tsx [hunk 1]
```diff
@@ -209,28 +235,53 @@ export const CreateOrEditOutOfOfficeEntryModal = ({
...
-                        <Select<Option>
-                          name="toTeamUsername"
-                          data-testid="team_username_select"
-                          value={memberListOptions.find((member) => member.value === value)}
-                          placeholder={t("select_team_member")}
-                          isSearchable
-                          options={memberListOptions}
-                          onChange={(selectedOption) => {
-                            if (selectedOption?.value) {
-                              onChange(selectedOption.value);
```
Comment (Udit-takkar) [inline packages/features/settings/outOfOffice/CreateOrEditOutOfOfficeModal.tsx:228]: Replaced React Select similar to https://github.com/calcom/cal.com/pull/17386

File: packages/trpc/server/routers/viewer/bookings/get.handler.ts [hunk 2]
```diff
@@ -114,6 +114,7 @@ export async function getBookings({
                     userId: {
                       in: filters.userIds,
                     },
+                    isFixed: true,
```
Comment (Udit-takkar) [inline packages/trpc/server/routers/viewer/bookings/get.handler.ts:117]: only fetch the bookings where host is fixed or booker.userId is filters.userIds

File: packages/trpc/server/routers/viewer/teams/legacyListMembers.handler.ts [hunk 3]
```diff
@@ -21,49 +21,93 @@ export const legacyListMembers = async ({ ctx, input }: ListMembersOptions) => {
...
         },
       },
     },
+    distinct: ["userId"],
+    cursor: cursor ? { id: cursor } : undefined,
+    take: limit ? limit + 1 : undefined,
+    orderBy: [
+      { userId: "asc" }, // First order by userId to ensure consistent ordering
+      { id: "asc" }, // Then by id as secondary sort
+    ],
```
Comment (Udit-takkar) [inline packages/trpc/server/routers/viewer/teams/legacyListMembers.handler.ts:84]: For pagination and making sure no duplicate user's are fetched

File: packages/trpc/server/routers/viewer/teams/legacyListMembers.handler.ts [hunk 4]
```diff
@@ -21,49 +21,93 @@ export const legacyListMembers = async ({ ctx, input }: ListMembersOptions) => {
...
+  const enrichedMembers = await Promise.all(
+    memberships.map(async (membership) =>
+      UserRepository.enrichUserWithItsProfile({
+        user: {
+          ...membership.user,
+          accepted: membership.accepted,
+          membershipId: membership.id,
+        },
+      })
+    )
```
Comment (Udit-takkar) [inline packages/trpc/server/routers/viewer/teams/legacyListMembers.handler.ts:96]: Earlier we were fetching all the members and then while iterating removing duplicate and then iterating again with `enrichUserWithItsProfile`

Comment (Udit-takkar) [reply packages/trpc/server/routers/viewer/teams/legacyListMembers.handler.ts:96]: Now i have moved all the logic inside query

File: packages/features/bookings/components/PeopleFilter.tsx [hunk 5]
```diff
@@ -21,16 +21,23 @@ export const PeopleFilter = () => {
...
+  const debouncedSearch = useDebounce(searchText, 500);
 
-  const filteredMembers = members?.data
-    ?.filter((member) => member.accepted)
-    ?.filter((member) =>
-      searchText.trim() !== ""
-        ? member?.name?.toLowerCase()?.includes(searchText.toLowerCase()) ||
-          member?.username?.toLowerCase()?.includes(searchText.toLowerCase())
-        : true
-    );
```
Comment (Udit-takkar) [inline packages/features/bookings/components/PeopleFilter.tsx:33]: Moved the filtering to the endpoint

File: packages/features/settings/outOfOffice/CreateOrEditOutOfOfficeModal.tsx [hunk 6]
```diff
@@ -43,21 +48,39 @@ export const CreateOrEditOutOfOfficeEntryModal = ({
...
     label: string;
+    avatarUrl: string | null;
   }[] =
-    listMembers
+    members?.data?.pages
+      .flatMap((page) => page.members)
       ?.filter((member) => me?.data?.id !== member.id)
       .map((member) => ({
         value: member.id,
         label: member.name || "",
```
Comment (sean-brydon) [inline packages/features/settings/outOfOffice/CreateOrEditOutOfOfficeModal.tsx:74]: I think we need to fall back to email here because when no names are set you get this weird state in the OOO list
image

**Review by sean-brydon — CHANGES_REQUESTED** [review]
I think we should fix this for users who have not completed on boarding (Don't think this was introduced in this PR but we should fix here either way)

File: packages/features/settings/outOfOffice/CreateOrEditOutOfOfficeModal.tsx (hunk 6 above)
Comment (sean-brydon) [reply packages/features/settings/outOfOffice/CreateOrEditOutOfOfficeModal.tsx]: Fixed here: https://github.com/calcom/cal.com/pull/17396/commits/c9a45137bb09027e803c78e32b2e597bad7a5541 fall back to username instead

**Review by sean-brydon — DISMISSED** [review]
LGTM - i made them changes i pointed out in a recent commit

**Comment by keithwillcode** [comment]
@Udit-takkar There are consistently failing E2E tests

**Comment by sean-brydon** [comment]
> @Udit-takkar There are consistently failing E2E tests

Fixed

**Review by sean-brydon — APPROVED** [review]

**Comment by Udit-takkar** [comment]
@sean-brydon thanks for fixing the tests
