### PR TITLE
fix: og image

### LINKED ISSUE #13777: [CAL-3175] og-image broken for website and for app.cal.com
[https://www.opengraph.xyz/url/https%3A%2F%2Fcal.com%2Fpeer](https://www.opengraph.xyz/url/https%3A%2F%2Fcal.com%2Fpeer)

image

image

image

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3175](https://linear.app/calcom/issue/CAL-3175/og-image-broken-for-website-and-for-appcalcom)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

This url works (without CAL_URL in url param)

https://cal.com/_next/image?w=1200&q=100&url=%2Fapi%2Fsocial%2Fog%2Fimage%3Ftype%3Dmeeting%26title%3DMeeting%26meetingProfileName%3DPeer%2520Richelsen%26meetingImage%3Dhttps%253A%252F%252Fcal.com%252Fapi%252Favatar%252F6480c992-64c2-4ae4-8210-b3086d72439c.png%26names%3DPeer%2520Richelsen%26usernames%3Dpeer

but current one doesn't  (with CAL_URL in url param)

https://cal.com/_next/image?w=1200&q=100&url=https%3A%2F%2Fcal.com%2Fapi%2Fsocial%2Fog%2Fimage%3Ftype%3Dmeeting%26title%3DMeeting%26meetingProfileName%3DPeer%2520Richelsen%26meetingImage%3Dhttps%253A%252F%252Fcal.com%252Fapi%252Favatar%252F6480c992-64c2-4ae4-8210-b3086d72439c.png%26names%3DPeer%2520Richelsen%26usernames%3Dpeer

Fixes https://github.com/calcom/cal.com/issues/13777

Screenshot 2024-02-22 at 8 00 49 PM

https://www.opengraph.xyz/url/https%3A%2F%2Fcal.com%2Fpeer

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/lib/constants.ts [hunk 1]
```diff
@@ -83,7 +83,7 @@ export const SEO_IMG_DEFAULT = `${CAL_URL}/og-image.png`;
 // parameters you pass to the /api/social/og/image endpoint, you wrap them in encodeURIComponent
 // as well, otherwise the URL won't be valid.
 export const SEO_IMG_OGIMG = `${CAL_URL}/_next/image?w=1200&q=100&url=${encodeURIComponent(
-  `${CAL_URL}/api/social/og/image`
+  `/api/social/og/image`
```
Comment (keithwillcode) [inline packages/lib/constants.ts:86]: This was explicitly changed by @zomars [here](https://threads.com/thread/34565411679/34565415082?s=dh8JPHDmxNbZtxyuXh3uVR). Will reverting it back break something else that was fixed here @zomars?

Comment (Udit-takkar) [reply packages/lib/constants.ts:86]: yeah i don't think we should have changed that. You can visit both of the url in the PR description. the second one returns 400 INVALID_IMAGE_OPTIMIZE_REQUEST

Comment (zomars) [reply packages/lib/constants.ts:86]: I'm basing my answer on @JeroenReumkens original testing URLs which used all fully formed URLs:

https://github.com/calcom/cal.com/blob/8e9744412912fbe3a9c49ed384f1b932764ed8a3/packages/lib/OgImages.tsx#L51-L58

My guess is that in this case it should be app.cal.com instead of cal.com

Comment (zomars) [reply packages/lib/constants.ts:86]: So using WEBAPP_URL instead of CAL_URL should work

**Review by zomars — APPROVED** [review]

File: packages/lib/constants.ts (hunk 1 above)
Comment (Udit-takkar) [reply packages/lib/constants.ts:86]: I also tried WEBAPP_URL (app.cal.com). it wasn't working

**Comment by zomars** [comment]
Will hotpatch to prod @calcom/foundation
