### PR TITLE
fix: revalidation replacing availability form values

### LINKED ISSUE #14113: [CAL-3280] Flakiness caused due to revalidation in availability forms
There's currently some flaky tests on main so I took into investgating and found an actual bug. We had some RHF forms that were being initialized with `values` instead of `deafultValue` causing the values to be replaced just before the form is submitted. Introducing a 50/50 chance of the tests to fail.

At first I've though this could be an issue with the click handler not being picked up properly but discarded after confirming:

Noticed the array field was being updated correctly but then it was resetting back to the initial value suddenly.

This pointed me to the right direction. Will publish a PR with fix soon.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3280](https://linear.app/calcom/issue/CAL-3280/flakiness-caused-due-to-revalidation-in-availability-forms)</sub>

### PR DESCRIPTION
**Pull request by zomars**
## What does this PR do?

Fixes #14113

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Run `yarn e2e apps/web/playwright/availability.e2e.ts` several times. At least 10 times. It should pass always.

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

File: apps/web/pages/availability/[schedule].tsx [hunk 1]
```diff
@@ -177,26 +178,43 @@ const SmallScreenSideBar = ({ open, children }: { open: boolean; children: JSX.E
...
 
+  // TODO: reimplement Skeletons for this page in here
+  if (isPending) return null;
+
+  if (!schedule) return null;
+
+  // We wait for the schedule to be loaded before rendering the form since `defaultValues`
+  // cannot be redeclared after first render. And using `values` will trigger a form reset
+  // when revalidating.
+  return <AvailabilityForm schedule={schedule} isPending={isPending} />;
```
Comment (zomars) [inline apps/web/pages/availability/[schedule].tsx:200]: This is important

File: apps/web/pages/availability/[schedule].tsx [hunk 2]
```diff
@@ -177,26 +178,43 @@ const SmallScreenSideBar = ({ open, children }: { open: boolean; children: JSX.E
...
+  const utils = trpc.useUtils();
+  const me = useMeQuery();
+  const scheduleId = searchParams?.get("schedule") ? Number(searchParams.get("schedule")) : -1;
+  const fromEventType = searchParams?.get("fromEventType");
+  const { timeFormat } = me.data || { timeFormat: null };
+  const [openSidebar, setOpenSidebar] = useState(false);
+
   const form = useForm<AvailabilityFormValues>({
-    values: schedule && {
+    defaultValues: {
```
Comment (zomars) [inline apps/web/pages/availability/[schedule].tsx:215]: If we're going to use values. At least we should use `resetOptions: { keepDirtyValues: true }` as stated in [the docs](https://react-hook-form.com/faqs#Howtoinitializeformvalues). But IMO is better to ensure initial data is always defined when initializing the form to avoid side effects.

**Review by zomars — COMMENTED** [review]
Self review done

**Review by alishaz-polymath — DISMISSED** [review]
Nice! 🙏

**Comment by Ryukemeister** [comment]
@zomars @alishaz-polymath can we hold this for the time being and merge it after #14106 since this can cause merge conflicts for the platform atoms and v2 PR

File: packages/platform/atoms/availability/AvailabilitySettings.tsx [hunk 3]
```diff
@@ -78,7 +77,7 @@ type AvailabilitySettingsProps = {
     workingHours: WorkingHours[];
     dateOverrides: { ranges: TimeRange[] }[];
     timeZone: string;
-    schedule: Schedule[] | [];
+    schedule: Schedule[];
```
Comment (zomars) [inline packages/platform/atoms/availability/AvailabilitySettings.tsx:80]: Redundant typing. And empty array is still a valid `Schedule[]`

File: packages/platform/atoms/availability/AvailabilitySettings.tsx [hunk 4]
```diff
@@ -239,9 +238,9 @@ export function AvailabilitySettings({
   const { t, i18n } = useLocale();
 
   const form = useForm<AvailabilityFormValues>({
-    values: schedule && {
+    defaultValues: {
```
Comment (zomars) [inline packages/platform/atoms/availability/AvailabilitySettings.tsx:241]: Ported my fix to the new atom location

**Review by zomars — COMMENTED** [review]
Fixed merge conflicts. Ready for re-review. @Ryukemeister @alishaz-polymath

**Review by emrysal — APPROVED** [review]
Good to go now the atom is merged
