### PR TITLE
fix(web): set canonical as `https://cal.com` in the `<HeadSeo/>`

### LINKED ISSUE #6726: [CAL-933] on cal.com, add canonical metatag for cal.com/<username> pages
right now we have both: https://app.cal.com/peer and https://cal.com/peer

we need a canonical meta tag in that page that says the default URL is cal.com/peer to prevent duplicate content

<sub>[CAL-933](https://linear.app/calcom/issue/CAL-933/on-calcom-add-canonical-metatag-for-calcomusername-pages)</sub>

### PR DESCRIPTION
**Pull request by p6l-richard**
## What does this PR do?

This PR handles canonicalization of the `web` app's pages that are deployed to both `app.cal.com` & `cal.com` (see [issue](https://github.com/calcom/website/issues/416)).

Fixes https://github.com/calcom/cal.com/issues/6726
note: see [#416](https://github.com/calcom/website/issues/416) for some context

CleanShot 2023-01-25 at 11 18 28@2x

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] `yarn test-e2e` should pass
- [ ] Inspect a couple of pages manually to re-evaluate the canonical tag

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/ui/components/head-seo/HeadSeo.tsx [hunk 1]
```diff
@@ -72,13 +73,15 @@ const buildSeoMeta = (pageProps: {
 };
 
 export const HeadSeo = (props: HeadSeoProps): JSX.Element => {
-  const defaultUrl = getBrowserInfo()?.url;
+  // build the canonical url to ensure it's always cal.com (not app.cal.com)
+  const router = useRouter();
+  const calcomUrl = (`https://cal.com` + (router.asPath === "/" ? "" : router.asPath)).split("?")[0]; // cut off search params
+  const defaultUrl = IS_SELF_HOSTED ? getBrowserInfo()?.url : calcomUrl;
```
Comment (PeerRich) [inline packages/ui/components/head-seo/HeadSeo.tsx:79]: we can use isCalcom here https://github.com/calcom/cal.com/blob/main/packages/lib/isCalcom.ts

Comment (p6l-richard) [reply packages/ui/components/head-seo/HeadSeo.tsx]: Updated to use it [here](https://github.com/calcom/cal.com/pull/6693/commits/2f47eb2c09c32227df38ad523f929881ed9e865f).

I think we could still need the `(router.asPath === "/" ? "" : router.asPath)` though as we still have to omit the trailing slash on the homepage?

**Review by PeerRich — APPROVED** [review]
