### PR TITLE
fix: rescheduling in require confirmation

### LINKED ISSUE #11075: Calendar issues with requires confirmation feature
### Issue Summary

> If an attendee reschedules an event, they will receive the "Booking submitted" email; stating that the host still needs to confirm or reject the booking. Almost instantly after this email, they receive a subsequent email stating the Event has been updated and includes the updated .ics which will update the calendar slot for both the host and attendee. 
When checking the "Upcoming" bookings page on cal.com - the event is still pending as unconfirmed: If confirmed, it will result in two booking slots in both calendars. If rejected, the "bug" event/slot will still appear in both calendars - making the attendees believe they still have a booked event. Hmmm.. Makes me unsure of the switch.
Also, if adding payment with Stripe - after the booking is paid, the attendee will receive an email (with .ics invite) stating that the event has been scheduled; again with the booking being unconfirmed in the system and with the same issue upon confirming/rejecting the booking.

[Reference link](https://discord.com/channels/1125390093386010654/1144648154160054345/1144648154160054345)

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/11075

BEFORE:

Meeting has been rescheduled email and calendar event after submitting booking without confirming the meeting (require confirmation event type).

Screenshot 2023-09-05 at 7 45 44 PM

AFTER:-

event scheduled email and calendar event created only after "awaiting approval" meeting has been confirmed.

Screenshot 2023-09-05 at 7 47 22 PM

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

1) Create a requires confirmation event type
2) open incognito tab or another browser and book a meeting (Attendee)
3) Confirm the booking (Organizer) and attendee would get meeting schedule email
4) Get the reschedule link from attendee's email and reschedule the booking

Both attendee and organiser shouldn't get booking email or calendar event  before organiser has accepted the meeting

### CODE REVIEW

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 1]
```diff
@@ -1374,7 +1374,7 @@ async function handler(
             }
           }
 
-          if (noEmail !== true) {
+          if (noEmail !== true && (!requiresConfirmation || isOrganizerRescheduling)) {
```
Comment (Udit-takkar) [inline packages/features/bookings/lib/handleNewBooking.ts:1377]: !requiresConfirmation || isOrganizerRescheduling

- We send the rescheduled email If the event doesn't require confirmation OR organiser is rescheduling the meeting

**Review by zomars — APPROVED** [review]
Thank you @Udit-takkar 🙏
