### PR TITLE
fix: weekly limits

### LINKED ISSUE #10361: [CAL-2237] "Limit booking frequency" setting doesn't work
### Issue Summary

I have a [Cal.com](http://Cal.com) event at [this link](https://cal.com/quanx/boba). In this event's settings > "Limits" > "Limit booking frequency", I added a rule of 1 per week. After I've set this rule, people could still book > 1 per week: evidently, I already have 1 booking this week and another next week, yet my public event page still allows people to book during these weeks.

### Steps to Reproduce

1. In an event's settings > "Limits" > "Limit booking frequency", add a rule of 1 per week
2. Book a meeting this week for that event
3. Return to the booking page to see that this week is available for more bookings

### Actual Results

* People can still book after I've set a rule of only one event booking per week

### Expected Results

* If this week already has a booking, people should see that this week no longer has any open slots for more booking

### Technical details

* I'm using Chrome / Arc browsers
* Confirmed that this setting has been saved and was set for several days now

### Evidence

CleanShot 070349@2x

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2237](https://linear.app/calcom/issue/CAL-2237/limit-booking-frequency-setting-doesnt-work)</sub>

### LINKED ISSUE #10402: Limits are incorrectly applied for partial weeks in consecutive months
### Issue Summary

Limits are only applied to part of the week currently in view, i.e. at the beginning or end of the month. This affects both limit by frequency and duration.

### Steps to Reproduce

1. Limit event to 1 booking per week
3. Book in week that ends in next month, e.g. Mon 31 Jul
4. See that you are still able to book 1-5 Aug

The same applies to duration limits, e.g. 30min per week.

### Expected Results

- Weekly limits should be applied regardless of end of month

### Evidence

- See steps to reproduce
- Also affected by this (but not just): #10361

### PR DESCRIPTION
**Pull request by nicktrn**
## What does this PR do?

This addresses two bugs related to weekly events, relating to:

1. All non-variable length event types
2. Weeks spanning two months

Fixes #10361
Fixes #10402

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

1. **Fixed length events**
- Limit a 30min event to 30min per week
- Book once
- See that the entire week is blocked

2. **Week in two months**
- Limit any event to 1 booking (or 1 length of event) per week
- Book in week that ends in next month, e.g. Mon 31 Jul
- See that you are unable to book 1-5 Aug

Availability and booking page tests are passing, but might make sense to add a new test to prevent regressions. Bug (2) was probably always there, but not (1).

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/core/getUserAvailability.ts [hunk 1]
```diff
@@ -165,8 +166,9 @@ export async function getUserAvailability(
 
   const busyTimes = await getBusyTimes({
     credentials: user.credentials,
-    startTime: dateFrom.toISOString(),
-    endTime: dateTo.toISOString(),
+    // needed to correctly apply limits (weeks can be part of two months)
+    startTime: dateFrom.startOf("week").toISOString(),
+    endTime: dateTo.endOf("week").toISOString(),
```
Comment (nicktrn) [inline packages/core/getUserAvailability.ts:171]: If this affects performance negatively, it would have to be pulled into both limit functions separately, or called with startOf/endOf only if any weekly limits are present.

**Review by nicktrn — COMMENTED** [review]
Ready for review

File: packages/core/getUserAvailability.ts (hunk 1 above)
Comment (Udit-takkar) [reply packages/core/getUserAvailability.ts:171]: nice catch

**Review by Udit-takkar — COMMENTED** [review]
Screenshot 2023-07-27 at 5 20 15 PM

If i have availability on all days then if i book on 13th july then sunday to saturday(of next week) gets blocked. I expected monday to sunday getting blocked ( 7th july - 13th July).

**Comment by nicktrn** [comment]
> If i have availability on all days then if i book on 13th july then sunday to saturday(of next week) gets blocked. I expected monday to sunday getting blocked ( 7th july - 13th July).

Seems unintuitive, but I think that was the case before. AFAIK, start of week is timezone dependent in dayjs. Is there a custom start of week option for users?

**Review by Udit-takkar — APPROVED** [review]
LGTM

@nicktrn i just checked that i had set start of the week to sunday in settings http://localhost:3000/settings/my-account/general. so yeah this works fine

**Comment by qu8n** [comment]
Thanks, @nicktrn 🙏. I assume that this fix has been deployed to cal.com?

**Comment by nicktrn** [comment]
@qu8n no worries, glad I could help! 

> I assume that this fix has been deployed to cal.com?

Not quite yet, but keep an eye on [releases](https://github.com/calcom/cal.com/releases), should only be a few days max. In the meantime, limiting to 1 booking per week (not via duration) should work fine for weeks in the middle of the month.
