### PR TITLE
fix: Routing Form and other org related fixes

### LINKED ISSUE #9821: Orgs Testing - List of bugs[Will keep on updating]
- Reschedule link is not of org.cal.com. It is of app.cal.com which gives 404 for org member's event
-

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #9821 by fixing the last pending item
Screenshot 2023-07-24 at 7 18 53 PM

- Make Routing Forms public pages(`/router` and `/forms/{FORMID}`) org context aware
- Fix duplicate / in org URLs avoiding too many warnings in console about it

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: apps/web/pages/event-types/index.tsx [hunk 1]
```diff
@@ -741,9 +742,7 @@ const EventTypeListHeading = ({
         )}
         {profile?.slug && (
           <Link href={`${CAL_URL}/${profile.slug}`} className="text-subtle block text-xs">
-            {orgBranding
-              ? `${orgBranding.fullDomain.replace("https://", "").replace("http://", "")}${profile.slug}`
-              : `${CAL_URL?.replace("https://", "").replace("http://", "")}/${profile.slug}`}
+            {`${bookerUrl.replace("https://", "").replace("http://", "")}/${profile.slug}`}
```
Comment (hariombalhara) [inline apps/web/pages/event-types/index.tsx:745]: Because fullDomain doesn't have an ending slash now which is consistent with WEBAPP and CAL_URL. We can simplify the logic using bookerUrl

File: packages/app-store/routing-forms/pages/router/[...appPages].tsx [hunk 2]
```diff
@@ -47,11 +48,21 @@ export const getServerSideProps = async function getServerSideProps(
   }
   // eslint-disable-next-line @typescript-eslint/no-unused-vars
   const { form: formId, slug: _slug, pages: _pages, ...fieldsResponses } = queryParsed.data;
-  const form = await prisma.app_RoutingForms_Form.findUnique({
+  const { currentOrgDomain, isValidOrgDomain } = orgDomainConfig(context.req.headers.host ?? "");
+
+  const form = await prisma.app_RoutingForms_Form.findFirst({
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/pages/router/[...appPages].tsx:53]: Changed to findFirst because you can have user has in where clause for findUnique

File: packages/features/ee/organizations/lib/orgDomains.ts [hunk 3]
```diff
@@ -37,6 +37,5 @@ export function subdomainSuffix() {
 }
 
 export function getOrgFullDomain(slug: string, options: { protocol: boolean } = { protocol: true }) {
-  // TODO: It is a replacement for WEBAPP_URL and that doesn't have / in the end.  Remove / after ensuring that it works reliably everywhere
-  return `${options.protocol ? `${new URL(WEBAPP_URL).protocol}//` : ""}${slug}.${subdomainSuffix()}/`;
+  return `${options.protocol ? `${new URL(WEBAPP_URL).protocol}//` : ""}${slug}.${subdomainSuffix()}`;
```
Comment (hariombalhara) [inline packages/features/ee/organizations/lib/orgDomains.ts:40]: Comment has the reason why this change was made.

File: packages/features/ee/teams/components/MemberListItem.tsx [hunk 4]
```diff
@@ -170,7 +171,7 @@ export default function MemberListItem(props: Props) {
               <Tooltip content={t("view_public_page")}>
                 <Button
                   target="_blank"
-                  href={"/" + props.member.username}
+                  href={`${bookerUrl}/${props.member.username}`}
```
Comment (hariombalhara) [inline packages/features/ee/teams/components/MemberListItem.tsx:174]: This link would have given 404 for org member.

File: packages/lib/hooks/useBookerUrl.ts [hunk 5]
```diff
@@ -1,7 +1,7 @@
 import { useOrgBranding } from "@calcom/features/ee/organizations/context/provider";
-import { WEBAPP_URL } from "@calcom/lib/constants";
+import { CAL_URL, WEBAPP_URL } from "@calcom/lib/constants";
 
 export const useBookerUrl = () => {
   const orgBranding = useOrgBranding();
-  return orgBranding?.fullDomain ?? WEBAPP_URL;
+  return orgBranding?.fullDomain ?? CAL_URL ?? WEBAPP_URL;
```
Comment (hariombalhara) [inline packages/lib/hooks/useBookerUrl.ts:6]: Prefer CAL_URL for public links, if not available , go for WEBAPP_URL.

**Review by leog — APPROVED** [review]
Looks good to me, thank you for taking care of this @hariombalhara.
