### PR TITLE
fix: add hour12

### LINKED ISSUE #4885: Event type availability does not respect 12h/24h account setting.
On an account with 12-hour time format display

image

### PR DESCRIPTION
**Pull request by Udit-takkar**
Fixes: #4885 

Screenshot 2022-11-03 at 4 22 22 PM

### CODE REVIEW

File: apps/web/components/v2/eventtype/AvailabilityTab.tsx [hunk 1]
```diff
@@ -91,15 +92,16 @@ const AvailabilitySelect = ({
...
+  Intl.DateTimeFormat(undefined, { hour: "numeric", minute: "numeric", hour12 }).format(
     new Date(dayjs.utc(date).format("YYYY-MM-DDTHH:mm:ss"))
   );
 
 export const AvailabilityTab = () => {
   const { t, i18n } = useLocale();
   const { watch } = useFormContext<FormValues>();
-
+  const me = useMeQuery();
+  const { timeFormat } = me.data || { timeFormat: null };
```
Comment (JeroenReumkens) [inline apps/web/components/v2/eventtype/AvailabilityTab.tsx:104]: Perhaps it's just me, but I don't really like the formatting this way 🤔  
I'd rather see something like `const timeFormat = me?.data?.timeFormat`, which also makes it more obvious to me that this data could be undefined. What do you think?

**Review by JeroenReumkens — APPROVED** [review]
Added one NIT, besides that awesome change!

File: apps/web/components/v2/eventtype/AvailabilityTab.tsx (hunk 1 above)
Comment (Udit-takkar) [reply apps/web/components/v2/eventtype/AvailabilityTab.tsx]: done
