### PR TITLE
Fix/DST issues

### LINKED ISSUE #6622: [CAL-863] No available users found error on confirming booking for an open slot
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I have not replicated this personally, but I have had different users report this error on more than occasion.

When confirming an individual booking [not a team page], some users have seen this error: "Could not book the meeting. No available users found."

image

<sub>[CAL-863](https://linear.app/calcom/issue/CAL-863/no-available-users-found-error-on-confirming-booking-for-an-open-slot)</sub>

### PR DESCRIPTION
**Pull request by roae**
## What does this PR do?

Fixes: #6622 #7462

https://www.loom.com/share/d444c5e102394cb194a836efcc98166c

/claim #6622

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by zomars — APPROVED** [review]
Code LGTM. Pre-approving since it still way better that what we currently have.

File: packages/lib/date-fns/index.ts [hunk 1]
```diff
@@ -126,3 +126,69 @@ export const isNextDayInTimezone = (time: string, timezoneA: string, timezoneB:
...
+export const timeZoneWithDST = (timeZone: string): boolean => {
+  const jan = dayjs.tz(`${new Date().getFullYear()}-01-01T00:00:00`, timeZone);
+  const jul = dayjs.tz(`${new Date().getFullYear()}-07-01T00:00:00`, timeZone);
+  return jan.utcOffset() !== jul.utcOffset();
+};
+
+/**
+ * Get DST difference.
+ * Today clocks are almost always set one hour back or ahead.
+ * However, on Lord Howe Island, Australia, clocks are set only 30 minutes forward
```
Comment (alannnc) [inline packages/lib/date-fns/index.ts:161]: 🥲

File: apps/web/test/lib/slots.test.ts [hunk 2]
```diff
@@ -24,6 +24,7 @@ describe("Tests the slot logic", () => {
           },
         ],
         eventLength: 60,
+        organizerTimeZone: "America/Toronto",
```
Comment (alannnc) [inline apps/web/test/lib/slots.test.ts:27]: Does Toronto has a special DST/TZ?

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 3]
```diff
@@ -111,16 +112,41 @@ const isWithinAvailableHours = (
...
 ) => {
   const timeSlotStart = dayjs(timeSlot.start).utc();
   const timeSlotEnd = dayjs(timeSlot.end).utc();
+  const isOrganizerInDST = isInDST(dayjs().tz(organizerTimeZone));
+  const isInviteeInDST = isInDST(dayjs().tz(organizerTimeZone));
+  const isOrganizerInDSTWhenSlotStart = isInDST(timeSlotStart.tz(organizerTimeZone));
+  const isInviteeInDSTWheSlotStart = isInDST(timeSlotStart.tz(inviteeTimeZone));
+  const organizerDSTDifference = getDSTDifference(organizerTimeZone);
+  const inviteeDSTDifference = getDSTDifference(inviteeTimeZone);
+
```
Comment (alannnc) [inline packages/features/bookings/lib/handleNewBooking.ts:131]:
```suggestion
const sameDSTUsers = isOrganizerInDSTWhenSlotStart === isInviteeInDSTWhenSlotStart;
const organizerDST = isOrganizerInDST === isOrganizerInDSTWhenSlotStart;
const inviteeDST = isInviteeInDST === isInviteeInDSTWheSlotStart;
```

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 4]
```diff
@@ -111,16 +112,41 @@ const isWithinAvailableHours = (
...
+    organizerTimeZone: string;
+    inviteeTimeZone: string;
   }
 ) => {
   const timeSlotStart = dayjs(timeSlot.start).utc();
   const timeSlotEnd = dayjs(timeSlot.end).utc();
+  const isOrganizerInDST = isInDST(dayjs().tz(organizerTimeZone));
+  const isInviteeInDST = isInDST(dayjs().tz(organizerTimeZone));
+  const isOrganizerInDSTWhenSlotStart = isInDST(timeSlotStart.tz(organizerTimeZone));
+  const isInviteeInDSTWheSlotStart = isInDST(timeSlotStart.tz(inviteeTimeZone));
```
Comment (alannnc) [inline packages/features/bookings/lib/handleNewBooking.ts:128]:
```suggestion
  const isInviteeInDSTWhenSlotStart = isInDST(timeSlotStart.tz(inviteeTimeZone));
```

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 5]
```diff
@@ -111,16 +112,41 @@ const isWithinAvailableHours = (
...
+  const organizerDSTDifference = getDSTDifference(organizerTimeZone);
+  const inviteeDSTDifference = getDSTDifference(inviteeTimeZone);
+
+  const getTime = (slotTime: Dayjs, minutes: number) =>
+    slotTime
+      .startOf("day")
+      .add(
+        isOrganizerInDSTWhenSlotStart === isInviteeInDSTWheSlotStart &&
+          isOrganizerInDST === isOrganizerInDSTWhenSlotStart &&
+          isInviteeInDST === isInviteeInDSTWheSlotStart
```
Comment (alannnc) [inline packages/features/bookings/lib/handleNewBooking.ts:138]: sameDSTUsers && organizerDST && inviteeDST

Comment (alannnc) [inline packages/features/bookings/lib/handleNewBooking.ts:138]:
```suggestion
sameDSTUsers && organizerDST && inviteeDST
```

File: packages/lib/slots.ts [hunk 6]
```diff
@@ -92,11 +98,23 @@ function buildSlots({
...
-  const timeZone =
-    (startOfInviteeDay as unknown as { $x: { $timezone: string } })["$x"]["$timezone"] || "UTC";
+
+  const isOrganizerInDST = isInDST(startOfInviteeDay.tz(organizerTimeZone));
+  const isInviteeInDST = isInDST(startOfInviteeDay.tz(inviteeTimeZone));
+  const organizerDSTDifference = getDSTDifference(organizerTimeZone);
+  const inviteeDSTDifference = getDSTDifference(inviteeTimeZone);
 
   const slots: { time: Dayjs; userIds?: number[] }[] = [];
+
```
Comment (alannnc) [inline packages/lib/slots.ts:108]:
```suggestion
const resultDSTDifference = isOrganizerInDST ? organizerDSTDifference : -inviteeDSTDifference;
```

File: packages/lib/slots.ts [hunk 7]
```diff
@@ -92,11 +98,23 @@ function buildSlots({
...
+  const getTime = (time: number) => {
+    const minutes =
+      isOrganizerInDST !== isInviteeInDST
+        ? time - (isOrganizerInDST ? organizerDSTDifference : -inviteeDSTDifference)
```
Comment (alannnc) [inline packages/lib/slots.ts:112]:
```suggestion
        ? time - DSTDifference
```

**Review by alannnc — APPROVED** [review]
Code looks good, just left some NIT changes

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 8]
```diff
@@ -111,16 +112,41 @@ const isWithinAvailableHours = (
...
+                : -inviteeDSTDifference),
+        "minutes"
+      );
   for (const workingHour of workingHours) {
-    // TODO: Double check & possibly fix timezone conversions.
-    const startTime = timeSlotStart.startOf("day").add(workingHour.startTime, "minute");
-    const endTime = timeSlotEnd.startOf("day").add(workingHour.endTime, "minute");
+    const startTime = getTime(timeSlotStart, workingHour.startTime);
+    const endTime = getTime(timeSlotEnd, workingHour.endTime);
+    console.log(timeSlotStart.format(), startTime.format());
```
Comment (zomars) [inline packages/features/bookings/lib/handleNewBooking.ts:149]:
```suggestion
```

**Review by CarinaWolli — COMMENTED** [review]
I am still getting `Could not book the meeting. No available users found.` when picking a slot after March 12 within the first hour of the day that shows as available

File: apps/web/test/lib/slots.test.ts (hunk 2 above)
Comment (roae) [reply apps/web/test/lib/slots.test.ts:27]: No, nothing special

**Comment by roae** [comment]
> I am still getting `Could not book the meeting. No available users found.` when picking a slot after March 12 within the first hour of the day that shows as available

What time zone does the organizer and booker have?

**Comment by CarinaWolli** [comment]
> What time zone does the organizer and booker have?

Organizer: London 
Booker: America/Detroit

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 9]
```diff
@@ -111,16 +112,40 @@ const isWithinAvailableHours = (
...
   const timeSlotEnd = dayjs(timeSlot.end).utc();
+  const isOrganizerInDST = isInDST(dayjs().tz(organizerTimeZone));
+  const isInviteeInDST = isInDST(dayjs().tz(organizerTimeZone));
+  const isOrganizerInDSTWhenSlotStart = isInDST(timeSlotStart.tz(organizerTimeZone));
+  const isInviteeInDSTWhenSlotStart = isInDST(timeSlotStart.tz(inviteeTimeZone));
+  const organizerDSTDifference = getDSTDifference(organizerTimeZone);
+  const inviteeDSTDifference = getDSTDifference(inviteeTimeZone);
+const sameDSTUsers = isOrganizerInDSTWhenSlotStart === isInviteeInDSTWhenSlotStart;
+const organizerDST = isOrganizerInDST === isOrganizerInDSTWhenSlotStart;
+const inviteeDST = isInviteeInDST === isInviteeInDSTWheSlotStart;
```
Comment (CarinaWolli) [inline packages/features/bookings/lib/handleNewBooking.ts:133]: typo
```suggestion
const inviteeDST = isInviteeInDST === isInviteeInDSTWhenSlotStart;
```

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 10]
```diff
@@ -111,16 +112,40 @@ const isWithinAvailableHours = (
...
+  const getTime = (slotTime: Dayjs, minutes: number) =>
+    slotTime
+      .startOf("day")
+      .add(
+        sameDSTUsers && organizerDST && inviteeDST
+          ? minutes
+          : minutes -
+              (isOrganizerInDSTWhenSlotStart || isOrganizerInDST
+                ? organizerDSTDifference
+                : -inviteeDSTDifference),
```
Comment (CarinaWolli) [inline packages/features/bookings/lib/handleNewBooking.ts:143]:
```suggestion
                : 0),
```

So this would fix my issue with `Could not book the meeting. No available users found.`. However, not sure if this would mess up something else?

Comment (roae) [reply packages/features/bookings/lib/handleNewBooking.ts:143]: no, the subtraction sign should be removed from there

**Comment by roae** [comment]
> > What time zone does the organizer and booker have?
> 
> Organizer: London Booker: America/Detroit

@CarinaWolli I think it's fixed now, I only remove the subtraction sign.

imagen

**Review by CarinaWolli — APPROVED** [review]
Fixed now 🙌🏻

**Comment by RussQuan** [comment]
You are the Hero!!!❤️
