### PR TITLE
fix: brand colors set by user not respected in embed

### LINKED ISSUE #10497: [CAL-4740] Embed brand colors doesn't work properly
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The brand color set in the Settings>Appearance is not set automatically in the brand color in embeds. When I try to set brand color from the color picker, it is set only for one theme, either dark or light. 

### Steps to Reproduce

1. Set your brand colors in Settings>Appearance.
2. Open embeds from an event. Select inline embeds.
3. The brand color is not selected according to the colors set in Settings.
4. When I select the brand color, it is only visible in preview for one theme, either light or dark.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

Brand color is not being set properly

### Expected Results

I shouldn't have to set brand colors in the embeds as it's already set in the settings. If the option to set brand colors is still required, the selected value should be according to the colors selected in the settings and should be available for both the themes.

### Technical details

https://app.birdeatsbug.com/sessions/N2G-znF0x0ipbn--ofl88su--GlD613Iqo31PVJsPl7G

### Evidence

Manual testing. Video recording attached above

<sub>[CAL-4740](https://linear.app/calcom/issue/CAL-4740/embed-brand-colors-doesnt-work-properly)</sub>

### PR DESCRIPTION
**Pull request by asadath1395**
## What does this PR do?

- Fixes #10497 Embed brand colors doesn't work properly

https://www.loom.com/share/2940a63587aa4e3d9164d921f0aa4753?sid=516c4ce9-3eec-41eb-b1c2-0db37c402514

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

Follow the repro steps in the issue

### CODE REVIEW

**Comment by Praashh** [comment]
hey @asadath1395 can you share any loom video of the fix?

**Comment by asadath1395** [comment]
Hey @Praashh, i have added a loom video in the description

**Review by Praashh — DISMISSED** [review]
changes looks fine to me, also working fine locally. Thanks @asadath1395   for the fix ❤️.

**Review by hariombalhara — CHANGES_REQUESTED** [review]
@asadath1395 Thanks for the PR 🙏

But we don't want to support the brand colors like this(i.e. through styles API). We would want user to specify the colors for both dark and light theme in the Embed itself. 

We want brand colors to work through custom CSS as demoed in below codesandbox link. That is more flexible and actually works for both light and dark theme. There was a ticket for switching to custom CSS somewhere but I couldn't find it.

https://codesandbox.io/p/sandbox/embed-ui-customization-using-css-vars-zix02l?file=%2Fsrc%2FApp.tsx%3A13%2C19

**Comment by hariombalhara** [comment]
On the other hand, I think the changes aren't much so we could be fine merging it and we could work on generating `cssVarsPerTheme` related code for branding colors in a different PR.

File: packages/features/embed/Embed.tsx [hunk 1]
```diff
@@ -578,6 +583,19 @@ const EmbedTypeCodeAndPreviewDialogContent = ({
   const defaultConfig = {
     layout: BookerLayouts.MONTH_VIEW,
   };
+
+  const paletteDefaultValue = useCallback(
+    (paletteName: string) => {
+      if (paletteName === "brandColor") {
+        const color = hasDarkTheme ? defaultBrandColor.darkBrandColor : defaultBrandColor.brandColor;
```
Comment (hariombalhara) [inline packages/features/embed/Embed.tsx:590]: Even though we decide dark/light based on current theme, user is still not able to test on dark theme because whatever color is chosen applies for light theme only as the styles API we are using currently only support light theme.

We should switch to using cssVarsPerTheme as shown in codesandbox demo

Comment (hariombalhara) [reply packages/features/embed/Embed.tsx:590]: See this loom that shows the issue https://www.loom.com/share/5ebab54eadb54dd5917d11a42812b8ed

**Review by hariombalhara — DISMISSED** [review]
Requesting changes again as the fix isn't working as expected and would require some API changes.

**Comment by asadath1395** [comment]
@hariombalhara Can you check this when you are available? Thanks

File: packages/features/embed/Embed.tsx [hunk 2]
```diff
@@ -578,6 +580,22 @@ const EmbedTypeCodeAndPreviewDialogContent = ({
   const defaultConfig = {
     layout: BookerLayouts.MONTH_VIEW,
   };
+
+  const paletteDefaultValue = useCallback(
```
Comment (hariombalhara) [inline packages/features/embed/Embed.tsx:584]: I don't see a purpose of useCallback here. Removing it.

File: packages/features/embed/Embed.tsx [hunk 3]
```diff
@@ -578,6 +584,19 @@ const EmbedTypeCodeAndPreviewDialogContent = ({
   const defaultConfig = {
     layout: BookerLayouts.MONTH_VIEW,
   };
+
+  const paletteDefaultValue = (paletteName: string) => {
```
Comment (hariombalhara) [inline packages/features/embed/Embed.tsx:588]: @asadath1395 Removed the usage of `useCallback` which makes sense if we are passing functions to components causing it to change reference. Here we are using the function call result, so that isn't needed.

File: packages/features/embed/Embed.tsx [hunk 4]
```diff
@@ -578,6 +584,19 @@ const EmbedTypeCodeAndPreviewDialogContent = ({
...
+    if (paletteName === "brandColor") {
+      return defaultBrandColor?.brandColor ?? DEFAULT_LIGHT_BRAND_COLOR;
```
Comment (hariombalhara) [inline packages/features/embed/Embed.tsx:590]: Using the default colors from constant to make it consistent with profile

File: packages/features/embed/Embed.tsx [hunk 5]
```diff
@@ -994,20 +1013,21 @@ const EmbedTypeCodeAndPreviewDialogContent = ({
...
                       ].map((palette) => (
                         <Label key={palette.name} className="mb-6">
-                          <div className="mb-2">{palette.title}</div>
+                          <div className="mb-2">{t(palette.title)}</div>
                           <div className="w-full">
                             <ColorPicker
                               popoverAlign="start"
                               container={dialogContentRef?.current ?? undefined}
-                              defaultValue="#000000"
+                              defaultValue={paletteDefaultValue(palette.name)}
```
Comment (hariombalhara) [inline packages/features/embed/Embed.tsx:1030]: We use the default values here only when showing the default color in color picker.

We don't want the default value to be used elsewhere because otherwise it goes into Embed Snippt and unnecessarily hardcoded there on user websites.

File: packages/features/embed/Embed.tsx [hunk 6]
```diff
@@ -1164,11 +1184,8 @@ export const EmbedDialog = ({
   types,
   tabs,
   eventTypeHideOptionDisabled,
-}: {
-  types: EmbedTypes;
-  tabs: EmbedTabs;
-  eventTypeHideOptionDisabled: boolean;
-}) => {
+  defaultBrandColor,
+}: EmbedDialogProps) => {
```
Comment (hariombalhara) [inline packages/features/embed/Embed.tsx:1188]: Reuse props type

**Review by hariombalhara — COMMENTED** [review]
@asadath1395 
- I did some code cleanup 
- Fixed the default values of brandColor
- Ensured that default values don't go into the snippet

Please take a look into it once and then we are good to go

**Comment by hariombalhara** [comment]
Also, I just realised that there isn't always user brand colors being used,
For team event, we use team brand colors.
In an organization, we use organization's brand colors.

We should consider that too, but that could be a followup as well.

**Review by hariombalhara — APPROVED** [review]
