### PR TITLE
Fix Plausible App

### LINKED ISSUE #6855: [CAL-986] Plausible App installation takes the user away from event type page.
Installing Plausible app from EventType Apps section, takes the user to installed page instead of updating the status on EventType Apps section itself.

<sub>[CAL-986](https://linear.app/calcom/issue/CAL-986/plausible-app-installation-takes-the-user-away-from-event-type-page)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #6855 #6462

Screenshot 2023-02-02 at 8 31 36 PM

See how Plausible installation doesn't redirect away from EventType page now. Status of installation updates on the same page.
https://www.loom.com/share/f795d48042114132ad3849405a781ce5

**Environment**:  Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Add plausible app and see that the trackingDomain is available on plausible script tag.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/app-store/plausible/components/InstallAppButton.tsx [hunk 1]
```diff
@@ -1,18 +0,0 @@
-import type { InstallAppButtonProps } from "@calcom/app-store/types";
```
Comment (hariombalhara) [inline packages/app-store/plausible/components/InstallAppButton.tsx:1]: One should not add InstallAppButton component separately now. It's automatically handled by App Store. 
Adding it actually disables OmniInstallation behaviour.

**Review by emrysal — APPROVED** [review]
