### PR TITLE
fix: add recurringEventCount to URL params

### LINKED ISSUE #18547: [CAL-5000] Default number of recurring event occurrences should be configurable
when using a recurring event booking link, the occurrences count defaults to the maximum (in the example 8).
Ideally that would default to the minimum (1), or we could set the default value via a query param

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-5000](https://linear.app/calcom/issue/CAL-5000/default-number-of-recurring-event-occurrences-should-be-configurable)</sub>

### PR DESCRIPTION
**Pull request by ibex088**
## What does this PR do?

- Fixes #18547

#### Video Demo (if applicable):

https://www.loom.com/share/78d5d072b3234197886d94d3c514c53e

---
## Summary by cubic
Validate the occurrence count from the ?recurringEventCount= URL param and unify input validation for recurring events. Invalid values now fall back to the allowed maximum, show a warning, and the store stays in sync with the URL when allowed. Adds a “Repeats X times” badge when count > 1.

- **Bug Fixes**
  - Initialize occurrence count from the recurringEventCount query param on load; validate numeric, >=1, and <= max occurrences, and default to max when missing.
  - Guard against invalid/NaN values updating state or URL.
  - Prevent overlayCalendar toggle from overwriting existing URL query params.

- **New Features**
  - Show a “Repeats {{count}} times” badge in the booking modal (new i18n key: repeats_num_times).

<sup>Written for commit 3be6bb63b043fd830ae0ed305975562750308127. Summary will update automatically on new commits.</sup>

### CODE REVIEW

File: packages/features/bookings/Booker/store.ts [hunk 1]
```diff
@@ -421,8 +426,13 @@ export const createBookerStore = () =>
     },
     recurringEventCount: null,
     setRecurringEventCount: (recurringEventCount: number | null) => set({ recurringEventCount }),
-    occurenceCount: null,
-    setOccurenceCount: (occurenceCount: number | null) => set({ occurenceCount }),
+    occurenceCount: Number(getQueryParam("recurringEventCount")) || null,
```
Comment (ibex088) [inline packages/features/bookings/Booker/store.ts]: named the queryParam recurringEventCount as it makes more sense than occurrenceCount
not setting it directly into recurringEventCount because we need to validate this input first

File: packages/features/bookings/components/event-meta/Occurences.tsx [hunk 2]
```diff
@@ -25,14 +25,37 @@ export const EventOccurences = ({ event }: { event: Pick<BookerEvent, "recurring
...
-    setOccurenceCount(occurenceCount || event.recurringEvent.count);
-    setRecurringEventCount(recurringEventCount || event.recurringEvent.count);
-    if (occurenceCount && (occurenceCount > event.recurringEvent.count || occurenceCount < 1))
-      setWarning(true);
-  }, [setRecurringEventCount, event.recurringEvent, recurringEventCount, setOccurenceCount, occurenceCount]);
+
+    if (occurenceCount) {
+      validateAndSetRecurringEventCount(occurenceCount);
+    } else {
+      setRecurringEventCount(maxOccurences);
```
Comment (ibex088) [inline packages/features/bookings/components/event-meta/Occurences.tsx:49]: defaulting to Max RN
dont like the idea of defaulting to 1 if the input is invalid

File: packages/features/bookings/Booker/store.ts [hunk 3]
```diff
@@ -421,8 +426,13 @@ export const createBookerStore = () =>
     },
     recurringEventCount: null,
```
Comment (supalarry) [inline packages/features/bookings/Booker/store.ts:427]: I am confused - here we have `recurringEventCount` in booker store but we store `getQueryParam("recurringEventCount")` within `occurenceCount` within booker context?

File: packages/features/bookings/components/event-meta/Occurences.tsx [hunk 4]
```diff
@@ -25,14 +25,37 @@ export const EventOccurences = ({ event }: { event: Pick<BookerEvent, "recurring
   const bookerState = useBookerStoreContext((state) => state.state);
   const { timezone, timeFormat } = useBookerTime();
   const [warning, setWarning] = useState(false);
-  // Set initial value in booker store.
+
+  const validateAndSetRecurringEventCount = (value: number | string) => {
+    const pattern = /^(?=.*[0-9])\S+$/;
```
Comment (supalarry) [inline packages/features/bookings/components/event-meta/Occurences.tsx]: Do we really need regex to validate url pattern and then have `inputValue` and `valueStr` and all the checks in `isValid` ?

Why can't we just check
```
const inputValue = parseInt(value);
const isValid = !isNaN(inputValue) && inputValue < 0 && inputValue > maxOccurences);
```

You can parseInt a string or a number you don't need to check if its a string or not and we dont need a string and number as variables to do the is valid check. We just convert whatever value is passed to number and if its a valid number we check its range.

**Review by supalarry — COMMENTED** [review]
Review:

File: packages/features/bookings/Booker/store.ts (hunk 3 above)
Comment (ibex088) [reply packages/features/bookings/Booker/store.ts:427]: https://github.com/calcom/cal.com/pull/24986#discussion_r2502488543

Comment (ibex088) [reply packages/features/bookings/Booker/store.ts:427]: Let me clarify the distinction between these two variables:

## Two-State Pattern for Input Validation

We use a **two-state pattern** to separate UI state from business logic state:

### `occurenceCount` (UI/Input State)
- Stores the **raw user input** (can be invalid)
- Initialized from URL query param `?recurringEventCount=X`
- Always reflects what the user typed or what came from the URL
- Used as the `defaultValue` for the input field
- Gets persisted back to URL params

### `recurringEventCount` (Validated/Business Logic State)
- Stores the **validated value** actually used for creating bookings
- Only gets set when the input is valid (within range 1 to max)
- Used in the booking submission and for displaying recurring dates preview
- Never contains invalid values

## Why This Pattern?

This separation allows us to:

1. **Preserve user input**: If someone types "999" but max is "12", we keep "999" in the input field (with a warning) rather than replacing it immediately
2. **Safe booking flow**: The booking always uses a valid value from `recurringEventCount`, even if `occurenceCount` is invalid
3. **URL param handling**: When someone shares a URL with `?occurenceCount=999`, we validate it and either use it (if valid) or fallback to the max allowed value, while still showing the warning

## Flow Example

User types "999" (max is 12):

occurenceCount = 999 (stored, shown in input)
recurringEventCount = 12 (fallback to max)
warning = true (shown to user)
Booking uses: 12 ✅
User types "5" (max is 12):

occurenceCount = 5 (stored, shown in input)
recurringEventCount = 5 (valid, used for booking)
warning = false
Booking uses: 5 ✅

Comment (supalarry) [reply packages/features/bookings/Booker/store.ts:427]: In that case can we rename `occurenceCount` to `recurringEventCountQueryParam` and `setOccurenceCount` to `setRecurringEventCountQueryParam` ? Otherwise the code is too confusing.

File: packages/features/bookings/Booker/store.ts [hunk 5]
```diff
@@ -430,7 +430,8 @@ export const createBookerStore = () =>
     setOccurenceCount: (occurenceCount: number | null) => {
       set({ occurenceCount });
       if (!get().isPlatform || get().allowUpdatingUrlParams) {
-        updateQueryParam("recurringEventCount", occurenceCount ?? "");
+        const validCount = occurenceCount !== null && !isNaN(occurenceCount) ? occurenceCount : "";
```
Comment (supalarry) [inline packages/features/bookings/Booker/store.ts]: Is empty string validCount? Why not max occurences allowed?

File: packages/features/bookings/Booker/store.ts (hunk 3 above)
Comment (ibex088) [reply packages/features/bookings/Booker/store.ts:427]: how does recurringCountInput sound?

Comment (supalarry) [reply packages/features/bookings/Booker/store.ts:427]: I think `QueryParam` suffix makes it more clear where it comes from and goes to - and input in my mind could be an input to react component.

**Review by supalarry — APPROVED** [review]
