### PR TITLE
fix #582: send user back to onboarding after adding integration 

### LINKED ISSUE #582: Taken out of onboarding flow when connecting a calendar integration
### Steps to Reproduce
1. Go to step 2 of the onboarding flow
2. And proceed to connect Google Calendar
3. Then you'll be redirected to <BASE_URL>/integrations

### Expected results
Be taken to Step 3 to fill in my times

### PR DESCRIPTION
**Pull request by femyeda**
fixes #582 

Adds check for onboarding incomplete on /integrations.

### CODE REVIEW

File: lib/getting-started.tsx [hunk 1]
```diff
@@ -1,3 +1,20 @@
...
+
+export const shouldShowOnboarding = ({
+  completedOnboarding,
+  createdDate,
+}: {
+  completedOnboarding: boolean;
+  createdDate: dayjs.ConfigType;
+}) => {
+  return !completedOnboarding && dayjs(createdDate).isAfter(ONBOARDING_INTRODUCED_AT);
+};
```
Comment (KATT) [inline lib/getting-started.tsx:20]: this could be done so looking at the function we know it has to do with the `User`
```suggestion
import {User} from '@prisma/client';

export const shouldShowOnboarding = (user: Pick<User, 'createdDate' | 'completedOnboarding') => {
  return !completedOnboarding && dayjs(createdDate).isAfter(ONBOARDING_INTRODUCED_AT);
};
```

File: pages/event-types/index.tsx [hunk 2]
```diff
@@ -701,13 +700,10 @@ export const getServerSideProps = async (context: GetServerSidePropsContext) =>
...
 
-  if (!user.completedOnboarding && dayjs(user.createdDate).isAfter(ONBOARDING_INTRODUCED_AT)) {
-    return {
-      redirect: {
-        permanent: false,
-        destination: "/getting-started",
-      },
-    } as const;
+  if (
+    shouldShowOnboarding({ completedOnboarding: user.completedOnboarding, createdDate: user.createdDate })
```
Comment (KATT) [inline pages/event-types/index.tsx:704]: think this should work.

```suggestion
    shouldShowOnboarding(user)
```

File: pages/integrations/index.tsx [hunk 3]
```diff
@@ -487,9 +489,17 @@ export async function getServerSideProps(context) {
     },
     select: {
       id: true,
+      completedOnboarding: true,
+      createdDate: true,
     },
   });
 
+  if (
+    shouldShowOnboarding({ completedOnboarding: user.completedOnboarding, createdDate: user.createdDate })
```
Comment (KATT) [inline pages/integrations/index.tsx:498]: think this should work.

```suggestion
    shouldShowOnboarding(user)
```

**Review by KATT — APPROVED** [review]
LGTM, left some optional comments.

@emrysal is doing refactoring that might conflict on this in #613 so good if he's aware

File: pages/integrations/index.tsx (hunk 3 above)
Comment (femyeda) [reply pages/integrations/index.tsx:497]: Used the suggestion for the types, but still only passing the required parameters instead of the entire user object.

**Review by pumfleet — APPROVED** [review]
Looks good to me, will merge on Monday
