### PR TITLE
fix: url input field inconsistent 

### LINKED ISSUE #13955: Url Input feild Inconsistent UI/UX
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When we try update the URL with a long name the name feild is overflowing the Confirm panel and the UI seems Inconsistent.

### Steps to Reproduce

1.Go to My setting
2.Clicked on Profile
3.Update the input field of URL

### Actual Results

- The New name feild is exceeding the width of the Confirm username change panel.

### Expected Results

- The UI have to be consistent having the vertical-y scroll bar to avoid this issue

### Evidence
Screenshot 2024-03-02 133819

### PR DESCRIPTION
**Pull request by vikas-verma**
## What does this PR do?

Fixes #13955 

Closes #13955

Fixes # (issue)

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Tests (Unit/Integration/E2E or any other test)
- This change requires a documentation update

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Ryukemeister** [comment]
@vikas-verma linters are failing, can you prettier to format your code?

File: apps/web/components/ui/UsernameAvailability/UsernameTextfield.tsx [hunk 1]
```diff
@@ -168,7 +168,17 @@ const UsernameTextfield = (props: ICustomUsernameProps & Partial<React.Component
                   <p className="text-subtle" data-testid="new-username">
                     {t("new_username")}
                   </p>
-                  <p className="text-emphasis mt-1 break-all">{inputUsernameValue}</p>
+
+                  <p
+                    className="text-emphasis mt-1 break-all"
+                    style={{
+                      overflowY: "auto",
```
Comment (Ryukemeister) [inline apps/web/components/ui/UsernameAvailability/UsernameTextfield.tsx:175]: Instead of using the styles attribute here why not pass in those directly as tailwind classnames? eg: `className="text-emphasis mt-1 break-all overflow-y-auto"` something like that

**Comment by Ryukemeister** [comment]
lint checks are still failing :(

**Comment by vikas-verma** [comment]
> lint checks are still failing :(

fixed..  can you pls check now

**Comment by Ryukemeister** [comment]
There's also a small issue related to icon which I've mentioned in the comments for #13955 , can you have a look at that as well?

**Review by PeerRich — APPROVED** [review]
