### PR TITLE
fix: Dynamic events prevent fetching all users that share a username [CAL-2409]

### LINKED ISSUE #11186: [CAL-2409] orgs: duplicate invites for orgs and non-orgs with dynamic bookings
both [cal.com/peer](http://cal.com/peer) and [meet.cal.com/peer](http://meet.cal.com/peer) (see emails) are getting invites with dynamic links

same goes for [cal.com/bailey](http://cal.com/bailey) and [meet.cal.com/bailey](http://meet.cal.com/bailey)

i've only realised this since i renamed people today

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2409](https://linear.app/calcom/issue/CAL-2409/orgs-duplicate-invites-for-orgs-and-non-orgs-with-dynamic-bookings)</sub>

### PR DESCRIPTION
**Pull request by joeauyeung**
## What does this PR do?

Currently there can be multiple usernames if they belong to different organizations. Right now in `handleNewBooking` all users of the same username were being fetched in dynamic bookings, without any context to the org or not. The PR only fetches users that belong to the org or just normal users.

For example we have two users with the "admin" username "admin@example.com" and "org1member1@org1.com". We can see when we create a dynamic event with "admin+free" before it was grabbing both users but now it is querying for one. This works within an orgs context as well

## Before
image

## After
image

Fixes #11186 

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Create two users with the same username. The second user should belong to an org
- Create a dynamic booking that includes the test username
- The created booking should only contain the user outside of the booking
- Go through this flow again but within an org context

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/features/ee/organizations/lib/orgDomains.ts [hunk 1]
```diff
@@ -64,3 +64,8 @@ export function getSlugOrRequestedSlug(slug: string) {
     ],
   } satisfies Prisma.TeamWhereInput;
 }
+
+export function userOrgQuery(hostname: string, fallback?: string | string[]) {
+  const { currentOrgDomain, isValidOrgDomain } = orgDomainConfig(hostname, fallback);
+  return isValidOrgDomain && currentOrgDomain ? getSlugOrRequestedSlug(currentOrgDomain) : null;
+}
```
Comment (joeauyeung) [inline packages/features/ee/organizations/lib/orgDomains.ts:71]: This is being used in more than one place so let's abstract it.

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 2]
```diff
@@ -732,6 +733,7 @@ async function handler(
         const users = await prisma.user.findMany({
           where: {
             username: { in: dynamicUserList },
+            organization: userOrgQuery(req.headers.host.replace(/^https?:\/\//, "")),
```
Comment (joeauyeung) [inline packages/features/bookings/lib/handleNewBooking.ts:736]: When loading users we should only grab users that belong to the org. This is similar to how we fetch users on the dynamic booking page

Comment (keithwillcode) [reply packages/features/bookings/lib/handleNewBooking.ts:736]: This doesn't feel like the correct place to do this code. i.e. Parsing request headers inside of place where we create a new booking to determine the org.

Do we not have this on session or somewhere? If not, feels like this should be pulled out to some other class and called here.

**Review by keithwillcode — DISMISSED** [review]

File: packages/features/bookings/lib/handleNewBooking.ts (hunk 2 above)
Comment (alannnc) [reply packages/features/bookings/lib/handleNewBooking.ts:736]: I think this can only come from the request headers sadly.

**Review by alannnc — DISMISSED** [review]
Looks good to me, sadly that's the only way to tell if fetching users from an org.

File: packages/features/ee/organizations/lib/orgDomains.ts [hunk 3]
```diff
@@ -64,3 +64,8 @@ export function getSlugOrRequestedSlug(slug: string) {
     ],
   } satisfies Prisma.TeamWhereInput;
 }
+
+export function userOrgQuery(hostname: string, fallback?: string | string[]) {
+  const { currentOrgDomain, isValidOrgDomain } = orgDomainConfig(hostname, fallback);
```
Comment (zomars) [inline packages/features/ee/organizations/lib/orgDomains.ts:69]: This is already being called in the parent: https://github.com/calcom/cal.com/pull/11288/files#diff-0a49c6d137ab5a519fee377425ff051a13bcf55ff728bca45daaa73a4c5f0458R144-R147

Can we either just pass the computed data or find another abstraction?

File: packages/features/bookings/lib/handleNewBooking.ts (hunk 2 above)
Comment (emrysal) [reply packages/features/bookings/lib/handleNewBooking.ts:749]: We don't have a session here (not guaranteed anyways) and we don't have an event type id. the only way really is parsed from the calling url. think that's the nicest way too

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 4]
```diff
@@ -745,6 +746,7 @@ async function handler(
...
```
Comment (hariombalhara) [inline packages/features/bookings/lib/handleNewBooking.ts:749]:
```suggestion
            organization: userOrgQuery(req.headers.host),
```

I don't think host has protocol in it. We seem to be using it as is without replace elsewhere as well.

File: packages/features/bookings/lib/handleNewBooking.ts (hunk 2 above)
Comment (hariombalhara) [reply packages/features/bookings/lib/handleNewBooking.ts:749]: I am not sure if I am right but I am reluctant towards sending either the `req`(more inclined towards it) or `req.headers` to userOrgQuery so that it can be sure that it is receiving **host** only and not some other string. We will get better type safety that way.

Comment (hariombalhara) [reply packages/features/bookings/lib/handleNewBooking.ts:749]: Also, I feel that prisma client extensions would really solve this problem once and for all. We would be able to enforce an explicit value for `organization` there in user queries. Problem arises mostly when we forget to use `organization` in where.

Though not sure if I should focus on that considering, we are looking for prisma alternatives.

**Review by hariombalhara — APPROVED** [review]
LGTM!!

**Review by hariombalhara — CHANGES_REQUESTED** [review]
Typechecks are failing

File: packages/features/bookings/lib/handleNewBooking.ts (hunk 2 above)
Comment (joeauyeung) [reply packages/features/bookings/lib/handleNewBooking.ts:749]: I noticed that `req.headers.host` is being passed to `orgDomainConfig` which I think is similar to `userOrgQuery`.

File: packages/features/ee/organizations/lib/orgDomains.ts (hunk 3 above)
Comment (joeauyeung) [reply packages/features/ee/organizations/lib/orgDomains.ts:69]: I noticed that `orgDomainConfig` and `getSlugOrRequestedSlug` were called together in multiple places throughout the app, so I created this function. Looking through the codebase I noticed this is happening more than just the file that is linked.

**Review by hariombalhara — APPROVED** [review]
Types issue resolved now. LGTM !!

**Comment by alannnc** [comment]
@joeauyeung Should we merge? It was already approved by me but not sure if we waiting on something?
