### PR TITLE
fix: #15749 Display availability page as per weekstart setting

### LINKED ISSUE #15749: Respect "Start of week" Setting also on Availability Dashboard
### Issue Summary & Steps to Reproduce
Currently the account settings allow to override the default Start of the week.
As per my current settings the Start of the week is set to Monday.

Settingslink: https://app.cal.com/settings/my-account/general
image

On the Availability Overview Dashboard the set working hours still show Sunday first: https://app.cal.com/availability
image

Please make sure to respect the Start of the Week Setting also on the Availability Dashboard.

### Actual Results
On Availability Dashboard still the Times show from Sunday to Saturday

### Expected Results
Based on the Setting the Start of Week Setting should be respected.
In our Case times should be Mondy - Sunday.

### PR DESCRIPTION
**Pull request by vijayraghav-io**
## What does this PR do?

- Fixes #15749 
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

After Changes: 
https://www.loom.com/share/259b91928d0847f4af87e94808bee955?sid=2e2a41ee-7f6e-4ba7-9f16-61688e161915

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by masteradhoc** [comment]
@vijayraghav-io looks amazing, thanks for the fast fix 👍🏻

**Comment by vijayraghav-io** [comment]
> @vijayraghav-io looks amazing, thanks for the fast fix 👍🏻

Thank you! @masteradhoc

File: apps/web/components/eventtype/EventAvailabilityTab.tsx [hunk 1]
```diff
@@ -87,14 +87,18 @@ const EventTypeScheduleDetails = memo(
       { enabled: !!scheduleId || !!loggedInUser?.defaultScheduleId || !!selectedScheduleValue }
     );
 
+    const weekStart = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"].indexOf(
+      loggedInUser?.weekStart || "Sunday"
+    ) as 0 | 1 | 2 | 3 | 4 | 5 | 6;
+
```
Comment (surajgjadhav) [inline apps/web/components/eventtype/EventAvailabilityTab.tsx:93]: We can move this logic to util. so, it will get used in sorting function as well
Thanks

File: packages/features/schedules/components/ScheduleListItem.tsx [hunk 2]
```diff
@@ -58,12 +60,32 @@ export function ScheduleListItem({
...
+                    ) as 0 | 1 | 2 | 3 | 4 | 5 | 6,
+                    "short"
+                  );
+                  const weekIndex = (day: string) => {
+                    for (let i = 0; i < weekNames.length; i++) {
+                      if (day.includes(weekNames[i])) return i;
+                    }
+                    return -1;
+                  };
+                  return weekIndex(a) - weekIndex(b);
```
Comment (surajgjadhav) [inline packages/features/schedules/components/ScheduleListItem.tsx:84]: Hi,
Instead of repeating this logic in both ScheduleListItem.tsx and AvailabilitySetigs.tsx, we can move this to common util and reuse it in both files.
Thanks

**Review by surajgjadhav — CHANGES_REQUESTED** [review]
Hi @vijayraghav-io, 
Small Suggestions
Please Check
thanks

File: packages/platform/atoms/availability/AvailabilitySettings.tsx [hunk 3]
```diff
@@ -291,11 +292,32 @@ export function AvailabilitySettings({
...
+                ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"].indexOf(
+                  weekStart || "Sunday"
+                ) as 0 | 1 | 2 | 3 | 4 | 5 | 6,
+                "short"
+              );
+              const weekIndex = (day: string) => {
+                for (let i = 0; i < weekNames.length; i++) {
+                  if (day.includes(weekNames[i])) return i;
+                }
+                return -1;
```
Comment (Amit91848) [inline packages/platform/atoms/availability/AvailabilitySettings.tsx:314]: Same as @surajgjadhav suggested, make it reusable.

**Review by Amit91848 — CHANGES_REQUESTED** [review]

File: packages/platform/atoms/availability/AvailabilitySettings.tsx (hunk 3 above)
Comment (vijayraghav-io) [reply packages/platform/atoms/availability/AvailabilitySettings.tsx]: done

File: packages/lib/weekstart.ts [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+// sorts the availability strings based on the weekStart
+export function sortAvailabilityStrings(language: string, weekStart = "Sunday") {
+  return (a: string, b: string) => {
+    const weekNames = weekdayNames(language, weekStartNum(weekStart), "short");
+    const weekIndex = (day: string) => {
+      for (let i = 0; i < weekNames.length; i++) {
+        if (day.includes(weekNames[i])) return i;
+      }
+      return -1;
+    };
```
Comment (Amit91848) [inline packages/lib/weekstart.ts:20]: Why not use indexOf here as well?

**Review by Amit91848 — CHANGES_REQUESTED** [review]
Tested and works great! Thanks for adding a test as well. I have updated test description and left a small suggestion.

File: packages/lib/weekstart.ts (hunk 4 above)
Comment (vijayraghav-io) [reply packages/lib/weekstart.ts:20]: indexOf searches for the exact match of string in array, but here will not have exact match in weekNames. The input string will be of 'Mon - Tue , 12AM - 2PM' or 'Fri , Tue - Thu, .... hence iterating and using includes

**Review by Amit91848 — APPROVED** [review]
LGTM! Thanks @vijayraghav-io

**Review by surajgjadhav — APPROVED** [review]
Thanks @vijayraghav-io 👍
