### PR TITLE
Hotfix: guest are not added to the invite and emails

### LINKED ISSUE #7759: Guests are not added to the invite and emails
### Issue Summary

When scheduling with additional guests, they're not being added to the invite nor receiving emails or displayed in the confirmatin screen.

### Steps to Reproduce

1. Select any event type to schedule
2. Enter your name and email
3. Add 1 or more additional guests
4. Check the confirmation, emails sent and calendar

**Here's the input:**
image

**Here's the confirmation screen:**
image

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

Fixes #7759 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by hariombalhara — APPROVED** [review]

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 1]
```diff
@@ -692,18 +692,15 @@ async function handler(
...
-        return guestArray;
-      } else {
-        guestArray.push({
-          email: guest,
-          name: "",
-          timeZone: reqBody.timeZone,
-          language: { translate: tGuests, locale: "en" },
-        });
-      }
+    if (isTeamEventType && users.some((user) => user.email === guest)) {
```
Comment (hariombalhara) [inline packages/features/bookings/lib/handleNewBooking.ts:695]: @G3root Simplified the condition. Please review it.

Comment (G3root) [reply packages/features/bookings/lib/handleNewBooking.ts:695]: LGTM 👍🏼
