### PR TITLE
fix/saving-stripe-price-for-event-type

### LINKED ISSUE #5875: [CAL-535] Issue with Stripe App
Issue with Stripe App when trying to add a price

BAD_REQUEST: \[ { "code": "invalid_type", "expected": "number", "received": "nan", "path": \[ "metadata", "apps", "stripe", "price" \], "message": "Expected number, received nan" } \]

Created via Threads. See full discussion: [https://threads.com/34436815265](https://threads.com/34436815265)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-535](https://linear.app/calcom/issue/CAL-535/issue-with-stripe-app)</sub>

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

Converts number from input using Number().

Fixes #5875 

**Environment**: Staging(main branch) / Production

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by PeerRich — APPROVED** [review]

File: packages/app-store/stripepayment/extensions/EventTypeAppCard.tsx [hunk 1]
```diff
@@ -61,7 +61,7 @@ const EventTypeAppCard: EventTypeAppCardComponent = function EventTypeAppCard({
                 className="block w-full rounded-sm border-gray-300 pl-2 pr-12 text-sm"
                 placeholder="Price"
                 onChange={(e) => {
-                  setAppData("price", e.target.valueAsNumber * 100);
```
Comment (zomars) [inline packages/app-store/stripepayment/extensions/EventTypeAppCard.tsx:64]: @alannnc why is `valueAsNumber` not used anymore? This is from [RHF](https://react-hook-form.com/api/useform/register/#options) btw

Comment (alannnc) [reply packages/app-store/stripepayment/extensions/EventTypeAppCard.tsx:64]: Probably something changed, valueAsNumber was being picked up correctly.
