### PR TITLE
fix: MSTeams not created as online meetings 

### LINKED ISSUE #14765: [Bug] MS Teams + MS Calendar Bad Implementation
### Issue Summary

Microsoft Teams + Microsoft Outlook Calendar Meetings are not being created as online meetings, and have unprofessional description.

### Steps to Reproduce

1. Install MS Teams app from the app marketplace
2. Setup MS Outlook as your main Calendar
3. Create a Booking and set MS Teams as the meeting software
4. Book a meeting
5. Atendees will receive 2 emails: 1 from Cal.com + 1 from MS Calendar

### Actual Results

- Attendees will get 2 emails. 1 from Cal.com and 1 from MS Calendar
- The one from MS Calendar looks like this:
image

- When I go to MS Teams to check this is what I see:
image

### Expected Results

- This is what that email would normally look like when I create a meeting through Calendly or MS Teams directly:
image

-
_Notice how the location is Not the Meeting Link but an arbitrary URL, in this case Calendly's event, and the "Online Meeting" switch is turned on, letting Microsoft handle the link creation, instead of creating a link and then attaching it to the calendar event_
image

### PR DESCRIPTION
**Pull request by vijayraghav-io**
## What does this PR do?

- Fixes #14765 
- Fixes CAL-3446
/claim #14765 

#### Video Demo:
Before fix (or issue):
https://www.loom.com/share/87082087c5f64e368494ec6aea834a48?sid=4c3724fa-5c6a-4a57-8b25-d32e6989404d

After fix :
https://www.loom.com/share/75f976cf3b6f4b27b5da3301089fb2fd?sid=fe926a95-9953-4797-a7f0-bc6524f35c83

Changes in /apps/msteams (MSTeams installation page with dependency added)
https://www.loom.com/share/2881ab3bf573453585a029016c82b3ba?sid=478b4496-9112-43b0-a3db-f6050a2baaf3

#### Image Demo :

- Add side-by-side screenshots of the original and updated change.
<table>
  <tr>
    <th>Before Fix</th>
    <th>After Fix</th>
  </tr>
  <tr>
   <td>Screenshot 2025-05-17 at 9 53 17 PM</td>
    <td>Screenshot 2025-05-17 at 9 28 23 PM</td>
  </tr>
  
  <tr>
    <td>
Screenshot 2025-05-17 at 9 54 20 PM
 </td>
    <td>
Screenshot 2025-05-17 at 9 29 35 PM
 </td>
  </tr>

<tr>
    <td>
Screenshot 2025-05-20 at 12 36 02 AM
 </td>
    <td>
Screenshot 2025-05-20 at 12 34 58 AM
 </td>
  </tr>
</table>

- Highlight any significant change(s).
The root cause for the issue is -
   - `/onlineMeetings` endpoint was used to create MSTeam meetings in office365video/lib/VideoApiAdapter.ts. But as per microsoft Graph API doc -
https://learn.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=javascript 
Screenshot 2025-05-17 at 11 13 59 PM
This endpoint does not create an onlineMeeting.
For MSTeam event to look as onlineMeeting it should be associated with an event or in other words it should be created using `/events` endpoint as recommended here

https://learn.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&tabs=javascript#example-4-create-and-enable-an-event-as-an-online-meeting

with key properties set `allowNewTimeProposals: true` , `isOnlineMeeting: true`, `onlineMeetingProvider: 'teamsForBusiness'`

   - Also duplicate events or emails were generated because a event was created on outlook calendar using calendar service, and `/onlineMeetings` also created an event on same calendar by office365video/lib/VideoApiAdapter.

   - Implemented a check in this PR -> to not create meeting using office365video/lib/videoApiAdapter, but the office365calendar/lib/CalendarService with /events endpoint will be used to create onlineMeeting by passing required parameters..

   - Also the body content should be of type `HTML` and html content has to be input in body for /event endpoint , for the texts and content to look good along with `Microsoft Teams` details at the end of the body with meeting details. This resolves content not looking good.

  - MSTeams automatically send mails to attendees with the body passed in `/events` endpoint. Also appending its meeting details like url, passcode, id,...

  - Added a dependency to MSTeams installation in app-store, this suggests or warns user if they are trying to install MSTeams without outlook calendar and recommends to install outlook calendar first.
  
  - Also updated the `updateEvent` in office365calendar/lib/CalendarService.ts
  `updateEvent` updates or moves the meeting without loosing its `onlineMeeting` feature by getting the meeting blob first in the existing body and then patching it. Without this blob patch the updated meeting becomes non-onlineMeeting (or without msTeams feature)
https://learn.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&tabs=javascript
Screenshot 2025-05-17 at 11 42 19 PM

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] - N/A - I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.
This functionality test requires verification on external app - MSTeams and can be verified visually.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
   Install Microsoft outlook calendar and MS teams with a work account for a organizer in cal
- What is expected (happy path) to have (input and output)?
   The events on MS teams should be created as online meetings.
   The text should be formatted correctly inside this event on MS teams.
   The buttons 'Join' , label 'Microsoft Teams Meeting' for location should be visible.
   It should be marked as online meeting when event is opened to edit.
   Should be able to reschedule and the rescheduled event should also be 'online meeting'.
- Any other important info that could help to test that PR
    

---

## Summary by mrge
Fixed an issue where MS Teams events were not created as online meetings and prevented duplicate calendar events in Outlook when using MS Teams.

- **Bug Fixes**
  - Ensured MS Teams events are always marked as online meetings with correct formatting and join links.
  - Skipped creating duplicate Outlook calendar events when a Teams meeting is already created.

### CODE REVIEW

**Comment by anikdhabal** [comment]
@vijayraghav-io thanks for your work. But it looks more like a workaround, also i am already working on it. Closing it for now

File: packages/app-store/office365video/api/add.ts [hunk 1]
```diff
@@ -6,7 +6,7 @@ import { WEBAPP_URL_FOR_OAUTH } from "@calcom/lib/constants";
 import getAppKeysFromSlug from "../../_utils/getAppKeysFromSlug";
 import { encodeOAuthState } from "../../_utils/oauth/encodeOAuthState";
 
-export const OFFICE365_VIDEO_SCOPES = ["OnlineMeetings.ReadWrite", "offline_access"];
+export const OFFICE365_VIDEO_SCOPES = ["OnlineMeetings.ReadWrite", "offline_access", "Calendars.ReadWrite"];
```
[the remark this answers is not in the document]
Comment (vijayraghav-io) [reply packages/app-store/office365video/api/add.ts:9]: I guess this is the only way to go , Users have to re-install , as MS Teams need to create events on calendar for it be treated as online meeting. Hence this permission is required.

**Comment by vijayraghav-io** [comment]
> @vijayraghav-io thanks for your work. But it looks more like a workaround, also i am already working on it. Closing it for now

Please note, this is not work around.
The other approach would be to update createEvent() function in office365Calendar Service to include 'isOnlineMeeting' property to true , if MSTeams is installed.
But , how it will work for users who have only MSTeams installed and not outlook calendar?

**Comment by anikdhabal** [comment]
@vijayraghav-io Let's approach this in a way that doesn't affect active users. There are many users who have already installed and are actively using it. It doesn’t make sense to break it for them and ask them to reinstall. If users are happy with the current setup, we shouldn’t force them to go through that process. So let's find a fix that preserves the existing experience

**Review by anikdhabal — CHANGES_REQUESTED** [review]
Let's approach this in a way that doesn't affect active users. There are many users who have already installed and are actively using it. It doesn’t make sense to break it for them and ask them to reinstall. If users are happy with the current setup, we shouldn’t force them to go through that process. So let's find a fix that preserves the existing experience

**Comment by vijayraghav-io** [comment]
To update the prgoress:
- Pushed changes without changing scopes.
- Skipping VideoMeeting Creating by making MSTeams has non-dedicated integration similar to google meet.
- Updated CreateEvent() and UpdateEvent() in office365calendar/lib/CalendarService to create/update events as 'onlineMeeting' based on the event.location, if MSTeams (i.e. integrations:office365video).

Tested the working with an work account in MSTeams and outlook calendar.

Will update more notes , by testing different scenarios for existing users and existing bookings.
Will do one more round of self-review, before moving it from draft.

**Comment by vijayraghav-io** [comment]
Update:
Almost all changes are done. 
Also tested different scenarios.
Updated description with changes in app installation page for `msteams`.
Will move it out of draft after adding some self-review comments.

File: packages/app-store/components.tsx [hunk 2]
```diff
@@ -137,7 +137,7 @@ export const AppDependencyComponent = ({
                         {t("this_app_requires_connected_account", {
                           appName,
                           dependencyName: dependency.name,
-                        })}
+                        }).replaceAll(/&#x2F;/g, "/")}
```
Comment (vijayraghav-io) [inline packages/app-store/components.tsx:140]: without this replaceAll(), the dependency component , appears like this 
Screenshot 2025-05-20 at 12 24 17 AM

File: packages/app-store/office365calendar/lib/CalendarService.ts [hunk 3]
```diff
@@ -256,7 +257,13 @@ export default class Office365CalendarService implements Calendar {
...
       });
 
-      const responseJson = await handleErrorsJson<NewCalendarEventType & { iCalUId: string }>(response);
+      const responseJson = await handleErrorsJson<
+        NewCalendarEventType & { iCalUId: string; onlineMeeting?: { joinUrl?: string } }
+      >(response);
+
+      if (responseJson?.onlineMeeting?.joinUrl) {
+        responseJson.url = responseJson?.onlineMeeting?.joinUrl;
+      }
```
Comment (vijayraghav-io) [inline packages/app-store/office365calendar/lib/CalendarService.ts:266]: the meeting `url` has to be extracted from response after onlineMeeting is created.
This is required to update `event.videoCallData` in EventManager, like how it was done before when video createMeeting() was called.
Eventually this url would be used to render as link in booking success page and also other records like `Booking` (metadata column), `BookingReference`, also to include meeting links in mails sent by Cal.

File: packages/app-store/office365calendar/lib/CalendarService.ts [hunk 4]
```diff
@@ -268,12 +275,28 @@ export default class Office365CalendarService implements Calendar {
...
+      let rescheduledEvent: Event | undefined;
+      if (event.location === MSTeamsLocationType) {
+        // Extract the existing body content to preserve the meeting blob, otherwise it breaks and converts it into non-onlineMeeting
+        const response = await this.fetcher(`${await this.getUserEndpoint()}/calendar/events/${uid}`, {
+          method: "GET",
+        });
+
+        rescheduledEvent = await handleErrorsJson<Event>(response);
+      }
+
```
Comment (vijayraghav-io) [inline packages/app-store/office365calendar/lib/CalendarService.ts:287]: For Reschedule - before sending PATCH request, the body property of original event has to be retrieved.
This contains meeting details like id, passcode that MSTeams had embedded during first/original meeting creation. 
And then the new content can be appended.
Without this step, the rescheduled becomes Non-OnlineMeeting (i.e. without MSTeams features)

Ref - https://learn.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&tabs=javascript

File: packages/app-store/office365calendar/lib/CalendarService.ts [hunk 5]
```diff
@@ -403,12 +426,30 @@ export default class Office365CalendarService implements Calendar {
...
+    const isOnlineMeeting = event.location === MSTeamsLocationType;
+    const isRescheduledOnlineMeeting = rescheduledEvent ? rescheduledEvent.isOnlineMeeting : false;
+    const existingBody =
+      rescheduledEvent?.body?.contentType === "html" ? rescheduledEvent.body.content : undefined;
+
+    let content = "";
+    if (isOnlineMeeting) {
+      if (isRescheduledOnlineMeeting && existingBody) {
+        content = `
+        ${getRichDescriptionHTML(event)}<hr>
```
Comment (vijayraghav-io) [inline packages/app-store/office365calendar/lib/CalendarService.ts:439]: For OnlineMeetings, the body of event should be in HTML format to get proper look and feel when opened in MSTeams.
Otherwise the text and links appear separately.

**HTML**
Screenshot 2025-05-17 at 9 29 35 PM

**Text**
Screenshot 2025-05-17 at 6 46 50 PM

File: packages/app-store/office365calendar/lib/CalendarService.ts [hunk 6]
```diff
@@ -458,6 +499,17 @@ export default class Office365CalendarService implements Calendar {
...
+    if (isOnlineMeeting) {
+      office365Event.isOnlineMeeting = true;
+      office365Event.allowNewTimeProposals = true;
+      office365Event.onlineMeetingProvider = "teamsForBusiness";
+      // MSTeams sets location as 'Microsoft Teams Meeting' by default, if location is undefined.
+      // For backward compatibility, setting explicitly.
+      office365Event.location =
+        rescheduledEvent && !isRescheduledOnlineMeeting
+          ? { displayName: "Microsoft Teams Meeting" }
+          : undefined;
```
Comment (vijayraghav-io) [inline packages/app-store/office365calendar/lib/CalendarService.ts:511]: For backward compatibility, .i.e meetings created before that were intended to be onlineMeetings but were not created as onlineMeetings, setting location explicitly to 'Microsoft Teams Meeting'.
Otherwise it will show the location with a link when those meetings are rescheduled.

File: packages/lib/EventManager.ts [hunk 7]
```diff
@@ -219,6 +221,24 @@ export default class EventManager {
         evt["conferenceCredentialId"] = undefined;
       }
     }
```
Comment (vijayraghav-io) [inline packages/lib/EventManager.ts:223]: The checks currently done if only google meet is selected without google calendar, same is implemented if only MSTeams is selected without outlook calendar.
The same logic along with comments are done for MSTeams.

Without this check, the `/onlineMeetings` endpoint in videoApiAdapter for office365video, creates Non-OnlineMeetings.

File: packages/lib/EventManager.ts [hunk 8]
```diff
@@ -251,6 +271,31 @@ export default class EventManager {
...
+          evt.responses["location"] = {
+            ...(evt.responses["location"] ?? {}),
+            value: {
+              optionValue: "",
+              value: evt.location,
+            },
+          };
+        }
+      }
+    }
```
Comment (vijayraghav-io) [inline packages/lib/EventManager.ts:297]: The way `evt.videoCallData` was updated after creating meeting in office365video, 
the same is done now after event is created by office365calendar service.

**Comment by vijayraghav-io** [comment]
@anikdhabal , Please refer my previous comments as well 🙏 

I have testing the following scenarios -
Existing Users:
- New Bookings -> CreateNewBooking, Reschedule on this, Delete - all works well . Attached After fix Video covers these.
- Reschedule existing bookings -> Taken care of transitioning the non-online Meeting to onlineMeeting if its rescheduled.



**Alternate Approach (with Scope Change)** -
We can still append the scope in `office365video/api/add.ts` with `Calendars.ReadWrite`.
We can handle it without requiring enduser to re-install msteams app in cal.
**For DelegatedCredentials** :
- In Azure, inside existing App registration, the API permission `Calendars.ReadWrite` has to be added as `Application` type permission (and not delegated).
- Admin consent has to be granted, by clicking on a button here as shown below.
Screenshot 2025-05-20 at 12 41 29 PM
- By granting admin consent, the next time when accessToken is requested from our code with new scope, the required calendar permissions are granted without requiring user consent (or app re-install) as admin has already consented in portal. This works for 'client_credentials' flow which we use for DelegatedCredential scenarios.
If we are targeting platform users, this one time configuration can be done on Azure portal without enduser's involvement.


**For Non-DelegatedCredentials**:
- OnlineMeeting is tried to create using `/events` endpoint in office365video/lib/VideoApiAdapter with updated scopes, the oauth/token request fails or the endpoint returns error if no required permissions (or if app is not re-installed).
- For such cases, the `url` returned would be null or `createdEvent.result.success` would be false.
- If such error occurs, we can use `CalendarService's /events` endpoint to create onlineMeeting (as a fallback). I had included this condition in my first approach, checking if `joinUrl` could not be obtained from msTeams app then use outlook calendar app.

With this approach there will be no dependency on MSTeams app installation.

File: packages/app-store/components.tsx (hunk 2 above)
Comment (vijayraghav-io) [reply packages/app-store/components.tsx:140]: tested with other languages as well

Comment (Udit-takkar) [reply packages/app-store/components.tsx:140]: You should use this property here instead https://www.i18next.com/translation-function/interpolation

File: packages/app-store/components.tsx [hunk 9]
```diff
@@ -152,7 +152,10 @@ export const AppDependencyComponent = ({
                 </div>
                 <div>
                   <span className="font-semibold">
-                    {t("this_app_requires_connected_account", { appName, dependencyName: dependency.name })}
+                    {t("this_app_requires_connected_account", {
+                      appName,
+                      dependencyName: dependency.name,
+                    }).replaceAll(/&#x2F;/g, "/")}
```
Comment (Udit-takkar) [inline packages/app-store/components.tsx:158]: same https://www.i18next.com/translation-function/interpolation

File: packages/app-store/components.tsx (hunk 2 above)
Comment (vijayraghav-io) [reply packages/app-store/components.tsx]: done

**Comment by vijayraghav-io** [comment]
@anikdhabal / @Udit-takkar reminding for review 🙏 .

**Comment by anikdhabal** [comment]
I will review it shortly

**Comment by anikdhabal** [comment]
@vijayraghav-io is your pr fix this? Because the linked issue started from this and aims to fix the double email sending issue?

```Steps to Reproduce

1. Install MS Teams app from the app marketplace
2. Setup MS Outlook as your main Calendar
3. Create a Booking and set MS Teams as the meeting software
4. Book a meeting
5. Atendees will receive 2 emails: 1 from Cal.com + 1 from MS Calendar. It's fine and expected that they get two emails.```

**Comment by vijayraghav-io** [comment]
> @vijayraghav-io is your pr fix this? Because the linked issue started from this and aims to fix the double email sending issue?
> 
> ```
> 
> 1. Install MS Teams app from the app marketplace
> 2. Setup MS Outlook as your main Calendar
> 3. Create a Booking and set MS Teams as the meeting software
> 4. Book a meeting
> 5. Atendees will receive 2 emails: 1 from Cal.com + 1 from MS Calendar. It's fine and expected that they get two emails.```
> ```

@anikdhabal  
getting 2 emails is not an issue, also as highlighted here, it is as expected.
Also it is normal with any other calendar apps as well to get 1 email from cal and 1 from calendar app.

Screenshot 2025-07-01 at 1 11 19 PM

So, this PR resolves all other issues mentioned in this issue description https://github.com/calcom/cal.com/issues/14765, like
-  Event on MS Teams Calendar not created as `online meeting`
-  The text on this event on MS Teams is not formatted as expected
....

Please refer this PR description for more details.

**Comment by anikdhabal** [comment]
@vijayraghav-io The improvement looks good and should work fine for new installations. But how is backward compatibility being handled? I’ve seen that MS Calendar and MS Teams video dependent. Please make sure it doesn’t cause any issues for active MS Teams users. It should seamlessly support full CRUD operations for existing users without any problems

**Comment by vijayraghav-io** [comment]
> @vijayraghav-io The improvement looks good and should work fine for new installations. But how is backward compatibility being handled? I’ve seen that MS Calendar and MS Teams video dependent. Please make sure it doesn’t cause any issues for active MS Teams users. It should seamlessly support full CRUD operations for existing users without any problems

@anikdhabal Thank you! 🙏.
Yes had thought of backward compatibility while creating PR and was handled.
Please check my latest comments below.

**Comment by vijayraghav-io** [comment]
> @vijayraghav-io The improvement looks good and should work fine for new installations. But how is backward compatibility being handled? I’ve seen that MS Calendar and MS Teams video dependent. Please make sure it doesn’t cause any issues for active MS Teams users. It should seamlessly support full CRUD operations for existing users without any problems

@anikdhabal , verified this again.

**Scenario - For Users who have only MS Teams installed and no Outlook(or MS) Calendar, after this PR is released** :
**Create** : Cal Video link will be created for the booking as fallback. 
               Since Outlook calendar is not installed and only MS Teams, cal video link will be created as fallback and not MS Teams meeting link. This is in-line or similar to GoogleMeet & GoogleCalendar implementation.
               If we allow to create MS Teams meeting link (without MS Calendar being installed), we again get the same issues reported for which this PR was created (like no online-meeting and not formatted text on MSTeams event)
               So User would have to install Outlook Calendar to successfully create MSTeams video meeting with fixes from this PR.
**Read** : Read operation will not be affected
                   Users can still use the same MSTeam video meeting links created earlier (i.e. before this PR get merged)
**Update**:  If Users reschedule the MSTeam video meetings (or bookings) created earlier, a new MSTeam video meeting will be created. This is same as earlier flow and so its not affected.
                      But, the new or rescheduled video meetings will be of same type as earlier (not online-meeting type and not formatted text).
**Delete**: Not affected, users can cancel the bookings with MSTeams created earlier.


**Scenario - For Users who have both MS Teams and Outlook(or MS) Calendar installed, after this PR is released** :
**Create**: Users will have new improved seamless experience with new improved versions.
**Update**: If Users reschedule the bookings (with Outlook and MSTeams) created earlier, due care is taken to reschedule the Non-Online meeting types created earlier to new improved version. 
                      Kindly refer this my self-review comment - https://github.com/calcom/cal.com/pull/21377#discussion_r2096406716
**Read**: Not affected, bookings created earlier can be used.
**Delete**: Not affected, bookings created earlier can be deleted or canceled.

File: packages/lib/EventManager.ts [hunk 10]
```diff
@@ -299,6 +301,24 @@ export default class EventManager {
         evt["conferenceCredentialId"] = undefined;
       }
     }
+    // Fallback to Cal Video if MSTeams is selected w/o a Outlook Calendar connection
+    if (
+      evt.location === MSTeamsLocationType &&
+      mainHostDestinationCalendar?.integration !== "office365_calendar"
```
Comment (anikdhabal) [inline packages/lib/EventManager.ts]: How does it tackle backward compatibility? Doesn't it fall back to calling video in the existing app?

File: packages/lib/EventManager.ts [hunk 11]
```diff
@@ -331,6 +351,31 @@ export default class EventManager {
...
+          evt.responses["location"] = {
+            ...(evt.responses["location"] ?? {}),
+            value: {
+              optionValue: "",
+              value: evt.location,
+            },
+          };
+        }
+      }
+    }
```
[the remark this answers is not in the document]
Comment (anikdhabal) [reply packages/lib/EventManager.ts]: @vijayraghav-io fix it

File: packages/lib/CalEventParser.ts [hunk 12]
```diff
@@ -314,6 +314,58 @@ type RichDescriptionCalEvent = Parameters<typeof getCancellationReason>[0] &
...
+      .join("");
+  };
+
+  // Convert the manage link to a clickable hyperlink
+  const manageLinkText = getManageLink(calEvent, t);
+  const manageLinkHtml = manageLinkText
+    ? `<p><strong>${t("need_to_reschedule_or_cancel")}</strong> <a href="${manageLinkText
+        .split(" ")
+        .pop()}">${manageLinkText.split(" ").pop()}</a></p>`
+    : "";
```
[the remark this answers is not in the document]
Comment (vijayraghav-io) [reply packages/lib/CalEventParser.ts]: not able to see `t("need_to_reschedule_or_cancel")` in the suggested code, will check and update

File: packages/lib/EventManager.ts (hunk 11 above)
[the remark this answers is not in the document]
Comment (vijayraghav-io) [reply packages/lib/EventManager.ts]: will address this

File: packages/lib/EventManager.ts (hunk 10 above)
Comment (vijayraghav-io) [reply packages/lib/EventManager.ts]: This is in the `create()` method.
Yes it fall backs to `cal video`, when new event is tried to create if no Outlook installed.
But for `update()` method, i.e. reschedule of existing MSTeam event created earlier (backward compatibility) new MSTeam meeting will be created as earlier.

Please refer this comment https://github.com/calcom/cal.com/pull/21377#issuecomment-3074650585

Comment (anikdhabal) [reply packages/lib/EventManager.ts]: No, don't like this behavior. There should be backward compatibility for create method also

Comment (vijayraghav-io) [reply packages/lib/EventManager.ts]: In that case `only MSTeam` users (.i.e users with only MSTeam installed without outlook integrated into cal) would still see the meetings in the older format (.i.e non-online meeting and text not formatted) when they open the event in their MSTeams Calendar.

The new improved look and feel can be seen for users who have both MSTeams and Outlook integrated with cal.
Kindly confirm if this is ok.

Reason being the MS endpoint `/calendar/events` can be used only if outlook is installed and online meetings can be created with this endpoint only (please refer PR description with link to MS docs)

The fallback approach to cal video if only MSTeams installed is similar to google calendar and google meet implementation. In this way we are avoiding creation of standalone (Non-online meetings, not tied to a calendar) event on MSTeams.

Also had mentioned the same in my prev comment https://github.com/calcom/cal.com/pull/21377#issuecomment-3074650585
>If we allow to create MS Teams meeting link (without MS Calendar being installed), we again get the same issues >reported for which this PR was created (like no online-meeting and not formatted text on MSTeams event)
>So User would have to install Outlook Calendar to successfully create MSTeams video meeting with fixes from this >PR.

Comment (vijayraghav-io) [reply packages/lib/EventManager.ts]: @anikdhabal 
probably or assuming that this issue is of concern only for (or reported by) users who have installed both MSTeams and Outlook, we can remove 'cal video' fallback approach.
And assuming that the set of users who have only MSTeams installed are ok with the way events being created currently on MSTeams.

I have removed the `cal video` approach , kindly let me know if decision is taken the other way, i can revert this.

File: packages/lib/EventManager.ts [hunk 13]
```diff
@@ -251,6 +251,34 @@ export default class EventManager {
...
+    evt: CalendarEvent,
+    results: Array<EventResult<Exclude<Event, AdditionalInformation>>>
+  ) {
+    if (evt.location === MSTeamsLocationType) {
+      const office365CalendarWithTeams = results.find(
+        (result) => result.type === "office365_calendar" && result.success && result.createdEvent?.url
+      );
+      if (office365CalendarWithTeams) {
+        evt.videoCallData = {
+          type: "office365_video",
```
Comment (anikdhabal) [inline packages/lib/EventManager.ts]: `updateVideoCallData` is only used in the context of MS Teams or Outlook Calendar. So let's change the method name to reflect that

File: packages/lib/EventManager.ts [hunk 14]
```diff
@@ -405,6 +438,8 @@ export default class EventManager {
     const calendarReference = booking.references.find((reference) => reference.type.includes("_calendar"));
     if (calendarReference) {
       results.push(...(await this.updateAllCalendarEvents(evt, booking)));
+
+      this.updateVideoCallData(evt, results);
```
Comment (anikdhabal) [inline packages/lib/EventManager.ts]: Let's add the if block here — `if (evt.location === MSTeamsLocationType)` — instead of using in the `updateVideoCallData` method

File: packages/lib/EventManager.ts [hunk 15]
```diff
@@ -331,6 +362,8 @@ export default class EventManager {
     // Create the calendar event with the proper video call data
     results.push(...(await this.createAllCalendarEvents(clonedCalEvent)));
 
+    this.updateVideoCallData(evt, results);
```
Comment (anikdhabal) [inline packages/lib/EventManager.ts]: Let's add the if block here — if (evt.location === MSTeamsLocationType) — instead of using in the updateVideoCallData method

**Review by anikdhabal — CHANGES_REQUESTED** [review]
Few tweaks

File: packages/lib/EventManager.ts (hunk 13 above)
Comment (vijayraghav-io) [reply packages/lib/EventManager.ts]: thought of having this function generic so that if any other location specific logic in future can be handled here.
Yeah until then, we can avoid a function call for all other location types by making this function specific to MSTeams,
Updated.

File: packages/lib/CalEventParser.ts (hunk 12 above)
[the remark this answers is not in the document]
Comment (vijayraghav-io) [reply packages/lib/CalEventParser.ts]: since we have control on the input , the input is not coming from external sources.
The functions `getManageLink()` and `getPlatformManageLink()` always ensure the last word would be a link.
Hence avoiding the usage of regex here.

**Review by anikdhabal — APPROVED** [review]
Looks good 👍

File: packages/lib/CalEventParser.ts [hunk 16]
```diff
@@ -314,6 +314,64 @@ type RichDescriptionCalEvent = Parameters<typeof getCancellationReason>[0] &
...
+
+  // Build the HTML content for each section
+  const parts = [
+    textToHtml(getCancellationReason(calEvent, t)),
+    textToHtml(getWhat(calEvent, t)),
+    textToHtml(getWhen(calEvent, t)),
+    textToHtml(getWho(calEvent, t)),
+    textToHtml(getDescription(calEvent, t)),
+    textToHtml(getAdditionalNotes(calEvent, t)),
+    textToHtml(getUserFieldsResponses(calEvent, t)),
```
Comment (volnei) [inline packages/lib/CalEventParser.ts:360]: It would be good to have a "where" section here!

Comment (vijayraghav-io) [reply packages/lib/CalEventParser.ts:360]: currently fn `getRichDescriptionHTML()` is used only by office365 Calendar service to create HTML content.
This content is passed as payload for MS Graph API. This HTML content will be rendered inside MSTeams.
So here its not required to specify location as MS Teams explicitly, instead the meeting link will be appended by MS.

Whereas fn `getRichDescription()` is used by Cal to create email body/content, there it would be required to specify the location.

**Review by volnei — APPROVED** [review]

**Comment by vijayraghav-io** [comment]
Thank you! 🙏
