### PR TITLE
fix: #16079 hide settings/Admin API if not org and update link to sales

### LINKED ISSUE #16079: [CAL-4114] Hide Admin API Key from Individuals and Teams View
Only display to organization customers 

Instead of linking enterprise sales booking link, link cal.com/sales

cc @alishaz-polymath 

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4114](https://linear.app/calcom/issue/CAL-4114/hide-admin-api-key-from-individuals-and-teams-view)</sub>

### PR DESCRIPTION
**Pull request by vijayraghav-io**
## What does this PR do?

- Fixes #16079 
- Fixes CAL-4114

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A - I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [x] N/A - I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

File: packages/features/settings/layouts/SettingsLayout.tsx [hunk 1]
```diff
@@ -182,8 +182,10 @@ const useTabs = () => {
           (childTab) => childTab.href !== "/settings/security/two-factor-auth"
         );
         return { ...tab, children: filtered };
-      } else if (tab.href === "/settings/developer" && !!orgBranding) {
-        const filtered = tab?.children?.filter((childTab) => childTab.name !== "admin_api");
+      } else if (tab.href === "/settings/developer") {
+        const filtered = tab?.children?.filter((childTab) =>
+          childTab.name === "admin_api" ? isOrgAdminOrOwner : true
+        );
```
Comment (anikdhabal) [inline packages/features/settings/layouts/SettingsLayout.tsx:188]: The issue describes that Only display this to organization customers. SO why the checks for isOrgAdminOrOwner?

**Review by anikdhabal — CHANGES_REQUESTED** [review]

File: packages/features/settings/layouts/SettingsLayout.tsx (hunk 1 above)
Comment (vijayraghav-io) [reply packages/features/settings/layouts/SettingsLayout.tsx]: by "Admin API" i inferred as only for admin, updated.
true was to allow other childtabs to pass through filter in that case.

Comment (anikdhabal) [reply packages/features/settings/layouts/SettingsLayout.tsx]: Hey Vijay, talk to the team. Yes, organization customers mean it will only be visible to the org admin/owner. So your previous check was correct, but code needs to improve a bit. Let me update it.

Comment (vijayraghav-io) [reply packages/features/settings/layouts/SettingsLayout.tsx]: ok, updated

**Review by anikdhabal — APPROVED** [review]
LGTM !! Thanks for your works @vijayraghav-io
