### PR TITLE
fix: add no show guest

### LINKED ISSUE #18023: [CAL-4850] add no-show (guest) to /insights export
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4850](https://linear.app/calcom/issue/CAL-4850/add-no-show-guest-to-insights-export)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

- Fixes https://github.com/calcom/cal.com/issues/18023 (GitHub issue number)
- Fixes CAL-4850 (Linear issue number - should be visible at the bottom of the GitHub issue description)

Screenshot 2024-12-10 at 12 24 42 AM

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] N/A I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

Go to /insights
Click on download

### CODE REVIEW

File: packages/features/insights/server/events.ts [hunk 1]
```diff
@@ -442,6 +444,7 @@ class EventsInsights {
 
       return {
         ...bookingTimeStatus,
+        bookerNoShow: booker.noShow,
```
Comment (PeerRich) [inline packages/features/insights/server/events.ts:447]: can we call this noShowGuest? to be consistent with

- No-Show (Guests)
- No-Show (Hosts)

**Review by keithwillcode — APPROVED** [review]
