### PR TITLE
fix: Recurring meeting creates increasing number of Zoom events

### LINKED ISSUE #14171: [CAL-4158] Recurring meeting creates increasing number of Zoom events
### Issue Summary

Creating a recurring event creates increasing number of Zoom events as the series adance

### Steps to Reproduce

1. Create a recurring event for 4 meetings with Zoom meeting.

Screen Shot 2024-03-21 at 11 06 10

Screen Shot 2024-03-21 at 11 06 53

### Actual Results

- In the Zoom app, you'll see one Zoom meeting on the first event, two on the second, three on the third, etc.

Screen Shot 2024-03-21 at 11 07 13
Screen Shot 2024-03-21 at 11 07 20
Screen Shot 2024-03-21 at 11 07 38
Screen Shot 2024-03-21 at 11 07 55

### Expected Results

- Only one Zoom event created on each day (or even better a recurring meeting - but a single meeting per event would be just fine).

<sub>[CAL-4158](https://linear.app/calcom/issue/CAL-4158/recurring-meeting-creates-increasing-number-of-zoom-events)</sub>

### PR DESCRIPTION
**Pull request by anikdhabal**
## What does this PR do?

- Fixes #14171

### CODE REVIEW

File: packages/app-store/zoomvideo/lib/VideoApiAdapter.ts [hunk 1]
```diff
@@ -105,7 +105,7 @@ const ZoomVideoApiAdapter = (credential: CredentialPayload): VideoApiAdapter =>
       recurringEvent,
       startTime,
       attendees,
-    }: CalendarEvent): { recurrence: ZoomRecurrence; type: 8 } | undefined => {
+    }: CalendarEvent): { recurrence: ZoomRecurrence } | undefined => {
```
Comment (anikdhabal) [inline packages/app-store/zoomvideo/lib/VideoApiAdapter.ts:108]: Now only one Zoom event will create on each interval

**Review by alishaz-polymath — APPROVED** [review]
🚀 🚀 🚀 🚀
