### PR TITLE
fix: booking confirmation email missing variables

### LINKED ISSUE #7097: [CAL-1063] Booking Confirmation Email not Loading Variables
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1063](https://linear.app/calcom/issue/CAL-1063/booking-confirmation-email-not-loading-variables)</sub>

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

Fixes #7097 

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by emrysal — APPROVED** [review]
Looks good to me :)

File: packages/emails/src/templates/AttendeeRequestEmail.tsx [hunk 1]
```diff
@@ -1,22 +1,30 @@
...
-        )}
-      </>
-    }
-    headerType="calendarCircle"
-    subject={props.calEvent.attendees[0].language.translate("booking_submitted_subject")}
-    {...props}
-  />
-);
+export const AttendeeRequestEmail = (props: React.ComponentProps<typeof AttendeeScheduledEmail>) => {
+  const date = new AttendeeScheduledEmailClass(props.calEvent, props.attendee).getFormattedDate();
```
Comment (zomars) [inline packages/emails/src/templates/AttendeeRequestEmail.tsx:5]: Very clever. Although it feels kinda hacky

**Review by zomars — APPROVED** [review]
