### PR TITLE
fix: booking rejection message

### LINKED ISSUE #5393: [CAL-324] When rejecting a booking request, it results in a confirmed appointment that requires cancellation
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. When receiving a booking that requires approval, it shows up as normal in upcoming/unconfirmed bookings;
2. When clicking on "reject", it asks for a reason, but then in the lower right corner, it shows "booking confirmation succeeded";
3. In order to fully reject the booking, it must be cancelled

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I expect that when a booking is rejected, that it is not added as a confirmed appointment and the client is not notified of the appointment confirmation.

### Technical details

Video of screen grab is attached to show real-time

[https://user-images.githubusercontent.com/51497445/200126591-11a13dfe-0a8d-48dc-941a-884ca856592b.mov](https://user-images.githubusercontent.com/51497445/200126591-11a13dfe-0a8d-48dc-941a-884ca856592b.mov)

> From [SyncLinear.com](https://synclinear.com)

### PR DESCRIPTION
**Pull request by Udit-takkar**
Fixes: #5393

https://user-images.githubusercontent.com/53316345/201474649-2c340e8d-7a77-4d91-8917-198c4aa84e0e.mov

Booking rejection was working fine but the toast message was incorrect. it displayed booking has been confirmed

### CODE REVIEW

File: packages/trpc/server/routers/viewer/bookings.tsx [hunk 1]
```diff
@@ -985,6 +985,10 @@ export const bookingsRouter = router({
 
       await sendDeclinedEmails(evt);
     }
-    return { message: "Booking " + confirmed ? "confirmed" : "rejected" };
+
+    const message = "Booking " + confirmed ? "confirmed" : "rejected";
+    const status = confirmed ? BookingStatus.ACCEPTED : BookingStatus.REJECTED;
+
+    return { message, status };
```
Comment (Udit-takkar) [inline packages/trpc/server/routers/viewer/bookings.tsx:992]: earlier { message: "Booking " + confirmed ? "confirmed" : "rejected" }
returned only {message : "confirmed" } everytime for some reason. doing concatenation before fixed it

**Review by PeerRich — APPROVED** [review]
