### PR TITLE
fix: Autodetection of time zone only updated default time zone

### LINKED ISSUE #13424: [CAL-3044] Autodetection of time zone only updated default time zone
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Autodetection of time zone only updated default time zone

image

### Steps to Reproduce

1. have 2 timezones
2. fly to mexico
3. login
4. have only the default updated by the auto detect :)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

only updates default one

### Expected Results

update all availabilities

### Technical details

* Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
* Node.js version
* Anything else that you think could be an issue.

### Evidence

* How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3044](https://linear.app/calcom/issue/CAL-3044/autodetection-of-time-zone-only-updated-default-time-zone)</sub>

### PR DESCRIPTION
**Pull request by Amit91848**
## What does this PR do?

- Fixes #13424 
- Fixes CAL-3044 

https://github.com/calcom/cal.com/assets/74371312/adae8d15-cbca-48e6-b8a6-9ef32d1cdbd9

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

### CODE REVIEW

File: packages/features/settings/TimezoneChangeDialog.tsx [hunk 1]
```diff
@@ -104,9 +82,56 @@ export function useOpenTimezoneDialog() {
...
+      <TimezoneChangeDialogContent
+        browserTimezone={browserTimezone}
+        onAction={() => {
+          setOpen(false);
+          setSelectAvailability(true);
+        }}
+      />
+      <BulkEditDefaultModal
+        title={t("default_timezone_bulk_title")}
+        description={t("default_timezone_bulk_description")}
```
Comment (sean-brydon) [inline packages/features/settings/TimezoneChangeDialog.tsx:121]: I think we need to change the copy in the description 

> Update the locations for the selected event types

But we're actually updating availability

**Review by sean-brydon — DISMISSED** [review]
LGTM 

Comment is none blocking - tested works well nice job

File: packages/features/settings/TimezoneChangeDialog.tsx (hunk 1 above)
Comment (Amit91848) [reply packages/features/settings/TimezoneChangeDialog.tsx:121]: Yeah missed that my bad, fixed it.

**Review by sean-brydon — APPROVED** [review]
SHIP IT 🚢

LGTM

**Comment by albertborsos** [comment]
I think this messed up my (and I am sure all other user's) whole Availability.

This overwrote my saved timezone from Europe/Budapest to America/Sao Paulo.

And my booking page shows my whole calendar free so customers booked appointments for midnight instead of afternoon.

**Comment by albertborsos** [comment]
OK, I saved for Europe/Budapest, and now after 10 minutes it is America/Guatemala.

Please rollback to 4.2.3

File: packages/trpc/server/routers/loggedInViewer/updateProfile.handler.ts [hunk 2]
```diff
@@ -257,24 +256,11 @@ export const updateProfileHandler = async ({ ctx, input }: UpdateProfileOptions)
...
-        },
-      });
-    }
-
     await prisma.schedule.updateMany({
       where: {
-        id: defaultScheduleId,
+        id: {
+          in: input.availabilityIds,
+        },
```
Comment (zomars) [inline packages/trpc/server/routers/loggedInViewer/updateProfile.handler.ts:263]: This is a very dangerous change. We don't validate availabilityIds are present since this field is optional. This will trigger an update of ALL schedules. Already affected production.

Comment (zomars) [reply packages/trpc/server/routers/loggedInViewer/updateProfile.handler.ts:263]: cc @keithwillcode @emrysal @sean-brydon

Comment (keithwillcode) [reply packages/trpc/server/routers/loggedInViewer/updateProfile.handler.ts:263]: Have to be honest. This seems like bad default behavior by prisma. Will reach out to them for insights

Comment (Amit91848) [reply packages/trpc/server/routers/loggedInViewer/updateProfile.handler.ts:263]: My mistake 😥😫! Will keep it in mind next time

Comment (keithwillcode) [reply packages/trpc/server/routers/loggedInViewer/updateProfile.handler.ts:263]: Opened https://github.com/calcom/cal.com/pull/15721 to prevent this from happening in the future
