### PR TITLE
fix: align tick icon, text, and cross icon inside toaster

### LINKED ISSUE #21606: Toaster alignment inconsistency
### Issue Summary

The elements inside the toaster are not correctly aligned

### Steps to Reproduce

1. login
2. go to profile
3. go to general
4. toggle dynamic group links

the tickmark icon ,text & cross icon are not correctly aligned

### Actual Results

Image

### Expected Results

- The ideal result should be the correct alignment

### PR DESCRIPTION
**Pull request by faizshaikh17**
## What does this PR do?

Aligns the element inside the toaster

- Fixes #21606 (GitHub issue number)
- Fixes CAL-5873 (Linear issue number)

## Visual Demo (For contributors especially)

Screenshot 2025-05-28 234515

Screenshot 2025-05-29 022256

## Mandatory Tasks (DO NOT REMOVE)

- [X] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [X] N/A
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- login
- go to profile
- go to general
- toggle dynamic group links

## Checklist

- I haven't commented my code, particularly in hard-to-understand areas

    

---

## Summary by cubic
Aligned the tick icon, message text, and cross icon inside toaster notifications for better visual consistency.

### CODE REVIEW

File: packages/ui/components/toast/showToast.tsx [hunk 1]
```diff
@@ -31,16 +33,18 @@ export const SuccessToast = ({ message, onClose, toastId }: IToast) => (
 export const ErrorToast = ({ message, onClose, toastId }: IToast) => (
   <button
     className={classNames(
-      "animate-fade-in-up bg-semantic-error-subtle text-semantic-error shadow-elevation-low border-semantic-error-subtle mb-2 flex h-auto space-x-2 rounded-md border px-3 py-2.5 text-sm font-semibold rtl:space-x-reverse md:max-w-sm"
+      "animate-fade-in-up bg-semantic-error-subtle text-semantic-error shadow-elevation-low border-semantic-error-subtle mb-2 flex h-auto items-center justify-center space-x-2 rounded-md border px-3 py-2.5 text-sm font-semibold rtl:space-x-reverse md:max-w-sm"
```
Comment (TusharBhatt1) [inline packages/ui/components/toast/showToast.tsx:36]: IG just adding `items-center` should have worked

Comment (faizshaikh17) [reply packages/ui/components/toast/showToast.tsx:36]: yeah,in my opinion this make it future proof if dimensions change
(changing center to between)

**Comment by faizshaikh17** [comment]
@TusharBhatt1 can you review this?

**Comment by faizshaikh17** [comment]
@Udit-takkar can you review this?

**Comment by kart1ka** [comment]
@faizshaikh17 We have a test failing. Can you fix it?

**Review by kart1ka — APPROVED** [review]
LGTM

**Review by eunjae-lee — APPROVED** [review]
