### PR TITLE
Fixes bug that new line is not working in workflow reminder emails

### LINKED ISSUE #3424: Line breaks in workflow reminder email not always working
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Line break in workflow reminder email is not always working. 

Works with Mailtrap.io: 
Screenshot 2022-07-18 at 15 00 34

Not working on my Apple Mail: 
Screenshot 2022-07-18 at 15 01 50

### PR DESCRIPTION
**Pull request by CarinaWolli**
## What does this PR do?

Uses HTML template for email to correctly show line breaks in reminder and custom templates. 

Before: 
Screenshot 2022-07-19 at 15 47 33

After: 
Screenshot 2022-07-19 at 15 47 05

Fixes #3424

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: apps/web/ee/lib/workflows/reminders/emailReminderManager.ts [hunk 1]
```diff
@@ -57,11 +56,17 @@ export const scheduleEmailReminder = async (
   const attendeeName = action === WorkflowActions.EMAIL_HOST ? evt.attendees[0].name : evt.organizer.name;
   const timeZone = action === WorkflowActions.EMAIL_HOST ? evt.organizer.timeZone : evt.attendees[0].timeZone;
 
+  let emailContent = {
+    emailSubject,
+    emailBody: {
+      text: emailBody,
+      html: `<body style="white-space: pre-wrap;">${emailBody}</body>`,
```
Comment (CarinaWolli) [inline apps/web/ee/lib/workflows/reminders/emailReminderManager.ts:63]: necessary so line breaks from custom templates work

File: apps/web/ee/lib/workflows/reminders/templates/emailReminderTemplate.ts [hunk 2]
```diff
@@ -7,19 +7,25 @@ const emailReminderTemplate = (
...
 
-  const templateBody = `Hi ${name},\n\nThis is a reminder that your meeting (${eventName}) with ${attendee} is on ${dayjs(
+  const templateBodyText = `Hi ${name},\n\nThis is a reminder that your meeting (${eventName}) with ${attendee} is on ${dayjs(
     startTime
   )
     .tz(timeZone)
     .format("YYYY MMM D")} at ${dayjs(startTime).tz(timeZone).format("h:mmA")} ${timeZone}.`;
 
-  const emailContent = { subject: templateSubject, body: templateBody };
+  const templateBodyHtml = `<body>Hi ${name},<br><br>This is a reminder that your meeting (${eventName}) with ${attendee} is on ${dayjs(
```
Comment (CarinaWolli) [inline apps/web/ee/lib/workflows/reminders/templates/emailReminderTemplate.ts:20]: in html format so line breaks are actually working

**Review by zomars — APPROVED** [review]
