### PR TITLE
fix: Popular Apps Slider

### LINKED ISSUE #9179: [CAL-1812] App Store / Most Popular showing same 3 apps
This should show the top 3-5 apps with the most installs.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1812](https://linear.app/calcom/issue/CAL-1812/app-store-most-popular-showing-same-3-apps)</sub>

### LINKED ISSUE #9185: [CAL-1814] fix "most popular" apps slider
CleanShot 2023-05-29 at 15 58 53@2x

<sub>[CAL-1814](https://linear.app/calcom/issue/CAL-1814/fix-most-popular-apps-slider)</sub>

### PR DESCRIPTION
**Pull request by zomars**
## What does this PR do?

Fixes #9185 

image

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [x] [Check apps in preview deployment](https://cal-git-zomars-cal-1812-app-store-most-popular-showi-85c653-cal.vercel.app/apps)
- [ ] Most popular apps should behave as expected

### CODE REVIEW

File: packages/app-store/_appRegistry.ts [hunk 1]
```diff
@@ -108,10 +113,33 @@ export async function getAppRegistryWithCredentials(userId: number) {
...
+    FROM
+      "Credential" c
+    WHERE
+      c."appId" IS NOT NULL
+    GROUP BY
+      c."appId"
+    ORDER BY
+      "installCount" DESC
+    `
+  );
```
Comment (PeerRich) [inline packages/app-store/_appRegistry.ts:140]: since when do we do that? @zomars

**Review by PeerRich — APPROVED** [review]

File: packages/types/App.d.ts [hunk 2]
```diff
@@ -149,6 +149,8 @@ export type AppFrontendPayload = Omit<App, "key"> & {
     name?: string;
     installed?: boolean;
   }[];
+  /** Number of users who currently have this App installed */
```
Comment (PeerRich) [inline packages/types/App.d.ts:152]: NIT: the variable explains what it is, no? 😆

File: packages/app-store/_appRegistry.ts (hunk 1 above)
Comment (zomars) [reply packages/app-store/_appRegistry.ts:140]: Since prisma doesn't have a more performant way to do it AFAIK.

File: packages/types/App.d.ts (hunk 2 above)
Comment (zomars) [reply packages/types/App.d.ts:152]: It's mostly for Intellisense

image

File: packages/app-store/_appRegistry.ts (hunk 1 above)
Comment (PeerRich) [reply packages/app-store/_appRegistry.ts:140]: is this query fast enough?

Comment (PeerRich) [reply packages/app-store/_appRegistry.ts:140]: i also really dont mind to use that space for "Recently added" and sort by created_by. I am not married to "most popular" if the query is too slow

Comment (zomars) [reply packages/app-store/_appRegistry.ts:140]: It is fast enough

**Comment by keithwillcode** [comment]
@zomars Issue with the production build. Missing env variable DATABASE_URL

**Review by keithwillcode — DISMISSED** [review]
@zomars Issue with the production build. Missing env variable DATABASE_URL

**Comment by zomars** [comment]
> @zomars Issue with the production build. Missing env variable DATABASE_URL

That was a caching issue. We're all green now!
