### PR TITLE
fix: premium-username-callback

### LINKED ISSUE #9932: bug: 500 when redirected back from checkout
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When upgrading to a premium username, I got a 500 after the checkout was finished:

CleanShot 2023-07-04 at 22 54 40@2x

I still got the username though:

CleanShot 2023-07-04 at 23 02 37@2x

The upgrade was a sponsored one though, so not sure if that has something to do with it still going through?

### Steps to Reproduce

1. Go to account page
2. Enter a premium username you want to upgrade to
3. Go to the billing portal
4. Enter the sponsored discount code, and your card details
5. See the screenshot posted above when redirected back to Cal.

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

- Adds full url to stripe callbackUrl

Fixes #9932 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Setup your project constants so your cal.com instance run as a production and not a self host so premium usernames are available
- [ ] Setup website api to be listening
- [ ] Try to update your username to something premium.
- [ ] Do the payment checkout flow
- [ ] Callback url should be working now

## Mandatory Tasks

- [X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: apps/web/components/ui/UsernameAvailability/PremiumTextfield.tsx [hunk 1]
```diff
@@ -116,7 +117,7 @@ const PremiumTextfield = (props: ICustomUsernameProps) => {
 
   const paymentLink = `/api/integrations/stripepayment/subscription?intentUsername=${
     inputUsernameValue || usernameFromStripe
-  }&action=${usernameChangeCondition}&callbackUrl=${router.asPath}`;
+  }&action=${usernameChangeCondition}&callbackUrl=${WEBAPP_URL}${router.asPath}`;
```
Comment (alannnc) [inline apps/web/components/ui/UsernameAvailability/PremiumTextfield.tsx:120]: Recent changes on next broke callbackUrl to be only path adding full url now should solve the issue.

File: packages/trpc/server/routers/loggedInViewer/stripeCustomer.handler.ts [hunk 2]
```diff
@@ -30,12 +30,29 @@ export const stripeCustomerHandler = async ({ ctx }: StripeCustomerOptions) => {
...
+        id: userId,
+      },
+      data: {
+        metadata: {
+          ...metadata,
+          stripeCustomerId: customer.id,
+        },
+      },
+    });
+    stripeCustomerId = customer.id;
```
Comment (alannnc) [inline packages/trpc/server/routers/loggedInViewer/stripeCustomer.handler.ts:52]: Little improvement, in the case user doesn't have stripeCustomerId in user metadata it should create one for him.

File: apps/web/components/ui/UsernameAvailability/UsernameTextfield.tsx [hunk 3]
```diff
@@ -135,7 +135,7 @@ const UsernameTextfield = (props: ICustomUsernameProps & Partial<React.Component
           />
           {currentUsername !== inputUsernameValue && (
             <div className="absolute right-[2px] top-6 flex flex-row">
-              <span className={classNames("mx-2 py-2.5")}>
+              <span className={classNames("mx-2 py-3.5")}>
```
Comment (alannnc) [inline apps/web/components/ui/UsernameAvailability/UsernameTextfield.tsx:138]: Little visual fix

File: apps/web/components/ui/UsernameAvailability/PremiumTextfield.tsx (hunk 1 above)
Comment (alannnc) [reply apps/web/components/ui/UsernameAvailability/PremiumTextfield.tsx:120]: https://nextjs.org/docs/pages/api-reference/functions/use-router#router-object

File: packages/trpc/server/routers/loggedInViewer/stripeCustomer.handler.ts (hunk 2 above)
Comment (emrysal) [reply packages/trpc/server/routers/loggedInViewer/stripeCustomer.handler.ts:52]: In what situation would this happen?

File: apps/web/components/ui/UsernameAvailability/PremiumTextfield.tsx (hunk 1 above)
Comment (emrysal) [reply apps/web/components/ui/UsernameAvailability/PremiumTextfield.tsx:120]: How did you decide to implement within the frontend instead of backend?

Comment (alannnc) [reply apps/web/components/ui/UsernameAvailability/PremiumTextfield.tsx:120]: To be fair I don't remember but having url on server will mean that it can only handle one url, instead of having the UI component in different places and they should be on charge of their url to return, this means if component gets moved around places it will be itself in charge of having to provide return url.

File: packages/trpc/server/routers/loggedInViewer/stripeCustomer.handler.ts (hunk 2 above)
Comment (alannnc) [reply packages/trpc/server/routers/loggedInViewer/stripeCustomer.handler.ts:52]: - An error during signup
- Not sure if getting invited would create you stripe customer id

**Review by emrysal — APPROVED** [review]
