### PR TITLE
fix: visiting organization without access shows empty page

### LINKED ISSUE #15061: [CAL-3715] visiting "Organization" pages without access shows empty page
if you are not in an organisation and you visit a link like: [https://app.cal.com/settings/organizations/members](https://app.cal.com/settings/organizations/members)

you will see an empty page:

image

instead we should link to [https://app.cal.com/enterprise](https://app.cal.com/enterprise)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3715](https://linear.app/calcom/issue/CAL-3715/visiting-organization-pages-without-access-shows-empty-page)</sub>

### PR DESCRIPTION
**Pull request by Shaik-Sirajuddin**
## What does this PR do?

- Fixes #15061  (GitHub issue number)
- Fixes CAL-3715 (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

- Login into an account not enrolled in an organization
- Visit [settings/organizations/members](https://app.cal.com/settings/organizations/members) page
- User will be redirected to /enterprise page

### CODE REVIEW

File: packages/features/ee/organizations/pages/settings/members.tsx [hunk 1]
```diff
@@ -19,6 +23,15 @@ const MembersView = () => {
   const canLoggedInUserSeeMembers =
     (currentOrg?.isPrivate && isOrgAdminOrOwner) || isOrgAdminOrOwner || !currentOrg?.isPrivate;
 
+  useEffect(
+    function refactorMeWithoutEffect() {
```
Comment (hariombalhara) [inline packages/features/ee/organizations/pages/settings/members.tsx:27]: I know we have this pattern already somewhere in app but can we not simply remove this effect and have the same behaviour ?

Even when the component re-renders before the navigation completes, it is still asking us to go to the same page and thus it is `idempotent` in nature.

**Review by hariombalhara — DISMISSED** [review]
@Shaik-Sirajuddin Thank you for the PR 🙏

I have left a suggestion for code improvement, please see if it makes sense.

**Comment by Shaik-Sirajuddin** [comment]
> @Shaik-Sirajuddin Thank you for the PR 🙏
> 
> I have left a suggestion for code improvement, please see if it makes sense.

Added ServerSideProps to redirect user before page load , 
this makes redirection slightly faster and eliminates use of effect user side
PTAL @hariombalhara

**Review by Amit91848 — CHANGES_REQUESTED** [review]
Can you add it to other pages too @Shaik-Sirajuddin ?

**Comment by Shaik-Sirajuddin** [comment]
> Can you add it to other pages too @Shaik-Sirajuddin ?

As I checked , redirection using useEffect is available in around 9 pages , 
I think it will be blocking the current objective of this pr , i am open to handling this via a seperate PR as this is out of scope for the issue

**Review by Amit91848 — DISMISSED** [review]
We can add it to org pages, remaining can be done in a follow up pr. Also e2e is consistently failing, please have a look @Shaik-Sirajuddin

File: packages/features/ee/organizations/pages/settings/getServerSidePropsMembers.tsx [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+  });
+
+  if (!membership) {
+    return {
+      redirect: {
+        permanent: false,
+        destination: "/enterprise",
+      },
+    };
+  }
```
Comment (hariombalhara) [inline packages/features/ee/organizations/pages/settings/getServerSidePropsMembers.tsx:52]: I don't think it is needed. session.user.org.id having being there should confirm membership with the organiztion
```suggestion
```

**Review by hariombalhara — DISMISSED** [review]

**Review by Amit91848 — APPROVED** [review]

**Comment by Amit91848** [comment]
This broke a bunch of e2e for orgs, I am working on fixing it

**Comment by hariombalhara** [comment]
> This broke a bunch of e2e for orgs, I am working on fixing it

Wow, seriously !! Thanks @Amit91848. Curious to see what was the issue.

**Review by Amit91848 — CHANGES_REQUESTED** [review]
Broke e2e for a bunch of orgs. Working on it

File: packages/features/ee/organizations/pages/settings/getServerSidePropsMembers.tsx [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+  if (!session || !session.user) {
+    return {
+      redirect: {
+        permanent: false,
+        destination: "/auth/login",
+      },
+    };
+  }
+
+  if (!session.user.org?.id) {
```
Comment (Amit91848) [inline packages/features/ee/organizations/pages/settings/getServerSidePropsMembers.tsx:24]: https://github.com/calcom/cal.com/blob/8a972a74c67bb11d3833a733e054aa0e182cddcf/packages/features/auth/lib/getServerSession.ts#L38-L40

When we decode token here, token.org is undefined for users with organization, but only when doing it via e2e, works fine normally.

Couldn't really figure out why till now, it is kinda confusing. As a work around we can use profile.organizationId instead of org?.id which I checked is working for both e2e and webapp. @hariombalhara . Will keep digging till then 🤔

```suggestion
  if (!session.user.profile?.organizationId) {
```

Comment (Amit91848) [reply packages/features/ee/organizations/pages/settings/getServerSidePropsMembers.tsx:24]: Update:

https://github.com/calcom/cal.com/blob/d84f08c998623f0fbb5975a684a8830327294260/packages/features/auth/lib/next-auth-options.ts#L229-L238

My best guess is when doing .apiLogin, CredentialsProvider block is what runs where we are never adding org. 

https://github.com/calcom/cal.com/blob/d84f08c998623f0fbb5975a684a8830327294260/packages/features/auth/lib/next-auth-options.ts#L555-L574 . So user.org is always undefined when running e2e

Comment (Amit91848) [reply packages/features/ee/organizations/pages/settings/getServerSidePropsMembers.tsx:24]: Ig if we want to fix the core issue, we can call `autoMergeIdentites`

https://github.com/calcom/cal.com/blob/d84f08c998623f0fbb5975a684a8830327294260/packages/features/auth/lib/next-auth-options.ts#L469
 

for account.type === "credentials" as well


https://github.com/calcom/cal.com/blob/d84f08c998623f0fbb5975a684a8830327294260/packages/features/auth/lib/next-auth-options.ts#L560-L574

Honestly I am not completely sure what any of these do so I will leave it up to you @hariombalhara

**Review by Amit91848 — APPROVED** [review]

**Review by hariombalhara — APPROVED** [review]

File: packages/features/ee/organizations/pages/settings/getServerSidePropsMembers.tsx (hunk 3 above)
Comment (hariombalhara) [reply packages/features/ee/organizations/pages/settings/getServerSidePropsMembers.tsx]: If it's a testcase thing only it is better to just use what works for now. I am good with the changes.
