### PR TITLE
fix: Close.com can't be installed

### LINKED ISSUE #16183: [CAL-3969] Close.com can't be installed
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3969](https://linear.app/calcom/issue/CAL-3969/closecom-cant-be-installed)</sub>

### PR DESCRIPTION
**Pull request by Flash-Shivam**
## What does this PR do?

Fixes the below issues

- Fixes #16183 (GitHub issue number)
- Fixes [CAL-3969] (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?
Tested locally 

https://www.loom.com/share/9b7f1f23af604cc594476a6bb07fd84c?sid=aa62fa96-f27d-4281-9488-7d3fc287f788

### CODE REVIEW

File: packages/app-store/closecom/pages/setup/index.tsx [hunk 1]
```diff
@@ -66,7 +66,8 @@ export default function CloseComSetup() {
                 form={form}
                 handleSubmit={async (values) => {
                   const { returnTo } = query;
-                  const url = new URL("/api/integrations/closecom/add");
+                  const baseUrl = window.location.origin;
+                  const url = new URL("/api/integrations/closecom/add", baseUrl);
```
Comment (anikdhabal) [inline packages/app-store/closecom/pages/setup/index.tsx:70]: Hey, we have introduced a class called WebAppURL. Can you use it instead of window.location.origin?

**Review by anikdhabal — CHANGES_REQUESTED** [review]

File: packages/app-store/closecom/pages/setup/index.tsx (hunk 1 above)
Comment (Flash-Shivam) [reply packages/app-store/closecom/pages/setup/index.tsx:70]: Is there an issue with `window.location.origin` technically speaking ?

Comment (anikdhabal) [reply packages/app-store/closecom/pages/setup/index.tsx:70]: No issue, but when we provide the same here, why use the window object?

**Review by anikdhabal — APPROVED** [review]
LGTM!!

File: packages/app-store/closecom/pages/setup/index.tsx (hunk 1 above)
Comment (anikdhabal) [reply packages/app-store/closecom/pages/setup/index.tsx]: No issue, we provide the similar thing.
