### PR TITLE
Fix dynamic bookings overwriting users

### LINKED ISSUE #7648: Success page of a group booking is not correctly displaying attendees
Found a bug? Please fill out the sections below. 👍

I made a group booking and it only showed my information and the host's information was duplicated.

34454665462_image2048

### PR DESCRIPTION
**Pull request by joeauyeung**
## What does this PR do?

This PR moves some logic in `handleNewBooking` that caused some users to be overwritten.

Fixes #7648

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Create a dynamic booking with "free+pro"
- Both users should be saved in the booking

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 1]
```diff
@@ -668,20 +682,6 @@ async function handler(
...
   const uid = translator.fromUUID(uuidv5(seed, uuidv5.URL));
 
-  let locationBodyString = location;
-  let defaultLocationUrl = undefined;
-  if (dynamicUserList.length > 1) {
-    users = users.sort((a, b) => {
-      const aIndex = (a.username && dynamicUserList.indexOf(a.username)) || 0;
-      const bIndex = (b.username && dynamicUserList.indexOf(b.username)) || 0;
-      return aIndex - bIndex;
-    });
```
Comment (joeauyeung) [inline packages/features/bookings/lib/handleNewBooking.ts:678]: On line 639, we assigned the first entry in the `users` array as the organizer. Here we rearrange the `users` array so there's no guarantee that the first entry in the array will stay the same. I moved these lines of code earlier in the function so when we assign the organizer, the `users` array will not change anymore.

**Review by zomars — APPROVED** [review]
