### PR TITLE
fix: No option to install/disconnect app from app detail page

### LINKED ISSUE #14307: inconsistency with the disconnect app button
Found a bug? Please fill out the sections below. 👍

### Issue Summary

**issue 1** - Despite installing the app on all available teams and your personal account, the "install" button persists on the appCard, while the app detail page shows the "disconnect" option.

**issue 2** - the disconnect app only removes the app from my personal account, there is no way to remove the app from a team.
It should ideally provide the option to select the account or team, similar to the installation process.

### Evidence

[LOOM](https://www.loom.com/share/c9be89a08ee34d47bfd327998bc61426?sid=d22335a6-66a8-4d86-bbba-a46f67b905ad)

### PR DESCRIPTION
**Pull request by asadath1395**
## What does this PR do?

No option to install/disconnect app from app detail page

- Partially Fixes #14307 

It fixes only the issue-2 mentioned in the linked ticket -- Hariom

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?
[https://www.loom.com/share/49e1050b7e1e42e9af6e669b953b4118?sid=0807e556-61a0-4faa-99ea-d4ce9795b8a0](https://www.loom.com/share/49e1050b7e1e42e9af6e669b953b4118?sid=0807e556-61a0-4faa-99ea-d4ce9795b8a0)

### CODE REVIEW

**Comment by asadath1395** [comment]
@keithwillcode Can you please assign someone to review this? Thanks

**Comment by asadath1395** [comment]
@emrysal If you have the bandwidth, could you please review this PR? Thanks

File: apps/web/components/apps/AppPage.tsx [hunk 1]
```diff
@@ -98,6 +99,11 @@ export const AppPage = ({
    * which is caused by heavy queries in getServersideProps. This causes the loader to turn off before the page changes.
    */
   const [isLoading, setIsLoading] = useState<boolean>(mutation.isPending);
+  const enabledOnTeams = doesAppSupportTeamInstall({
```
Comment (hariombalhara) [inline apps/web/components/apps/AppPage.tsx:102]: nit: `enabledOnTeams` make it sound like user has it enabled.
```suggestion
  const availableForTeams = doesAppSupportTeamInstall({
```

File: apps/web/components/apps/AppPage.tsx [hunk 2]
```diff
@@ -142,10 +144,13 @@ export const AppPage = ({
...
-      setShowDisconnectIntegration(
-        data?.userAdminTeams.length ? credentialsCount >= data?.userAdminTeams.length : credentialsCount > 0
-      );
-      setExistingCredentials(data?.credentials.map((credential) => credential.id) || []);
+      setExistingCredentials(data?.credentials || []);
+
+      const appInstalled =
+        enabledOnTeams && data?.userAdminTeams
+          ? data?.userAdminTeams.length < credentialsCount
+          : credentialsCount > 0;
```
Comment (hariombalhara) [inline apps/web/components/apps/AppPage.tsx:152]: This conditional seems to be the same logic as earlier except for an additional check. I think we shouldn't change the approach unnecessarily here, makes it difficult to review code

File: apps/web/components/apps/AppPage.tsx [hunk 3]
```diff
@@ -168,6 +173,91 @@ export const AppPage = ({
...
+                onSuccess={() => appDbQuery.refetch()}
+              />
+            ) : (
+              <DisconnectIntegration
+                buttonProps={{ color: "secondary" }}
+                label={t("disconnect")}
+                credentialId={Number(existingCredentials[0].id)}
+                teamId={existingCredentials[0].teamId}
+                onSuccess={() => appDbQuery.refetch()}
+              />
```
Comment (hariombalhara) [inline apps/web/components/apps/AppPage.tsx:253]: I think we could make `MultiDisconnectIntegration` a wrapper over `DisconnectIntegration` so that it can handle single as well multiple disconnects. It keeps the consumer logic simple

File: apps/web/components/apps/AppPage.tsx (hunk 2 above)
Comment (hariombalhara) [reply apps/web/components/apps/AppPage.tsx:152]: Infact it is missing the equal case. So, if the app is installed for all teams then `data?.userAdminTeams.length == credentialsCount` is true and in that case app, still shows Install button.

Comment (hariombalhara) [reply apps/web/components/apps/AppPage.tsx:152]: Fixed it.

File: apps/web/components/apps/AppPage.tsx [hunk 4]
```diff
@@ -142,10 +144,13 @@ export const AppPage = ({
...
-      setExistingCredentials(data?.credentials.map((credential) => credential.id) || []);
+      setExistingCredentials(data?.credentials || []);
+
+      const appInstalled =
+        enabledOnTeams && data?.userAdminTeams
+          ? data?.userAdminTeams.length < credentialsCount
+          : credentialsCount > 0;
+      setAppInstalled(appInstalled);
     },
     [appDbQuery.data]
```
Comment (hariombalhara) [inline apps/web/components/apps/AppPage.tsx:159]: We haven't added `enabledOnTeams` in the useEffect deps

File: apps/web/components/apps/AppPage.tsx [hunk 5]
```diff
@@ -168,6 +177,89 @@ export const AppPage = ({
...
+                  ? t("active_install", { count: existingCredentials.length })
+                  : t("default")}
+              </Button>
+              {!isGlobal && !appInstalledForAllTargets && MultiInstallButtonEl}
+            </div>
+          ) : (
+            !appInstalledForAllTargets && SingleInstallButtonEl
+          ))}
+
+        {existingCredentials.length > 0 && (
```
Comment (hariombalhara) [inline apps/web/components/apps/AppPage.tsx:241]: Made this logic a bit easier to understand by moving the JSX to variables above

**Review by hariombalhara — DISMISSED** [review]
LGTM now !! Great work @asadath1395 !!

Feel free to open other PR for any pending suggestions I have added.

File: apps/web/components/apps/AppPage.tsx (hunk 4 above)
Comment (hariombalhara) [reply apps/web/components/apps/AppPage.tsx]: Done

**Comment by asadath1395** [comment]
@PeerRich @anikdhabal I think auto-merge is broken. Can we get this merged today? All i see is everyone trying to run the pipeline and forgetting to come back 😄

**Comment by asadath1395** [comment]
@PeerRich Can we get this merged?

**Comment by retrogtx** [comment]
> @PeerRich Can we get this merged?

hey the E2E tests are failing on this

**Comment by TusharBhatt1** [comment]
@asadath1395 are you still working on this , tests are failing

**Comment by retrogtx** [comment]
> @asadath1395 are you still working on this , tests are failing

it's the E2E failure I think, Anik is working on this made a PR for the same yesterday

**Review by anikdhabal — APPROVED** [review]
Looks Good
