### PR TITLE
fix: metadata not saved while creating a booking.

### LINKED ISSUE #6808: [CAL-984] Metadata is ignored when you create a booking.
### Issue Summary

Metadata is ignored when you create a booking.

### Steps to Reproduce

1. Add metadata to query parameters of the event link, e.g. `http://localhost:3000/john-foo-zrurxq/30min?metadata[user_id]=123`
2. Open the link in the browser;
3. Book a meeting.
4. Call the `GET v1/bookings` endpoint and find created booking.

Expected: To see created booking with `metadata` provided in query params.
Actual: `metadata` is null.

<sub>[CAL-984](https://linear.app/calcom/issue/CAL-984/metadata-is-ignored-when-you-create-a-booking)</sub>

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

Fixes #6808 

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by CarinaWolli — CHANGES_REQUESTED** [review]
It's not working if the location is a video conferencing app. It then only shows the `videoCallUrl` in `metadata`. 

It's overwritten here, I believe:
Screenshot 2023-02-03 at 10 02 39

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 1]
```diff
@@ -1141,7 +1141,7 @@ async function handler(req: NextApiRequest & { userId?: number | undefined }) {
         uid: booking.uid,
       },
       data: {
-        metadata,
+        metadata: { ...(typeof booking.metadata === "object" && booking.metadata), ...metadata },
```
Comment (G3root) [inline packages/features/bookings/lib/handleNewBooking.ts:1144]: workaround for typescript complaining that only objects can be spreaded

**Comment by G3root** [comment]
@CarinaWolli pushed some changes

**Review by CarinaWolli — APPROVED** [review]
Works now, thank you 🙏

**Review by zomars — APPROVED** [review]
LGTM
