### PR TITLE
fix: color tokens are not used in payment form

### LINKED ISSUE #10796: [CAL-2359] color tokens are not used in payment form
### Steps to Reproduce

1. Install Stripe and create a paid booking
2. Book a time slot
   \]

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2359](https://linear.app/calcom/issue/CAL-2359/color-tokens-are-not-used-in-payment-form)</sub>

### PR DESCRIPTION
**Pull request by ghost**
## What does this PR do?

Fixes #10796

Fixes irregular payment form input

Note: Payment page is always set to light theme regardless of browser's theme.

Before: 
68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f65383662663935372d643832662d343635652d623230352d3133353535396634623632332f38353134306334612d663339632d343038642d613863322d3833383832363739353931662f303337323461

After: 
Screenshot 2023-08-16 210145

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Book a paid event
- Go to payment page

## Mandatory Tasks

- [X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: packages/features/ee/payments/components/Payment.tsx [hunk 1]
```diff
@@ -162,18 +162,13 @@ const ELEMENT_STYLES_DARK: stripejs.Appearance = {
...
-  useEffect(() => {
-    setDarkMode(window.matchMedia("(prefers-color-scheme: dark)").matches);
-  }, []);
 
   return (
     <Elements
       stripe={stripePromise}
       options={{
         clientSecret: props.clientSecret,
-        appearance: darkMode ? ELEMENT_STYLES_DARK : ELEMENT_STYLES,
```
Comment (Udit-takkar) [inline packages/features/ee/payments/components/Payment.tsx:176]: we shouldn't have same styles on dark mode and light mode

**Review by Udit-takkar — COMMENTED** [review]
@vineetpradhanvp we need to get the correct current theme and use styles according to that

**Review by Udit-takkar — APPROVED** [review]
LGTM. I pushed some changs

**Comment by vineetpradhanvp** [comment]
> @vineetpradhanvp we need to get the correct current theme and use styles according to that

In dev env, I tried with dark mode and light mode. I never got dark theme stripe page. And I've also found some irregularities on user's page theme i.e. It is not following the same theme as browser's theme.Is there any env variable I have to address?
