### PR TITLE
fix: bad request in webhook route

### LINKED ISSUE #13007: [CAL-2857] Bad request on webhooks
there were some bad requests in webhooks logs in daily video

image

It's because of "max_participants" property is not sent in the request payload by daily video which used to be present before.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2857](https://linear.app/calcom/issue/CAL-2857/bad-request-on-webhooks)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
Fixes: https://github.com/calcom/cal.com/issues/13007

Made some keys optional that are not being used

### CODE REVIEW

File: apps/web/pages/api/recorded-daily-video.ts [hunk 1]
```diff
@@ -21,16 +21,16 @@ const schema = z
...
     payload: z.object({
       recording_id: z.string(),
-      end_ts: z.number(),
+      end_ts: z.number().optional(),
       room_name: z.string(),
-      start_ts: z.number(),
+      start_ts: z.number().optional(),
       status: z.string(),
 
-      max_participants: z.number(),
```
Comment (Udit-takkar) [inline apps/web/pages/api/recorded-daily-video.ts:29]: earlier "max_participants" was also present in the request payload but not now.

**Review by emrysal — APPROVED** [review]
👍
