### PR TITLE
fix: reduce cal recording bitrate

### LINKED ISSUE #15494: [CAL-3949] Reduce cal video recording bitrate
### Is your proposal related to a problem?

Reduce recording bitrate to reduce size of the file

requested by [https://calcominc.slack.com/archives/C06UTF7QLU9/p1718728247345149](https://calcominc.slack.com/archives/C06UTF7QLU9/p1718728247345149)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3949](https://linear.app/calcom/issue/CAL-3949/reduce-cal-video-recording-bitrate)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

- Fixes https://github.com/calcom/cal.com/issues/15494
- Fixes CAL-3949 (Linear issue number - should be visible at the bottom of the GitHub issue description)

Slack thread about implementation https://calcominc.slack.com/archives/C02EQ5KP630/p1718760508623649?thread_ts=1718307301.750959&cid=C02EQ5KP630

Screenshot 2024-06-27 at 6 30 10 PM

TODO:-

- [x] Currently it takes some seconds to start recording so we need to add some modal/indicator that recording is starting

AFTER(21s, 480p, 500KB) VS BEFORE(26s, 1080p, 15MB)

Screenshot 2024-06-26 at 11 13 40 PM

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [x] N/A I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

File: packages/lib/constants.ts [hunk 1]
```diff
@@ -165,3 +165,11 @@ export const TRANSCRIPTION_STARTED_ICON = IS_PRODUCTION
 export const TRANSCRIPTION_STOPPED_ICON = IS_PRODUCTION
   ? `${WEBAPP_URL}/sparkles.svg`
   : `https://app.cal.com/sparkles.svg`;
+
+export const RECORDING_DEFAULT_ICON = IS_PRODUCTION
```
Comment (Udit-takkar) [inline packages/lib/constants.ts:169]: Daily requires icon to be in https format so this won't be visible right now locally.

File: packages/app-store/dailyvideo/lib/types.ts [hunk 2]
```diff
@@ -0,0 +1,66 @@
+import { z } from "zod";
+
+/** @link https://docs.daily.co/reference/rest-api/rooms/create-room */
+export const dailyReturnTypeSchema = z.object({
```
Comment (Udit-takkar) [inline packages/app-store/dailyvideo/lib/types.ts:4]: just moved zod schemas to this file

File: packages/app-store/dailyvideo/lib/VideoApiAdapter.ts [hunk 3]
```diff
@@ -159,7 +124,12 @@ const DailyVideoApiAdapter = (): VideoApiAdapter => {
     const body = await translateEvent(event);
     const dailyEvent = await postToDailyAPI(endpoint, body).then(dailyReturnTypeSchema.parse);
     const meetingToken = await postToDailyAPI("/meeting-tokens", {
-      properties: { room_name: dailyEvent.name, exp: dailyEvent.config.exp, is_owner: true },
+      properties: {
+        room_name: dailyEvent.name,
+        exp: dailyEvent.config.exp,
+        is_owner: true,
+        enable_recording_ui: false,
```
Comment (Udit-takkar) [inline packages/app-store/dailyvideo/lib/VideoApiAdapter.ts:131]: set enable_recording_ui: false to hide default recording button because we want are using customTrayButtons

File: apps/web/modules/videos/views/videos-single-view.getServerSideProps.tsx [hunk 4]
```diff
@@ -103,12 +104,18 @@ export async function getServerSideProps(context: GetServerSidePropsContext) {
 
   const session = await getServerSession({ req });
 
-  // set meetingPassword to null for guests
+  // set meetingPassword for guests
   if (session?.user.id !== bookingObj.user?.id) {
+    const videoReference = getCalVideoReference(bookingObj.references);
+    const guestMeetingPassword = await generateGuestMeetingTokenFromOwnerMeetingToken(
+      videoReference.meetingPassword
+    );
```
Comment (Udit-takkar) [inline apps/web/modules/videos/views/videos-single-view.getServerSideProps.tsx:112]: This is required because we want a meeting token with `enable_recording_ui: false` so that default recording button doesn't show up

**Review by joeauyeung — APPROVED** [review]
