### PR TITLE
Fix/unpaid unconfirmed

### LINKED ISSUE #2170: Unpaid/Unconfirmed bookings should not block availability
### Issue Summary

Found out that unconfirmed/unpaid bookings are blocking availability when they should only do if they're confirmed/paid.

### Steps to Reproduce

1. Connect a Stripe account
2. Create a priced event type
3. Remove Stripe account (so we can trigger an error)
4. Try to book paid event type
5. You'll get this error `ERROR [api] book:user Creating payment failed`
6. Try to book again, you'll get this error:
    ```sh
    10:34:57.582 timeZoneName DEBUG [api] book:user Booking Pro Example failed
    {
      errorCode: 'BookingUserUnAvailable',
      message: 'Pro Example is unavailable at this time.'
    }
    ```
7. Go to `/bookings` you'll se and unconfirmed/unpaid booking

### PR DESCRIPTION
**Pull request by andreaestefania12**
## What does this PR do?

- Fixed bug when you trying to book an event with payment, this event was booked and saved in google calendar even if it showed an error. So if you want to book an event with payment, it will show an error and the reservation will not be reserved and will not take availability.

- Fixed bug when you have unpaid or unconfirmed events bookings that need payment and you disconnect the payment method in installed apps, all those bookings are going to be canceled automatically.

Fixes #2170 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

Test for the first bug.
1. Go to apps/installed.
2. Connect a Stripe account.
3. Create a priced event type.
4. Remove Stripe account.
5. Try to book paid event type.

Test for the second bug.
1. Go to bookings/upcoming and see the unpaid or unconfirmed bookings.
2. Go to apps/installed and disconnect Stripe account.
3. Go to bookings/canceled and you are going to see all unpaid and unconfirmed bookings.

### CODE REVIEW

File: apps/web/pages/api/book/confirm.ts [hunk 1]
```diff
@@ -115,6 +116,21 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
       return res.status(400).json({ message: "booking already confirmed" });
     }
 
+    /** If we are confirming a booking that need pay and does not have payment,
+     * it would not have to save in destination calendar */
```
Comment (alannnc) [inline apps/web/pages/api/book/confirm.ts:120]: Probably a better wording could be:
`When a booking that requires payment its being confirmed but doesn't have any payment, we shouldn’t save it on DestinationCalendars`

File: apps/web/pages/api/book/event.ts [hunk 2]
```diff
@@ -508,7 +508,27 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
       }
     }
 
-    return prisma.booking.create(createBookingObj);
+    /*Validate if there is any stripe_payment credential for this user*/
```
Comment (alannnc) [inline apps/web/pages/api/book/event.ts:511]: `/* Validate if there is any stripe_payment credential for this user */`
Missing spaces after, before comment code

File: apps/web/pages/api/book/event.ts [hunk 3]
```diff
@@ -508,7 +508,27 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
...
+    const eventTypePayment = await prisma.credential.findFirst({
```
Comment (alannnc) [inline apps/web/pages/api/book/event.ts:512]: rename `eventTypePayment` to `stripePaymentCredential`

File: apps/web/pages/api/book/event.ts [hunk 4]
```diff
@@ -508,7 +508,27 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
...
+        userId: users[0].id,
+      },
+      select: {
+        id: true,
+      },
+    });
+    /** If the stripe_payment credential exists then it creates the booking OR*/
+    /** If the stripe_payment credential does not exist but the eventTypes is
+     *   without payment then create the booking
+     */
```
Comment (alannnc) [inline apps/web/pages/api/book/event.ts:524]: Use same comment code for all the comment
```suggestion
     /** eventType doesn’t require payment then we create a booking
     * OR
     * stripePaymentCredential is found and price is higher than 0 then we create a booking
     */
```

File: apps/web/pages/api/book/event.ts [hunk 5]
```diff
@@ -508,7 +508,27 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
...
+    if ((eventTypePayment && eventType.price > 0) || !eventType.price) {
```
Comment (alannnc) [inline apps/web/pages/api/book/event.ts:525]: Changing the order on this or conditional can make our if conditional run faster I think as evenType.price validates to true faster than the left sentence that requires 2 conditionals.
```suggestion
    if (!eventType.price || (stripePaymentCredential && evenType.price > 0)) {
```

File: apps/web/pages/api/book/event.ts [hunk 6]
```diff
@@ -508,7 +508,27 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
...
+      return prisma.booking.create(createBookingObj);
+    }
+    /** If the stripe_payment credential does not exist and the eventTypes is
```
Comment (alannnc) [inline apps/web/pages/api/book/event.ts:528]: single line comment its enough here
```suggestion
// stripePaymentCredential not found and eventType requires payment we return null
```

File: apps/web/pages/api/book/event.ts [hunk 7]
```diff
@@ -623,7 +646,7 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
   let booking: Booking | null = null;
   try {
     booking = await createBooking();
-    evt.uid = booking.uid;
+    evt.uid = booking?.uid ?? null;
```
Comment (alannnc) [inline apps/web/pages/api/book/event.ts:649]: I got a doubt with this, in which scenarios our `evt.uid` can be `null`?

File: apps/web/pages/api/book/event.ts [hunk 8]
```diff
@@ -712,7 +735,12 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
     await sendAttendeeRequestEmail(evt, attendeesList[0]);
   }
 
-  if (typeof eventType.price === "number" && eventType.price > 0 && !originalRescheduledBooking?.paid) {
+  if (
+    typeof eventType.price === "number" &&
```
Comment (alannnc) [inline apps/web/pages/api/book/event.ts:739]:
```suggestion
!Number.isNaN(eventType.price)
```
Method documentation
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN

File: apps/web/pages/api/book/event.ts [hunk 9]
```diff
@@ -712,7 +735,12 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
...
+    eventType.price > 0 &&
+    !originalRescheduledBooking?.paid &&
+    booking
```
Comment (alannnc) [inline apps/web/pages/api/book/event.ts:742]:
```suggestion
    !!booking
```

File: apps/web/pages/api/integrations.ts [hunk 10]
```diff
@@ -30,7 +30,17 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
   }
 
   if (req.method == "DELETE") {
-    const id = req.body.id;
+    /** Get the id from the stripe_payment credential for this user */
+    const paymentCredential = await prisma.credential.findFirst({
```
Comment (alannnc) [inline apps/web/pages/api/integrations.ts:34]: `const stripePaymentCredential` as above

Comment (alannnc) [reply apps/web/pages/api/integrations.ts:34]: Also we can move this code below where paymentCredential its being used on line 44

File: apps/web/pages/api/integrations.ts [hunk 11]
```diff
@@ -30,7 +30,17 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
...
+      where: {
+        userId: session?.user?.id,
+        type: "stripe_payment",
+      },
+      select: {
+        id: true,
+      },
+    });
```
Comment (alannnc) [inline apps/web/pages/api/integrations.ts:42]: As we already have credentialId we can use findFirst with where: { id: req.body.id }
```suggestion
    /** Get the id from the stripe_payment credential for this user */
    const stripePaymentCredential = await prisma.credential.findFirst({
      where: {
        id: req.body.id,
        userId: session?.user?.id,
        type: "stripe_payment",
      },
      select: {
        id: true,
      },
    });
```

File: apps/web/pages/api/integrations.ts [hunk 12]
```diff
@@ -30,7 +30,17 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
...
+    const credentialToDeleteId = req.body.id;
```
Comment (alannnc) [inline apps/web/pages/api/integrations.ts:43]: Move this to top of function on line 33

File: apps/web/pages/api/integrations.ts [hunk 13]
```diff
@@ -39,12 +49,84 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
...
+            id: credentialToDeleteId,
           },
         },
       },
     });
 
+    /** This validates if you disconnect the Stripe credential.
+    When you disconnect this credential, you have to delete the information from payment 
+    and then update the booking status to Rejected, this is just for those booking that are unconfirmed and 
+    unpaid*/
```
Comment (alannnc) [inline apps/web/pages/api/integrations.ts:61]: NIT suggestion:
```suggestion
    /** If stripePaymentCredential was deleted successfully we need to delete the information from payment 
    * and then update all the user's bookings that where unconfirmed and unpaid to a status = "rejected"
    */
```

File: apps/web/pages/api/integrations.ts [hunk 14]
```diff
@@ -39,12 +49,84 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
...
+    if (paymentCredential?.id === credentialToDeleteId) {
+      try {
+        const bookingWithPaymentIds = await prisma.booking
```
Comment (alannnc) [inline apps/web/pages/api/integrations.ts:64]: NIT: `const bookingIdsWithPayments = `

File: apps/web/pages/api/integrations.ts [hunk 15]
```diff
@@ -39,12 +49,84 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
...
+
+        const updateBookings = prisma.booking.updateMany({
+          where: {
+            id: {
+              in: bookingWithPaymentIds,
+            },
+          },
+          data: {
+            rejected: true,
+            status: "REJECTED",
```
Comment (alannnc) [inline apps/web/pages/api/integrations.ts:99]: I think Rejected means the owner has explicitly rejected to meet with someone else, on this case it can be Cancelled and use cancellationReason = "Payment provider got removed".
Probably we need to revise what we wanna do here with bookings that had payment option but provider got removed.
I would suggest we tell the user what is gonna happen when disconnecting from stripe and has some events that rely on it, whether it's cancelling them or just remove they payment required fields.
cc @zomars

**Review by alannnc — DISMISSED** [review]
Good code! I tested it and it works, just some NIT changes. But I think we need to revise what happens with pending bookings that had payment option.

- Convert them to no payment required
- Cancel them

File: apps/web/pages/api/integrations.ts (hunk 15 above)
Comment (zomars) [reply apps/web/pages/api/integrations.ts:99]: Agreed

Comment (zomars) [reply apps/web/pages/api/integrations.ts:99]: Agreed

**Review by zomars — CHANGES_REQUESTED** [review]
Let's address @alannnc comments first

File: apps/web/pages/api/book/confirm.ts [hunk 16]
```diff
@@ -115,6 +116,21 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
       return res.status(400).json({ message: "booking already confirmed" });
     }
 
+    /** When a booking that requires payment its being confirmed but doesn't have any payment, 
+     * we shouldn’t save it on DestinationCalendars*/
```
Comment (alannnc) [inline apps/web/pages/api/book/confirm.ts:120]:
```suggestion
     * we shouldn’t save it on DestinationCalendars
     */
```

File: apps/web/pages/api/book/event.ts (hunk 7 above)
Comment (alannnc) [reply apps/web/pages/api/book/event.ts:647]: @andreaestefania12  Do you happen to know when this happens? I wanna know a little more on this context

**Review by alannnc — COMMENTED** [review]
It looks like prettier it's not working for you?
try to run `yarn lint --fix` maybe

File: apps/web/pages/api/book/event.ts (hunk 7 above)
Comment (andreaestefania12) [reply apps/web/pages/api/book/event.ts:647]: Hi @alannnc, in case the function createBooking returns null, the booking.uid is going to be undefined but inside the interface CalendarEvent uid specifies that it should be a string or null, so that is the reason why I put null instead of undefined.
image

File: apps/web/pages/api/integrations.ts (hunk 15 above)
Comment (andreaestefania12) [reply apps/web/pages/api/integrations.ts:100]: Working on 👍

**Review by zomars — APPROVED** [review]
Better late than never. Very wall done and Thank you for your contribution 🙏

**Review by zomars — CHANGES_REQUESTED** [review]
Can we check if tests need to be updated or there's something wrong on the code that may be causing tests to fail? 
image

**Comment by andreaestefania12** [comment]
> Can we check if tests need to be updated or there's something wrong on the code that may be causing tests to fail? image

I am going to check it

**Review by zomars — APPROVED** [review]
Thank you for your contribution 🙏 Merging for v1.6
