### PR TITLE
fix: Allows team owners and team admins to query team availability

### LINKED ISSUE #9243: [CAL-1834] API: Teams availability returning 403 even if called by Team Owner or Team Admin
The API is returning 403 when queried for team availability even if that's done by a team owner or a team admin.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1834](https://linear.app/calcom/issue/CAL-1834/api-teams-availability-returning-403-even-if-called-by-team-owner-or)</sub>

### PR DESCRIPTION
**Pull request by alishaz-polymath**
## What does this PR do?

The modification was to remove the restriction if the user is an 'Admin' or 'Owner' of the team being queried. If the user's role within the team is either 'Admin' or 'Owner', they are allowed to retrieve the availability of each member, regardless of their Admin status as a user in the instance.

Fixes #9243 

**Environment**: Staging(main branch)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] If you send an API request to the teams/{teamId}/availability endpoint with a team owner or a team admin, who isn't a system admin, now the call should go through fine. Earlier, it was returning 403 if it was made by anyone who isn't a system admin

### CODE REVIEW

File: apps/api/pages/api/availability/_get.ts [hunk 1]
```diff
@@ -134,7 +135,14 @@ async function handler(req: NextApiRequest) {
     where: { id: { in: allMemberIds } },
     select: availabilityUserSelect,
   });
-  if (!isAdmin) throw new HttpError({ statusCode: 403, message: "Forbidden" });
+  const memberRoles = team.members.reduce((acc, membership) => {
+    acc[membership.userId] = membership.role;
+    return acc;
+  }, {});
+  // check if the user is a team Admin or Owner, if it is a team request
```
Comment (keithwillcode) [inline apps/api/pages/api/availability/_get.ts:142]: Nit: This comment shouldn't be added because you've named the variable well. It's redundant.

**Review by keithwillcode — APPROVED** [review]

**Review by keithwillcode — CHANGES_REQUESTED** [review]
API deployment to Vercel is failing.
@calcom/api:build: ./pages/api/availability/_get.ts:139:5
@calcom/api:build: Type error: Element implicitly has an 'any' type because expression of type 'number' can't be used to index type '{}'.

**Review by alannnc — APPROVED** [review]

**Review by keithwillcode — APPROVED** [review]
