### PR TITLE
fix: Text in Embed Code  Visibility Fixed

### LINKED ISSUE #15707: Text in Embed Code Becomes Invisible When Selected
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When selecting the provided embed code with the mouse, the selected lines become invisible (less visible) due to the change in colour to white from black.

### Steps to Reproduce

1. Go to the Embed section of the calendar.
2. Try to select the text with the mouse.

Include any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- The text is white and not visible.

### Expected Results

- When selected, the text should change to a visible colour instead of white.

### Technical Details

- Chrome (Version 126.0.6478.127 (Official Build) (arm64))

### Evidence

https://github.com/calcom/cal.com/assets/51878265/65a91b83-dbec-43d5-8e81-b2e11370f55a

### PR DESCRIPTION
**Pull request by anku909**
## What does this PR do?

- Fixes #15707
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

# Evidence
Screenshot_2024-07-09_21_33_43
Screenshot_2024-07-09_21_32_31

### CODE REVIEW

File: packages/features/embed/lib/EmbedTabs.tsx [hunk 1]
```diff
@@ -44,7 +44,7 @@ export const tabs = [
             data-testid="embed-code"
             ref={ref as typeof ref & MutableRefObject<HTMLTextAreaElement>}
             name="embed-code"
-            className="text-default bg-default selection:bg-subtle h-[calc(100%-50px)] font-mono"
+            className="text-default bg-default  h-[calc(100%-50px)] font-mono selection:bg-black dark:selection:bg-white"
```
Comment (anikdhabal) [inline packages/features/embed/lib/EmbedTabs.tsx:47]: Hey just remove `selection:bg-subtle`

**Review by anikdhabal — CHANGES_REQUESTED** [review]

**Review by anikdhabal — DISMISSED** [review]
LGTM

File: packages/features/embed/lib/EmbedTabs.tsx [hunk 2]
```diff
@@ -44,7 +44,7 @@ export const tabs = [
             data-testid="embed-code"
             ref={ref as typeof ref & MutableRefObject<HTMLTextAreaElement>}
             name="embed-code"
-            className="text-default bg-default selection:bg-subtle h-[calc(100%-50px)] font-mono"
+            className="text-default bg-default  h-[calc(100%-50px)] font-mono"
```
Comment (keithwillcode) [inline packages/features/embed/lib/EmbedTabs.tsx:47]:
```suggestion
            className="text-default bg-default h-[calc(100%-50px)] font-mono"
```

**Review by keithwillcode — APPROVED** [review]
