### PR TITLE
Resolved[#8732] Adding Trim to remove extra space

### LINKED ISSUE #8732: Email with space in prefix and postfix should not be considered as a different user
### Issue Summary

Email with space in prefix and postfix should not be considered as a different user – while adding member to a team

### Steps to Reproduce

1. Open cal.com and log in
2. Go to Settings
3. Press on **ADD A TEAM** button
4. Start creating a new team
5. In the step-2 of creating a new team, invite someone to the team who is not a user
 of cal.com
6. Now, again, try to invite the same email address to the team by using space in prefix and postfix of the email address (example: {space} email {space} )
7. The app recognizes the email address as a different user and shows error- "Invite failed because there is no corresponding user for *************"

### Actual Results
7. The add recognizes the email address as a different user and shows error- "Invite failed because there is no corresponding user for *************"

### Expected Results
Email with space in prefix and postfix should not be considered as a different user – while adding member to a team

### Technical details
OS: MacOS Ventura 13.3.1 (a)
Browser: Chrome 113.0.5672.63

### PR DESCRIPTION
**Pull request by pranjalg13**
## What does this PR do?

Added .trim() to the email value while adding new member so that it is not treated as a new email.

Fixes #8732

**Environment**: Staging(main branch) / Production

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [x] Without the changes the space between email while adding a new member was considered as a new member
- [x] Now with the changes it wont be (added .trim to the value_

### CODE REVIEW

**Comment by pranjalg13** [comment]
@zomars please review this once

**Review by Udit-takkar — COMMENTED** [review]
Screenshot 2023-05-09 at 1 02 35 AM

LGTM.
I have pushed some changes in the code

**Comment by pranjalg13** [comment]
@zomars please review this once.
Thanks

File: packages/features/ee/teams/components/MemberInvitationModal.tsx [hunk 1]
```diff
@@ -96,7 +96,7 @@ export default function MemberInvitationModal(props: MemberInvitationModalProps)
                     name="inviteUser"
                     placeholder="email@example.com"
                     required
-                    onChange={onChange}
+                    onChange={(e) => onChange(e.target.value.trim().toLowerCase())}
```
Comment (hariombalhara) [inline packages/features/ee/teams/components/MemberInvitationModal.tsx:99]: Can add similar logic in rules as well so that the error can be shown without needing validation from server.
Screenshot 2023-05-10 at 11 23 21 AM

**Review by hariombalhara — APPROVED** [review]
LGTM!! Apart from the small suggestion
