### PR TITLE
iCalendar timezone fix in CalDAV

### LINKED ISSUE #2139: Apple Calendar/CalDav events are getting converted to GMT
Apple Calendar events are shown in the GMT time zone in Cal even though the apple calendar account is set to EST.
This is causing double booking. 
cal com timezone bug

### PR DESCRIPTION
**Pull request by alishaz-polymath**
## What does this PR do?

Adds support for timezone change when vTimezone is not provided in the calendar object, but tzid is provided. This is the case with iCalendar, along with a few other service providers.

Fixes #2139 

[Loom](https://www.loom.com/share/8aee64f227884d9f84ac9f25d1d86455)

**Environment**: Staging(main branch)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [x] connect apple calendar and mark something busy there
- [x] Test for the timeslot in Cal to ensure timezone shift for the slots is accurate

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/lib/CalendarService.ts [hunk 1]
```diff
@@ -47,6 +47,17 @@ const getDuration = (start: string, end: string): DurationObject => ({
...
+const buildUtcOffset = (minutes: number): string => {
+  const h =
+    minutes > 0
+      ? "+" + (Math.floor(minutes / 60) < 10 ? "0" + Math.floor(minutes / 60) : Math.floor(minutes / 60))
+      : "-" +
+        (Math.ceil(minutes / 60) > -10 ? "0" + Math.ceil(minutes / 60) * -1 : Math.ceil(minutes / 60) * -1);
+  const m = minutes > 0 ? minutes % 60 : (minutes % 60) * -1;
+  const offset = `${h}:${m}`;
+  return offset;
+};
```
Comment (alishaz-polymath) [inline packages/lib/CalendarService.ts:59]: Simply takes in the offset in minutes and returns the offset in the format of `+-hh:mm`. This is done to satisfy the needs of our beloved ICAL parser to adjust the timezone of the event's start and end date and to avoid the GMT shift caused in the absence of `vTimezone`

File: packages/lib/CalendarService.ts [hunk 2]
```diff
@@ -274,6 +285,24 @@ export default abstract class BaseCalendarService implements Calendar {
...
+        const tzoffsetfrom = buildUtcOffset(dayjs(event.startDate.toJSDate()).tz(tzid, true).utcOffset());
+        const tzoffsetto = buildUtcOffset(dayjs(event.endDate.toJSDate()).tz(tzid, true).utcOffset());
+        // set timezone offset
+        standard.addPropertyWithValue("tzoffsetfrom", tzoffsetfrom);
+        standard.addPropertyWithValue("tzoffsetto", tzoffsetto);
+        // provide a standard dtstart
+        standard.addPropertyWithValue("dtstart", "1601-01-01T00:00:00");
+        timezoneComp.addSubcomponent(standard);
+        vcalendar.addSubcomponent(timezoneComp);
+      }
```
Comment (alishaz-polymath) [inline packages/lib/CalendarService.ts:305]: If `vTimezone` is absent and `tzid` is present, we "build" the `vTimezone` component from the `tzid` and make sure to include the `dtstart`, `tzoffsetfrom`, and `tzoffsetto` and then add it to the `vCalendar` component to ensure proper timezone conversion

**Review by alishaz-polymath — COMMENTED** [review]
Self review added

File: packages/lib/CalendarService.ts [hunk 3]
```diff
@@ -274,6 +285,24 @@ export default abstract class BaseCalendarService implements Calendar {
...
+        timezoneComp.addPropertyWithValue("tzid", tzid);
+        const standard = new ICAL.Component("standard");
+        // get timezone offset
+        const tzoffsetfrom = buildUtcOffset(dayjs(event.startDate.toJSDate()).tz(tzid, true).utcOffset());
+        const tzoffsetto = buildUtcOffset(dayjs(event.endDate.toJSDate()).tz(tzid, true).utcOffset());
+        // set timezone offset
+        standard.addPropertyWithValue("tzoffsetfrom", tzoffsetfrom);
+        standard.addPropertyWithValue("tzoffsetto", tzoffsetto);
+        // provide a standard dtstart
+        standard.addPropertyWithValue("dtstart", "1601-01-01T00:00:00");
```
Comment (emrysal) [inline packages/lib/CalendarService.ts:302]: How did you get to 1601?

File: packages/lib/CalendarService.ts (hunk 2 above)
Comment (alishaz-polymath) [reply packages/lib/CalendarService.ts:305]: this might still require consideration of daylight savings but I believe I'd need to add that as a follow up

File: packages/lib/CalendarService.ts (hunk 3 above)
Comment (alishaz-polymath) [reply packages/lib/CalendarService.ts:302]: Oh I just monitored a few calls and this seemed like a standard dtstart. It doesn't really matter as long as it is before the earliest start time of the calendar.

File: packages/lib/CalendarService.ts [hunk 4]
```diff
@@ -47,6 +47,17 @@ const getDuration = (start: string, end: string): DurationObject => ({
   minutes: dayjs(end).diff(dayjs(start), "minute"),
 });
 
+const buildUtcOffset = (minutes: number): string => {
+  const h =
+    minutes > 0
+      ? "+" + (Math.floor(minutes / 60) < 10 ? "0" + Math.floor(minutes / 60) : Math.floor(minutes / 60))
+      : "-" +
+        (Math.ceil(minutes / 60) > -10 ? "0" + Math.ceil(minutes / 60) * -1 : Math.ceil(minutes / 60) * -1);
+  const m = minutes > 0 ? minutes % 60 : (minutes % 60) * -1;
```
Comment (emrysal) [inline packages/lib/CalendarService.ts:56]: Correct me if I'm wrong but wouldn't a minutes offset like this cause a potential for:
```
-2:-15
// in case of -135?
```

**Review by emrysal — CHANGES_REQUESTED** [review]

File: packages/lib/CalendarService.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (alishaz-polymath) [reply packages/lib/CalendarService.ts:56]: Yeah, this is a good suggestion 🙏

Comment (emrysal) [reply packages/lib/CalendarService.ts]: You're right, but yeah abs is a little neater anyway.

**Review by emrysal — APPROVED** [review]

File: packages/lib/CalendarService.ts (hunk 4 above)
Comment (alishaz-polymath) [reply packages/lib/CalendarService.ts]: Oh yeah, for sure. Way better. I believe there’s still room for code improvement but I’ll do that in a follow up where I take care of the daylight monster 🥲

File: packages/lib/CalendarService.ts (hunk 2 above)
Comment (hariombalhara) [inline packages/lib/CalendarService.ts:305]: Don't know what sorcery is going on in this PR @alishaz-polymath @emrysal 😂

Comment (alishaz-polymath) [reply packages/lib/CalendarService.ts:305]: Just pleasing the Timezone Masters 🥲

**Comment by davidwuest** [comment]
Still having the issue with iCalendar timezone. Running on Docker, the commits are already in the latest as far as I can see. Anyone els can confirm this?

**Comment by alishaz-polymath** [comment]
> 

Hey @davidwuest can you elaborate on the exact issue? There is still daylight issue to be taken care of so if you’re testing it post October dates, there will still be a discrepancy of 1 hour. If you’re testing in October, and with our latest main pull, please let me know.

**Comment by davidwuest** [comment]
@alishaz-polymath I was only testing within October. Checked that the latest main pull was in the docker build. I will make another build, without any cache to see if that is the issue. Let me know what I can do to support to fix this issue.

**Comment by alishaz-polymath** [comment]
Can you please book me [here](https://cal.com/d/f1bTqT6zejuHfKzDHtR7Wc/quick-chat) and we can then take care of it on a call, explore it further
