### PR TITLE
fix: Create team events using admin token

### LINKED ISSUE #9119: [CAL-1787] Impossible to create Team Event Type with admin token
When we try to create an Event Type `checkTeamEventEditPermission` function is called, which checks if a user from request has membership in the given team. But the correct flow for admin is to pass `userId` in the request body. 

This code: 
```
  const { prisma, userId } = req;
  if (body.teamId) {
    const membership = await prisma.membership.findFirst({
      where: {
        userId,
        teamId: body.teamId,
        accepted: true,
      },
    });
```

Shouldn't take `userId` from `body`, not `req`

<sub>[CAL-1787](https://linear.app/calcom/issue/CAL-1787/impossible-to-create-team-event-type-with-admin-token)</sub>

### PR DESCRIPTION
**Pull request by asadath1395**
## What does this PR do?

Fixes #9119 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Create a new event using the API, i used the below payload
```json
{
    "title": "Hello World",
    "slug": "hello-world",
    "length": 30,
    "hidden": false,
    "position": 0,
    "eventName": null,
    "timeZone": null,
    "scheduleId": 5,
    "periodType": "UNLIMITED",
    "periodDays": null,
    "periodCountCalendarDays": false,
    "requiresConfirmation": false,
    "disableGuests": false,
    "hideCalendarNotes": false,
    "minimumBookingNotice": 120,
    "beforeEventBuffer": 0,
    "afterEventBuffer": 0,
    "price": 0,
    "currency": "usd",
    "slotInterval": null,
    "successRedirectUrl": null,
    "description": "A test event type",
    "teamId": 1,
    "userId": 13
}
```

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by asadath1395** [comment]
Quick question: As an admin, shouldn't i not see all the teams and its events in the UI?

File: apps/api/pages/api/event-types/_utils/checkTeamEventEditPermission.ts [hunk 1]
```diff
@@ -3,13 +3,17 @@ import type { z } from "zod";
 
 import { HttpError } from "@calcom/lib/http-error";
 
-import type { schemaEventTypeBaseBodyParams } from "~/lib/validations/event-type";
+import { type schemaEventTypeCreateBodyParams } from "~/lib/validations/event-type";
```
Comment (emrysal) [inline apps/api/pages/api/event-types/_utils/checkTeamEventEditPermission.ts:6]:
```suggestion
import type { schemaEventTypeCreateBodyParams } from "~/lib/validations/event-type";
```

**Review by emrysal — APPROVED** [review]
Looks good to me :)
