### PR TITLE
fix: Zoho Bigin not pulling information from booking

### LINKED ISSUE #16035: [CAL-4072] Zoho bigin
Issue with Zoho Bigin: the integration installs and you can toggle the app in the event types, but it does not pull up any information in Zoho Bigin.
The app is turned on for the event type, but it's still not working.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4072](https://linear.app/calcom/issue/CAL-4072/zoho-bigin)</sub>

### PR DESCRIPTION
**Pull request by anikdhabal**
## What does this PR do?

- Fixes CAL-4072
- Fixes https://github.com/calcom/cal.com/issues/16035

Now:-
Screenshot 2025-01-02 213306
Screenshot 2025-01-02 213228

### CODE REVIEW

File: packages/app-store/zoho-bigin/lib/CrmService.ts [hunk 1]
```diff
@@ -134,7 +132,7 @@ export default class BiginCrmService implements CRM {
 
     const response = await axios({
       method: "post",
-      url: token.api_domain + this.contactsSlug,
+      url: "https://www.zohoapis.in/bigin/v1/Contacts",
```
Comment (joeauyeung) [inline packages/app-store/zoho-bigin/lib/CrmService.ts:135]: I noticed you're using the `.in` domain here. We need to consider that Zoho has servers around the would with different domains. I think the current implementation handles that. Unless the string created isn't as expected?

**Review by joeauyeung — CHANGES_REQUESTED** [review]

**Review by joeauyeung — APPROVED** [review]
