### PR TITLE
fix/secret-premade-event-hidden

### LINKED ISSUE #1947: "secret" event-type is not hidden
the pre-made secret event-type used to be hidden but now it's hidden: false

image

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

Fix hidden field for secret event created on the onboarding page for initial users, and a minor lint fix.

Fixes #1947 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [X] Run the onboarding page for a user that hasn't completed it, and after finishing it. It should have 3 event types and the one that is called _"Secret Meeting"_ should be flagged as **hidden**.

### CODE REVIEW

File: packages/prisma/zod/custom/eventtype.ts [hunk 1]
```diff
@@ -1,15 +1,17 @@
...
+  .pick({
+    title: true,
+    slug: true,
+    description: true,
+    length: true,
+    teamId: true,
+    schedulingType: true,
+    hidden: true,
+  })
+  .partial({ hidden: true })
```
Comment (zomars) [inline packages/prisma/zod/custom/eventtype.ts:13]: Why is this needed?

Comment (alannnc) [reply packages/prisma/zod/custom/eventtype.ts:13]: @zomars 
Looks like when creating event types via API, hidden field it's omitted sometimes. With these we flag hidden as an optional field, and if it's missing on the data before creating it, it will default to create eventType with default false value.

**Review by zomars — APPROVED** [review]
