### PR TITLE
fix: missing empty state in `/apps/installed/web3`

### LINKED ISSUE #6370: [CAL-733] /apps/installed/web3 - missing empty state
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-733](https://linear.app/calcom/issue/CAL-733/appsinstalledweb3-missing-empty-state)</sub>

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

Fixes #6370 

before:
Screenshot 2023-01-10 at 22-24-50 Installed Apps Cal com

after:
Screenshot 2023-01-10 at 22-22-47 Installed Apps Cal com

**Environment**: Staging(main branch) / Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by G3root** [comment]
@PeerRich there's some missing translation keys, is it good to go ?

**Comment by PeerRich** [comment]
> @PeerRich there's some missing translation keys, is it good to go ?

no you have to add them to public/static/locales/en/common.json

**Comment by G3root** [comment]
@PeerRich added the i18n keys.

**Comment by PeerRich** [comment]
types failing

CleanShot 2023-01-10 at 19 50 18@2x

File: apps/web/components/apps/layouts/InstalledAppsLayout.tsx [hunk 1]
```diff
@@ -44,13 +44,15 @@ export default function InstalledAppsLayout({
...
+
   const query = trpc.viewer.integrations.useQuery({
-    variant: InstalledAppVariants.payment,
+    variant,
     onlyInstalled: true,
   });
   let actualTabs = tabs;
   if (query.data?.items.length === 0) {
-    actualTabs = tabs.filter((tab) => tab.name !== InstalledAppVariants.payment);
+    actualTabs = tabs.filter((tab) => tab.name !== variant);
```
Comment (leog) [inline apps/web/components/apps/layouts/InstalledAppsLayout.tsx:55]: Not sure about this change, mainly because there is a warning here 👇 that says `actualTabs` is never used.

File: apps/web/pages/apps/installed/[category].tsx [hunk 2]
```diff
@@ -198,31 +200,29 @@ const IntegrationsContainer = ({ variant, exclude }: IntegrationsContainerProps)
 };
 
 const querySchema = z.object({
-  category: z.nativeEnum(InstalledAppVariants),
+  category: z.enum(InstalledAppVariants),
```
Comment (leog) [inline apps/web/pages/apps/installed/[category].tsx:203]: Does this work? I had problems in the past trying to do this, always had to use `nativeEnum`

File: apps/web/pages/apps/installed/[category].tsx [hunk 3]
```diff
@@ -198,31 +200,29 @@ const IntegrationsContainer = ({ variant, exclude }: IntegrationsContainerProps)
...
-            InstalledAppVariants.conferencing,
-            InstalledAppVariants.calendar,
-            InstalledAppVariants.analytics,
-            InstalledAppVariants.automation,
-          ]}
-        />
+      {categoryList.includes(category) && <IntegrationsContainer variant={category} />}
+      {category === "calendar" && <CalendarListContainer />}
+      {category === "other" && (
+        <IntegrationsContainer variant={category} exclude={[...categoryList, "calendar"]} />
```
Comment (leog) [inline apps/web/pages/apps/installed/[category].tsx:225]: I like how this was simplified!

File: apps/web/pages/apps/installed/[category].tsx (hunk 2 above)
Comment (leog) [reply apps/web/pages/apps/installed/[category].tsx:203]: Saw the change in the enum itself, I get it 👍

**Review by leog — APPROVED** [review]
LGTM
