### PR TITLE
fix: button shifting while focusing

### LINKED ISSUE #6516: [CAL-806] Component: Button - focus state causing shifting
Focussing on our buttons shouldn't cause things to jump around. Perhaps we need to have the same properties on the default state but hidden with opacity and then shown on hover rather than adding something that's causing the jump but will let the professionals diagnose 😃

[bfbd6789-e9fc-44a0-98ca-63222f728a43](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/5d4578cd-8ad1-475e-b24d-27b232461b02/bfbd6789-e9fc-44a0-98ca-63222f728a43)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-806](https://linear.app/calcom/issue/CAL-806/component-button-focus-state-causing-shifting)</sub>

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

Fixes #6516 
https://www.loom.com/share/c5c2dc820bef408a9feb4cbbf3a14a4f

**Environment**: Staging(main branch) / Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

File: apps/web/components/booking/pages/BookingPage.tsx [hunk 1]
```diff
@@ -961,12 +961,7 @@ const BookingPage = ({
                       className="mr-auto"
                     />
                   )}
-                  <Button
-                    color="minimal"
-                    type="button"
-                    onClick={() => router.back()}
-                    // We override this for this component only for now - as we don't support darkmode everywhere in the app
-                    className="dark:hover:bg-darkgray-200 dark:border-none dark:text-white">
```
Comment (G3root) [inline apps/web/components/booking/pages/BookingPage.tsx:969]: removed className because button component has dark styles.

**Review by sean-brydon — APPROVED** [review]
LGTM - my bad for using border ;)

**Review by emrysal — APPROVED** [review]
lgtm
