### PR TITLE
fix(form-builder): correct value of selection box behavior in Edit of new Added Question dialog

### LINKED ISSUE #27889: Input type selection not updating correctly in Add Question (Advanced Tab)
### Issue Summary

Inside Event Edit → Advanced → Questions → Add Question, changing the value from the selection box does not update the input box correctly. When a user chooses a different option, the UI continues to display the previous value.

### Steps to Reproduce

1. Open any Event and click Edit.
2. Navigate to the Advanced tab.
3. Click Add Question.
4. Change the values from the selection dropdown.
5. Notice that the selected value does not update as expected.

### Actual Results

- Selecting a different values does not reflect visually in the selection box.

### Expected Results

- When a user selects a different option, the SelectField should update immediately.

### PR DESCRIPTION
**Pull request by Shrey-Sutariya**
## What does this PR do?

Inside Event Edit → Advanced → Add Question → Edit Question , changing the values from the selection dropdown did not update the displayed value correctly. When users selected a different option, the UI continued showing the previous value because the onChange handler and the rendered value were referencing different sources.

- Fixes #27889
- Fixes [CAL-7200](https://linear.app/calcom/issue/CAL-7200/input-type-selection-not-updating-correctly-in-add-question-advanced)

#### Video Demo (Before):

https://github.com/user-attachments/assets/7e768a9d-c4ee-4311-adfe-0d77cac1dc8b

#### Video Demo (After):

https://github.com/user-attachments/assets/ad436797-8229-4e2e-89fb-cb999be7db4c

- UI behavior fix only.
- No backend or data structure changes.

## Mandatory Tasks 

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

File: apps/web/modules/event-types/components/tabs/advanced/FormBuilder.tsx [hunk 1]
```diff
@@ -645,7 +647,8 @@ function FieldEditDialog({
                 }
                 fieldForm.setValue("type", value, { shouldDirty: true });
               }}
-              value={dialog.data ? getLocationFieldType(dialog.data) : fieldTypesConfigMap[formFieldType]}
+              value={fieldTypesConfigMap[formFieldType]}
+              // value="Hello World"
```
Comment (romitg2) [inline apps/web/modules/event-types/components/tabs/advanced/FormBuilder.tsx]: can you please remove this comment?

**Review by romitg2 — CHANGES_REQUESTED** [review]

File: apps/web/modules/event-types/components/tabs/advanced/FormBuilder.tsx (hunk 1 above)
Comment (Shrey-Sutariya) [reply apps/web/modules/event-types/components/tabs/advanced/FormBuilder.tsx]: This one is Fixed

**Review by romitg2 — APPROVED** [review]
