### PR TITLE
Rounded divider + Fixing button group

### LINKED ISSUE #4181: /routing-form-detail - header actions - combined button component has double border
Image

And divider has rounded corners :)

Image

### PR DESCRIPTION
**Pull request by sean-brydon**
## What does this PR do?

Fixes button group and adds rounded divider. I will take no credit for the button group fix (he massively gave inspiration with this approach)   - Thank you https://twitter.com/malfaitrobin

Before:
CleanShot 2022-09-07 at 11 40 37@2x

After:
CleanShot 2022-09-07 at 11 39 34@2x

Fixes #4181

### CODE REVIEW

**Review by PeerRich — APPROVED** [review]
awesome!

File: packages/ui/v2/core/ButtonGroup.tsx [hunk 1]
```diff
@@ -8,7 +8,13 @@ export default function ButtonGroup({ children, combined = false, containerProps
   return (
     <div
       {...containerProps}
-      className={classNames("flex", !combined && "space-x-2", containerProps?.className)}>
+      className={classNames(
+        "flex",
+        !combined
+          ? "space-x-2"
+          : "[&_button]:border-l-0 [&>*:first-child]:rounded-l-md [&>*:first-child]:border-l [&_a]:border-l-0  [&>*:last-child]:rounded-r-md",
```
Comment (PeerRich) [inline packages/ui/v2/core/ButtonGroup.tsx:15]: @sean-brydon for those unaware of tailwind magic, can you explain what this does?

Comment (sean-brydon) [reply packages/ui/v2/core/ButtonGroup.tsx:15]: I'll add a comment in the code :)

**Review by PeerRich — APPROVED** [review]
