### PR TITLE
fix: optional email validation

### LINKED ISSUE #27299: Optional email field still requires verification
An optional email field (booking question) should still require email verification when an input is given. At the moment, you can submit any text.

### PR DESCRIPTION
**Pull request by deepeshbind**
## What does this PR do?

- Currently, optional email fields bypass validation entirely if any input is provided. This PR ensures that if a user provides an input in an optional email field, it must follow a valid email format, while still allowing the field to be left empty.

- Fixes #27299. 
- Fixes CAL-7141

Changes
- packages/prisma/zod-utils.ts: Updated emailSchemaRefinement to handle optionality (passing on empty/null values) while maintaining strict validation for any provided input.

- packages/features/bookings/lib/getBookingResponsesSchema.ts: Updated the email validation trigger to include optional fields that contain a value. This follows the existing pattern used for phone number validation.

- packages/features/bookings/lib/getBookingResponsesSchema.test.ts: Added regression tests to verify that optional fields pass when empty and fail when invalid input is provided.

## Why this implementation?
I noticed another PR addressing this, but I chose to modify the global zod-utils to keep the schema as the single source of truth. By centralizing the refinement logic, we ensure consistent validation behavior across the entire platform and prevent future regressions through the added test cases.

## Visual Demo (For contributors especially)

https://github.com/user-attachments/assets/830fbefe-57f9-4a94-a257-6a7e2bd2c85a

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Create or edit an Event Type. Add a "Booking Question" of type Email. Ensure "Required" is toggled OFF.
- Open the booking page. Leave the optional email field empty. Click "Confirm". The booking should succeed.
- Open the booking page. Type not-an-email into the optional field. Click "Confirm".
- The form should block submission and display {field_name}Invalid email.

## Checklist

- I have read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code follows the style guidelines of this project
- I have checked if my changes generate no new warnings
- My PR is small and focused (<10 lines of functional change)

### CODE REVIEW

**Review by eunjae-lee — APPROVED** [review]
thanks for adding the test !

File: packages/prisma/zod-utils.ts [hunk 1]
```diff
@@ -901,7 +901,12 @@ export const emailSchema = emailRegexSchema;
 // The PR at https://github.com/colinhacks/zod/pull/2157 addresses this issue and improves email validation
 // I introduced this refinement(to be used with z.email()) as a short term solution until we upgrade to a zod
 // version that will include updates in the above PR.
-export const emailSchemaRefinement = (value: string) => {
+export const emailSchemaRefinement = (value: string | null | undefined) => {
+  // If no value is provided (optional field left blank), return true (valid)
+  if (!value || value.trim().length === 0) {
+    return true;
+  }
```
Comment (eunjae-lee) [inline packages/prisma/zod-utils.ts]: Hmm I'm not too confident about this. Can we handle "no value" situation outside this function

**Review by eunjae-lee — CHANGES_REQUESTED** [review]

File: packages/features/bookings/lib/getBookingResponsesSchema.test.ts [hunk 2]
```diff
@@ -1854,4 +1854,73 @@ describe("require email/domain validation", () => {
       })
     );
   });
+
+  test(`optional email field should fail if invalid input is provided`, async () => {
```
Comment (hbjORbj) [inline packages/features/bookings/lib/getBookingResponsesSchema.test.ts:1858]: Thanks for adding the unit test. Would you create a new e2e test as well? Thanks !

**Review by hbjORbj — DISMISSED** [review]

File: packages/prisma/zod-utils.ts (hunk 1 above)
Comment (deepeshbind) [reply packages/prisma/zod-utils.ts]: Done! I’ve moved the "no value" check into the schema file instead of the global utility. Thanks for the guidance!

File: packages/features/bookings/lib/getBookingResponsesSchema.test.ts (hunk 2 above)
Comment (deepeshbind) [reply packages/features/bookings/lib/getBookingResponsesSchema.test.ts:1858]: Thanks for the feedback! I’ll add an E2E test for optional email validation and update the PR once it’s ready.

Comment (deepeshbind) [reply packages/features/bookings/lib/getBookingResponsesSchema.test.ts:1858]: Hi @hbjORbj , i have added the requested e2e test.

**Review by eunjae-lee — APPROVED** [review]

**Comment by deepeshbind** [comment]
Hi @eunjae-lee, just checking in—happy to help if anything’s needed.

**Comment by eunjae-lee** [comment]
> Hi @eunjae-lee, just checking in—happy to help if anything’s needed.

let me ping the other team (we still need their approval)

**Review by volnei — APPROVED** [review]
