### PR TITLE
fix(settings): improve spacing between navigation child items

### LINKED ISSUE #25635: Add vertical spacing between dropdown items and roundness to one section
### Issue Summary

Rounded hover states were added to dropdown items in FilterSegmentSelect and the settings navigation, but vertical spacing between items is missing. This makes hover states overlap and reduces clarity.

### Steps to Reproduce

1. Go to /settings/my-account/profile (or any settings page)
2. Open the settings sidebar navigation
3. Expand a section with child items (e.g., "My Account" with Profile, General, Calendars, etc.)
4. Hover over child navigation items
5. Observe the spacing between items

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

Image

Image

### Expected Results

Image

Image

### PR DESCRIPTION
**Pull request by KartikLabhshetwar**
## What does this PR do?

- Fixes #25635
- Fixes [CAL-6873](https://linear.app/calcom/issue/CAL-6873/add-vertical-spacing-between-dropdown-items-and-roundness-to-one)
## Visual Demo (For contributors especially)

A visual demonstration is strongly recommended, for both the original and new change **(video / image - any one)**.

#### Image Demo (if applicable):

before:
Screenshot 2025-12-05 at 12 44 51 PM
Screenshot 2025-12-05 at 12 56 33 PM
Screenshot 2025-12-06 at 2 21 12 PM

after:
Screenshot 2025-12-05 at 12 48 56 PM
Screenshot 2025-12-05 at 1 03 18 PM
Screenshot 2025-12-06 at 2 18 29 PM

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

File: apps/web/app/(use-page-wrapper)/settings/(settings-layout)/SettingsLayoutAppDirClient.tsx [hunk 1]
```diff
@@ -647,7 +758,7 @@ const SettingsSidebarContainer = ({
                       </Skeleton>
                     </div>
                   </div>
-                  <div className="stack-y-px">
+                  <div className="flex flex-col space-y-1">
```
Comment (KartikLabhshetwar) [inline apps/web/app/(use-page-wrapper)/settings/(settings-layout)/SettingsLayoutAppDirClient.tsx:761]: this is the change which i have done in this file rest of the other changes are done by prettier.

Comment (dhairyashiil) [reply apps/web/app/(use-page-wrapper)/settings/(settings-layout)/SettingsLayoutAppDirClient.tsx:761]: revert them

Comment (dhairyashiil) [reply apps/web/app/(use-page-wrapper)/settings/(settings-layout)/SettingsLayoutAppDirClient.tsx:761]: make it easy for us to review 😅

**Review by dhairyashiil — CHANGES_REQUESTED** [review]
please create an issue and link the PR to it. Also, it would be really helpful if you could revert the Prettier changes in this file to make the review easier. Thankss

**Comment by KartikLabhshetwar** [comment]
> please create an issue and link the PR to it. Also, it would be really helpful if you could revert the Prettier changes in this file to make the review easier. Thankss

hi @dhairyashiil i have removed the prettier formatting, can you please review this once again?

**Review by dhairyashiil — COMMENTED** [review]
Are we also changing the border radius for outer div? 

Screenshot 2025-12-05 at 3 27 30 PM


maybe we should change only inner one

**Comment by KartikLabhshetwar** [comment]
> Are we also changing the border radius for outer div?
> 
> Screenshot 2025-12-05 at 3 27 30 PM
> maybe we should change only inner one

We're only changing the inner items (DropdownMenuItem), not the outer container (DropdownMenuContent).

**Comment by KartikLabhshetwar** [comment]
hi @dhairyashiil i have fixed the spacing issue between booking navigation, also address the issues which you mentioned.

before:
Screenshot 2025-12-06 at 2 21 12 PM


after:
Screenshot 2025-12-06 at 2 18 29 PM

**Comment by dhairyashiil** [comment]
Applied the same fix here: 

Screenshot 2025-12-12 at 12 02 12 AM

**Review by dhairyashiil — APPROVED** [review]
Rest looks good to me 👍🏼 
Thank you for the contribution.
