### PR TITLE
fix: #16150 update to fix seated event reschedule

### LINKED ISSUE #16150: [CAL-4131] Can reschedule a booking out of availability (seated event)
There is a bug in seated events that when you reschedule using the API you can reschedule to a slot that is out of your availability.

How to reproduce:

* create an event with seats
* book first seat of one slot
* API call to reschedule booking: `POST https://api.cal.com/v1/bookings?apiKey=... `
  * body:

```
{
  "eventTypeId": <event type id here>,
  "start": "2024-08-10T16:30:00+02:00", --> pick unavailable slot time
  "rescheduleUid": <bookingUID here>,
  "responses": {
    "name": "test",
    "email": "test@example.com", 
    "guests": [],
    "location": {
      "value": "inPerson",
      "optionValue": ""
     }
   },
"metadata": {},
"timeZone": "Europe/London",
"language": "en"
}
```

* This will reschedule the booking to the unavailable slot, it should throw a `no_available_users_found_error`

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4131](https://linear.app/calcom/issue/CAL-4131/can-reschedule-a-booking-out-of-availability-seated-event)</sub>

### PR DESCRIPTION
**Pull request by vijayraghav-io**
## What does this PR do?

- Fixes #16150 
- Fixes CAL-4131

https://www.loom.com/share/750656f945fe41f98a69c65e0bac9066?sid=b3334c28-047b-42be-9d06-e00c32f85423

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 1]
```diff
@@ -483,15 +483,9 @@ async function handler(
   if (eventType.seatsPerTimeSlot) {
     const booking = await prisma.booking.findFirst({
       where: {
-        OR: [
```
Comment (vijayraghav-io) [inline packages/features/bookings/lib/handleNewBooking.ts:486]: Due to this OR condition, in case of reschedule , the check on timeslot was skipped.
Hence the reschedule scenario was considered as second seat booking, isFirstSeat was set to false.
So user availability check was skipped causing to book in nonavailability slots.

Timeslot is the key here to determine if same slot is being booked for second/multiple seats.
Tested for #15105 scenario as well

**Comment by anikdhabal** [comment]
@vijayraghav-io pls share a loom video

**Review by Amit91848 — CHANGES_REQUESTED** [review]
Thanks for the PR @vijayraghav-io ! Works well, can you expand tests in `handleSeats.test.ts` to cover this scenario

**Comment by vijayraghav-io** [comment]
> Thanks for the PR @vijayraghav-io ! Works well, can you expand tests in `handleSeats.test.ts` to cover this scenario

Thankyou! @Amit91848 , updated tests and verified

**Review by Amit91848 — DISMISSED** [review]
LGTM! Tested and works 🚀. Thanks @vijayraghav-io

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 2]
```diff
@@ -483,15 +483,9 @@ async function handler(
...
-          {
-            uid: rescheduleUid || reqBody.bookingUid,
-          },
-          {
-            eventTypeId: eventType.id,
-            startTime: new Date(dayjs(reqBody.start).utc().format()),
-          },
-        ],
+        uid: rescheduleUid || reqBody.bookingUid,
```
Comment (Amit91848) [inline packages/features/bookings/lib/handleNewBooking.ts:486]: On a second thought do we even need to search by uid here? We just need to find if there is a booking at a particular time, for which we need only eventTypeId and startTime?

When rescheduling, you will never find a booking with rescheduleUid and startTime of the new slot, so it will always be treated as first seat. Although it does not look like anything is breaking 🤔

Comment (vijayraghav-io) [reply packages/features/bookings/lib/handleNewBooking.ts:486]: Yes uid is not required, but nothing will break now by having it. Since reqBody.bookingUid was used, i left it as it is.
In case of new booking, there is no bookingUid or rescheduleUId, uid will be false, prisma will remove this field from where clause, when value is false , so not a problem.
In case of reschedule, rescheduleUid itself is the bookingUid of original booking, any how the slot won't match to decide that it's second slot, so not a problem

Comment (CarinaWolli) [reply packages/features/bookings/lib/handleNewBooking.ts:486]: > On a second thought do we even need to search by uid here? We just need to find if there is a booking at a particular time, for which we need only eventTypeId and startTime?

Agree, I am not sure why `rescheduleUid` and `bookingUid` would be needed here

> When rescheduling, you will never find a booking with rescheduleUid and startTime of the new slot, since it has not been booked yet, so it will always be treated as first seat. Although it does not look like anything is breaking 🤔

Agree, also couldn't find anything that it breaks but that just makes me wondering why we even check for `isFirstSeat` 🤔

Comment (vijayraghav-io) [reply packages/features/bookings/lib/handleNewBooking.ts:486]: to skip avilability check - in case of seated event (or multiple slots) , if user is trying to book second seat or (for remaining seats) then no need to check for user availability.
But need to check when trying to book for first time (or first seat)

Comment (CarinaWolli) [reply packages/features/bookings/lib/handleNewBooking.ts:486]: > to skip avilability check - in case of seated event (or multiple slots) , if user is trying to book second seat or (for remaining seats) then no need to check for user availability.

I tested rescheduling to a slot that already has seats. `isFirstSeat` was true (even though it wasn't the first seat), but the availability check didn't throw an error even when I tried to create a calendar event that would conflict

Comment (vijayraghav-io) [reply packages/features/bookings/lib/handleNewBooking.ts:486]: In that case, IMO its better to remove uid from where clause.

but for fresh or new booking, if this `isFirstSeat` check is not there , booking is allowed in non-availability slots.

Comment (vijayraghav-io) [reply packages/features/bookings/lib/handleNewBooking.ts]: > > to skip avilability check - in case of seated event (or multiple slots) , if user is trying to book second seat or (for remaining seats) then no need to check for user availability.
> 
> I tested rescheduling to a slot that already has seats. `isFirstSeat` was true (even though it wasn't the first seat), but the availability check didn't throw an error even when I tried to create a calendar event that would conflict

updated to remove `uid` in where clause, now `isFirstSeat` should be false for this scenario

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 3]
```diff
@@ -483,15 +483,8 @@ async function handler(
   if (eventType.seatsPerTimeSlot) {
     const booking = await prisma.booking.findFirst({
       where: {
-        OR: [
-          {
-            uid: rescheduleUid || reqBody.bookingUid,
```
Comment (CarinaWolli) [inline packages/features/bookings/lib/handleNewBooking.ts:488]: Removing this looks ok to me, this shouldn't be needed for finding an existing seat/booking

**Review by CarinaWolli — APPROVED** [review]
Fix looks good 👍 Also, great work on adding a test for it 🙌🏻

**Review by Amit91848 — APPROVED** [review]
