### PR TITLE
fix: eventName variables

### LINKED ISSUE #10916: [CAL-2384] Canceled Booking throws off Variable
I put "**TEST**" as the company name that this is pulling in, not sure why it's throwing off a variable

Customer: [cal.com/team/spot](https://cal.com/team/spot)

Collective event: Meet with Spot

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2384](https://linear.app/calcom/issue/CAL-2384/canceled-booking-throws-off-variable)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/10916

Screenshot 2023-08-24 at 1 08 47 PM

## How to test ?

1) Go to advanced setting of any event type
2) Create a booking question with identifier "company" and short text.
3) edit event name in advanced setting and name is Your Name x {company}
4) Book a meeting and then cancel it to get the cancellation email. 

Check the subject of cancelled email of both organizer and attendee

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/core/event.ts [hunk 1]
```diff
@@ -57,8 +57,12 @@ export function getEventName(eventNameObj: EventNameObjectType, forAttendeeView
         if (variable === bookingField) {
           let fieldValue;
           if (eventNameObj.bookingFields) {
-            fieldValue =
-              eventNameObj.bookingFields[bookingField as keyof typeof eventNameObj.bookingFields]?.toString();
+            const field = eventNameObj.bookingFields[bookingField as keyof typeof eventNameObj.bookingFields];
+            if (typeof field === "object" && "value" in field) {
```
Comment (Udit-takkar) [inline packages/core/event.ts:61]: booking fields could also be of type object { value, label } ( in case of attendee-cancelled-email)

**Review by CarinaWolli — APPROVED** [review]
