### PR TITLE
fix(phone input): trigger validation and formatting for prefill query…

### LINKED ISSUE #15182: [CAL-3833] Invalid Input Phone Number Recognition, Attendee Phone Number Location Events
Currently with event type 'phone call', location 'attendee phone number'. A USA formatted phone number is returning a "invalid Input" error. Country Code dropdown has USA +1 selected, data input field auto formats the raw phone number input to +1 (XXX) XXX-XXXX. 

image

May relate to closed issue: https://github.com/calcom/cal.com/pull/15046

<sub>[CAL-3833](https://linear.app/calcom/issue/CAL-3833/invalid-input-phone-number-recognition-attendee-phone-number-location)</sub>

### LINKED ISSUE #22992: Passing phone through query params is partially broken (format makes validation not go through)
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When pre-filling any of the phone params (location, attendeePhoneNumber, smsReminderNumber) and trying to click confirm right away I'm greeted with an "Invalid format" error -- deleting the spaces between the numbers fixes the issue, I believe it has to do with the way query param numbers are getting formatted when they're rendered in the input field

Extra context: what's interesting is the format is not wrong, I've tried sending over the phone:
* with "+"
* with "%2B52"
* without "+"
* with "521" (old formatting of Mexican phone numbers)
* etc

And nothing seemed to work... Until I deleted the blank characters between the numbers, that made it go through.

### Steps to Reproduce

1. Click on this event's URL (see how we're piping the number through query params) -- https://cal.com/bunopro-intro/repro-introduccion?name=Emilio+Gonzalez+Guerra&email=emiliogzz24%40gmail.com&smsReminderNumber=%7B%22value%22%3A%22phone%22%2C%22optionValue%22%3A%22+528112886677%22%7D
2. Click on any date, see how the phone number appears in the field
3. Try clicking "Confirm" right away... You'll see an error "invalid phone"

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
* Because I'm piping the query params so the user doesn't have to make any changes in order to go through, this bug makes it such that piping the phone number without user interaction is impossible

### Actual Results

User has to modify the phone slightly in order to finish booking the event

### Expected Results

User only has to click confirm to book the event

### Technical details

NA -- tried digging in the code to see if on [packages/features/components/phone-input/PhoneInput.tsx](https://github.com/calcom/cal.com/blob/26f8246b91f84468a9bb6d8911c9cd2d3e4a188e/packages/features/components/phone-input/PhoneInput.tsx#L12) there's a formatter that could be responsible for adding extra spaces while formatting the phone but wasn't able to find it

### Evidence

Repro video: https://drive.google.com/file/d/1zNn0Tm5mzdsgLcAvX_M6sbPMHfZsA0fo/view?usp=sharing

### PR DESCRIPTION
**Pull request by Vibgitcode27**
## What does this PR do?

- **Fixes #22992**  
- **Fixes #15182**
- This PR ensures prefilled phone input values (such as location, attendeePhoneNumber, smsReminderNumber) are properly sanitized and immediately validated in all booking flows.
- The main change: Whenever a phone number is prefilled, internal formatting and validation are triggered automatically, so users no longer have to manually edit the phone field to resolve a “Invalid format” error.

## Motivation and Context

- Previously, phone numbers piped via query params (with or without +, %2B, spaces, etc.) appeared correctly in the field, but clicking “Confirm” immediately resulted in a validation error (“Invalid phone”).  
- It appeared as though the issue was extra spaces or formatting, but the real problem was **validation not running on prefilled values** until the user typed or edited the field.  
- This PR fixes that by ensuring sanitization and validation are triggered whenever a value is prefilled, making booking smooth for users who use prefilled phone fields.

## Visual Demo

> Please see the original issue and the demos below for before/after comparison.

**Before:**  
- Prefilled phone value visible  
- Clicking Confirm results in “Invalid phone”  
- User must manually edit the field to submit  
- [Before fix video](https://drive.google.com/file/d/1Z4XCwuthUuNRf-5xtUC5-ynWbfuBE7xm/view?usp=drive_link)

**After:**  
- Prefilled phone value visible  
- Clicking Confirm submits successfully if the number is valid; no manual edit required  
- [After fix video](https://drive.google.com/file/d/12uRutCYqlebNUV5bUsqxv2O0tRQj8PK_/view?usp=drive_link)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code.
- [x] N/A — No developer docs update required for this fix.
- [x] Manual testing: Validated local and staging booking flows with a variety of phone prefills; confirm that the validation and formatting work as expected.

## How should this be tested?

- Use a booking URL with phone, location, or smsReminderNumber params, including numbers with spaces and `+`/`%2B` prefixes.
- Try booking without manually editing the phone field.
- The booking should succeed if the number is valid and show an error only for truly invalid numbers.
- No form or input changes required from the user.

## Checklist

- [x] I have read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

---

## Additional notes

The original issue report focused on space/blank character causing validation failures.  
**In reality, the core problem was that the input’s validation was not triggered on prefilled values.**  
This PR solves it by ensuring that the phone field runs internal validation and formatting immediately after prefill, not just after user input.

### CODE REVIEW

**Comment by kart1ka** [comment]
@Vibgitcode27 Thanks for the pr. Can you please address the coderabbit suggestions?

File: packages/features/components/phone-input/PhoneInput.tsx [hunk 1]
```diff
@@ -31,6 +31,16 @@ function BasePhoneInput({
...
 
+  // This is to trigger validation on prefill value changes
+  useEffect(() => {
+    if (value) {
+      const sanitized = value.trim().replace(/\s+/g, "").replace(/^\+?/, "+");
+      if (value !== sanitized) {
+        onChange(sanitized);
+      }
+    }
+  }, []);
```
Comment (kart1ka) [inline packages/features/components/phone-input/PhoneInput.tsx]: As suggested by coderabbit, we already do use libphonenumber-js library for phone number validation. Could you please check if we can use that to perform phone number validation here?

**Review by kart1ka — DISMISSED** [review]
left a comment

File: packages/features/components/phone-input/PhoneInput.tsx (hunk 1 above)
Comment (Vibgitcode27) [reply packages/features/components/phone-input/PhoneInput.tsx]: I agree with CodeRabbit's suggestion. I implemented the regex approach for consistency since we already use similar logic in this component:

```tsx
value={value ? value.trim().replace(/^\+?/, "+") : undefined}
```

However, if you prefer using **libphonenumber-js**, I can implement it with `parseIncompletePhoneNumber` something like this:

```tsx
useEffect(() => {
  if (!value) return;

  const cleanedDigits = parseIncompletePhoneNumber(value);
  if (!cleanedDigits) return;

  const sanitized = cleanedDigits.startsWith("+") ? cleanedDigits : `+${cleanedDigits}`;
  if (value !== sanitized) {
    onChange(sanitized);
  }
}, []);
```

I have pushed the regex approach. if you think I should implement the other one, please let me know and I’ll do it quickly.

**Comment by Vibgitcode27** [comment]
@kart1ka  I’ve made the changes. Have a look whenever you get time.

**Comment by Vibgitcode27** [comment]
@kart1ka Can you review this?

**Comment by anikdhabal** [comment]
@coderabbitai could you pls review it once again?

**Review by anikdhabal — APPROVED** [review]
