### PR TITLE
fix: Calendar events attached to workflow emails are missing meeting url

### LINKED ISSUE #18194: Calendar events attached to workflow emails are missing title and meeting link
### Issue Summary

Calendar events attached to workflow emails are missing title and meeting link. Instead, it says "undefined" for the title.

### Steps to Reproduce

1. Create a booking link
2. Enable workflow emails for that booking link
3. Select the option "Include calendar event" for those workflow emails
4. Book a meeting through the link
5. Wait for the workflow email to come in

### Actual Results

The title and meeting link are missing from the calendar event. Instead, it says "undefined" for the title.

CleanShot 2024-12-15 at 13 23 43

### Expected Results

The calendar event should have the correct title and meeting link.

### Technical details

- Latest Firefox was used for the booking

### Evidence

Screenshot: see above

### PR DESCRIPTION
**Pull request by anikdhabal**
## What does this PR do?

- Fixes #18194 
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

### CODE REVIEW

**Comment by anikdhabal** [comment]
@nikwen Found the issue related to the location, but can't reproduce the undefined title bug. So let's merge this first, then I'll dive into the title issue.

File: packages/features/ee/workflows/api/scheduleEmailReminders.ts [hunk 1]
```diff
@@ -320,6 +320,7 @@ async function handler(req: NextApiRequest, res: NextApiResponse) {
               language: { translate: t, locale: booking.user?.locale ?? "en" },
             },
             attendees,
+            location: bookingMetadataSchema.parse(booking.metadata || {})?.videoCallUrl || booking.location,
```
Comment (nikwen) [inline packages/features/ee/workflows/api/scheduleEmailReminders.ts:323]: Given that the title works properly in the email content where it uses `reminder.booking.eventType?.title`, I wonder if the following would fix the title issue:

```suggestion
            location: bookingMetadataSchema.parse(booking.metadata || {})?.videoCallUrl || booking.location,
            title: booking.title || booking.eventType?.title || "",
```

Comment (anikdhabal) [reply packages/features/ee/workflows/api/scheduleEmailReminders.ts:323]: Yeah I was thinking the same. Let's do it and check

**Review by retrogtx — APPROVED** [review]

File: packages/features/ee/workflows/api/scheduleEmailReminders.ts [hunk 2]
```diff
@@ -320,6 +320,8 @@ async function handler(req: NextApiRequest, res: NextApiResponse) {
...
```
Comment (Udit-takkar) [inline packages/features/ee/workflows/api/scheduleEmailReminders.ts:323]: bookingMetadataSchema has ` .and(z.record(z.string()))`  so empty object won't parse successfully

Comment (anikdhabal) [reply packages/features/ee/workflows/api/scheduleEmailReminders.ts:323]: `z.object({ videoCallUrl: z.string().optional() })` allows an optional videoCallUrl property, meaning {} is valid

**Comment by rowansc1** [comment]
Thank you very, very much!

**Comment by nikwen** [comment]
Thank you, @anikdhabal!

Can you let me know when it's deployed to the live system? Then I'll test it there.

**Comment by rowansc1** [comment]
> Thank you, @anikdhabal!
> 
> 
> 
> Can you let me know when it's deployed to the live system? Then I'll test it there.

Likewise

**Comment by anikdhabal** [comment]
I will inform you here

**Comment by rowansc1** [comment]
@nikwen Its been merged in 😄

**Comment by nikwen** [comment]
@rowansc1 Thanks! I just scheduled a bunch of workflow emails that should come in over the next two days. Will let you know how it goes. :)

**Comment by rowansc1** [comment]
@nikwen No worries!
I've just been testing it. Now for some reason, although MS Teams **is 100%** selected in the meeting conferencing tool, and set as default everywhere. It seems to be sending a cal video invite instead! 
Y2qggU9yMq2Uwf22YotXOw3Th07v7Xci7F0
MbPwTuxGAeduYO32ZFbt8hOwlqEvOsd34v1
The link is a cal video link as well. How weird!

**Comment by nikwen** [comment]
@rowansc1 That's unlikely to be related to this PR. It only changed workflow emails.

**Comment by rowansc1** [comment]
@nikwen ah. I thought this resolved my previous issue of #18259

**Comment by anikdhabal** [comment]
@nikwen this is live now. Pls check it now

**Comment by nikwen** [comment]
@anikdhabal I've scheduled a ton of events. So far, all of them have had the correct meeting title and url. :tada:

I still have a bunch of additional events scheduled over the weekend. If anything goes wrong with those, I'll let you know, but so far it's looking good.

Thank you so much for your help! :pray:

**Comment by nikwen** [comment]
I can confirm that this is working great now. Thank you so much for your help, @anikdhabal!
