### PR TITLE
fix: use overflow-auto

### LINKED ISSUE #6285: [CAL-688] UI bug below filters
### Issue Summary

Screenshot 2023-01-05 at 5 54 12 PM

go to /booking pages ( /bookings/upcoming ) 

Browser: Brave [Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (arm64)](https://brave.com/latest/) 

<sub>[CAL-688](https://linear.app/calcom/issue/CAL-688/ui-bug-below-filters)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/6285

Screenshot 2023-01-06 at 2 54 52 AM

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by Udit-takkar** [comment]
Screenshot 2023-01-07 at 1 45 58 AM

TODO: filters are not working properly when content overflows.

**Comment by Udit-takkar** [comment]
https://user-images.githubusercontent.com/53316345/211097462-07250f34-1342-4ee6-badc-f7e31ac88505.mov

File: packages/features/bookings/components/FiltersContainer.tsx [hunk 1]
```diff
@@ -29,7 +29,7 @@ const filters: Filter[] = [
 
 export function FiltersContainer() {
   return (
-    <div className="flex w-full space-x-2 overflow-x-scroll rtl:space-x-reverse lg:justify-end ">
```
Comment (Udit-takkar) [inline packages/features/bookings/components/FiltersContainer.tsx:32]: had to use ml-auto instead of justify-end. justify-end did not work when filters were overflowing

**Review by PeerRich — APPROVED** [review]
works
