### PR TITLE
fix: Booking failures when there are no destination calendars but Google Meet location

### LINKED ISSUE #11573: [CAL-2535] "Could not book the meeting" when Google Meet is the location and there are no destination calendars
For an event-type with no destination calendar, for a user with no destination calendar, if location is set to Google Meet, bookings can’t be made.

image

<sub>[CAL-2535](https://linear.app/calcom/issue/CAL-2535/could-not-book-the-meeting-when-google-meet-is-the-location-and-there)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
Fixes #11573

Possible regression from #10967

### CODE REVIEW

File: packages/core/EventManager.ts [hunk 1]
```diff
@@ -119,8 +119,9 @@ export default class EventManager {
 
     // Fallback to Cal Video if Google Meet is selected w/o a Google Cal
     // @NOTE: destinationCalendar it's an array now so as a fallback we will only check the first one
-    const [mainHostDestinationCalendar] = evt.destinationCalendar ?? [];
-    if (evt.location === MeetLocationType && mainHostDestinationCalendar.integration !== "google_calendar") {
+    const [mainHostDestinationCalendar] =
+      (evt.destinationCalendar as [undefined | NonNullable<typeof evt.destinationCalendar>[number]]) ?? [];
```
Comment (hariombalhara) [inline packages/core/EventManager.ts:123]: We should enable `noUncheckedIndexedAccess` https://www.totaltypescript.com/tips/make-accessing-objects-safer-by-enabling-nouncheckedindexedaccess-in-tsconfig

**Review by CarinaWolli — APPROVED** [review]
