### PR TITLE
Fix for buffer not considering custom interval slots and event duration for slots when using custom intervals

### LINKED ISSUE #1871: Event Duration not Taken into Consideration When Offering Time Slots
### Issue Summary

Consider an event type with a _Duration_ of 60m and a _Time-slot Interval_ of 15m. This event type has a custom availability when ends at 11pm. The time slots that will be generated will go all the way until 10:45pm. If the duration were taken into account, the last slot would start at 10pm.

### Steps to Reproduce

Just follow the steps outlined in the previous section.

### LINKED ISSUE #2078: Bug in event buffer when used alongside custom slot intervals
### Issue Summary

Event buffer is not working well with slot intervals
```
I have a call scheduled from 12:50 to 13:50. Session duration is 60 minutes, minimum time before booking is 0 minutes, intevals are 5 minutes, buffer before call is 15 minutes. My availability is to 16:00.I would have expected bookings to be available from 14:05 (cause of the buffer before) up until 14:45 (cause buffer before plus meeting duration). But last booking available is 15:45 which doesn’t seem right if my availability ends at 16:00.Is there a misconception on my part?

```

### Steps to Reproduce

1. Block time between 12:50 and 13:50 or any other hour long timeslot (1 hour slots for the event-type as well)
2. Set before event Buffer to 15 mins
3. Add 5min interval

### PR DESCRIPTION
**Pull request by alishaz-polymath**
## What does this PR do?

- Updates buffer checks to consider custom interval slots
- Event Duration is now taken into consideration when offering Time Slots

Fixes #2078 
Fixes #1871 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [x] Add custom intervals (`Time-slot intervals`) for the event type and check the resulting time slots in the `/[user]/[type]` page in front end and ensure that the `final time slot + event length <= availability end time` for that day
- [x] Add buffer time (`before and/or after`) alongside the custom intervals and ensure in `/[user]/[type]` page in front end and ensure that the `final time slot + event length + any buffers <= availability end time` for that day
- [x] Add buffer time (`before and/or after`) alongside the custom intervals and visit the `/[user]/[type]` page in the front end, ensure that any bookable slots do not overlap with any busy event on that day when accounting the buffer time in the equation.

### CODE REVIEW

File: apps/web/lib/hooks/useSlots.ts [hunk 1]
```diff
@@ -118,51 +118,65 @@ export const useSlots = (props: UseSlotsProps) => {
       inviteeDate: date,
       workingHours: responseBody.workingHours,
       minimumBookingNotice,
+      eventLength,
     });
+    // const busyTimes = [
+    //   { start: new Date(2022, 2, 9, 12, 50, 0, 0), end: new Date(2022, 2, 9, 13, 50, 0, 0) },
+    // ];
```
Comment (alannnc) [inline apps/web/lib/hooks/useSlots.ts:125]: Don't forget to remove unused comments

File: apps/web/lib/hooks/useSlots.ts [hunk 2]
```diff
@@ -118,51 +118,65 @@ export const useSlots = (props: UseSlotsProps) => {
...
-        } else {
-          return true;
-        }
-        return false;
-      });
+      // Check if the final slot surpasses the availability end time
+      if (
+        times[i]
+          .add(eventLength + beforeBufferTime + afterBufferTime, "minutes")
+          .isAfter(finalizationTime, "minute")
```
Comment (alannnc) [inline apps/web/lib/hooks/useSlots.ts:133]: I would appreciate to see an explicit if/else if sentence, to me this looks like a if else hell.
`times[i]
          .add(eventLength + beforeBufferTime + afterBufferTime, "minutes")`
          as
 `currentTime.add(totalEventDurationMinutes, "minutes")`
 Or probably just short form 
 `if(currentEventWithTotalDuration.isAfter(finalizationTimeMinutes)`
I think we can increase declaration of constants but make our code more readable in this delicate operation

File: apps/web/lib/slots.ts [hunk 3]
```diff
@@ -15,26 +15,29 @@ export type GetSlots = {
...
+  eventLength: number;
 };
 export type WorkingHoursTimeFrame = { startTime: number; endTime: number };
 
 const splitAvailableTime = (
   startTimeMinutes: number,
   endTimeMinutes: number,
-  frequency: number
+  frequency: number,
+  eventLength: number
```
Comment (alannnc) [inline apps/web/lib/slots.ts:26]: frequency and eventLength are probably the same thing? I remember frequency was the event time duration in minutes

File: apps/web/lib/slots.ts [hunk 4]
```diff
@@ -15,26 +15,29 @@ export type GetSlots = {
...
 ): Array<WorkingHoursTimeFrame> => {
   let initialTime = startTimeMinutes;
   const finalizationTime = endTimeMinutes;
   const result = [] as Array<WorkingHoursTimeFrame>;
   while (initialTime < finalizationTime) {
     const periodTime = initialTime + frequency;
-    result.push({ startTime: initialTime, endTime: periodTime });
+    if (initialTime + eventLength <= finalizationTime)
```
Comment (alannnc) [inline apps/web/lib/slots.ts:33]: Here the same thing as above, explicit if conditionals
`if (currentTimePlusEventLength <= finalizationTime)`
Probably with a better name constant than the one I mentioned

File: apps/web/test/lib/slots.test.ts [hunk 5]
```diff
@@ -26,6 +26,7 @@ it("can fit 24 hourly slots for an empty day", async () => {
           endTime: MINUTES_DAY_END,
         },
       ],
+      eventLength: 60,
```
Comment (alannnc) [inline apps/web/test/lib/slots.test.ts:29]: We can add a test with different eventLengths just to try this

**Review by alannnc — CHANGES_REQUESTED** [review]

**Review by alannnc — COMMENTED** [review]
Let's do a test suite for buffered events ✋

File: apps/web/lib/slots.ts (hunk 3 above)
Comment (alishaz-polymath) [reply apps/web/lib/slots.ts:26]: No, frequency is the same as eventLength when the user isn't making use of custom interval for slots. They're different when the user makes use of `Time Slot Intervals`; frequency being the interval chosen while eventLength being the length of the event

File: apps/web/lib/hooks/useSlots.ts (hunk 2 above)
Comment (alishaz-polymath) [reply apps/web/lib/hooks/useSlots.ts]: Yeah, that's a good point. I think we can make this a tad more readable for other devs to make sense of it quicker.

**Comment by alishaz-polymath** [comment]
> Let's do a test suite for buffered events ✋

Added a couple of test cases in `test/lib/test.slot.ts` for future proofing

File: apps/web/test/lib/slots.test.ts (hunk 5 above)
Comment (alishaz-polymath) [reply apps/web/test/lib/slots.test.ts:30]: Added a test with different frequency and eventLength to showcase where they vary 😄

**Review by alannnc — APPROVED** [review]
It appears to be working properly now. Tested

**Review by PeerRich — APPROVED** [review]
good fix!

File: apps/web/lib/hooks/useSlots.ts [hunk 6]
```diff
@@ -34,6 +34,70 @@ type UseSlotsProps = {
...
+          times.splice(i, 1);
+        } else {
+          return true;
+        }
+        return false;
+      });
+    }
+  }
+  return times;
+};
```
Comment (alishaz-polymath) [inline apps/web/lib/hooks/useSlots.ts:99]: Created the `getFilteredTimes`  function with added consts for improved code readability and extracted it outside of useSlots function for easier test suite usage in `test/lib/slots.test.ts`

File: apps/web/lib/slots.ts [hunk 7]
```diff
@@ -15,26 +15,34 @@ export type GetSlots = {
...
+  eventLength: number;
 };
 export type WorkingHoursTimeFrame = { startTime: number; endTime: number };
 
 const splitAvailableTime = (
   startTimeMinutes: number,
   endTimeMinutes: number,
-  frequency: number
+  frequency: number,
+  eventLength: number
```
Comment (alishaz-polymath) [inline apps/web/lib/slots.ts:26]: `eventLength` can be different from `frequency` when custom slot intervals are used, and so, we need eventLength to ensure the final few slots don't allow their respective end time to be beyond the user's availability end time.

File: apps/web/lib/slots.ts [hunk 8]
```diff
@@ -15,26 +15,34 @@ export type GetSlots = {
...
   while (initialTime < finalizationTime) {
     const periodTime = initialTime + frequency;
-    result.push({ startTime: initialTime, endTime: periodTime });
+    const slotEndTime = initialTime + eventLength;
+    /*
+    check if the slot end time surpasses availability end time of the user 
+    1 minute is added to round up the hour mark so that end of the slot is considered in the check instead of x9
+    eg: if finalization time is 11:59, slotEndTime is 12:00, we ideally want the slot to be available
+    */
+    if (slotEndTime <= finalizationTime + 1) result.push({ startTime: initialTime, endTime: periodTime });
```
Comment (alishaz-polymath) [inline apps/web/lib/slots.ts:39]: We need to add `+1`  to make sure a slot isn't skipped because it was from `11:00`-`12:00` for example and the finalization time was 11:59 (basically end of the hour/day). This fetches the right/expected number of slots.

**Review by zomars — APPROVED** [review]

**Review by emrysal — APPROVED** [review]
Looks good :)
