### PR TITLE
fix: no feedback on buttons on /getting-started page.

### LINKED ISSUE #10061: [CAL-2145] /onboarding: No feedback on buttons in onboarding
After I click a button, it should show in loading state similar to other parts of the app

[https://github.com/calcom/cal.com/assets/8019099/52c75b87-3d4c-4878-b6e9-089213198104](https://github.com/calcom/cal.com/assets/8019099/52c75b87-3d4c-4878-b6e9-089213198104)

[Button Brief - Cal DS - Components (Figma)](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/Cal-DS---Components?type=design&node-id=309%3A42062&mode=dev)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2145](https://linear.app/calcom/issue/CAL-2145/onboarding-no-feedback-on-buttons-in-onboarding)</sub>

### PR DESCRIPTION
**Pull request by puru-khedre**
## What does this PR do?

This PR fixes the buttons feedback on the onboarding pages like `/getting-started/connected-calendar`

Fixes #10061

[Screencast from 2023-07-14 06-24-08.webm](https://github.com/calcom/cal.com/assets/101047627/6c68395c-db7a-4d24-b184-99e7e1b665c1)

## Type of change

  - [ ] Chore (refactoring code, technical debt, workflow improvements)
  - [x] Bug fix (non-breaking change which fixes an issue)
  - [ ] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - [ ] This change requires a documentation update

## Mandatory Tasks

  - [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: apps/web/components/getting-started/components/AppConnectionItem.tsx [hunk 1]
```diff
@@ -28,6 +28,7 @@ const AppConnectionItem = (props: IAppConnectionItem) => {
             color="secondary"
             disabled={installed}
             type="button"
+            loading={buttonProps?.isLoading || false}
```
Comment (sean-brydon) [inline apps/web/components/getting-started/components/AppConnectionItem.tsx:31]:
```suggestion
            loading={buttonProps?.isLoading}
```

**Review by sean-brydon — APPROVED** [review]
Thank you :)
