### PR TITLE
Fix/availability not loading

### LINKED ISSUE #7783: [CAL-1022] Availability keeps loading
[https://app.birdeatsbug.com/sessions/Y7bIA-JyBzGlyD4EBvywOtG4GKFqKuGMqFqOVjxiQcSH](https://app.birdeatsbug.com/sessions/Y7bIA-JyBzGlyD4EBvywOtG4GKFqKuGMqFqOVjxiQcSH)

Created via Threads. See full discussion: [https://threads.com/34447640469](https://threads.com/34447640469)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1022](https://linear.app/calcom/issue/CAL-1022/availability-keeps-loading)</sub>

### PR DESCRIPTION
**Pull request by joeauyeung**
## What does this PR do?

This PR fixes
- Endless loading on the availability page
- Fixes the default schedule not saving in the DB
- Handles if a user does not have any schedules

https://www.loom.com/share/dd7e533941f5418db5d2667b142ad8be

Fixes #7783

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Go to an event type page
- On the availability, the schedule should load
- Delete all schedules
- Go back to the availability page, you should have the option of creating a new schedule
- The new schedule should be your new default

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

File: apps/web/components/eventtype/AvailabilityTab.tsx [hunk 1]
```diff
@@ -52,23 +54,24 @@ const SingleValue = ({ ...props }: SingleValueProps<AvailabilityOption>) => {
...
   className = "",
+  isLoading,
+  schedules,
   ...props
 }: {
   className?: string;
   name: string;
   value: number;
+  isLoading: boolean;
+  schedules: RouterOutputs["viewer"]["availability"]["list"]["schedules"] | [];
```
Comment (joeauyeung) [inline apps/web/components/eventtype/AvailabilityTab.tsx:65]: Moved the query up a level to display the empty screen component if there are no schedules

File: apps/web/pages/availability/[schedule].tsx [hunk 2]
```diff
@@ -153,7 +154,7 @@ export default function Availability() {
 
   return (
     <Shell
-      backPath="/availability"
+      backPath={fromEventType ? true : "/availability"}
```
Comment (joeauyeung) [inline apps/web/pages/availability/[schedule].tsx:157]: If we create a new schedule from an event type, the back button should bring the user back to the event type.

File: packages/trpc/server/routers/viewer/availability.tsx [hunk 3]
```diff
@@ -201,9 +201,16 @@ export const availabilityRouter = router({
...
+
+        if (!user.defaultScheduleId) {
+          await prisma.user.update({
+            where: {
+              id: user.id,
+            },
+            data: {
+              defaultScheduleId: schedule.id,
+            },
+          });
```
Comment (joeauyeung) [inline packages/trpc/server/routers/viewer/availability.tsx:213]: This function returns the first schedule as the default if the user does not have one set. If this is the case then we should set that schedule as the default

Comment (emrysal) [reply packages/trpc/server/routers/viewer/availability.tsx:213]: Isn't this what setupDefaultSchedule did/does? 😕

File: packages/trpc/server/routers/viewer/availability.tsx [hunk 4]
```diff
@@ -247,7 +254,7 @@ export const availabilityRouter = router({
               id: user.id,
             },
             data: {
-              defaultScheduleId: scheduleToSetAsDefault?.id,
+              defaultScheduleId: scheduleToSetAsDefault?.id || null,
```
[the remark this answers is not in the document]
Comment (emrysal) [reply packages/trpc/server/routers/viewer/availability.tsx:257]: Good spot!

File: packages/trpc/server/routers/viewer/availability.tsx [hunk 5]
```diff
@@ -459,6 +467,11 @@ const getDefaultScheduleId = async (userId: number, prisma: PrismaClient) => {
     },
   });
 
+  await prisma.user.update({
```
Comment (emrysal) [inline packages/trpc/server/routers/viewer/availability.tsx:470]: An update in a getter is very unexpected, function probably needs renaming (or logic modified)

**Review by emrysal — CHANGES_REQUESTED** [review]

File: packages/trpc/server/routers/viewer/availability.tsx (hunk 3 above)
Comment (joeauyeung) [reply packages/trpc/server/routers/viewer/availability.tsx:213]: That's what I thought as well, but it wasn't triggering

Comment (joeauyeung) [reply packages/trpc/server/routers/viewer/availability.tsx:213]: Dug into it some more. It's because the getter always an id, either the user default id or the first schedule in the query. That means the update never triggered.

File: packages/trpc/server/routers/viewer/availability.tsx (hunk 5 above)
Comment (joeauyeung) [reply packages/trpc/server/routers/viewer/availability.tsx]: https://github.com/calcom/cal.com/pull/7789/commits/7b2881b1f487a24be560662cf0fe281c0a295f8f

File: packages/prisma/schema.prisma [hunk 6]
```diff
@@ -168,7 +168,7 @@ model User {
   teams                Membership[]
   bookings             Booking[]
   schedules            Schedule[]
-  defaultScheduleId    Int?
+  defaultScheduleId    Int
```
Comment (joeauyeung) [inline packages/prisma/schema.prisma]: Made optional in the next commit

**Review by emrysal — APPROVED** [review]
LGTM
