### PR TITLE
fix/duplicate-event-types

### LINKED ISSUE #5835: [CAL-524] Duplicating an event only duplicates the title & description
Duplicating an event should duplicate **all** settings.

Right now it's deceptive, you could duplicate an event thinking all settings are being passed over, but things like buffer limits and all other things are not copied over.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-524](https://linear.app/calcom/issue/CAL-524/duplicating-an-event-only-duplicates-the-title-and-description)</sub>

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

- Creates new Dialog for duplicating event types
- Creates TRPC duplicate for eventTypes mutation

## Loom
https://www.loom.com/share/30bb65dec37447c2b0113ca8b675d9d4

Fixes #5835 

**Environment**: Staging(main branch)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

- [ ] Click on action button for a single event type and Duplicate it
- [ ] Choose a new name and click on Continue
- [ ] Validate every config was duplicated for the event

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: apps/web/pages/event-types/index.tsx [hunk 1]
```diff
@@ -1,5 +1,4 @@
 import { useAutoAnimate } from "@formkit/auto-animate/react";
-import Head from "next/head";
```
Comment (alannnc) [inline apps/web/pages/event-types/index.tsx:2]: not being used

File: apps/web/pages/event-types/index.tsx [hunk 2]
```diff
@@ -175,22 +174,17 @@ export const EventTypeList = ({ group, groupIndex, readOnly, types }: EventTypeL
...
-      dialog: "new-eventtype",
-      eventPage: group.profile.slug,
-      title: type.title,
-      slug: type.slug,
-      description: type.description,
-      length: type.length,
-      type: type.schedulingType,
-      teamId: group.teamId,
-      locations: encodeURIComponent(JSON.stringify(type.locations)),
+      dialog: "duplicate-event-type",
```
Comment (alannnc) [inline apps/web/pages/event-types/index.tsx:180]: new dialog with form and specific action for use case

File: apps/web/pages/event-types/index.tsx [hunk 3]
```diff
@@ -175,22 +174,17 @@ export const EventTypeList = ({ group, groupIndex, readOnly, types }: EventTypeL
   }
 
   // inject selection data into url for correct router history
-  const openModal = (group: EventTypeGroup, type: EventType) => {
+  const openDuplicateModal = (eventType: EventType) => {
```
Comment (alannnc) [inline apps/web/pages/event-types/index.tsx:177]: Some times we are better off creating a single function for a specific use case that using one and if else everything

File: apps/web/public/static/locales/en/common.json [hunk 4]
```diff
@@ -1400,11 +1400,10 @@
   "add_one_fixed_attendee": "Add one fixed attendee and round robin through a number of attendees.",
   "calcom_is_better_with_team": "Cal.com is better with teams",
   "add_your_team_members": "Add your team members to your event types. Use collective scheduling to include everyone or find the most suitable person with round robin scheduling.",
-  "booking_limit_reached":"Booking Limit for this event type has been reached",
```
Comment (alannnc) [inline apps/web/public/static/locales/en/common.json:1403]: Duplicated from above

File: apps/web/public/static/locales/en/common.json [hunk 5]
```diff
@@ -1400,11 +1400,10 @@
...
-  "fill_this_field": "Please fill in this field",
   "options": "Options",
   "enter_option": "Enter Option {{index}}",
   "add_an_option": "Add an option",
   "radio": "Radio",
-  "kbar_search_placeholder" : "Start typing to search"
+  "kbar_search_placeholder": "Start typing to search",
+  "event_type_duplicate_copy_text": "{{slug}}-copy"
```
Comment (alannnc) [inline apps/web/public/static/locales/en/common.json:1408]: So we can to "event-slug-copy"

File: packages/trpc/server/routers/viewer/eventTypes.tsx [hunk 6]
```diff
@@ -99,6 +99,14 @@ const EventTypeUpdateInput = _EventTypeModel
       })
   );
 
+const EventTypeDuplicateInput = z.object({
+  id: z.number(),
+  slug: z.string(),
+  title: z.string(),
+  description: z.string(),
+  length: z.number(),
```
Comment (alannnc) [inline packages/trpc/server/routers/viewer/eventTypes.tsx:107]: This is all we need for duplicating and event, form inputs and we can get the rest from DB.

File: packages/trpc/server/routers/viewer/eventTypes.tsx [hunk 7]
```diff
@@ -603,4 +611,78 @@ export const eventTypesRouter = router({
...
+        team: true,
+        workflows: true,
+        webhooks: true,
+      },
+    });
+
+    if (!eventType) {
+      throw new TRPCError({ code: "NOT_FOUND" });
+    }
+    // Validate user is owner of event type or in the team
```
Comment (alannnc) [inline packages/trpc/server/routers/viewer/eventTypes.tsx:633]: TODO

File: packages/trpc/server/routers/viewer/eventTypes.tsx [hunk 8]
```diff
@@ -603,4 +611,93 @@ export const eventTypesRouter = router({
...
+          options: options ?? undefined,
+          ...rest,
+          eventTypeId: newEventType.id,
+        };
+      });
+      await ctx.prisma.eventTypeCustomInput.createMany({
+        data: customInputsData,
+      });
+    }
+
```
Comment (alannnc) [inline packages/trpc/server/routers/viewer/eventTypes.tsx:698]: @CarinaWolli Which can be the best way to clone/copy webhooks/workflows?

File: packages/trpc/server/routers/viewer/eventTypes.tsx (hunk 7 above)
Comment (harshsinghatz) [reply packages/trpc/server/routers/viewer/eventTypes.tsx:634]: Is this necessary? i am not able to think of a scenario where an user would be able to create an event that is not created by the user itself or it's members. Can you elaborate this?

Comment (harshsinghatz) [reply packages/trpc/server/routers/viewer/eventTypes.tsx:634]: Yeah, that makes a lot of sense, I will try to think about this more carefully in future PRs.
Thanks for explaining @alannnc.

Comment (alannnc) [reply packages/trpc/server/routers/viewer/eventTypes.tsx:634]: No worries, anytime. What you think about this new approach? It's cleaner IMO and if you can tell me if its working for you it will be a lot of help. @harshsinghatz

Comment (harshsinghatz) [reply packages/trpc/server/routers/viewer/eventTypes.tsx:634]: Sorry for late replies, our timezones don't match lol. Your notifications starts popping up when i am half asleep.
Regarding the approach I feel there are more duplications which would have been avoided but i think overall it's more readable.
Have you implemented it completely or is it still in progress?

Comment (alannnc) [reply packages/trpc/server/routers/viewer/eventTypes.tsx:634]: It's complete right now, obviously just missing webhooks/workflows. But we can add that later.

File: packages/trpc/server/routers/viewer/eventTypes.tsx (hunk 8 above)
Comment (CarinaWolli) [reply packages/trpc/server/routers/viewer/eventTypes.tsx:700]: For workflows, this worked for me: 
```
    const ids = _workflows.map(workflow => workflow.workflowId);
    const connectWorkflowIds = ids.map(id => { return {workflow: { connect: { id: id } } }});
    
        const data: Prisma.EventTypeCreateInput = {
      ...rest,
      title: newEventTitle,
      slug: newSlug,
      locations: locations ?? undefined,
      team: team ? { connect: { id: team.id } } : undefined,
      users: users ? { connect: users.map((user) => ({ id: user.id })) } : undefined,
      recurringEvent: recurringEvent || undefined,
      bookingLimits: bookingLimits ?? undefined,
      metadata: metadata === null ? Prisma.DbNull : metadata,
      workflows: {
        create: connectWorkflowIds,
      }
    };
```

**Review by zomars — APPROVED** [review]
LGTM
