### PR TITLE
fix: password not updatable after an api error

### LINKED ISSUE #8502: Forgot password form doesn't submit after entering error state
### Issue Summary

After attempting to reset password and getting the old value wrong, correcting the old value and hitting submit does nothing

### Steps to Reproduce

1. on self hosted app to go change password screen
2. type in same password in both boxes (old and new)
3. Hit submit -> error state on old password is incorrect
4. correct old password to current password
5. hit submit and nothing happens.

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

Fixes #8502 

[Screencast 2023-04-25 16:35:26.webm](https://user-images.githubusercontent.com/84864519/234259345-25d43c2b-df7f-4d1d-a015-06ad6b77f910.webm)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by PeerRich — APPROVED** [review]

File: packages/ui/components/form/inputs/Input.tsx [hunk 1]
```diff
@@ -348,7 +348,8 @@ const PlainForm = <T extends FieldValues>(props: FormProps<T>, ref: Ref<HTMLForm
           event.stopPropagation();
 
           if (form.formState?.errors?.apiError) {
-            form.clearErrors("root");
+            // @ts-expect-error FIXME Fix these typings
+            form.clearErrors("apiError");
```
Comment (hariombalhara) [inline packages/ui/components/form/inputs/Input.tsx:352]: Screenshot 2023-04-26 at 6 31 19 PM
This is a better place to handle `apiError` as it is added by Change Password logic and doesn't make sense in generic Input component.

I think we should remove the complete condition at line 350.

**Review by hariombalhara — CHANGES_REQUESTED** [review]
Left a comment. The change is pretty small that I requested.

**Comment by G3root** [comment]
@hariombalhara pushed those requested changes

**Review by hariombalhara — APPROVED** [review]
