### PR TITLE
fix: 'Hide from profile' toggle background not sized correctly on mobile

### LINKED ISSUE #21534: Fix "Hide from profile" toggle background not sized correctly on mobile devices
### Issue Summary

On mobile viewports, the background of the "Hide from profile" toggle button is not sized properly, resulting in a visual inconsistency that affects the mobile user experience.

### Steps to Reproduce

1. login to your account
2. Change viewports to mobile dimensions
3. toggle Hide from profile button

Toggle background is not fit correctly, leaving spaces from all sides except top

### PR DESCRIPTION
**Pull request by faizshaikh17**
## What does this PR do?

- Fixes #21534  (GitHub issue number)  
- Fixes CAL-5834 (Linear issue number)  
- Fixes the "Hide from profile" toggle button background sizing issue on mobile devices to remove unwanted gaps and improve UI consistency.

#### Image Demo:

- Side-by-side screenshots showing the toggle background before and after the fix on mobile viewports.
Screenshot 2025-05-26 221708
Screenshot 2025-05-27 010812

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code  
- [X]  N/A   
- [X] Test not required to check this fix

## How should this be tested?

- Log in to your account.  
- Change viewport to mobile dimensions (e.g., using browser dev tools).  
- Toggle the "Hide from profile" button.  
- Confirm the toggle background fits correctly without extra spacing.

## Checklist
  
- I haven't commented my code, particularly in hard-to-understand areas 

    

---

## Summary by cubic
Fixed the "Hide from profile" toggle background so it fits correctly on mobile, removing extra gaps and improving the UI.

### CODE REVIEW

File: packages/ui/components/dropdown/Dropdown.tsx [hunk 1]
```diff
@@ -39,7 +39,7 @@ export const DropdownMenuContent = forwardRef<HTMLDivElement, DropdownMenuConten
         {...props}
         sideOffset={sideOffset}
         className={classNames(
-          "shadow-dropdown bg-default border-subtle relative z-10 origin-top-right space-y-[1px] rounded-xl border p-1 text-sm",
+          "shadow-dropdown bg-default border-subtle relative z-10 origin-top-right space-y-[1px] rounded-xl border p-0.5 text-sm",
```
Comment (Udit-takkar) [inline packages/ui/components/dropdown/Dropdown.tsx:42]: No need to change padding here

Comment (faizshaikh17) [reply packages/ui/components/dropdown/Dropdown.tsx]: I have Changed padding to original.
any suggestions from your side

**Review by Udit-takkar — APPROVED** [review]

**Review by hbjORbj — APPROVED** [review]
Thanks for the fix!

**Comment by faizshaikh17** [comment]
your welcome!
