### PR TITLE
fix: modals regression

### LINKED ISSUE #10202: UI from modal windows look like out of the correct place
### Issue Summary

This is a UI issue. The position of the text and buttons for the modal windows look out of the correct place. Check the screenshots attached to see it better.

### Steps to Reproduce

1. Login using an incognito mode window
2. Walkthrough where these notifications can appear. E.g.: waiting for the `Update timezone` notification or going to disband a team
3. Observe the buttons

### Actual Results

  - Buttons and text are out of the correct place

### Expected Results

  - Buttons and text should be better positioned

### Technical details

  - Tested on `app.cal.dev`
  - Tested on: Firefox (v115.0.2) and Chrome (v114.0.5735.199)

### Evidence

image

image

image

image

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/10202
Regression from https://github.com/calcom/cal.com/pull/10020

Screenshot 2023-07-18 at 1 46 29 PM

Screenshot 2023-07-18 at 1 47 12 PM

Screenshot 2023-07-18 at 1 48 15 PM

## Type of change

  - [ ] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

- Go to /event-types. Click on new button
-  Click on delete event type /event-type options

## Mandatory Tasks

  - [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: packages/ui/components/dialog/Dialog.tsx [hunk 1]
```diff
@@ -148,7 +148,7 @@ export function DialogFooter(props: {
       <div
         className={classNames(
           "flex justify-end space-x-2 pb-4 pt-4 rtl:space-x-reverse",
-          props.showDivider && "-mb-4"
+          !props.showDivider && "pb-8"
```
Comment (Udit-takkar) [inline packages/ui/components/dialog/Dialog.tsx:151]: Modal without divider should have padding bottom 32px

Screenshot 2023-07-18 at 1 50 38 PM

**Review by sean-brydon — APPROVED** [review]
Thank you! well needed fix
