### PR TITLE
fix: confirm button not displayed

### LINKED ISSUE #8716: [CAL-1810] Confirm Button Missing
Found a bug? Please fill out the sections below. 👍

### Issue Summary
Unable to confirm new appointment requests. The only option is "reject"

Screenshot 2023-05-05 at 7 41 13 PM

<sub>[CAL-1810](https://linear.app/calcom/issue/CAL-1810/confirm-button-missing)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/8716

Private Thread:- https://threads.com/34477827999?s=9FjKrJDzzW4b6JAhEBynD3

- [ ] Need to test it locally 

**Environment**: Staging(main branch) / Production

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by PeerRich — APPROVED** [review]
great find

File: apps/web/components/booking/BookingListItem.tsx [hunk 1]
```diff
@@ -123,7 +123,8 @@ function BookingListItem(booking: BookingItemProps) {
       disabled: mutation.isLoading,
     },
     // For bookings with payment, only confirm if the booking is paid for
-    ...((isPending && !booking?.eventType?.price) || (!!booking?.eventType?.price && booking.paid)
+    ...((isPending && !booking?.eventType?.metadata?.apps?.stripe?.price) ||
+    (!!booking?.eventType?.metadata?.apps?.stripe?.price && booking.paid)
```
Comment (joeauyeung) [inline apps/web/components/booking/BookingListItem.tsx:127]: Sorry @Udit-takkar I should have been more specific. In the future, we can't assume all event types will use Stripe. I would look at the `getPaymentAppData` function to check if 1. A payment app is enabled, and 2. Seeing if there is a price set.

**Review by joeauyeung — CHANGES_REQUESTED** [review]

**Review by joeauyeung — APPROVED** [review]
Tested by:
- Enable the Stripe app
- Paying for a booking
- Under the booking page, the "confirm" button appears
- Disable the Stripe app
- Under that booking made, "confirm" still appears

Thanks for fixing this
