### PR TITLE
fix: Organization Signup when the username is already taken by someone else outside the organization

### LINKED ISSUE #13508: [CAL-3072] Error during signup through invite for organization
'A user exists with that username'

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3072](https://linear.app/calcom/issue/CAL-3072/error-during-signup-through-invite-for-organization)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #13508

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
- Create an org Org1(@org1.com)
- Invite teampro@org1.com
- Observe the error during signup. It happens because teampro is already taken outside the organization.
	- 	After the fix, user should be allowed to signup.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by hariombalhara** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #13506** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/13506?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/calcom/cal.com/13506?utm_source=stack-comment).

File: packages/lib/server/username.ts [hunk 1]
```diff
@@ -116,14 +116,82 @@ const usernameCheck = async (usernameRaw: string) => {
...
+  });
+
+  // We only need suggestedUsername if the username is not available
+  if (!response.available) {
+    response.suggestedUsername = await generateUsernameSuggestion(
+      users.map((user) => user.username).filter(notEmpty),
+      username
+    );
+  }
+
```
Comment (hariombalhara) [inline packages/lib/server/username.ts:157]: Reverted usernameCheck back to it's previous state and introduced `usernameCheckForSignup` for the signup specific use case where an already created user is being allowed to signup so that he can set his password. Note that the user is created as soon as he is invited.

**Review by PeerRich — APPROVED** [review]

**Review by exception — APPROVED** [review]

**Review by emrysal — APPROVED** [review]
Looking good to me :)
