### PR TITLE
fix: meeting ended incorrect content type

### LINKED ISSUE #12470: MEETING_ENDED webhook has incorrect content type
### Issue Summary

Our webhook endpoint checks for `content-type` to be `application/json` for `POST` requests. It caught an error for the cal.com `MEETING_ENDED` event where the POST request is incorrectly setting  `content-type = text/plain;charset=UTF-8` when in reality it is sending JSON data.

### Steps to Reproduce

1. Configure a `MEETING_ENDED` webhook.
2. Consume the webhook from an API.
3. Schedule an appointment and let it finish so the `MEETING_ENDED` event triggers your API.
4. See the incorrect `content-type` come in.

### Actual Results

- The `content-type` is `text/plain;charset=UTF-8` in the `MEETING_ENDED` event.

### Expected Results

- The `content-type` is `application/json` in the `MEETING_ENDED` event.

### Technical details

N/A

### Evidence

- This was tested through our own webhook integration.

### PR DESCRIPTION
**Pull request by Amit91848**
## What does this PR do?

Fixes #12470 
/claim #12470 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: packages/features/webhooks/lib/cron.ts [hunk 1]
```diff
@@ -27,6 +27,9 @@ async function handler(req: NextApiRequest, res: NextApiResponse) {
       await fetch(job.subscriberUrl, {
         method: "POST",
         body: job.payload,
+        headers: {
+          "Content-Type": "application/json",
```
Comment (CarinaWolli) [inline packages/features/webhooks/lib/cron.ts:31]: If payload is not json we should add `application/x-www-form-urlencoded` here instead

Same as here: https://github.com/calcom/cal.com/blob/main/packages/features/webhooks/lib/sendPayload.ts#L108




<br class="Apple-interchange-newline">

**Review by CarinaWolli — CHANGES_REQUESTED** [review]

**Comment by Amit91848** [comment]
Made changes @CarinaWolli

**Review by CarinaWolli — APPROVED** [review]
Looks good now! Thank you for your contribution 🙏
