### PR TITLE
fix: seats regression [CAL-2041]

### LINKED ISSUE #7967: [CAL-1351] Only one seat counts when two or more users books an event without occupied seats.
if more than one user books an event with seats, when there are no seats occupied yet, only 1 seat will count.

Steps to reproduce:

1. Create an event with seats
2. Choose in 2 different browser windows/tabs the same slot with all available seats.
3. Complete the reservation in the 2 tabs/windows
4. Return to the event type page, and you will see that only one seat es occupied.

I think it is because bookingUid is generated when the first booking occurs. then the others booking has the same uuid. But in this scenario, all the users who selected the slot before the uuid was generated, will generate a different one.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1351](https://linear.app/calcom/issue/CAL-1351/only-one-seat-counts-when-two-or-more-users-books-an-event-without)</sub>

### LINKED ISSUE #9749: Event with "Seats" leads to multiple calendar events and incorrect availability
### Issue Summary

I have an event with "Offer Seats" enabled : https://cal.com/mc/catan
(set to 7 seats and disabled "Share attendee info between guests")
image

When a new guest books the event, I receive a new calendar invite with a **different cal.video link** for each guest

I see 3 separate "Upcoming" bookings in my account for the same event:
image

On the booking page it shows "6 Available Seats" for that date
image

### Steps to Reproduce

1. Create event with seats and cal.video meeting location
2. As a guest book a seat
3. as another guest, book another seat
4. check booking page to see number of available seats (replicated if is total available - 1)
5. check calendar invites for links (replicated if links of two bookings are different)

Other info:
Event was created after June 14th

### LINKED ISSUE #9779: [CAL-2041] Fix seats feature regression on new booker
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2041](https://linear.app/calcom/issue/CAL-2041/fix-seats-feature-regression-on-new-booker)</sub>

### LINKED ISSUE #9942: Embed > Slot disappears if user cancels while booking
### Issue Summary

When a user selects a slot and decides to go back and cancel the booking process (before clicking on confirm), the slot disappears in the booking overview and cannot be booked. 

### Steps to Reproduce

1. Select slot (13:15) on embedded Cal.com booking page 
image

2. Clicked on "Cancel"
image
3.  13:15 slot is not available anymore, although booking process was cancelled
image

The slot will appear after approx. 10 mins. 

### Technical details

- Embed Cal.Com Javascript in Vue.JS application

### PR DESCRIPTION
**Pull request by joeauyeung**
## What does this PR do?

- Passes the proper seats data in the new booker component between states and to the backend

Fixes #9779
Fixes #9749
Fixes #7967 
Fixes #9942 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

**As the organizer** 
- Create a seated event type
- Book at least 2 seats
- Reschedule the booking
    - All attendees should be moved to the new booking
- Cancel the booking
    - The event should be cancelled for all attendees

**As an attendee**
- [x] Book a seated event
- [x] Reschedule that booking to an empty slot
    - [x] The attendee should be moved to that new slot
- [x] Reschedule onto a booking with occupied seats
    - [x] The attendees should be merged
- [x] On that slot reschedule all attendees to a new slot
    - [x] The former booking should be deleted
- [x] As the attendee cancel the booking
    - [x] Only that attendee should be removed 

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: packages/features/bookings/Booker/components/AvailableTimeSlots.tsx [hunk 1]
```diff
@@ -22,17 +22,32 @@ type AvailableTimeSlotsProps = {
...
 
+    if (seatsPerTimeSlot && seatsPerTimeSlot - attendees > 1) {
+      setSeatedEventData({
+        seatsPerTimeSlot,
+        attendees,
+        bookingUid,
+      });
+      return;
+    }
+
```
Comment (joeauyeung) [inline packages/features/bookings/Booker/components/AvailableTimeSlots.tsx:50]: @roae for your attention in regards to #9769

File: packages/features/bookings/Booker/Booker.tsx [hunk 2]
```diff
@@ -56,6 +56,11 @@ const BookerComponent = ({
     (state) => [state.selectedTimeslot, state.setSelectedTimeslot],
     shallow
   );
+  // const seatedEventData = useBookerStore((state) => state.seatedEventData);
+  const [seatedEventData, setSeatedEventData] = useBookerStore(
```
Comment (hariombalhara) [inline packages/features/bookings/Booker/Booker.tsx:60]: I think we are not initializing `seatedEventData` here https://github.com/calcom/cal.com/blob/f405ae5824bc0e0750b543ca2e67433077ca3690/packages/features/bookings/Booker/Booker.tsx#L83

This is the reason, when I am trying to a book a slot with 2 seats. 2 different bookings are being created.

**Review by hariombalhara — CHANGES_REQUESTED** [review]
2 seats are creating 2 bookings.

File: packages/features/bookings/Booker/components/EventMeta.tsx [hunk 3]
```diff
@@ -101,6 +106,31 @@ export const EventMeta = () => {
...
+              <EventMetaBlock
+                icon={User}
+                className={`${
+                  seatedEventData?.attendees || 0 / seatedEventData.seatsPerTimeSlot >= 0.5
+                    ? "text-rose-600"
+                    : seatedEventData?.attendees || 0 / seatedEventData.seatsPerTimeSlot >= 0.33
+                    ? "text-yellow-500"
+                    : "text-bookinghighlight"
+                }`}>
+                <div className="text-bookinghighlight flex items-start text-sm">
```
Comment (sean-brydon) [inline packages/features/bookings/Booker/components/EventMeta.tsx:119]: I don't think these text- colors exist anymore? Do they get added by embed @hariombalhara ?

File: packages/features/bookings/Booker/Booker.tsx (hunk 2 above)
Comment (joeauyeung) [reply packages/features/bookings/Booker/Booker.tsx:60]: How are you testing the PR? It's working properly for me.

In terms of setting `seatedEventData` I set it when a slot is selected because we won't know how many seats are available or the bookingUid on the initial load.

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 4]
```diff
@@ -1400,82 +1404,83 @@ async function handler(
...
+          return attendee.email !== bookerEmail;
+        });
+        await lastAttendeeDeleteBooking(originalRescheduledBooking, filteredAttendees, originalBookingEvt);
 
-      const foundBooking = await findBookingQuery(newTimeSlotBooking.id);
+        const foundBooking = await findBookingQuery(newTimeSlotBooking.id);
 
-      resultBooking = { ...foundBooking, seatReferenceUid: bookingSeat?.referenceUid };
+        resultBooking = { ...foundBooking, seatReferenceUid: bookingSeat?.referenceUid };
+      }
```
Comment (zomars) [inline packages/features/bookings/lib/handleNewBooking.ts:1483]: Is this change intended?

**Review by zomars — CHANGES_REQUESTED** [review]
Found unexpected behavior here:

> **As the organizer**
> 
> * Create a seated event type
> * Book at least 2 seats
> * Reschedule the booking
>   
>   * All attendees should be moved to the new booking

This only happens if done in the same browser. Tested like this:

- Book a seated event as attendee 1 in incognito browser A
- Book a seated event as attendee 2 in incognito browser B
- Check bookings page as organizer in logged in browser C

See that both bookings are treated as separate booking of the same events instead of the seats of the same booking

image

If as organizer I cancel/reschedule the first one then only that attendee is affected:

image

EDIT:

Added attendee3 in the same browser as attendee1 and still being treated as separate bookings.

image


<details>
<summary>Adding logs of this last attempt as well ⬇️</summary>

```
@calcom/web:dev: 15:56:59.002 ERROR [api] book:user Booking pro failed 
@calcom/web:dev: {
@calcom/web:dev:   errorCode: 'BookingCreatingMeetingFailed',
@calcom/web:dev:   message: 'Booking failed'
@calcom/web:dev: }
@calcom/web:dev: [
@calcom/web:dev:   {
@calcom/web:dev:     appName: 'Cal Video',
@calcom/web:dev:     type: 'daily_video',
@calcom/web:dev:     uid: 'gnStipPKEktU5n4x5d5TCK',
@calcom/web:dev:     originalEvent: {
@calcom/web:dev:       type: 'Seated event',
@calcom/web:dev:       title: 'Seated event between Pro Example and attenddee3',
@calcom/web:dev:       description: '',
@calcom/web:dev:       additionalNotes: '',
@calcom/web:dev:       customInputs: {},
@calcom/web:dev:       startTime: '2023-06-30T08:00:00Z',
@calcom/web:dev:       endTime: '2023-06-30T08:15:00Z',
@calcom/web:dev:       organizer: {
@calcom/web:dev:         id: 4,
@calcom/web:dev:         name: 'Pro Example',
@calcom/web:dev:         email: 'pro@example.com',
@calcom/web:dev:         username: 'pro',
@calcom/web:dev:         timeZone: 'Europe/London',
@calcom/web:dev:         language: {
@calcom/web:dev:           translate: [Function: fixedT] {
@calcom/web:dev:             lng: 'en',
@calcom/web:dev:             ns: 'common',
@calcom/web:dev:             keyPrefix: undefined
@calcom/web:dev:           },
@calcom/web:dev:           locale: 'en'
@calcom/web:dev:         },
@calcom/web:dev:         timeFormat: 'h:mma'
@calcom/web:dev:       },
@calcom/web:dev:       responses: {
@calcom/web:dev:         name: {
@calcom/web:dev:           label: 'your_name',
@calcom/web:dev:           value: 'attenddee3'
@calcom/web:dev:         },
@calcom/web:dev:         email: {
@calcom/web:dev:           label: 'email_address',
@calcom/web:dev:           value: 'attenddee3@example.com'
@calcom/web:dev:         },
@calcom/web:dev:         location: {
@calcom/web:dev:           label: 'location',
@calcom/web:dev:           value: undefined
@calcom/web:dev:         },
@calcom/web:dev:         notes: {
@calcom/web:dev:           label: 'additional_notes',
@calcom/web:dev:           value: undefined
@calcom/web:dev:         },
@calcom/web:dev:         guests: {
@calcom/web:dev:           label: 'additional_guests',
@calcom/web:dev:           value: []
@calcom/web:dev:         },
@calcom/web:dev:         rescheduleReason: {
@calcom/web:dev:           label: 'reason_for_reschedule',
@calcom/web:dev:           value: undefined
@calcom/web:dev:         }
@calcom/web:dev:       },
@calcom/web:dev:       userFieldsResponses: {},
@calcom/web:dev:       attendees: [
@calcom/web:dev:         {
@calcom/web:dev:           email: 'attenddee3@example.com',
@calcom/web:dev:           name: 'attenddee3',
@calcom/web:dev:           timeZone: 'America/Mazatlan',
@calcom/web:dev:           language: {
@calcom/web:dev:             translate: [Function: fixedT] {
@calcom/web:dev:               lng: 'es',
@calcom/web:dev:               ns: 'common',
@calcom/web:dev:               keyPrefix: undefined
@calcom/web:dev:             },
@calcom/web:dev:             locale: 'es'
@calcom/web:dev:           }
@calcom/web:dev:         }
@calcom/web:dev:       ],
@calcom/web:dev:       location: 'integrations:daily',
@calcom/web:dev:       destinationCalendar: null,
@calcom/web:dev:       hideCalendarNotes: false,
@calcom/web:dev:       requiresConfirmation: false,
@calcom/web:dev:       eventTypeId: 80,
@calcom/web:dev:       seatsShowAttendees: false,
@calcom/web:dev:       seatsPerTimeSlot: 4,
@calcom/web:dev:       uid: 'gnStipPKEktU5n4x5d5TCK',
@calcom/web:dev:       attendeeSeatId: 'a198ad9c-01fb-4546-b85c-a9038ef0b991'
@calcom/web:dev:     },
@calcom/web:dev:     success: false,
@calcom/web:dev:     createdEvent: undefined
@calcom/web:dev:   }
@calcom/web:dev: ]
```

</details>

File: apps/web/pages/reschedule/[uid].tsx [hunk 5]
```diff
@@ -12,14 +12,11 @@ export default function Type() {
...
-  const { uid: bookingId } = z
+  const { uid: bookingId, seatReferenceUid } = z
     .object({ uid: z.string(), seatReferenceUid: z.string().optional() })
     .parse(context.query);
-  let seatReferenceUid;
+
   const uid = await maybeGetBookingUidFromSeat(prisma, bookingId);
-  if (uid) {
-    seatReferenceUid = bookingId;
-  }
```
[the remark this answers is not in the document]
Comment (alannnc) [reply apps/web/pages/reschedule/[uid].tsx:22]: I think there was a reason for this but can't remember right now. Will debug to see if anything happens.

[the remark this answers is not in the document]
Comment (alannnc) [reply apps/web/pages/reschedule/[uid].tsx:22]: I think it was there because there is a time when rescheduling we don't share bookingUid with user only seatReferenceUid, so thats why we execute maybeGetBookingUidFromSeat and then we reassign values.

File: apps/web/components/booking/AvailableTimes.tsx [hunk 6]
```diff
@@ -167,10 +167,10 @@ const AvailableTimes: FC<AvailableTimesProps> = ({
                         {!!seatsPerTimeSlot && (
                           <p
                             className={`${
-                              slot.attendees && slot.attendees / seatsPerTimeSlot >= 0.8
-                                ? "text-rose-600"
-                                : slot.attendees && slot.attendees / seatsPerTimeSlot >= 0.33
+                              slot.attendees && slot.attendees / seatsPerTimeSlot >= 0.5
                                 ? "text-yellow-500"
+                                : slot.attendees && slot.attendees / seatsPerTimeSlot >= 0.33
+                                ? "text-rose-600"
```
Comment (alannnc) [inline apps/web/components/booking/AvailableTimes.tsx:173]: Color fixing, was red at first and then yellow. I think it should be yellow and finally when running out of seats.

File: apps/web/pages/new-booker/[user]/[type].tsx [hunk 7]
```diff
@@ -123,7 +127,9 @@ async function getUserPageProps(context: GetServerSidePropsContext) {
 
   let booking: GetBookingType | null = null;
   if (rescheduleUid) {
-    booking = await getBookingByUidOrRescheduleUid(`${rescheduleUid}`);
+    booking = await getBookingForReschedule(`${rescheduleUid}`);
+  } else if (bookingUid) {
+    booking = await getBookingForSeatedEvent(`${bookingUid}`);
```
Comment (alannnc) [inline apps/web/pages/new-booker/[user]/[type].tsx:132]: The logic here changed a little bit, if booking had bookingUid it was completely ignored. From now receiving it means that we have a seated event.
Receiving rescheduleUid means that we either received bookingUid or bookingSeatUid.

Comment (alannnc) [reply apps/web/pages/new-booker/[user]/[type].tsx:132]: I separated in two functions, bookingForReschedule returns current user data, while getting a booking from a seated event should only return attendees.length.

File: apps/web/pages/new-booker/d/[link]/[slug].tsx [hunk 8]
```diff
@@ -26,7 +26,7 @@ export default function Type({ slug, user, booking, away, isBrandingHidden, isTe
       <Booker
         username={user}
         eventSlug={slug}
-        rescheduleBooking={booking}
+        bookingData={booking}
```
Comment (alannnc) [inline apps/web/pages/new-booker/d/[link]/[slug].tsx:29]: Renaming happened here because we can have bookingData but it's not exclusive to a reschedule.

File: packages/features/bookings/Booker/Booker.tsx (hunk 2 above)
Comment (alannnc) [reply packages/features/bookings/Booker/Booker.tsx:65]: There is a time when you access directly to a booking form without seatedEventData in store, this is because you didn't select a timeslot which saves slot data to it.
I made some changes that when SSR loading bookingForm, bookingData should retrieve bookingAttendees length so we can use that for that scenario.

File: packages/features/bookings/Booker/components/EventMeta.tsx (hunk 3 above)
Comment (alannnc) [reply packages/features/bookings/Booker/components/EventMeta.tsx:124]: It looks like they still work? What should we update to? @sean-brydon

File: packages/features/bookings/Booker/components/EventMeta.tsx [hunk 9]
```diff
@@ -33,6 +39,10 @@ export const EventMeta = () => {
   if (hideEventTypeDetails) {
     return null;
   }
+  // If we didn't pick a time slot yet, we load bookingData via SSR so bookingData should be set
+  // Otherwise we load seatedEventData from useBookerStore
+  const bookingSeatAttendeesQty = seatedEventData?.attendees || bookingData?.attendees.length;
+  const eventTotalSeats = seatedEventData?.seatsPerTimeSlot || event?.seatsPerTimeSlot;
```
Comment (alannnc) [inline packages/features/bookings/Booker/components/EventMeta.tsx:45]: Important change, depends if you get here via time slot picking or via SSR direct page.

**Review by alannnc — COMMENTED** [review]
Made an update in the code that should load total seats number if using direct event page link with selected slot.

Missing from my POV:
- ~~Update seats test to use new booker~~
- ~~Update text- colors~~
- ~~Nit comments~~

Couldn't replicate @zomars comment and I think it should be ready to go.

File: packages/features/bookings/Booker/components/EventMeta.tsx (hunk 3 above)
Comment (hariombalhara) [reply packages/features/bookings/Booker/components/EventMeta.tsx:124]: Screenshot 2023-07-01 at 3 51 12 PM
They are used in Old Booker only. So, I would say just remove this class and see if anything breaks and if not then we are okay removing it.

File: packages/features/bookings/Booker/Booker.tsx (hunk 2 above)
Comment (hariombalhara) [reply packages/features/bookings/Booker/Booker.tsx:65]: @alannnc @joeauyeung Can I test it again now?

**Review by alannnc — DISMISSED** [review]
Made some changes and it should be good now.

**Review by zomars — CHANGES_REQUESTED** [review]
Can we fix checks?

File: apps/web/components/booking/AvailableTimes.tsx [hunk 10]
```diff
@@ -44,7 +44,15 @@ const AvailableTimes: FC<AvailableTimesProps> = ({
...
-  const reserveSlotMutation = trpc.viewer.public.slots.reserveSlot.useMutation();
+  const [isBlockedReserveSlot, setIsBlockedReserveSlot] = useState(false);
+  const reserveSlotMutation = trpc.viewer.public.slots.reserveSlot.useMutation({
+    onSuccess: () => {
+      setIsBlockedReserveSlot(false);
+    },
+    onError: () => {
+      setIsBlockedReserveSlot(false);
+    },
+  });
```
Comment (alannnc) [inline apps/web/components/booking/AvailableTimes.tsx:55]: Doing doble click on a slot could potentially mark it as double attendee.

File: apps/web/playwright/booking-seats.e2e.ts [hunk 11]
```diff
@@ -83,34 +83,55 @@ testBothBookers.describe("Booking with Seats", (bookerVariant) => {
...
-
-    // Kept in if statement here, since it's only temporary
-    // until the old booker isn't used anymore, and I wanted
-    // to change the test as little as possible.
-    // eslint-disable-next-line playwright/no-conditional-in-test
-    if (bookerVariant === "old-booker") {
-      await page.waitForURL((url) => {
-        return url.pathname.endsWith("/book");
-      });
-    }
```
Comment (alannnc) [inline apps/web/playwright/booking-seats.e2e.ts:96]: I was seeing that old booker doesn't do /book anymore

File: apps/web/playwright/booking-seats.e2e.ts [hunk 12]
```diff
@@ -83,34 +83,55 @@ testBothBookers.describe("Booking with Seats", (bookerVariant) => {
...
 
-    const bookingUrl = page.url();
+    let bookingUrl = "";
```
Comment (alannnc) [inline apps/web/playwright/booking-seats.e2e.ts:87]: Getting url when booking has already 1 attendee and it's passed on the url for the second attendee after selecting a  slot.

File: apps/web/playwright/booking-seats.e2e.ts [hunk 13]
```diff
@@ -83,34 +83,55 @@ testBothBookers.describe("Booking with Seats", (bookerVariant) => {
...
+      await expect(page.locator('[data-testid="time"][data-disabled="true"]')).toBeVisible();
+    });
+    await test.step("Attendee #3 cannot book the same seated event time slot accessing via url", async () => {
       await page.goto(bookingUrl);
+
       await bookTimeSlot(page, { email: "rick@example.com", name: "Rick" });
       await expect(page.locator("[data-testid=success-page]")).toBeHidden();
     });
+
+    await test.step("User owner should have only 1 booking with 3 attendees", async () => {
```
Comment (alannnc) [inline apps/web/playwright/booking-seats.e2e.ts:118]: @joeauyeung Here are the test you were looking for.

File: apps/web/playwright/booking-seats.e2e.ts [hunk 14]
```diff
@@ -231,6 +252,7 @@ testBothBookers.describe("Reschedule for booking with seats", () => {
 
     await expect(page).toHaveURL(/.*booking/);
 
+    await page.waitForTimeout(300);
```
Comment (alannnc) [inline apps/web/playwright/booking-seats.e2e.ts:255]: Looks like between page navigation and playwright execution I should sleep a little before getting data on the DB

File: apps/web/playwright/lib/testUtils.ts [hunk 15]
```diff
@@ -92,7 +92,9 @@ export async function selectFirstAvailableTimeSlotNextMonth(page: Page) {
   await page.waitForTimeout(1000);
   // TODO: Find out why the first day is always booked on tests
   await page.locator('[data-testid="day"][data-disabled="false"]').nth(1).click();
-  await page.locator('[data-testid="time"][data-disabled="false"]').nth(0).click();
+  // Changed to dblclick because of some flakiness when click a button animated
+  // It is said playwright should wait for animations to end, but it doesn't seem to be the case on this one
+  await page.locator('[data-testid="time"]').nth(0).dblclick();
```
Comment (alannnc) [inline apps/web/playwright/lib/testUtils.ts:97]: This should be improved, but I was getting error while using new booker looks like playwright can get it's right X,Y position because it's animated and doing one single click didn't work.
@joeauyeung @zomars

File: packages/features/bookings/lib/get-booking.ts [hunk 16]
```diff
@@ -161,3 +167,64 @@ export const getBookingByUidOrRescheduleUid = async (uid: string) => {
       : booking.attendees,
   };
 };
+
+/**
+ * Should only get booking attendees length for seated events
+ * @param uid
+ * @returns booking with masked attendee emails
+ */
+export const getBookingForSeatedEvent = async (uid: string) => {
```
Comment (alannnc) [inline packages/features/bookings/lib/get-booking.ts:176]: New function that should fetch booking considering data return for booking with seats

File: packages/features/bookings/lib/get-booking.ts [hunk 17]
```diff
@@ -161,3 +167,64 @@ export const getBookingByUidOrRescheduleUid = async (uid: string) => {
...
+    customInputs: null,
+    responses: {},
+    smsReminderNumber: null,
+    location: null,
+    // mask attendee emails for seated events
+    attendees: booking.attendees.map((attendee) => ({
+      ...attendee,
+      email: "",
+      name: "",
+      bookingSeat: null,
```
Comment (alannnc) [inline packages/features/bookings/lib/get-booking.ts:226]: Always hide current attendees

File: packages/features/bookings/lib/handleNewBooking.ts (hunk 4 above)
Comment (alannnc) [reply packages/features/bookings/lib/handleNewBooking.ts:1483]: @joeauyeung

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 18]
```diff
@@ -1626,6 +1631,7 @@ async function handler(
     return resultBooking;
   };
   // For seats, if the booking already exists then we want to add the new attendee to the existing booking
+  // This also means if booker doesn't sends bookingUid it will create a separate booking
```
Comment (alannnc) [inline packages/features/bookings/lib/handleNewBooking.ts:1634]: I might be wrong on this but looks like new booker or handleNewBooking doesn't check if there is already a booking created with same start end date? I saw a bug on that recently.
@joeauyeung @zomars

Comment (emrysal) [reply packages/features/bookings/lib/handleNewBooking.ts:1619]: It does after the date range overhaul; a busy time would be excluded within the date ranges so would prevent the booking.

File: apps/web/playwright/booking-seats.e2e.ts (hunk 14 above)
Comment (emrysal) [reply apps/web/playwright/booking-seats.e2e.ts:255]: This is flaky, instead consider waitForURL

File: packages/features/bookings/lib/handleNewBooking.ts (hunk 18 above)
Comment (alannnc) [reply packages/features/bookings/lib/handleNewBooking.ts:1619]: Awesome @emrysal, will remove comment now
```suggestion
```

File: packages/features/bookings/lib/handleNewBooking.ts (hunk 4 above)
Comment (joeauyeung) [reply packages/features/bookings/lib/handleNewBooking.ts:1468]: I changed some of the logic flow. This changed how these lines were nested so the spaces were added by the linter.

File: packages/features/bookings/lib/get-booking.ts (hunk 17 above)
Comment (joeauyeung) [reply packages/features/bookings/lib/get-booking.ts:226]: Do we want to create a conditional where if `showAttendees` is true, then include the attendee name and emails? This is what we already show on the success page.

File: apps/web/playwright/lib/testUtils.ts (hunk 15 above)
Comment (joeauyeung) [reply apps/web/playwright/lib/testUtils.ts:97]: Can we artificially wait a few seconds or wait for an element to be rendered?

**Review by ericrommel — CHANGES_REQUESTED** [review]
After booking just 1 seat for a given date/time, all other ones are unavailable.

https://github.com/calcom/cal.com/assets/10250819/579207f9-a9ea-4c4e-9e87-2c0204e0d27c

**Comment by alannnc** [comment]
> After booking just 1 seat for a given date/time, all other ones are unavailable.

Looks like it's related to latest slots availabilities changes in main.

I just added some slot reservations fixes and test. Will add some fix and test for that scenario from your video soon. @ericrommel

File: apps/web/pages/reschedule/[uid].tsx [hunk 19]
```diff
@@ -76,7 +77,9 @@ export async function getServerSideProps(context: GetServerSidePropsContext) {
 
   return {
     redirect: {
-      destination: `/${eventPage}?${destinationUrl.toString()}`,
+      destination: `/${eventPage}?${destinationUrl.toString()}${
+        eventType.seatsPerTimeSlot ? "&bookingUid=null" : ""
+      }`,
```
Comment (joeauyeung) [inline apps/web/pages/reschedule/[uid].tsx:82]: Noticed that you would have to double click on a timeslot when `bookingUid` was not already in the URL params. Also setting to null as "" was not valid and messing with getting the URL params.

**Review by hariombalhara — CHANGES_REQUESTED** [review]
@joeauyeung I have fixed the 2 tests that were failing wrongly. But there seems to be a genuine failure where a 2 seated event timeslot even after booked is still bookable
image

**Comment by ericrommel** [comment]
> After booking just 1 seat for a given date/time, all other ones are unavailable.
> 
>  BookOneSeatGettingAll.mp4

This is fixed

**Review by ericrommel — DISMISSED** [review]
LGTM

**Review by zomars — CHANGES_REQUESTED** [review]
Did the reschedule URL structure changed? It seems like it's breaking embed tests. cc @joeauyeung @hariombalhara 

image

File: apps/web/components/booking/AvailableTimes.tsx [hunk 20]
```diff
@@ -66,6 +74,10 @@ const AvailableTimes: FC<AvailableTimesProps> = ({
   );
 
   const reserveSlot = (slot: Slot) => {
+    if (isBlockedReserveSlot) {
```
Comment (zomars) [inline apps/web/components/booking/AvailableTimes.tsx:77]:
```suggestion
    if (isBlockedReserveSlot || reserveSlotMutation.isLoading) {
```

Comment (zomars) [reply apps/web/components/booking/AvailableTimes.tsx:77]: To prevent double calls

Comment (zomars) [reply apps/web/components/booking/AvailableTimes.tsx:77]: No need for extra state

File: apps/web/playwright/booking-pages.e2e.ts [hunk 21]
```diff
@@ -87,8 +86,11 @@ testBothBookers.describe("pro user", () => {
       const bookingId = url.searchParams.get("rescheduleUid");
       return !!bookingId;
     });
-    await selectSecondAvailableTimeSlotNextMonth(page);
-    // --- fill form
+    await selectFirstAvailableTimeSlotNextMonth(page);
+
+    await page.waitForLoadState("networkidle");
```
Comment (zomars) [inline apps/web/playwright/booking-pages.e2e.ts:91]: Ideally we wouldn't need for this

File: apps/web/playwright/booking-pages.e2e.ts [hunk 22]
```diff
@@ -87,8 +86,11 @@ testBothBookers.describe("pro user", () => {
...
+
+    await page.locator('[data-testid="confirm-reschedule-button"]').waitFor();
```
Comment (zomars) [inline apps/web/playwright/booking-pages.e2e.ts:93]: Playwright auto-waits for selector.s Is this really necessary?

**Review by zomars — COMMENTED** [review]
Some more comments 🙏

File: packages/lib/date-ranges.ts [hunk 23]
```diff
@@ -163,10 +163,13 @@ function getIntersection(range1: DateRange, range2: DateRange) {
...
 
-export function subtract(sourceRanges: DateRange[], excludedRanges: DateRange[]) {
+export function subtract(
+  sourceRanges: (DateRange & { [x: string]: unknown })[],
+  excludedRanges: DateRange[]
+) {
   const result: DateRange[] = [];
 
-  for (const { start: sourceStart, end: sourceEnd } of sourceRanges) {
+  for (const { start: sourceStart, end: sourceEnd, ...passThrough } of sourceRanges) {
```
[the remark this answers is not in the document]
Comment (joeauyeung) [reply packages/lib/date-ranges.ts:172]: @emrysal and I talked about this. We want to seated events to appear as a slot, but a calendar event from the seated event would block this. We decided that if there are still seats available, then remove any busy times that are in the same time as the booked seated event.

File: packages/trpc/server/routers/viewer/bookings/get.handler.ts [hunk 24]
```diff
@@ -284,6 +285,9 @@ export const getHandler = async ({ ctx, input }: GetOptions) => {
   );
 
   const bookings = bookingsQuery.map((booking) => {
+    if (booking.seatsReferences.length && !booking.eventType?.seatsShowAttendees) {
```
[the remark this answers is not in the document]
Comment (joeauyeung) [reply packages/trpc/server/routers/viewer/bookings/get.handler.ts:289]: If the event type is a seated event and we want to hide attendees, then filter out all attendees that are not the current user. The hosts are still able to see all attendees.

**Review by alannnc — DISMISSED** [review]
Fixed last bug on the UI, will leave the last approve to other one.

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 25]
```diff
@@ -1589,7 +1594,7 @@ async function handler(
         resultBooking["paymentUid"] = payment?.uid;
       }
 
-      resultBooking = { ...foundBooking, seatReferenceUid: evt.attendeeSeatId };
+      resultBooking = { ...resultBooking, seatReferenceUid: evt.attendeeSeatId };
```
Comment (joeauyeung) [inline packages/features/bookings/lib/handleNewBooking.ts:1597]: This spread operator didn't consider the `paymentUid` being added in the previous step.

File: packages/lib/date-ranges.ts (hunk 23 above)
[the remark this answers is not in the document]
Comment (emrysal) [reply packages/lib/date-ranges.ts:172]: Before seated events were part of the busy times, which we discussed and concluded that seated events that are not fully booked are not busy until they are fully booked. But the thing is that seated calendar events on connections are marked busy even for those not fully booked yet. This is why this is done, so we can re-use our subtraction logic to subtract our seated event from the reported busy times from the calendar connections.

File: apps/web/components/booking/AvailableTimes.tsx [hunk 26]
```diff
@@ -132,8 +136,20 @@ const AvailableTimes: FC<AvailableTimesProps> = ({
...
+                const isHalfFull =
+                  slot.attendees && seatsPerTimeSlot && slot.attendees / seatsPerTimeSlot >= 0.5;
+                const isNearlyFull =
+                  slot.attendees && seatsPerTimeSlot && slot.attendees / seatsPerTimeSlot >= 0.83;
+
+                const colorClass = isNearlyFull
+                  ? "text-rose-600"
+                  : isHalfFull
+                  ? "text-yellow-500"
+                  : "text-emerald-400";
```
Comment (sean-brydon) [inline apps/web/components/booking/AvailableTimes.tsx:152]: This is duplicated a lot - why dont we move this over to a cva style function to make this a lot more readable? 

CleanShot 2023-07-10 at 10 38 37@2x

CleanShot 2023-07-10 at 10 38 41@2x

File: apps/web/components/booking/AvailableTimes.tsx [hunk 27]
```diff
@@ -132,8 +136,20 @@ const AvailableTimes: FC<AvailableTimesProps> = ({
...
                 if (slot.attendees && seatsPerTimeSlot) slotFull = slot.attendees >= seatsPerTimeSlot;
-                if (slot.attendees && bookingAttendees && seatsPerTimeSlot)
+                if (slot.attendees && bookingAttendees && seatsPerTimeSlot) {
                   notEnoughSeats = slot.attendees + bookingAttendees > seatsPerTimeSlot;
+                }
+
+                const isHalfFull =
+                  slot.attendees && seatsPerTimeSlot && slot.attendees / seatsPerTimeSlot >= 0.5;
+                const isNearlyFull =
+                  slot.attendees && seatsPerTimeSlot && slot.attendees / seatsPerTimeSlot >= 0.83;
```
Comment (sean-brydon) [inline apps/web/components/booking/AvailableTimes.tsx:146]: This is duplicate a lot also- Why dont we calculate this higher up - maybe when slots are fetched we can do this calculation instead of doing it on every use case

Comment (zomars) [reply apps/web/components/booking/AvailableTimes.tsx:146]: A Nit for sure, but not a blocking one.

File: apps/web/pages/reschedule/[uid].tsx (hunk 19 above)
Comment (zomars) [reply apps/web/pages/reschedule/[uid].tsx:82]: Why do we need to set `&bookingUid=null` ? Is skipping it no enough?

File: apps/web/playwright/booking-pages.e2e.ts [hunk 28]
```diff
@@ -53,8 +52,8 @@ testBothBookers.describe("free user", (bookerVariant) => {
     // book same time spot again
     await bookTimeSlot(page);
 
-    // check for error message
-    await expect(page.locator("[data-testid=booking-fail]")).toBeVisible();
+    await page.locator("[data-testid=booking-fail]").waitFor();
```
Comment (zomars) [inline apps/web/playwright/booking-pages.e2e.ts:55]: Was auto wait failing or why do we need to explicitly wait here?

Comment (alannnc) [reply apps/web/playwright/booking-pages.e2e.ts:54]:
```suggestion
```

File: apps/web/pages/reschedule/[uid].tsx (hunk 19 above)
Comment (joeauyeung) [reply apps/web/pages/reschedule/[uid].tsx:82]: @alannnc we don't need this now after you found the fix?

File: packages/features/bookings/lib/handleNewBooking.ts (hunk 4 above)
Comment (zomars) [reply packages/features/bookings/lib/handleNewBooking.ts:1468]: Are you sure @joeauyeung? Seems like that bracket moved way down. I'm just trying to grasp if this is intentional.

image

Comment (joeauyeung) [reply packages/features/bookings/lib/handleNewBooking.ts:1468]: This change is intentional.

**Review by alannnc — DISMISSED** [review]
Made some fixes on recently failing test. Should be ok now

**Review by hariombalhara — COMMENTED** [review]
Unrelated bug found during testing
https://github.com/calcom/cal.com/issues/10057

**Review by hariombalhara — DISMISSED** [review]
LGTM!! Let's do it.
 [doit](https://app.graphite.dev/macros/calcom)

**Review by zomars — APPROVED** [review]
LGTM

**Review by emrysal — APPROVED** [review]
