### PR TITLE
fix: Hydration error in root layout

### LINKED ISSUE #20313: Hydration error in root layout
Fix a new hydration error 

Image

### PR DESCRIPTION
**Pull request by vijayraghav-io**
## What does this PR do?

- Fixes #20313 
- Fixes CAL-XXXX 

Fix by explicitly specifying default value for "visibility"

#### Image Demo (if applicable):

fix one of the new hydration error

Screenshot 2025-03-22 at 1 58 57 PM

**After fix:**

Screenshot 2025-03-22 at 2 06 14 PM

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] -N/A I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x]  - N/A I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

File: apps/web/app/layout.tsx [hunk 1]
```diff
@@ -150,7 +150,9 @@ export default async function RootLayout({ children }: { children: React.ReactNo
                 // - Tells iframe which mode it should be in (dark/light) - if there is a a UI instruction for that
                 visibility: "hidden",
               }
-            : {}
+            : {
+                visibility: "visible",
+              }
```
Comment (vijayraghav-io) [inline apps/web/app/layout.tsx:155]: Explicitly specifying default value for `visibility` to avoid hydration error.

**Review by TusharBhatt1 — APPROVED** [review]

**Comment by vijayraghav-io** [comment]
Thank you! @TusharBhatt1 🙏
