### PR TITLE
fix: Better UI for the setup page, When trying to reach an app that hasn't been already installed under an account 

### LINKED ISSUE #15973: The page needs a better UI When trying to reach an app that hasn't been already installed under an account
**Problem Description**
When trying to install/setup an app that hasn't already been installed in your account for example: cal.com/apps/make/setup 
You will see the page below. and i think it needs a little improvement.

calsetup

**Steps to reproduce**
head to cal.com/apps/<appname>/setup     

**Solution could be**
A centered avatar that could describe there is no such app, paragraph and a button to redirect to go to the appsotre.

### PR DESCRIPTION
**Pull request by Mihir867**
## What does this PR do?

I have updated the setup page for the /apps/make/setup as per the figma design

- FIxes #15973 

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- No
- What are the minimal test data to have?
- NA
- What is expected (happy path) to have (input and output)?
- On the route - /apps/make/setup
- Any other important info that could help to test that PR
- No

## Checklist
At first the page used to look like this - 

image

and now its looking as per the figma design - 

image

### CODE REVIEW

**Review by anikdhabal — COMMENTED** [review]
Pls uncommit the yarn.lock file

**Comment by Mihir867** [comment]
> Pls uncommit the yarn.lock file

Done, thanks for pointing out

File: packages/app-store/make/pages/setup/index.tsx [hunk 1]
```diff
@@ -133,12 +133,23 @@ export default function MakeSetup({ inviteLink }: InferGetServerSidePropsType<ty
...
+            <h2 className="mt-4 text-lg text-[##4B5563] ">{t("install_make_app")}</h2>
+
+            <div className="mt-5">
+              <Link href="/apps/make" passHref>
+                <Button className="border">
+                  {t("go_to_app_store")}
+                  <Icon name="arrow-up-right" />
+                </Button>
+              </Link>
+            </div>
```
Comment (anikdhabal) [inline packages/app-store/make/pages/setup/index.tsx:152]: Hey, thanks for the changes. There are a total of 4 places where you need to make similar changes, not only here. So, make sure to change them there as well

Comment (Mihir867) [reply packages/app-store/make/pages/setup/index.tsx:152]: Sure, will get it done

File: apps/web/public/static/locales/de/common.json [hunk 2]
```diff
@@ -1134,7 +1134,7 @@
   "zapier_setup_instructions": "<0>Loggen Sie sich in Ihr Zapier-Konto ein und erstelle einen neuen Zap.</0><1>Wählen Sie Cal.com als ihre Trigger-App aus. Wählen Sie auch ein Auslöserereignis.</0><1>Wählen Sie ihr Konto aus und geben dann ihren eindeutigen API-Key ein.</2><3>Testen Sie den Trigger.</3><4>Alles fertig!</4>",
   "make_setup_instructions": "<0>Gehen Sie zu: <1><0>Make-Einladungs-Link</0></1>und installieren Sie die Cal.com-App.</0><1> Loggen Sie sich in Ihr Make-Konto ein und erstellen Sie ein neues Szenario.</1><2>Wählen Sie Cal.com als ihre Auslöser-App aus. Wählen Sie auch ein Auslöserereignis aus.</2><3>Wählen Sie ihr Konto aus und geben Sie dann Ihren eindeutigen API-Key ein.</3><4>Probierne Sie den Auslöser aus.</4><5>Und fertig!</5>",
   "install_zapier_app": "Bitte installieren Sie zuerst die Zapier-App im App Store.",
-  "install_make_app": "Bitte installieren Sie zuerst die Make-App im App Store.",
+  "install_make_app": "Leider ist diese App nicht in Ihrem Konto installiert. Bitte besuchen Sie unseren App Store, um diese und andere tolle Apps zu erkunden und zu entdecken.",
```
Comment (anikdhabal) [inline apps/web/public/static/locales/de/common.json:1137]: We don't need to make changes in every locale; just make changes in locales/en. Also, refactor the current locale changes and create new key and value only inside locales/en

**Comment by anikdhabal** [comment]
> > Pls uncommit the yarn.lock file
> 
> Done, thanks for pointing out

Nah this is wrong, pls go the correct commit history then force push from local

**Review by anikdhabal — CHANGES_REQUESTED** [review]
Left some comments, pls address them

File: packages/app-store/make/pages/setup/index.tsx [hunk 3]
```diff
@@ -133,12 +133,23 @@ export default function MakeSetup({ inviteLink }: InferGetServerSidePropsType<ty
...
         </div>
       ) : (
-        <div className="ml-5 mt-5">
-          <div>{t("install_make_app")}</div>
-          <div className="mt-3">
-            <Link href="/apps/make" passHref={true} legacyBehavior>
-              <Button>{t("go_to_app_store")}</Button>
-            </Link>
+        // Updated UI changes
+        <div className="flex h-full w-full flex-col  items-center justify-center rounded-md bg-white p-10  text-black">
```
Comment (anikdhabal) [inline packages/app-store/make/pages/setup/index.tsx:137]: Also, pls remove the comment. No need to add

**Comment by Mihir867** [comment]
> div

Sure, I will create a new PR and link that one addressing all issues

**Comment by anikdhabal** [comment]
> > div
> 
> Sure, I will create a new PR and link that one addressing all issues

No need to create a new pr for now. Can you pls uncommit the lock file using the refrence that i've attach? then i will handle the reamining

**Comment by Mihir867** [comment]
Hey, I have did all the changes on the four pages and also committed back my yarn.lock file should I push now or it seems that you are handling this ?

File: packages/app-store/make/pages/setup/index.tsx (hunk 1 above)
Comment (anikdhabal) [inline packages/app-store/make/pages/setup/index.tsx:152]: Since this is used in 4 different components, it would be better to create a single component and pass the app name to it, instead of duplicating the same thing in 4 different places

**Comment by anikdhabal** [comment]
> I did, Thanks a lot for your help on this

Thanks for your work. I will handle the rest

File: packages/app-store/make/pages/setup/index.tsx (hunk 1 above)
Comment (Mihir867) [reply packages/app-store/make/pages/setup/index.tsx:152]: Sure will do it

Comment (anikdhabal) [reply packages/app-store/make/pages/setup/index.tsx]: Thanks for your work @Mihir867 , it needs some improvement. I will fix that

**Review by anikdhabal — DISMISSED** [review]
LGTM !!

**Review by Amit91848 — CHANGES_REQUESTED** [review]
Hey! Nice work @Mihir867. Can you sign the CLA https://github.com/calcom/cal.com/pull/16121#issuecomment-2273417816, or else we won't be able to merge this

I have made some changes as it was breaking on smaller screens, and included some refactor to remove hardcoded css.

**Comment by Mihir867** [comment]
> Hey! Nice work @Mihir867. Can you sign the CLA [#16121 (comment)](https://github.com/calcom/cal.com/pull/16121#issuecomment-2273417816), or else we won't be able to merge this
> 
> I have made some changes as it was breaking on smaller screens, and included some refactor to remove hardcoded css.

Yeah done, thanks :)

**Review by Amit91848 — APPROVED** [review]

**Review by anikdhabal — APPROVED** [review]
Thanks for your work @Mihir867
