### PR TITLE
fix: office365video expiry_date

### LINKED ISSUE #15264: [CAL-3837] Credential.Key error when booking
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Users can't book meetings

### **Steps** to Reproduce

1. 

### Actual Results

image

### Expected Results

* a successful booking

### Technical details

* happens on chrome, safari, brave on mobile, iPad and desktop

### Evidence

* tested on multiple devices as described above

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3837](https://linear.app/calcom/issue/CAL-3837/credentialkey-error-when-booking)</sub>

### PR DESCRIPTION
**Pull request by ibex088**
## What does this PR do?

- Fixes #15264 (GitHub issue number)
- Fixes CAL-3837 (Linear issue number - should be visible at the bottom of the GitHub issue description)

found out that the user had only one integration "office365_video"
I believe the problem arises because we are saving the `expiry_date` from `expires_in` and then deleting `expires_in`, as seen here: 
https://github.com/calcom/cal.com/blob/86fc5161b63848d02cbd8f8f928106ed01ed7b1b/packages/app-store/office365video/api/callback.ts#L75
However, the key actually appears in the responseBody "ext_expires_in" and "expires_in" both, as a result `ext_expires_in` was getting saved in the key attribute which throwing an error because we only allow expires_in key

https://github.com/calcom/cal.com/blob/6142287805b5c6a40e746126735745a5617334c7/packages/app-store/_utils/oauth/universalSchema.ts#L41

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

### CODE REVIEW

**Review by Udit-takkar — COMMENTED** [review]
@SomayChauhan changes look fine. Can we add a unit test for this?

**Comment by hariombalhara** [comment]
@SomayChauhan Could you share a loom/video of this issue being reproduced?  I don't fully understand what the exact issue was and how it fixes the issue.

You are suggesting that the error came because `ext_expires_in` wasn't deleted and it was saved in key which later on errors.

But universalSchema isn't strict and infact allows passing through all extra props that are not defined in it. So, what exactly is causing the error?
https://github.com/calcom/cal.com/blob/86fc5161b63848d02cbd8f8f928106ed01ed7b1b/packages/app-store/_utils/oauth/universalSchema.ts#L16

**Comment by SomayChauhan** [comment]
@hariombalhara You are right!!, it looks like this isn't the issue then 👍 
this was the actual error that we had
https://calcom.sentry.io/issues/5464897059/?alert_rule_id=12606822&alert_timestamp=1717937107264&alert_type=email&environment=vercel-production&notification_uuid=1c826837-6882-4544-8a58-8812b9089355&project=4504055091625984&referrer=alert_email

we checked our prod db for this user and found out that it had an `ext_expires_in` key which looked abnormal and kinda jumped to the conclusion that this would be causing the parse error since its not in the schema

I couldn't reproduce the issue on my account, it was more of a guesswork

**Comment by hariombalhara** [comment]
@SomayChauhan This is the log stream for the error. See if it helps https://app.axiom.co/cal-2e7u/stream/vercel?q=%7B%22children%22:%5B%7B%22field%22:%22message%22,%22op%22:%22contains%22,%22value%22:%22GoogleCalendarService-getTokenObjectFromCredential%22%7D%5D,%22field%22:%22%22,%22op%22:%22and%22%7D

It should tell you what exactly is wrong with payload

File: packages/app-store/_utils/oauth/getTokenObjectFromCredential.ts [hunk 1]
```diff
@@ -8,7 +8,7 @@ export function getTokenObjectFromCredential(credential: CredentialPayload) {
   const parsedTokenResponse = OAuth2TokenResponseInDbSchema.safeParse(credential.key);
 
   if (!parsedTokenResponse.success) {
-    logger.debug(
+    logger.error(
```
Comment (SomayChauhan) [inline packages/app-store/_utils/oauth/getTokenObjectFromCredential.ts:11]: changed it from  logger.debug to logger.error so that all such cases are logged

**Review by hariombalhara — APPROVED** [review]
