### PR TITLE
fix: Allow unpublished org to serve redirected links  plus other org onboarding fixes

### LINKED ISSUE #14453: [CAL-3367] Allow unpublished org events and routing forms to be served in case it has reached via redirect from old link(non-org regular link)
It is necessary now because we are allowing ADMINS to invite an existing user to an unpublished org which moves that user to the organization and redirects are setup from old links to org links

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3367](https://linear.app/calcom/issue/CAL-3367/allow-unpublished-org-events-and-routing-forms-to-be-served-in-case-it)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

If `orgRedirection=true` query param is present then we allow unpublished organization to have working events. That query param is added when page redirects from old non-org link to new org links.

More details here(Private Link): https://app.campsite.co/cal/posts/js7864jjvukc

- Fixes #14453 [Loom](https://www.loom.com/share/ef4d2c06a95543429f95a64125f3183f)
- It fixes the issue where we use app.cal.com link instead of acme.cal.com for an unpublished organization's teams.[Loom](https://www.loom.com/share/d04829ca6a58432e92c846195dc7820c)
- Private links also redirect to organization link now. It was made necessary with this PR, but it should have been done earlier as well.[Loom](https://www.loom.com/share/a4bbda4f3bd8499a9cb7b0aa7e390448)
- Fix links in email. They had double protocol in it.
- When admin created the organization, the `admin` username was being used instead of owner's username.
- Team members of the team chosen to move to the organization weren't automatically added because of the recent restriction we added on auto-add flow. Reverted that change. We have a 2 published teams paywall now which should make that change unnecessary.
- Untiked Team was also being moved. It is fixed now.
- Require 2 teams to be published to be able to create an organization in self-serve flow.

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
image

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: apps/web/lib/d/[link]/[slug]/getServerSideProps.tsx [hunk 1]
```diff
@@ -57,6 +59,19 @@ async function getUserPageProps(context: GetServerSidePropsContext) {
     return notFound;
   }
 
+  if (!org) {
```
Comment (hariombalhara) [inline apps/web/lib/d/[link]/[slug]/getServerSideProps.tsx:62]: Private link didn't have auto-redirect to organization setup

File: apps/web/lib/getTemporaryOrgRedirect.ts [hunk 2]
```diff
@@ -45,7 +45,9 @@ export const getTemporaryOrgRedirect = async ({
 
   // Use the first redirect origin as the new origin as we aren't supposed to handle different org usernames in a group
   const newOrigin = new URL(redirects[0].toUrl).origin;
-  const query = currentQueryString ? `?${currentQueryString}` : "";
+  const query = currentQueryString
```
Comment (hariombalhara) [inline apps/web/lib/getTemporaryOrgRedirect.ts:48]: When doing the org redirect add this param to convey that the page has been reached due to this reason.

File: apps/web/lib/org/[orgSlug]/[user]/getServerSideProps.tsx [hunk 3]
```diff
@@ -19,7 +19,17 @@ export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
     },
   });
   if (team) {
-    return GSSTeamPage({ ...ctx, query: { slug: ctx.query.user } });
+    return GSSTeamPage({
+      ...ctx,
```
Comment (hariombalhara) [inline apps/web/lib/org/[orgSlug]/[user]/getServerSideProps.tsx:23]: Don't know why but we are selectively sending query params here, we should make it so that it auto-forwards all params

File: apps/web/lib/team/[slug]/[type]/getServerSideProps.tsx [hunk 4]
```diff
@@ -72,6 +72,7 @@ export const getServerSideProps = async (context: GetServerSidePropsContext) =>
     eventSlug: meetingSlug,
     isTeamEvent: true,
     org,
+    fromRedirectOfNonOrgLink: context.query.orgRedirection === "true",
```
Comment (hariombalhara) [inline apps/web/lib/team/[slug]/[type]/getServerSideProps.tsx:75]: Convey that event request has been sent from redirected page of non-org link i.e. app.cal.com/teampro redirected to example.cal.com/teampro and event request is sent from that page.

File: apps/web/lib/team/[slug]/getServerSideProps.tsx [hunk 5]
```diff
@@ -78,26 +79,22 @@ export const getServerSideProps = async (context: GetServerSidePropsContext) =>
     return { notFound: true } as const;
   }
 
-  if (!team || (team.parent && !team.parent.slug)) {
+  if (!team) {
```
Comment (hariombalhara) [inline apps/web/lib/team/[slug]/getServerSideProps.tsx:82]: Separate a regular team and a sub-team handling. 
Because regular team would still remain unpublished always but sub team would depend on if it was redirected from nonOrgLink or not.

File: apps/web/lib/team/[slug]/getServerSideProps.tsx [hunk 6]
```diff
@@ -78,26 +79,22 @@ export const getServerSideProps = async (context: GetServerSidePropsContext) =>
...
       },
       include: {
         parent: {
           select: {
             id: true,
             slug: true,
             name: true,
-            isPrivate: true,
             isOrganization: true,
+            isPrivate: true,
```
Comment (hariombalhara) [inline apps/web/lib/team/[slug]/getServerSideProps.tsx:97]: TODO: Fix unnecessary reorder

File: packages/lib/event-types/getEventTypesByViewer.ts [hunk 7]
```diff
@@ -245,10 +245,11 @@ export const getEventTypesByViewer = async (user: User, filters?: Filters, forRo
           }
 
           const eventTypes = await Promise.all(team.eventTypes.map(mapEventType));
+          const teamParentMetadata = team.parent ? teamMetadataSchema.parse(team.parent.metadata) : null;
           return {
             teamId: team.id,
             parentId: team.parentId,
-            bookerUrl: getBookerBaseUrlSync(team.parent?.slug ?? null),
+            bookerUrl: getBookerBaseUrlSync(team.parent?.slug ?? teamParentMetadata?.requestedSlug ?? null),
```
Comment (hariombalhara) [inline packages/lib/event-types/getEventTypesByViewer.ts:252]: It fixes the issue where we use app.cal.com link instead of acme.cal.com for an unpublished organization's teams.

File: packages/app-store/routing-forms/pages/routing-link/getServerSideProps.ts [hunk 8]
```diff
@@ -25,11 +25,12 @@ export async function isAuthorizedToViewTheForm({
     ...user,
     metadata: userMetadata.parse(user.metadata),
   };
+  const orgSlug = formUser.profile.organization?.slug ?? formUser.profile.organization?.requestedSlug ?? null;
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/pages/routing-link/getServerSideProps.ts:28]: Allow serving on both unpublished and published scenarios.

File: packages/features/eventtypes/lib/getPublicEvent.ts [hunk 9]
```diff
@@ -289,10 +291,11 @@ export const getPublicEvent = async (
     profile: getProfileFromEvent(eventWithUserProfiles),
     users,
     entity: {
-      isUnpublished:
-        eventWithUserProfiles.team?.slug === null ||
-        eventWithUserProfiles.owner?.profile?.organization?.slug === null ||
-        eventWithUserProfiles.team?.parent?.slug === null,
+      considerUnpublished:
+        !fromRedirectOfNonOrgLink &&
```
Comment (hariombalhara) [inline packages/features/eventtypes/lib/getPublicEvent.ts:295]: Added just an AND with ` !fromRedirectOfNonOrgLink`

File: packages/emails/src/templates/OrganizationCreationEmail.tsx [hunk 10]
```diff
@@ -51,9 +51,9 @@ export const OrganizationCreationEmail = (
           lineHeightStep: "24px",
         }}>
         <Trans i18nKey="email|existing_user_added_link_changed">
-          Your link has been changed from <a href={`https://${prevLink}`}>{prevLinkWithoutProtocol}</a> to{" "}
-          <a href={`https://${newLink}`}>{newLinkWithoutProtocol}</a> but don&apos;t worry, all previous links
-          still work and redirect appropriately.
+          Your link has been changed from <a href={prevLink ?? ""}>{prevLinkWithoutProtocol}</a> to{" "}
+          <a href={newLink ?? ""}>{newLinkWithoutProtocol}</a> but don&apos;t worry, all previous links still
```
Comment (hariombalhara) [inline packages/emails/src/templates/OrganizationCreationEmail.tsx:55]: Protocol is already there.

File: packages/emails/src/templates/OrganizationCreationEmail.tsx [hunk 11]
```diff
@@ -68,7 +68,8 @@ export const OrganizationCreationEmail = (
           For personal events we recommend creating a new account with a personal email address.
           <br />
           <br />
-          Enjoy your new clean link: <a href={`https://${newLink}`}>{newLinkWithoutProtocol}</a>
+          Enjoy your new clean link:{" "}
+          <a href={`${newLink}?orgRedirection=true` ?? ""}>{newLinkWithoutProtocol}</a>
```
Comment (hariombalhara) [inline packages/emails/src/templates/OrganizationCreationEmail.tsx:72]: So that, from the link in email the link shows up as working(and not unpublished)

Comment (sean-brydon) [reply packages/emails/src/templates/OrganizationCreationEmail.tsx:72]: NIT: The "??" does nothing here right?

File: packages/emails/src/templates/TeamInviteEmail.tsx [hunk 12]
```diff
@@ -179,7 +178,8 @@ export const TeamInviteEmail = (
                   For personal events we recommend creating a new account with a personal email address.
                   <br />
                   <br />
-                  Enjoy your new clean link: <a href={`https://${newLink}`}>{newLinkWithoutProtocol}</a>
+                  Enjoy your new clean link:{" "}
+                  <a href={`${newLink}?orgRedirection=true` ?? ""}>{newLinkWithoutProtocol}</a>
```
Comment (sean-brydon) [inline packages/emails/src/templates/TeamInviteEmail.tsx:182]: Same here - i dont think ?? does anything

File: packages/emails/src/templates/OrganizationCreationEmail.tsx (hunk 11 above)
Comment (hariombalhara) [reply packages/emails/src/templates/OrganizationCreationEmail.tsx:72]: Yeah here it's redundant. I added ?orgRedirection=true later so missed this.

**Review by sean-brydon — APPROVED** [review]
Wow this is a impressive PR as usual

Tested:
* User profile page 
* Users event type page
* Dynamic groups between published orgs
* Dynamic groups between unpublished orgs
* Sub team profile -> /marketing -> redirection query param peresent
* Organization profile page -> acme.cal.local
* Private link page now showing orgRedirection query param and fixing the issue we had previosuly
* Booking succes flow

I didnt test links in email because my mailhog would not work for the life of me.
