### PR TITLE
Managed event-types

### LINKED ISSUE #6184: [CAL-648] Managed Event-Types by admins
Give a team admin the ability to manage event-types for its members, to facilitate having common event-types between all members. The admin-created event-types could be part of a new section in each member’s profile to distinguish event types created by the member and the ones created by the admin.

As a sales manager (admin), want to:

* Create an event type for my entire sales assistants (members) to be able to use as individuals.
* I want to create and edit once, and assign to many
* Their should be locked settings and unlocked settings
* Unlocked settings for a member would be:
  * set their own availability
  * connect their own calendar
  * connect their own conferencing app
* Locked settings would include
  * I think everything else.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-648](https://linear.app/calcom/issue/CAL-648/team-event-types-admin)</sub>

### LINKED ISSUE #7882: [CAL-1314] Teams: Member can't view an event type. Just get white screen
As a member of a team, I used to be able to view an event type (as readonly) but not update it. Now I get a white screen when I click in.

[https://share.cleanshot.com/tmZPzdsG](https://share.cleanshot.com/tmZPzdsG)

From Alex: "Seems like this is only happening on readonly members - but definitely a regression we used to be able to view as member, now it's a white page".

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1314](https://linear.app/calcom/issue/CAL-1314/teams-member-cant-view-an-event-type-just-get-white-screen)</sub>

### PR DESCRIPTION
**Pull request by leog**
### What does this PR do?
Implements managed event types for team admins.

### Loom 
 - **Rev 2:** https://www.loom.com/share/0a69563c402f4d3983d4a054e0edda64
 - **Original:** https://www.loom.com/share/da11df882d944e078d897e11207835c9

### Release plan
<table>
  <tr>
    <td>Version</td>
    <td>Description</td>
  </tr>
<tr>
  <td align="center">v1</td>
  <td>All event type configs including unlocked availability, destination calendar and location</td>
</tr>
<tr></tr>
<tr></tr>
<tr>
  <td align="center">v2</td>
  <td>Managed event types list from settings, new managed event type button from settings, Webhooks and Workflows</td>
</tr>
<tr></tr>
<tr>
  <td align="center">v3</td>
  <td>Apps (introducing read-only shared app credentials?)</td>
</tr>
</table>

### Use cases
 - Admin creates a managed event type for one team member without any specific unlocked field
 - Admin creates a managed event type for one team member with location set (plain)
 - Admin creates a managed event type for one team member with location set (not app installed)
 - Admin creates a managed event type for one team member with location set (app installed)
 - Admin creates a managed event type for one team member with availability set
 - Admin creates a managed event type for one team member with destination calendar set
 - Admin updates a managed event type changing a locked field
   - All other users should get this change
 - Admin updates a managed event type changing an unlocked field
   - Old users should get the change
   - New users should get the change
 - Admin creates a managed event type for himself/herself 

### Added unit tests
```bash
PASS @calcom/web apps/web/test/lib/handleChildrenEventTypes.test.ts (8.915 s)
  handleChildrenEventTypes
    Shortcircuits
      ✓ No managed event type (5 ms)
      ✓ No managed event metadata (6 ms)
      ✓ Missing event type (3 ms)
    Happy paths
      ✓ New users added (6 ms)
      ✓ Old users updated (5 ms)
      ✓ Old users deleted (6 ms)
      ✓ New, old and deleted users (9 ms)
```

### Known issues
 - Once members have been assigned and the event type was updated, preview link icons don’t show up as the shown list does not update accordingly once the form was successfully submitted 
 
### Fixed existent issue
 - Shown read-only event types had the link to edit page which resulted in blank page => removed edit menu option and clickable area

### Basic diagram
<a href="https://www.figma.com/file/HkwaSzwCCNpaiJplIzsTJW/Managed-Event-Types-by-Admin?node-id=1-84&t=TAddyrLql4RwxptE-4">Managed Event Types by Admin</a>

### Migration details
```diff
enum SchedulingType {
  ROUND_ROBIN @map("roundRobin")
  COLLECTIVE  @map("collective")
+  MANAGED     @map("managed")
}

model EventType {
  ...
+  parentId                Int?
+  parent                  EventType?              @relation("managed_eventtype", fields: [parentId], references: [id], onDelete: Cascade)
+  children                EventType[]             @relation("managed_eventtype")
  ...
  @@unique([userId, slug])
  @@unique([teamId, slug])
+  @@unique([userId, parentId])
}
```

#### Concepts
 - Along with children/parent relation between event types, users for an event type is also having their children user ids in order to show assigned members in the UI
 - The created managed event type by the team admin does not include a `userId` in order to allow the team admin to also be an assigned member if needed
 - A new metadata object is introduced, `managedEventConfig` in order to keep track of unlocked fields discretionally per member event type. Any change in the parent regarding unlocked events will need to be updated in children metadata.
 - Differences between parent and children are:
   -  parent has `SchedulingType = MANAGED`, `metadata.managedEventConfig` and `teamId`
   - children has `parentId`, `metadata.managedEventConfig` and `userId`

#### Main new files
 - `packages/lib/handleChildrenEventTypes.ts`: used only in `packages/trpc/server/routers/viewer/eventTypes.ts` update mutation is in charged to implement the user diff between the old state of the event type with the new state, in order to detect new, existent and deleted users
 - `packages/lib/LockedFieldsManager.tsx`: used mainly in event type config tabs, provide a way to abstract the logic to determine a field is disabled for a member or have a locked icon for both, admin and member, showing different tooltips to explain a fields will be locked for members (admin) or that the field was actually locked by admin (members)

#### Email notification
When a team admin assigns a member to an event type, and the member already has an event type with the same slug, the team admin is prompted to confirm they want to replace the member's event type with the managed one, for which a new email is triggered to be sent to the affected user. The following screenshot shows that email's content.

<kbd>image<kbd>

[See Figma Designs](https://www.figma.com/file/ZJNAFHCAq6rnuGRgUFxjzQ/Cal.com-Teams?node-id=698-108980)

Closes #6184 
Fixes #7882 

**Environment**: Staging(main branch) / Production

## Type of change

- [X] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by PeerRich** [comment]
excited for this!!

File: apps/web/components/eventtype/EventAdvancedTab.tsx [hunk 1]
```diff
@@ -10,6 +10,7 @@ import type { EventNameObjectType } from "@calcom/core/event";
 import { getEventName } from "@calcom/core/event";
 import DestinationCalendarSelector from "@calcom/features/calendars/DestinationCalendarSelector";
 import { FormBuilder } from "@calcom/features/form-builder/FormBuilder";
+import lockedFieldsManager from "@calcom/lib/LockedFieldsManager";
```
Comment (leog) [inline apps/web/components/eventtype/EventAdvancedTab.tsx:13]: New lib to let us operate with a managed event type or a children managed event type

File: apps/web/components/eventtype/EventAdvancedTab.tsx [hunk 2]
```diff
@@ -125,6 +127,7 @@ export const EventAdvancedTab = ({ eventType, team }: Pick<EventTypeSetupProps,
         <TextField
           label={t("event_name_in_calendar")}
           type="text"
+          {...shouldLockDisableProps("eventName")}
```
Comment (leog) [inline apps/web/components/eventtype/EventAdvancedTab.tsx:130]: This function returns `disabled` and `isLocked` properties for a given field name, `TextField` now supports `isLocked` to be able to show an indicator in the label, indicator that comes in the `isLocked` flag itself.

File: apps/web/components/eventtype/EventAdvancedTab.tsx [hunk 3]
```diff
@@ -163,6 +168,7 @@ export const EventAdvancedTab = ({ eventType, team }: Pick<EventTypeSetupProps,
         render={({ field: { value, onChange } }) => (
           <SettingsToggle
             title={t("disable_notes")}
+            {...shouldLockDisableProps("hideCalendarNotes")}
```
Comment (leog) [inline apps/web/components/eventtype/EventAdvancedTab.tsx:171]: This function returns `disabled` and `isLocked` properties for a given field name, `SettingsToggle ` now supports `disabled` and `isLocked` to be able to show an indicator in the label, indicator that comes in the isLocked flag itself.

File: apps/web/components/eventtype/EventAppsTab.tsx [hunk 4]
```diff
@@ -82,22 +97,24 @@ export const EventAppsTab = ({ eventType }: { eventType: EventType }) => {
...
-          {notInstalledApps?.map((app) => (
-            <EventTypeAppCard
-              getAppData={getAppDataGetter(app.slug as EventTypeAppsList)}
-              setAppData={getAppDataSetter(app.slug as EventTypeAppsList)}
-              key={app.slug}
-              app={app}
-              eventType={eventType}
-            />
-          ))}
+      {!appsLockedStatus.disabled && (
```
Comment (leog) [inline apps/web/components/eventtype/EventAppsTab.tsx:96]: We only show suggestions to install new apps if apps are not locked by a managed event type

File: apps/web/components/eventtype/EventAvailabilityTab.tsx [hunk 5]
```diff
@@ -52,43 +54,28 @@ const SingleValue = ({ ...props }: SingleValueProps<AvailabilityOption>) => {
...
-  value: number;
+  value: AvailabilityOption | undefined;
+  options: AvailabilityOption[];
+  isDisabled?: boolean;
   onBlur: () => void;
   onChange: (value: AvailabilityOption | null) => void;
 }) => {
-  const { data, isLoading } = trpc.viewer.availability.list.useQuery();
   const { t } = useLocale();
-
```
Comment (leog) [inline apps/web/components/eventtype/EventAvailabilityTab.tsx:65]: Moved one level up to be able to manipulate the options available and know it beforehand to show needed differences in the UI

File: apps/web/components/eventtype/EventLimitsTab.tsx [hunk 6]
```diff
@@ -78,6 +79,7 @@ const MinimumBookingNoticeInput = React.forwardRef<
       <div className="w-1/2 md:w-full">
         <InputField
           required
+          disabled={passThroughProps.disabled}
```
Comment (leog) [inline apps/web/components/eventtype/EventLimitsTab.tsx:82]: This was missing

File: apps/web/components/eventtype/EventLimitsTab.tsx [hunk 7]
```diff
@@ -94,6 +96,7 @@ const MinimumBookingNoticeInput = React.forwardRef<
       </div>
       <Select
         isSearchable={false}
+        isDisabled={passThroughProps.disabled}
```
Comment (leog) [inline apps/web/components/eventtype/EventLimitsTab.tsx:99]: This was missing

File: apps/web/components/eventtype/EventLimitsTab.tsx [hunk 8]
```diff
@@ -145,12 +148,20 @@ export const EventLimitsTab = ({ eventType }: Pick<EventTypeSetupProps, "eventTy
...
+
   return (
     <div className="space-y-8">
       <div className="space-y-4 lg:space-y-8">
         <div className="flex flex-col space-y-4 lg:flex-row lg:space-y-0 lg:space-x-4">
           <div className="w-full">
-            <Label htmlFor="beforeBufferTime">{t("before_event")} </Label>
+            <Label htmlFor="beforeBufferTime">
+              {t("before_event")}
+              {shouldLockIndicator("bookingLimits")}
```
Comment (leog) [inline apps/web/components/eventtype/EventLimitsTab.tsx:163]: This gets the locked indicator if the passed field name is actually locked, otherwise it doesn't return an object hence nothing is shown

File: packages/embeds/embed-react/playwright/config/playwright.config.ts [hunk 9]
```diff
@@ -1,4 +1,4 @@
-import { PlaywrightTestConfig, devices } from "@playwright/test";
+import type { PlaywrightTestConfig } from "@playwright/test";
```
Comment (leog) [inline packages/embeds/embed-react/playwright/config/playwright.config.ts:1]: Opened this file and showed an error for which just saving it converted this automatically.

File: apps/web/components/eventtype/EventAppsTab.tsx [hunk 10]
```diff
@@ -55,19 +56,39 @@ export const EventAppsTab = ({ eventType }: { eventType: EventType }) => {
     };
   };
 
+  const { shouldLockDisableProps, isManagedEventType, isChildrenManagedEventType } = lockedFieldsManager(
```
Comment (leog) [inline apps/web/components/eventtype/EventAppsTab.tsx:59]: Using the introduced locked fields manager

File: apps/web/pages/event-types/index.tsx [hunk 11]
```diff
@@ -115,30 +117,45 @@ const MobileTeamsTab: FC<MobileTeamsTabProps> = (props) => {
 const Item = ({ type, group, readOnly }: { type: EventType; group: EventTypeGroup; readOnly: boolean }) => {
   const { t } = useLocale();
 
-  return (
+  const content = () => (
```
Comment (leog) [inline apps/web/pages/event-types/index.tsx:120]: Refactored to be able to show it in two different cases below

File: apps/web/pages/event-types/index.tsx [hunk 12]
```diff
@@ -398,34 +429,40 @@ export const EventTypeList = ({ group, groupIndex, readOnly, types }: EventTypeL
...
-                                <EmbedButton
-                                  as={DropdownItem}
-                                  type="button"
-                                  StartIcon={FiCode}
-                                  className="w-full rounded-none"
-                                  embedUrl={encodeURIComponent(embedLink)}>
-                                  {t("embed")}
-                                </EmbedButton>
-                              </DropdownMenuItem>
+                              {!readOnly && (
```
Comment (leog) [inline apps/web/pages/event-types/index.tsx:432]: Fixes #7882

File: apps/web/pages/event-types/index.tsx [hunk 13]
```diff
@@ -115,30 +117,45 @@ const MobileTeamsTab: FC<MobileTeamsTabProps> = (props) => {
...
+      ) : null}
+      {readOnly && (
+        <Badge variant="gray" className="ml-2">
+          {t("readonly")}
+        </Badge>
+      )}
+    </div>
+  );
+
+  return readOnly ? (
```
Comment (leog) [inline apps/web/pages/event-types/index.tsx:144]: Fixes #7882

File: tests/config/singleton.ts [hunk 14]
```diff
@@ -1,5 +1,6 @@
-import { PrismaClient } from "@prisma/client";
-import { mockDeep, mockReset, DeepMockProxy } from "jest-mock-extended";
+import type { PrismaClient } from "@prisma/client";
+import type { DeepMockProxy } from "jest-mock-extended";
+import { mockDeep, mockReset } from "jest-mock-extended";
```
Comment (leog) [inline tests/config/singleton.ts:3]: Automatic code changes separating types from actual values.

File: packages/ui/components/form/switch/Switch.tsx [hunk 15]
```diff
@@ -31,7 +32,7 @@ const Switch = (
       <div className={classNames("flex h-auto w-auto flex-row items-center", fitToHeight && "h-fit")}>
         <PrimitiveSwitch.Root
           className={classNames(
-            props.checked ? "bg-gray-900" : "bg-gray-200",
+            props.checked ? (primitiveProps.disabled ? "!bg-gray-500" : "bg-gray-900") : "bg-gray-200",
```
Comment (leog) [inline packages/ui/components/form/switch/Switch.tsx:35]: Needed to accentuate the visual representation for a disabled toggle.

File: packages/ui/components/avatar/AvatarGroup.tsx [hunk 16]
```diff
@@ -26,35 +26,39 @@ export const AvatarGroup = function AvatarGroup(props: AvatarGroupProps) {
...
-          )}>
-          <span
-            className={classNames(
-              "m-auto px-1 text-center text-white",
-              props.size === "sm" ? "text-[12px]" : "text-2xl"
-            )}>
-            +{numTruncatedAvatars}
-          </span>
-        </li>
+    <>
```
Comment (leog) [inline packages/ui/components/avatar/AvatarGroup.tsx:29]: An empty <ul> was being added in case no avatar was in the list, fixed.

File: apps/web/components/eventtype/EventSetupTab.tsx [hunk 17]
```diff
@@ -157,13 +165,36 @@ export const EventSetupTab = (
       return true;
     });
 
+    const defaultValue = isManagedEventType
+      ? locationOptions.find((op) => op.label === t("default"))?.options[0]
```
Comment (leog) [inline apps/web/components/eventtype/EventSetupTab.tsx:169]: We need to show the inserted value at 0 (referencing user's default location) for a managed event

File: apps/web/components/eventtype/EventSetupTab.tsx [hunk 18]
```diff
@@ -157,13 +165,36 @@ export const EventSetupTab = (
...
+      : undefined;
+
+    const locationAvailable =
```
Comment (leog) [inline apps/web/components/eventtype/EventSetupTab.tsx:172]: This is to be able to know if the selected location is actually available as an option for the user, in order to show go install the app if not.

File: apps/web/components/eventtype/EventSetupTab.tsx [hunk 19]
```diff
@@ -157,13 +165,36 @@ export const EventSetupTab = (
...
+      eventType.locations &&
+      eventType.locations.length > 0 &&
+      locationOptions.some((op) => op.options.find((opt) => opt.value === eventType.locations[0].type));
+
+    const locationDetails = eventType.locations &&
```
Comment (leog) [inline apps/web/components/eventtype/EventSetupTab.tsx:177]: Very rudimentary way to come up with the selected location's name

File: apps/web/components/eventtype/EventTeamTab.tsx [hunk 20]
```diff
@@ -189,14 +261,19 @@ const Hosts = ({
                 />*/}
             </>
           ),
+          MANAGED: <></>,
```
Comment (leog) [inline apps/web/components/eventtype/EventTeamTab.tsx:264]: Necessary to avoid an error in the following line expecting to have all scheduling types covered.

**Comment by Jaibles** [comment]
Suggested edits for the email:
CleanShot 2023-03-23 at 12 44 55@2x

**Comment by leog** [comment]
> Suggested edits for the email

@Jaibles thanks Ciarán, how about these?

Regular event type delete dialog:
<kbd></kbd>

Managed event type delete dialog:
<kbd></kbd>

**Review by PeerRich — COMMENTED** [review]
not a fan of this

@Jaibles thoughts?
CleanShot 2023-03-23 at 21 49 06@2x

**Review by PeerRich — COMMENTED** [review]
amazing work! cant wait for this

File: apps/web/public/static/locales/en/common.json [hunk 21]
```diff
@@ -1451,6 +1467,11 @@
   "duration_limit_reached": "Duration Limit for this event type has been reached",
   "admin_has_disabled": "An admin has disabled {{appName}}",
   "disabled_app_affects_event_type": "An admin has disabled {{appName}} which affects your event type {{eventType}}",
+  "event_replaced_notice": "An admin has replaced one of your event types",
+  "email_subject_slug_replacement": "A team administrator has replaced your event /{{slug}}",
+  "email_body_slug_replacement_notice": "An administrator on the <strong>{{teamName}}</strong> team has replaced your event type <strong>/{{slug}}</strong> with a managed event type that they control.",
+  "email_body_slug_replacement_info": "Your link will continue to work but somesettings for it may have changed. You can review it in event types.",
```
Comment (CarinaWolli) [inline apps/web/public/static/locales/en/common.json:1473]:
```suggestion
  "email_body_slug_replacement_info": "Your link will continue to work but some settings for it may have changed. You can review it in event types.",
```

**Review by CarinaWolli — COMMENTED** [review]
User can enable their personal workflow on their managed event types and the managed event type can be set active on a team workflow as well. Should we disable that for now until v2? 
Screenshot 2023-03-28 at 11 36 41

**Review by zomars — COMMENTED** [review]
Partial review. Will continue tomorrow. Left some comments. Overall looks pretty good!. Nice job @leog 🙏🏽

File: packages/lib/LockedFieldsManager.tsx [hunk 22]
```diff
@@ -0,0 +1,58 @@
...
+
+const Indicator = (label: string) => (
+  <Tooltip content={<>{label}</>}>
+    <div className="ml-1 -mt-0.5 inline-flex h-4 w-4 rounded-sm bg-gray-100 p-0.5">
+      <FiLock className="h-3 w-3 text-gray-500 hover:text-black" />
+    </div>
+  </Tooltip>
+);
+
+const lockedFieldsManager = (
```
[the remark this answers is not in the document]
Comment (leog) [reply packages/lib/LockedFieldsManager.tsx]: Done

File: apps/web/components/eventtype/EventTypeSingleLayout.tsx [hunk 23]
```diff
@@ -80,12 +83,6 @@ function getNavigation(props: {
       icon: FiLink,
       info: `${duration} ${t("minute_timeUnit")}`, // TODO: Get this from props
     },
-    {
-      name: "availability",
```
[the remark this answers is not in the document]
Comment (leog) [reply apps/web/components/eventtype/EventTypeSingleLayout.tsx:84]: Yes, was moved later on to have data at hand to determine the info to be shown

**Comment by zomars** [comment]
Reviewing and testing...

File: packages/lib/telemetry.ts [hunk 24]
```diff
@@ -22,6 +22,7 @@ export const telemetryEventTypes = {
   website: {
     pageView: "website_page_view",
   },
+  slugReplacementAction: "slug_replacement_action",
```
Comment (zomars) [inline packages/lib/telemetry.ts:25]: What is this for?

File: packages/ui/components/editor/plugins/ToolbarPlugin.tsx [hunk 25]
```diff
@@ -384,7 +384,7 @@ export default function ToolbarPlugin(props: TextEditorProps) {
       editor.dispatchCommand(TOGGLE_LINK_COMMAND, null);
     }
   }, [editor, isLink]);
-  return (
+  return props.editable ? (
```
Comment (zomars) [inline packages/ui/components/editor/plugins/ToolbarPlugin.tsx:387]: [Prefer Early Returns](https://handbook.cal.com/engineering/best-practices/prefer-early-returns) 

```suggestion
  if (!props.editable) return  <></>
```

**Review by zomars — COMMENTED** [review]
Code looking good so far. Testing locally before final approval 🙏🏽

File: apps/web/pages/event-types/index.tsx (hunk 13 above)
Comment (CarinaWolli) [reply apps/web/pages/event-types/index.tsx:145]: Shouldn't we rather let the user open it to see all event-type details and just not allow editing? Can be done in a follow-up

File: packages/lib/telemetry.ts (hunk 24 above)
Comment (leog) [reply packages/lib/telemetry.ts:25]: See https://github.com/calcom/cal.com/pull/6876/files#diff-d75f96ff093473eefda3b50645504e299af40b26538bf2b235dc067293d3af2cR413

**Review by zomars — APPROVED** [review]
Tested locally and functionality seems to be solid. Nice work @leog I have some concerns to be addressed before merging tho.

From self-hosted perspective, can I opt-in to this feature? Should I? 

Is it unexpected for a team member if a team admin can suddenly replace their event types?

Would it make sense to put this feature behind a feature flag?

I'm assuming this is an enterprise feature. If that's the case, can we collocate most of the code in `@calcom/features/ee/managed-event-types`?

If yes, some good candidates for collocation would be:
- `@calcom/lib/hooks/useLockedFieldsManager`
- `apps/web/test/lib/handleChildrenEventTypes.test.ts`

**Comment by zomars** [comment]
Also, IMO since this affect the normal event type flow it should be helpful to have E2E tests in addition to the current unit tests.

**Comment by zomars** [comment]
Unit tests are failing as well

image

Also E2E although it seems unrelated to this PR

**Comment by zomars** [comment]
> Should I work on E2E as part of this PR or can be added as a follow-up?

In this PR would be desirable but I'll let you decide 🙏

**Comment by leog** [comment]
> In this PR would be desirable but I'll let you decide 🙏

@zomars done, better to don't put off till tomorrow what you can do today

**Comment by CarinaWolli** [comment]
@leog Users can still edit the time here: 
Screenshot 2023-04-11 at 17 09 05

File: packages/features/flags/hooks/index.ts [hunk 26]
```diff
@@ -1,6 +1,8 @@
 import { trpc } from "@calcom/trpc/react";
 
 export function useFlags() {
-  const query = trpc.viewer.features.map.useQuery(undefined, { initialData: {} });
+  const query = trpc.viewer.features.map.useQuery(undefined, {
+    initialData: process.env.NEXT_PUBLIC_IS_E2E ? { "managed-event-types": true, teams: true } : {},
```
Comment (zomars) [inline packages/features/flags/hooks/index.ts:5]: Clever

**Review by zomars — APPROVED** [review]
Ship it

**Comment by leog** [comment]
@zomars shouldn't we wait till the E2E tests are passing? don't want to break main, and not entirely sure why it fails, was hoping to get @hariombalhara's opinion

**Comment by zomars** [comment]
Do we know the reason it's failing? Seems safe to merge to me. We could follow to fix the test

**Comment by zomars** [comment]
@leog seems like we're hiding the embed button when is not a managed type which fails on e2e: 

Captura de pantalla 2023-04-11 a la(s) 14 58 19
