### PR TITLE
fix(ui): interface language toggle

### LINKED ISSUE #24367: The interface language in event type settings does not work; after saving.
### Issue Summary

https://www.loom.com/share/ae3a733acbea453cbac04b8142819da9?sid=af07b4fb-d33b-4d2c-8a60-bf8e86491d0a

Image

### PR DESCRIPTION
**Pull request by dhairyashiil**
## What does this PR do?

- Fixes #24367 
- Fixes CAL-6551 

## Visual Demo (For contributors especially)

https://github.com/user-attachments/assets/b23f4704-b1c9-425c-9a2b-3042b0034200

### CODE REVIEW

**Review by anikdhabal — DISMISSED** [review]

**Comment by IbrahimLoveForJS** [comment]
is it still available?

**Comment by anikdhabal** [comment]
@dhairyashiil the test is still failing, can you pls check and fix it

**Comment by dhairyashiil** [comment]
> @dhairyashiil the test is still failing, can you pls check and fix it

Thank you for mentioning it, I was unaware of this. I will resolve it.

**Comment by anikdhabal** [comment]
@dhairyashiil bump^^

File: packages/features/eventtypes/components/tabs/advanced/EventAdvancedTab.tsx [hunk 1]
```diff
@@ -434,9 +434,14 @@ export const EventAdvancedTab = ({
...
   );
+  const watchedInterfaceLanguage = formMethods.watch("interfaceLanguage");
   const [interfaceLanguageVisible, setInterfaceLanguageVisible] = useState(
-    !!formMethods.getValues("interfaceLanguage")
+    watchedInterfaceLanguage !== null && watchedInterfaceLanguage !== undefined
   );
+
+  useEffect(() => {
+    setInterfaceLanguageVisible(watchedInterfaceLanguage !== null && watchedInterfaceLanguage !== undefined);
+  }, [watchedInterfaceLanguage]);
```
Comment (anikdhabal) [inline packages/features/eventtypes/components/tabs/advanced/EventAdvancedTab.tsx:444]: Can you explain this change?

Comment (dhairyashiil) [reply packages/features/eventtypes/components/tabs/advanced/EventAdvancedTab.tsx:444]: We added this code to make sure the visibility of the interface language toggle always matches the real value in the form. Without it, the toggle could get out of sync, sometimes showing or hiding at the wrong time, because the form value doesn’t update instantly when the component first loads.
- _getValues() only reads the value once when the component starts, so it misses later updates._
- _watch() listens for changes, and useEffect reacts to those changes to update our local state (interfaceLanguageVisible)._

The useEffect checks whether the form value is null, "", or undefined:
- _null → feature is off, hide the toggle_
- _"" or "de", "es", etc. → feature on, show the toggle_
- _undefined → form not loaded yet, hide temporarily to avoid flicker_

This approach fixes:
- _The original bug (toggle disappearing after saving)._
- _The end-to-end (E2E) test failures caused by timing/sync issues._

watch() + useEffect keeps the toggle visibility perfectly in sync with the form, even during loading and saving.

**Review by anikdhabal — APPROVED** [review]
