### PR TITLE
fix: Organization's Team invite emails

### LINKED ISSUE #12804: [CAL-2811] Organization's Team invite email review and fixes
In the screenshot it shows email sent when an email was invited in a team(Engineering) of an organization(Org1)

* Subject is wrong - It should have said something like 'Engineering's admin invited you to join the team in Org1 organization'
* There are other similar discrepancies in the content

  @peer @ciaranha Need the copy from you for this.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2811](https://linear.app/calcom/issue/CAL-2811/organizations-team-invite-email-review-and-fixes)</sub>

### PR DESCRIPTION
**Pull request by ibex088**
## What does this PR do?

Fixes #12804

#### 1. invite a member to a organization and resend invite (no change)

* invite-to-org

#### 2. add a pending member to a sub-team (change)
* before
Screenshot from 2023-12-17 13-47-03

* after
Screenshot from 2023-12-17 13-06-15

#### 3. add a pending member to a sub-team and clicking on resend invite (change)
* before
Screenshot from 2023-12-17 13-48-13

* after
Screenshot from 2023-12-17 13-23-47

#### 4. invite a member to a subTeam directly (change)
* before
Screenshot from 2023-12-17 13-49-11

* after
Screenshot from 2023-12-17 13-14-38

#### 5. invite a member to a subTeam directly and click on resend invite from sub-team members page (change)

* before
Screenshot from 2023-12-17 13-49-11

* after
Screenshot from 2023-12-17 13-14-38

#### 1. invite a member to a Team directly and click on resend invite (no change)

* Screenshot from 2023-12-17 13-33-40

PS: 
* these are all the casses i could think of, that usses `team-invite-email` email template, however there maybe more that i could've missed, in that case do let me know.
* i have added only one case where the team has a parent and sending a slightly modified email in that case, and please review the language of the email as well, as I'm not very confident about it.
thank you.

### CODE REVIEW

File: packages/emails/src/templates/TeamInviteEmail.tsx [hunk 1]
```diff
@@ -12,24 +12,30 @@ type TeamInvite = {
   joinLink: string;
   isCalcomMember: boolean;
   isOrg: boolean;
+  parentTeamName: string | undefined;
```
Comment (hariombalhara) [inline packages/emails/src/templates/TeamInviteEmail.tsx:15]:
```suggestion
  parentTeamName?: string;
```
It makes more sense. As parentTeamName itself isn't undefined but the caller can choose to not pass this.

**Review by hariombalhara — APPROVED** [review]
@SomayChauhan Thanks and great work !!
