### PR TITLE
fix: #15857 add managed by tooltip

### LINKED ISSUE #15857: [CAL-4058] managed event types: hovering over "Managed" should show a <Tooltip>: "Managed by {NameOfAdmin}"
the "Managed" badge should have a tooltip

i.e.: "Managed by Peer Richelsen"

image

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4058](https://linear.app/calcom/issue/CAL-4058/managed-event-types-hovering-over-managed-should-show-a-tooltip)</sub>

### PR DESCRIPTION
**Pull request by vijayraghav-io**
## What does this PR do?

- Fixes #15857 
- Fixes CAL-4058

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by anikdhabal — COMMENTED** [review]
Great work @vijayraghav-io till now, type check and lint test are failing currently

File: packages/features/eventtypes/components/EventTypeDescription.tsx [hunk 1]
```diff
@@ -78,11 +81,21 @@ export const EventTypeDescription = ({
               </Badge>
             </li>
           )}
-          {eventType.metadata?.managedEventConfig && !isPublic && (
-            <Badge variant="gray" startIcon="lock">
-              {t("managed")}
-            </Badge>
-          )}
+          {eventType.metadata?.managedEventConfig &&
```
Comment (Ryukemeister) [inline packages/features/eventtypes/components/EventTypeDescription.tsx:84]: @vijayraghav-io can we not have this much nesting? Reason I say is because if someone in the future wants to add more logic to this it will get very messy very soon. I was thinking we have two variables, one for `isEventTypeManaged` and `isOwnerPresent` (the variables names can be more descriptive) and then we display component based on that.
```
const isEventTypeManaged = eventType.metadata?.managedEventConfig && !isPublic
const isOwnerPresent = !!eventType.teamAdmin 

if (isEventTypeManaged && isOwnerPresent) <>Render icon with tooltip here</>
if (isEventTypeManaged && !isOwnerPresent) <>Render just the icon</>
```
What do you think about this?

**Review by anikdhabal — COMMENTED** [review]
"Hey @vijayraghav-io, please clarify these points (I haven't looked at the code):

1. In a team, there are multiple owners, each with the ability to create managed event types and assign users. When hovering over the managed badge, which owner's name should be shown to the host? How do you determine whom to display?

2. An admin also has the ability to create a team-managed event. In this case, when hovering over the badge, should you display the owner's name or the admin's name for that particular event type? Note that there can be multiple admins. (Currently, only the owner's name is shown in the tooltip, but the issue suggests showing 'managed by admin'.)

3. Shouldn't we also display the tooltip for event types in the team event section? (Currently not visible)

**Comment by vijayraghav-io** [comment]
> Great work @vijayraghav-io till now, type check and lint test are failing currently

Thankyou! @anikdhabal , updated for type and lint checks

**Comment by vijayraghav-io** [comment]
I guess for multiple admins, its better to show comma separated, thereby we are showing all admins in tooltip. Updated for this.

**Comment by anikdhabal** [comment]
> "Hey @vijayraghav-io, please clarify these points (I haven't looked at the code):
> 
> 1. In a team, there are multiple owners, each with the ability to create managed event types and assign users. When hovering over the managed badge, which owner's name should be shown to the host? How do you determine whom to display?
> 2. An admin also has the ability to create a team-managed event. In this case, when hovering over the badge, should you display the owner's name or the admin's name for that particular event type? Note that there can be multiple admins. (Currently, only the owner's name is shown in the tooltip, but the issue suggests showing 'managed by admin'.)
> 3. Shouldn't we also display the tooltip for event types in the team event section? (Currently not visible)

@PeerRich can you clear this?

**Comment by vijayraghav-io** [comment]
**Single admin :**

Screenshot 2024-07-22 at 7 29 59 PM



**Multiple admins:**

Screenshot 2024-07-22 at 7 27 55 PM

**Comment by anikdhabal** [comment]
> **Single admin :**
> 
> Screenshot 2024-07-22 at 7 29 59 PM
> **Multiple admins:**
> 
> Screenshot 2024-07-22 at 7 27 55 PM

So, for team event types, we set the owner for each event type to undefined, unlike for personal event types. This problem will be fixed if we set the owner for team event types as well. However, it's generally not to set the owner of an event type, especially for a team event type. Need a review on this from others.

File: packages/features/eventtypes/components/EventTypeDescription.tsx (hunk 1 above)
Comment (vijayraghav-io) [reply packages/features/eventtypes/components/EventTypeDescription.tsx:82]: I feel instead of having multiple conditions, this is more readable.

**Comment by anikdhabal** [comment]
@hariombalhara needs your thoughts here

**Comment by anikdhabal** [comment]
@vijayraghav-io, there is always confusion about whether to show the team owner’s or admin’s name. If we display a comma-separated list of names, the tooltip might become too lengthy in some cases. Therefore, what if we show the team name instead, like 'Managed by Team [Team Name]'? Let me know what you think.

**Comment by PeerRich** [comment]
can we not show the creator of the managed link? thats always just one person

**Comment by anikdhabal** [comment]
> can we not show the creator of the managed link? thats always just one person

Yeah, my first suggestion was this. Fir team event type we set the owner undefined, let set the owner name and show in the tooltip. @vijayraghav-io

**Comment by vijayraghav-io** [comment]
> can we not show the creator of the managed link? thats always just one person

Hi @PeerRich,
Currently there is no CreatedBy (or similar) field on eventType.
New field `CreatedByUser` can be created and the value can be assigned during the Managed (Parent) eventType creation itself (inside the create.handler.ts for eventType).

This works fine for new Managed EventTypes created in future, but for already created `Parent ManagedEventTypes`, we will have to fallback to Team Owner or Admin (and if only one owner has to be shown in ToolTip , we can try to get the first owner by least membership `id` and accepted).

Please let me know, if I can go with the above approach.

The idea of showing all or multiple admins in Tooltip, was that a team member knows alternate admins to contact in case of absence of an admin.

**Comment by vijayraghav-io** [comment]
> > can we not show the creator of the managed link? thats always just one person
> 
> Yeah, my first suggestion was this. Fir team event type we set the owner undefined, let set the owner name and show in the tooltip. @vijayraghav-io

Hi @anikdhabal, 

My understanding is this -
1. For team events, the `owner` field is undefined intentionally, as these events are managed by team. A team can have multiple owners and ownership is subjected to change.
2. Here we are trying to show tooltip for personal events or children eventTypes. This children eventType created automatically from a Parent eventType (managed) will already have the owner field assigned. It will be assigned with `assigned user` for whom these children eventTypes are distributed. I understand we should not change this field.

**Comment by anikdhabal** [comment]
Hey @vijayraghav-io, after considering all options, the best approach would be to show a comma-separated list of admins in the tooltip. To avoid making the tooltip too large, we can display up to 2 admin names there. If there are more admins, we'll show the number of remaining admins along with a link to the team members page. The route for this is `settings/teams/{teamId}/members`

eg:- peer, keith and 3 more

Screenshot 2024-08-01 230856

Lmk what you think

cc @PeerRich

**Comment by vijayraghav-io** [comment]
> Hey @vijayraghav-io, after considering all options, the best approach would be to show a comma-separated list of admins in the tooltip. To avoid making the tooltip too large, we can display up to 2-3 admin names there. If there are more admins, we'll show the number of remaining admins.
> 
> eg:- peer, keith and 3 more or others
> 
> Screenshot 2024-08-01 230856
> 
> Lmk what you think
> cc @PeerRich 
> 

@anikdhabal will update for 'and x more' in case of more than 2 admins.

**Comment by anikdhabal** [comment]
@vijayraghav-io One more thing we can add to this is to make the rest admins, for example: '3 more', and make this a link. Clicking it will redirect to the team members page. This is simple. The route for this is: settings/teams/{teamId}/members. It would be great to add this. Also, the '3 more' text color should be blue, as you can see in the example I provided. It is possible to add this functionality to the tooltip currently.

eg:-

https://github.com/user-attachments/assets/5a0ba58b-1737-4937-9032-e0304a6952ff

**Comment by vijayraghav-io** [comment]
> @vijayraghav-io One more thing we can add to this is to make the rest admins, for example: '3 more', and make this a link. Clicking it will redirect to the team members page. This is simple, only you need to handle the passing content to the tooltip. The route for this is: settings/teams/{teamId}/members. It would be great to add this. Also, the '3 more' text color should be blue, as you can see in the example I provided. It is possible to add this functionality to the tooltip currently.
> 
> eg:-
> 
>  Teams._.Cal.com.and.23.more.pages.-.Personal.-.Microsoft.Edge.2024-08-02.08-24-16.mp4

ok will include this as well

**Comment by vijayraghav-io** [comment]
@anikdhabal updated with required changes, please check.

https://www.loom.com/share/75f8cea1e57c4229b14cf2e2b2afd062?sid=2b25127d-44d7-40c1-99db-3b6e855467ce

File: packages/features/eventtypes/components/EventTypeDescription.tsx [hunk 2]
```diff
@@ -40,6 +42,31 @@ export const EventTypeDescription = ({
 
   const paymentAppData = getPaymentAppData(eventType);
 
+  const showManagedBadge = eventType.metadata?.managedEventConfig && !isPublic;
+  const numOfManagedByAdmins = eventType.managedBy?.admins.length || 0;
```
Comment (anikdhabal) [inline packages/features/eventtypes/components/EventTypeDescription.tsx:46]: Add a better variable name, no need to include managed. Change it to `numberOfTeamAdmins`

File: packages/features/eventtypes/components/EventTypeDescription.tsx [hunk 3]
```diff
@@ -40,6 +42,31 @@ export const EventTypeDescription = ({
...
+  const showManagedByToolTip = showManagedBadge && numOfManagedByAdmins > 0;
```
Comment (anikdhabal) [inline packages/features/eventtypes/components/EventTypeDescription.tsx:47]: We don't need the `showManagedByToolTip` variable

File: packages/features/eventtypes/components/EventTypeDescription.tsx [hunk 4]
```diff
@@ -40,6 +42,31 @@ export const EventTypeDescription = ({
...
+  let managedByToolTipContent = "";
+  let managedByToolTipContentWithLink;
```
Comment (anikdhabal) [inline packages/features/eventtypes/components/EventTypeDescription.tsx:49]: pls remove `managedByToolTipContentWithLink` and try to use `managedByToolTipContent` in both condition. Use single variable to store the tooltip content.

File: packages/features/eventtypes/components/EventTypeDescription.tsx [hunk 5]
```diff
@@ -40,6 +42,31 @@ export const EventTypeDescription = ({
...
+          {`${managedByToolTipContent} ${t("and")} `}
+          <Link
+            href={`/settings/teams/${eventType.managedBy?.teamId}/members`}
+            className=" text-blue-300 underline">
+            {`${numOfManagedByAdmins - 2} ${t("more")}`}
+          </Link>
+        </>
+      );
+    }
+  }
```
Comment (anikdhabal) [inline packages/features/eventtypes/components/EventTypeDescription.tsx:68]: Nah, we should show the number of admins if the length is greater than 2. So, remove the check `!!eventType.managedBy?.teamId `and disable the link if teamId is not present.

File: packages/features/eventtypes/components/EventTypeDescription.tsx [hunk 6]
```diff
@@ -40,6 +42,31 @@ export const EventTypeDescription = ({
 
   const paymentAppData = getPaymentAppData(eventType);
 
+  const showManagedBadge = eventType.metadata?.managedEventConfig && !isPublic;
+  const numOfManagedByAdmins = eventType.managedBy?.admins.length || 0;
+  const showManagedByToolTip = showManagedBadge && numOfManagedByAdmins > 0;
+  let managedByToolTipContent = "";
+  let managedByToolTipContentWithLink;
+
+  if (showManagedByToolTip) {
```
Comment (anikdhabal) [inline packages/features/eventtypes/components/EventTypeDescription.tsx:51]: As we don't need the `showManagedByTooltip` so instead use the variable that store the admins length and check

File: packages/features/eventtypes/components/EventTypeDescription.tsx [hunk 7]
```diff
@@ -78,11 +105,21 @@ export const EventTypeDescription = ({
               </Badge>
             </li>
           )}
-          {eventType.metadata?.managedEventConfig && !isPublic && (
+          {showManagedBadge && !showManagedByToolTip && (
```
Comment (anikdhabal) [inline packages/features/eventtypes/components/EventTypeDescription.tsx:108]: Remove `showManagedByToolTip` from here

File: packages/features/eventtypes/components/EventTypeDescription.tsx [hunk 8]
```diff
@@ -78,11 +105,21 @@ export const EventTypeDescription = ({
...
+          {showManagedBadge && showManagedByToolTip && (
+            <Tooltip
+              content={numOfManagedByAdmins <= 2 ? managedByToolTipContent : managedByToolTipContentWithLink}>
+              <div>
+                <Badge variant="gray" startIcon="lock">
+                  {t("managed")}
+                </Badge>
+              </div>
+            </Tooltip>
+          )}
```
Comment (anikdhabal) [inline packages/features/eventtypes/components/EventTypeDescription.tsx:122]: Don't need to conditionally show the tooltip and use the same batch two times. Instead, keep the badge inside the tooltip for both conditions and disable the tooltip when the length of the admins is 0. I think there are props present to open the tooltip, so use it.

**Review by anikdhabal — CHANGES_REQUESTED** [review]
Great work @vijayraghav-io , left some comments

File: packages/features/eventtypes/components/EventTypeDescription.tsx (hunk 8 above)
Comment (vijayraghav-io) [reply packages/features/eventtypes/components/EventTypeDescription.tsx]: i had tried with disabling tooltip, but there are no props for disabling. There is one `aria-disabled` but it will still show empty tooltip.

File: packages/features/eventtypes/components/EventTypeDescription.tsx (hunk 2 above)
Comment (vijayraghav-io) [reply packages/features/eventtypes/components/EventTypeDescription.tsx]: done

File: packages/features/eventtypes/components/EventTypeDescription.tsx (hunk 3 above)
Comment (vijayraghav-io) [reply packages/features/eventtypes/components/EventTypeDescription.tsx]: i thought since this condition is used at 2 places, we can have this flag, ya since we are going with single batch (this was my initial approach) removed this.

File: packages/features/eventtypes/components/EventTypeDescription.tsx (hunk 4 above)
Comment (vijayraghav-io) [reply packages/features/eventtypes/components/EventTypeDescription.tsx]: ya done

File: packages/features/eventtypes/components/EventTypeDescription.tsx (hunk 5 above)
Comment (vijayraghav-io) [reply packages/features/eventtypes/components/EventTypeDescription.tsx]: Yeah, but if teamId is null, we wont get the admins as well.
Anyway updated this.
But disabling Link is not possible, as there is no prop for this in <Link

File: packages/features/eventtypes/components/EventTypeDescription.tsx (hunk 6 above)
Comment (vijayraghav-io) [reply packages/features/eventtypes/components/EventTypeDescription.tsx]: done

**Comment by vijayraghav-io** [comment]
> Great work @vijayraghav-io , left some comments

Thank you! @anikdhabal , i have addressed the comments, please check

File: packages/features/eventtypes/components/EventTypeDescription.tsx (hunk 8 above)
Comment (anikdhabal) [reply packages/features/eventtypes/components/EventTypeDescription.tsx]: You can use the hidden class inside the classname conditionally, but it’s not necessary.

Hey, it just came to my mind now, that in a team the owner has the highest priority. This means there must be an owner on the team, but admins might not be present. As the owner, you can assign roles to others, but as an admin, you cannot edit the owner.

So, the main point is to show the owner's name instead of the admin's name. This way, you won't need to conditionally render anything, because there will always be an owner present in the team. We only need to check the owner length to show the number if the length is greater than two, just like we do for the admin.

And you don't need to conditionally render badge also.

Apart from this all things are perfect.

Comment (anikdhabal) [reply packages/features/eventtypes/components/EventTypeDescription.tsx]: Let's go with 'admin' for now, as per the requirement.

**Review by anikdhabal — APPROVED** [review]
LGTM!, thanks for your work
