### PR TITLE
fix: get location url from metadata

### LINKED ISSUE #6478: [CAL-788] downloading an .ics with zoom link shows "integration:daily"
very odd, when downloading the .ics of an event with zoom it says

location = integrations:daily

it should show the zoom link instead

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-788](https://linear.app/calcom/issue/CAL-788/downloading-an-ics-with-zoom-link-shows-integrationdaily)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/6478
2) shows url in where section for confirmed bookings

Screenshot 2023-02-04 at 12 53 57 AM

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

File: apps/web/pages/booking/[uid].tsx [hunk 1]
```diff
@@ -186,16 +186,19 @@ export default function Success(props: SuccessProps) {
     window.scrollTo(0, document.body.scrollHeight);
   }
 
-  const location: ReturnType<typeof getEventLocationValue> = Array.isArray(props.bookingInfo.location)
```
Comment (Udit-takkar) [inline apps/web/pages/booking/[uid].tsx:189]: why was Array.isArray used here ? props.bookingInfo.location is always string

**Review by emrysal — APPROVED** [review]
