### PR TITLE
remove duplicate datepicker, slight changes to success page

### LINKED ISSUE #3158: Availability page displays two Timezone dropdown button for mobile view
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Availability page displays two Timezone dropdown button for mobile view

### Steps to Reproduce

1. Go to Event Types
2. Click on Preview button for any one of the Event Types
3. Follow the link in a new tab
4. Enable mobile view
5. Notice one more Timezone dropdown button just below the calendar

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- https://www.loom.com/share/ad5975aa1878499380753c0b2877a494
Screen Shot 2022-06-26 at 8 50 14 AM

### Expected Behaviour

- Second dropdown button below the calendar should not be displayed

### PR DESCRIPTION
**Pull request by PeerRich**
- closes #3158 
- minor UI fixes to success page

### CODE REVIEW

File: apps/web/pages/success.tsx [hunk 1]
```diff
@@ -268,10 +268,10 @@ export default function Success(props: SuccessProps) {
         className={isEmbed ? "" : "h-screen bg-neutral-100 dark:bg-neutral-900"}
         data-testid="success-page">
         {userIsOwner && !isEmbed && (
-          <div className="-mb-7 ml-9 mt-7">
+          <div className="ml-4 mt-2 -mb-4">
```
Comment (PeerRich) [inline apps/web/pages/success.tsx:271]: @alannnc lets use intervals of 2, (ml-2, ml-4, ml-6, ml-8) and not 7, 9

File: apps/web/pages/success.tsx [hunk 2]
```diff
@@ -471,7 +471,7 @@ export default function Success(props: SuccessProps) {
                           }>
                           <a className="mx-2 h-10 w-10 rounded-sm border border-neutral-200 px-3 py-2 dark:border-neutral-700 dark:text-white">
                             <svg
-                              className="-mt-1 inline-block h-4 w-4"
+                              className="-mt-1.5 inline-block h-4 w-4"
```
Comment (PeerRich) [inline apps/web/pages/success.tsx:474]: the icons were not visually centered

**Review by zomars — APPROVED** [review]
