### PR TITLE
fix: Unpublished screens 

### LINKED ISSUE #10400: [CAL-2250] Show org unpublished state for unpublished org user profiles
As discussed in Threads → area-organizations we need to not show a 404 error page for existing users within an unpublished organization.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2250](https://linear.app/calcom/issue/CAL-2250/show-org-unpublished-state-for-unpublished-org-user-profiles)</sub>

### PR DESCRIPTION
**Pull request by leog**
## What does this PR do?

When an unpublished team or organization was accessed, a 404 error appeared, we now show an unpublished screen, whether is for that team or org, or a user/event-type inside a team, or a user/sub-team/event-type inside an org.

Also fixes a few cases where not the correct entity was fetched, as well as UI issues with some unpublished screens that existed already, see the following old version, not very well centered:

<kbd></kbd>

And now:

<kbd>image</kbd>

And for teams, the entity is actually "team":

<kbd>image<kbd>

Fixes #10400 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

> **Note**
> E2E tests have been added as part of this PR

Unpublished entities were added to the seed, so visit the following URLs and see their corresponding unpublished screens:

- `http://localhost:3000/team/foobar`
- `http://localhost:3000/team/foobar/collective`
- `http://localhost:3000/org/acme` same as `http://acme.cal.local:3000`
- `http://localhost:3000/org/acme/team/marketing` same as `http://acme.cal.local:3000/marketing`
- `http://localhost:3000/org/acme/team/marketing/collective` same as `http://acme.cal.local:3000/marketing/collective`
- `http://localhost:3000/org/acme/john` same as `http://acme.cal.local:3000/john`
- `http://localhost:3000/org/acme/john/30min`same as `http://acme.cal.local:3000/john/30min`

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: apps/web/pages/[user].tsx [hunk 1]
```diff
@@ -58,6 +58,15 @@ export function UserPage(props: InferGetServerSidePropsType<typeof getServerSide
       telemetry.event(telemetryEventTypes.embedView, collectPageParameters("/[user]"));
     }
   }, [telemetry, router.asPath]); */
+
+  if (entity?.isUnpublished) {
```
Comment (leog) [inline apps/web/pages/[user].tsx:62]: Including the unpublished screen on user pages if entity (team or org) holding the user is unpublished

File: apps/web/pages/[user].tsx [hunk 2]
```diff
@@ -225,20 +239,31 @@ export type UserPageProps = {
 
 export const getServerSideProps: GetServerSideProps<UserPageProps> = async (context) => {
   const ssr = await ssrInit(context);
-  const { currentOrgDomain, isValidOrgDomain } = orgDomainConfig(context.req.headers.host ?? "");
-
+  const { currentOrgDomain, isValidOrgDomain } = orgDomainConfig(
+    context.req.headers.host ?? "",
+    context.query.orgSlug
```
Comment (leog) [inline apps/web/pages/[user].tsx:244]: Making sure we respect the way of accessing an org link using `/org/orgSlug` as well

File: apps/web/pages/[user].tsx [hunk 3]
```diff
@@ -225,20 +239,31 @@ export type UserPageProps = {
...
-        : null,
+      organization:
+        isValidOrgDomain && currentOrgDomain
+          ? {
+              OR: [
+                { slug: currentOrgDomain },
+                {
+                  metadata: {
+                    path: ["requestedSlug"],
+                    equals: currentOrgDomain,
```
Comment (leog) [inline apps/web/pages/[user].tsx:261]: Needed to make sure we also selected an unpublished organization to not end up in a 404 page

File: apps/web/pages/[user]/[type].tsx [hunk 4]
```diff
@@ -58,7 +58,10 @@ async function getDynamicGroupPageProps(context: GetServerSidePropsContext) {
 
   const { ssrInit } = await import("@server/lib/ssr");
   const ssr = await ssrInit(context);
-  const { currentOrgDomain, isValidOrgDomain } = orgDomainConfig(context.req.headers.host ?? "");
+  const { currentOrgDomain, isValidOrgDomain } = orgDomainConfig(
+    context.req.headers.host ?? "",
+    context.query.orgSlug
```
Comment (leog) [inline apps/web/pages/[user]/[type].tsx:63]: Making sure we respect the way of accessing an org link using `/org/orgSlug` as well

File: apps/web/pages/[user]/[type].tsx [hunk 5]
```diff
@@ -124,18 +127,32 @@ async function getUserPageProps(context: GetServerSidePropsContext) {
   const { user: usernames, type: slug } = paramsSchema.parse(context.params);
   const username = usernames[0];
   const { rescheduleUid, bookingUid } = context.query;
-  const { currentOrgDomain, isValidOrgDomain } = orgDomainConfig(context.req.headers.host ?? "");
+  const { currentOrgDomain, isValidOrgDomain } = orgDomainConfig(
+    context.req.headers.host ?? "",
+    context.query.orgSlug
```
Comment (leog) [inline apps/web/pages/[user]/[type].tsx:132]: Making sure we respect the way of accessing an org link using `/org/orgSlug` as well

File: apps/web/pages/[user]/[type].tsx [hunk 6]
```diff
@@ -124,18 +127,32 @@ async function getUserPageProps(context: GetServerSidePropsContext) {
...
+      organization:
+        isValidOrgDomain && currentOrgDomain
+          ? {
+              OR: [
+                {
+                  slug: currentOrgDomain,
+                },
+                {
+                  metadata: {
+                    path: ["requestedSlug"],
```
Comment (leog) [inline apps/web/pages/[user]/[type].tsx:149]: Needed to make sure we also selected an unpublished organization to not end up in a 404 page

File: apps/web/pages/org/[orgSlug]/[user]/[type].tsx [hunk 7]
```diff
@@ -17,7 +17,15 @@ export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
         not: null,
       },
       parent: {
-        slug: ctx.query.orgSlug as string,
+        OR: [
+          { slug: ctx.query.orgSlug as string },
+          {
+            metadata: {
+              path: ["requestedSlug"],
```
Comment (leog) [inline apps/web/pages/org/[orgSlug]/[user]/[type].tsx:24]: Needed to make sure we also selected an unpublished organization to not end up in a 404 page

File: apps/web/pages/org/[orgSlug]/[user]/index.tsx [hunk 8]
```diff
@@ -17,17 +17,25 @@ export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
         not: null,
       },
       parent: {
-        slug: ctx.query.orgSlug as string,
+        OR: [
+          { slug: ctx.query.orgSlug as string },
+          {
+            metadata: {
+              path: ["requestedSlug"],
```
Comment (leog) [inline apps/web/pages/org/[orgSlug]/[user]/index.tsx:24]: Needed to make sure we also selected an unpublished organization to not end up in a 404 page

File: apps/web/pages/org/[orgSlug]/[user]/index.tsx [hunk 9]
```diff
@@ -17,17 +17,25 @@ export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
...
+        ],
       },
     },
     select: {
       id: true,
     },
   });
   if (team) {
-    return GSSTeamPage({ ...ctx, query: { slug: ctx.query.user } });
+    return GSSTeamPage({ ...ctx, query: { slug: ctx.query.user, orgSlug: ctx.query.orgSlug } });
```
Comment (leog) [inline apps/web/pages/org/[orgSlug]/[user]/index.tsx:36]: Passing down the org slug to also take it into account downwards

File: apps/web/pages/org/[orgSlug]/[user]/index.tsx [hunk 10]
```diff
@@ -17,17 +17,25 @@ export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
...
   }
-  return GSSUserPage({ ...ctx, query: { user: ctx.query.user } });
+  return GSSUserPage({ ...ctx, query: { user: ctx.query.user, orgSlug: ctx.query.orgSlug } });
```
Comment (leog) [inline apps/web/pages/org/[orgSlug]/[user]/index.tsx:38]: Passing down the org slug to also take it into account downwards

File: apps/web/pages/team/[slug].tsx [hunk 11]
```diff
@@ -249,29 +245,33 @@ function TeamPage({ team, isUnpublished, markdownStrippedBio, isValidOrgDomain }
 export const getServerSideProps = async (context: GetServerSidePropsContext) => {
   const ssr = await ssrInit(context);
   const slug = Array.isArray(context.query?.slug) ? context.query.slug.pop() : context.query.slug;
-  const { isValidOrgDomain } = orgDomainConfig(context.req.headers.host ?? "");
+  const { isValidOrgDomain, currentOrgDomain } = orgDomainConfig(
+    context.req.headers.host ?? "",
+    context.query.orgSlug
```
Comment (leog) [inline apps/web/pages/team/[slug].tsx:250]: Making sure we respect the way of accessing an org link using `/org/orgSlug` as well

File: apps/web/pages/team/[slug].tsx [hunk 12]
```diff
@@ -249,29 +245,33 @@ function TeamPage({ team, isUnpublished, markdownStrippedBio, isValidOrgDomain }
...
+  );
   const flags = await getFeatureFlagMap(prisma);
-
-  const team = await getTeamWithMembers(undefined, slug);
+  const team = await getTeamWithMembers(undefined, slug, undefined, currentOrgDomain);
```
Comment (leog) [inline apps/web/pages/team/[slug].tsx:253]: We need to select a team within an org context if it exists

File: apps/web/pages/team/[slug].tsx [hunk 13]
```diff
@@ -249,29 +245,33 @@ function TeamPage({ team, isUnpublished, markdownStrippedBio, isValidOrgDomain }
...
-    (isValidOrgDomain && team?.parent && !!metadata?.isOrganization) ||
     (!isValidOrgDomain && team?.parent) ||
     (!isValidOrgDomain && !!metadata?.isOrganization) ||
     flags["organizations"] !== true
   ) {
     return { notFound: true } as const;
   }
 
-  if (!team) {
+  if (!team || !team.parent?.slug) {
```
Comment (leog) [inline apps/web/pages/team/[slug].tsx:264]: We also consider unpublished a team with no parent slug

File: apps/web/pages/team/[slug]/[type].tsx [hunk 14]
```diff
@@ -57,16 +57,38 @@ export const getServerSideProps = async (context: GetServerSidePropsContext) =>
   const { rescheduleUid } = context.query;
   const { ssrInit } = await import("@server/lib/ssr");
   const ssr = await ssrInit(context);
-  const { currentOrgDomain, isValidOrgDomain } = orgDomainConfig(context.req.headers.host ?? "");
+  const { currentOrgDomain, isValidOrgDomain } = orgDomainConfig(
+    context.req.headers.host ?? "",
+    context.query.orgSlug
```
Comment (leog) [inline apps/web/pages/team/[slug]/[type].tsx:62]: Making sure we respect the way of accessing an org link using `/org/orgSlug` as well

File: apps/web/pages/team/[slug]/[type].tsx [hunk 15]
```diff
@@ -57,16 +57,38 @@ export const getServerSideProps = async (context: GetServerSidePropsContext) =>
...
-      parent: isValidOrgDomain
-        ? {
-            slug: currentOrgDomain,
-          }
-        : null,
+      OR: [
+        { slug: teamSlug },
+        {
+          metadata: {
+            path: ["requestedSlug"],
```
Comment (leog) [inline apps/web/pages/team/[slug]/[type].tsx:71]: Needed to make sure we also selected an unpublished organization to not end up in a 404 page

File: apps/web/pages/team/[slug]/[type].tsx [hunk 16]
```diff
@@ -57,16 +57,38 @@ export const getServerSideProps = async (context: GetServerSidePropsContext) =>
...
+      parent:
+        isValidOrgDomain && currentOrgDomain
+          ? {
+              OR: [
+                {
+                  slug: currentOrgDomain,
+                },
+                {
+                  metadata: {
+                    path: ["requestedSlug"],
```
Comment (leog) [inline apps/web/pages/team/[slug]/[type].tsx:85]: Needed to make sure we also selected an unpublished organization to not end up in a 404 page

File: packages/features/bookings/Booker/Booker.tsx [hunk 17]
```diff
@@ -139,6 +140,10 @@ const BookerComponent = ({
 
   const hideEventTypeDetails = isEmbed ? embedUiConfig.hideEventTypeDetails : false;
 
+  if (entity.isUnpublished) {
+    return <UnpublishedEntity {...entity} />;
```
Comment (leog) [inline packages/features/bookings/Booker/Booker.tsx:144]: Showing unpublished screen on event-type under unpublished team/org

File: packages/features/ee/organizations/lib/orgDomains.ts [hunk 18]
```diff
@@ -23,12 +23,21 @@ export function getOrgSlug(hostname: string) {
   return null;
 }
 
-export function orgDomainConfig(hostname: string) {
+export function orgDomainConfig(hostname: string, fallback?: string | string[]) {
```
Comment (leog) [inline packages/features/ee/organizations/lib/orgDomains.ts:26]: We now provide a possible fallback in case host is not a valid subdomain, this is to take into account accessing through `/org/orgSlug`

File: packages/features/eventtypes/lib/getPublicEvent.ts [hunk 19]
```diff
@@ -37,7 +38,24 @@ const publicEventSelect = Prisma.validator<Prisma.EventTypeSelect>()({
...
+      logo: true,
+      theme: true,
+      parent: {
+        select: {
+          slug: true,
+          name: true,
+        },
+      },
+    },
+  },
```
Comment (leog) [inline packages/features/eventtypes/lib/getPublicEvent.ts:58]: Before this, it was selecting all of these and more fields, this just specifies the ones needed adding parent

File: packages/features/eventtypes/lib/getPublicEvent.ts [hunk 20]
```diff
@@ -87,7 +111,7 @@ export const getPublicEvent = async (
   const usernameList = getUsernameList(username);
   const orgQuery = org
     ? {
-        slug: org ?? null,
+        OR: [{ slug: org }, { metadata: { path: ["requestedSlug"], equals: org } }],
```
Comment (leog) [inline packages/features/eventtypes/lib/getPublicEvent.ts:114]: Needed to make sure we also selected an unpublished organization to not end up in a 404 page

File: packages/features/eventtypes/lib/getPublicEvent.ts [hunk 21]
```diff
@@ -150,13 +182,26 @@ export const getPublicEvent = async (
...
 
   const usersOrTeamQuery = isTeamEvent
     ? {
         team: {
-          slug: username,
+          OR: [
+            { slug: username },
+            {
+              metadata: {
+                path: ["requestedSlug"],
```
Comment (leog) [inline packages/features/eventtypes/lib/getPublicEvent.ts:200]: Needed to make sure we also selected an unpublished organization to not end up in a 404 page

File: packages/features/eventtypes/lib/getPublicEvent.ts [hunk 22]
```diff
@@ -200,7 +246,15 @@ export const getPublicEvent = async (
...
     profile: getProfileFromEvent(event),
     users,
-    orgDomain: org,
+    entity: {
+      isUnpublished:
+        event.team?.slug === null ||
+        event.owner?.organization?.slug === null ||
+        event.team?.parent?.slug === null,
+      orgSlug: org,
+      teamSlug: (event.team?.slug || teamMetadata?.requestedSlug) ?? null,
```
Comment (leog) [inline packages/features/eventtypes/lib/getPublicEvent.ts:255]: `orgSlug` and `teamSlug` are defined separately to know which entity is being accessed, in case both are defined is because a sub-team is being accessed

File: packages/features/eventtypes/lib/getPublicEvent.ts [hunk 23]
```diff
@@ -217,20 +271,6 @@ function getProfileFromEvent(event: Event) {
   if (!profile) throw new Error("Event has no owner");
 
   const username = "username" in profile ? profile.username : team?.slug;
-  if (!username) {
-    if (event.slug === "test") {
-      // @TODO: This is a temporary debug statement that should be removed asap.
```
Comment (leog) [inline packages/features/eventtypes/lib/getPublicEvent.ts:222]: We clearly needed to remove this 😁

File: packages/lib/server/queries/teams/index.ts [hunk 24]
```diff
@@ -92,6 +97,13 @@ export async function getTeamWithMembers(id?: number, slug?: string, userId?: nu
   const where: Prisma.TeamFindFirstArgs["where"] = {};
 
   if (userId) where.members = { some: { userId } };
+  if (orgSlug) {
+    where.parent = {
+      OR: [{ slug: orgSlug }, { metadata: { path: ["requestedSlug"], equals: orgSlug } }],
```
Comment (leog) [inline packages/lib/server/queries/teams/index.ts:102]: Accounting for unpublished orgs too

File: packages/lib/server/queries/teams/index.ts [hunk 25]
```diff
@@ -92,6 +97,13 @@ export async function getTeamWithMembers(id?: number, slug?: string, userId?: nu
...
+    };
+  } else {
+    where.parentId = null;
```
Comment (leog) [inline packages/lib/server/queries/teams/index.ts:105]: This is a bug fix, where it was not being explicitly set to null and was selecting any team org or not with the passed slug

File: packages/prisma/seed.ts [hunk 26]
```diff
@@ -24,7 +24,7 @@ async function createUserAndEventType(opts: {
     theme?: "dark" | "light";
   };
   eventTypes: Array<
-    Prisma.EventTypeCreateInput & {
+    Prisma.EventTypeUncheckedCreateInput & {
```
Comment (leog) [inline packages/prisma/seed.ts:27]: So we can be a bit more permissive on what to pass down to create

File: packages/prisma/seed.ts [hunk 27]
```diff
@@ -279,19 +279,19 @@ async function main() {
         title: "Zoom Event",
         slug: "zoom",
         length: 60,
-        locations: [{ type: zoomMeta.appData?.location.type }],
+        locations: [{ type: zoomMeta.appData?.location?.type }],
```
Comment (leog) [inline packages/prisma/seed.ts:282]: Annoying error fix, as well as the following ones

File: packages/prisma/seed.ts [hunk 28]
```diff
@@ -606,6 +606,81 @@ async function main() {
       },
     ]
   );
+
+  await prisma.team.create({
```
Comment (leog) [inline packages/prisma/seed.ts:610]: Creating an unpublished team with event types, as well as an org with event types and users with event types, to run e2e and have available to test app workflows when publishing them

File: packages/trpc/server/routers/viewer/teams/create.handler.ts [hunk 29]
```diff
@@ -28,7 +28,7 @@ export const createHandler = async ({ ctx, input }: CreateOptions) => {
     where: {
       slug: slug,
       // If this is under an org, check that the team doesn't already exist
-      ...(isOrgChildTeam && { parentId: user.organizationId }),
+      parentId: isOrgChildTeam ? user.organizationId : null,
```
Comment (leog) [inline packages/trpc/server/routers/viewer/teams/create.handler.ts:31]: Also needed to check parent null explicitly when on org is in context, otherwise it could select wrongly

File: apps/web/pages/[user]/[type].tsx [hunk 30]
```diff
@@ -26,7 +26,7 @@ export default function Type({
   away,
   isBrandingHidden,
   rescheduleUid,
-  org,
+  entity,
```
Comment (zomars) [inline apps/web/pages/[user]/[type].tsx:29]: What does entity means in this context?

File: packages/prisma/seed.ts (hunk 28 above)
Comment (CarinaWolli) [reply packages/prisma/seed.ts:610]: We need to skip if database entry already exists, I am getting this error: 
Screenshot 2023-07-28 at 16 04 34

And Foobar Team is now there several times, no slug yet so it doesn't throw any unique constraint
Screenshot 2023-07-28 at 16 07 14

File: packages/features/ee/organizations/lib/orgDomains.ts [hunk 31]
```diff
@@ -23,12 +23,21 @@ export function getOrgSlug(hostname: string) {
...
+      currentOrgDomain,
+      isValidOrgDomain,
+    };
+  } else {
+    const fallbackOrgDomain = getOrgSlug(`${fallback}.${subdomainSuffix()}`);
+    return {
+      currentOrgDomain: fallbackOrgDomain,
+      isValidOrgDomain: fallbackOrgDomain !== null && !RESERVED_SUBDOMAINS.includes(fallbackOrgDomain),
+    };
+  }
```
Comment (zomars) [inline packages/features/ee/organizations/lib/orgDomains.ts:40]: Nitpick

```suggestion
  }
  const fallbackOrgDomain = getOrgSlug(`${fallback}.${subdomainSuffix()}`);
  return {
    currentOrgDomain: fallbackOrgDomain,
    isValidOrgDomain: fallbackOrgDomain !== null && !RESERVED_SUBDOMAINS.includes(fallbackOrgDomain),
  };
```

File: apps/web/pages/team/[slug].tsx (hunk 13 above)
Comment (CarinaWolli) [reply apps/web/pages/team/[slug].tsx:264]: we are throwing 404 for normal teams now: 

Screenshot 2023-07-28 at 16 27 57

Is that what we want? 
```suggestion
  if (!team || (team.parent && !team.parent.slug) {
```

**Review by CarinaWolli — DISMISSED** [review]
Getting 404 for teams that are in no organization

**Review by zomars — COMMENTED** [review]
Code looking good, will push a small refactor for DRYness and legibility

File: apps/web/pages/team/[slug].tsx (hunk 13 above)
Comment (leog) [reply apps/web/pages/team/[slug].tsx]: Oh left an `orgDomains` util/test changes in the stash! Thanks, accepted your suggestion as well as it was needed.

File: packages/prisma/seed.ts (hunk 28 above)
Comment (leog) [reply packages/prisma/seed.ts:610]: Oh so are you running the seed without resetting the DB? 🤔

File: packages/lib/server/queries/teams/index.ts [hunk 32]
```diff
@@ -8,7 +8,12 @@ import { WEBAPP_URL } from "../../../constants";
 
 export type TeamWithMembers = Awaited<ReturnType<typeof getTeamWithMembers>>;
 
-export async function getTeamWithMembers(id?: number, slug?: string, userId?: number) {
+export async function getTeamWithMembers(
+  id?: number,
+  slug?: string,
+  userId?: number,
+  orgSlug?: string | null
+) {
```
[the remark this answers is not in the document]
Comment (leog) [reply packages/lib/server/queries/teams/index.ts]: Great idea, done. Please merge this one accordingly: https://github.com/calcom/website/pull/583

File: apps/web/pages/[user]/[type].tsx (hunk 30 above)
Comment (leog) [reply apps/web/pages/[user]/[type].tsx:30]: It refers to whether this user event type is being accessed from a team or an org, getting the values from eventData.

File: packages/prisma/seed.ts (hunk 28 above)
Comment (CarinaWolli) [reply packages/prisma/seed.ts:610]: I ran yarn dx, I think this always runs seed

Comment (leog) [reply packages/prisma/seed.ts]: Corrected, now using seed utils with some adjustments

File: apps/web/playwright/unpublished.e2e.ts [hunk 33]
```diff
@@ -0,0 +1,75 @@
...
+test.describe.configure({ mode: "parallel" });
+
+const title = (name: string) => `${name} is unpublished`;
+const description = (entity: string) =>
+  `This ${entity} link is currently not available. Please contact the ${entity} owner or ask them to publish it.`;
+const avatar = (slug: string) => `http://localhost:3000/team/${slug}/avatar.png`;
+
+test.describe("Unpublished", () => {
+  test("Regular team profile", async ({ page }) => {
+    await page.goto("/team/foobar");
```
Comment (zomars) [inline apps/web/playwright/unpublished.e2e.ts:14]: We cannot rely on seeded data for tests. We must use fixtures for reliability.

File: apps/web/playwright/unpublished.e2e.ts [hunk 34]
```diff
@@ -9,23 +11,36 @@ const description = (entity: string) =>
...
+    await page.goto(`/team/${requestedSlug}/${teamEventSlug}`);
     expect(await page.locator('[data-testid="empty-screen"]').count()).toBe(1);
-    expect(await page.locator(`h2:has-text("${title("Foobar Team")}")`).count()).toBe(1);
+    expect(await page.locator(`h2:has-text("${title(team.name)}")`).count()).toBe(1);
     expect(await page.locator(`div:text("${description("team")}")`).count()).toBe(1);
-    await expect(page.locator(`img`)).toHaveAttribute("src", avatar("foobar"));
+    await expect(page.locator(`img`)).toHaveAttribute("src", avatar(requestedSlug!));
   });
 
   test("Organization profile", async ({ page }) => {
```
Comment (zomars) [inline apps/web/playwright/unpublished.e2e.ts:46]: Can you take care of the remaining ones? 🙏🏽 @leog

File: apps/web/playwright/fixtures/users.ts
Comment (zomars) [inline apps/web/playwright/fixtures/users.ts:1]: I get the need for the refactor @leog but I would rather do this in another PR. Let’s prioritize not touching more files than needed. 🙏

Comment (leog) [reply apps/web/playwright/fixtures/users.ts:1]: Yeah, we really need to redo the whole fixture tooling, seems really redundant passing down flags here and there where you can always rely on Prisma types to do the same. Also, I want to use Faker power to generate names and stuff, [like this](https://gist.github.com/leog/70066880f8f722fd0b3be91ead7689cd) I created in another PR that I closed. Reverting refactor, good call, that way we also reduce possible error points to have this PR merged.

**Review by alannnc — COMMENTED** [review]
Code looks good, find some test fail on local due to subdomains not being handled by orgDomainConfig() function. Added some test url map so it can handle subdomains.

File: apps/web/pages/[user].tsx [hunk 35]
```diff
@@ -225,20 +240,18 @@ export type UserPageProps = {
 
 export const getServerSideProps: GetServerSideProps<UserPageProps> = async (context) => {
   const ssr = await ssrInit(context);
-  const { currentOrgDomain, isValidOrgDomain } = orgDomainConfig(context.req.headers.host ?? "");
-
+  const { currentOrgDomain, isValidOrgDomain } = orgDomainConfig(
+    context.req.headers.host ?? "",
+    context.query.orgSlug
```
Comment (hariombalhara) [inline apps/web/pages/[user].tsx:245]: nit: It's important and complex enough to be in it's own utility now. I like `getOrgDomainConfigFromCtx`

File: apps/web/pages/[user].tsx (hunk 2 above)
Comment (hariombalhara) [reply apps/web/pages/[user].tsx:245]: Also, using query.orgSlug might allow a non-org booker URL to server the org booking page by passing `orgSlug` query param.

We should probably use context.params here which has just dynamic params and no additional query param from client.

File: apps/web/pages/[user].tsx [hunk 36]
```diff
@@ -310,6 +329,7 @@ export const getServerSideProps: GetServerSideProps<UserPageProps> = async (cont
   const safeBio = markdownToSafeHTML(user.bio) || "";
 
   const markdownStrippedBio = stripMarkdown(user?.bio || "");
+  const unPublishedOrgUser = usersWithoutAvatar.find((us) => us.organization?.slug === null);
```
Comment (hariombalhara) [inline apps/web/pages/[user].tsx:332]: nit:
I think if we can get the org directly. All users would have the same org because of the above query.
`const org = usersWithoutAvatar[0].organization`

and the modify the below code like this
`isUnpublished: org.slug == null`
`name: org.name`


It would IMHO, make the code more readable.

File: apps/web/pages/team/[slug].tsx [hunk 37]
```diff
@@ -249,29 +245,33 @@ function TeamPage({ team, isUnpublished, markdownStrippedBio, isValidOrgDomain }
...
-  if (!team) {
+  if (!team || (team.parent && !team.parent.slug)) {
     const unpublishedTeam = await prisma.team.findFirst({
       where: {
-        metadata: {
-          path: ["requestedSlug"],
-          equals: slug,
-        },
+        ...(team?.parent
+          ? { id: team.parent.id }
```
Comment (hariombalhara) [inline apps/web/pages/team/[slug].tsx:268]: Can we have a possibility of unpublished team in an organization? It isn't handling that at the moment.

File: .github/workflows/e2e-app-store.yml [hunk 38]
```diff
@@ -54,6 +54,7 @@ jobs:
           SENDGRID_EMAIL: ${{ secrets.CI_SENDGRID_EMAIL }}
           TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
           TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
+          ALLOWED_HOSTNAMES: '"cal.com","cal.dev","cal-staging.com","cal.community","cal.local:3000","localhost:3000"'
```
Comment (keithwillcode) [inline .github/workflows/e2e-app-store.yml:57]: @hariombalhara These were sorted alphabetically. Can we maintain that?

**Review by keithwillcode — CHANGES_REQUESTED** [review]

File: .github/workflows/e2e-app-store.yml (hunk 38 above)
Comment (keithwillcode) [reply .github/workflows/e2e-app-store.yml:57]: @hariombalhara Since we now have these variables spread across the files, let's add them to variables. Can you change this line of code to ${{ vars.ALLOWED_HOSTNAMES }}? I'll update GitHub

Comment (hariombalhara) [reply .github/workflows/e2e-app-store.yml:57]: Sure. Making the change.

File: apps/web/pages/team/[slug].tsx (hunk 37 above)
Comment (leog) [reply apps/web/pages/team/[slug].tsx:274]: No, subteams are always published as Org the tier includes them at no extra cost, what can be unpublished is just the Org for which you have to pay the Org tier

File: apps/web/pages/[user].tsx (hunk 36 above)
Comment (leog) [reply apps/web/pages/[user].tsx]: Good call, made the change, thanks!

**Review by keithwillcode — APPROVED** [review]

File: apps/web/pages/team/[slug].tsx [hunk 39]
```diff
@@ -249,29 +245,39 @@ function TeamPage({ team, isUnpublished, markdownStrippedBio, isValidOrgDomain }
...
-  const team = await getTeamWithMembers(undefined, slug);
+  const team = await getTeamWithMembers({ slug, orgSlug: currentOrgDomain });
   const metadata = teamMetadataSchema.parse(team?.metadata ?? {});
-
+  console.warn("gSSP, team/[slug] - ", {
+    isValidOrgDomain,
+    currentOrgDomain,
+    ALLOWED_HOSTNAMES: process.env.ALLOWED_HOSTNAMES,
+    flags: JSON.stringify,
+  });
```
Comment (zomars) [inline apps/web/pages/team/[slug].tsx:260]: Is this intended? @leog

Comment (leog) [reply apps/web/pages/team/[slug].tsx:260]: Introduced by @alannnc or @hariombalhara, didn’t remember to remove it
