### PR TITLE
fix: selected organizer when creating event

### LINKED ISSUE #11156: [CAL-2405] Duplicated calendar events for main host on team/dynamic events
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2405](https://linear.app/calcom/issue/CAL-2405/duplicated-calendar-events-for-main-host-on-teamdynamic-events)</sub>

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

- Fixes selected organizer when creating google calendar event.

Fixes #11156 

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

Create a collective event and link up multiple calendar for each required host. Then when booking said event type it should only create 1 event per host calendar.

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/app-store/googlecalendar/lib/CalendarService.ts [hunk 1]
```diff
@@ -97,10 +97,9 @@ export default class GoogleCalendarService implements Calendar {
         responseStatus: "accepted",
       })) || [];
     return new Promise(async (resolve, reject) => {
-      const [mainHostDestinationCalendar] =
-        calEventRaw?.destinationCalendar && calEventRaw?.destinationCalendar.length > 0
-          ? calEventRaw.destinationCalendar
-          : [];
+      const selectedHostDestinationCalendar = calEventRaw.destinationCalendar?.find(
+        (cal) => cal.credentialId === credentialId
+      );
```
Comment (alannnc) [inline packages/app-store/googlecalendar/lib/CalendarService.ts:102]: Was creating the event but always sending mainHostAttendee so it will eventually get 3 calendar event entries.

File: packages/app-store/googlecalendar/lib/CalendarService.ts [hunk 2]
```diff
@@ -119,8 +118,8 @@ export default class GoogleCalendarService implements Calendar {
             id: String(calEventRaw.organizer.id),
             responseStatus: "accepted",
             organizer: true,
-            email: mainHostDestinationCalendar?.externalId
-              ? mainHostDestinationCalendar.externalId
+            email: selectedHostDestinationCalendar?.externalId
+              ? selectedHostDestinationCalendar.externalId
               : calEventRaw.organizer.email,
```
Comment (alannnc) [inline packages/app-store/googlecalendar/lib/CalendarService.ts:123]: Still default to mainHostAttendee organizer email, but shouldn't happen.

**Review by zomars — APPROVED** [review]
