### PR TITLE
fix: dark mode improvements for signup

### LINKED ISSUE #12963: [CAL-2847] dark mode fixes
- signup
- onboarding

<sub>[CAL-2847](https://linear.app/calcom/issue/CAL-2847/dark-mode-fixes)</sub>

### PR DESCRIPTION
**Pull request by PeerRich**
before:
CleanShot 2023-12-29 at 17 21 54@2x

after:
CleanShot 2023-12-29 at 17 21 35@2x

### CODE REVIEW

File: apps/web/pages/signup.tsx [hunk 1]
```diff
@@ -461,54 +468,59 @@ export default function Signup({
...
+            </div>
+          </div>
           <div
-            className="border-default rounded-bl-2xl rounded-br-none rounded-tl-2xl border-dashed py-[6px] pl-[6px]"
+            className="border-default hidden rounded-bl-2xl rounded-br-none rounded-tl-2xl border-dashed lg:block lg:py-[6px] lg:pl-[6px]"
             style={{
               backgroundColor: "rgba(236,237,239,0.9)",
             }}>
-            <img src="/mock-event-type-list.svg" alt="#" className="" />
+            <img src="/mock-event-type-list.svg" alt="Cal.com Booking Page" />
```
Comment (emrysal) [inline apps/web/pages/signup.tsx:501]: Does this need white labeling with APP_NAME?

Comment (PeerRich) [reply apps/web/pages/signup.tsx:528]: right.. lemme remove cal.com

**Review by emrysal — APPROVED** [review]
Looking gewd
