### PR TITLE
Imports performance explicitly for Node v14

### LINKED ISSUE #3396: Not capable to open schedule and select time slot on localhost
### Issue Summary

When I open the public page for selecting time slot, I don't see any slots are available, while there is a timetable which covers all daily hours. 
I am performing that on local machine.

### Steps to Reproduce

1. Do ```docker compose up database -d``` for the database as it's in the steps for calcom/docker repo
2. Run the build and up commands locally, following the steps from calcom/docker repo
4. Open profile page where people can arrange a meeting
5. Press F12 to see errors
6. Run ```docker logs container_id``` for your running calcom/docker build in terminal

console log from docker container I run

`@calcom/web:start: [ERROR][0.0002s] query 'viewer.public.slots.getSchedule'
@calcom/web:start: [ERROR][0.0002s] query 'viewer.public.slots.getSchedule'
@calcom/web:start: [ERROR][0.0002s] query 'viewer.public.slots.getSchedule'
@calcom/web:start: [ERROR][0.0002s] query 'viewer.public.slots.getSchedule'
@calcom/web:start: [ERROR][0.0003s] query 'viewer.public.slots.getSchedule'
@calcom/web:start: [ERROR][0.0003s] query 'viewer.public.slots.getSchedule'
@calcom/web:start: [ERROR][0.0003s] query 'viewer.public.slots.getSchedule'
@calcom/web:start: [ERROR][0.0003s] query 'viewer.public.slots.getSchedule'
@calcom/web:start: Something went wrong ReferenceError: performance is not defined
@calcom/web:start:     at Procedure.resolve [as resolver] (/calcom/apps/web/.next/server/chunks/5017.js:3195:41)
@calcom/web:start:     at Array.<anonymous> (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:101:36)
@calcom/web:start:     at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:     at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:     at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:     at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:     at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:     at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:     at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:     at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:     at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:     at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:     at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:     at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:     at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:     at async Procedure.call (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:144:20) {
@calcom/web:start:   originalError: ReferenceError: performance is not defined
@calcom/web:start:       at Procedure.resolve [as resolver] (/calcom/apps/web/.next/server/chunks/5017.js:3195:41)
@calcom/web:start:       at Array.<anonymous> (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:101:36)
@calcom/web:start:       at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:       at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:       at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:       at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:       at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:       at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:       at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:       at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:       at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:       at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:       at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:       at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:       at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:       at async Procedure.call (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:144:20),
@calcom/web:start:   cause: ReferenceError: performance is not defined
@calcom/web:start:       at Procedure.resolve [as resolver] (/calcom/apps/web/.next/server/chunks/5017.js:3195:41)
@calcom/web:start:       at Array.<anonymous> (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:101:36)
@calcom/web:start:       at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:       at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:       at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:       at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:       at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:       at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:       at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:       at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:       at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:       at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:       at async next (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:126:20)
@calcom/web:start:       at async Array.<anonymous> (/calcom/apps/web/.next/server/chunks/5017.js:748:24)
@calcom/web:start:       at async callRecursive (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:119:24)
@calcom/web:start:       at async Procedure.call (/calcom/node_modules/@trpc/server/dist/router-459409c8.cjs.prod.js:144:20),
@calcom/web:start:   code: 'INTERNAL_SERVER_ERROR',
@calcom/web:start:   name: 'TRPCError'
@calcom/web:start: }
`
### Technical details

- nothing in both repos was changed

### PR DESCRIPTION
**Pull request by emrysal**
## What does this PR do?

Adds an import for compatibility with v14 on the performance module, I think there is no reason not to do this but it does add some redundancy for people trying to run on older node versions.

Fixes #3396

### CODE REVIEW

File: packages/trpc/server/routers/viewer/slots.tsx [hunk 1]
```diff
@@ -1,4 +1,5 @@
 import { SchedulingType } from "@prisma/client";
+import { performance } from "perf_hooks";
```
Comment (zomars) [inline packages/trpc/server/routers/viewer/slots.tsx:2]:
```suggestion
import { performance } from "@calcom/lib/server/perfObserver";
```

Nice catch, although we might want to import the pre-configured one.

**Review by zomars — APPROVED** [review]
