### PR TITLE
fix/4128-reschedulebook-stops-creating-event-calendar

### LINKED ISSUE #4128: Several Reschedule/book back and forth stops creating google calendar.
Found a bug? Please fill out the sections below. 👍

### Issue Summary
It appears that some users had trouble when being booked/rescheduled, event it's not added to their calendar and meeting url it's not present when manually adding event to calendar.

### Steps to Reproduce

Quoted by @Jaibles 
Someone booked a call with me
I requested they reschedule

They rescheduled and everything worked fine
They then realised the new time they chose didn’t work for them, and rescheduled it themselves.

The rescheduled event got updated in Cal, but did not get added to my calendar. The only reason I knew it changed was because they emailed me. The result was I now had no event in my calendar.
I logged into Cal and clicked to view the event and add it to my Google calendar manually.
It added to my calendar successfully but the attendee’s details are not in the event.

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

- Fix email templates being sent while rescheduling

Fixes #4128

**Environment**: Staging(main branch)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/lib/CalEventParser.ts [hunk 1]
```diff
@@ -93,7 +93,10 @@ export const getLocation = (calEvent: CalendarEvent) => {
 export const getProviderName = (calEvent: CalendarEvent): string => {
   // TODO: use getAppName from @calcom/app-store
   if (calEvent.location && calEvent.location.includes("integrations:")) {
-    const location = calEvent.location.split(":")[1];
+    let location = calEvent.location.split(":")[1];
+    if (location === "daily") {
+      location = "Cal Video";
+    }
```
Comment (joeauyeung) [inline packages/lib/CalEventParser.ts:99]: Is this what was causing the bugs?

Comment (joeauyeung) [inline packages/lib/CalEventParser.ts:99]: Is this what was causing the bugs?

**Review by joeauyeung — APPROVED** [review]
LGTM
