### PR TITLE
fix: small UI improvements for troubleshooter

### LINKED ISSUE #12533: [CAL-2756] show troubleshooter on your own page
when visiting your own profile page, it should show a button to open troubleshooter

<sub>[CAL-2756](https://linear.app/calcom/issue/CAL-2756/show-troubleshooter-on-your-own-page)</sub>

### PR DESCRIPTION
**Pull request by PeerRich**
- [x] fixed padding
- [x] i18n fixes
- [x] show troubleshooter on your own page
- [x] bug: when visiting: http://localhost:3000/availability/troubleshoot?eventType=paid it doesn't select "paid" and instead the first entry
CleanShot 2023-11-24 at 23 12 44@2x

after:

CleanShot 2023-11-24 at 23 03 14@2x

CleanShot 2023-11-24 at 23 02 45@2x

## how to test
- visit your own link on localhost
- see "need help" button
- click it

- visit someone else's link on local host
- don't see the "need help" button

### CODE REVIEW

File: packages/features/bookings/Booker/components/Header.tsx [hunk 1]
```diff
@@ -54,12 +62,23 @@ export function Header({
...
   if (isMonthView) {
     return (
       <div className="flex gap-2">
         <OverlayCalendarContainer />
+        {isMyLink && (
+          <Tooltip content={t("troubleshooter_tooltip")} side="bottom">
+            <Button
+              color="primary"
+              target="_blank"
+              href={`${WEBAPP_URL}/availability/troubleshoot?eventType=${eventSlug}`}>
```
Comment (PeerRich) [inline packages/features/bookings/Booker/components/Header.tsx:77]: this works, but for some reason the URL does not take the state and by default loads the first event-type in the dropdown

cc @sean-brydon

File: packages/features/bookings/Booker/components/Header.tsx [hunk 2]
```diff
@@ -54,12 +62,23 @@ export function Header({
       <LayoutToggle onLayoutToggle={onLayoutToggle} layout={layout} enabledLayouts={enabledLayouts} />
     );
   };
+  const isMyLink = username === session?.data?.user.username; // TODO: check for if the user is the owner of the link
```
Comment (PeerRich) [inline packages/features/bookings/Booker/components/Header.tsx:65]: only show this button if your logged in session === the link of the username

**Review by sean-brydon — APPROVED** [review]
LGTM :) Thanks for fixes
