### PR TITLE
fix: resolve undefined {CANCEL_URL} in workflow templates

### LINKED ISSUE #22572: Workflow {CANCEL_URL} gives undefined booking in link
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When using the {CANCEL_URL} variable for the email body (and potentially text) with a seated booking, the received message shows https://cal.com/booking/undefined?cancel=true as the link for all bookers after the first booker.

### Steps to Reproduce

1. Create a new event type
2. Under the Advanced tab, enable Offer seats
3. Set the seat limit to 2
4. Disable show the number of available seats
5. Save
6. Under the Workflows tab, create a new workflow
7. Set this workflow to trigger When new event is booked
8. Set the email body to '{CANCEL_URL}'
9. Save
10. Book a slot on an email (not the email that created the Event Type)
11. Check that email account's inbox and observe that the url shows up properly (https://cal.com/booking/{UID_HERE}?cancel=true&cancelledBy={EMAIL_1_HERE})
12. Book **that same slot** (time and data) on a **different account**
13. Check that email account's inbox and observe that the link shows up with an unidentified undefined in the url (https://cal.com/booking/undefined?cancel=true&cancelledBy={EMAIL_1_HERE})

### Actual Results

- The url doesn't properly show the link to cancel.

### Expected Results

- The url should show the link to cancel.

### Evidence

Workflow email body:
Image

Email message received:
Image

### PR DESCRIPTION
**Pull request by ShashwatPS**
## What does this PR do?

When using the {CANCEL_URL} variable in the workflow for seated bookings, the scheduleWorkflowReminders function was called directly for the first seat, and the template worked fine. However, for subsequent seats, the handleSeats function (in packages/features/bookings/lib/handleSeats/handleSeats.ts), inside which scheduleWorkflowReminders was being called, did not pass the event’s uid. This uid was required to construct the cancel URL.

While fixing this, I also discovered that seatReferenceUid was being set incorrectly and fixed that as well.

- Fixes #22572 
- Fixes CAL-6113

## Visual Demo

A booking with 2 seats 
Screenshot 2025-08-31 at 1 02 07 PM
Screenshot 2025-08-31 at 1 02 22 PM

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### Files Modified  
packages/features/bookings/lib/handleSeats/handleSeats.ts

## How should this be tested?

- Run the project locally
- Create a new event type
- Under the Advanced tab, enable Offer seats
- Set the seat limit to 2
- Disable show the number of available seats
- Save
- Under the Workflows tab, create a new workflow
- Set this workflow to trigger When new event is booked
- Set the email body to '{CANCEL_URL}'
- Save
- Book a slot on an email (not the email that created the Event Type)
- Check that email account's inbox and observe that the url shows up properly.
- Book that same slot (time and data) on a different account
- Check that email account's inbox and observe that the link shows up with an unidentified undefined in the url

## Checklist  
- [x] I have read the contributing guide  
- [x] My code follows the style guidelines of this project  
- [x] I have commented my code, particularly in hard-to-understand areas  
- [x] I have checked that my changes generate no new warnings

### CODE REVIEW

File: packages/features/bookings/lib/handleSeats/handleSeats.ts [hunk 1]
```diff
@@ -127,7 +128,7 @@ const handleSeats = async (newSeatedBookingObject: NewSeatedBookingObject) => {
         isRescheduleEvent: !!rescheduleUid,
         isFirstRecurringEvent: true,
         emailAttendeeSendToOverride: bookerEmail,
-        seatReferenceUid: evt.attendeeSeatId,
```
Comment (anikdhabal) [inline packages/features/bookings/lib/handleSeats/handleSeats.ts:130]: What is the issue with it?

Comment (ShashwatPS) [reply packages/features/bookings/lib/handleSeats/handleSeats.ts:130]: Actually, while testing the cancel variable, I logged the evt object and found that there’s no attendeeSeatId in it.

Comment (anikdhabal) [reply packages/features/bookings/lib/handleSeats/handleSeats.ts:130]: Okay

**Comment by anikdhabal** [comment]
@ShashwatPS pls check this and try to address it here:- https://github.com/calcom/cal.com/issues/22572#issuecomment-3240243799

File: packages/features/bookings/lib/handleSeats/handleSeats.ts (hunk 1 above)
Comment (ShashwatPS) [reply packages/features/bookings/lib/handleSeats/handleSeats.ts:130]: Actually, this change should stay, because as you said, the seatReference should also be passed in the URL for attendees in the cancel link, without this change, the reference won’t show up since it was not being passed correctly

**Review by anikdhabal — DISMISSED** [review]
Looks good

**Review by anikdhabal — DISMISSED** [review]

**Review by anikdhabal — APPROVED** [review]
Thanks for your work

**Review by volnei — APPROVED** [review]
