### PR TITLE
fix: bookings for guests added by organizer get cancelled when rescheduled

### LINKED ISSUE #17813: Bookings for Guests Added by Organiser or Team Owner get cancelled when the booking is rescheduled
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When a booking that contains guests added by organiser or team owner is rescheduled, the guests added by the organiser or team owner are not present in the rescheduled booking and they receive booking cancelled email.

### Steps to Reproduce

1. Create a booking on team pro example account.
2. Login to team pro example account and Go to /bookings/incoming page. 
3. Add guests to that booking.
4. Now Reschedule the booking.
5. Notice that the guests that were just added (by team pro example) are not included in the rescheduled booking and cancellation emails were sent for those guests.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- Guests added by organiser or team owner are removed when the booking is rescheduled.

### Expected Results

- Guests added by organiser or team owner should be present in the rescheduled booking.

### Evidence

[Screencast from 23-11-24 07:31:29 PM IST.webm](https://github.com/user-attachments/assets/0ccd4c3a-29db-4b13-b4c4-55759e632daa)

### PR DESCRIPTION
**Pull request by kart1ka**
## What does this PR do?

- Fixes #17813 (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

[Screencast from 25-11-24 12:25:13 AM IST.webm](https://github.com/user-attachments/assets/2e67a49a-7fd0-4f92-8201-feefda492e17)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

1. Create a booking on team pro example account.
2. Login to team pro example account and Go to /bookings/incoming page.
3. Add guests to that booking.
4. Now Reschedule the booking.
5. Notice that the guests that were just added (by team pro example) are now included in the rescheduled booking.

### CODE REVIEW

File: packages/lib/bookingSuccessRedirect.ts
Comment (Praashh) [inline packages/lib/bookingSuccessRedirect.ts:1]: We are not changing anything locally in this file, so we can keep it as it is.

Comment (kart1ka) [reply packages/lib/bookingSuccessRedirect.ts:1]: I’ve moved the getSafe function out of the other function it was in so that it can be exported.

**Review by Praashh — APPROVED** [review]
LGTM!!

**Review by anikdhabal — COMMENTED** [review]
Working fine, but I will check the code once before shipping

**Review by Praashh — CHANGES_REQUESTED** [review]
@kart1ka can you please resolve merge conflicts?

**Comment by kart1ka** [comment]
> @kart1ka can you please resolve merge conflicts?

On it.

**Comment by kart1ka** [comment]
> @kart1ka can you please resolve merge conflicts?

Merge conflicts resolved.

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 1]
```diff
@@ -899,7 +901,69 @@ async function handler(
...
+    //  Filter out: Team members, booker and Guests added by the booker from the original rescheduled booking attendees to get the guests added by organizer
+    const emailsToExclude = new Set([
+      ...originalRescheduledBookingTeamMembers.map((user) => user?.email),
+      ...invitee.map((user) => user?.email),
+      ...bookerAddedGuests,
+    ]);
+
+    originalRescheduledBookingAttendees
+      .filter((attendee) => !emailsToExclude.has(attendee.email))
+      .map((guest) =>
```
Comment (TusharBhatt1) [inline packages/features/bookings/lib/handleNewBooking.ts:950]: _.map()_ is typically used for transforming arrays, but here it’s being used for side effects (pushing to organizerAddedGuests). 
Can replace it with ._forEach()_ ,  making the intent clearer.

**Comment by TusharBhatt1** [comment]
The current logic filters out team members, booker, and booker-added guests from the original booking's attendees to identify "guests added by organizer".
However, this approach might not be robust because :
It assumes all remaining attendees are "organizer-added guests"
It doesn't definitively distinguish between truly organizer-added guests and other potential attendees
Guest identification relies solely on email exclusion, which could lead to false positives

Or I am missing something ?

File: packages/features/bookings/lib/handleNewBooking.ts (hunk 1 above)
Comment (TusharBhatt1) [inline packages/features/bookings/lib/handleNewBooking.ts:950]: `.forEach()` is more appropriate here

**Comment by TusharBhatt1** [comment]
@kart1ka LGTM , once the comment is resolved , let's take this ahead

**Comment by kart1ka** [comment]
> @kart1ka tested and LGTM , once the comment is resolved , let's take this ahead

Done

**Review by TusharBhatt1 — APPROVED** [review]
Tested works well , LGTM !

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 2]
```diff
@@ -899,7 +901,69 @@ async function handler(
...
+    const isSameRRHost = !!originalRescheduledBooking?.userId && eventType.rescheduleWithSameRoundRobinHost;
+
+    // Get the list of team members for original rescheduled booking
+    const originalRescheduledBookingTeamMembers = (
+      isTeamEventType && eventType.schedulingType === SchedulingType.ROUND_ROBIN && !isSameRRHost
+        ? [...users.slice(0, -1), originalRoundRobinHost]
+        : [...users]
+    ).filter((user) => user?.email !== organizerUser.email);
+
+    // Get guests that were added by the booker in the original booking
```
Comment (anikdhabal) [inline packages/features/bookings/lib/handleNewBooking.ts:935]: @kart1ka Is this the right place for the changes? I think we should fix the addGuest handler and find out why it is causing this error. It should be similar to how we normally do it from the booking page/
