### PR TITLE
added auto animate to installed apps, fixed container size

### LINKED ISSUE #4507: /installed-apps: use auto animate when switching categories
https://app.cal.com/apps/installed/calendar

### PR DESCRIPTION
**Pull request by PeerRich**
before:

https://user-images.githubusercontent.com/8019099/207979398-7828702a-c4cf-4303-81f0-6e4ccf2d8a57.mp4

after:
https://user-images.githubusercontent.com/8019099/207979257-b5610e45-84c8-43d1-acc9-6e21fc5c7263.mp4

### CODE REVIEW

File: packages/ui/v2/modules/booker/DatePicker.tsx [hunk 1]
```diff
@@ -229,6 +229,7 @@ const DatePicker = ({
           <button
             type="button"
             className="group p-1 opacity-50 hover:opacity-100"
+            w
```
Comment (zomars) [inline packages/ui/v2/modules/booker/DatePicker.tsx:232]:
```suggestion
```

**Review by zomars — APPROVED** [review]
Ship it

File: packages/ui/v2/modules/booker/DatePicker.tsx (hunk 1 above)
Comment (PeerRich) [reply packages/ui/v2/modules/booker/DatePicker.tsx]: oops
