### PR TITLE
fix: allow backtracking while adding new time slots in availability

### LINKED ISSUE #9743: Cannot add multiple time slots
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A second time slot cannot be added to the last-day entry. Screen recording attached

### Steps to Reproduce
See the recording for clarification

1. Land on the default Cal management page
2. Go to Availability
3. Select Default Availability
4. Offtopic: Notice the time delay between the mouse click and the actual page load (relates to https://github.com/calcom/cal.com/issues/9742)
5. On the last day in the list (Saturday for me), make sure only one entry is there. Now try adding a second slot
6. Nothing would happen (unexpected)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Users should be able to add the time slot.

### Technical details

- Google Chrome Version 114.0.5735.134 (Official Build) (64-bit)
- 

https://github.com/calcom/cal.com/assets/11042267/37bbe033-c7ec-4a1f-b940-51d591a8e8e2

### PR DESCRIPTION
**Pull request by anmol242**
## What does this PR do?
**Issue -** Currently when the user selects `11.59 pm or the end time for which the difference between 11.59 pm and the selected end time is less than one hour`, it doesn't allow to add new time slot.
**Changes -** 
-  `Cal.com` will allow to add the slot until the start and end of the day meaning from 12.00 am - 11.59 pm.
-   It will keep adding slots while it is existing doing until the last of day time slot, when those are done and there no last time slot left it will backtrack and start adding the slot before the first start time until 12.00 am
-  Same fix applies on Date overrides slots too

Fixes [# 9743](https://github.com/calcom/cal.com/issues/9743)

 Loom Video: https://www.loom.com/share/0b8b9f136e2f4826981d3b7b0ede75e6?sid=e6dbac37-efbf-41e9-aba5-2649e7ad8860

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

See loom video: https://www.loom.com/share/0b8b9f136e2f4826981d3b7b0ede75e6?sid=e6dbac37-efbf-41e9-aba5-2649e7ad8860

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by anmol242** [comment]
@keithwillcode can I get review on this PR?

File: packages/features/schedules/components/Schedule.tsx [hunk 1]
```diff
@@ -193,8 +193,18 @@ export const DayRanges = <TFieldValues extends FieldValues>({
...
+                    getValues(`${name}.${fields.length - 1}`),
+                    getValues(`${name}.0`)
+                  );
+
+                  if (slotRange?.append) {
+                    append(slotRange.append);
+                  }
+
+                  if (slotRange?.prepend) {
+                    prepend(slotRange.prepend);
```
Comment (anmol242) [inline packages/features/schedules/components/Schedule.tsx:206]: Once the slot end time will reach `11.59 pm` it will start prepending the slots meaning my first slot is 11.00 am -12.00 pm. I still have slot windows before 11.00 am so I will start prepending the slots. See loom video for more clarity

**Comment by anmol242** [comment]
@Udit-takkar or someone from team can I get a review on this PR?

**Comment by anmol242** [comment]
@Udit-takkar , @PeerRich or some one from team can I get a review on this PR?

**Review by CarinaWolli — APPROVED** [review]
Nice work, looks good to me. Thank you for your contribution 🙏
