### PR TITLE
fix: correct month after changing time zone

### LINKED ISSUE #5607: [CAL-410] Different month showing once I switch to the timezone ahead of my own on the booking page
[https://app.birdeatsbug.com/sessions/NpQFOvTCGYnwn4LiZT9O8qU2v6pD5mvr2iHl9fagSZtA](https://app.birdeatsbug.com/sessions/NpQFOvTCGYnwn4LiZT9O8qU2v6pD5mvr2iHl9fagSZtA) [https://app.birdeatsbug.com/sessions/NpQFOvTCGYnwn4LiZT9O8qU2v6pD5mvr2iHl9fagSZtA](https://app.birdeatsbug.com/sessions/NpQFOvTCGYnwn4LiZT9O8qU2v6pD5mvr2iHl9fagSZtA)

Created via Threads. See full discussion: [https://threads.com/messages/3ac5f762-2e64-4651-afa9-375ad13192ae?messageID=b17e5c69-94ee-4d19-9909-5db1ce21d7cd](https://threads.com/messages/3ac5f762-2e64-4651-afa9-375ad13192ae?messageID=b17e5c69-94ee-4d19-9909-5db1ce21d7cd)

> From [SyncLinear.com](https://synclinear.com) | [CAL-410](https://linear.app/calcom/issue/CAL-410/different-month-showing-once-i-switch-to-the-timezone-ahead-of-my-own)

### PR DESCRIPTION
**Pull request by Udit-takkar**
Signed-off-by: Udit Takkar <udit.07814802719@cse.mait.ac.in>

## What does this PR do?

Fixes: https://github.com/calcom/cal.com/issues/5607

https://user-images.githubusercontent.com/53316345/203311565-ca7b8003-2e71-4bac-956e-d4686fe57f3c.mov

### CODE REVIEW

File: packages/ui/v2/modules/booker/DatePicker.tsx [hunk 1]
```diff
@@ -138,9 +138,10 @@ const DatePicker = ({
       onMonthChange(browsingDate.add(newMonth, "month"));
     }
   };
-
   const month = browsingDate
-    ? new Intl.DateTimeFormat(i18n.language, { month: "long" }).format(new Date(browsingDate.toISOString()))
+    ? new Intl.DateTimeFormat(i18n.language, { month: "long" }).format(
+        new Date(browsingDate.year(), browsingDate.month())
```
Comment (Udit-takkar) [inline packages/ui/v2/modules/booker/DatePicker.tsx:143]: so at browsing date that we pass is starting day of the month and if we change timezone it could happen a case that browsing date becomes 31 oct. 

but this so

**Review by CarinaWolli — APPROVED** [review]
Tested and it works 👍

**Comment by PeerRich** [comment]
@emrysal is this ok i merged this?
