### PR TITLE
fix: Embed Issues: Logo causing scroll, Logo text color, mobile view with layout configuration

### LINKED ISSUE #9831: [CAL-2064] New Booker in Embed: The branding logo bug
* The logo is causing scrollbar to appear in embed.
* Also the logo text color should be dark for Inline Embed and light for Modal based embeds as they have dark overlay.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2064](https://linear.app/calcom/issue/CAL-2064/new-booker-in-embed-the-branding-logo-bug)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes the blockers for new-booker to be enabled for embeds.

Fixes #9830
Fixes #9831

Non Embed View - Light
Screenshot 2023-06-28 at 2 51 53 PM

Non Embed View - Dark
Screenshot 2023-06-28 at 2 52 27 PM

Modal Embed - Light
Screenshot 2023-06-28 at 2 53 34 PM

Modal Embed - Dark
Screenshot 2023-06-28 at 2 54 07 PM

Embed Inline - Dark
image

Embed Inline - Light
image

Embed WeekView(when configured through instruction) - On Mobile
Screenshot 2023-06-28 at 3 05 33 PM

Embed Column View(when configured through instruction) - On Mobile
image

Embed Month View(when configured through instruction) - On Mobile
image

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
See the screenshots above in different scenarios. Those are the tests.

## Mandatory Tasks
- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/features/bookings/Booker/Booker.tsx [hunk 1]
```diff
@@ -133,14 +136,14 @@ const BookerComponent = ({
       {event.data ? <BookingPageTagManager eventType={event.data} /> : null}
       <div
         className={classNames(
+          // In a popup embed, if someone clicks outside the main(having main class or main tag), it closes the embed
+          "main",
```
Comment (hariombalhara) [inline packages/features/bookings/Booker/Booker.tsx:140]: Moved to the wrapper containing the branding logo as well.

**Comment by PeerRich** [comment]
seems good, whats missing?

**Comment by hariombalhara** [comment]
> seems good, whats missing?

Testing. Done now.

File: packages/embeds/embed-core/src/embed-iframe.ts [hunk 2]
```diff
@@ -257,7 +257,7 @@ function getNamespace() {
     return embedStore.namespace;
   }
   if (isBrowser) {
-    const namespace = window?.getEmbedNamespace?.() || null;
+    const namespace = window?.getEmbedNamespace?.() ?? null;
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed-iframe.ts:260]: It was causing a false alarm in logs.

File: packages/features/bookings/Booker/Booker.tsx [hunk 3]
```diff
@@ -241,6 +245,7 @@ const BookerComponent = ({
           key="logo"
           className={classNames(
             "mb-6 mt-auto pt-6 [&_img]:h-[15px]",
+            hasDarkBackground ? "dark" : "",
```
Comment (hariombalhara) [inline packages/features/bookings/Booker/Booker.tsx:248]: Adding dark class here would cause logo image to invert automatically as it has `dark:invert` class

File: packages/features/bookings/Booker/Booker.tsx [hunk 4]
```diff
@@ -48,10 +48,14 @@ const BookerComponent = ({
   const [_layout, setLayout] = useBookerStore((state) => [state.layout, state.setLayout], shallow);
 
   const isEmbed = useIsEmbed();
+  const embedType = useEmbedType();
+  // Floating Button and Element Click both are modal and thus have dark background
+  const hasDarkBackground = isEmbed && embedType !== "inline";
```
Comment (hariombalhara) [inline packages/features/bookings/Booker/Booker.tsx:53]: In case of inline background depends on the website embedding the embed.

**Review by PeerRich — APPROVED** [review]
