### PR TITLE
fix: payload cleanup

### LINKED ISSUE #13549: [CAL-3082] eventTypes/getByViewer regression on v3.7.12
rel #13002

It seems like we're having a increased payload on latest release. It is causing this endpoint to fail. This is what we have on the runtime logs:

```
[PERF]: getByViewer(109147) took 402.34358200000133ms
API response for /api/trpc/eventTypes/getByViewer?batch=1&input={"0":{"json":{"filters":{"teamIds":[REDACTED],"upIds":null,"userIds":null}},"meta":{"values":{"filters.upIds":["undefined"],"filters.userIds":["undefined"]}}}} exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[ERROR] [1707184498477] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 413.
```

There's also a potential leakage of password of your team members as well.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3082](https://linear.app/calcom/issue/CAL-3082/eventtypesgetbyviewer-regression-on-v3712)</sub>

### PR DESCRIPTION
**Pull request by zomars**
## What does this PR do?

fixes #13549 

Managed to reduced the payload to 1MB. Also made sure to avoid leaking password or other sensitive info.

image

Fixes # (issue)

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Tests (Unit/Integration/E2E or any other test)
- This change requires a documentation update

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/lib/server/repository/user.ts [hunk 1]
```diff
@@ -136,7 +188,7 @@ export class UserRepository {
     return { where, profiles };
   }
 
-  static async findByEmailAndIncludeProfiles({ email }: { email: string }) {
+  static async findByEmailAndIncludeProfilesAndPassword({ email }: { email: string }) {
```
Comment (hariombalhara) [inline packages/lib/server/repository/user.ts:191]: Changed name to convey that it has password

File: packages/lib/server/repository/user.ts [hunk 2]
```diff
@@ -12,14 +13,64 @@ import { getParsedTeam } from "./teamUtils";
...
+
+const teamSelect = Prisma.validator<Prisma.TeamSelect>()({
+  id: true,
+  name: true,
+  slug: true,
+  metadata: true,
+  logoUrl: true,
+});
+
+const userSelect = Prisma.validator<Prisma.UserSelect>()({
```
Comment (hariombalhara) [inline packages/lib/server/repository/user.ts:25]: Added userSelect to not include password by default.

**Review by keithwillcode — APPROVED** [review]

File: apps/api/pages/api/event-types/[id]/_get.ts [hunk 3]
```diff
@@ -51,7 +51,6 @@ export async function getHandler(req: NextApiRequest) {
     include: {
       customInputs: true,
       team: { select: { slug: true } },
-      users: true,
```
Comment (zomars) [inline apps/api/pages/api/event-types/[id]/_get.ts:54]: @keithwillcode we should select fields instead of removing. This will omit participants from the api response
