### PR TITLE
fix(app-store): Giphy Ux fixes

### LINKED ISSUE #2682: UI Improvements to the Giphy App
### Is your proposal related to a problem?

The current implementation of the Giphy app has some UI inconsistencies.

I've proposed updates in the following design:
https://www.figma.com/file/6sITaSOZ2JCXyKEYhC10P5/%F0%9F%96%B1-Cal-Web-App?node-id=6293%3A99883

### PR DESCRIPTION
**Pull request by with-shrey**
## What does this PR do?
Fixes UX/UI as per Figma designs

Fixes #2682 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## How should this be tested?

    Install the Giphy app from App Store
    Create a new event or use any existing event type
    Click on "Show advanced settings" & scroll to the bottom
    Press search on the Giphy button which should open a popup
    On the popup type something in the search box and press search
    You can use the next & prev icons to see more gifs
    After selecting one press Save
    the selected Gif should be visible on the event edit page
    Press the update button on the page
    Preview this event and schedule a time, the gif should be visible on the success page
   
   To Search By URL use the gif URL from here 
image

# Screenshots

Screenshot 2022-05-17 at 4 54 00 PM
Screenshot 2022-05-17 at 4 53 47 PM

Screenshot 2022-05-17 at 4 53 41 PM

### CODE REVIEW

**Comment by joeauyeung** [comment]
Hey @with-shrey thanks for working on the Giphy app! I noticed you added the search gif function but you're missing some of the smaller UI fixes in the Figma file in the discussion. I would start with the first row in the Figma file.

File: packages/app-store/giphy/api/get.ts [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+    if (!matches || matches.length < 2) {
+      return res.status(422).json({ message: "Giphy URL is invalid" });
+    }
+    const giphyId = matches[1];
+    const gifImageUrl = await GiphyManager.getGiphyById(giphyId);
+    return res.status(200).json({ image: gifImageUrl });
+  } catch (error: unknown) {
+    console.error({ error });
+    if (error instanceof Error) {
+      return res.status(500).json({ message: error.message });
```
Comment (zomars) [inline packages/app-store/giphy/api/get.ts:36]: If we error because the url is invalid we should return a 400 error. A 500 indicates that something crashed on our side and that's not the case here.

File: packages/app-store/giphy/api/get.ts [hunk 2]
```diff
@@ -0,0 +1,60 @@
+import type { NextApiRequest, NextApiResponse } from "next";
+import { z, ZodError } from "zod";
+
+import prisma from "@calcom/prisma";
+
+import { GiphyManager } from "../lib";
+
+const getSchema = z.object({
+  url: z.string(),
```
Comment (zomars) [inline packages/app-store/giphy/api/get.ts:9]: We could do something like this:

```suggestion
  url: z.string().regex(giphyUrlRegexp),
```

**Review by zomars — CHANGES_REQUESTED** [review]
Overall very good! Let's address some of the comments so we can merge 🙏

File: packages/app-store/giphy/api/get.ts (hunk 2 above)
Comment (with-shrey) [reply packages/app-store/giphy/api/get.ts]: Nice catch! 
Fixed that

**Comment by with-shrey** [comment]
@joeauyeung I have made the UI changes.
Can you please review and let me know if i have missed something

File: packages/app-store/giphy/lib/giphyManager.ts [hunk 3]
```diff
@@ -4,10 +4,14 @@ import getAppKeysFromSlug from "../../_utils/getAppKeysFromSlug";
 
 let api_key = "";
 
-export const searchGiphy = async (locale: string, keyword: string, offset: number = 0) => {
+const getGiphyApiKey = async () => {
```
[the remark this answers is not in the document]
Comment (zomars) [reply packages/app-store/giphy/lib/giphyManager.ts:7]: `checkGiphyApiKey`?

[the remark this answers is not in the document]
Comment (with-shrey) [reply packages/app-store/giphy/lib/giphyManager.ts]: Yeah guess that would be the best of both worlds 😅

Let me know if there is anything else

**Review by zomars — DISMISSED** [review]

**Comment by joeauyeung** [comment]
Everything looks good so far! Just two things.

1. Is there a way to remove these scrollbars? I noticed you used the dialog component from our UI library so I'm not sure why they are popping up here
image

2. I tried adding a GIF from a link and it threw an error. I tried copying the URL of the link and by clicking share ->  copy GIF link

**Review by zomars — COMMENTED** [review]
Testing on preview

- Pressing enter here should submit the search form
  image
- We might need to tweak the regex
  image

File: apps/web/public/static/locales/en/common.json [hunk 4]
```diff
@@ -827,6 +827,11 @@
   "go_to_app_store": "Go to App Store",
   "calendar_error": "Something went wrong, try reconnecting your calendar with all necessary permissions",
   "calendar_no_busy_slots": "There are no busy slots",
+  "add_gif": "Add GIF",
+  "search_giphy": "Search Giphy",
+  "add_link_from_giphy": "Add link from Giphy",
+  "add_gif_to_confirmation": "Adding a GIF to confirmation page",
+  "find_gif_spice_confirmation": "Find GIF to spice up your confirmation page"
```
Comment (zomars) [inline apps/web/public/static/locales/en/common.json:834]:
```suggestion
  "find_gif_spice_confirmation": "Find GIF to spice up your confirmation page",
```

**Comment by with-shrey** [comment]
@joeauyeung I am not able to reproduce the scrollbars can you please share browser details etc 

@zomars 
- I have wrapped the input within a `form` that seems to handle the entry submittion
- And fixed the regex it was kinda complicated to read. looks good now

**Comment by joeauyeung** [comment]
@with-shrey I'm on Chrome Version 101.0.4951.64 (Official Build) (64-bit)

**Review by joeauyeung — APPROVED** [review]
@with-shrey I revisited this and my concerns have been addressed. LGTM

**Review by hariombalhara — APPROVED** [review]
Works well. Looks awesome. Thanks for the contribution @with-shrey !!

**Comment by with-shrey** [comment]
Looking forward to more @hariombalhara @joeauyeung 📅
