### PR TITLE
fix: add spacing between form and submit button in TeamEventTypeForm

### LINKED ISSUE #24698: Add spacing between form fields and submit button in TeamEventTypeForm
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The submit button in the TeamEventTypeForm component lacks proper visual spacing from the form fields above it, causing poor visual hierarchy and UX. The form uses space-y-6 for field spacing but doesn't apply bottom padding to create separation before the submit button, making the layout feel cramped.

### Steps to Reproduce

1. Navigate to /settings/teams/[teamId]/event-type (Create Team Event Type page)
2. Observe the form layout with scheduling type radio buttons
3. Notice the submit button appears immediately after the last form field with no spacing

### Actual Results

- The submit button is positioned directly after the form fields with no visual separation
- The form container div (line 49) uses mt-1 space-y-6 but lacks bottom margin
- This creates inconsistent spacing where internal fields have 24px gaps (space-y-6) but the button has no separation

### Expected Results

- The submit button should have consistent spacing that matches the internal form field gaps (space-y-6 = 1.5rem/24px)
- Adding mb-6 to the form container div creates proper bottom padding
- This maintains visual hierarchy and improves the user experience

### Technical details

Environment:
- Browser: Chrome (latest)
- Node.js version: v18+
- Cal.com version: Latest main branch

### Evidence

- Form fields have 24px spacing between them (via space-y-6)
- Submit button has 0px spacing above it
- Inconsistent visual rhythm
- 

Image

### PR DESCRIPTION
**Pull request by Shrey-Sutariya**
## What does this PR do?

- Fixes #24698 
- Fixes CAL-6642

## Visual Demo (For contributors especially)

A visual demonstration is strongly recommended, for both the original and new change **(video / image - any one)**.

#### Video Demo (if applicable):

- Show screen recordings of the issue or feature.
- Demonstrate how to reproduce the issue, the behavior before and after the change.

#### Image Demo (if applicable):

- Before change.
- 
image
-After change 
image

- Highlight any significant change(s).

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

---
## Summary by cubic
Added vertical spacing between the form and the submit button in TeamEventTypeForm to prevent the button from touching the last input and improve readability.

This wraps the SubmitButton in a div with mt-6 to match form spacing.

### CODE REVIEW

**Review by dhairyashiil — CHANGES_REQUESTED** [review]
Please address the comments, making it draft until then. Also please create a issue for the same as well. and mention the issue number and linear number in description later

File: packages/features/ee/teams/components/TeamEventTypeForm.tsx
Comment (dhairyashiil) [inline packages/features/ee/teams/components/TeamEventTypeForm.tsx]: Add padding to bottom here, to match existing pattern

File: packages/features/ee/teams/components/TeamEventTypeForm.tsx [hunk 1]
```diff
@@ -158,7 +158,7 @@ export const TeamEventTypeForm = ({
           </RadioArea.Group>
         </div>
       </div>
-      {SubmitButton(isPending)}
+      <div className="mt-6">{SubmitButton(isPending)}</div>
```
Comment (dhairyashiil) [inline packages/features/ee/teams/components/TeamEventTypeForm.tsx]: undo this

File: packages/features/ee/teams/components/TeamEventTypeForm.tsx
Comment (Shrey-Sutariya) [reply packages/features/ee/teams/components/TeamEventTypeForm.tsx]: Updated to match existing pattern,please check

File: packages/features/ee/teams/components/TeamEventTypeForm.tsx (hunk 1 above)
Comment (Shrey-Sutariya) [reply packages/features/ee/teams/components/TeamEventTypeForm.tsx]: Done

**Review by dhairyashiil — APPROVED** [review]
LGTM 👍🏼 , Thank you.
