### PR TITLE
fix: webhooks for managed event types

### LINKED ISSUE #10940: trigger user and team webhooks for managed events
### Issue Summary

Currently, for managed event types only the team webhook triggeres. We also want the user webhooks to trigger. Same with Zapier, a managed event type should trigger for the team and the user.

### PR DESCRIPTION
**Pull request by CarinaWolli**
## What does this PR do?

Webhooks for managed event types should trigger for team webhooks and user webhooks. Before they only triggerd for team webhooks. Also fixes that listBookings (for Zapier) now returns bookings from managed events when using user or team API key. 

Fixes #10940

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Create a managed event type
- Create a team webhook and a user webhook that triggers when booking is created (use webhook.site)
- Book managed event type, see that webhooks triggered twice (once for users, once for team)
- Test other webhook triggers + test booking normal user event type and team event type (round robin, collective)

### CODE REVIEW

File: packages/app-store/zapier/api/subscriptions/listBookings.ts [hunk 1]
```diff
@@ -22,8 +22,15 @@ async function handler(req: NextApiRequest, res: NextApiResponse) {
...
     const where: Prisma.BookingWhereInput = {};
-    if (validKey.teamId) where.eventType = { teamId: validKey.teamId };
-    else where.userId = validKey.userId;
+    if (validKey.teamId) {
+      where.eventType = {
+        OR: [{ teamId: validKey.teamId }, { parent: { teamId: validKey.teamId } }],
+      };
+    } else {
+      where.userId = validKey.userId;
+      s;
```
Comment (zomars) [inline packages/app-store/zapier/api/subscriptions/listBookings.ts:31]:
```suggestion
```

**Review by zomars — APPROVED** [review]
LGTM
