### PR TITLE
fix: Duplicate Calendar Invites on rescheduling an accepted booking that requires confirmation

### LINKED ISSUE #8444: [CAL-1694] Duplicate events when using the event approval feature.
### Issue Summary

If I have event approval turned on (so that new events don't get added until I approve them) and someone reschedules an event, I get an approval request for the reschedule and the event gets rescheduled automatically as well. The moment I approve the reschedule via the email I receive, cal.com ends up creating two events for the same time but with two separate video call-in details (they are essentially two events), which ends up confusing me and the attendees.

### Steps to Reproduce

1. Turn on event approval in settings
2. Invite someone to request a new meeting
3. Accept/approve this meeting
4. Ask the person to reschedule
5. Approve the reschedule request

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
→ I don't expect two events to be created.

### Technical details

- MS Edge on MacOS (both on their respective latest versions as of this writing).

<sub>[CAL-1694](https://linear.app/calcom/issue/CAL-1694/duplicate-events-when-using-the-event-approval-feature)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #8444

Reason behind the issue was simply that the code always assumed that rescheduling would move the calendar invite to new time but in case of a booking that requires confirmation it is not true as the booking goes to PENDING state on reschedule.

Added a test as well for the flow
Before Fix  - [Loom](https://www.loom.com/share/d9560369d7f14306a7a1b34f1be5eeca)
After Fix - [Loom](https://www.loom.com/share/c1dc9bccd6cc4ab0abbc8dcb56133810)

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
- Turn on event approval in settings
- Do a booking as booker
- Accept the booking as organizer
- Reschedule the booking as booker. At this point notice that the calendar event didn't get cancelled, it just moved to new time without confirmation from organizer.
- Confirm the new booking. Now, you would see two calendar invites.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: packages/core/CalendarManager.ts [hunk 1]
```diff
@@ -366,14 +366,34 @@ export const updateEvent = async (
   };
 };
 
-export const deleteEvent = async (
```
Comment (hariombalhara) [inline packages/core/CalendarManager.ts:369]: It was unused method, started using it and fixed it.

File: packages/core/EventManager.ts [hunk 2]
```diff
@@ -466,13 +621,9 @@ export default class EventManager {
         (credential) => credential.id === event.conferenceCredentialId
       );
     } else {
-      videoCredential = this.videoCredentials
-        // Whenever a new video connection is added, latest credentials are added with the highest ID.
-        // Because you can't rely on having them in the highest first order here, ensure this by sorting in DESC order
-        .sort((a, b) => {
```
Comment (hariombalhara) [inline packages/core/EventManager.ts:472]: Sort does the sorting in place, so it modifies `this.videoCredentials` itself. Moved this sorting to constructor to make it clear.

File: packages/core/EventManager.ts [hunk 3]
```diff
@@ -281,24 +360,37 @@ export default class EventManager {
...
 
-    // There was a case that booking didn't had any reference and we don't want to throw error on function
-    if (booking.references.find((reference) => reference.type.includes("_calendar"))) {
-      // Update all calendar events.
-      results.push(...(await this.updateAllCalendarEvents(evt, booking, newBookingId)));
+      const bookingCalendarReference = booking.references.find((reference) =>
+        reference.type.includes("_calendar")
+      );
+      // There was a case that booking didn't had any reference and we don't want to throw error on function
+      if (bookingCalendarReference) {
```
Comment (hariombalhara) [inline packages/core/EventManager.ts:390]: Extracted out in a variable.

File: packages/core/EventManager.ts [hunk 4]
```diff
@@ -281,24 +360,37 @@ export default class EventManager {
...
+        // Update all calendar events.
+        results.push(...(await this.updateAllCalendarEvents(evt, booking, newBookingId)));
+      }
```
Comment (hariombalhara) [inline packages/core/EventManager.ts:393]: Moved existing code into this else condition

File: packages/core/EventManager.ts [hunk 5]
```diff
@@ -281,24 +360,37 @@ export default class EventManager {
...
+      const isDedicated = evt.location ? isDedicatedIntegration(evt.location) : null;
+      // If and only if event type is a dedicated meeting, update the dedicated video meeting.
+      if (isDedicated) {
+        const result = await this.updateVideoEvent(evt, booking);
+        const [updatedEvent] = Array.isArray(result.updatedEvent)
+          ? result.updatedEvent
+          : [result.updatedEvent];
+
+        if (updatedEvent) {
+          evt.videoCallData = updatedEvent;
```
Comment (hariombalhara) [inline packages/core/EventManager.ts:380]: Moved existing code into this else condition

File: apps/web/test/utils/bookingScenario/bookingScenario.ts [hunk 6]
```diff
@@ -318,6 +314,15 @@ async function addBookings(bookings: InputBooking[]) {
           },
         };
       }
+      if (booking.attendees) {
```
Comment (hariombalhara) [inline apps/web/test/utils/bookingScenario/bookingScenario.ts:317]: Support creating fake attendees as well.

File: apps/web/test/utils/bookingScenario/bookingScenario.ts [hunk 7]
```diff
@@ -888,6 +895,11 @@ export function mockCalendar(
               url: "https://UNUSED_URL",
             });
           },
+          deleteEvent: async (...rest: any[]) => {
+            log.silly("mockCalendar.deleteEvent", JSON.stringify({ rest }));
```
Comment (hariombalhara) [inline apps/web/test/utils/bookingScenario/bookingScenario.ts:899]: Verify deleteEvent calls

File: apps/web/test/utils/bookingScenario/bookingScenario.ts [hunk 8]
```diff
@@ -998,15 +1013,19 @@ export function mockVideoApp({
...
-                  JSON.stringify({ bookingRef, calEvent })
-                );
+                log.silly("MockVideoApiAdapter.updateMeeting", JSON.stringify({ bookingRef, calEvent }));
                 return Promise.resolve({
                   type: appStoreMetadata[metadataLookupKey as keyof typeof appStoreMetadata].type,
                   ...videoMeetingData,
                 });
               },
+              deleteMeeting: async (...rest: any[]) => {
+                log.silly("MockVideoApiAdapter.deleteMeeting", JSON.stringify(rest));
```
Comment (hariombalhara) [inline apps/web/test/utils/bookingScenario/bookingScenario.ts:1023]: Allow verifying deleteMeeting calls

File: packages/core/EventManager.ts [hunk 9]
```diff
@@ -91,7 +96,14 @@ export default class EventManager {
...
     this.calendarCredentials = appCredentials.filter((cred) => cred.type.endsWith("_calendar"));
-    this.videoCredentials = appCredentials.filter((cred) => cred.type.endsWith("_video"));
+    this.videoCredentials = appCredentials
+      .filter((cred) => cred.type.endsWith("_video"))
+      // Whenever a new video connection is added, latest credentials are added with the highest ID.
+      // Because you can't rely on having them in the highest first order here, ensure this by sorting in DESC order
+      // We also don't have updatedAt or createdAt dates on credentials so this is the best we can do
+      .sort((a, b) => {
+        return b.id - a.id;
+      });
```
Comment (hariombalhara) [inline packages/core/EventManager.ts:106]: Moved here from other place.

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 10]
```diff
@@ -979,10 +979,45 @@ async function handler(
...
+    loggerWithEventDetails.debug(
+      "user can reschedule without confirmation",
+      safeStringify({
+        isOrganizerRescheduling: isBeingBookedByOrganizer,
+        userReschedulingIsOwner,
+        originalRescheduledBooking,
+        isConfirmedByDefault,
+      })
+    );
+  }
```
Comment (hariombalhara) [inline packages/features/bookings/lib/handleNewBooking.ts:1017]: Placed all requiresConfirmation related logic here as it was becoming really difficult to debug when these variables were being set.

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 11]
```diff
@@ -979,10 +979,45 @@ async function handler(
 
   const allCredentials = await getAllCredentials(organizerUser, eventType);
 
-  const isOrganizerRescheduling = organizerUser.id === userId;
```
Comment (hariombalhara) [inline packages/features/bookings/lib/handleNewBooking.ts:982]: Renamed `isOrganizerRescheduling` to `isBeingBookedByOrganizer` because it isn't just possibly true for rescheduling. It can also be true for fresh booking.

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 12]
```diff
@@ -979,10 +979,45 @@ async function handler(
...
+   */
+  const userReschedulingIsOwner = userId && originalRescheduledBooking?.user?.id === userId;
+
+  /**
+   * Tells that the user doing booking(fresh or reschedule) is logged in as the organizer of the event
+   */
+  const isBeingBookedByOrganizer = organizerUser.id === userId;
+
+  const canBookWithoutConfirmation = isBeingBookedByOrganizer || userReschedulingIsOwner;
+  const isConfirmedByDefault = (!requiresConfirmation && !paymentAppData.price) || canBookWithoutConfirmation;
```
Comment (hariombalhara) [inline packages/features/bookings/lib/handleNewBooking.ts:1005]: Instead of using `userReschedulingIsOwner`, now we are using canBookWithoutConfirmation so that the user who is rescheduling is the organizer of the event, he can still reschedule without confirmation. He doesn't just need to be the owner of the previous booking.

A test was failing earlier, which is passing now.

File: packages/features/bookings/lib/handleNewBooking/test/reschedule.test.ts [hunk 13]
```diff
@@ -604,5 +613,700 @@ describe("handleNewBooking", () => {
...
+              }),
+            },
+            uid: "MOCK_ID",
+          });
+        },
+        timeout
+      );
+
+      // eslint-disable-next-line playwright/no-skipped-test
+      test.skip(
```
Comment (hariombalhara) [inline packages/features/bookings/lib/handleNewBooking/test/reschedule.test.ts:817]: Wrote the following 2 tests but they were failing as there is bug in identifying properly when an organizer reschedules the booking. Fill fix it in a followup PR as that's taking time.

**Review by CarinaWolli — APPROVED** [review]
Tested and works. Code looks good as well 🙏
