### PR TITLE
fix: Unable to invite a user to a team via username

### LINKED ISSUE #15853: Unable to invite a user to a team via username
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Email or username is shown as label for email input , while adding new team members
Invite fails while using a username
### Steps to Reproduce

1. Navigate to members page of team : /settings/teams/{id}/members
2. Click on Add ( present at top right )
3. provide username as input 
4. Click send invite 
5. Invite fails even if username has been registered 

### Actual Results

- Invite fails when using username

### Expected Results

- Invite via username should be possible if username exists

### Evidence
[
Screenshot from 2024-07-21 20-30-52
](url)

### PR DESCRIPTION
**Pull request by Souptik2001**
## What does this PR do?

- Fixes #15853 (GitHub issue number)
- Fixes CAL-XXXX (N/A)

Old video - `https://www.loom.com/share/3728e0c81bec44a79b5eca54169c6294?sid=6105f4e3-ce2b-4230-bd44-4d6dfccf5b31`

New video -

https://www.loom.com/share/f75dc72f098e4a569bed6bd6bc9cf6c5?sid=1b2d6379-5f05-4717-ab26-d2711f40d2e1

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Create a team.
- Now try to add a member to the team (maybe from here - `http://localhost:3000/settings/teams/<team_id>/members`)
- Instead of writing email, write the username of an existing user.
- It should successfully invite the existing user with username.

### CODE REVIEW

**Comment by Souptik2001** [comment]
This might require some tests to be updated. Will update it once someone validates the approach. 👍

File: packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts [hunk 1]
```diff
@@ -178,14 +178,10 @@ export async function findUsersWithInviteStatus({
...
+        // Either it's a username with organization as null in the main user table.
         {
-          profiles: {
-            some: {
-              organizationId: team.id,
-              username: { in: usernamesOrEmails },
-            },
-          },
+          username: { in: usernamesOrEmails },
+          organizationId: null,
```
[the remark this answers is not in the document]
Comment (anikdhabal) [reply packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts:184]: Ah, this is not the correct way. You can no longer invite users using usernames in a team within the organization. Your code is almost correct, but the catch is that instead of setting the organizationId to null, we need to do it like this :- 
```
const orgInfo = team.isOrganization && {
  organizationId: team.id,
}
```
and then 

```
{ username: { in: usernamesOrEmails }, ...orgInfo }, { email: { in: usernamesOrEmails } }

```

And yes, usernames are also unique. However, our job isn't finished yet. There might be functions or hooks that only allow email invitations and don't account for usernames, so you might encounter some undefined errors.

Here are my thoughts on this. Please let me know what you think and try to solve it using my suggestion. If you have any other methods to solve this, feel free to share.

**Review by anikdhabal — CHANGES_REQUESTED** [review]

**Review by anikdhabal — CHANGES_REQUESTED** [review]
Left a comment. Pls address it

**Comment by hariombalhara** [comment]
I don't see a compelling reason to support username again. We earlier supported it but with organizations which allow having same username in different organizations, it easily becomes confusing and problematic.

I would prefer to just update the label to say Email and support username when there is a usecase for it.

cc @PeerRich @ciaranha what do you guys think ?

**Review by hariombalhara — DISMISSED** [review]
I have some concerns that need to be addressed

File: packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (Souptik2001) [reply packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts:184]: @anikdhabal

> Still, you cannot invite users using usernames in a team within the organization.

Yup correct!

I have made some different change instead of the one you mentioned above.

The code you gave particularly this one -

```
const orgInfo = team.isOrganization && {
    organizationId: team.id,
  };
```
This one seems to address when you are adding an user to "an organization" not a "team of an organization".
And while I agree that currently you can't add an user to an organization, but that's disabled in front-end also -

Screenshot 2024-07-23 at 3 08 39 PM

That's why I think we can handle that case later, in a different PR. What do you think?

With my last commit I have added some changes to support adding users to team or an organization also.

cc: @hariombalhara

**Comment by Souptik2001** [comment]
@hariombalhara Yes I agree there is a chance of username might be colliding in that case. 👍 

FYI it currently looks like this with the last commit (in org) - 


https://github.com/user-attachments/assets/5fd51a7c-71d5-45bf-9ce4-432aac157feb

**Comment by anikdhabal** [comment]
@Souptik2001 i am also agree with Hariom, let address his requested changes.

**Comment by Souptik2001** [comment]
Ok sure @anikdhabal!

I am currently working on this one - https://github.com/calcom/cal.com/issues/15776
Almost done! Will be completed today.

Will do this one after that. 👍

File: packages/features/ee/teams/pages/team-members-view.tsx [hunk 2]
```diff
@@ -206,6 +206,7 @@ const MembersView = () => {
               orgMembers={orgMembersNotInThisTeam}
               members={team.members}
               teamId={team.id}
+              justEmailInvites={true}
```
Comment (anikdhabal) [inline packages/features/ee/teams/pages/team-members-view.tsx:209]: Hey, there's no need to add any new props. If we find a use case to re-add the username in the future, we can manage that at that time. For now, just remove the conditional rendering for the label and only add 'enter_email'

**Review by anikdhabal — CHANGES_REQUESTED** [review]

File: packages/features/ee/teams/pages/team-members-view.tsx (hunk 2 above)
Comment (Souptik2001) [reply packages/features/ee/teams/pages/team-members-view.tsx:209]: @anikdhabal Ok! One question - `justEmailInvites` prop is already present in the `MemberInvitationModal` component. So, should I just remove that prop also from there, along with the conditional renderings?

Comment (anikdhabal) [reply packages/features/ee/teams/pages/team-members-view.tsx:209]: Yeah, pls remove that.

Comment (Souptik2001) [reply packages/features/ee/teams/pages/team-members-view.tsx]: @anikdhabal Done!

Also FYI - Updated the video of the PR description.

Comment (anikdhabal) [reply packages/features/ee/teams/pages/team-members-view.tsx]: Great

**Review by anikdhabal — APPROVED** [review]
LGTM
