### PR TITLE
fix: remove ts-ignore by converting to string[]

### LINKED ISSUE #14621: Simplify logic by removing unnecessary // ts-ignore
In `packages/platform/sdk/src/lib/entpoints/getEndpointData`

The `endpointData.constructUri` expects `string[]` and the code is forcefully converting `Record<string,string>` to `string[]` and suppressing with // ts-ignore

#### Suggestions

Either combine both if and else if and convert params to `string[]` to get rid of  ts-ignore OR 
make endpointData.constructUri accept `string[] | Record<string,string>`

Screenshot 2024-04-17 at 3 53 32 AM

### PR DESCRIPTION
**Pull request by kaleem68**
## What does this PR do?

It removes ts-ignore by combining if and else if conditions into if condition.

Fixes #14621 

The solution follows a suggestion mentioned in the suggestion of #14621 

Screenshot 2024-04-17 at 4 14 01 AM

ts ignore warning is removed successfully. 

## Type of change
- Chore (refactoring code, technical debt, workflow improvements)

### CODE REVIEW

**Comment by emrysal** [comment]
Closing this as it's possible that the parameter is an object - but the typescript is a little bit hard due to constructUri overloading.

**Comment by emrysal** [comment]
@kaleem68 I committed in a potential fix for your consideration also

File: packages/platform/sdk/src/lib/endpoints.ts [hunk 1]
```diff
@@ -9,19 +9,19 @@ type BaseEndpointDeclaration = {
 // Define a type for static URIs
 type StaticUriEndpoint = BaseEndpointDeclaration & {
   uri: string;
-  constructUri?: never; // Ensure constructUri is not used here
+  constructUriFromObject?: never;
+  constructUriFromArray?: never;
 };
```
Comment (kaleem68) [inline packages/platform/sdk/src/lib/endpoints.ts:15]: Create a type for convenience to remove verbosity
`type StrArrOrRecordStrStr = string[] | Record<string, string>;`

File: packages/platform/sdk/src/lib/endpoints.ts [hunk 2]
```diff
@@ -9,19 +9,19 @@ type BaseEndpointDeclaration = {
...
-  constructUri: (params: ParamsType) => string;
+  constructUriFromArray?: (params: string[]) => string;
+  constructUriFromObject?: (params: Record<string, string>) => string;
 };
 
 // Create a discriminated union of the two types, incorporating generics
-type EndpointDeclaration<ParamsType extends Record<string, string> | string[] = string[]> =
-  | StaticUriEndpoint
-  | DynamicUriEndpoint<ParamsType>;
+type EndpointDeclaration = StaticUriEndpoint | DynamicUriEndpoint;
```
Comment (kaleem68) [inline packages/platform/sdk/src/lib/endpoints.ts:24]: // Define a type for to avoid verbosity
`type StrArrOrRecordStrStr = string[] | Record<string, string>;`

File: packages/platform/sdk/src/lib/endpoints.ts [hunk 3]
```diff
@@ -50,29 +50,37 @@ const publicEndpoint = (uri: string, version = ApiVersion.NEUTRAL): EndpointDecl
...
-// Adjust the constructor to use generics for flexible parameter typing
-const publicEndpointConstructor = <ParamsType extends Record<string, string> | string[]>(
-  constructUri: (params: ParamsType) => string,
-  version = ApiVersion.NEUTRAL
-): EndpointDeclaration<ParamsType> => ({
-  constructUri,
-  auth: "public",
-  apiVersion: version,
-});
+const constructUri = (
```
Comment (kaleem68) [inline packages/platform/sdk/src/lib/endpoints.ts:53]: constructUri params can be simplified

#### Suggestion
```
const constructUri = (endpointData: EndpointDeclaration, params: StrArrOrRecordStrStr) => {
  if (endpointData.constructUriFromObject && isParamsRecord(params)) {
    return endpointData.constructUriFromObject(params);
  }
  if (endpointData.constructUriFromArray && Array.isArray(params)) {
    return endpointData.constructUriFromArray(params);
  }
  throw new Error("Invalid parameter type for dynamic endpoint.");
};
 ```

Comment (kaleem68) [reply packages/platform/sdk/src/lib/endpoints.ts:53]: Similarly update params for  `getEndpointData`

#### Suggestion

```
export const getEndpointData = (
  endpoint: Endpoints,
  params?: StrArrOrRecordStrStr
)
```

**Review by kaleem68 — COMMENTED** [review]
@emrysal I have made a few suggestions based on your commit.

I would be happy if we could get one more review from calcom team member on your changes.

**Review by emrysal — APPROVED** [review]
Looks great to me, thanks for this follow up 🙏
