### PR TITLE
Fix no video reference on google-meet

### LINKED ISSUE #8765: [CAL-1633] Seated event not generating Google Meet URL for each subsequently booked seat.
Screenshot 2023-05-09 at 10 03 52
Screenshot 2023-05-09 at 10 04 28
Once the first seat has been booked, Google Meet URL is in both confirmation email and google calendar as intended. However, once each subsequent seat is booked Google Meet URL isn't there anymore for both the attendee and the organizer.
Created via Threads. See full discussion: [https://threads.com/34471280408](https://threads.com/34471280408)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1633](https://linear.app/calcom/issue/CAL-1633/seated-event-not-generating-google-meet-url-for-each-subsequently)</sub>

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?
Google Calendar with Google Meet it's handled different than others, as for creating a google meet link you need to have google calendars credentials.

- Add video booking reference for google_meet created with same credential as google calendar.
- Also if google meet is created we add meetingUrl to bookingReference under type calendar.

Fixes #8765 8765

**Environment**: Staging(main branch) / Production

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Install Google Calendar 
- [ ] Install Google Meet
- [ ] Create a Seated event
- [ ] Change location to Google Meet
- [ ] Reserve multiple slots and every email should have the same google meet Url.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 1]
```diff
@@ -1955,6 +1959,20 @@ async function handler(
...
+
+            // Add google_meet to referencesToCreate in the same index as google_calendar
+            createManager.referencesToCreate[googleCalIndex] = {
+              ...createManager.referencesToCreate[googleCalIndex],
+              meetingUrl: googleCalResult.createdEvent.hangoutLink,
+            };
+
+            // Also create a new referenceToCreate with type video for google_meet
+            createManager.referencesToCreate.push({
+              type: "google_meet_video",
```
Comment (alannnc) [inline packages/features/bookings/lib/handleNewBooking.ts:1971]: reference should include _video at the end to be considered as video app.

**Review by zomars — APPROVED** [review]
LGTM
