### PR TITLE
Fix app categories

### LINKED ISSUE #5963: [CAL-575] Apps Admin Panel: Some apps appear as disabled when they're not
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-575](https://linear.app/calcom/issue/CAL-575/apps-admin-panel-some-apps-appear-as-disabled-when-theyre-not)</sub>

### PR DESCRIPTION
**Pull request by joeauyeung**
## What does this PR do?

This PR aims to replace `category` with `categories` in apps still using the depreciated field. This caused errors in the admin apps screen. This PR also optimizes how the `allApps` component gets it's category fields.

Fixes #5963

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- On an admins account go to the Admin -> Apps page in the settings.
- Under the "other" category, only apps labelled as "other" should appear

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

File: apps/web/pages/apps/index.tsx [hunk 1]
```diff
@@ -52,7 +52,11 @@ export default function Apps({
           <TrendingAppsSlider items={appStore} />
         </>
       )}
-      <AllApps apps={appStore} searchText={searchText} />
+      <AllApps
+        apps={appStore}
+        searchText={searchText}
+        categories={categories.map((category: string) => category.name)}
```
Comment (joeauyeung) [inline apps/web/pages/apps/index.tsx:58]: Pass categories down to the all apps component since we already get this value server side.

File: packages/ui/v2/core/apps/AllApps.tsx [hunk 2]
```diff
@@ -124,18 +128,13 @@ function CategoryTab({ selectedCategory, categories, searchText }: CategoryTabPr
...
   const router = useRouter();
   const { t } = useLocale();
   const [selectedCategory, setSelectedCategory] = useState<string | null>(null);
   const [appsContainerRef, enableAnimation] = useAutoAnimate<HTMLDivElement>();
 
-  const categories = apps
-    .map((app) => app.category)
-    .filter((cat, pos, self) => {
-      return self.indexOf(cat) === pos;
-    });
```
Comment (joeauyeung) [inline packages/ui/v2/core/apps/AllApps.tsx:137]: By passing down categories as a prop, we don't need to loop through all the apps on the frontend.

**Review by PeerRich — APPROVED** [review]

File: apps/web/pages/apps/index.tsx (hunk 1 above)
Comment (zomars) [inline apps/web/pages/apps/index.tsx:58]:
```suggestion
        categories={categories.map((category) => category.name)}
```

File: packages/app-store/utils.ts [hunk 3]
```diff
@@ -76,7 +76,10 @@ export function getLocationGroupedOptions(integrations: ReturnType<typeof getApp
   const apps: Record<string, { label: string; value: string; disabled?: boolean; icon?: string }[]> = {};
   integrations.forEach((app) => {
     if (app.locationOption) {
-      const category = app.category;
+      // All apps that are labeled as a locationOption are video apps. Extract the secondary category if available
+      let category =
+        app.categories.length >= 2 ? app.categories.find((category) => category !== "video") : app.category;
+      if (!category) category = "video";
```
Comment (joeauyeung) [inline packages/app-store/utils.ts:82]: @zomars @Udit-takkar made a change here since an app might not have the `category` field. Also added a consideration if an app belongs in another category ex. Huddle01

image

File: apps/web/pages/apps/categories/[category].tsx [hunk 4]
```diff
@@ -47,13 +47,7 @@ export default function Apps({ apps }: InferGetStaticPropsType<typeof getStaticP
 }
 
 export const getStaticPaths = async () => {
-  const appStore = await getAppRegistry();
-  const paths = appStore.reduce((categories, app) => {
-    if (!categories.includes(app.category)) {
-      categories.push(app.category);
-    }
-    return categories;
-  }, [] as string[]);
```
Comment (joeauyeung) [inline apps/web/pages/apps/categories/[category].tsx:56]: Since we're just getting the app categories we don't need to loop through all apps, we can just use the enum from the schema. This will also help with performance.

File: packages/app-store/larkcalendar/_metadata.ts [hunk 5]
```diff
@@ -11,6 +11,7 @@ export const metadata = {
   imageSrc: "/api/app-store/larkcalendar/icon.svg",
   variant: "calendar",
   category: "calendar",
```
Comment (hariombalhara) [inline packages/app-store/larkcalendar/_metadata.ts:13]: We can remove this one as well

File: packages/app-store/jitsivideo/_metadata.ts [hunk 6]
```diff
@@ -9,6 +9,7 @@ export const metadata = {
   type: "jitsi_video",
   imageSrc: "/api/app-store/jitsivideo/icon.svg",
   variant: "conferencing",
+  categories: ["video"],
   logo: "/api/app-store/jitsivideo/icon.svg",
```
Comment (hariombalhara) [inline packages/app-store/jitsivideo/_metadata.ts:13]: Corresponding `category` property not removed.

File: packages/app-store/utils.ts [hunk 7]
```diff
@@ -76,7 +76,10 @@ export function getLocationGroupedOptions(integrations: ReturnType<typeof getApp
   const apps: Record<string, { label: string; value: string; disabled?: boolean; icon?: string }[]> = {};
   integrations.forEach((app) => {
     if (app.locationOption) {
-      const category = app.category;
+      // All apps that are labeled as a locationOption are video apps. Extract the secondary category if available
+      let category =
+        app.categories.length >= 2 ? app.categories.find((category) => category !== "video") : app.category;
```
Comment (hariombalhara) [inline packages/app-store/utils.ts:81]: I am confused. Aren't we removing the `category` field in this PR?

File: apps/web/pages/apps/index.tsx [hunk 8]
```diff
@@ -52,7 +52,11 @@ export default function Apps({
           <TrendingAppsSlider items={appStore} />
         </>
       )}
-      <AllApps apps={appStore} searchText={searchText} />
+      <AllApps
+        apps={appStore}
+        searchText={searchText}
+        categories={categories.map((category: typeof categories[number]) => category.name)}
```
Comment (zomars) [inline apps/web/pages/apps/index.tsx:58]:
```suggestion
        categories={categories.map((category) => category.name)}
```
If inferred types are failing let's fix that instead

File: packages/ui/v2/core/apps/AllApps.tsx [hunk 9]
```diff
@@ -37,7 +37,11 @@ export function useShouldShowArrows() {
   return { ref, calculateScroll, leftVisible: showArrowScroll.left, rightVisible: showArrowScroll.right };
 }
 
-type AllAppsPropsType = { apps: (App & { credentials: Credential[] | undefined })[]; searchText?: string };
+type AllAppsPropsType = {
+  apps: (App & { credentials: Credential[] | undefined })[];
```
Comment (zomars) [inline packages/ui/v2/core/apps/AllApps.tsx:41]: I'm just noticing. Why do we need credentials in the frontend? If this a leak?

**Review by zomars — APPROVED** [review]
Fixed types, added code to avoid leaks and LGTM 

Ship it  

Thanks again @joeauyeung 🙏🏽
