### PR TITLE
fixes toggle

### LINKED ISSUE #4245: /event-type-detail /recurring - toggle goes down a row when active
Image

### PR DESCRIPTION
**Pull request by agustif**
## What does this PR do?

Fixes #4245 

## Type of change
image

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
Go to a recurring event, checkbox should stay on top and not move down now

### CODE REVIEW

File: apps/web/components/eventtype/RecurringEventController.tsx [hunk 1]
```diff
@@ -47,8 +47,8 @@ export default function RecurringEventController({
           <Alert severity="warning" title={t("warning_payment_recurring_event")} />
         ) : (
           <>
-            <div className="relative flex items-start">
-              <div className="flex h-5 items-center">
+            <div className="absolute flex items-start">
```
Comment (zomars) [inline apps/web/components/eventtype/RecurringEventController.tsx:50]: Is the absolute needed? Shouldn't flex-start suffice?

Comment (PeerRich) [reply apps/web/components/eventtype/RecurringEventController.tsx:50]: agree. i dont think absolute should be used here. it would be better to stay flex but in the same container so it doesn't move down

**Review by PeerRich — CHANGES_REQUESTED** [review]
dont use absolute, instead stay in flex but move the switch into the headline container

File: apps/web/components/eventtype/RecurringEventController.tsx (hunk 1 above)
Comment (agustif) [reply apps/web/components/eventtype/RecurringEventController.tsx:50]: oops yes! removing wasn't meant to be on the commit and from previous testing

**Comment by agustif** [comment]
yeah removed that absolute as it wasn't needed, forgot to remove it from previous testing, fixed it now!

**Review by PeerRich — APPROVED** [review]

**Comment by PeerRich** [comment]
great stuff, thanks!
