### PR TITLE
fix: Issues with scheduling timezone change without end time

### LINKED ISSUE #19095: [CAL-5127] Issues with scheduling timezone change without end time
1. Broken UI in dark mode

2. Add button always stays disabled. Probably because it expects the end time to be set

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-5127](https://linear.app/calcom/issue/CAL-5127/issues-with-scheduling-timezone-change-without-end-time)</sub>

### PR DESCRIPTION
**Pull request by nayan-bagale**
## What does this PR do?

- Fixes Broken Ui in dark mode
- Fixes Add button always stays disabled.
- Fixes #19095 (GitHub issue number)
- Fixes CAL-5127 (Linear issue number - should be visible at the bottom of the GitHub issue description)

Before:
[Screencast from 2025-02-05 01-53-37.webm](https://github.com/user-attachments/assets/1a2652de-8b52-4ab9-819f-5a8d44e98369)

After:
[Screencast from 2025-02-05 01-57-22.webm](https://github.com/user-attachments/assets/fa19d853-caca-4467-95ec-0eb94058477d)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by nayan-bagale** [comment]
Hey @CarinaWolli , I’ve changed the `DatePicker` code and added the `Calendar.tsx` component to handle single-day selection. Since `Calendar.tsx` is now being reused, should I remove the test cases for DatePicker?

**Comment by nayan-bagale** [comment]
Hey @CarinaWolli , I’ve changed the `DatePicker` code and added the `Calendar.tsx` component to handle single-day selection. Since `Calendar.tsx` is now being reused, So i removed the test cases for DatePicker?

File: packages/ui/components/form/datepicker/DatePicker.tsx [hunk 1]
```diff
@@ -1,10 +1,10 @@
...
-import PrimitiveDatePicker from "react-date-picker/dist/entry.nostyle";
+import * as Popover from "@radix-ui/react-popover";
+import { format } from "date-fns";
 
-import classNames from "@calcom/lib/classNames";
+import { classNames as cn } from "@calcom/lib";
 
-import { Icon } from "../../icon";
+import { Button } from "../../button";
+import { Calendar } from "../date-range-picker/Calendar";
```
Comment (TusharBhatt1) [inline packages/ui/components/form/datepicker/DatePicker.tsx:7]: Try using absolute imports

File: packages/ui/components/form/datepicker/datepicker.test.tsx [hunk 2]
```diff
@@ -1,44 +0,0 @@
-/* eslint-disable playwright/missing-playwright-await */
```
Comment (TusharBhatt1) [inline packages/ui/components/form/datepicker/datepicker.test.tsx:1]: Why deleted this file , instead a test as per the current implementation is recommended

File: packages/ui/components/form/datepicker/DatePicker.tsx [hunk 3]
```diff
@@ -15,20 +15,45 @@ type Props = {
...
-      onChange={onDatesChange}
     />
   );
+
+  return (
+    <div className={cn("grid gap-2", className)}>
+      <Popover.Root>
+        <Popover.Trigger asChild>
+          <Button
+            data-testid="date-range"
```
Comment (TusharBhatt1) [inline packages/ui/components/form/datepicker/DatePicker.tsx:41]: Ideally should be "pick-date" or similar

File: packages/ui/components/form/datepicker/DatePicker.tsx (hunk 1 above)
Comment (nayan-bagale) [reply packages/ui/components/form/datepicker/DatePicker.tsx:7]: I did tried, but it give import error
Screenshot from 2025-02-20 23-13-16

so basically we cannot use absolute imports because the components are in the same package `@calcom/ui`

**Review by TusharBhatt1 — COMMENTED** [review]
@nayan-bagale can you add these changes exactly : https://github.com/calcom/cal.com/pull/19418/commits/9ecf7be2030fc65260902f7821398bccfa17aa44
And then let’s take this ahead

**Review by TusharBhatt1 — APPROVED** [review]
