### PR TITLE
fix: add tooltip, truncate

### LINKED ISSUE #5075: Whereby URL needs wrapping
Found a bug? Please fill out the sections below. 👍

Using a whereby URL as a location doesn’t look so good on the calendar view.

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

Wrap the text to not overflow on the calendar
This can be seen here: https://cal.com/patrickludewig/30min

[image](https://user-images.githubusercontent.com/88032331/196442978-7bc1d1b4-ee0a-41f2-892a-d80bd4727e1f.png)

### PR DESCRIPTION
**Pull request by Udit-takkar**
Fixes #5075 

https://user-images.githubusercontent.com/53316345/196696858-29cfcd5f-0116-4daa-a461-4a99a23d6b1c.mov

made changes suggested here https://github.com/calcom/cal.com/issues/5075#issuecomment-1283128271

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

navigate to /[user]/[type] and check location url

### CODE REVIEW

File: apps/web/components/booking/AvailableEventLocations.tsx [hunk 1]
```diff
@@ -1,5 +1,6 @@
 import { getEventLocationType, locationKeyToString } from "@calcom/app-store/locations";
 import { classNames } from "@calcom/lib";
+import { Tooltip } from "@calcom/ui/Tooltip";
```
Comment (PeerRich) [inline apps/web/components/booking/AvailableEventLocations.tsx:3]:
```suggestion
import Tooltip from "@calcom/ui/v2/core/Tooltip";
```

**Review by PeerRich — COMMENTED** [review]
use new tooltip

**Review by PeerRich — APPROVED** [review]
