### PR TITLE
Fix: EventType crash when Moving up and down beyond boundaries

### LINKED ISSUE #7743: [CAL-1259] Event Type Page crashed on reordering Booking Questions
Issue re-ordering. To recreate, I had to move things a few times, but the first time it happened on first re-order, when I moved name below email. Let me know if you need help recreating Hariom

(Attachment: )

Created via Threads. See full discussion: [https://threads.com/34455732616](https://threads.com/34455732616)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1259](https://linear.app/calcom/issue/CAL-1259/event-type-page-crashed-on-reordering-booking-questions)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #7743
Disable buttons that allow going beyond boundaries

Before:
Screenshot 2023-03-16 at 9 28 04 AM
Screenshot 2023-03-16 at 9 28 30 AM

After:
Screenshot 2023-03-16 at 9 28 59 AM
Screenshot 2023-03-16 at 9 29 14 AM

**Environment**: Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [x] Try moving beyond the last and first items.

### CODE REVIEW

File: packages/features/form-builder/FormBuilder.tsx [hunk 1]
```diff
@@ -287,18 +287,22 @@ export const FormBuilder = function FormBuilder({
                 key={index}
```
Comment (emrysal) [inline packages/features/form-builder/FormBuilder.tsx:287]:
```suggestion
                key={field.name}
```

**Review by emrysal — APPROVED** [review]
NIT because unrelated, but key={index} on a re-indexable list causes full list remounts on every move event. key={field.name} is stable (and I believe uniq) and you'll find it's much more performant 🙏

**Comment by hariombalhara** [comment]
@emrysal Fully agreed. Applied the change.
