### PR TITLE
fix: #15474 retrieve zoom usersettings and update zoom integration

### LINKED ISSUE #15474: [CAL-3943] Zoom integration doesn't follow the zoom app settings for auto-record
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3943](https://linear.app/calcom/issue/CAL-3943/zoom-integration-doesnt-follow-the-zoom-app-settings-for-auto-record)</sub>

### PR DESCRIPTION
**Pull request by vijayraghav-io**
## What does this PR do?

- Fixes #15474 
- Fixes CAL-3943

This is generic implementation with zoomUserSettingsSchema defined , any future zoomUserSettings retrieval and corresponding logic update for create/update meetings or any.. can be easily extended.

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

### CODE REVIEW

**Comment by vijayraghav-io** [comment]
all checks passed

File: packages/app-store/zoomvideo/lib/VideoApiAdapter.ts [hunk 1]
```diff
@@ -59,6 +59,45 @@ export const zoomMeetingsSchema = z.object({
   ),
 });
 
+export type ZoomUserSettings = z.infer<typeof zoomUserSettingsSchema>;
+
+/** @link https://developers.zoom.us/docs/api/rest/reference/user/methods/#operation/userSettings */
+export const zoomUserSettingsSchema = z.object({
```
Comment (joeauyeung) [inline packages/app-store/zoomvideo/lib/VideoApiAdapter.ts:65]: I noticed we're only using the password and auto record settings. When making the API call can we filter for just those two properties.

**Review by joeauyeung — CHANGES_REQUESTED** [review]
Thanks for your contribution @vijayraghav-io. I just have one blocking comment.

File: packages/app-store/zoomvideo/lib/VideoApiAdapter.ts (hunk 1 above)
Comment (vijayraghav-io) [reply packages/app-store/zoomvideo/lib/VideoApiAdapter.ts:65]: sure

Comment (vijayraghav-io) [reply packages/app-store/zoomvideo/lib/VideoApiAdapter.ts:65]: updated as per doc - https://developers.zoom.us/docs/api/rest/reference/user/methods/#operation/userSettings
Screenshot 2024-06-21 at 10 00 17 PM

Comment (joeauyeung) [reply packages/app-store/zoomvideo/lib/VideoApiAdapter.ts:65]: Awesome, can we also then clean up `zoomUserSettingsSchema` to only the fields we're filtering on. It'll help make reading the file easier.

Comment (vijayraghav-io) [reply packages/app-store/zoomvideo/lib/VideoApiAdapter.ts:65]: I can clean up.
I thought in future if any more settings is required to be retrieved , we already have the schema defined, need not again refer or search the zoom api doc.
Please share your thoughts.

Comment (vijayraghav-io) [reply packages/app-store/zoomvideo/lib/VideoApiAdapter.ts:65]: @joeauyeung , updated

Comment (joeauyeung) [reply packages/app-store/zoomvideo/lib/VideoApiAdapter.ts:65]: Our thought process is we only want code that is being used. If we need to access different user settings we can always add to the schema in the future.

File: packages/app-store/zoomvideo/lib/VideoApiAdapter.ts [hunk 2]
```diff
@@ -257,13 +269,23 @@ const ZoomVideoApiAdapter = (credential: CredentialPayload): VideoApiAdapter =>
...
+      let userSettings: ZoomUserSettings | undefined;
+      try {
+        const filterResp = "default_password_for_scheduled_meetings,auto_recording";
+        const responseBody = await fetchZoomApi(`users/me/settings?custom_query_fields=${filterResp}`);
+        userSettings = zoomUserSettingsSchema.parse(responseBody);
+      } catch (err) {
+        console.error(err);
+        /* If user settings could not be retrieved due to error in like - api scope configurations,
+         just continue create meeting with default settings*/
+      }
```
Comment (joeauyeung) [inline packages/app-store/zoomvideo/lib/VideoApiAdapter.ts:281]: Since we're repeating this functionality, can we abstract this into its own function? Maybe we can call that function inside of translate event.

Also we have to add a new scope to our Zoom app. If a user has not reauthenticated then that means this will always throw an error. can we add proper logging if that is the case?

File: packages/app-store/zoomvideo/lib/VideoApiAdapter.ts (hunk 1 above)
Comment (vijayraghav-io) [reply packages/app-store/zoomvideo/lib/VideoApiAdapter.ts:65]: ok

File: packages/app-store/zoomvideo/lib/VideoApiAdapter.ts (hunk 2 above)
Comment (vijayraghav-io) [reply packages/app-store/zoomvideo/lib/VideoApiAdapter.ts:281]: sure will do

**Comment by vijayraghav-io** [comment]
Hi @joeauyeung , all comments are addressed, reminding you on this PR.

**Comment by CarinaWolli** [comment]
> Hi @joeauyeung , all comments are addressed, reminding you on this PR.

@joeauyeung can you take a look again 🙏

**Comment by vijayraghav-io** [comment]
@joeauyeung , can you please review the required changes done and approve

**Review by joeauyeung — APPROVED** [review]
Sorry for the delay, every thing looks good @vijayraghav-io. Thanks again for your contribution

**Comment by vijayraghav-io** [comment]
> Sorry for the delay, every thing looks good @vijayraghav-io. Thanks again for your contribution

Thankyou! @joeauyeung 🙏

**Comment by milospuac** [comment]
@joeauyeung @vijayraghav-io 

Looks like this isn't fixed, auto record is still not engaging once the meeting starts 
Screenshot 2024-08-21 at 08 49 25

**Comment by vijayraghav-io** [comment]
I guess the specific scopes have to be enabled/added for cal app to access the zoom user settings. 

https://developers.zoom.us/docs/api/rest/reference/user/ma/#operation/userSettings
Screenshot 2024-08-21 at 12 49 14 PM

https://developers.zoom.us/docs/integrations/oauth-scopes-overview/
