### PR TITLE
Fix bug for reschedule on opt-in bookings

### LINKED ISSUE #3595: Rescheduling an Opt-in booking bypasses opt-in and doesn't add rescheduled event to calendar
### Issue Summary
An opt-in booking when rescheduled is automatically “accepted“ but doesn’t show up on the calendar (double jeopardy)

### Steps to Reproduce
1. Book an opt-in booking
2. Reschedule it to a different slot (date or time). Note that the rescheduled booking is accepted even if the initial booking wasn’t.
4. Check your calendar for the rescheduled time (not there)
5. The host can also still accept the original request and end up with two bookings in cal.

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

- Fixes opt-in reschedule as user attendee.
- Fixes reschedule option from being blocked any time. This text form should be always enabled.

Fixes #3595

https://www.loom.com/share/3a452dcd0852464392937b92a16c5661

**Environment**: Staging(main branch) / Production

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Create an event with opt-in option
- [ ] Book it with a new user
- [ ] Confirm it as an owner
- [ ] From user email of booking submitted try to reschedule from "Manage this booking" option
- [ ] You should as owner see the new rescheduled booking with Pending status.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: apps/web/components/booking/pages/BookingPage.tsx [hunk 1]
```diff
@@ -218,11 +218,25 @@ const BookingPage = ({
     ? booking?.attendees.slice(1).map((attendee) => attendee.email)
     : [];
 
+  // There should only exists one default userData variable for primaryAttendee.
```
Comment (alannnc) [inline apps/web/components/booking/pages/BookingPage.tsx:221]: There were several declaration tries to get user attendee default name, wether it came from booking or query param. With these we only declare/obtain it once.

File: apps/web/components/booking/pages/BookingPage.tsx [hunk 2]
```diff
@@ -428,7 +442,7 @@ const BookingPage = ({
     }
   };
 
-  const disableInput = !!rescheduleUid;
+  const disableInput = !!defaultUserValues.email && !!defaultUserValues.name;
```
Comment (alannnc) [inline apps/web/components/booking/pages/BookingPage.tsx:445]: There was a case when no default user data was obtain neither query nor booking data, so input text field shouldn't be disabled in this case.

File: apps/web/pages/api/book/event.ts [hunk 3]
```diff
@@ -214,6 +215,9 @@ const getEventTypesFromDB = async (eventTypeId: number) => {
 type User = Prisma.UserGetPayload<typeof userSelect>;
 
 async function handler(req: NextApiRequest) {
+  const session = await getSession({ req });
+  const currentUser = session?.user;
```
Comment (alannnc) [inline apps/web/pages/api/book/event.ts:219]: I'm using session here so if the user that it's triggering the reschedule of an opt-in booking it's the host it should be Accepted as a status and no pending since he has chosen a new time for the booking.

File: packages/core/builders/CalendarEvent/builder.ts [hunk 4]
```diff
@@ -314,7 +314,7 @@ export class CalendarEventBuilder implements ICalendarEventBuilder {
 
       const queryParams = new URLSearchParams();
       queryParams.set("rescheduleUid", `${booking.uid}`);
-      slug = `${slug}?${queryParams.toString()}`;
+      slug = `${slug}`;
```
Comment (alannnc) [inline packages/core/builders/CalendarEvent/builder.ts:317]: This was causing mismatch for rescheduleUid while obtaining original booking.

**Review by leog — APPROVED** [review]
Looks good, thanks for the Loom

**Review by zomars — APPROVED** [review]
Nice job @alannnc

**Comment by alannnc** [comment]
e2e failed on reschedule test, investigating it right now.

File: apps/web/components/booking/pages/AvailabilityPage.tsx [hunk 5]
```diff
@@ -285,10 +285,14 @@ const dateQuerySchema = z.object({
...
   const router = useRouter();
-  const query = z.object({ [name]: z.string().optional() }).parse(router.query);
+  const existingQueryParams = router.asPath.split("?")[1];
+
+  const urlParams = new URLSearchParams(existingQueryParams);
+  const query = Object.fromEntries(urlParams);
 
   const setQuery = (newValue: string | number | null | undefined) => {
     router.replace({ query: { ...router.query, [name]: newValue } }, undefined, { shallow: true });
+    router.replace({ query: { ...router.query, ...query, [name]: newValue } }, undefined, { shallow: true });
```
Comment (alannnc) [inline apps/web/components/booking/pages/AvailabilityPage.tsx:295]: This are the changed I mentioned you @zomars

File: apps/web/playwright/reschedule.test.ts [hunk 6]
```diff
@@ -155,4 +154,45 @@ test.describe("Reschedule Tests", async () => {
 
     await payment.delete();
   });
+
+  test("Opt in event should be PENDING when rescheduled by USER", async ({ page, users, bookings }) => {
```
Comment (alannnc) [inline apps/web/playwright/reschedule.test.ts:158]: Added test to prove my fix

**Comment by alannnc** [comment]
@zomars Added playwright test to prove my fix works and don't break anything. Should be ready to merge when all green.
