### PR TITLE
fix:  New Team Members Join Org as OWNER/ADMIN

### LINKED ISSUE #13773: [CAL-3171] New Team Members Join Org as OWNER/ADMIN
Found a bug? Please fill out the sections below. 👍

### Issue Summary

invite a new team member to a sub-team in an org as an OWNER/ADMIN, notice how the player also joins the org with that role.

### Steps to Reproduce

1. create an org
2. create a new team in that org
3. to to team/[teamId]/members page - ignore the weird layout of page, created another issue for that
4. add a new team member to that team as ADMIN/OWNER

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- the new team member also joins the org with the selected role itself

### Expected Results

- we want that member to be a admin/owner of that team only not the entire organization

### Evidence

[LOOM](https://www.loom.com/share/2cce8b2c87a347678eaf0a5ca9528660?sid=93054cfa-7f8b-4bf0-a79a-04848be15cda)

<sub>[CAL-3171](https://linear.app/calcom/issue/CAL-3171/new-team-members-join-org-as-owneradmin)</sub>

### PR DESCRIPTION
**Pull request by ibex088**
## What does this PR do?

Fixes #13773

### CODE REVIEW

File: packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts [hunk 1]
```diff
@@ -285,7 +285,7 @@ export async function createNewUsersConnectToOrgIfExists({
             data: {
               teamId: parentId,
               userId: createdUser.id,
-              role: input.role as MembershipRole,
+              role: MembershipRole.MEMBER,
```
Comment (Udit-takkar) [inline packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts:288]: So earlier if you invite someone to team as admin then we would also assign admin role of complete org too?

Comment (SomayChauhan) [reply packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts:288]: Yes

**Review by CarinaWolli — APPROVED** [review]
Looks good, thank you for this fix 🙏
