### PR TITLE
fix: added brand hover for dates

### LINKED ISSUE #9838: [CAL-2068] UI: make hover brand color
[https://github.com/calcom/cal.com/assets/8019099/5d7cc736-20b9-4159-8bed-81e6ee93db01](https://github.com/calcom/cal.com/assets/8019099/5d7cc736-20b9-4159-8bed-81e6ee93db01)

this should be brand:

[https://github.com/calcom/cal.com/assets/8019099/3617c2c4-c248-4c4b-b004-f4c061215506](https://github.com/calcom/cal.com/assets/8019099/3617c2c4-c248-4c4b-b004-f4c061215506)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2068](https://linear.app/calcom/issue/CAL-2068/ui-make-hover-brand-color)</sub>

### PR DESCRIPTION
**Pull request by PeerRich**
CleanShot 2023-07-05 at 00 02 26@2x

### CODE REVIEW

File: packages/features/bookings/components/AvailableTimes.tsx [hunk 1]
```diff
@@ -86,7 +86,7 @@ export const AvailableTimes = ({
               data-disabled={bookingFull}
               data-time={slot.time}
               onClick={() => onTimeSelect(slot.time)}
-              className="min-h-9 mb-2 flex h-auto w-full flex-col justify-center py-2"
+              className="min-h-9 hover:border-brand-default mb-2 flex h-auto w-full flex-col justify-center py-2 "
```
Comment (emrysal) [inline packages/features/bookings/components/AvailableTimes.tsx:89]:
```suggestion
              className="min-h-9 hover:border-brand-default mb-2 flex h-auto w-full flex-col justify-center py-2"
```

**Review by emrysal — APPROVED** [review]
lgtm
