### PR TITLE
fix: duplicate workflow reminders caused by scanWorkflowBody

### LINKED ISSUE #21559: Fix duplicate workflow reminders
Workflow updates can cause duplicate reminders because of several scanWorkflow body tasks waiting in the tasker.

### PR DESCRIPTION
**Pull request by CarinaWolli**
## What does this PR do?

If a workflow is saved multiple times within a short period, the tasker will have multiple scanWorkflowBody tasks, each creating a reminder. This results in duplicate workflow reminders.

- Fixes #21559
- Fixes CAL-5844

    

---

## Summary by cubic
Fixed duplicate workflow reminders by ensuring only the latest scanWorkflowBody task creates a reminder for each workflow step.

- **Bug Fixes**
  - Added a check to skip scan tasks if a newer one exists for the same workflow step.
  - Updated task creation to use one task per workflow step with a timestamp.

### CODE REVIEW

File: packages/features/tasker/tasks/scanWorkflowBody.ts [hunk 1]
```diff
@@ -11,18 +12,39 @@ import { scheduleWorkflowNotifications } from "@calcom/trpc/server/routers/viewe
...
+    JSON.parse(payload)
+  );
+
+  const stepIdsToScan: number[] = workflowStepIds ? workflowStepIds : [];
+
+  if (workflowStepId && !workflowStepIds) {
+    if (createdAt) {
+      const newerTask = await Task.findNewerScanTaskForStepId(workflowStepId, createdAt);
+
+      if (newerTask) return;
```
Comment (CarinaWolli) [inline packages/features/tasker/tasks/scanWorkflowBody.ts]: returns early if a newer tasks for this workflow step exists --> Task suceeds but workflow step is not marked as verified yet

File: packages/trpc/server/routers/viewer/workflows/update.handler.ts [hunk 2]
```diff
@@ -467,11 +471,15 @@ export const updateHandler = async ({ ctx, input }: UpdateOptions) => {
     );
 
     if (SCANNING_WORKFLOW_STEPS) {
-      // workflows are scanned then scheduled in the task
-      await tasker.create("scanWorkflowBody", {
-        workflowStepIds: createdSteps.map((step) => step.id),
-        userId: ctx.user.id,
-      });
+      await Promise.all(
+        createdSteps.map((step) =>
```
Comment (CarinaWolli) [inline packages/trpc/server/routers/viewer/workflows/update.handler.ts:475]: Creating a seperate task for each workflow step makes it easier to query for existing tasks for a workflow step

File: packages/features/tasker/tasks/scanWorkflowBody.ts [hunk 3]
```diff
@@ -11,18 +12,39 @@ import { scheduleWorkflowNotifications } from "@calcom/trpc/server/routers/viewe
...
 
 const log = logger.getSubLogger({ prefix: ["[tasker] scanWorkflowBody"] });
 
 export async function scanWorkflowBody(payload: string) {
-  const { workflowStepIds, userId } = scanWorkflowBodySchema.parse(JSON.parse(payload));
+  const { workflowStepIds, userId, createdAt, workflowStepId } = scanWorkflowBodySchema.parse(
+    JSON.parse(payload)
+  );
+
+  const stepIdsToScan: number[] = workflowStepIds ? workflowStepIds : [];
```
[the remark this answers is not in the document]
Comment (CarinaWolli) [reply packages/features/tasker/tasks/scanWorkflowBody.ts:28]: if `workflowStepIds` is defined there are no push opertions

File: packages/features/tasker/tasks/scanWorkflowBody.ts [hunk 4]
```diff
@@ -11,18 +12,39 @@
...
+
+  if (workflowStepId && !workflowStepIds) {
```
[the remark this answers is not in the document]
Comment (CarinaWolli) [reply packages/features/tasker/tasks/scanWorkflowBody.ts:30]: That's fine, it should only check for undefined. No need to check for empty array

File: packages/features/tasker/tasks/scanWorkflowBody.ts (hunk 1 above)
Comment (eunjae-lee) [reply packages/features/tasker/tasks/scanWorkflowBody.ts]: If we don't need the actual newerTask, what if we rename it to `Task.hasNewerScanTaskForStepId`?

**Review by eunjae-lee — DISMISSED** [review]
Looks good to me!

File: packages/features/tasker/tasks/scanWorkflowBody.ts (hunk 1 above)
Comment (CarinaWolli) [reply packages/features/tasker/tasks/scanWorkflowBody.ts]: Good point, I changed it to `hasNewerScanTaskForStepId` and return a boolean instead

**Review by eunjae-lee — APPROVED** [review]
