### PR TITLE
Fixes that sometimes last shown slot was unavailable

### LINKED ISSUE #7659: Error when booking meeting/incorrect meeting time showing as available
### Issue Summary

My meetings are set to 20 mins long. My calendar is set to max of 5:45pm. It shows an available time slot on my calendar of 5:40pm.

### Steps to Reproduce

1. Meeting length set to 20 mins
2. Calendar time set to max of 5:45pm
3. Available time slot in my calendar of 5:40pm
4. Meeting at 5:40pm shows an error when trying to book

I would expect the calendar slot at 5:40pm not to show, since my max time is set to 5:45pm. But if it is supposed to show, I would expect the 5:40pm meeting to correctly book and not show an error.

### Technical details
-MacBook Pro 13" M1, Google Chrome

### Screenshots
Calendar settings image:

Ability to schedule / reschedule appointments outside of regular appointment times.
CleanShot 2023-03-14 at 12 54 04@2x

Calendar availability image:

CleanShot 2023-03-14 at 12 53 28@2x

Calendar booking error image:

CleanShot 2023-03-14 at 12 53 41@2x

### PR DESCRIPTION
**Pull request by CarinaWolli**
## What does this PR do?

Fixes that sometimes the last time slot shown is not within working hours. This is the case for 20 minute long events that have working hours that don't end in a full hour. 

Also adds a test that fails before and succeeds with the new changes

Fixes #7659

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Create event type with event length 20 minutes
- Set your availability to 9:00 - 16:45 (or anything else that does not end in a full hour)
- See that the 16:40 time slot is not shown anymore

### CODE REVIEW

File: packages/lib/slots.ts [hunk 1]
```diff
@@ -87,7 +87,7 @@ function buildSlots({
     for (let slotStart = boundaryStart; slotStart < boundaryEnd; slotStart += frequency) {
       computedLocalAvailability.forEach((item) => {
         // TODO: This logic does not allow for past-midnight bookings.
-        if (slotStart < item.startTime || slotStart > item.endTime + 15 - eventLength) {
+        if (slotStart < item.startTime || slotStart > item.endTime + 1 - eventLength) {
```
Comment (CarinaWolli) [inline packages/lib/slots.ts:90]: Without the + 1 any last timeslot before midnight would not be shown

**Review by zomars — APPROVED** [review]
Nice catch @CarinaWolli 🙏🏽
