### PR TITLE
V2/settings shell

### LINKED ISSUE #4098: Settings need a mobile view
Screenshot 2022-09-01 at 18 14 12

### LINKED ISSUE #4194: /settings - sidebar ui issues - multiple
[Refer to anatomy in Figma](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=17937%3A171647)

Image

### LINKED ISSUE #4200: /settings - conferencing broken
Currently
Image

Should be

Image

### PR DESCRIPTION
**Pull request by joeauyeung**
## What does this PR do?

This PR adds the shell component for the settings pages for both desktop and mobile views

Fixes #4098 

**Environment**: Staging(main branch) / Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Go to a V2 settings page ex. http://localhost:3000/v2/settings/my-account/profile
- The shell should show other sections of the settings pages
	- Note that only my account and security are the only pages created right now
- Reduce your window size to small
- The top bar should be rendered and when clicking on the button the side drawer should appear 

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

File: apps/web/pages/v2/settings/my-account/appearance.tsx [hunk 1]
```diff
@@ -46,129 +46,133 @@ const AppearanceView = (props: inferSSRProps<typeof getServerSideProps>) => {
...
-            <div>
-              <p className="block text-sm font-medium text-gray-900">{t("light_brand_color")}</p>
-              <ColorPicker
-                defaultValue={user.brandColor}
-                onChange={(value) => formMethods.setValue("brandColor", value)}
-              />
-            </div>
-          )}
-        />
+    <SettingsShell heading={t("appearance")} subtitle={t("appearance_subtitle")}>
```
Comment (zomars) [inline apps/web/pages/v2/settings/my-account/appearance.tsx:49]: Let’s stick with the getLayout approach, if that layout doesn’t cover the current needs let’s modify it or make another one.

File: packages/ui/v2/modules/settings/SettingsShell.tsx [hunk 2]
```diff
@@ -0,0 +1,233 @@
+import Link from "next/link";
```
Comment (zomars) [inline packages/ui/v2/modules/settings/SettingsShell.tsx:1]: Why is this file being duplicated?

**Comment by agustif** [comment]
Hey @joeauyeung https://github.com/calcom/cal.com/pull/3817. is ready for merge (conflict free) so you can work on integrating with it! Thanks!

File: packages/ui/v2/core/Shell.tsx [hunk 3]
```diff
@@ -26,6 +26,7 @@ import Dropdown, {
   DropdownMenuTrigger,
 } from "@calcom/ui/Dropdown";
 import { CollectionIcon, Icon } from "@calcom/ui/Icon";
+import MobileSettingsContainer from "@calcom/ui/v2/core/navigation/MobileSettingsContainer";
```
Comment (joeauyeung) [inline packages/ui/v2/core/Shell.tsx:29]: Created a separate component to render on <md screens

File: packages/ui/v2/core/Shell.tsx [hunk 4]
```diff
@@ -484,7 +485,9 @@ function MobileNavigationContainer() {
 }
 
 const MobileNavigation = () => {
+  const router = useRouter();
   const isEmbed = useIsEmbed();
+  if (router.route.startsWith("/v2/settings/")) return null;
```
Comment (joeauyeung) [inline packages/ui/v2/core/Shell.tsx:490]: We don't want the bottom navigation bar to be displayed when on the settings page

File: packages/ui/v2/core/Shell.tsx [hunk 5]
```diff
@@ -644,18 +647,25 @@ function MainContainer(props: LayoutProps) {
 }
 
 function TopNavContainer() {
+  const router = useRouter();
   const { status } = useSession();
   if (status !== "authenticated") return null;
+  if (router.route.startsWith("/v2/settings/")) return <MobileSettingsContainer />;
```
Comment (joeauyeung) [inline packages/ui/v2/core/Shell.tsx:653]: If on the settings pages then have the mobile settings nav bar

File: packages/ui/v2/core/Shell.tsx [hunk 6]
```diff
@@ -644,18 +647,25 @@ function MainContainer(props: LayoutProps) {
...
   const isEmbed = useIsEmbed();
   const { t } = useLocale();
   return (
     <nav
       style={isEmbed ? { display: "none" } : {}}
-      className="flex items-center justify-between border-b border-gray-200 bg-white p-4 md:hidden">
+      className={classNames(
+        "flex items-center justify-between border-b border-gray-200 bg-white p-4 md:hidden",
+        router.route.startsWith("/v2/settings/") && "hidden"
+      )}>
```
Comment (joeauyeung) [inline packages/ui/v2/core/Shell.tsx:668]: Hide the default top bar on mobile

File: packages/ui/v2/core/layouts/SettingsLayout.tsx [hunk 7]
```diff
@@ -8,19 +8,19 @@ import Shell from "../Shell";
 import { VerticalTabItem } from "../navigation/tabs";
 import VerticalTabs from "../navigation/tabs/VerticalTabs";
 
-const tabs = [
+export const settingsTabs = [
```
Comment (joeauyeung) [inline packages/ui/v2/core/layouts/SettingsLayout.tsx:11]: Have one source of truth for the navigation tabs for the moble settings nav bar

**Comment by joeauyeung** [comment]
Implemented changes from #3817

Tested by
- Changing password
- Enabling 2FA
- Logging out and logging back in with 2FA
- Disable 2FA
- Deleting an account with 2FA enabled

**Comment by joeauyeung** [comment]
Implemented changes from #3817 

Tested by:
- Enabling 2FA
- Disabling 2FA
- Changing password
- Logging in with 2FA
- Deleting account with 2FA enabled

File: packages/ui/v2/core/Shell.tsx (hunk 4 above)
Comment (PeerRich) [reply packages/ui/v2/core/Shell.tsx:490]: we just need to remember to remove "v2" later haha

**Comment by PeerRich** [comment]
left some feedback @joeauyeung https://www.loom.com/share/86d430adc1854e3ca96093e0fc15766b

**Comment by joeauyeung** [comment]
@zomars I still have feedback to implement but I'm wondering if you could still review my use of `getLayout` and the shell component

**Comment by zlwaterfield** [comment]
@joeauyeung could you add a description + testing notes and tag the project/issue to the PR.

File: packages/ui/v2/core/layouts/SettingsLayout.tsx [hunk 8]
```diff
@@ -1,99 +1,48 @@
...
+    <Shell flexChildrenContainer {...rest} SidebarContainer={<SettingsSidebarContainer />}>
+      <div
+        className={classNames(
+          "absolute z-40 h-screen w-screen bg-black opacity-50",
+          sideContainerOpen ? "" : "hidden"
+        )}
+        onClick={() => {
+          setSideContainerOpen(false);
+        }}
+      />
```
Comment (joeauyeung) [inline packages/ui/v2/core/layouts/SettingsLayout.tsx:26]: This div provides the dark filter on the screen when the side drawer is open on mobile view. Checked and it doesn't cause unnecessary rerendering

File: apps/web/components/v2/settings/DisableTwoFactorModal.tsx [hunk 9]
```diff
@@ -1,10 +1,14 @@
 import { SyntheticEvent, useState } from "react";
```
Comment (zomars) [inline apps/web/components/v2/settings/DisableTwoFactorModal.tsx:1]:
```suggestion
import { useState } from "react";
```

File: apps/web/pages/v2/settings/my-account/profile.tsx [hunk 10]
```diff
@@ -2,28 +2,37 @@ import crypto from "crypto";
 import { GetServerSidePropsContext } from "next";
 import { signOut } from "next-auth/react";
 import { Trans } from "next-i18next";
```
Comment (zomars) [inline apps/web/pages/v2/settings/my-account/profile.tsx:4]:
```suggestion
```

File: apps/web/pages/v2/settings/my-account/profile.tsx [hunk 11]
```diff
@@ -2,28 +2,37 @@ import crypto from "crypto";
...
-import { useRef, useState } from "react";
+import { useRef, useState, BaseSyntheticEvent, FormEvent } from "react";
```
Comment (zomars) [inline apps/web/pages/v2/settings/my-account/profile.tsx:5]:
```suggestion
import { useRef, useState, BaseSyntheticEvent } from "react";
```

File: apps/web/pages/v2/settings/my-account/profile.tsx [hunk 12]
```diff
@@ -37,23 +46,48 @@ const ProfileView = (props: inferSSRProps<typeof getServerSideProps>) => {
   });
 
   const [deleteAccountOpen, setDeleteAccountOpen] = useState(false);
+  const [hasErrors, setHasErrors] = useState(false);
```
Comment (zomars) [inline apps/web/pages/v2/settings/my-account/profile.tsx:49]:
```suggestion
```

File: apps/web/pages/v2/settings/my-account/profile.tsx [hunk 13]
```diff
@@ -64,6 +98,16 @@ const ProfileView = (props: inferSSRProps<typeof getServerSideProps>) => {
   });
 
   const avatarRef = useRef<HTMLInputElement>(null!);
```
Comment (zomars) [inline apps/web/pages/v2/settings/my-account/profile.tsx:100]:
```suggestion
```

File: packages/ui/v2/core/layouts/SettingsLayout.tsx [hunk 14]
```diff
@@ -1,98 +1,49 @@
...
+import { classNames } from "@calcom/lib";
 import { useLocale } from "@calcom/lib/hooks/useLocale";
+import { Icon } from "@calcom/ui/Icon";
 
-import { Icon } from "../../../Icon";
 import { useMeta } from "../Meta";
 import Shell from "../Shell";
-import VerticalTabs, { VerticalTabItem } from "../navigation/tabs/VerticalTabs";
-
-const tabs = [
```
Comment (zomars) [inline packages/ui/v2/core/layouts/SettingsLayout.tsx:10]: Why?

**Review by zomars — CHANGES_REQUESTED** [review]
Let's make sure self-review is done before asking of a re-review. cc @PeerRich

File: packages/ui/v2/core/layouts/SettingsLayout.tsx (hunk 14 above)
Comment (joeauyeung) [reply packages/ui/v2/core/layouts/SettingsLayout.tsx:10]: I moved it to `packages/ui/v2/core/navigation/SettingsSidebarContainer.tsx` since I was thinking that would be the only time we would need to access those tabs.

Comment (zomars) [reply packages/ui/v2/core/layouts/SettingsLayout.tsx:10]: Id rather keep this outside of react since they should be "static"

**Review by zomars — APPROVED** [review]
Ship it!
Ship it
