### PR TITLE
fix: [CAL-2040] add spinner when bookerState is loading

### LINKED ISSUE #9758: [CAL-2040] Booker shows loading of monthly, if only view is weekly or column
We shouldn't see a flash of the monthly view is the only calendar available is monthly or column

[https://github.com/calcom/cal.com/assets/4536123/9726b5e4-dddd-4079-8af6-aa09e8d9ba07](https://github.com/calcom/cal.com/assets/4536123/9726b5e4-dddd-4079-8af6-aa09e8d9ba07)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2040](https://linear.app/calcom/issue/CAL-2040/booker-shows-loading-of-monthly-if-only-view-is-weekly-or-column)</sub>

### PR DESCRIPTION
**Pull request by afrieirham**
## What does this PR do?

Add loading spinner when bookerState is loading to avoid showing monthly view if the default is set to weekly or column.

Fixes #9758 

https://github.com/calcom/cal.com/assets/32460534/0a865096-5585-4d5f-b092-b506f8e44709

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [x] Use user free@example.com and choose weekly or column view in appearance. Then visit booker's page.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/features/bookings/Booker/Booker.tsx [hunk 1]
```diff
@@ -132,6 +133,11 @@ const BookerComponent = ({
   };
 
   const shouldShowFormInDialog = shouldShowFormInDialogMap[layout];
+
+  if (bookerState === "loading") {
+    return <Spinner />;
```
Comment (CarinaWolli) [inline packages/features/bookings/Booker/Booker.tsx:138]: I don't think we want to show a spinner. I would prefer to return `null` if `bookerState` is still loading. 

Let me know in case I am missing something and it was mentioned somewhere to use a spinner here (cc @Jaibles )

**Review by CarinaWolli — CHANGES_REQUESTED** [review]

File: packages/features/bookings/Booker/Booker.tsx (hunk 1 above)
Comment (afrieirham) [reply packages/features/bookings/Booker/Booker.tsx]: updated


https://github.com/calcom/cal.com/assets/32460534/9931f492-bedb-4df6-8ff3-6cfdaf927d26

**Review by CarinaWolli — APPROVED** [review]
Looks good to me now. Thank you 🙏
