### PR TITLE
fix: Collective Events: Duration parameter in link not working

### LINKED ISSUE #13504: Collective Events: Duration parameter in link not working when changing it manually
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Created an event type with multiple durations (e.g. 15m, 30m, 45m)
2. marked one duration as standard duration (e.g. 15m)
3. visiting the public link and changing manually the "?duration=45" parameter to one of the available durations
4. open the "new" link/URL
5. duration in the URL gets ignored and the standard duration of 15m gets preselected 
6. URL switches back to the "standard" duration

Thus it is impossible to share the actual URL of the page to make sure people are booking the right duration.

Weird fact: this only happens on collective events with more than one person ([see screenrecording](https://share.vidyard.com/watch/7W1pxjAzdEWx7Md2EEbLvW?)).

### Actual Results

- It doesn't reflect the duration that is present in the URL.

### Expected Results

- It should change the duration to the duration in the URL.

### Technical details

- Chrome Browser 121.0.6167.140 (Offizieller Build) (64-Bit)
- screenrecording: https://share.vidyard.com/watch/7W1pxjAzdEWx7Md2EEbLvW?
- cal version v.3.7.9-sh

### Evidence

- see [screen recording](https://share.vidyard.com/watch/7W1pxjAzdEWx7Md2EEbLvW?)

### PR DESCRIPTION
**Pull request by Nis-Han**
## What does this PR do?

Fixes #13504

https://www.loom.com/share/1d37a04658a7453ca662bea38988b7ee?sid=447a9129-0905-48f3-a855-1513ba0ddb0c

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Run this branch on local and try doing [this](https://share.vidyard.com/watch/7W1pxjAzdEWx7Md2EEbLvW)

## Mandatory Tasks

- [X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't checked if my PR needs changes to the documentation
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: apps/web/pages/team/[slug]/[type].tsx [hunk 1]
```diff
@@ -25,6 +28,12 @@ export default function Type({
   duration,
   isInstantMeeting,
 }: PageProps) {
+  const setSelectedDuration = useBookerStore((state) => state.setSelectedDuration);
+  useEffect(() => {
+    if (!!duration) {
+      setSelectedDuration(duration);
+    }
+  });
```
Comment (Udit-takkar) [inline apps/web/pages/team/[slug]/[type].tsx:36]: is there any better way to do this?

**Review by Udit-takkar — DISMISSED** [review]
can we do something like Alex did for user booking pages https://github.com/calcom/cal.com/pull/12444 ?

**Comment by Nis-Han** [comment]
> can we do something like Alex did for user booking pages #12444 ?

Have made the changes and tested accordingly. (almost copied the exact code)

There are [some comments](https://github.com/calcom/cal.com/pull/12444/files#diff-0a49c6d137ab5a519fee377425ff051a13bcf55ff728bca45daaa73a4c5f0458R68-R70) related to `duration` prop in Booker component that Alex left. Have copied that as well, as it might need a cleanup later.

**Comment by keithwillcode** [comment]
@Nis-Han looks like there are some type checks failing

**Comment by Nis-Han** [comment]
> @Nis-Han looks like there are some type checks failing

fixed

**Review by Udit-takkar — APPROVED** [review]
@Nis-Han LGTM 👍
