### PR TITLE
fix: long URLs no longer overflow when creating or editing an event on smaller screens 

### LINKED ISSUE #24695: Responsive Layout Bug URL Input Field Breaks on Screen Sizes
Found a bug? Please fill out the sections below. 👍

### Issue Summary
The URL input field in the form has responsive design issues where the layout breaks on screen sizes.

### Steps to Reproduce
1. Navigate to: `cal.com/XXXX-XXXXXXXX9kjmxs`
2. Reduce browser window width to between 280px and 1024px
3. Observe the URL input field layout

### Actual Results
- URL input field overflows its container
- Text content overlaps with adjacent elements

### Expected Results
- URL input field should maintain proper proportions across all screen sizes
- The text must remain fully visible without exceeding the border.
- Responsive design should work seamlessly at all breakpoints

### Evidence
Image

### PR DESCRIPTION
**Pull request by ifrah-ashraf**
## What does this PR do?

- Fixes #24695  
- Fixes [CAL-6640](https://linear.app/calcom/issue/CAL-6640/responsive-layout-bug-url-input-field-breaks-on-screen-sizes)
 
The long **URL** prefix in the input field is now truncated responsively based on the screen size, ensuring it does not overflow and remains visually consistent across different devices 

## Visual Demo (For contributors especially)

A visual demonstration is strongly recommended, for both the original and new change **(video / image - any one)**.

#### Video Demo (if applicable):

- Chrome browser (**Before**)

https://github.com/user-attachments/assets/f92e1a34-6e0b-4e91-bdfd-9e4158ab1aa6

-  Chrome browser (**After**)

https://github.com/user-attachments/assets/d736d275-c472-40a7-a152-152cc531c1cc

#### Image Demo (if applicable):

- Mozilla Firefox Browser (**After only**)

1. While creating a new event

Screenshot from 2025-10-26 21-07-39

2. While editing an event

Screenshot from 2025-10-26 20-40-13

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Create or edit any event and test the reponsiveness on both browser **Mozilla Firefox** and **Chrome**.

---
## Summary by cubic
Long URL prefixes in the event URL input are now truncated on smaller screens to prevent overflow in create and edit forms. Addresses CAL-6640 and #24695.

- **Bug Fixes**
  - Wrapped the leading URL prefix in a span with responsive truncation (inline-block, overflow-hidden, text-ellipsis, whitespace-nowrap, min-w-0).
  - Applied in CreateEventTypeForm and EventSetupTab; tooltip continues to show the full URL where used.

<sup>Written for commit f6f3a2ca023cd3b8a97ccd0cd92745a77c58e6d8. Summary will update automatically on new commits.</sup>

### CODE REVIEW

**Comment by dhairyashiil** [comment]
@ifrah-ashraf  please add 'before' video to confirm that the issue really existed

**Comment by ifrah-ashraf** [comment]
> @ifrah-ashraf please add 'before' video to confirm that the issue really existed

Updated with before video.

File: packages/features/eventtypes/components/CreateEventTypeForm.tsx [hunk 1]
```diff
@@ -64,7 +64,7 @@ export default function CreateEventTypeForm({
               required
               addOnLeading={
                 !isPlatform ? (
-                  <span className="max-w-24 md:max-w-56">
+                  <span className="max-w-24 md:max-w-56 inline-block overflow-hidden text-ellipsis whitespace-nowrap min-w-0">
```
Comment (saadazghour) [inline packages/features/eventtypes/components/CreateEventTypeForm.tsx:67]: I see duplicate classes in nested span

`className="max-w-24 md:max-w-56 inline-block overflow-hidden text-ellipsis whitespace-nowrap min-w-0"`

DRY, This is repeated on both parent and child spans. This is unnecessary and can be simplified to use just one span element. We can improve this. 

```suggestion
         <div>
            <TextField
                label={isPlatform ? "Slug" : `${t("url")}: ${urlPrefix}`}
                required
                addOnLeading={
                  !isPlatform ? (
                    <Tooltip
                      content={`${urlPrefix}/${!isManagedEventType ? pageSlug : t("username_placeholder")}/`}>
                      <span className="max-w-24 md:max-w-56 inline-block overflow-hidden text-ellipsis whitespace-nowrap min-w-0">
                        {urlPrefix && urlPrefix.length >= 21 
                          ? `/${!isManagedEventType ? pageSlug : t("username_placeholder")}/`
                          : `${urlPrefix}/${!isManagedEventType ? pageSlug : t("username_placeholder")}/`
                        }
                      </span>
                    </Tooltip>
                ) : undefined
              }
                containerClassName="[&>div]:gap-0"
                className="pl-0"
                {...register("slug")}
                onChange={(e) => {
                  form.setValue("slug", slugify(e?.target.value), { shouldTouch: true });
                }}
            />
            
            {isManagedEventType && !isPlatform && (
              <p className="mt-2 text-sm text-gray-600">{t("managed_event_url_clarification")}</p>
            )}
      </div>
```

Comment (ifrah-ashraf) [reply packages/features/eventtypes/components/CreateEventTypeForm.tsx:67]: Hey @saadazghour I checked the changed files where I added the CSS properties to the `<span>` tag. There’s no nesting of `<span>` tags if you check, the former `<span>` tag has been replaced with the latter one.
```bash
<span className="max-w-24 md:max-w-56">
```
with this one
```bash
<span className="max-w-24 md:max-w-56 inline-block overflow-hidden text-ellipsis whitespace-nowrap min-w-0">

Comment (saadazghour) [reply packages/features/eventtypes/components/CreateEventTypeForm.tsx:67]: Hi @ifrah-ashraf 

image

Comment (ifrah-ashraf) [reply packages/features/eventtypes/components/CreateEventTypeForm.tsx:67]: Hey @saadazghour if you check the whole code properly there is a condtional check for the **URL** at line 60.

```bash
{urlPrefix && urlPrefix.length >= 21 ? ...
```

based on this `urlPrefix` check condition the URL is displayed properly. Now earlier there is same `<span>` tag in both the checks maybe to ensure **styling** consistency and not **DRY**. So i followed the same to keep it consistent.

Note: if needed like for shorter URL (**length < 21**) we can keep the previous `<span>` as it is.

**Review by dhairyashiil — APPROVED** [review]
LGTM 👍🏼 , Thank youu for the contribution.

**Review by saadazghour — APPROVED** [review]
