### PR TITLE
fix: change admin user password requirement

### LINKED ISSUE #3085: Error ESLint
I'm getting this error when trying to upload the project to production on a private server. 
Can someone help me?

@calcom/web:build: Generated `apps.server.generated.ts` and `apps.browser.generated.tsx`
@calcom/web:build: info  - Checking validity of types...
@calcom/web:build: 
@calcom/web:build: Failed to compile.
@calcom/web:build: 
@calcom/web:build: ./pages/api/auth/saml/token.ts
@calcom/web:build: 15:17  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 
@calcom/web:build: ./pages/api/auth/saml/userinfo.ts
@calcom/web:build: 41:17  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 
@calcom/web:build: ./pages/api/auth/signup.ts
@calcom/web:build: 84:2  Error: Insert `⏎`  prettier/prettier
@calcom/web:build: 
@calcom/web:build: ./pages/api/teams/[team]/invite.ts
@calcom/web:build: 109:17  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 
@calcom/web:build: ./pages/apps/[slug]/index.tsx
@calcom/web:build: 25:31  Warning: 'placeholder' is defined but never used.  @typescript-eslint/no-unused-vars
@calcom/web:build: 
@calcom/web:build: ./pages/auth/signup.tsx
@calcom/web:build: 32:34  Warning: 'email' is defined but never used.  @typescript-eslint/no-unused-vars
@calcom/web:build: 168:1  Error: Delete `··`  prettier/prettier
@calcom/web:build: 199:3  Error: Insert `⏎`  prettier/prettier
@calcom/web:build: 
@calcom/web:build: ./pages/auth/sso/[provider].tsx
@calcom/web:build: 104:19  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 
@calcom/web:build: ./pages/settings/profile.tsx
@calcom/web:build: 123:48  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
@calcom/web:build: 124:44  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
@calcom/web:build: 125:45  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
@calcom/web:build: 126:54  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
@calcom/web:build: 127:46  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
@calcom/web:build: 128:52  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
@calcom/web:build: 129:64  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
@calcom/web:build: 
@calcom/web:build: ./lib/QueryCell.tsx
@calcom/web:build: 71:34  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 92:51  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 92:56  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 92:61  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 92:66  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 92:71  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 92:76  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 
@calcom/web:build: ./lib/app-providers.tsx
@calcom/web:build: 4:37  Warning: 'useMemo' is defined but never used.  @typescript-eslint/no-unused-vars
@calcom/web:build: 
@calcom/web:build: ./lib/config/next-seo.config.ts
@calcom/web:build: 28:12  Error: Insert `⏎`  prettier/prettier
@calcom/web:build: 
@calcom/web:build: ./lib/hooks/useSlots.ts
@calcom/web:build: 194:44  Warning: Forbidden non-null assertion.  @typescript-eslint/no-non-null-assertion
@calcom/web:build: 
@calcom/web:build: ./lib/jackson.ts
@calcom/web:build: 22:21  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 
@calcom/web:build: ./lib/slots.ts
@calcom/web:build: 52:3  Warning: 'currentSeats' is defined but never used.  @typescript-eslint/no-unused-vars
@calcom/web:build: 
@calcom/web:build: ./lib/telemetry.ts
@calcom/web:build: 87:13  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 92:27  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 93:49  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 
@calcom/web:build: ./lib/types/inferSSRProps.ts
@calcom/web:build: 3:35  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 5:35  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 7:48  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
@calcom/web:build: 
@calcom/web:build: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
@calcom/web:build: error Command failed with exit code 1.
@calcom/web:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@calcom/web:build: Error: command finished with error: command (apps/web) yarn run build exited (1)
command (apps/web) yarn run build exited (1)

 Tasks:    4 successful, 5 total
Cached:    1 cached, 5 total
  Time:    33.316s 

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### PR DESCRIPTION
**Pull request by Udit-takkar**
Fixes: #3085 

After:

Screenshot 2022-11-18 at 2 02 26 PM
Screenshot 2022-11-18 at 2 02 16 PM

### CODE REVIEW

File: packages/lib/auth.ts [hunk 1]
```diff
@@ -38,21 +38,23 @@ export function isPasswordValid(
...
+): { caplow: boolean; num: boolean; min: boolean; admin_min: boolean };
 export function isPasswordValid(password: string, breakdown?: boolean, strict?: boolean) {
   let cap = false, // Has uppercase characters
     low = false, // Has lowercase characters
     num = false, // At least one number
-    min = false; // Eight characters, or fifteen in strict mode.
+    min = false, // Eight characters, or fifteen in strict mode.
+    admin_min = false;
   if (password.length > 7 && (!strict || password.length > 14)) min = true;
+  if (strict && password.length > 14) admin_min = true;
```
Comment (Udit-takkar) [inline packages/lib/auth.ts:49]: created a variable admin_min to check valid admin password. 
zod also requires this key("admin_min") to display error if conditions are not met.

File: apps/web/pages/auth/setup.tsx [hunk 2]
```diff
@@ -185,7 +189,7 @@ const SetupFormStep1 = (props: { setIsLoading: (val: boolean) => void }) => {
                   formMethods.setValue("password", e.target.value);
                   await formMethods.trigger("password");
                 }}
-                hintErrors={["caplow", "min", "num"]}
+                hintErrors={["caplow", "admin_min", "num"]}
```
Comment (JeroenReumkens) [inline apps/web/pages/auth/setup.tsx:192]: Should "min" also still remain as a hint?

Comment (Udit-takkar) [reply apps/web/pages/auth/setup.tsx:192]: min property only checks for 8 characters or more and also displays 8 characters "password_hint_min": "Minimum 8 characters long".  check HintsOrErrors.tsx file once.

**Review by JeroenReumkens — APPROVED** [review]
