### PR TITLE
test: Hotfix/Orgs rewrite causing 404 with 3 or more dots domains

### LINKED ISSUE #9768: / Redirect doesnt appear to be working on self hosting
### Issue Summary

When login or just hitting root domain, i see the following screenshot.  This happens on a deploy of a self hosted instance and does not appear if i run the code locally.  

Screenshot 2023-06-23 at 1 20 35 PM

### Steps to Reproduce

1. Deploy a self hosted instance and login
2. Observe 404 page (username / is still available)

### Technical details

- Deployed this both on vercel and Digital ocean.

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #9768
Added tests as well. Helped in testing and helps in avoiding future bugs.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
- [x] Add a hosts entry for `calcom.app.company.com` and `acme.calcom.app.company.com` to 127.0.0.1
 - [x] Visit `calcom.app.company.com` and see a 404. With this branch that 404 is fixed. Also, test `acme.calcom.app.company.com`, it should also not be 404.
- [x] Ensure that env variables are like this
Screenshot 2023-06-26 at 7 25 16 PM

## Here are the tests done with app.cal.com and vwo org.
Screenshot 2023-06-27 at 12 36 32 PM
Screenshot 2023-06-27 at 12 36 47 PM
Screenshot 2023-06-27 at 12 37 00 PM
Screenshot 2023-06-27 at 12 37 28 PM

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: apps/web/getSubdomainRegExp.js [hunk 1]
```diff
@@ -0,0 +1,15 @@
+const getDefaultSubdomain = (url) => {
+  if (!url.startsWith("http:") && !url.startsWith("https:")) {
+    // Make it a valid URL. Mabe we can simply return null and opt-out from orgs support till the use a URL scheme.
```
Comment (hariombalhara) [inline apps/web/getSubdomainRegExp.js:3]: Someone reported they were using cal.com without specifying https:// earlier. So I just added it, didn't verify what else fails if someone uses that.

File: apps/web/next.config.js [hunk 2]
```diff
@@ -70,14 +71,6 @@ const informAboutDuplicateTranslations = () => {
 };
 
 informAboutDuplicateTranslations();
-
-const getSubdomain = () => {
-  const _url = new URL(process.env.NEXT_PUBLIC_WEBAPP_URL);
```
Comment (hariombalhara) [inline apps/web/next.config.js:75]: Moved outside to allow writing unit tests

File: apps/web/test/lib/next-config.test.ts [hunk 3]
```diff
@@ -155,3 +157,35 @@ describe('next.config.js - RegExp', ()=>{
...
+      const subdomainRegExp = getSubdomainRegExp('https://calcom.app.company.com');
+      expect(pagesRewriteRegex(subdomainRegExp).exec('calcom.app.company.com')).toEqual(null)
+      expect(pagesRewriteRegex(subdomainRegExp).exec('acme.calcom.app.company.com')?.groups?.orgSlug).toEqual('acme')
+    })
+
+    it('https://calcom.example.com', ()=>{
+      const subdomainRegExp = getSubdomainRegExp('https://calcom.example.com');
+      expect(pagesRewriteRegex(subdomainRegExp).exec('calcom.example.com')).toEqual(null)
+      expect(pagesRewriteRegex(subdomainRegExp).exec('acme.calcom.example.com')?.groups?.orgSlug).toEqual('acme')
+      // The following also matches which causes anything other than the domain in NEXT_PUBLIC_WEBAPP_URL to give 404
```
Comment (hariombalhara) [inline apps/web/test/lib/next-config.test.ts:187]: I am not sure what to do about this case?

File: apps/web/getSubdomainRegExp.js [hunk 4]
```diff
@@ -0,0 +1,15 @@
...
+    url = `https://${url}`;
+  }
+  const _url = new URL(url);
+  const regex = new RegExp(/^([a-z]+\:\/{2})?((?<subdomain>[\w-.]+)\.[\w-]+\.\w+)$/);
+  //console.log(_url.hostname, _url.hostname.match(regex));
+  return _url.hostname.match(regex)?.groups?.subdomain || null;
```
Comment (hariombalhara) [inline apps/web/getSubdomainRegExp.js:9]: Copied as is.

File: apps/web/getSubdomainRegExp.js [hunk 5]
```diff
@@ -0,0 +1,15 @@
...
+};
+exports.getSubdomainRegExp = (url) => {
+  const defaultSubdomain = getDefaultSubdomain(url);
+  const subdomain = defaultSubdomain ? `(?!${defaultSubdomain})[^.]+` : "[^.]+";
+  return subdomain;
```
Comment (hariombalhara) [inline apps/web/getSubdomainRegExp.js:14]: Copied as is.

File: apps/web/getSubdomainRegExp.js [hunk 6]
```diff
@@ -0,0 +1,15 @@
+const getDefaultSubdomain = (url) => {
+  if (!url.startsWith("http:") && !url.startsWith("https:")) {
+    // Make it a valid URL. Mabe we can simply return null and opt-out from orgs support till the use a URL scheme.
+    url = `https://${url}`;
+  }
+  const _url = new URL(url);
+  const regex = new RegExp(/^([a-z]+\:\/{2})?((?<subdomain>[\w-.]+)\.[\w-]+\.\w+)$/);
```
Comment (hariombalhara) [inline apps/web/getSubdomainRegExp.js:7]: Only this regex changed with inclusion of dot in subdomain capturing group

**Review by hariombalhara — COMMENTED** [review]
Self reviewed.

**Review by zomars — COMMENTED** [review]
LGTM. Delegatin final testing to @roae

File: apps/web/getSubdomainRegExp.js (hunk 6 above)
Comment (roae) [reply apps/web/getSubdomainRegExp.js:7]: so, when the subdomain is org.app.cal.com the slug will be org.app?

**Review by roae — CHANGES_REQUESTED** [review]
rewrites related to organization are not working. e.g. `org.cal.local/team-slug` return 404 error

**Comment by hariombalhara** [comment]
Seems to be working for me @roae. I would like you take it over as I am not fully aware of the logic.
Screenshot 2023-06-27 at 10 56 56 AM

File: apps/web/getSubdomainRegExp.js (hunk 6 above)
Comment (hariombalhara) [reply apps/web/getSubdomainRegExp.js:7]: `subdomain` group would be org.app but `orgSlug` group would be **org**. This is because we are simply doing negative lookahead for `subdomain`.

File: apps/web/next.config.js [hunk 7]
```diff
@@ -102,6 +95,39 @@ const teamTypeRouteRegExp = "/team/:slug/:type((?!book$)[^/]+)";
...
+
+const matcherConfigUserPath = {
+  has: [
+    {
+      type: "host",
+      value: `^(?<orgSlug>${subdomainRegExp}[^.]+)\\..*`,
+    },
+  ],
+  source: `/:user((?!${pages.join("|")}|_next|public))/:path*`,
+};
```
Comment (hariombalhara) [inline apps/web/next.config.js:130]: Abstracted out to shared with headers

File: apps/web/next.config.js [hunk 8]
```diff
@@ -381,6 +390,35 @@ const nextConfig = {
           },
         ],
       },
+      ...[
```
Comment (hariombalhara) [inline apps/web/next.config.js:393]: Added response header `X-Cal-Org-path` to easily identify to which path the rewrite occured. It would also help in writing checkly tests.

**Comment by hariombalhara** [comment]
Here are the tests done with app.cal.com and vwo org.
Screenshot 2023-06-27 at 12 36 32 PM
Screenshot 2023-06-27 at 12 36 47 PM
Screenshot 2023-06-27 at 12 37 00 PM
Screenshot 2023-06-27 at 12 37 28 PM

**Comment by roae** [comment]
@hariombalhara it is not working on my end, I'm taking over of this.

imagen

**Comment by roae** [comment]
> @roae I have added a response header to confirm the route(X-Cal-Org-Path). Can you check what the value for this is for you

Yes, I notice that, it seems there was something bad in my BD I just reseted it and create a new organization and teams and is working now!

**Review by roae — APPROVED** [review]
Thanks @hariombalhara, nice job. 

It's working on my end.

**Comment by mariushosting** [comment]
I still experience the same identical issue on a new fresh installation. The fix it's already in :main ?

**Comment by carsonbird** [comment]
I'm also still experiencing this on a fresh install inside docker. My full host domain only has 2 periods. Everything else works great, except for trying to access the root / path.
