### PR TITLE
fix: Add CORP and COEP headers to embedded pages

### LINKED ISSUE #14547: [CAL-3732] Embed.js - CORS issue
### Issue Summary

we use strict security at @un due to the nature of data we handle
one of the sercurity headers we have enabled is COEP (Cross-Origin-Embedder-Policy)

When using the Cal js embed, the component fails to load and we get multiple cors errors
image

it seems that cal's embed does not have `Cross-Origin-Resource-Policy: cross-origin` enabled, thus breaking cors for sites that require it

can the correct security header be added so we can embed cal.com in our application please

<sub>[CAL-3732](https://linear.app/calcom/issue/CAL-3732/embedjs-cors-issue)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?
- Fixes #14547 (GitHub issue number)
- Fixes CAL-3732(Linear issue number - should be visible at the bottom of the GitHub issue description)

- User needs to opt-in to enable these headers in embed(using query param `flag.coep`)
- Added the COEP header to /:path*/embed routes making all the resources on those routes to have CORP header.
- Also, added the COEP header to playground to be able to replicate the issue and henceforth test this scenario.

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [x] N/A I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [x] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?
Simply launch the playground using `yarn dev` inside packages/embeds/embed-core and see the embed loading

### CODE REVIEW

**Comment by hariombalhara** [comment]
* **#15275** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/15275?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hariombalhara and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: apps/web/app/WithEmbedSSR.tsx [hunk 1]
```diff
@@ -14,7 +14,10 @@ export default function withEmbedSsrAppDir<T extends Record<string, any>>(
 ) {
   return async (context: GetServerSidePropsContext): Promise<T> => {
     const { embed, layout } = context.query;
-
+    const isCOEPEnabled = context.query["flag.coep"] === "true";
+    if (isCOEPEnabled) {
+      context.res.setHeader("Cross-Origin-Embedder-Policy", "require-corp");
```
Comment (hariombalhara) [inline apps/web/app/WithEmbedSSR.tsx:19]: Setting it unconditionally will break "pushing events to certain third party analytics" apps. So, we let the embed user opt-in by flag.coep=true

File: apps/web/lib/withEmbedSsr.tsx [hunk 2]
```diff
@@ -11,6 +11,10 @@ export default function withEmbedSsr(getServerSideProps: GetServerSideProps) {
     const ssrResponse = await getServerSideProps(context);
     const embed = context.query.embed;
     const layout = context.query.layout;
+    const isCOEPEnabled = context.query["flag.coep"] === "true";
+    if (isCOEPEnabled) {
+      context.res.setHeader("Cross-Origin-Embedder-Policy", "require-corp");
+    }
```
Comment (hariombalhara) [inline apps/web/lib/withEmbedSsr.tsx:17]: It sets the header on all booking pages except Routing Form.

File: apps/web/pages/reschedule/[uid].tsx [hunk 3]
```diff
@@ -136,6 +136,10 @@ export async function getServerSideProps(context: GetServerSidePropsContext) {
 
   destinationUrl.set("rescheduleUid", seatReferenceUid || bookingUid);
 
+  // TODO: I think we should just forward all the query params here including coep flag
+  if (coepFlag) {
```
Comment (hariombalhara) [inline apps/web/pages/reschedule/[uid].tsx:140]: Directly opening /reschedule/[uid] endpoint seems to lose the flag on redirect, so we explicitly add it.

File: packages/app-store/routing-forms/pages/routing-link/getServerSideProps.ts [hunk 4]
```diff
@@ -58,6 +58,9 @@ export const getServerSideProps = async function getServerSideProps(
   const { currentOrgDomain } = orgDomainConfig(context.req);
 
   const isEmbed = params.appPages[1] === "embed";
+  if (context.query["flag.coep"] === "true") {
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/pages/routing-link/getServerSideProps.ts:61]: Routing Form doesn't use withEmbedSsr, so we handle it separately here.

File: packages/embeds/embed-core/index.html
Comment (hariombalhara) [inline packages/embeds/embed-core/index.html:1]: Because Vite dev server has COEP set to require-corp, we need to opt-in in all the embed cases.

Vite server doesn't allow conditionally setting header without some complexity

File: packages/embeds/embed-core/playwright/tests/inline.e2e.ts [hunk 5]
```diff
@@ -24,10 +30,33 @@ test.describe("Inline Iframe", () => {
     if (!embedIframe) {
       throw new Error("Embed iframe not found");
     }
+
+    assertNoRequestIsBlocked(page);
```
Comment (hariombalhara) [inline packages/embeds/embed-core/playwright/tests/inline.e2e.ts:34]: This test ensures that during the booking no resource is blocked.

File: packages/embeds/embed-core/playwright/tests/inline.e2e.ts [hunk 6]
```diff
@@ -24,10 +30,33 @@ test.describe("Inline Iframe", () => {
...
+
     await bookFirstEvent("pro", embedIframe, page);
     await deleteAllBookingsByEmail("embed-user@example.com");
   });
 
+  test("COEP flag if not enabled, embed is blocked", async ({ page, embeds }) => {
```
Comment (hariombalhara) [inline packages/embeds/embed-core/playwright/tests/inline.e2e.ts:40]: Tests that COEP header isn't there by default.

**Comment by keithwillcode** [comment]
@Amit91848 @anikdhabal can one of you review and test this please?

**Comment by anikdhabal** [comment]
> @Amit91848 @anikdhabal can one of you review and test this please?

Sure

**Review by sean-brydon — APPROVED** [review]
Tested in playground all seems to work! Nice job @hariombalhara
