### PR TITLE
fix: start and end date for ooo entry

### LINKED ISSUE #13268: [CAL-2945] Time range wrong in OOO feature
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2945](https://linear.app/calcom/issue/CAL-2945/time-range-wrong-in-ooo-feature)</sub>

### PR DESCRIPTION
**Pull request by CarinaWolli**
## What does this PR do?

Fixes issue with wrong start and end date shown for ooo entries. This was caused by two issues (both of them depended on the user's browser timezone):
1. a correct date from the db was shown wrong in the UI 
2. date was saved wrong in the db

Fixes #13268

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: apps/web/pages/settings/my-account/out-of-office/index.tsx [hunk 1]
```diff
@@ -195,7 +198,7 @@ const OutOfOfficeEntriesList = () => {
             <TableRow key={item.id} data-testid={`table-redirect-${item.toUser?.username || "n-a"}`}>
               <TableCell>
                 <p className="px-2">
-                  {dayjs(item.start).format("ll")} - {dayjs(item.end).format("ll")}
+                  {dayjs.utc(item.start).format("ll")} - {dayjs.utc(item.end).format("ll")}
```
Comment (CarinaWolli) [inline apps/web/pages/settings/my-account/out-of-office/index.tsx:201]: fixes issues that wrong day was shown in UI

File: packages/trpc/server/routers/loggedInViewer/outOfOffice.handler.ts [hunk 2]
```diff
@@ -134,12 +134,14 @@ export const outOfOfficeCreate = async ({ ctx, input }: TBookingRedirect) => {
   if (existingOutOfOfficeEntry) {
     throw new TRPCError({ code: "BAD_REQUEST", message: "booking_redirect_infinite_not_allowed" });
   }
+  const startDateUtc = dayjs.utc(startDate).add(input.offset, "minute");
```
Comment (CarinaWolli) [inline packages/trpc/server/routers/loggedInViewer/outOfOffice.handler.ts:137]: The date form the `DateRangePicker` returns the date in utc but with offset hours from the user's browser timezone. 

So in NY `startDate` from `DateRangePicker` would be 05:00 instead of 00:00, wich ended up saving wrong days in database

File: apps/web/pages/settings/my-account/out-of-office/index.tsx [hunk 3]
```diff
@@ -104,20 +106,17 @@ const OutOfOfficeSection = () => {
               </div>
             )}
           </div>
-          <div className="mt-4 flex flex-row">
+          <div className="mt-4 grid grid-rows-2 gap-2 md:grid-cols-2">
             {profileRedirect && (
-              <div className="mr-2 w-1/2 lg:w-1/3">
+              <div className="">
```
Comment (joeauyeung) [inline apps/web/pages/settings/my-account/out-of-office/index.tsx:111]: Small NIT but I think we can clean up this empty className

**Review by joeauyeung — DISMISSED** [review]
LGTM. Tested by adding OOO entries and the DB record has the times stored as "2024-01-17T00:00:00.000Z" instead of "2024-01-17T05:00:00.000Z". Also rendering correctly.

File: apps/web/pages/settings/my-account/out-of-office/index.tsx (hunk 3 above)
Comment (CarinaWolli) [reply apps/web/pages/settings/my-account/out-of-office/index.tsx]: Remove it, can you re-approve @joeauyeung ?

**Review by joeauyeung — APPROVED** [review]

**Review by zomars — APPROVED** [review]
