### PR TITLE
fix: [CAL-2593]  Uploading a CSV File does not comma separate the values

### LINKED ISSUE #11742: [CAL-2593] Uploading a CSV File does not comma separate the values
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Uploading a CSV File does not comma separate the values

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- What's happening right now that is different from what is expected

### Expected Results

- This is an ideal result that the system should get after the tests are performed

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

<sub>[CAL-2593](https://linear.app/calcom/issue/CAL-2593/uploading-a-csv-file-does-not-comma-separate-the-values)</sub>

### PR DESCRIPTION
**Pull request by Chiranjeev-droid**
## What does this PR do?
This pr separates the valid email addresses so that team owners can bulk import their team members using a CSV file. When a user uploads the CSV file, it goes through every column because we don't know in which column the email is present. It checks whether it is a valid email; if it is, then it adds it to the email list and moves to the next line.

Fixes #11742 

Before Change 
 Loom Video: https://www.loom.com/share/b616e942a55141fbb62cb96366c10d4a?sid=67a9582f-a0d7-41ce-9a89-492a7490d6d4

After making changes
Loom Video: https://www.loom.com/share/857d4a5d5b9d44f498c3b0db23920bba?sid=2153fb9e-813c-44a0-b434-17fe769ae9a5

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Create a team
- Go to settings/teams and then choose the team you had created
- Go to members section of that team
- Click on add and import bulk members.

## Mandatory Tasks
- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: packages/features/ee/teams/components/MemberInvitationModal.tsx [hunk 1]
```diff
@@ -143,11 +143,24 @@ export default function MemberInvitationModal(props: MemberInvitationModalProps)
...
-        const values = contents?.split(",").map((email) => email.trim().toLocaleLowerCase());
-        newMemberFormMethods.setValue("emailOrUsername", values);
+        const lines = contents.split("\n");
+        const validEmails = [];
+        for (const line of lines) {
+          const columns = line.split(/,|;|\|| /);
+          for (const column of columns) {
+            const email = column.trim().toLowerCase();
+
+            if (emailRegex.test(email)) {
```
Comment (sean-brydon) [inline packages/features/ee/teams/components/MemberInvitationModal.tsx:156]: i wonder if we should just z.email(email).parse() for this to keep inline with the rest of our app testing (They do pretty much the same thing just a NIT)

**Review by sean-brydon — APPROVED** [review]
LGTM - tested locally and works perfectly. NIT doesnt need to be addressed and can be picked up in a follow up.

**Comment by sean-brydon** [comment]
### Merge activity

* **Oct 16, 5:39 AM**: [Graphite](https://app.graphite.dev/github/pr/calcom/cal.com/11756) failed to merge this pull request due to **internal failures**. Try your merge again, or report a bug if you see this consistently.
