### PR TITLE
fix: [CAL-4296] Fix Booking Text wrap issue for multi emails

### LINKED ISSUE #16559: [CAL-4296] text of booking question does not stays inside of the box
text of booking question does not stays inside of the box

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4296](https://linear.app/calcom/issue/CAL-4296/text-of-booking-question-does-not-stays-inside-of-the-box)</sub>

### PR DESCRIPTION
**Pull request by Raghul18**
## What does this PR do?
Fixes Text wrap issue for multi email option in booking.

- Fixes #16559 (GitHub issue number)
- Fixes CAL-4296 (Linear issue number - should be visible at the bottom of the GitHub issue description)

Before Fix: 
booking before text

After Fix:
booking after text

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

### CODE REVIEW

File: packages/features/form-builder/Components.tsx [hunk 1]
```diff
@@ -306,7 +306,7 @@ export const Components: Record<FieldType, Component> = {
                 value.push("");
                 setValue(value);
               }}
-              className="mr-auto">
+              className="mr-auto h-fit whitespace-normal text-left">
```
Comment (anikdhabal) [inline packages/features/form-builder/Components.tsx:309]: This is not how it should be fixed for email; you can simply use break-all. Also, this issue is visible in other booking fields, not just in the 'Add Guests' field

File: packages/ui/components/button/Button.tsx [hunk 2]
```diff
@@ -171,7 +171,8 @@ export const Button = forwardRef<HTMLAnchorElement | HTMLButtonElement, ButtonPr
                 name={StartIcon}
                 className={classNames(
                   variant === "icon" && "h-4 w-4",
-                  variant === "button" && "h-4 w-4 stroke-[1.5px] ltr:-ml-1 ltr:mr-2 rtl:-mr-1 rtl:ml-2"
+                  variant === "button" &&
+                    "h-4 w-4 shrink-0 stroke-[1.5px] ltr:-ml-1 ltr:mr-2 rtl:-mr-1 rtl:ml-2"
```
Comment (anikdhabal) [inline packages/ui/components/button/Button.tsx:175]: unnecessary changes

**Review by anikdhabal — CHANGES_REQUESTED** [review]
Left comments

File: packages/ui/components/button/Button.tsx (hunk 2 above)
Comment (Raghul18) [reply packages/ui/components/button/Button.tsx:175]: @anikdhabal : I have just added shrink-0 class. If i don't apply shrink-0 then icon gets squeezed. Attaching Screenshot for reference
image

**Comment by Raghul18** [comment]
> Left comments

@anikdhabal resolved the comments

File: packages/ui/components/button/Button.tsx (hunk 2 above)
Comment (anikdhabal) [reply packages/ui/components/button/Button.tsx:175]: This is used globally. For small bug, I prefer not to update this. Please use a different method

File: packages/features/form-builder/Components.tsx (hunk 1 above)
Comment (anikdhabal) [reply packages/features/form-builder/Components.tsx:309]: Screenshot 2024-09-11 001427
It's a problem in my end

Comment (Raghul18) [reply packages/features/form-builder/Components.tsx:309]: @anikdhabal : This is happening because it is a single word. Please use multiple words and try. In addition to above classes will add work-break all aswell to break a single long word.

File: packages/ui/components/button/Button.tsx (hunk 2 above)
Comment (Raghul18) [reply packages/ui/components/button/Button.tsx:175]: @anikdhabal : I do understand it is used at global level, but is there any place where we want to shrink the icon? Even in the same booking page i noticed shrink-0 is applied to icons. 

Also it is difficult to fix this issue without modifying Button.tsx file. Other than adding the class directly i have 2-3 approaches mentioned below. Please let me know which works best or feel free to suggest an alternate approach
1) add a new prop like startIconClasses and include it in Icon classname.
2) pass the icon as customstartIcon (Note: need to copy all the button classes and pass it as icon from Component.tsx)
3) create a new property for shrink in buttonClasses which in turn provides the ability to control shrink based on props.

**Review by anikdhabal — APPROVED** [review]
