### PR TITLE
fix: Allow i18n of form builder max/min character count. Earlier strings missed due to variable. 

### LINKED ISSUE #22358: Missing translation in German

### PR DESCRIPTION
**Pull request by Anshumancanrock**
## What does this PR do?

- Fixes #22358 (GitHub issue number)
- Fixes CAL-6070(Linear issue number - should be visible at the bottom of the GitHub issue description)

**Key Changes:**
- Fixes missing German localization for form validation messages

#### Image Demo:

**Before (Issues):**

68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f65383662663935372d643832662d343635652d623230352d3133353535396634623632332f63626263323830322d633262662d346663362d393462362d3666383662656435366161372f626132666137

- German users saw "Min. 20 characters required" instead of localized text

**After (Fixed):**

Screenshot 2025-07-11 233252

https://github.com/user-attachments/assets/3bec74ab-a382-4f15-9138-3cf08a0c1b85

- German users see: "Min. 20 Zeichen erforderlich"

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write **N/A** here and check the checkbox. **N/A** - These are internal URL construction fixes that don't affect public API.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

**Environment Setup:**
- No special environment variables required
- Standard Cal.com development setup

**Test Cases:**

 **German Translation Validation:**
   - Set browser language to German
   - Create/edit an event type with form fields requiring min/max characters
   - Verify validation messages appear in German: "Min. 20 Zeichen erforderlich"

**Expected Results:**
- German form validation messages display correctly

**Minimal Test Data:**

- German locale enabled in browser/system

## Checklist

- [x] I have read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have checked if my changes generate no new warnings
    

---
## Summary by cubic
Localized min/max character validation messages and wired schemas to use i18n with count placeholders, so German users now see correct error text.

- **Bug Fixes**
  - Replaced hardcoded length errors with translation keys and count interpolation; added locale strings.
  - Passed translateFn through booking responses and form-builder schemas to surface localized errors (CAL-6070).

<sup>Written for commit 89fdc33e186fa67b9689fa17d0e0d885507f54a7. Summary will update automatically on new commits.</sup>

### CODE REVIEW

**Comment by akashkinkarpandey** [comment]
@Anshumancanrock Can you please provide a loom video confirming the German translation ?

**Review by anikdhabal — DISMISSED** [review]
Pls share the evidence of the fix

**Review by kart1ka — CHANGES_REQUESTED** [review]
does not seem to work

Image

**Comment by Anshumancanrock** [comment]
@anikdhabal @kart1ka . Sorry for the delay in getting back. I’ve made the requested changes now and also added a video showing that the German translation issue is fixed.

Let me know if there’s anything else I should update. Really appreciate your time !

**Comment by kart1ka** [comment]
@Anshumancanrock I don't see the video.
Also can you please make sure that all the necessary checks are passing? Type check seem to be failing.

**Comment by Anshumancanrock** [comment]
https://github.com/user-attachments/assets/7225888b-2685-4bd9-8d8f-44ff68b38c3a



@kart1ka Hey Sir, I’ve fixed the type check issue and made sure the video is showing properly now. Let me know if anything else needs to be updated !

File: packages/features/bookings/lib/getBookingResponsesSchema.ts [hunk 1]
```diff
@@ -317,7 +333,7 @@ function preprocess<T extends z.ZodType>({
 
         // Use fieldTypeConfig.propsType to validate for propsType=="text" or propsType=="select" as in those cases, the response would be a string.
         // If say we want to do special validation for 'address' that can be added to `fieldTypesSchemaMap`
-        if (["address", "text", "select", "number", "radio", "textarea"].includes(bookingField.type)) {
```
Comment (kart1ka) [inline packages/features/bookings/lib/getBookingResponsesSchema.ts:327]: why was "textarea" removed?

**Review by kart1ka — COMMENTED** [review]
Left a comment

File: packages/features/bookings/lib/getBookingResponsesSchema.ts (hunk 1 above)
Comment (Anshumancanrock) [reply packages/features/bookings/lib/getBookingResponsesSchema.ts:327]: You can add it back sir ! It would still work without breaking anything. Please let me know if you want any changes.

**Comment by Anshumancanrock** [comment]
@anikdhabal Please review this. Appreciate your time !

File: packages/features/bookings/lib/getBookingResponsesSchema.ts (hunk 1 above)
Comment (kart1ka) [reply packages/features/bookings/lib/getBookingResponsesSchema.ts:327]: Pls make the changes if this was removed without a reason.

Comment (Anshumancanrock) [reply packages/features/bookings/lib/getBookingResponsesSchema.ts:327]: I have added "textarea" back. Please let me know if you want any other changes.

**Review by kart1ka — DISMISSED** [review]
LGTM

**Comment by kart1ka** [comment]
@Anshumancanrock Can you pls fix the merge conflicts?

**Comment by Anshumancanrock** [comment]
@kart1ka Hey Sir !  I have fixed the merge conflicts + added a fix to tackle the grammatical issue where we were showing "1 characters required" instead of "1 character required".  Please let me know if you want any other changes. Appreciate your time !

**Comment by Anshumancanrock** [comment]
@kart1ka Hey Sir ! Because of Rabbit AI suggestion i implemented "1 character" case without even thinking that the "1 character" case would never actually be displayed to users because of required field message, hence we dont need to handle that case.  So i reverted that change and now everything is working clean like before.

Here is the ss of translation after these changes:

Screenshot 2025-07-15 120921

Appreciate your time !

**Review by kart1ka — DISMISSED** [review]
LGTM

**Comment by Anshumancanrock** [comment]
@anikdhabal Please review sir and let me know if you want any changes. Appreciate your time !

**Comment by kart1ka** [comment]
@Anshumancanrock It will be reviewed. It is going to take some time.

File: apps/web/public/static/locales/en/common.json [hunk 2]
```diff
@@ -10,6 +10,8 @@
   "accept_invitation": "Accept Invitation",
   "max_characters": "Max. Characters",
   "min_characters": "Min. Characters",
+  "min_characters_required": "Min. {{count}} characters required",
+  "max_characters_allowed": "Max. {{count}} characters allowed",
```
[the remark this answers is not in the document]
Comment (keithwillcode) [reply apps/web/public/static/locales/en/common.json:14]: @Anshumancanrock Let's implement this suggestion from CodeRabbit

**Review by keithwillcode — DISMISSED** [review]

**Comment by Anshumancanrock** [comment]
@keithwillcode I've implemented the plural forms and updated both English and German locales exactly as suggested. Please take a look and let me know if you’d like me to make any other changes.

**Comment by Anshumancanrock** [comment]
@keithwillcode  The "1 character" case will never show since required field validation runs first, but implemented the complete pattern to follow i18next best practices as per your suggestions.
 
 Here is the latest video after changes:


https://github.com/user-attachments/assets/30e2d172-1752-43e1-99f1-2a61d239385a

Please take a look and let me know if you’d like me to make any other changes.

**Comment by Anshumancanrock** [comment]
@kart1ka @keithwillcode Pease review this pr sir . It's been open for a long time and I would appreciate your feedback when you have a moment.

**Review by anikdhabal — DISMISSED** [review]

File: apps/web/public/static/locales/de/common.json [hunk 3]
```diff
@@ -10,6 +10,10 @@
   "accept_invitation": "Einladung annehmen",
   "max_characters": "Max. Zeichen",
   "min_characters": "Min. Zeichen",
+  "min_characters_required_one": "Min. {{count}} Zeichen erforderlich",
+  "min_characters_required_other": "Min. {{count}} Zeichen erforderlich",
```
Comment (kart1ka) [inline apps/web/public/static/locales/de/common.json]: These two keys have the same values and also "min_characters_required_one" is not used anywhere in the code.

File: apps/web/public/static/locales/de/common.json [hunk 4]
```diff
@@ -10,6 +10,10 @@
...
+  "max_characters_allowed_one": "Max. {{count}} Zeichen erlaubt",
+  "max_characters_allowed_other": "Max. {{count}} Zeichen erlaubt",
```
Comment (kart1ka) [inline apps/web/public/static/locales/de/common.json]: same is true here as well

**Review by kart1ka — CHANGES_REQUESTED** [review]
left some comments

File: apps/web/public/static/locales/de/common.json (hunk 4 above)
Comment (Anshumancanrock) [reply apps/web/public/static/locales/de/common.json]: @kart1ka The word Zeichen works for both ‘character’ and ‘characters’ in German. I am aware that min_characters_required_one is not used anywhere in the code, as it is overridden by the ‘This field is required’ message, but since this change was requested by @keithwillcode, I implemented it even though it is not used anywhere in the code.

Screenshot 2025-09-02 181731

Comment (anikdhabal) [reply apps/web/public/static/locales/de/common.json]: @Anshumancanrock if it's not use anywhere pls remove it

**Comment by Anshumancanrock** [comment]
@kart1ka  The word Zeichen works for both ‘character’ and ‘characters’ in German. I am aware that min_characters_required_one is not used anywhere in the code, as it is overridden by the ‘This field is required’ message, but since this change was requested by @keithwillcode, I implemented it even though it is not used anywhere in the code.

**Comment by kart1ka** [comment]
> @kart1ka The word Zeichen works for both ‘character’ and ‘characters’ in German. I am aware that min_characters_required_one is not used anywhere in the code, as it is overridden by the ‘This field is required’ message, but since this change was requested by @keithwillcode, I implemented it even though it is not used anywhere in the code.

Remove this if it is not used anywhere. I have also noticed that you are using "min_characters_required" and "max_characters_required" for i18n but they are not present in the common.json file. Please fix this issue as well

**Review by kart1ka — DISMISSED** [review]
LGTM

**Review by kart1ka — DISMISSED** [review]

**Comment by kart1ka** [comment]
Build is successful now. Please review @volnei

**Comment by Anshumancanrock** [comment]
@volnei could you please take a look when convenient? Thanks!

**Comment by Anshumancanrock** [comment]
@anikdhabal Could you kindly review this PR? Thank you!

**Comment by Anshumancanrock** [comment]
Hi @keithwillcode, is there anything wrong with this PR?

**Comment by volnei** [comment]
> @volnei could you please take a look when convenient? Thanks!

hey @Anshumancanrock, we don't need to introduce changes for specific languages, only english and let's lingo.dev to make appropriated translations for all supported languages.

**Comment by Anshumancanrock** [comment]
Hi @volnei,
Thanks for clarifying. I’ve removed the German translations from my PR. You are right that lingo.dev should handle translations.
Apart from that, my PR fixes the hardcoded English logic that was preventing other translations from appearing.
Please review it now !

**Comment by Anshumancanrock** [comment]
@kart1ka, please review this now.

**Review by dhairyashiil — CHANGES_REQUESTED** [review]
Everything looks good. Please resolve this last comment and let’s get this merged. I can see it’s been pending for a long time.
making it draft until then

File: packages/features/bookings/lib/getBookingResponsesSchema.ts [hunk 5]
```diff
@@ -10,7 +10,8 @@ import { bookingResponses, emailSchemaRefinement } from "@calcom/prisma/zod-util
 // eslint-disable-next-line @typescript-eslint/ban-types
 type View = ALL_VIEWS | (string & {});
 type BookingFields = (z.infer<typeof eventTypeBookingFields> & z.BRAND<"HAS_SYSTEM_FIELDS">) | null;
-type CommonParams = { bookingFields: BookingFields; view: View };
+type TranslationFunction = (key: string, options?: any) => string;
```
Comment (dhairyashiil) [inline packages/features/bookings/lib/getBookingResponsesSchema.ts]: we don't want any 
let's use proper types

**Comment by Anshumancanrock** [comment]
Fixed! Replaced [any] with [Record<string, unknown>] to match the actual implementation in [useBookingForm.ts]. Thanks for catching that!

File: apps/web/public/static/locales/en/common.json [hunk 6]
```diff
@@ -10,6 +10,8 @@
   "accept_invitation": "Accept Invitation",
   "max_characters": "Max. Characters",
   "min_characters": "Min. Characters",
+  "min_characters_required": "Min. {{count}} characters required",
```
[the remark this answers is not in the document]
Comment (Anshumancanrock) [reply apps/web/public/static/locales/en/common.json:13]: we don't need to introduce changes for specific languages, let's lingo.dev will manage appropriated translations for all supported languages.

File: packages/features/form-builder/schema.ts [hunk 7]
```diff
@@ -116,7 +116,7 @@ export const fieldTypesSchemaMap: Partial<
         response: string;
         isPartialSchema: boolean;
         ctx: z.RefinementCtx;
-        m: (key: string) => string;
+        m: (key: string, options?: any) => string;
```
Comment (dhairyashiil) [inline packages/features/form-builder/schema.ts]: this one?

Comment (Anshumancanrock) [reply packages/features/form-builder/schema.ts]: done ser ! Thanks for reminding

Comment (dhairyashiil) [reply packages/features/form-builder/schema.ts]: haha, you can call me dhairyashil, and thank you for quick fix

**Review by dhairyashiil — APPROVED** [review]
LGTM 👍🏼 Thank you for the contribution and for being so patient with all the back and forth communication, I know this can be tiring

**Comment by anikdhabal** [comment]
cc @volnei can you pls check this in the meantime?

**Review by emrysal — APPROVED** [review]
Looks good to me, but the title doesn't seem accurate, will update.
