### PR TITLE
fix: add booking form prefill e2e test

### LINKED ISSUE #10242: [CAL-2201] E2E to verify that session name and email are prefilled in booking form
Write an e2e that could have avoided this regression https://github.com/calcom/cal.com/issues/10227

There are many booking form tests already, let's just ensure that the user is logged in, in one of them and verify the name and email prefill from session

<sub>[CAL-2201](https://linear.app/calcom/issue/CAL-2201/e2e-to-verify-that-session-name-and-email-are-prefilled-in-booking)</sub>

### PR DESCRIPTION
**Pull request by nicktrn**
## What does this PR do?

Ensures that booking form is prefilled:
- from session when logged in
- from query params regardless of auth

Fixes #10242 

Prevents regressions:
- [x] #10227

## New features

- users fixture `create()` method now returns email and name

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

```
yarn e2e -g prefill
```

### CODE REVIEW

File: apps/web/playwright/fixtures/users.ts [hunk 1]
```diff
@@ -311,7 +313,7 @@ const createUser = (workerInfo: WorkerInfo, opts?: CustomUserOpts | null): Prism
   const uname = `${opts?.username || "user"}-${workerInfo.workerIndex}-${Date.now()}`;
   return {
     username: uname,
-    name: opts?.name,
+    name: opts?.name || "Default Name",
```
Comment (nicktrn) [inline apps/web/playwright/fixtures/users.ts:316]: maybe we should add a way to not add a name, is that ever required for tests or even possible for real users?

**Review by nicktrn — COMMENTED** [review]
Ready for review :eyes:

**Comment by nicktrn** [comment]
Will fix the errors in a moment

File: apps/web/playwright/fixtures/users.ts (hunk 1 above)
Comment (nicktrn) [reply apps/web/playwright/fixtures/users.ts:316]: At least one test relies on a "Nameless" return. Will change the default to that for now.

**Review by keithwillcode — APPROVED** [review]
Nice. Love the addition of tests.

**Comment by nicktrn** [comment]
Will ping you when #10518 is done in that case ;)

**Comment by hariombalhara** [comment]
Thanks a lot @nicktrn !! Really appreciate that.  🙏

**Comment by nicktrn** [comment]
Happy to help. More tests incoming soon, hopefully with full email support. Seen you worked on that @hariombalhara so will let you know when I have updates.
