### PR TITLE
fix: move organization members list

### LINKED ISSUE #17534: [CAL-4675] Move organization /settings/organizations/members to /members
* Move organization member list from settings to the root Navigation
* Only visible if in an org

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4675](https://linear.app/calcom/issue/CAL-4675/move-organization-settingsorganizationsmembers-to-members)</sub>

### PR DESCRIPTION
**Pull request by eunjae-lee**
## What does this PR do?

This moves Organization Members page
- from `/settings/organizations/members`
- to `/settings/organization/[orgSlug]/members`
 
so that it's more accessible on the root Sidebar.

- Fixes #17534 (GitHub issue number)
- Fixes CAL-4675 (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

**Previously, under Settings**

Screenshot 2024-11-07 at 14 35 34

**Now, at root**

Screenshot 2024-11-15 at 14 49 58

### CODE REVIEW

File: packages/features/shell/navigation/Navigation.tsx [hunk 1]
```diff
@@ -131,33 +140,40 @@ const platformNavigation: NavigationItemType[] = [
...
-        items.mobileNavigationBottomItems.push(item);
-      } // Items for the "more" menu in mobile navigation
-      else {
-        items.mobileNavigationMoreItems.push(item);
-      }
-      return items;
-    },
-    { desktopNavigationItems: [], mobileNavigationBottomItems: [], mobileNavigationMoreItems: [] }
-  );
+const useDesktopNavigationItems = (isPlatformNavigation = false) => {
```
Comment (eunjae-lee) [inline packages/features/shell/navigation/Navigation.tsx:143]: It was exported but never used anywhere. So I removed `export` keyword and turned it into a hook (so that I can use `useOrgBranding()` hook inside)

**Review by eunjae-lee — COMMENTED** [review]
This setting makes it easier to review this PR, FYI.

Screenshot 2024-11-07 at 14 20 19

File: packages/features/shell/navigation/Navigation.tsx [hunk 2]
```diff
@@ -131,33 +142,36 @@ const platformNavigation: NavigationItemType[] = [
   },
 ];
 
-export const getDesktopNavigationItems = (isPlatformNavigation = false) => {
-  const navigationType = !isPlatformNavigation ? navigation : platformNavigation;
-  const moreSeparatorIndex = navigationType.findIndex((item) => item.name === MORE_SEPARATOR_NAME);
+const useNavigationItems = (isPlatformNavigation = false) => {
```
Comment (eunjae-lee) [inline packages/features/shell/navigation/Navigation.tsx:145]: It was exported but never used anywhere. So I removed `export` keyword and turned it into a hook (so that I can use `useOrgBranding()` hook inside)

File: apps/web/pages/orgs/[orgSlug]/members/index.tsx [hunk 3]
```diff
@@ -0,0 +1,9 @@
+import PageWrapper from "@components/PageWrapper";
```
Comment (keithwillcode) [inline apps/web/pages/orgs/[orgSlug]/members/index.tsx:1]: Based on our post in Campsite, I think we decided to actually move this to /settings/organizations/[id]/members to match the other routes

**Review by keithwillcode — DISMISSED** [review]
https://github.com/calcom/cal.com/pull/17531/files#r1846673515

File: apps/web/pages/orgs/[orgSlug]/members/index.tsx (hunk 3 above)
Comment (eunjae-lee) [reply apps/web/pages/orgs/[orgSlug]/members/index.tsx:1]: Oh I see. I misunderstood it then. ([ref](https://linear.app/calcom/issue/CAL-4675/move-organization-settingsorganizationsmembers-to-members#comment-88cbfa9d))

Working on it now

**Review by zomars — DISMISSED** [review]
LGTM

**Comment by eunjae-lee** [comment]
hey @zomars i've made two more commits: https://github.com/calcom/cal.com/pull/17531/commits/fbf4db9fc548a6d6801c321d5988aff854f298c1 and https://github.com/calcom/cal.com/pull/17531/commits/6459b83dcfdc17de8277cff166caf0cb6c52581a

could you give it another review? :)

**Review by zomars — DISMISSED** [review]

**Review by zomars — DISMISSED** [review]

**Review by zomars — DISMISSED** [review]
Fixed conflicts

File: packages/features/settings/layouts/SettingsLayout.tsx [hunk 4]
```diff
@@ -77,10 +77,6 @@ const tabs: VerticalTabItemProps[] = [
         name: "general",
         href: "/settings/organizations/general",
       },
-      {
-        name: "members",
```
Comment (hbjORbj) [inline packages/features/settings/layouts/SettingsLayout.tsx:81]: can you make the same change in `SettingsLayoutAppDirClient`? We currently keep two same layouts until we fully migrate to app router

**Review by hbjORbj — APPROVED** [review]
