### PR TITLE
[CAL-925] fix: add null check for userSchedule.availability

### LINKED ISSUE #6708: [CAL-925] 500 on prod /api/trpc/viewer.public.slots.getSchedule
```
Something went wrong TypeError: Cannot read properties of undefined (reading 'availability')
    at getUserAvailability (/var/task/apps/web/.next/server/chunks/8555.js:1358:36)
    ... 14 lines matching cause stack trace ...
    at async resolveHTTPResponse (file:///var/task/node_modules/@trpc/server/dist/resolveHTTPResponse-6bee34f0.mjs:120:28) {
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError',
  [cause]: TypeError: Cannot read properties of undefined (reading 'availability')
      at getUserAvailability (/var/task/apps/web/.next/server/chunks/8555.js:1358:36)
      at async /var/task/apps/web/.next/server/chunks/7024.js:8763:99
      at async Promise.all (index 0)
      at async getSchedule (/var/task/apps/web/.next/server/chunks/7024.js:8762:82)
      at async /var/task/apps/web/.next/server/chunks/7024.js:8631:16
      at async resolveMiddleware (file:///var/task/node_modules/@trpc/server/dist/index.mjs:383:30)
      at async callRecursive (file:///var/task/node_modules/@trpc/server/dist/index.mjs:419:32)
      at async next (file:///var/task/node_modules/@trpc/server/dist/index.mjs:427:32)
      at async callRecursive (file:///var/task/node_modules/@trpc/server/dist/index.mjs:419:32)
      at async next (file:///var/task/node_modules/@trpc/server/dist/index.mjs:427:32)
      at async /var/task/apps/web/.next/server/chunks/7024.js:10865:20
      at async callRecursive (file:///var/task/node_modules/@trpc/server/dist/index.mjs:419:32)
      at async resolve (file:///var/task/node_modules/@trpc/server/dist/index.mjs:447:24)
      at async file:///var/task/node_modules/@trpc/server/dist/resolveHTTPResponse-6bee34f0.mjs:123:32
      at async Promise.all (index 0)
      at async resolveHTTPResponse (file:///var/task/node_modules/@trpc/server/dist/resolveHTTPResponse-6bee34f0.mjs:120:28)
}
```

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-925](https://linear.app/calcom/issue/CAL-925/500-on-prod-apitrpcviewerpublicslotsgetschedule)</sub>

### PR DESCRIPTION
**Pull request by ShaneMaglangit**
## What does this PR do?

Fixes #6708

This issue seems to appear when the user does not have any availability created.
- Does not happen when using any of the pre-created accounts, even if all availability are removed.

**Environment**: Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't commented my code, particularly in hard-to-understand areas
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/core/getUserAvailability.ts [hunk 1]
```diff
@@ -231,7 +231,7 @@ export async function getUserAvailability(
       ? { ...eventType?.schedule }
       : {
           ...userSchedule,
-          availability: userSchedule.availability.map((a) => ({
+          availability: userSchedule?.availability.map((a) => ({
```
Comment (emrysal) [inline packages/core/getUserAvailability.ts:234]:
```suggestion
          // FIXME: Default Schedule can be null if the user has no schedules at all
          //        - Create testcases & test through the behaviour in this edge case.
          availability: userSchedule?.availability.map((a) => ({
```

**Review by emrysal — APPROVED** [review]

**Comment by emrysal** [comment]
Thank you for your contribution! I added a FIXME so we will come back to this later to handle the situation with no availability better; but this fixes the hard crash 👍
