### PR TITLE
fix: use getVideoData function

### LINKED ISSUE #7176: [CAL-1104] Non Cal link for Cal Video on success page
When CalVideo is chosen as the location, the success page (`/booking/[uid]`) doesn't show cal.com/video link. The link is correct in email that is received.

Email:
Screenshot 2023-02-17 at 5 30 06 PM

Success Page:
Screenshot 2023-02-17 at 5 27 13 PM

<sub>[CAL-1104](https://linear.app/calcom/issue/CAL-1104/non-cal-link-for-cal-video-on-success-page)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/7176

Screenshot 2023-02-19 at 3 28 43 AM

**Environment**: Staging(main branch) / Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 1]
```diff
@@ -1127,7 +1125,7 @@ async function handler(req: NextApiRequest & { userId?: number | undefined }) {
   }
 
   log.debug(`Booking ${organizerUser.username} completed`);
-  const metadata = videoCallUrl ? { videoCallUrl } : undefined;
+  const metadata = videoCallUrl ? { videoCallUrl: getVideoCallUrl(evt) } : undefined;
```
Comment (Udit-takkar) [inline packages/features/bookings/lib/handleNewBooking.ts:1128]: we were using getVideoCallUrl function for sending url in emails

**Review by hariombalhara — APPROVED** [review]
