### PR TITLE
fix: request reschedule link in email for an Org event

### LINKED ISSUE #11785: [CAL-2602] Request reschedule broken for org event booking.
"Book a new Time" CTA in request reschedule email doesn't handle org context. It is app.cal.com for an org event and thus clicking on the link takes to 404 page
image

<sub>[CAL-2602](https://linear.app/calcom/issue/CAL-2602/request-reschedule-broken-for-org-event-booking)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?
Fixes #11785

Even though this PR adds some tests for verifying links in email, the exact scenario of the bug is still not verified because request reschedule flow doesn't have tests at the moment. 

Created a ticket #12141 to test that.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
- Create an event in an org
- Do a booking for it
- Do 'Request Reschedule' for the event(from the app when logged in as the event organizer)
- Check the link in the email sent to booker 

## Mandatory Tasks
- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by hariombalhara** [comment]
Current dependencies on/for this PR:
* main
  * **PR #12095** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/12095" target="_blank">Graphite</a> 
    * **PR #12116** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/12116" target="_blank">Graphite</a> 
      * **PR #12125** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/12125" target="_blank">Graphite</a>  👈
      * **PR #12124** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/12124" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/calcom/cal.com/12125?utm_source=stack-comment).

File: apps/web/test/utils/bookingScenario/bookingScenario.ts
Comment (hariombalhara) [inline apps/web/test/utils/bookingScenario/bookingScenario.ts:1]: Added organization support

File: apps/web/test/utils/bookingScenario/expects.ts
Comment (hariombalhara) [inline apps/web/test/utils/bookingScenario/expects.ts:1]: Borrowed changes from #11774

Adds support for testing links as required by the bug fix, plus adds support to verify other things in email

File: packages/features/bookings/lib/handleNewBooking/test/lib/getMockRequestDataForBooking.ts [hunk 1]
```diff
@@ -20,6 +21,8 @@ export function getMockRequestDataForBooking({
     eventTypeId: number;
     rescheduleUid?: string;
     bookingUid?: string;
+    recurringEventId?: string;
+    recurringCount?: number;
```
Comment (hariombalhara) [inline packages/features/bookings/lib/handleNewBooking/test/lib/getMockRequestDataForBooking.ts:25]: This too got in from #11774. Will be actually used by that PR.

File: packages/features/bookings/lib/handleNewBooking/test/lib/test.ts [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+        expect,
+        skip,
+        org: null,
+      });
+    },
+    timeout
+  );
+};
+
+export const testWithAndWithoutOrg = (
```
Comment (hariombalhara) [inline packages/features/bookings/lib/handleNewBooking/test/lib/test.ts:55]: Allows same test to run for both org(with a default organization) and non-org case.

File: packages/trpc/server/routers/viewer/bookings/requestReschedule.handler.ts [hunk 3]
```diff
@@ -167,6 +168,7 @@ export const requestRescheduleHandler = async ({ ctx, input }: RequestReschedule
   const builder = new CalendarEventBuilder();
   builder.init({
     title: bookingToReschedule.title,
+    bookerUrl: await getBookerUrl(user),
```
Comment (hariombalhara) [inline packages/trpc/server/routers/viewer/bookings/requestReschedule.handler.ts:171]: The same way we do it in handleNewBooking, provide bookerUrl so that all links can use that as the origin.

File: tests/libs/__mocks__/prisma.ts [hunk 4]
```diff
@@ -46,35 +45,6 @@ const handlePrismockBugs = () => {
...
-        if (or.endTime?.gte) {
-          or.endTime.lte = or.endTime.gte.toISOString ? or.endTime.gte.toISOString() : or.endTime.gte;
-        }
-        if (or.endTime?.lte) {
-          or.endTime.lte = or.endTime.lte.toISOString ? or.endTime.lte.toISOString() : or.endTime.lte;
-        }
-      });
-    }
-    return __findManyBooking(...rest);
-  };
```
Comment (hariombalhara) [inline tests/libs/__mocks__/prisma.ts:77]: Handled in a better way in bookingScenario.ts now.

**Review by Udit-takkar — COMMENTED** [review]
@hariombalhara I create a booking for a team event type in org.

When i click "Book a new time" i get redirected to this page


Screenshot 2023-10-30 at 1 37 11 PM

instead of booking page

**Review by ThyMinimalDev — APPROVED** [review]
LGTM, I noticed that we call `getBookerUrl` which calls `getBrand` which calls prisma to get the org. I think we should cache this as the org is not supposed to change often

**Comment by hariombalhara** [comment]
@Udit-takkar I recorded a loom and it's working for me https://www.loom.com/share/71c46088fab14030ac77f8314464a579

Could you record yours? Seems like some other edge case.

**Comment by Udit-takkar** [comment]
@hariombalhara 

https://www.loom.com/share/9f5d8588918a4ddcb443891028092dfe?sid=cd532e85-7963-4800-8b2a-59f3170eed20

**Comment by hariombalhara** [comment]
Thanks @Udit-takkar 🙏 Can replicate now. It's a bug with team events and  it's not specific to orgs. A non-org team has the same issue.
I wil fix it in a followup but seems important
