### PR TITLE
fix: Managed children event listing for organization members

### LINKED ISSUE #13723: [CAL-3154] Managed Event-types Dashboard listing issue
All Managed Event Type children are showing under the creator and not in the assignee's dashboard

Booking Links are working fine though

This is an organization specific issue

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3154](https://linear.app/calcom/issue/CAL-3154/managed-event-types-dashboard-listing-issue)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?
Fixes managed event-types listing in dashboard for organization members.

The root cause is that the profileId is wrongly set for children event-types. 

Fixes #13723

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
1. Login to acme using owner1-acme
2. Create a managed event-type for Team1
3. Assign it to two members - Member1 and Member2
4. Notice that owner1-acme is seeing the event-types 2 more times.(Bug)
5. Login as member1 and notice that there is no event-type in there.(Bug)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/lib/server/repository/eventType.ts [hunk 1]
```diff
@@ -156,6 +156,13 @@ export class EventTypeRepository {
             {
               profileId,
             },
+            // Fetch children event-types by userId because profileId is wrong
```
Comment (hariombalhara) [inline packages/lib/server/repository/eventType.ts:159]: profileId is wrong for children event-types. Will open a separate PR to fix that and add a migration to fix existing data.

File: packages/trpc/server/routers/viewer/eventTypes/getByViewer.handler.ts [hunk 2]
```diff
@@ -131,7 +132,15 @@ export const getByViewerHandler = async ({ ctx, input }: GetByViewerOptions) =>
     ),
   });
 
-  const userEventTypes = await Promise.all(profileEventTypes.map(mapEventType));
+  const userEventTypes = (await Promise.all(profileEventTypes.map(mapEventType))).filter((eventType) => {
+    const isAChildEvent = eventType.parentId;
+    // A child event only has one user
+    const childEventAssignee = eventType.users[0];
+    if (isAChildEvent && childEventAssignee.id != ctx.user.id) {
```
Comment (hariombalhara) [inline packages/trpc/server/routers/viewer/eventTypes/getByViewer.handler.ts:139]: If there is a childEvent that doesn't belong to the user remove that.

**Review by alishaz-polymath — APPROVED** [review]
🚀 
Works as a hotfix, awesome work 🙏

**Review by keithwillcode — APPROVED** [review]
