### PR TITLE
chore: fix all Typescript warnings

### LINKED ISSUE #8351: fix all Typescript warnings
image

### PR DESCRIPTION
**Pull request by gitstart-calcom**
Fixes #8351 

yarn lint: 
image

### CODE REVIEW

File: apps/web/components/AppListCard.tsx [hunk 1]
```diff
@@ -60,7 +60,7 @@ export default function AppListCard(props: AppListCardProps) {
         timeoutRef.current = null;
       }
     };
-  }, []);
+  }, [highlight, router, shouldHighlight]);
```
Comment (emrysal) [inline apps/web/components/AppListCard.tsx:63]: This is very risky, we can't merge this - I pushed a suggestion to https://github.com/calcom/cal.com/pull/8621 which @keithwillcode will evaluate, after which we can re-run the fixer and hopefully get the desired fixups without breaking anything.

**Review by emrysal — DISMISSED** [review]

File: apps/web/components/AppListCard.tsx (hunk 1 above)
Comment (keithwillcode) [reply apps/web/components/AppListCard.tsx]: @emrysal My thoughts [here](https://github.com/calcom/cal.com/pull/8621/files#r1192590344).

File: apps/web/components/apps/layouts/InstalledAppsLayout.tsx [hunk 2]
```diff
@@ -2,60 +2,12 @@ import type { ComponentProps } from "react";
 import React from "react";
 
 import AppCategoryNavigation from "@calcom/app-store/_components/AppCategoryNavigation";
-import type { InstalledAppVariants } from "@calcom/app-store/utils";
 import Shell from "@calcom/features/shell/Shell";
-import { trpc } from "@calcom/trpc/react";
-import type { HorizontalTabItemProps, VerticalTabItemProps } from "@calcom/ui";
-import { BarChart, Calendar, CreditCard, Grid, Share2, Video } from "@calcom/ui/components/icon";
-
-const tabs: (VerticalTabItemProps | HorizontalTabItemProps)[] = [
```
Comment (zomars) [inline apps/web/components/apps/layouts/InstalledAppsLayout.tsx:11]: Is this intended?

File: apps/web/pages/auth/saml-idp.tsx [hunk 3]
```diff
@@ -19,7 +19,7 @@ export default function Page() {
       callbackUrl: "/",
       code,
     });
-  }, []);
+  }, [router.isReady, router.query]);
```
Comment (zomars) [inline apps/web/pages/auth/saml-idp.tsx:22]: Router.query is an object. I think this will cause unintended behavior

File: apps/web/pages/auth/sso/direct.tsx [hunk 4]
```diff
@@ -29,7 +29,7 @@ export default function Page({ samlTenantID, samlProductID }: inferSSRProps<type
       },
       { tenant: samlTenantID, product: samlProductID }
     );
-  }, []);
+  }, [samlProductID, samlTenantID]);
```
Comment (zomars) [inline apps/web/pages/auth/sso/direct.tsx:32]: This changes the useEffect behavior. Let's be careful with these changes.

File: apps/web/pages/auth/sso/direct.tsx [hunk 5]
```diff
@@ -18,7 +18,7 @@ export default function Page({ samlTenantID, samlProductID }: inferSSRProps<type
     if (HOSTED_CAL_FEATURES) {
       router.push("/auth/login");
     }
-  }, []);
+  }, [router]);
```
Comment (zomars) [inline apps/web/pages/auth/sso/direct.tsx:21]: This changes the useEffect behavior. Let's be careful with these changes.

**Review by zomars — DISMISSED** [review]
Agreed with @emrysal we cannot trust auto fixes here. Most useEffect calls with empty dependencies are intentional. Let's triple check those please.

File: apps/web/components/apps/layouts/InstalledAppsLayout.tsx (hunk 2 above)
Comment (gitstart-calcom) [reply apps/web/components/apps/layouts/InstalledAppsLayout.tsx:11]: yes, we removed these because it was unused code

Comment (gitstart-calcom) [reply apps/web/components/apps/layouts/InstalledAppsLayout.tsx:11]: should we comment them instead?

Comment (zomars) [reply apps/web/components/apps/layouts/InstalledAppsLayout.tsx:11]: It's ok if it's really unused

**Review by emrysal — APPROVED** [review]
Applied a couple of pending fixes, if tests pass it's on auto-merge, nice work.
