### PR TITLE
fix: Theme class names for embed elements

### LINKED ISSUE #20913: Embed: light and dark classes on Custom Elements are in the embedding page scopes and thus embedding page could accidentally override embed css
Image

We need to find a way to keep https://github.com/calcom/cal.com/blob/main/packages/embeds/embed-core/src/addAppCssVars.ts#L11 working by changing the class names to something like cal-element-embed-light, cal-element-embed-dark

### PR DESCRIPTION
**Pull request by RajdeepDs**
## What does this PR do?

Modified theme class names to `cal-element-embed-light` and `cal-element-embed-dark` to prevent CSS conflicts with embedding pages, ensuring isolated styling for embed elements.

- Fixes #20913 
- Fixes [CAL-5647](https://linear.app/calcom/issue/CAL-5647/light-and-dark-classes-on-custom-elements-are-in-the-embedding-page) (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Visual Demo (For contributors especially)
A visual demonstration is strongly recommended, for both the original and new change (video / image - any one).
Before:
436613316-f0858153-730a-4080-87ad-09f565afcfb3
After:
Screenshot 2025-05-13 192132

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.
    

---

## Summary by mrge
Changed theme class names for embed elements to `cal-element-embed-light` and `cal-element-embed-dark` to prevent CSS conflicts with embedding pages. This ensures embed styles stay isolated and do not affect or get affected by host page styles.

### CODE REVIEW

**Review by TusharBhatt1 — DISMISSED** [review]
Good practice would be to keep it as constant and import at multiple places , making it draft until then , feel free to make it RFR

**Review by TusharBhatt1 — COMMENTED** [review]
Hey man , thanks for the PR - LGTM but a visual demo is verifying the changes is required here , making it draft until then

**Comment by RajdeepDs** [comment]
Hey @TusharBhatt1,
Embed previews aren’t showing on this branch, though they work fine on the main branch.
They were working earlier while I was making changes, and I don’t think anything I changed would’ve caused this.

Could you help me check this?

File: packages/embeds/embed-core/src/EmbedElement.ts [hunk 1]
```diff
@@ -197,20 +196,26 @@ export class EmbedElement extends HTMLElement {
...
+
+    const newThemeClass = getThemeClassForEmbed({ theme });
+
+    if (newThemeClass === this.themeClass) {
+      return;
+    }
+    this.themeClass = newThemeClass;
+    this.classList.remove(...allPossibleThemeClasses);
+    this.classList.add(this.themeClass);
+  }
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/EmbedElement.ts:210]: Centralize theme setting logic. It fixes an existing bug where the class wasn't changing on system theme change.

**Review by hariombalhara — DISMISSED** [review]

**Review by hariombalhara — APPROVED** [review]

**Review by hbjORbj — APPROVED** [review]
Makes tons of sense! Love the change.
