### PR TITLE
fix: your name translation

### LINKED ISSUE #14734: [CAL-3883] Event booking - one input label lacks Polish translation
### Issue Summary

When booking a meeting, after choosing the hour, first input label is "Your name" instead of "Imię i nazwisko".

### Steps to Reproduce

1. Go to cal.com/(user)/(event)
2. Choose date and hour.

### Actual Results

- After choosing the hour, first input label is "Your name" instead of "Imię i nazwisko".

### Expected Results

- Input label "Your name" should say for Polish "Imię i nazwisko".

### Technical details

- Happens on every browser.

### Evidence

image

<sub>[CAL-3883](https://linear.app/calcom/issue/CAL-3883/event-booking-one-input-label-lacks-polish-translation)</sub>

### PR DESCRIPTION
**Pull request by smitgol**
## What does this PR do?

Fixes #14734 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by malbq** [comment]
I'd like to share another perspective.
I saw the same issue as https://github.com/calcom/cal.com/issues/14734 when experimenting on a way to translate Booker Atom.
After some debugging, I came to same conclusion as @smitgol, that the label was overridden by the default value from `fieldTypes.ts`.

However, the correct label is already translated in:
https://github.com/calcom/cal.com/blob/56e59ab3e13a841124e4735ba972c10e109563b5/packages/features/form-builder/FormBuilderField.tsx#L57

My suggestion is to pass it down to the name component factory instead of translating it again: https://github.com/malbq/cal.com/commit/814fa953ae4ea0aa382e0f235647b5fdb28622cb

File: packages/features/form-builder/utils.ts [hunk 1]
```diff
@@ -53,21 +48,3 @@ function getFirstAndLastName(value: string | Record<"firstName" | "lastName", st
...
-  if (!fieldTypeConfig) throw new Error(`Invalid field.type ${field.type}}`);
-
-  const defaultVariantsConfig = fieldTypeConfig?.variantsConfig?.defaultValue;
-  const variantsConfig = fieldVariantsConfig || defaultVariantsConfig;
-
-  if (fieldTypeConfig.propsType === "variants" && !variantsConfig) {
-    throw new Error(`propsType variants must have variantsConfig`);
-  }
-  return variantsConfig;
-};
```
Comment (hariombalhara) [inline packages/features/form-builder/utils.ts:73]: Refactored out in a separate module variantsConfig

File: packages/features/form-builder/utils/variantsConfig.ts [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+  if (!fieldTypeConfig) throw new Error(`Invalid field.type ${field.type}}`);
+
+  const defaultVariantsConfig = fieldTypeConfig?.variantsConfig?.defaultValue;
+  const variantsConfig = fieldVariantsConfig || defaultVariantsConfig;
+
+  if (fieldTypeConfig.propsType === "variants" && !variantsConfig) {
+    throw new Error(`propsType variants must have variantsConfig`);
+  }
+  return variantsConfig;
+};
```
Comment (hariombalhara) [inline packages/features/form-builder/utils/variantsConfig.ts:49]: Copied from utils.ts

File: packages/features/form-builder/FormBuilderField.tsx [hunk 3]
```diff
@@ -333,8 +334,8 @@ export const ComponentForField = ({
   }
 
   if (componentConfig.propsType === "variants") {
-    const variantsConfig = getVariantsConfig(field);
-    if (!variantsConfig) {
+    const translatedVariantsConfig = getTranslatedVariantsConfig(field, t);
```
Comment (hariombalhara) [inline packages/features/form-builder/FormBuilderField.tsx:337]: Passing the translatedVariantsConfig directly so that Components don't need to do the translation.

**Review by hariombalhara — APPROVED** [review]
@smitgol Thanks for the PR.

I was testing out the PR and found a better approach to fix it. Could you please check the changes out and see if they are acceptable to you
