### PR TITLE
fix/3928-reschedule-unexpected-error

### LINKED ISSUE #3928: reschedule unexpected error
imagepotentially after already rescheduled?

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

Fixes api/book/event error handling. Now if a syntax error is received in defaultResponder message should be custom and not retrieved to user. Also improved default error message.

Fixes #3928

**Environment**: Staging(main branch)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] On api/book/event you can use JSON.parse("Error parsing") to be thrown on any part of the code and it should be handled properly.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/lib/server/getServerErrorFromUnknown.ts [hunk 1]
```diff
@@ -33,6 +33,12 @@ export function getServerErrorFromUnknown(cause: unknown): HttpError {
       cause,
     });
   }
+  if (cause instanceof SyntaxError) {
+    return new HttpError({
+      statusCode: 500,
+      message: "Unexpected error, please reach out for our customer support.",
+    });
+  }
```
Comment (alannnc) [inline packages/lib/server/getServerErrorFromUnknown.ts:41]: SyntaxError were being handled and response to user was misleading.

**Review by zomars — APPROVED** [review]
Nice catch @alannnc 🙏🏽
