### PR TITLE
fix: improve mobile positioning for link dialog in form builder checkbox editor

### LINKED ISSUE #24267: bug: Link dialog opens outside screen boundaries in checkbox question editor
### Issue Summary

The link attachment dialog in the checkbox input type within the "Add a question" feature opens outside the screen boundaries on mobile devices. When users try to add a link to checkbox question labels in event type advanced settings, the floating link editor dialog appears positioned outside the viewport, making it impossible to interact with on mobile and tablet devices.

### Steps to Reproduce

1. Navigate to Event Types in Cal.com
2. Click on an existing event type or create a new one
3. Go to the "Advanced" tab in event type settings
4. Scroll down to the "Booking Questions" section
5. Click "Add a booking question"
6. Select "Checkbox" as the input type
7. In the Label field, select some text and click the link button  in the editor toolbar
8. Observe the link dialog positioning on mobile/tablet devices (viewport width < 768px)

### Actual Results

- The link dialog appears outside the screen boundaries on mobile devices
- Users cannot see or interact with the link input field
- The dialog may be partially or completely cut off from the viewport
- The positioning logic doesn't account for mobile viewport constraints

### Expected Results

- The link dialog should appear within the screen boundaries on all device sizes
- The dialog should be properly positioned and fully accessible on mobile and tablet devices
- Users should be able to see and interact with the link input field regardless of screen size
- The dialog should have responsive positioning that adapts to different viewport sizes

### Technical details

- **Affected browsers**: All browsers on mobile and tablet devices
- **Screen sizes affected**: Devices with viewport width < 768px (tablets and mobile phones)

### Actual Result

https://github.com/user-attachments/assets/14421409-6c03-425d-ac90-aed70f51dab7

### PR DESCRIPTION
**Pull request by kartik-212004**
## What does this PR do?

This PR fixes a mobile positioning issue where the link attachment dialog in the checkbox input type within the "Add a question" feature opens outside screen boundaries on mobile and tablet devices. Users were unable to access or interact with the link dialog when editing checkbox question labels in event type advanced settings.

- Fixes #24267
- Fixes [CAL-6520](https://linear.app/calcom/issue/CAL-6520/bug-link-dialog-opens-outside-screen-boundaries-in-checkbox-question)

#### Video Demo (if applicable):

*Before Fix:*

https://github.com/user-attachments/assets/4c8e9fb5-1899-4a95-b1e5-12be75009a5d

*After Fix:

https://github.com/user-attachments/assets/81c330a5-cb80-47f3-8bb6-26a5fb0c4da7

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write **N/A** here and check the checkbox. *(N/A - This is a bug fix that doesn't require documentation changes)*
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

**Environment Setup:**
- No special environment variables required
- Standard Cal.com development environment

**Test Steps:**
1. **Desktop Testing:**
   - Navigate to Event Types → Select/Create Event → Advanced Tab
   - Add a checkbox question and verify link dialog works normally
   - Ensure no regression in existing functionality

2. **Mobile/Tablet Testing (Critical):**
   - Use browser dev tools to simulate mobile viewports (320px, 480px, 768px widths)
   - Or test on actual mobile/tablet devices
   - Follow same steps as desktop
   - Verify link dialog appears within screen boundaries
   - Test interaction with the dialog (typing URLs, saving links)

**Expected Results:**
- Link dialog stays within viewport boundaries on all screen sizes
- Dialog is fully accessible and interactive on mobile devices
- Consistent minimum width of 200px across all breakpoints
- No regression in desktop functionality
- Smooth responsive behavior when resizing browser window

**Test Data:**
- Any existing event type or create a new one
- No special test data required

### CODE REVIEW

**Review by dhairyashiil — CHANGES_REQUESTED** [review]
The PR looks good. Please remove unnecessary comments. Making it draft until then

File: packages/ui/components/editor/plugins/ToolbarPlugin.tsx [hunk 1]
```diff
@@ -56,8 +56,31 @@ function positionEditorElement(editor: HTMLInputElement, rect: DOMRect | null) {
...
-    editor.style.top = `${rect.top + rect.height + window.pageYOffset + 10}px`;
-    editor.style.left = `${rect.left + window.pageXOffset - editor.offsetWidth / 2 + rect.width / 2}px`;
+
+    let top = rect.top + rect.height + window.pageYOffset + 10;
+    let left = rect.left + window.pageXOffset - editor.offsetWidth / 2 + rect.width / 2;
+
+    const viewportWidth = window.innerWidth;
+    const viewportHeight = window.innerHeight;
+    const editorWidth = editor.offsetWidth || 300; // fallback width
+    const editorHeight = editor.offsetHeight || 100; // fallback height
```
Comment (dhairyashiil) [inline packages/ui/components/editor/plugins/ToolbarPlugin.tsx]: these ones

Comment (kartik-212004) [reply packages/ui/components/editor/plugins/ToolbarPlugin.tsx]: > these ones

removed the comments.

**Review by dhairyashiil — APPROVED** [review]
LGTM 👍🏼 , Thank you for your contribution.

**Review by dhairyashiil — APPROVED** [review]
LGTM 👍🏼

**Review by keithwillcode — APPROVED** [review]
