### PR TITLE
fix: Update forms UI

### LINKED ISSUE #7463: Routing Forms: Update forms UI
Current design:
Screenshot 2023-03-02 at 2 20 23 PM

Figma design:
Screenshot 2023-03-02 at 2 31 01 PM

https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=26%3A101811&t=H8vJq20EFrvW7I1g-4

### PR DESCRIPTION
**Pull request by gitstart-calcom**
Fixes #7463 

## Demo
https://www.loom.com/share/e38c151d6493467781bc2fa344344458

### CODE REVIEW

**Comment by gitstart-calcom** [comment]
Hi @Jaibles, the tests are partially failing because we have removed the "Test Preview" button according to the new design. Should we remove it from the tests too or should we add the button back? cc: @hariombalhara 
I have shared the screenshots of the current and new designs below:

Current design
Screenshot 2023-04-07 at 8 35 38 AM

New Design
Screenshot 2023-04-07 at 8 31 36 AM

Figma Link: https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?node-id=26%3A101811&amp;t=H8vJq20EFrvW7I1g-4

**Comment by hariombalhara** [comment]
'Send Email' and 'Test Previee' both are required. They are just missing in the new design

**Comment by hariombalhara** [comment]
@gitstart-calcom Can you please resolve the conflicts and let me know if it's ready to review again ?

**Comment by gitstart-calcom** [comment]
> @gitstart-calcom Can you please resolve the conflicts and let me know if it's ready to review again ?

@hariombalhara 
Conflicts have been resolved, and the PR is now ready for review :+1:

File: packages/app-store/routing-forms/components/RoutingNavBar.tsx [hunk 1]
```diff
@@ -27,7 +27,7 @@ export default function RoutingNavBar({
   ];
   return (
     <div className="mb-4">
-      <HorizontalTabs tabs={tabs} />
+      <HorizontalTabs isRoutingFormsTabs tabs={tabs} />
```
Comment (zomars) [inline packages/app-store/routing-forms/components/RoutingNavBar.tsx:30]: HorizontalTabs should be business logic agnostic. HorizontalTabs should not have to care if it's `isRoutingFormsTabs` or not.

File: packages/ui/components/form/toggleGroup/BooleanToggleGroup.tsx [hunk 2]
```diff
@@ -16,12 +16,14 @@ export const BooleanToggleGroup = function BooleanToggleGroup({
...
   // eslint-disable-next-line @typescript-eslint/no-empty-function
   onValueChange = () => {},
+  isSmaller,
   ...passThrough
 }: {
   defaultValue?: boolean;
   value?: boolean;
   onValueChange?: (value?: boolean) => void;
   disabled?: boolean;
+  isSmaller?: boolean;
```
Comment (zomars) [inline packages/ui/components/form/toggleGroup/BooleanToggleGroup.tsx:26]: Why not?

```suggestion
  variant?: 'default' | 'small';
```

File: packages/ui/components/navigation/tabs/HorizontalTabItem.tsx [hunk 3]
```diff
@@ -31,9 +39,14 @@ const HorizontalTabItem = function ({ name, href, linkProps, avatar, ...props }:
       href={href}
       {...linkProps}
       className={classNames(
-        isCurrent ? "bg-subtle text-emphasis" : "  hover:bg-subtle hover:text-emphasis text-default ",
+        isCurrent
+          ? isRoutingFormsTabs
+            ? "bg-emphasis text-emphasis"
+            : "bg-subtle text-emphasis"
```
Comment (zomars) [inline packages/ui/components/navigation/tabs/HorizontalTabItem.tsx:45]: If we're only using `isRoutingFormsTabs` to change classnames let's just allow the component to receive new classnames as prop. See my previous comment.

File: packages/ui/components/navigation/tabs/HorizontalTabs.tsx [hunk 4]
```diff
@@ -5,17 +5,18 @@ export interface NavTabProps {
...
+const HorizontalTabs = function ({ tabs, linkProps, actions, isRoutingFormsTabs, ...props }: NavTabProps) {
   return (
     <div className="mb-4 h-9 max-w-[calc(100%+40px)] lg:mb-5">
       <nav
         className="no-scrollbar flex max-h-9 space-x-1 overflow-scroll rounded-md"
         aria-label="Tabs"
         {...props}>
         {tabs.map((tab, idx) => (
-          <HorizontalTabItem {...tab} key={idx} {...linkProps} />
+          <HorizontalTabItem isRoutingFormsTabs={isRoutingFormsTabs} {...tab} key={idx} {...linkProps} />
```
Comment (zomars) [inline packages/ui/components/navigation/tabs/HorizontalTabs.tsx:19]: Same comment as above. HorizontalTabItem should not care about this.

**Review by zomars — DISMISSED** [review]
Left some comments 🙏🏽

**Comment by hariombalhara** [comment]
Screenshot 2023-05-06 at 4 35 02 PM
Navigation doesn't match figma. Padding and background are off

File: apps/web/public/static/locales/en/common.json [hunk 5]
```diff
@@ -1456,7 +1456,7 @@
   "team_url_required": "Must enter a team URL",
   "team_url_taken": "This URL is already taken",
   "team_publish": "Publish team",
-  "number_sms_notifications": "Phone number (SMS notifications)",
+  "number_sms_notifications": "Phone number (SMS notifications)",
```
Comment (hariombalhara) [inline apps/web/public/static/locales/en/common.json:1459]:
```suggestion
  "number_sms_notifications": "Phone number (SMS notifications)",
```

File: packages/app-store/routing-forms/components/RoutingNavBar.tsx [hunk 6]
```diff
@@ -11,7 +11,7 @@ export default function RoutingNavBar({
 }) {
   const tabs = [
     {
-      name: "Form",
+      name: "Forms",
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/components/RoutingNavBar.tsx:14]: I am not sure why we are calling it forms. It is a single Form. I am not sure if it's intentional in figma

File: packages/app-store/routing-forms/components/SingleForm.tsx [hunk 7]
```diff
@@ -280,6 +287,7 @@ function SingleForm({ form, appUrl, Page }: SingleFormComponentProps) {
         <FormActionsProvider appUrl={appUrl}>
           <Meta title={form.name} description={form.description || ""} />
           <ShellMain
+            upButton={!!form.description?.length}
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/components/SingleForm.tsx:290]: Why is this needed? `form.description` is actually the `subtitle` for Shell. It can handle that itself.

File: packages/app-store/routing-forms/components/SingleForm.tsx [hunk 8]
```diff
@@ -289,6 +297,7 @@ function SingleForm({ form, appUrl, Page }: SingleFormComponentProps) {
                 <div className="lg:min-w-72 lg:max-w-72 mb-6 md:mr-6">
                   <TextField
                     type="text"
+                    label="Routing forms"
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/components/SingleForm.tsx:300]: Again confused here. Why are we labelling a field as Routing Forms when it is the name of the Routing Form you are editing.

**Comment by hariombalhara** [comment]
No border for Routing tab.
Screenshot 2023-05-06 at 5 49 44 PM

**Comment by hariombalhara** [comment]
Screenshot 2023-05-06 at 5 53 27 PM
This is how the zero state looks. Is the background color correct? I think it should be bg-default only like for Routing and Form tab.

**Comment by hariombalhara** [comment]
Screenshot 2023-05-06 at 5 59 09 PM
Similarly for Reporting Tab, the reporting table should probably in white background

File: packages/app-store/routing-forms/components/SingleForm.tsx [hunk 9]
```diff
@@ -371,18 +380,26 @@ function SingleForm({ form, appUrl, Page }: SingleFormComponentProps) {
                       {t("test_preview")}
                     </Button>
                   </div>
+                  {!form.routes && (
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/components/SingleForm.tsx:383]:
```suggestion
                  {!form.routes?.some((r) => !r.isFallback) && (
```

There is always a fallback route even if user didn't define any route, so we need to exclude that to identify if there is a user defined route or not.

**Comment by hariombalhara** [comment]
Screenshot 2023-05-06 at 6 15 53 PM
Let's stick to one term, either options or attributes. I vote for options

**Review by hariombalhara — CHANGES_REQUESTED** [review]
There is no identifier now. I don't think that was intentional. It is probably missing in designs. Identifier is important to give a unique identifier to any field that would remain constant when label changes. By removing identifier explicitly, label is used as an identifier which can easily change.


I think while implementing design changes, we shouldn't make text modifications or logical changes unless explicitly mentioned. cc @Jaibles what do you think we should go about it? As designs can never be expected to be fully upto date(as feature keeps improving).

**Comment by gitstart-calcom** [comment]
> Screenshot 2023-05-06 at 4 35 02 PM
> 
> Navigation doesn't match figma. Padding and selected item background are off

Hi @hariombalhara, we are following [this](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/Cal---Live?type=design&node-id=26-101811&t=6CcKbn5VRz4qepxl-0) design
Screenshot 2023-05-09 at 9 02 42 PM

**Comment by gitstart-calcom** [comment]
> Screenshot 2023-05-06 at 5 53 27 PM
> 
> This is how the zero state looks. Is the background colour correct? I think it should be bg-default only like for Routing and Form tab.

@hariombalhara We don't have a reference for the zero-state design. Can you please provide a Figma link to the required design so that we can make the changes accordingly?

**Comment by gitstart-calcom** [comment]
Hi @hariombalhara! PR has been updated, please review 🙏

File: packages/app-store/routing-forms/components/SingleForm.tsx [hunk 10]
```diff
@@ -371,18 +378,28 @@ function SingleForm({ form, appUrl, Page }: SingleFormComponentProps) {
                       {t("test_preview")}
                     </Button>
                   </div>
+                  {!form.routes?.some(
+                    (r) => ("isFallback" in r && !r.isFallback) || !("isFallback" in r)
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/components/SingleForm.tsx:382]: There is a isFallbackRoute method. That takes care of this TypeScript requirement.
Screenshot 2023-05-11 at 12 47 14 PM

File: packages/app-store/routing-forms/pages/reporting/[...appPages].tsx [hunk 11]
```diff
@@ -165,7 +165,7 @@ const Reporter = ({ form }: { form: inferSSRProps<typeof getServerSideProps>["fo
   );
   return (
     <div className="flex flex-col-reverse md:flex-row">
-      <div className="cal-query-builder w-full ltr:mr-2 rtl:ml-2">
+      <div className="cal-query-builder bg-default w-full ltr:mr-2 rtl:ml-2">
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/pages/reporting/[...appPages].tsx:168]: missing border and other classes

File: packages/app-store/routing-forms/pages/form-edit/[...appPages].tsx [hunk 12]
```diff
@@ -85,30 +87,70 @@ function Field({
...
+    );
+  };
   return (
     <div
       data-testid="field"
-      className="group mb-4 flex w-full items-center justify-between ltr:mr-2 rtl:ml-2">
+      className="bg-default group mb-4 flex w-full items-center justify-between ltr:mr-2 rtl:ml-2">
       <FormCard
-        label={label || `Field ${fieldIndex + 1}`}
+        label={`Form ${fieldIndex + 1}`}
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/pages/form-edit/[...appPages].tsx:153]: This is supposed to be called Field only. The tab that shows it has name Form, so it can't have multiple forms. These are fields.

File: packages/app-store/routing-forms/pages/form-edit/[...appPages].tsx [hunk 13]
```diff
@@ -137,18 +180,13 @@ function Field({
...
-          <div className="mb-6 w-full">
-            <TextField
-              disabled={!!router}
-              label={t("placeholder")}
-              placeholder={t("this_will_be_the_placeholder")}
-              defaultValue={routerField?.placeholder}
-              {...hookForm.register(`${hookFieldNamespace}.placeholder`)}
+              defaultValue={
+                hookForm.watch(`${hookFieldNamespace}.identifier`) ||
+                hookForm.watch(`${hookFieldNamespace}.label`)
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/pages/form-edit/[...appPages].tsx:185]: What is the motivation behind this code change?

File: packages/app-store/routing-forms/pages/form-edit/[...appPages].tsx [hunk 14]
```diff
@@ -42,7 +44,7 @@ export const FieldTypes = [
     value: "textarea",
   },
   {
-    label: "Select",
+    label: "Single selection",
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/pages/form-edit/[...appPages].tsx:47]: Screenshot 2023-05-17 at 6 13 52 PM
It makes it inconsistent with MultiSelect. We should call that as `Multiple Selection` too

File: packages/app-store/routing-forms/pages/form-edit/[...appPages].tsx [hunk 15]
```diff
@@ -177,28 +226,55 @@ function Field({
             />
           </div>
           {["select", "multiselect"].includes(hookForm.watch(`${hookFieldNamespace}.type`)) ? (
-            <div className="mt-2 block items-center sm:flex">
-              <div className="w-full">
-                <TextAreaField
-                  disabled={!!router}
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/pages/form-edit/[...appPages].tsx:183]: Earlier it was disabled in case the field was coming from Router Form but now it's enabled.
Screenshot 2023-05-17 at 6 18 31 PM

File: packages/ui/components/card/FormCard.tsx [hunk 16]
```diff
@@ -61,16 +61,14 @@ export default function FormCard({
               </Badge>
             )}
           </div>
-          {deleteField?.check() ? (
```
Comment (hariombalhara) [inline packages/ui/components/card/FormCard.tsx:64]: Why was it removed? It results in showing delete button where it doesn't work. 

image

**Review by hariombalhara — COMMENTED** [review]
Left some more comments.

@gitstart-calcom I would recommend you to do a self review with the purpose being adding comments on the changes throughout the PR mentioning reasoning for the change.

File: packages/ui/components/alert/Alert.tsx [hunk 17]
```diff
@@ -32,29 +34,39 @@ export const Alert = forwardRef<HTMLDivElement, AlertProps>((props, ref) => {
...
-            />
-          )}
-          {severity === "neutral" && (
-            <Info className={classNames("text-default h-5 w-5", iconClassName)} aria-hidden="true" />
-          )}
-          {severity === "success" && (
-            <CheckCircleIcon className={classNames("text-muted h-5 w-5", iconClassName)} aria-hidden="true" />
-          )}
-        </div>
+        {CustomIcon ? (
```
[the remark this answers is not in the document]
Comment (niteshsingh1357) [reply packages/ui/components/alert/Alert.tsx:37]: Hi @sean-brydon, what should we do about this?

[the remark this answers is not in the document]
Comment (gitstart-calcom) [reply packages/ui/components/alert/Alert.tsx:37]: Hi @sean-brydon, what should we do here?

**Review by zomars — COMMENTED** [review]
Delegating my final approval to @hariombalhara as he's the code owner for routing forms

File: packages/app-store/routing-forms/pages/form-edit/[...appPages].tsx [hunk 18]
```diff
@@ -298,14 +378,14 @@ const FormEdit = ({
               StartIcon={Plus}
               color="secondary"
               onClick={addField}>
-              Add Field
+              Add form
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/pages/form-edit/[...appPages].tsx:381]: Add field

Comment (hariombalhara) [inline packages/app-store/routing-forms/pages/form-edit/[...appPages].tsx:381]:
```suggestion
              Add field
```

**Review by hariombalhara — APPROVED** [review]
LGTM now.  Thanks 🙏
Approving but will check for tests.
