### PR TITLE
fix: add metadata to stripe payment intent

### LINKED ISSUE #10678: [CAL-2327] Add more data to stripe payment metadata
Adding { identifier: "[cal.com](http://cal.com)", userId, eventName } as requested by user.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2327](https://linear.app/calcom/issue/CAL-2327/add-more-data-to-stripe-payment-metadata)</sub>

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

- Add booking and event metadata to payment intent stripe

Fixes #10678 

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Are there environment variables that should be set? No
- What are the minimal test data to have? Stripe app setup on event type
- What is expected (happy path) to have (input and output)? In stripe dashboard payment intent you should see new metadata to identify that this payment came from cal.com.
- Any other important info that could help to test that PR. No

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/app-store/stripepayment/lib/PaymentService.ts [hunk 1]
```diff
@@ -50,7 +50,8 @@ export class PaymentService implements IAbstractPaymentService {
     payment: Pick<Prisma.PaymentUncheckedCreateInput, "amount" | "currency">,
     bookingId: Booking["id"],
     bookerEmail: string,
-    paymentOption: PaymentOption
+    paymentOption: PaymentOption,
+    eventTitle?: string
```
Comment (alannnc) [inline packages/app-store/stripepayment/lib/PaymentService.ts:54]: We need to pass event title to stripe metadata

File: packages/app-store/stripepayment/lib/PaymentService.ts [hunk 2]
```diff
@@ -78,6 +79,12 @@ export class PaymentService implements IAbstractPaymentService {
         currency: this.credentials.default_currency,
         payment_method_types: ["card"],
         customer: customer.id,
+        metadata: {
+          identifier: "cal.com",
+          bookingId,
+          bookerEmail,
+          eventName: eventTitle || "",
```
Comment (alannnc) [inline packages/app-store/stripepayment/lib/PaymentService.ts:86]: New data to pass to stripe

**Review by zomars — APPROVED** [review]
LGTM
