### PR TITLE
fix: incorrect week-start input value

### LINKED ISSUE #16056: Incorrect default week start value(bug)
### Issue Summary

So, while adding new user in ui default value is monday but in request input it is sunday

### Steps to Reproduce

1. go to settings/admin/users/add
2. try to add user
3. check inputs sent with the request

### Expected behavior

The value in request input should be the default one(Monday).

### Other information

_No response_

### Screenshots

photo_2024-08-04_01-07-35

### Environment

- [X] app.cal.com
- [X] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS:Linux
- Node:20.12.2
- npm: 10.8.0
```

### PR DESCRIPTION
**Pull request by ymohit1603**
fixed incorrect default value in request.

- Fixes #16056 

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

File: packages/features/ee/users/components/UserForm.tsx [hunk 1]
```diff
@@ -95,7 +95,7 @@ export const UserForm = ({
       },
       timeZone: defaultValues?.timeZone || "",
       weekStart: {
-        value: defaultValues?.weekStart || weekStartOptions[0].value,
+        value: defaultValues?.weekStart || weekStartOptions[1].value,
```
Comment (anikdhabal) [inline packages/features/ee/users/components/UserForm.tsx:98]: Nah, this is not correct. This is not solved the issue. The correct week start value is saved in the database, but there is a problem in the frontend

**Review by anikdhabal — CHANGES_REQUESTED** [review]

**Review by anikdhabal — APPROVED** [review]
Fixed it
LGTM!

File: packages/features/ee/users/components/UserForm.tsx (hunk 1 above)
Comment (ymohit1603) [reply packages/features/ee/users/components/UserForm.tsx]: Hey ,Are there any docs for how the code is written or i have to figure out on my own ?  I am new to this repo.
