### PR TITLE
fix: all booking and duration limits

### LINKED ISSUE #10361: [CAL-2237] "Limit booking frequency" setting doesn't work
### Issue Summary

I have a [Cal.com](http://Cal.com) event at [this link](https://cal.com/quanx/boba). In this event's settings > "Limits" > "Limit booking frequency", I added a rule of 1 per week. After I've set this rule, people could still book > 1 per week: evidently, I already have 1 booking this week and another next week, yet my public event page still allows people to book during these weeks.

### Steps to Reproduce

1. In an event's settings > "Limits" > "Limit booking frequency", add a rule of 1 per week
2. Book a meeting this week for that event
3. Return to the booking page to see that this week is available for more bookings

### Actual Results

* People can still book after I've set a rule of only one event booking per week

### Expected Results

* If this week already has a booking, people should see that this week no longer has any open slots for more booking

### Technical details

* I'm using Chrome / Arc browsers
* Confirmed that this setting has been saved and was set for several days now

### Evidence

CleanShot 070349@2x

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2237](https://linear.app/calcom/issue/CAL-2237/limit-booking-frequency-setting-doesnt-work)</sub>

### PR DESCRIPTION
**Pull request by nicktrn**
## What does this PR do?

Fixes #10361 :pray: 

This builds on #10435 to also fix the following issues:
- yearly duration limits
- yearly booking limits if event booked in multiple years
- yearly limits if the checked date range is in multiple years (31 Dec or 1 Jan in view with diff TZ)
- performance: re-checking of known busy periods
- some unexpected type issues

Further performance improvements are possible if required. The groundwork is already there.

Current unit and e2e tests are happy so hopefully I didn't break anything. New e2e tests in #10518 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)

### Yearly Duration Limits

1. Set yearly duration limit
2. Make some bookings
3. Issue: year NOT busy
4. Fix: year busy

### Yearly Booking Limits

1. Set yearly booking limit to `1`
2. Make one booking this year
3. See that the whole year is now busy
5. Make one booking next year
6. Issue: BOTH years are now available for bookings
7. Fix: both years busy

### Multiple Years

Can currently not be tested as there seems to be a separate bug hiding these slots from view. Set availability to 24h for all days, then check start/end of month (or year). When TZ differs, the slots that cross into the host's next month (or year) will not be shown.

### Misc

All duration and booking limits should be tested extensively. None of them were working that well beforehand. New E2E tests just for limits in #10518 

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

~- I haven't added tests that prove my fix is effective or that my feature works~

### CODE REVIEW

File: packages/core/getBusyTimes.ts [hunk 1]
```diff
@@ -210,4 +210,63 @@ export async function getBusyTimes(params: {
   return busyTimes;
 }
 
+export async function getBusyTimesForLimitChecks(params: {
+  userId: number;
+  eventTypeId: number;
+  startDate: Date;
+  endDate: Date;
+}) {
```
Comment (nicktrn) [inline packages/core/getBusyTimes.ts:218]: This allows us to only fetch the absolute minimum info required to check limits

File: packages/core/getBusyTimes.ts [hunk 2]
```diff
@@ -210,4 +210,63 @@ export async function getBusyTimes(params: {
...
+      eventTypeId,
+      status: BookingStatus.ACCEPTED,
+      // FIXME: bookings that overlap on one side will never be counted
+      startTime: {
+        gte: startDate,
+      },
+      endTime: {
+        lte: endDate,
+      },
+    },
```
Comment (nicktrn) [inline packages/core/getBusyTimes.ts:241]: Should probably get all bookings that start in that period, not also end. Need some input here.

File: packages/core/getUserAvailability.ts [hunk 3]
```diff
@@ -158,17 +164,36 @@ export async function getUserAvailability(
...
+  const getBusyTimesStart = dateFrom.toISOString();
+  const getBusyTimesEnd = dateTo.toISOString();
+
   const busyTimes = await getBusyTimes({
     credentials: user.credentials,
-    // needed to correctly apply limits (weeks can be part of two months)
-    startTime: dateFrom.startOf("week").toISOString(),
-    endTime: dateTo.endOf("week").toISOString(),
+    startTime: getBusyTimesStart,
+    endTime: getBusyTimesEnd,
```
Comment (nicktrn) [inline packages/core/getUserAvailability.ts:196]: No longer required as we get the booking info to apply limits separately now

File: packages/core/getUserAvailability.ts [hunk 4]
```diff
@@ -257,22 +258,22 @@ export async function getUserAvailability(
...
     dateRanges: subtract(dateRanges, formattedBusyTimes),
     workingHours,
     dateOverrides,
     currentSeats,
   };
-}
+};
 
-const getDatesBetween = (dateFrom: Dayjs, dateTo: Dayjs, period: "day" | "week" | "month" | "year") => {
+const getPeriodStartDatesBetween = (dateFrom: Dayjs, dateTo: Dayjs, period: IntervalLimitUnit) => {
```
Comment (nicktrn) [inline packages/core/getUserAvailability.ts:276]: Created new type as this is used in a lot of places

File: packages/core/getUserAvailability.ts [hunk 5]
```diff
@@ -283,65 +284,198 @@ const getDatesBetween = (dateFrom: Dayjs, dateTo: Dayjs, period: "day" | "week"
...
+          eventId: eventTypeId,
+          key,
+          returnBusyTimes: true,
+        });
+        if (yearlyBusyTime) {
+          limitManager.addBusyTime(periodStart, unit);
+          if (periodStartDates.every((start) => limitManager.isAlreadyBusy(start, unit))) {
+            return;
+          }
+        }
```
Comment (nicktrn) [inline packages/core/getUserAvailability.ts:459]: Previously, if any year was marked as busy, we would skip all other limits, even if there was an additional year to check.

File: packages/dayjs/index.ts [hunk 6]
```diff
@@ -10,6 +10,7 @@ import relativeTime from "dayjs/plugin/relativeTime";
 import timeZone from "dayjs/plugin/timezone";
 import toArray from "dayjs/plugin/toArray";
 import utc from "dayjs/plugin/utc";
+import weekOfYear from "dayjs/plugin/weekOfYear";
```
Comment (nicktrn) [inline packages/dayjs/index.ts:13]: Greatly simplifies checking for already blocked weeks

File: packages/lib/server/checkBookingLimits.ts [hunk 7]
```diff
@@ -12,23 +15,22 @@ export async function checkBookingLimits(
...
-      async ([key, limitingNumber]) =>
-        await checkBookingLimit({ key, limitingNumber, eventStartDate, eventId, returnBusyTimes })
+  if (!parsedBookingLimits) return false;
+
+  // convoluted but typesafe
+  const limitCalculations = ascendingLimitKeys
+    .filter((key) => parsedBookingLimits[key])
+    .map((key) =>
+      checkBookingLimit({ key, limitingNumber: parsedBookingLimits[key], eventStartDate, eventId })
     );
```
Comment (nicktrn) [inline packages/lib/server/checkBookingLimits.ts:25]: Correct types were previously not preserved and there was an issue further down the chain with this. The `entries()` helper would have prevented using a simple map function here.

File: packages/lib/server/checkBookingLimits.ts [hunk 8]
```diff
@@ -40,55 +42,45 @@ export async function checkBookingLimit({
...
+        // FIXME: bookings that overlap on one side will never be counted
+        startTime: {
+          gte: startDate,
+        },
+        endTime: {
+          lte: endDate,
         },
       },
     });
-    if (bookingsInPeriod >= limitingNumber) {
```
Comment (nicktrn) [inline packages/lib/server/checkBookingLimits.ts:79]: This used to hide that limitingNumber could sometimes be `undefined`, as greater and lesser than always evaluate to false in that case

File: packages/lib/server/checkBookingLimits.ts [hunk 9]
```diff
@@ -40,55 +42,45 @@ export async function checkBookingLimit({
...
-            {
-              id: eventId,
-              bookings: {
-                every: {
-                  startTime: {
-                    gte: startDate,
-                  },
-                  endTime: {
-                    lte: endDate,
-                  },
```
Comment (nicktrn) [inline packages/lib/server/checkBookingLimits.ts:71]: This is a strange recursion that would not count bookings if not ALL bookings for that event were in the same period

File: packages/lib/server/checkDurationLimits.ts [hunk 10]
```diff
@@ -36,30 +38,33 @@ export async function checkDurationLimit({
 }: {
   eventStartDate: Date;
   eventId: number;
-  key: string;
-  limitingNumber: number;
+  key: keyof IntervalLimit;
+  limitingNumber: number | undefined;
```
Comment (nicktrn) [inline packages/lib/server/checkDurationLimits.ts:42]: type safety

File: packages/lib/server/queries/booking/index.ts [hunk 11]
```diff
@@ -10,11 +10,12 @@ export const getTotalBookingDuration = async ({
...
   // Aggregates the total booking time for a given event in a given time period
+  // FIXME: bookings that overlap on one side will never be counted
   const [totalBookingTime] = (await prisma.$queryRaw`
     SELECT SUM(EXTRACT(EPOCH FROM ("endTime" - "startTime")) / 60) as "totalMinutes"
     FROM "Booking"
     WHERE "status" = 'accepted'
-      AND "id" = ${eventId}
+      AND "eventTypeId" = ${eventId}
       AND "startTime" >= ${startDate}
       AND "endTime" <= ${endDate};
```
Comment (nicktrn) [inline packages/lib/server/queries/booking/index.ts:20]: Using the wrong key caused this to return `0` most of the time, and a random booking duration at best. Need some input here re counting overlapping bookings, e.g. starts in one week and ends in the next. Currently, those bookings are never considered when checking weekly limits. Same naturally applies to other periods.

**Review by nicktrn — COMMENTED** [review]
Ready for review and suggestions!

File: packages/lib/server/checkDurationLimits.ts [hunk 12]
```diff
@@ -11,55 +13,46 @@ export async function checkDurationLimits(
...
+    const endDate = dayjs(eventStartDate).endOf(unit).toDate();
 
     const totalBookingDuration = await getTotalBookingDuration({ eventId, startDate, endDate });
-    if (totalBookingDuration >= limitingNumber) {
-      // This is used when getting availability
-      if (returnBusyTimes) {
-        return {
-          start: startDate,
-          end: endDate,
-        };
```
Comment (nicktrn) [inline packages/lib/server/checkDurationLimits.ts:56]: now unused, caller already has this

File: packages/lib/server/checkDurationLimits.ts [hunk 13]
```diff
@@ -11,55 +13,46 @@ export async function checkDurationLimits(
...
-  }
+  if (!parsedDurationLimits) return false;
 
-  const limitCalculations = Object.entries(parsedDurationLimits).map(
-    async ([key, limitingNumber]) =>
-      await checkDurationLimit({ key, limitingNumber, eventStartDate, eventId })
+  // not iterating entries to preserve types
+  const limitCalculations = ascendingLimitKeys.map((key) =>
+    checkDurationLimit({ key, limitingNumber: parsedDurationLimits[key], eventStartDate, eventId })
   );
```
Comment (nicktrn) [inline packages/lib/server/checkDurationLimits.ts:21]: not preserving types caused a hidden `undefined` comparison in the callee

File: packages/lib/server/queries/booking/index.ts [hunk 14]
```diff
@@ -10,14 +10,15 @@ export const getTotalBookingDuration = async ({
   endDate: Date;
 }) => {
   // Aggregates the total booking time for a given event in a given time period
-  const [totalBookingTime] = (await prisma.$queryRaw`
+  // FIXME: bookings that overlap on one side will never be counted
+  const [totalBookingTime] = await prisma.$queryRaw<[{ totalMinutes: number | null }]>`
```
Comment (nicktrn) [inline packages/lib/server/queries/booking/index.ts:14]: previous type assertion missed this could be `null` which caused issues when comparing to numbers

File: packages/types/Calendar.d.ts [hunk 15]
```diff
@@ -120,12 +120,9 @@ export interface RecurringEvent {
...
 
-export interface IntervalLimit {
-  PER_DAY?: number | undefined;
-  PER_WEEK?: number | undefined;
-  PER_MONTH?: number | undefined;
-  PER_YEAR?: number | undefined;
-}
+export type IntervalLimitUnit = "day" | "week" | "month" | "year";
+
+export type IntervalLimit = Partial<Record<`PER_${Uppercase<IntervalLimitUnit>}`, number | undefined>>;
```
Comment (nicktrn) [inline packages/types/Calendar.d.ts:125]: abstracted limit units as they were repeatedly asserted in many different places

**Review by nicktrn — COMMENTED** [review]
Added some more comments for the recent push

**Comment by nicktrn** [comment]
@emrysal @CarinaWolli hope it's okay to ping you here as this builds on #10435 and probably easier to review together. E2E tests are WIP #10518

Quick recap:
- weekly limit issues were fixed by extending the date range of bookings we fetch #10404 
- monthly limit issues were pointed out for dates in the past, but simply extending the date range further would have been quite bad for performance
- looked into yearly limits and found more issues

File: apps/web/test/lib/checkBookingLimits.test.ts [hunk 16]
```diff
@@ -81,21 +81,6 @@ describe("Check Booking Limits Tests", () => {
       })
     ).rejects.toThrowError();
   });
-  it("Should return busyTimes when set", async () => {
```
Comment (nicktrn) [inline apps/web/test/lib/checkBookingLimits.test.ts:84]: no need to return busyTimes anymore after refactor

File: apps/web/test/lib/checkDurationLimits.test.ts [hunk 17]
```diff
@@ -97,21 +97,6 @@ describe("Check Duration Limit Tests", () => {
       })
     ).resolves.toBeUndefined();
   });
-  it("Should return busyTimes when set and limit is reached", async () => {
```
Comment (nicktrn) [inline apps/web/test/lib/checkDurationLimits.test.ts:100]: no need to return busyTimes anymore after refactor

File: packages/lib/server/checkBookingLimits.ts [hunk 18]
```diff
@@ -1,94 +1,71 @@
...
+import { getErrorFromUnknown } from "../errors";
 import { HttpError } from "../http-error";
+import { ascendingLimitKeys, intervalLimitKeyToUnit } from "../intervalLimit";
 import { parseBookingLimit } from "../isBookingLimits";
 
 export async function checkBookingLimits(
   bookingLimits: IntervalLimit,
   eventStartDate: Date,
-  eventId: number,
-  returnBusyTimes?: boolean
```
Comment (nicktrn) [inline packages/lib/server/checkBookingLimits.ts:12]: not needed anymore

File: packages/lib/server/checkBookingLimits.ts [hunk 19]
```diff
@@ -1,94 +1,71 @@
...
+  const limitCalculations = ascendingLimitKeys.map((key) =>
+    checkBookingLimit({ key, limitingNumber: parsedBookingLimits[key], eventStartDate, eventId })
+  );
+
+  try {
+    return !!(await Promise.all(limitCalculations));
+  } catch (error) {
+    throw new HttpError({ message: getErrorFromUnknown(error).message, statusCode: 401 });
   }
-  return false;
```
Comment (nicktrn) [inline packages/lib/server/checkBookingLimits.ts:31]: refactor, same behaviour except removal of busyTimes, added type safety

File: packages/lib/server/checkBookingLimits.ts [hunk 20]
```diff
@@ -1,94 +1,71 @@
...
   limitingNumber,
-  returnBusyTimes = false,
 }: {
   eventStartDate: Date;
   eventId: number;
-  key: string;
-  limitingNumber: number;
-  returnBusyTimes?: boolean;
+  key: keyof IntervalLimit;
+  limitingNumber: number | undefined;
```
Comment (nicktrn) [inline packages/lib/server/checkBookingLimits.ts:40]: type safety

File: packages/lib/server/checkBookingLimits.ts [hunk 21]
```diff
@@ -1,94 +1,71 @@
...
       },
     });
-    if (bookingsInPeriod >= limitingNumber) {
-      // This is used when getting availability
-      if (returnBusyTimes) {
-        return {
-          start: startDate,
-          end: endDate,
-        };
-      }
```
Comment (nicktrn) [inline packages/lib/server/checkBookingLimits.ts:86]: Now unused, as we already have that data when checking availability for specific periods

File: packages/lib/server/queries/booking/index.ts [hunk 22]
```diff
@@ -10,14 +10,15 @@ export const getTotalBookingDuration = async ({
...
     SELECT SUM(EXTRACT(EPOCH FROM ("endTime" - "startTime")) / 60) as "totalMinutes"
     FROM "Booking"
     WHERE "status" = 'accepted'
-      AND "id" = ${eventId}
+      AND "eventTypeId" = ${eventId}
```
Comment (nicktrn) [inline packages/lib/server/queries/booking/index.ts:18]: mixup between booking and event id, caused booking limits to not be enforced here and lead to unnecessary calls to getUserAvailability where those limits were checked again

**Review by zomars — COMMENTED** [review]
Impressive work so far @nicktrn 🙏🏽 I love myself a good refactor. Will test locally and get back to you.

**Comment by nicktrn** [comment]
This is what happens when the surgical approach fails. Apologies if the gutting was too extensive. Feel free to keep the knife if you find one in there!

File: apps/web/components/eventtype/EventLimitsTab.tsx [hunk 23]
```diff
@@ -477,11 +478,9 @@ export const EventLimitsTab = ({ eventType }: Pick<EventTypeSetupProps, "eventTy
 
 type IntervalLimitsKey = keyof IntervalLimit;
 
-const intervalOrderKeys = ["PER_DAY", "PER_WEEK", "PER_MONTH", "PER_YEAR"] as const;
-
-const INTERVAL_LIMIT_OPTIONS = intervalOrderKeys.map((key) => ({
+const INTERVAL_LIMIT_OPTIONS = ascendingLimitKeys.map((key) => ({
   value: key as keyof IntervalLimit,
-  label: `Per ${key.split("_")[1].toLocaleLowerCase()}`,
+  label: `Per ${intervalLimitKeyToUnit(key)}`,
```
[the remark this answers is not in the document]
Comment (alannnc) [reply apps/web/components/eventtype/EventLimitsTab.tsx:482]: Can we avoid transformation here and just use plain array with ["day", "week", "month", "year"]? Or there is a reason for this?

**Review by zomars — APPROVED** [review]
Loving the refactor so far. My only concern are the possible git conflicts for other PRs. Not a blocker on my side. Thank you for your contribution 🙏

File: apps/web/components/eventtype/EventLimitsTab.tsx (hunk 23 above)
[the remark this answers is not in the document]
Comment (nicktrn) [reply apps/web/components/eventtype/EventLimitsTab.tsx:482]: Sure, just thought it might be easier to extend in the future, e. g. adding "quarter". Looking back should probably localise those strings.

**Comment by nicktrn** [comment]
Wow, that was quick! I was getting concerned with merges too, glad it was spotted.

File: apps/web/components/eventtype/EventLimitsTab.tsx (hunk 23 above)
[the remark this answers is not in the document]
Comment (alannnc) [reply apps/web/components/eventtype/EventLimitsTab.tsx:482]: We should be good with plains on low number options.

File: packages/core/getBusyTimes.ts [hunk 24]
```diff
@@ -207,4 +207,63 @@ export async function getBusyTimes(params: {
...
+    select: {
+      id: true,
+      startTime: true,
+      endTime: true,
+      eventType: {
```
Comment (emrysal) [inline packages/core/getBusyTimes.ts:243]: I believe what you can do as well is `eventTypeId: true` - for future reference

File: packages/core/getUserAvailability.ts [hunk 25]
```diff
@@ -105,7 +111,7 @@ export const getCurrentSeats = (eventTypeId: number, dateFrom: Dayjs, dateTo: Da
 export type CurrentSeats = Awaited<ReturnType<typeof getCurrentSeats>>;
 
 /** This should be called getUsersWorkingHoursAndBusySlots (...and remaining seats, and final timezone) */
-export async function getUserAvailability(
+export const getUserAvailability = async function getUsersWorkingHoursLifeTheUniverseAndEverythingElse(
```
Comment (emrysal) [inline packages/core/getUserAvailability.ts:114]: welp this got merged 😆

File: packages/core/getUserAvailability.ts [hunk 26]
```diff
@@ -141,17 +147,36 @@ export async function getUserAvailability(
...
+      : [];
+
+  // TODO: only query what we need after applying limits (shrink date range)
+  const getBusyTimesStart = dateFrom.toISOString();
+  const getBusyTimesEnd = dateTo.toISOString();
+
   const busyTimes = await getBusyTimes({
     credentials: user.credentials,
-    // needed to correctly apply limits (weeks can be part of two months)
-    startTime: dateFrom.startOf("week").toISOString(),
```
Comment (emrysal) [inline packages/core/getUserAvailability.ts:153]: 🙌  - disliked this very much

File: packages/core/getBusyTimes.ts (hunk 2 above)
Comment (emrysal) [reply packages/core/getBusyTimes.ts:238]: True, an event end time typically does not matter unless it's greater than startDate - this probably makes the most sense.

```suggestion
  const bookings = await prisma.booking.findMany({
    where: {
      userId,
      eventTypeId,
      status: BookingStatus.ACCEPTED,
      // FIXME: bookings that overlap on one side will never be counted
      startTime: {
        gte: startDate,
      },
      endTime: {
        gte: startDate,
      },
    },
```

File: packages/lib/server/checkBookingLimits.ts [hunk 27]
```diff
@@ -1,94 +1,71 @@
...
+
+  // not iterating entries to preserve types
+  const limitCalculations = ascendingLimitKeys.map((key) =>
+    checkBookingLimit({ key, limitingNumber: parsedBookingLimits[key], eventStartDate, eventId })
+  );
+
+  try {
+    return !!(await Promise.all(limitCalculations));
+  } catch (error) {
+    throw new HttpError({ message: getErrorFromUnknown(error).message, statusCode: 401 });
```
Comment (emrysal) [inline packages/lib/server/checkBookingLimits.ts:27]: 401 Unauthorized?

**Comment by emrysal** [comment]
Amazing work done here! 👍

**Comment by nicktrn** [comment]
Thanks to everyone for the thorough review, this really helps!

**Comment by PeerRich** [comment]
/tip 50 thank you for this awesome PR!
