### PR TITLE
Fixing app details disconnect button and number of apps

### LINKED ISSUE #3567: installed apps page slow
@leog you were looking into this? any ideas why?

### LINKED ISSUE #4255: /apps/app-store - App card actions are mis-aligned
@leog not sure if this is a known issue or not so adding in case!

Image

### LINKED ISSUE #4257: "Remove" button in app store when app is already installed
- right now we throw a toast "App already installed" 
- we should show the "Remove" button when app is already installed (vs showing another "Install" Button that doesn't work)

CleanShot 2022-09-07 at 21 20 59@2x

like in installed apps:
CleanShot 2022-09-07 at 21 21 43@2x

### LINKED ISSUE #4269: amount of apps is wrong
- there is 1 web3 app in the filter:
CleanShot 2022-09-08 at 11 16 05@2x
- 3 in the category card
CleanShot 2022-09-08 at 11 16 37@2x
- and 2 in the category page https://app.cal.com/apps/categories/web3
CleanShot 2022-09-08 at 11 16 51@2x

### LINKED ISSUE #4416: /app-store - 2 small ui changes
- [ ] border on cards to `border-gray-200` so they don't appear above buttons
- [ ] reduce title size to `text-base`

https://user-images.githubusercontent.com/4536123/189813768-da73adc3-2542-4939-a4d8-e17dafb3751c.mp4

### PR DESCRIPTION
**Pull request by leog**
## What does this PR do?

Trying to fix #4269 and #4257

**Environment**: Staging(main branch) / Production

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

Go to an installed app details page and see the Disconnect button to remove it. Also, trying to fix number of apps in categories in v2 where it should show more apps under certain categories.

### CODE REVIEW

**Comment by zlwaterfield** [comment]
Tried locally, and I'm not seeing the installed button at all on the app detail page. I do not have this app installed. I do see the button on `main`. 
Screen Shot 2022-09-09 at 9 52 25 AM

File: apps/web/components/App.tsx [hunk 1]
```diff
@@ -66,7 +77,7 @@ const Component = ({
         });
         if (result.status === 200) {
           const res = await result.json();
-          setInstalledAppCount(res.count);
+          setExistingCredentials(res.credentials);
```
Comment (leog) [inline apps/web/components/App.tsx:80]: We now return credentials, not just the count, in order to pass down the credential ID to the DIsconnect button.

File: apps/web/pages/v2/apps/index.tsx [hunk 2]
```diff
@@ -32,11 +32,9 @@ export const getServerSideProps = async (context: NextPageContext) => {
     appStore = await getAppRegistry();
   }
 
-  const categoryQuery = await prisma.app.findMany({
-    select: {
-      categories: true,
-    },
-  });
```
Comment (leog) [inline apps/web/pages/v2/apps/index.tsx:39]: Removed getting all categories from the database in favor of filtering down the categories existent in the available apps returned by the App Registry.

File: apps/web/playwright/app-store.e2e.ts [hunk 3]
```diff
@@ -23,6 +24,7 @@ test.describe("App Store - Unauthed", () => {
     await page.waitForSelector("[data-testid=dashboard-shell]");
     await page.click('[data-testid="app-store-category-calendar"]');
     await page.click('[data-testid="app-store-app-card-apple-calendar"]');
+    await page.waitForResponse((resp) => resp.url().includes("/api/apps") && resp.status() === 200);
```
Comment (leog) [inline apps/web/playwright/app-store.e2e.ts:27]: Same as before.

File: packages/ui/v2/core/apps/AllApps.tsx [hunk 4]
```diff
@@ -86,8 +86,8 @@ export default function AllApps({ apps }: AllAppsPropsType) {
               router.replace(router.asPath.split("?")[0], undefined, { shallow: true });
             }}
             className={classNames(
-              selectedCategory === null ? "bg-gray-200" : "bg-gray-50",
-              "rounded-md px-4 py-2.5 text-sm font-medium text-gray-900 hover:cursor-pointer hover:bg-gray-200"
+              selectedCategory === null ? "bg-gray-900 text-gray-50" : "bg-gray-50 text-gray-900",
+              "rounded-md px-4 py-2.5 text-sm font-medium hover:cursor-pointer hover:bg-gray-900 hover:text-gray-50"
```
Comment (leog) [inline packages/ui/v2/core/apps/AllApps.tsx:90]: Some tweaks to the categories strip in the App Store, to have a black background on selected or hover.

File: packages/ui/v2/core/apps/AllApps.tsx [hunk 5]
```diff
@@ -104,8 +104,8 @@ export default function AllApps({ apps }: AllAppsPropsType) {
                 }
               }}
               className={classNames(
-                selectedCategory === cat ? "bg-gray-200" : "bg-gray-50",
-                "rounded-md px-4 py-2.5 text-sm font-medium text-gray-900 hover:cursor-pointer hover:bg-gray-200"
+                selectedCategory === cat ? "bg-gray-900 text-gray-50" : "bg-gray-50 text-gray-900",
```
Comment (leog) [inline packages/ui/v2/core/apps/AllApps.tsx:107]: Same as before.

File: packages/ui/v2/core/apps/AllApps.tsx [hunk 6]
```diff
@@ -122,7 +122,13 @@ export default function AllApps({ apps }: AllAppsPropsType) {
       </div>
       <div className="grid grid-cols-2 gap-3 md:grid-cols-4" ref={appsContainerRef}>
         {apps
-          .filter((app) => (selectedCategory !== null ? app.category === selectedCategory : true))
+          .filter((app) =>
+            selectedCategory !== null
+              ? app.categories
+                ? app.categories.includes(selectedCategory)
+                : app.category === selectedCategory
```
Comment (leog) [inline packages/ui/v2/core/apps/AllApps.tsx:129]: Just in case there are apps with `category` and not a list of `categories`. But the main issue regarding app count not correct was fixed by filtering existent apps from app registry, not taking into consideration all categories in the database.

File: packages/ui/v2/modules/integrations/DisconnectIntegration.tsx [hunk 7]
```diff
@@ -12,11 +12,13 @@ export default function DisconnectIntegration({
   label,
   trashIcon,
   isGlobal,
+  onSuccess,
 }: {
   credentialId: number;
   label: string;
   trashIcon?: boolean;
   isGlobal?: boolean;
+  onSuccess?: () => void;
```
Comment (leog) [inline packages/ui/v2/modules/integrations/DisconnectIntegration.tsx:21]: Had to add this because in some cases, the disconnect action should for example, redirect the user somewhere else. See https://github.com/calcom/cal.com/pull/4305/files#diff-ca24dc6387663c3bf0b33e52827cb05585264596d8f9b65b02c56565b403dca2R160

File: apps/web/pages/api/apps/installed.ts [hunk 8]
```diff
@@ -14,24 +14,24 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
 
     const userId = req.session.user.id;
     try {
-      const installedApp = await prisma.credential.findMany({
+      const credentials = await prisma.credential.findMany({
         where: {
           type: appCredentialType as string,
           userId: userId,
         },
       });
```
Comment (zomars) [inline apps/web/pages/api/apps/installed.ts:22]: This is a security risk. We're exposing private credential keys unnecessarily to the frontend.

File: apps/web/components/v2/apps/App.tsx [hunk 9]
```diff
@@ -68,7 +72,7 @@ const Component = ({
         });
         if (result.status === 200) {
           const res = await result.json();
-          setInstalledAppCount(res.count);
+          setExistingCredentials(res.credentials);
```
Comment (zomars) [inline apps/web/components/v2/apps/App.tsx:75]: Lets expose only necessary data

**Review by zomars — CHANGES_REQUESTED** [review]
Adding to my review I would suggest taking this opportunity to convert `/api/apps/installed` to a tRPC query.

**Comment by leog** [comment]
Let's continue review in the main branch, which is why I can merge without explicit approval 😅
