### PR TITLE
fix: use typedquery hook in duplicate dialog

### LINKED ISSUE #6727: [CAL-937] When duplicating event > UI: URL missing username
### Issue Summary

When you duplicate an event, the settings popup is missing the user's name from the address field
image

### Steps to Reproduce

1. Duplicate an existing event
2. In the "Duplicate Event" popup the user's username is not rendered in the UI

### Technical details

- Safari 16.2

<sub>[CAL-937](https://linear.app/calcom/issue/CAL-937/when-duplicating-event-ui-url-missing-username)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes :- 1) Improves duplicate event type dialog.
2) add destructive on delete btn
3) clear pageSlug param when dialog is closed

This issue was already fixed https://github.com/calcom/cal.com/issues/6727 ( not deployed)

https://user-images.githubusercontent.com/53316345/214856211-8de00634-23ca-4d54-b2e6-7e9d6ee94d07.mov

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

File: packages/features/eventtypes/components/DuplicateDialog.tsx [hunk 1]
```diff
@@ -16,18 +18,28 @@ import {
...
+
   // react hook form
   const form = useForm({
     defaultValues: {
-      id: Number(router.query.id as string) || -1,
-      title: (router.query.title as string) || "",
-      slug: t("event_type_duplicate_copy_text", { slug: router.query.slug as string }),
-      description: (router.query.description as string) || "",
-      length: Number(router.query.length) || 30,
+      slug: t("event_type_duplicate_copy_text", { slug: slug }),
```
Comment (zomars) [inline packages/features/eventtypes/components/DuplicateDialog.tsx:41]:
```suggestion
      slug: t("event_type_duplicate_copy_text", { slug }),
```

**Review by zomars — APPROVED** [review]
LGTM
