### PR TITLE
fix: Copy invite link on safari

### LINKED ISSUE #12801: [CAL-2810] Copy Invite link not working on safari
Copying doesn't show an error on Ui but there is an error in console.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2810](https://linear.app/calcom/issue/CAL-2810/copy-invite-link-not-working-on-safari)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #12801
Gets Copy Invite Link working on Safari

[Demo ](https://www.loom.com/share/e62273425e664494a9bc0371fe3f7dad)

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
- Go to members page
- Click on Add 
- Click on Copy Invite Link

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by hariombalhara** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #12873** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/12873?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/calcom/cal.com/12873?utm_source=stack-comment).

File: packages/features/ee/teams/components/MemberInvitationModal.tsx [hunk 1]
```diff
@@ -389,8 +379,36 @@ export default function MemberInvitationModal(props: MemberInvitationModalProps)
...
-                    createInviteMutation.mutate({ teamId: props.teamId, token: props.token });
+                  onClick={async function () {
+                    try {
+                      // Required for Safari but also works on Chrome
+                      // Credits to https://wolfgangrittner.dev/how-to-use-clipboard-api-in-firefox/
+                      if (typeof ClipboardItem) {
+                        const inviteLinkClipbardItem = new ClipboardItem({
+                          "text/plain": new Promise(async (resolve) => {
+                            // Instead of doing async work and then writing to clipboard, do async work in clipboard API itself
+                            const { inviteLink } = await createInviteMutation.mutateAsync({
```
Comment (hariombalhara) [inline packages/features/ee/teams/components/MemberInvitationModal.tsx:390]: Spent quite some time figuring out two promises to work together with closures going on. In the end discovered that there is mutateAsync to make it simpler 😅

**Review by emrysal — APPROVED** [review]
Very cool! Nice getting this sorted
