### PR TITLE
Fix/conflicts of custom input Name, with system field

### LINKED ISSUE #7737: [CAL-1264] Booking Questions - Unable to remove duplicates
### Issue Summary

In the past, a location boolean was added to the fields that were added as a booking question. As the user wanted to add a question for the user to enter the actual address they created a new field with the same name (location). Now the location questions are not able to be modified or removed. 

### Steps to Reproduce

1. Navigate to a Booking
2. Select the Advanced option from the left navigation
3. Scroll to the Booking Questions section
4. I currently have 2 questions that are labeled location (You may not as this was added before some of the newer functions that now allow you to create more custom question fields).
5. If you change anything within the booking it displays an error toast "BAD_REQUEST: Duplicate booking field name: location"
6. Unfortunately I am not able to edit, remove, or disable either of the duplicated fields. 

This is demonstrated in the video here:
https://share.icloud.com/photos/042ja6dgV9x3JI8qOMmwYK36Q

Safari Version 16.3 (18614.4.6.1.6)

<sub>[CAL-1264](https://linear.app/calcom/issue/CAL-1264/booking-questions-unable-to-remove-duplicates)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #7737

**Environment**: Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [x] Create a new EventType and change eventType.`customInputs` in DB torefer to customInputs table rows like this
Screenshot 2023-03-21 at 3 18 42 PM
Go to Advanced section and try saving the EventType. You won't be able to save it. If you would try to edit the custom field name, you won't be able to. With this branch, you would be able to change custom fields' names even if they are same as system fields' names
- [x] Check that the fields with same name as system fields are deletable but system fields are not deletable.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/features/bookings/lib/getBookingFields.ts [hunk 1]
```diff
@@ -338,17 +334,5 @@ export const ensureBookingInputsHaveSystemFields = ({
 
   bookingFields = bookingFields.concat(missingSystemAfterFields);
 
-  bookingFields = bookingFields.map((field) => {
```
Comment (hariombalhara) [inline packages/features/bookings/lib/getBookingFields.ts:341]: This was a futuristic code to ensure that system fields can never change their `editable` property because they are essential for the system.

But relying on the name, causes this problem where a custom field with same name as system field when migrates to Bookign Questions, automatically get's marked as a system field because the name is same as System field.

So, remove that futuristic code so that user fields with same name as system fields can be editable.

File: packages/features/bookings/lib/getBookingFields.ts [hunk 2]
```diff
@@ -55,16 +55,6 @@ export const SystemField = z.enum([
   "smsReminderNumber",
 ]);
 
-export const SystemFieldsEditability: Record<z.infer<typeof SystemField>, Fields[number]["editable"]> = {
-  name: "system",
```
Comment (hariombalhara) [inline packages/features/bookings/lib/getBookingFields.ts:59]: These are now moved to individual fields.

File: packages/features/bookings/lib/getBookingFields.ts [hunk 3]
```diff
@@ -55,16 +55,6 @@ export const SystemField = z.enum([
...
-  email: "system",
-  location: "system",
-  notes: "system-but-optional",
-  guests: "system-but-optional",
-  rescheduleReason: "system-but-optional",
-  smsReminderNumber: "system",
```
Comment (hariombalhara) [inline packages/features/bookings/lib/getBookingFields.ts:65]: `smsReminderNumber` field already has editable prop correctly set.
Screenshot 2023-03-21 at 3 27 39 PM

**Review by emrysal — APPROVED** [review]
Looks good to me
