### PR TITLE
fix: to allow paypal install on team when user already installed

### LINKED ISSUE #16549: [CAL-4287] Users cannot add paypal app to a team if they have a paypal app installed
packages/app-store/paypal/api/add.ts

as soon as you install paypal app on your personal account (attached to your userID) controller will not let you add paypal app to one of your team

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4287](https://linear.app/calcom/issue/CAL-4287/users-cannot-add-paypal-app-to-a-team-if-they-have-a-paypal-app)</sub>

### PR DESCRIPTION
**Pull request by vijayraghav-io**
## What does this PR do?

- Fixes #16549 
- Fixes CAL-4287

**Before Fix:**
https://www.loom.com/share/c802aa572f084e14b910aa802adfb6f2?sid=8ed16c89-5180-4d1c-a247-64214967d6ba

**After Fix:**
https://www.loom.com/share/9689aef195504761b3ba37b83dc1ac90?sid=e8133e4c-b392-44a7-853e-789cf3ab709b

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

File: packages/app-store/paypal/api/add.ts [hunk 1]
```diff
@@ -9,12 +9,18 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
...
   }
   const appType = config.type;
+  const teamId =
+    req.query?.teamId && typeof req.query?.teamId === "string"
+      ? parseInt(req.query?.teamId as string)
+      : undefined;
+  const whereClause =
+    teamId !== undefined && !Number.isNaN(teamId)
+      ? { type: appType, teamId }
+      : { type: appType, userId: req.session.user.id };
```
Comment (anikdhabal) [inline packages/app-store/paypal/api/add.ts:19]: You can simply it more. Also, we need to check if the user has admin access to team or not.

**Review by anikdhabal — CHANGES_REQUESTED** [review]

**Review by anikdhabal — APPROVED** [review]
LGTM!
