### PR TITLE
fix: re-render on insights with orgs

### LINKED ISSUE #11352: [CAL-2466] Insights re renders and loads every endpoint again, possible bug with state changing when it shouldn't
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2466](https://linear.app/calcom/issue/CAL-2466/insights-re-renders-and-loads-every-endpoint-again-possible-bug-with)</sub>

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

- When in an org we first loaded user insights data and then when obtaining org details we refetched insights and changed select values. Now we wait to load any insights till we know if user has or not org. So we only see one fetching.
- Removes double heading on insights introduced earlier.

Fixes #11352 

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: apps/web/pages/insights/index.tsx [hunk 1]
```diff
@@ -20,19 +20,6 @@ import { RefreshCcw, UserPlus, Users } from "@calcom/ui/components/icon";
...
-  const { t } = useLocale();
-
-  return (
-    <div className="min-w-52 hidden md:block">
-      <h3 className="font-cal max-w-28 sm:max-w-72 md:max-w-80 text-emphasis truncate text-xl font-semibold tracking-wide xl:max-w-full">
-        {t("insights")}
-      </h3>
-      <p className="text-default mt-2 hidden text-sm md:block">{t("insights_subtitle")}</p>
-    </div>
-  );
```
Comment (alannnc) [inline apps/web/pages/insights/index.tsx:33]: Removed since a change in shell that has the same was introduced recently by a contributor.

File: packages/features/insights/components/AverageEventDurationChart.tsx [hunk 2]
```diff
@@ -12,10 +12,10 @@ import { LoadingInsight } from "./LoadingInsights";
 export const AverageEventDurationChart = () => {
   const { t } = useLocale();
   const { filter } = useFilterContext();
-  const { dateRange, selectedMemberUserId, isAll } = filter;
+  const { dateRange, selectedMemberUserId, isAll, initialConfig } = filter;
   const [startDate, endDate] = dateRange;
   const { selectedTeamId: teamId, selectedUserId } = filter;
-
+  const initialConfigIsReady = !!(initialConfig?.teamId || initialConfig?.userId || initialConfig?.isAll);
```
Comment (alannnc) [inline packages/features/insights/components/AverageEventDurationChart.tsx:18]: Don't load any trpc till we know if user belongs to an org/team

File: packages/features/insights/filters/TeamAndSelfList.tsx [hunk 3]
```diff
@@ -25,6 +25,12 @@ export const TeamAndSelfList = () => {
   });
 
   useEffect(() => {
+    const isInitialSetupAlready = !!(
+      filter.initialConfig?.teamId ||
+      filter.initialConfig?.userId ||
+      filter.initialConfig?.isAll
+    );
+    if (isInitialSetupAlready) return;
```
Comment (alannnc) [inline packages/features/insights/filters/TeamAndSelfList.tsx:33]: Only setup initialConfig once.

**Review by zomars — APPROVED** [review]
LGTM
