### PR TITLE
fix: prevent linking duplicate apple calendars

### LINKED ISSUE #16482: [CAL-4256] Fix logic to add multiple calendars for Apple calendar
At the moment while adding a new apple calendar we don't check for existing apple calendars with the same calendar credentials, which results in multiple credentials being created for the same calendar if someone tries to add the same calendar multiple times. 

<h1>Steps to reproduce</h1>
1. Go to apple calendar setup - https://app.cal.com/apps/apple-calendar/setup in the web app and try to add a new apple calendar with your apple id and the generated app specific password. 
<br />
2. If you add the same id and password again and again you'll be able to see something like this 

https://www.loom.com/share/98d4a78a653b42f481b225e1c9889d80?sid=beecaf69-6956-4006-b3f5-c9009f3422df

<h1>Possible solution</h1>
The approach that I've used to resolve this for v2 api which can be referenced through #16478 is as follows:
<br />
<br />
1. Fetch the  users existing apple calendar credentials from the db based on the userId and type APPLE_CALENDAR_TYPE
<br />
2. If there are existing credentials, use array.filter to map through each credential and decrypt the credential key. That way we get the username and password of that credential.
<br />
3. Match the decrypted key password and username against the password and username that we get in the api request eg. 
decryptedKey.username == username && decryptedKey.password == password;
<br />
4. If the filtered array is not empty that means we already have those credentials present so we just do an early return.
<br />
5. Otherwise we add the calendar using the new CalendarService as expected
<br />
 <br />
If there's a better approach happy to discuss that, otherwise I think this solution should work.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4256](https://linear.app/calcom/issue/CAL-4256/fix-logic-to-add-multiple-calendars-for-apple-calendar)</sub>

### PR DESCRIPTION
**Pull request by Amit91848**
## What does this PR do?

- Fixes #16482 
- Fixes CAL-4256

https://github.com/user-attachments/assets/81cadab8-f434-46b6-ab7c-c62481372061

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by Amit91848** [comment]
> 3. Match the decrypted key password and username against the password and username that we get in the api request eg. decryptedKey.username == username && decryptedKey.password == password;

@Ryukemeister description said both username and password should match the one entered by user, but imo we should also prevent same username with different passwords. Lmk if this needs to be changed

File: packages/app-store/applecalendar/api/add.ts [hunk 1]
```diff
@@ -18,9 +18,22 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
...
       },
     });
 
+    const alreadyExists = user.credentials.find((credential) => {
+      const decryptedCredential = JSON.parse(symmetricDecrypt(credential.key?.toString() || "", process.env.CALENDSO_ENCRYPTION_KEY || ""));
+      return decryptedCredential.username === username;
+    })
+
+
+    if (alreadyExists) return res.status(409).json({ message: "account_already_linked" });
```
Comment (Ryukemeister) [inline packages/app-store/applecalendar/api/add.ts:35]: I would try to do something like 

`if(alreadyExists) && alreadyExists.password === password { return a 409 }`

`if(alreadyExists) && alreadyExists.password !== password { `
` users app specific password expired and so we update it in the credentials table`
`}`

[the remark this answers is not in the document]
Comment (Amit91848) [reply packages/app-store/applecalendar/api/add.ts]: Yes makes much more sense,  made changes

Comment (Amit91848) [reply packages/app-store/applecalendar/api/add.ts]: Implemented

File: packages/app-store/applecalendar/api/add.ts [hunk 2]
```diff
@@ -35,13 +55,17 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
 
     try {
       const dav = new CalendarService({
-        id: 0,
         ...data,
+        id: 0,
```
Comment (Amit91848) [inline packages/app-store/applecalendar/api/add.ts:59]:
```suggestion
        id: 0,
        ...data,
```

File: packages/app-store/applecalendar/api/add.ts [hunk 3]
```diff
@@ -18,9 +18,29 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
...
+          where: {
+            type: "apple_calendar",
+          },
+        },
       },
     });
 
+    let alreadyExistsId = -1;
+
+    for (const credential of user.credentials) {
```
Comment (Ryukemeister) [inline packages/app-store/applecalendar/api/add.ts:31]: @Amit91848 had a question for you, is there any added performance advantage or benefit for using the `for of` loop here instead of your previous approach where you were using `array.find()` before? I found the previous approach which you took much more clean and readable, and I just feel like somewhere in the future if we would want to modify this code, it could get messy real fast and that it might lead to a refactor then. Other than that I have no doubts over the code, LGTM and both the approaches should work as expected so kudos for that!

File: packages/app-store/applecalendar/api/add.ts [hunk 4]
```diff
@@ -18,9 +18,29 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
...
         id: true,
+        credentials: {
+          where: {
+            type: "apple_calendar",
+          },
+        },
       },
     });
 
+    let alreadyExistsId = -1;
```
Comment (Ryukemeister) [inline packages/app-store/applecalendar/api/add.ts:29]: NIT: you can rename this to something like `alreadyExisingCredentialId` or `alreadyExisingCalendarCredentialId`

File: packages/app-store/applecalendar/api/add.ts (hunk 3 above)
Comment (Amit91848) [reply packages/app-store/applecalendar/api/add.ts]: It was just easier to break out of loop when using for. Changed it back to find 👍

**Review by Ryukemeister — APPROVED** [review]
LGTM, haven't tested though!

**Review by keithwillcode — DISMISSED** [review]
Marking requested changes to block on testing by @Ryukemeister

**Comment by Ryukemeister** [comment]
> Marking requested changes to block on testing by @Ryukemeister

Will test this soon!

**Comment by Ryukemeister** [comment]
Tested this and seems to work as expected, great job @Amit91848!
