### PR TITLE
fix: improve redirect parameter handling for success page

### LINKED ISSUE #20469: [CAL-5388] Embed: Success page redirect to a wordpress page breaks that page
Wordpress seems to have a problem with its pages if the page has ***embed*** query param and thus we mustn't forward that.

We forward all the existing query params which is required but we shouldn't forward the **embed** query param (which stores the embed namespace), which is used only in case of embed.

We should also add some kind of test(preferrably unit test) to verify that embed query param isn't forwarded and all other existing params and some special params that we are supposed to forward are being forwarded

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-5388](https://linear.app/calcom/issue/CAL-5388/embed-success-page-redirect-to-a-wordpress-page-breaks-that-page)</sub>

### PR DESCRIPTION
**Pull request by guptadeepak8**
## Summary by mrge
Improved redirect handling by removing the unused "embed" parameter before forwarding users to the success page.

- **Bug Fixes**
  - Filters out the "embed" query parameter to prevent it from appearing on the success page.
  - Added a test to confirm correct parameter filtering.

## What does this PR do?

Improved query parameter handling by removing the unused embed param before forwarding to success page

- Fixes #20469

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by TusharBhatt1 — DISMISSED** [review]
@guptadeepak8 visual demo is important here - can you add , making it draft until then.

**Comment by guptadeepak8** [comment]
previous:-
Screenshot 2025-04-18 144955

changes:-

https://github.com/user-attachments/assets/a56249f2-8b00-4f7b-86e7-f34ea597d7de

File: packages/lib/bookingSuccessRedirect.ts [hunk 1]
```diff
@@ -149,6 +149,13 @@ export const getBookingRedirectExtraParams = (booking: SuccessRedirectBookingTyp
   return queryCompatibleParams;
 };
 
+export const filterEmbedParameter = (params: URLSearchParams) => {
+  // Remove the embed parameter if it exists
+  const filteredParams = new URLSearchParams(params);
+  filteredParams.delete("embed");
+  return filteredParams;
+};
+
```
Comment (anikdhabal) [inline packages/lib/bookingSuccessRedirect.ts:158]: I think there's a specific reason it's there, right?

Comment (retrogtx) [reply packages/lib/bookingSuccessRedirect.ts:158]: So removing it from here will interfere with the booking flow right?

Comment (guptadeepak8) [reply packages/lib/bookingSuccessRedirect.ts:158]: it won't interere the booking flow

File: packages/lib/bookingSuccessRedirect.ts [hunk 2]
```diff
@@ -185,7 +194,7 @@ export const useBookingSuccessRedirect = () => {
           ...query,
           ...bookingExtraParams,
         },
-        searchParams: new URLSearchParams(searchParams.toString()),
+        searchParams: filterEmbedParameter(searchParams, isEmbed),
```
Comment (hariombalhara) [inline packages/lib/bookingSuccessRedirect.ts:197]: Instead of making it embed specific we should handle removing the param in `getBookingRedirectExtraParams` and unit test that function as that function has the responidbility of building what params to send

**Review by hariombalhara — DISMISSED** [review]
@guptadeepak8 Thanks for the PR !! I have left a suggestion to implement it in a better way

**Comment by TusharBhatt1** [comment]
> @guptadeepak8 Thanks for the PR !! I have left a suggestion to implement it in a better way

Making it draft until then

**Comment by guptadeepak8** [comment]
@TusharBhatt1 pls review this

**Review by kart1ka — APPROVED** [review]
LGTM

**Review by Devanshusharma2005 — APPROVED** [review]
LGTM

File: packages/lib/bookingSuccessRedirect.ts [hunk 3]
```diff
@@ -184,6 +189,7 @@ export const useBookingSuccessRedirect = () => {
         query: {
           ...query,
           ...bookingExtraParams,
+          isEmbed,
```
Comment (hariombalhara) [inline packages/lib/bookingSuccessRedirect.ts:192]: I don't think it is implemented correctly @Devanshusharma2005 could you confirm?
 
_getNewSearchParams_ seems to have added a new property isEmbed(optional) but that isn't passed here. isEmbed is being passed in _query_ object and we don't read isEmbed from query object in _getNewSearchParams_

Comment (hariombalhara) [reply packages/lib/bookingSuccessRedirect.ts:192]: Also, I asked Devin to work on a much more exhaustive approach with unit tests to handle all embed related params

https://github.com/calcom/cal.com/pull/22028 @Devanshusharma2005 Maybe you want to pick it up?
