### PR TITLE
Fixing installed app navigation

### LINKED ISSUE #4588: /installed-apps white screen when navigating
https://www.loom.com/share/7c32f3adda1f46a287a6bfabe75f6916

### PR DESCRIPTION
**Pull request by leog**
## What does this PR do?

Fixes Installed Apps navigation between different variants in the sub menu.

Fixes #4588 

 Loom Video: https://www.loom.com/share/1892cd68d5fb476995f656725d6023e5

**Environment**: Staging(main branch) / Production

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

Go to installed apps page and switch between variants/categories and see the content of each. Before, a white screen appeared due to navigation issues.

### CODE REVIEW

File: apps/web/pages/v2/apps/installed/[category].tsx [hunk 1]
```diff
@@ -202,3 +198,25 @@ export default function InstalledApps() {
     </InstalledAppsLayout>
   );
 }
+
+export const getStaticProps: GetStaticProps = (ctx) => {
```
Comment (hariombalhara) [inline apps/web/pages/v2/apps/installed/[category].tsx:202]: Works well, but don't fully understand why it's required and why it wasn't working earlier.

**Review by hariombalhara — APPROVED** [review]

File: apps/web/pages/v2/apps/installed/[category].tsx [hunk 2]
```diff
@@ -177,12 +177,8 @@ const querySchema = z.object({
   category: z.nativeEnum(InstalledAppVariants),
 });
 
-export default function InstalledApps() {
+export default function InstalledApps({ category }: InferGetStaticPropsType<typeof getStaticProps>) {
   const { t } = useLocale();
-  const router = useRouter();
-  const { category } = router.isReady
```
Comment (zomars) [inline apps/web/pages/v2/apps/installed/[category].tsx:183]: Why this was removed?
