### PR TITLE
fix: use Intl to format month name

### LINKED ISSUE #5442: [CAL-338] Elements on Calendar Widget Localization Translation not Working
A few elements of the calendar widget are not getting localized / translated.

> From [SyncLinear.com](https://synclinear.com)

### PR DESCRIPTION
**Pull request by Udit-takkar**
Fixes: #5442 

Screenshot 2022-11-10 at 12 10 22 AM

### CODE REVIEW

File: packages/ui/v2/modules/booker/DatePicker.tsx [hunk 1]
```diff
@@ -130,22 +131,25 @@ const DatePicker = ({
...
   const browsingDate = passThroughProps.browsingDate || dayjs().startOf("month");
+  const { i18n } = useLocale();
 
   const changeMonth = (newMonth: number) => {
     if (onMonthChange) {
       onMonthChange(browsingDate.add(newMonth, "month"));
     }
   };
 
+  const month = browsingDate
```
Comment (JeroenReumkens) [inline packages/ui/v2/modules/booker/DatePicker.tsx:142]: Is there a possibility where `browsingDate` can be undefined? Looking at the old implementation on line 146 it didn't seem that way? Mainly wondering that since you added the conditional here :)

**Review by JeroenReumkens — APPROVED** [review]
One small question. Besides that looks perfect 🙏

File: packages/ui/v2/modules/booker/DatePicker.tsx (hunk 1 above)
Comment (Udit-takkar) [reply packages/ui/v2/modules/booker/DatePicker.tsx:142]: there was this condition so i thought maybe it takes some time to get browsingData
```
 {browsingDate ? (
            <>
              <strong className="text-bookingdarker text-base font-semibold dark:text-white">{month}</strong>{" "}
              <span className="text-bookinglight text-sm font-medium">{browsingDate.format("YYYY")}</span>
            </>
          ) : (
            <SkeletonText className="h-8 w-24" />
          )}
```

Comment (JeroenReumkens) [reply packages/ui/v2/modules/booker/DatePicker.tsx:142]: Right! I overlooked that. Definitely makes sense! Good to merge to me!
