### PR TITLE
fix: team invite links

### LINKED ISSUE #10106: [CAL-2160] Team invites aren't working for non-users
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Introduced in #8355

Seems like invites to external users aren't being sent when there's more than one.

### Steps to Reproduce

1. Create a team
2. Invite a non-Cal user (all good so far)
3. Try inviting another non-Cal user

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

The current DB schema has a wrong unique constrain on teamID for VerificationToken, also seems like a Team can only have 1 active VerificationToken at a time.

### Actual Results

* There can only be 1 active invite at a time per team

### Expected Results

* A team should be able to have multiple invite tokens active

### Technical details

* Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
* Node.js version
* Anything else that you think could be an issue.

### Evidence

Created a team and bulk-invited 3 new memebers. Only the last one had a relationship with the team.

[Source image](https://github.com/calcom/cal.com/assets/3504472/9bc19629-6536-4f6d-90d9-3e2a7be9bdd7)

Invited a new one and this one got the relationship with the team now. So now previous invites are stuck in limbo.

[Source image](https://github.com/calcom/cal.com/assets/3504472/01e45f68-d34b-4963-84da-f845a3bae295)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2160](https://linear.app/calcom/issue/CAL-2160/team-invites-arent-working-for-non-users)</sub>

### PR DESCRIPTION
**Pull request by zomars**
## What does this PR do?

Fixes #10106

## Type of change

  - [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

  - Create a team and bulk invite new members, on the DB all should have the teamID properly set.
  - Use the copy invite link button. There should be only one active token for it.

## Mandatory Tasks

  - [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: apps/web/pages/signup.tsx [hunk 1]
```diff
@@ -83,7 +82,7 @@ export default function Signup({ prepopulateFormValues, token, orgSlug }: Signup
   };
 
   return (
-    <LicenseRequired>
```
Comment (zomars) [inline apps/web/pages/signup.tsx:86]: LicenseRequired only works for logged in users. All users landing will be logged off.

File: packages/lib/server/queries/teams/index.ts [hunk 2]
```diff
@@ -114,7 +115,16 @@ export async function getTeamWithMembers(id?: number, slug?: string, userId?: nu
     ...eventType,
     metadata: EventTypeMetaDataSchema.parse(eventType.metadata),
   }));
-  return { ...team, metadata: teamMetadataSchema.parse(team.metadata), eventTypes, members };
+  /** Don't leak invite tokens to the frontend */
+  const { inviteTokens, ...teamWithoutInviteTokens } = team;
```
Comment (zomars) [inline packages/lib/server/queries/teams/index.ts:119]: Also to keep previous frontend signature

File: packages/prisma/migrations/20230712192734_fixes_team_verification_tokens/migration.sql [hunk 3]
```diff
@@ -0,0 +1,2 @@
+-- DropIndex
+DROP INDEX "VerificationToken_teamId_key";
```
Comment (zomars) [inline packages/prisma/migrations/20230712192734_fixes_team_verification_tokens/migration.sql:2]: A team can have multiple tokens. Dropped the unique requirement

File: packages/prisma/schema.prisma [hunk 4]
```diff
@@ -310,7 +310,7 @@ model VerificationToken {
   expiresInDays Int?
   createdAt     DateTime @default(now())
   updatedAt     DateTime @updatedAt
-  teamId        Int?     @unique
+  teamId        Int?
```
Comment (zomars) [inline packages/prisma/schema.prisma:313]: This was causing that only the most recent invite had the proper team relationship.

File: packages/trpc/server/routers/viewer/teams/createInvite.handler.ts [hunk 5]
```diff
@@ -22,7 +22,7 @@ export const createInviteHandler = async ({ ctx, input }: CreateInviteOptions) =
   const token = randomBytes(32).toString("hex");
   await prisma.verificationToken.create({
     data: {
-      identifier: "",
+      identifier: "invite-link-for-teamId-" + teamId,
```
Comment (zomars) [inline packages/trpc/server/routers/viewer/teams/createInvite.handler.ts:25]: Only to distinguish the copy link token VS the each individual email.

**Review by zomars — COMMENTED** [review]
Ready for review

File: apps/web/pages/signup.tsx (hunk 1 above)
Comment (PeerRich) [reply apps/web/pages/signup.tsx:86]: we dont need this for this component anyway. great catch!

**Review by emrysal — APPROVED** [review]

**Review by alannnc — APPROVED** [review]
Code looks good!
