### PR TITLE
fix: remove avatar form user select when loading insights

### LINKED ISSUE #11351: [CAL-2465] [CAL-2464] /api/trpc/insights/teamListForUser,userList,eventTypeList,userList,eventTypeList exceeds 4MB size
From axiom logs

```
PI response for /api/trpc/insights/teamListForUser,userList,eventTypeList,userList,eventTypeList?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%2C%221%22%3A%7B%22json%22%3A%7B%22teamId%22%3A10542%2C%22isAll%22%3Afalse%7D%7D%2C%222%22%3A%7B%22json%22%3A%7B%22teamId%22%3A10542%2C%22userId%22%3A108666%2C%22isAll%22%3Afalse%7D%7D%2C%223%22%3A%7B%22json%22%3A%7B%22teamId%22%3A-1%2C%22isAll%22%3Afalse%7D%7D%2C%224%22%3A%7B%22json%22%3A%7B%22teamId%22%3Anull%2C%22userId%22%3A108666%2C%22isAll%22%3Afalse%7D%2C%22meta%22%3A%7B%22values%22%3A%7B%22teamId%22%3A%5B%22undefined%22%5D%7D%7D%7D%7D exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[ERROR] [1694661100348] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 413.
```

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2464](https://linear.app/calcom/issue/CAL-2464/apitrpcinsightsteamlistforuseruserlisteventtypelistuserlisteventtypeli)</sub>

<sub>[CAL-2465](https://linear.app/calcom/issue/CAL-2465/[cal-2464])</sub>

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

- Removes avatar from user select, there are times when on Production loading the avatar will load the full blob making the response larger than 4MB that Vercel limits on api responses.

Fixes #11351 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/features/insights/components/TotalBookingUsersTable.tsx [hunk 1]
```diff
@@ -21,7 +21,7 @@ export const TotalBookingUsersTable = ({
                   <Avatar
                     alt={item.user.name || ""}
                     size="sm"
-                    imageSrc={item.user.avatar}
+                    imageSrc={"/" + item.user.username + "/avatar.png"}
```
Comment (alannnc) [inline packages/features/insights/components/TotalBookingUsersTable.tsx:24]: Loading it via dynamic link.

**Review by PeerRich — APPROVED** [review]

**Comment by PeerRich** [comment]
great idea
