### PR TITLE
fix: display all responses

### LINKED ISSUE #13923: [CAL-3245] Booking question "short text" not being passed to the booking confirmation page or email
Steps to recreate:

* Create an event type
* Add a "Short text" booking question and mark it required
* Try book yourself. The field will be required as expected and you have to enter it
* But the response will not appear in the booking confirmation or in the email and I can't find that response the user entered anywhere

[CleanShot 2024-02-28 at 18.29.41.mp4](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a3201269-7417-4af6-bfad-f8cffe53ee29/1ed9689c-aaf1-45ce-958d-b676130d926e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2U4NmJmOTU3LWQ4MmYtNDY1ZS1iMjA1LTEzNTU1OWY0YjYyMy9hMzIwMTI2OS03NDE3LTRhZjYtYmZhZC1mOGNmZmU1M2VlMjkvMWVkOTY4OWMtYWFmMS00NWNlLTk1OGQtYjY3NjEzMGQ5MjZlIiwiaWF0IjoxNzA5MTQ1MTIwLCJleHAiOjE3MDkyMzE1MjB9._8g91QDTNrIYNRxxOwbjRAGkmkpPpZqSmc9q1UH-TeM)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3245](https://linear.app/calcom/issue/CAL-3245/booking-question-short-text-not-being-passed-to-the-booking)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/13923

Screenshot 2024-03-07 at 10 46 47 AM

Screenshot 2024-03-07 at 10 47 17 AM

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/lib/getLabelValueMapFromResponses.ts [hunk 1]
```diff
@@ -1,10 +1,16 @@
...
 import type { bookingResponse } from "@calcom/features/bookings/lib/getBookingResponsesSchema";
 import type { CalendarEvent } from "@calcom/types/Calendar";
 
 export default function getLabelValueMapFromResponses(calEvent: CalendarEvent) {
-  const { customInputs, userFieldsResponses } = calEvent;
+  const { customInputs, userFieldsResponses, responses, eventTypeId } = calEvent;
+
+  const isDynamicEvent = !eventTypeId;
+  if (!!responses[TITLE] && !isDynamicEvent) {
+    userFieldsResponses[TITLE] = responses[TITLE];
```
Comment (CarinaWolli) [inline packages/lib/getLabelValueMapFromResponses.ts:12]: type errors here

File: packages/features/bookings/lib/SystemField.ts [hunk 2]
```diff
@@ -12,3 +12,4 @@ export const SystemField = z.enum([
 ]);
 
 export const SMS_REMINDER_NUMBER_FIELD = "smsReminderNumber";
+export const TITLE = "title";
```
Comment (emrysal) [inline packages/features/bookings/lib/SystemField.ts:15]:
```suggestion
export const TITLE_FIELD = "title";
```

**Review by emrysal — APPROVED** [review]
Looks good to me, thanks for the rename 😎
