### PR TITLE
Redirect to /even-types after deleting an event type

### LINKED ISSUE #4694: Deleting an event on the events settings page should return to events page
### Issue Summary

If an event is deleted using the trash can icon from that event's settings page, the event is deleted, but the user remains in that event's page. This is confusing for the user, as the event no longer exists. Instead, after deletion the deleted event should no longer be shown and the user should be taken back to the main Events page instead.

### Steps to Reproduce

1. Go to Events
1. Navigate to an existing event
1. On the right-hand side, click on the ellipsis for that event
1. On the drop-down menu, click on Duplicate
1. Fill in the necessary details on the `Add event type` dialog
1. Click on Accept
1. On the next screen with the newly created event settings, click on the trash can icon to delete it
1. On the next dialog, click on `Yes, delete event type`
1. A message is shown at the bottom right-hand side of the screen: `Event has been deleted`
1. The user is left at the screen showing the details of the deleted event

Expected:
- After event deletion, the deleted event settings should not be shown. Instead, the user should be redirected to the main Events page.

### Technical details

- Browser version: Firefox 105
- OS version: Ubuntu 22.04

### PR DESCRIPTION
**Pull request by CarinaWolli**
## What does this PR do?

Redirect to /event-types after deleting an event type.

Fixes #4694

**Environment**: Staging(main branch) / Production

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Go to /event-types
- Click on an event type to go to event type settings
- Click on trash icon to delete even type 
- Click 'Yes, delete event type'
- See that you are redirected back to /event-types

### CODE REVIEW

File: apps/web/components/v2/eventtype/EventTypeSingleLayout.tsx [hunk 1]
```diff
@@ -118,6 +120,7 @@ function EventTypeSingleLayout({
     onSuccess: async () => {
       await utils.invalidateQueries(["viewer.eventTypes"]);
       showToast(t("event_type_deleted_successfully"), "success");
+      await router.push("/event-types");
       setDeleteDialogOpen(false);
```
Comment (emrysal) [inline apps/web/components/v2/eventtype/EventTypeSingleLayout.tsx:124]: setDeleteDialogOpen(false); may be redundant now too

**Review by emrysal — APPROVED** [review]
