### PR TITLE
Fix: Show smsReminderNumber on booking success page

### LINKED ISSUE #8380: [CAL-1527] SMS reminder number not shown on /booking/[uid] page
The sms reminder number from SMS workflows (send SMS to attendee) is not shown anywhere. It used to be shown on the /booking/\[uid\] page

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1527](https://linear.app/calcom/issue/CAL-1527/sms-reminder-number-not-shown-on-booking[uid]-page)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?
Fixes #8380
Fixes CAL-1607
#8465 was initially created by @Hallidayo which implements the fix but some changes were requested which are not yet done yet. So, I am taking over the bug fix.

Before:
Screenshot 2023-05-01 at 3 44 20 PM

After:
Screenshot 2023-05-01 at 3 43 38 PM

**Environment**: Production

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [x] Enable a workflow(with action that sends SMS to attendee) in an event-type. Fill up the automatically added SMS Reminder Number field in the booking form. Expect that the smsReminderNumber is shown as in above screenshot

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: apps/web/pages/booking/[uid].tsx [hunk 1]
```diff
@@ -487,7 +488,8 @@ export default function Success(props: SuccessProps) {
                       // We show rescheduleReason at the top
                       if (!field) return null;
                       const isSystemField = SystemField.safeParse(field.name);
-                      if (isSystemField.success) return null;
+                      // SMS_REMINDER_NUMBER_FIELD is a system field but doesn't have a dedicated place in the UI. So, it would be shown through the folowing responses list
```
Comment (hariombalhara) [inline apps/web/pages/booking/[uid].tsx:491]:
```suggestion
                      // SMS_REMINDER_NUMBER_FIELD is a system field but doesn't have a dedicated place in the UI. So, it would be shown through the following responses list
```

**Review by Udit-takkar — APPROVED** [review]

**Review by CarinaWolli — APPROVED** [review]
