### PR TITLE
Fix: Profile update refresh issues

### LINKED ISSUE #8448: [CAL-1574] Avatar not Loading after New Account Setup
This is a dumby account, but the avatar isn't loading after it's been set in settings (granted username has not been paid for)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1574](https://linear.app/calcom/issue/CAL-1574/avatar-not-loading-after-new-account-setup)</sub>

### LINKED ISSUE #8567: Full Name not refreshing after Profile Update
### Issue Summary

Left Navigation Profile Name not refreshed after Full Name update under My Profile on this route: `/settings/my-account/profile`

### Steps to Reproduce

1. Went to Settings -> MyAccount -> Profile page
2. Modified Full Name and Clicked on Update
3. Full Name didn't update/refresh immediately on the Left Navigation.

Refer to the screenshot below:

Screenshot 2023-04-29 at 2 41 22 PM

### Technical details

- Google Chrome version: 112.0.5615.137
- Node.js version: v16.19.0

### PR DESCRIPTION
**Pull request by Keyurkd**
## What does this PR do?

Fixes #8567 #8610 

## Type of change

- Bug fix 
Query the user profile & avatar data from the database and refresh the content of the left navbar.

### CODE REVIEW

**Comment by ExplorerAadi** [comment]
Hey @Keyurkd This was a neat solution, but I believe you need to implement the same fix for the sidebar as well. I updated my profile picture but as you can see, it did not update here.
image

**Comment by Keyurkd** [comment]
Hi @ExplorerAadi 
Check the updates on PR that will resolve the issue you've mentioned.

**Comment by Keyurkd** [comment]
Hi @zomars, @sean-brydon ,
Please review this PR.

File: apps/web/pages/event-types/index.tsx [hunk 1]
```diff
@@ -675,7 +679,11 @@ const EventTypeListHeading = ({
       <Avatar
         alt={profile?.name || ""}
         href={teamId ? `/settings/teams/${teamId}/profile` : "/settings/my-account/profile"}
-        imageSrc={`${WEBAPP_URL}/${profile.slug}/avatar.png` || undefined}
+        imageSrc={
+          loggedInUser?.username === profile.slug
```
Comment (Udit-takkar) [inline apps/web/pages/event-types/index.tsx:683]: why are you checking loggedInUser here ?

File: packages/features/settings/layouts/SettingsLayout.tsx [hunk 2]
```diff
@@ -105,14 +107,16 @@ const adminRequiredKeys = ["admin"];
...
+  const { data: user } = useMeQuery();
+  const { data: avatar } = useAvatarQuery();
 
   const isAdmin = session.data?.user.role === UserPermissionRole.ADMIN;
 
   tabs.map((tab) => {
-    if (tab.name === "my_account") {
-      tab.name = session.data?.user?.name || "my_account";
+    if (tab.href === "/settings/my-account") {
+      tab.name = user?.name || "my_account";
```
Comment (Udit-takkar) [inline packages/features/settings/layouts/SettingsLayout.tsx:117]: although this works but we should look into how can we make sure useSession returns the latest data.

Comment (Keyurkd) [reply packages/features/settings/layouts/SettingsLayout.tsx:117]: @Udit-takkar ,

I used href because when the user changed the name in the profile settings, `tab.name` wouldn't remain the same as `my-account` in re-render.  

Here in [trpc].ts file, cacheRules is mentioned as `no-cache` for the session. So, it does revalidate each time but somehow it didn't update.

```
const cacheRules = {
      "viewer.public.session": `no-cache`,
      "viewer.public.i18n": `no-cache`,
      // Revalidation time here should be 1 second, per https://github.com/calcom/cal.com/pull/6823#issuecomment-1423215321
      "viewer.public.slots.getSchedule": `no-cache`, // FIXME
      "viewer.public.cityTimezones": `max-age=${ONE_DAY_IN_SECONDS}, stale-while-revalidate`,
    } as const;
```

File: apps/web/pages/event-types/index.tsx (hunk 1 above)
Comment (Keyurkd) [reply apps/web/pages/event-types/index.tsx:683]: @Udit-takkar ,
This component `EventTypeListHeading` is used in the map of `eventTypeGroups`. To make sure to update the avatar image of loggedInUser only I have to use that condition.

Without the loggedInUser check:
```  
imageSrc={avatar?.avatar || `${WEBAPP_URL}/${profile.slug}/avatar.png` || undefined} 
```
Screenshot 2023-05-02 at 3 38 53 PM

With the loggedInUser check:
``` 
imageSrc={loggedInUser?.username === profile.slug ? avatar?.avatar : `${WEBAPP_URL}/${profile.slug}/avatar.png` || undefined}
```
        
Screenshot 2023-05-02 at 3 44 15 PM

Once you approve this change I have to update the same in the `MobileTeamsTab` function of the same file for Mobile view.

File: packages/features/settings/layouts/SettingsLayout.tsx (hunk 2 above)
Comment (Keyurkd) [reply packages/features/settings/layouts/SettingsLayout.tsx]: @Udit-takkar ,
Fixed. Thanks.

File: apps/web/pages/event-types/index.tsx (hunk 1 above)
Comment (Keyurkd) [reply apps/web/pages/event-types/index.tsx:683]: @Udit-takkar ,
Let me know your thoughts on the above changes. I will revert if you think we should find a better way to handle this so that the rest of the code you can merge.

Comment (Keyurkd) [reply apps/web/pages/event-types/index.tsx]: Hi @Udit-takkar ,
Raised a separate PR(https://github.com/calcom/cal.com/pull/8694)  for the #8448 fixes. 
You can merge these changes.

**Comment by PeerRich** [comment]
it feels like there is an easier fix for this. @zomars any ideas?

**Comment by zomars** [comment]
> it feels like there is an easier fix for this. @zomars any ideas?

Agreed. Can't we just invalidate the used query on the sidebar whenever updating the profile?

**Review by alannnc — APPROVED** [review]
