### PR TITLE
Close settings sidebar on window resize

### LINKED ISSUE #4642: Duplicate sidebar on settings
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When opening the sidebar with the split screen and then increasing the screen the sidebar is duplicated

### Steps to Reproduce

1. Go to http://localhost:3000/settings
2. Decrease the screen size and open the sidebar
3. The side bar will be duplicated

Screenshot from 2022-09-21 09-28-54

Loom video: https://www.loom.com/share/e469fc0292174d13b65fee736191259b

### PR DESCRIPTION
**Pull request by joeauyeung**
## What does this PR do?

This PR adds an event listener to close the settings sidebar when the window reaches the "large" (1024px) size.

Fixes #4642

https://www.loom.com/share/36f07579cf9a4bcfbac5d5c66aef900a

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Go to the settings page and reduce the window size to where the top bar renders
- Open the side navigation pane
- Resize the window back to large
	- There should only be one sidebar container

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Jaibles** [comment]
Looks good to me!

**Review by ciaranha — APPROVED** [review]
Looks good to me!

File: packages/ui/v2/core/layouts/SettingsLayout.tsx [hunk 1]
```diff
@@ -296,6 +296,17 @@ export default function SettingsLayout({
...
+
+  useEffect(() => {
+    const closeSideContainer = () => {
+      if (window.innerWidth >= 1024) {
+        setSideContainerOpen(false);
+      }
+    };
+
+    window.addEventListener("resize", closeSideContainer);
+  }, []);
```
Comment (zomars) [inline packages/ui/v2/core/layouts/SettingsLayout.tsx:308]:
```suggestion
  useEffect(() => {
    const closeSideContainer = () => {
      if (window.innerWidth >= 1024) {
        setSideContainerOpen(false);
      }
    };

    window.addEventListener("resize", closeSideContainer);
    return () => {
      window.removeEventListener("resize", closeSideContainer);
    }
  }, []);
```
