### PR TITLE
fix: Embed - Non transparent background when color-scheme of embedding document and cal.com iframe don't match

### LINKED ISSUE #10032: [CAL-2129] Explicitly setting dark color-scheme on container page of embed adds a white background to embed iframe
Demo of the bug at [https://codesandbox.io/s/color-scheme-3xvcqy?file=/public/index.html](https://codesandbox.io/s/color-scheme-3xvcqy?file=/public/index.html). Notice that there is white background beyond the bordered booker.

Why it happens [https://fvsch.com/transparent-iframes#:\~:text=the resolution was%3A-,If the color scheme of an iframe differs from embedding document%2C iframe gets an opaque canvas background appropriate to its color scheme.,-So the dark](https://fvsch.com/transparent-iframes#:\~:text=the%20resolution%20was%3A-,If%20the%20color%20scheme%20of%20an%20iframe%20differs%20from%20embedding%20document%2C%20iframe%20gets%20an%20opaque%20canvas%20background%20appropriate%20to%20its%20color%20scheme.,-So%20the%20dark)

When color-scheme is set to dark

[Source image](https://github.com/calcom/cal.com/assets/1780212/131fc8ab-22cb-46b2-8de0-95fdbd9e34d2)

When color-scheme isn't set to dark

[Source image](https://github.com/calcom/cal.com/assets/1780212/cf7c0360-3c78-4534-b8da-1c6bce62e062)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2129](https://linear.app/calcom/issue/CAL-2129/explicitly-setting-dark-color-scheme-on-container-page-of-embed-adds-a)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #10032

Before:
https://www.loom.com/share/1890e4eebf41426aaf66d8b4909d0765
After:
https://www.loom.com/share/8b00c41587f2467ab05ef48e4ed523ef

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- See loom

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by PeerRich** [comment]
is this what infisical is experiencing?

**Comment by hariombalhara** [comment]
@PeerRich Yes, it's the same issue. But they are experiencing a bigger issue that their CSP policy is blocking our inline styles. Also CSP policy is impacting not just us but Intercom as well.
Screenshot 2023-07-12 at 8 53 29 AM

File: apps/web/pages/_document.tsx [hunk 1]
```diff
@@ -28,17 +28,18 @@ class MyDocument extends Document<Props> {
...
 
   render() {
     const { locale } = this.props.__NEXT_DATA__;
-    const { isEmbed } = this.props;
+    const { isEmbed, embedColorScheme } = this.props;
     const nonceParsed = z.string().safeParse(this.props.nonce);
     const nonce = nonceParsed.success ? nonceParsed.data : "";
     return (
-      <Html lang={locale}>
+      <Html lang={locale} style={embedColorScheme ? { colorScheme: embedColorScheme as string } : undefined}>
```
Comment (hariombalhara) [inline apps/web/pages/_document.tsx:42]: Setting `colorScheme` serverside to avoid flash of unexpected background due to missing color-scheme.

File: packages/embeds/embed-core/playground.ts [hunk 2]
```diff
@@ -6,8 +6,28 @@ const callback = function (e) {
...
+    const pageUrl = new URL(document.URL);
+    for (const [name, value] of pageUrl.searchParams.entries()) {
+      if (toUrl.searchParams.get(name) === null) {
+        toUrl.searchParams.append(decodeURIComponent(name), value);
+      }
+    }
+    location.href = `?${toUrl.searchParams.toString()}#${toUrl.hash}`;
+    e.preventDefault();
+  }
+});
```
Comment (hariombalhara) [inline packages/embeds/embed-core/playground.ts:22]: Enables the playground to carry forward existing query params on clicking an anchor tag. Helps with testing color-scheme with all embeds

File: packages/embeds/embed-core/playground.ts [hunk 3]
```diff
@@ -6,8 +6,28 @@ const callback = function (e) {
...
+
 const searchParams = new URL(document.URL).searchParams;
 const only = searchParams.get("only");
+const colorScheme = searchParams.get("color-scheme");
+if (colorScheme) {
+  document.documentElement.style.colorScheme = colorScheme;
```
Comment (hariombalhara) [inline packages/embeds/embed-core/playground.ts:28]: Allows playground to use a specific color-scheme as instructed by query param

File: packages/embeds/embed-core/src/embed.ts [hunk 4]
```diff
@@ -116,6 +116,31 @@ function validate(data: Record<string, unknown>, schema: ValidationSchema) {
   }
 }
 
+function getColorScheme(el: HTMLElement) {
+  const pageColorScheme = getComputedStyle(el).colorScheme;
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed.ts:120]: Allows us to get the color scheme  from any element(even when it is set on root element). It allows us to handle all scenarios of setting color-scheme even down the DOM tree.

File: packages/embeds/embed-core/src/embed.ts [hunk 5]
```diff
@@ -116,6 +116,31 @@ function validate(data: Record<string, unknown>, schema: ValidationSchema) {
...
+  if (pageColorScheme === "dark" || pageColorScheme === "light") {
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed.ts:121]: Initially handle `colorScheme` of dark and light only. Theoretcially there can be more color-schemes but let that scenario come up in production and handle the right way then.

File: packages/embeds/embed-core/src/embed.ts [hunk 6]
```diff
@@ -711,3 +750,18 @@ document.addEventListener("click", (e) => {
     calOrigin,
   });
 });
+
+let currentColorScheme: string | null = null;
+
+(function watchAndActOnColorSchemeChange() {
+  setInterval(() => {
+    const colorScheme = getColorScheme(document.body);
+    if (colorScheme && colorScheme !== currentColorScheme) {
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed.ts:759]: Avoid bombarding iframe with colorScheme setting instructions. Only do it when it actually changes.

File: packages/embeds/embed-core/src/embed.ts [hunk 7]
```diff
@@ -421,23 +446,31 @@ class CalApi {
     if (typeof config.iframeAttrs === "string" || config.iframeAttrs instanceof Array) {
       throw new Error("iframeAttrs should be an object");
     }
-    config.embedType = "inline";
-    const iframe = this.cal.createIframe({ calLink, queryObject: Cal.getQueryObject(config) });
-    iframe.style.height = "100%";
-    iframe.style.width = "100%";
-    const element =
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed.ts:428]: Renamed element to containerEl

File: packages/embeds/embed-core/src/embed.ts [hunk 8]
```diff
@@ -421,23 +448,35 @@ class CalApi {
...
       throw new Error("Element not found");
     }
-    element.classList.add("cal-inline-container");
+
+    config.embedType = "inline";
+
+    // Note that by the time, the server responds with html having appropriate color-scheme, there might be a flash of non-transparent(white/black) background(for a few 100 milliseconds)
+    // There is no quick way know to fix it.
+    // An approach might be to add a temporary neutral iframe(with no src) whose html can be directly modified synchronously and let the iframe with calLink src respond,
+    // once the iframe responds, we can replace the neutral iframe with the calLink iframe
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed.ts:465]: Followup on this when needed.

**Review by zomars — APPROVED** [review]
[cool](https://app.graphite.dev/macros/calcom)
