### PR TITLE
fix: improved 'use-identity-login' error message for users trying to signInn using different provider

### LINKED ISSUE #20550: [CAL-5430] Improve 'use-identity-login' error
Image

The error shows when user tries to signin through different SSO or Signin method than what his account was created with.

e.g. User account created via Okta but user tries to signin via Google - That error would show. We should show something like 'You should signin through Okta'
User tries to sign in via Google, but he created account using username and password, then too that error can possibly come and we should show error like 'You should sign in with email and password'

<sub>[CAL-5430](https://linear.app/calcom/issue/CAL-5430/improve-use-identity-login-error)</sub>

### PR DESCRIPTION
**Pull request by romitg2**
…t provider

## What does this PR do?

- Fixes #20550  
- Fixes CAL-5430 

### Before Change: (was like)

Screenshot 2025-04-05 at 4 16 09 AM

### After Change:

Screenshot 2025-04-07 at 3 01 54 PM

##### how I solved?
- passed additional query parameter passing identity provider which is managing user acccount.

##### changes made:
- added additional query parameter for "user-identity-login" type of error which gives provider to which email is linked to (CAL, GOOGLE, SAML)
- based on this provider render specific error message for user. 

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

Screenshot 2025-04-05 at 4 33 50 AM

###### redirects to this page: (i added query parameter which passes original provider information to error page)

- http://localhost:3000/auth/error?error=use-identity-login&provider=CAL

### CODE REVIEW

**Comment by romitg2** [comment]
@hariombalhara

**Review by retrogtx — DISMISSED** [review]

File: apps/web/app/(use-page-wrapper)/auth/error/page.tsx [hunk 1]
```diff
@@ -17,12 +18,36 @@ export const generateMetadata = async () => {
...
 });
 
 const ServerPage = async ({ searchParams }: PageProps) => {
   const t = await getTranslate();
-  const { error } = querySchema.parse({ error: (await searchParams)?.error || undefined });
-  const errorMsg = t("error_during_login") + (error ? ` Error code: ${error}` : "");
+
+  const { error, provider } = querySchema.parse({
+    error: (await searchParams)?.error || undefined,
+    provider: (await searchParams)?.provider || undefined,
```
Comment (hariombalhara) [inline apps/web/app/(use-page-wrapper)/auth/error/page.tsx:29]: Who provides the provider query param?

**Comment by hariombalhara** [comment]
@romitg2 You add/commit/push that file, we will re-review and approve

File: packages/features/auth/lib/next-auth-options.ts [hunk 2]
```diff
@@ -950,7 +950,7 @@ export const getOptions = ({
               return true;
             }
           } else if (existingUserWithEmail.identityProvider === IdentityProvider.CAL) {
-            return "/auth/error?error=use-password-login";
+            return `/auth/error?error=use-identity-login&provider=${existingUserWithEmail.identityProvider}`;
```
Comment (hariombalhara) [inline packages/features/auth/lib/next-auth-options.ts:953]: I think the error code `use-identity-login` doesn't make sense in this case as it is email and password case and not identity provider.

How about we change the error to something generic like, "wrong-provider" and then we can handle all cases under this error instead of use-identity-login

File: packages/features/auth/lib/next-auth-options.ts [hunk 3]
```diff
@@ -971,8 +971,7 @@ export const getOptions = ({
               return true;
             }
           }
-
-          return "/auth/error?error=use-identity-login";
+          return `auth/error?error=use-identity-login&provider=${existingUserWithEmail.identityProvider}`;
```
Comment (hariombalhara) [inline packages/features/auth/lib/next-auth-options.ts:974]:
```suggestion
          return `/auth/error?error=use-identity-login&provider=${existingUserWithEmail.identityProvider}`;
```

File: apps/web/app/(use-page-wrapper)/auth/error/page.tsx [hunk 4]
```diff
@@ -17,12 +18,36 @@ export const generateMetadata = async () => {
...
+  const getErrorMessage = (error: string | undefined, provider: string | undefined) => {
+    if (error === "use-identity-login") {
+      // showing user their original identity provider by which account is managed.
+      const providerName =
+        provider === IdentityProvider.GOOGLE
+          ? "Google"
+          : provider === IdentityProvider.CAL
+          ? "Email and Password"
+          : provider === IdentityProvider.SAML
+          ? "SAML"
```
Comment (hariombalhara) [inline apps/web/app/(use-page-wrapper)/auth/error/page.tsx:42]:
```suggestion
          ? "SAML(e.g. Okta)"
```

File: packages/features/auth/lib/next-auth-options.ts [hunk 5]
```diff
@@ -971,8 +971,7 @@ export const getOptions = ({
               return true;
             }
           }
-
-          return "/auth/error?error=use-identity-login";
+          return `/auth/error?error=use-identity-login&provider=${existingUserWithEmail.identityProvider}`;
         }
```
Comment (hariombalhara) [inline packages/features/auth/lib/next-auth-options.ts:975]: Also there is one more place that uses `use-identity-login` as the error when there is actually an error in creating new user. We should change that error to something like 'user-creation-error' and show it in UI like 'There is an error in creating your user'
https://github.com/romitg2/cal.com/blob/user-identity-login/packages/features/auth/lib/next-auth-options.ts#L1012

**Review by hariombalhara — DISMISSED** [review]
Great work so far @romitg2 !! Left some comments to be addressed

File: packages/features/auth/lib/next-auth-options.ts (hunk 5 above)
Comment (romitg2) [reply packages/features/auth/lib/next-auth-options.ts:975]: 👍. 
We're currently using a very generic error type (use-identity-login). I'll define and use more specific error names to clearly distinguish between different error cases

**Comment by romitg2** [comment]
> Great work so far @romitg2 !! Left some comments to be addressed

Thanks. 

Fixed and Tested. 

Image
Image

**Review by retrogtx — APPROVED** [review]
