### PR TITLE
fix: Embed: data-cal-origin not used by modal(which is used by both element click popup and floating button popup)

### LINKED ISSUE #12073: [CAL-2644] Not able to configure origin for element click popup with React snippet.
This is because `data-cal-origin` is unused for element-click-popup

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2644](https://linear.app/calcom/issue/CAL-2644/not-able-to-configure-origin-for-element-click-popup-with-react)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #12073

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
Set `data-cal-origin` on the element click popup button and see that the cal link is still being opened from default app.cal.local:3000 and not the provided value

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/embeds/embed-core/src/embed.ts [hunk 1]
```diff
@@ -236,7 +236,7 @@ export class Cal {
   }: {
     calLink: string;
     queryObject?: PrefillAndIframeAttrsConfig & { guest?: string | string[] };
-    calOrigin?: string;
+    calOrigin: string | null;
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed.ts:239]: Make it required so that it's never missed

File: packages/embeds/embed-core/src/embed.ts [hunk 2]
```diff
@@ -473,10 +473,12 @@ class CalApi {
     }
 
     config.embedType = "inline";
+    const calConfig = this.cal.getConfig();
 
     const iframe = this.cal.createIframe({
       calLink,
       queryObject: withColorScheme(Cal.getQueryObject(config), containerEl),
+      calOrigin: calConfig.calOrigin,
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed.ts:481]: Even though createIframe fallbacks to it, but it's better to be explcit.

File: packages/embeds/embed-core/src/embed.ts [hunk 3]
```diff
@@ -607,6 +610,7 @@ class CalApi {
       iframe = this.cal.createIframe({
         calLink,
         queryObject,
+        calOrigin: calOrigin || null,
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed.ts:613]: This is what actually fixes the bug.

**Review by PeerRich — APPROVED** [review]
