### PR TITLE
fix: Reschedule a cancelled booking

### LINKED ISSUE #13166: [CAL-2909] Ability to reschedule a cancelled event
So there's a way a user can potentially rescheduled a cancelled event.

if the user gets to booking page url, they can still use this bug to create new bookings from the previously cancelled one. Please take a look at the loom video to see how to recreate the issue.

Loom: [https://www.loom.com/share/f03e2f3788ce42839704068ff91469e4](https://www.loom.com/share/f03e2f3788ce42839704068ff91469e4)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2909](https://linear.app/calcom/issue/CAL-2909/ability-to-reschedule-a-cancelled-event)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/13166

Throw error while trying to reschedule cancelled booking.

Screenshot 2024-01-11 at 6 15 42 PM

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 1]
```diff
@@ -1078,6 +1078,13 @@ async function handler(
     if (!originalRescheduledBooking) {
       throw new HttpError({ statusCode: 404, message: "Could not find original booking" });
     }
+
+    if (
+      originalRescheduledBooking.status === BookingStatus.CANCELLED &&
+      !originalRescheduledBooking.rescheduled
```
Comment (Udit-takkar) [inline packages/features/bookings/lib/handleNewBooking.ts:1084]: when organizer selects "request reschedule" then reschedule is set to true and that booking can be rescheduled

**Review by alishaz-polymath — DISMISSED** [review]
LGTM 🚀

**Review by CarinaWolli — APPROVED** [review]
LGTM 🙏
