### PR TITLE
fix: textarea ux in Editor.tsx #16225

### LINKED ISSUE #16225: just a small ui bug
### Issue Summary

there is some ui bugs there in the textarea
Screenshot 2024-08-16 115548
Screenshot 2024-08-16 115702

### Steps to Reproduce

1. (for example) Went to /event-types
2. Clicked on New
3. go to text area

### Expected behavior

the text are should have max-width for stopping it to grow very long on default.

### Other information

_No response_

### Screenshots

_No response_

### Environment

- [ ] app.cal.com
- [ ] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS:
- Node:
- npm:
```

### PR DESCRIPTION
**Pull request by thefcraft**
## What does this PR do?

- Fixes #16225 

also follows [pull request] 16226 changes

Screenshot 2024-08-16 144852

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

i tested the ui my self
and run the test cases

## Checklist

### CODE REVIEW

File: packages/ui/components/dialog/Dialog.tsx [hunk 1]
```diff
@@ -190,8 +191,10 @@ export function DialogFooter(props: DialogFooterProps) {
       <div
         className={classNames(
           "flex justify-end space-x-2 pb-4 pt-4 rtl:space-x-reverse",
-          !props.showDivider && "pb-8"
-        )}>
+          !props.showDivider && "pb-8",
+          props.className
+        )}
+        style={{ borderColor: "var(--cal-bg)" }}>
```
Comment (anikdhabal) [inline packages/ui/components/dialog/Dialog.tsx:197]: This is very bad

File: packages/ui/components/editor/Editor.tsx [hunk 2]
```diff
@@ -84,13 +85,13 @@ export const Editor = (props: TextEditorProps) => {
           />
           <div
             className={classNames("editor-inner scroll-bar", !editable && "!bg-subtle")}
-            style={{ height: props.height }}>
+            style={{ height: props.height, overflow: "hidden auto" }}>
```
Comment (anikdhabal) [inline packages/ui/components/editor/Editor.tsx:88]: Why this changes?

**Review by anikdhabal — CHANGES_REQUESTED** [review]
Your changes did not fix the actual issue; now it hides the ring color using hardcoded styles. I don't think this is a good approach.

The only thing that is needed, and I thought about it before, is a max-height property for the editor.

File: packages/ui/components/editor/Editor.tsx (hunk 2 above)
Comment (thefcraft) [reply packages/ui/components/editor/Editor.tsx:88]: Screenshot 2024-08-16 101322
to remove the visibility of scroll bar in x direction. as it is not needed

File: packages/features/eventtypes/components/CreateEventTypeDialog.tsx [hunk 3]
```diff
@@ -254,6 +254,7 @@ export default function CreateEventTypeDialog({
                   placeholder={t("quick_video_meeting")}
                   firstRender={firstRender}
                   setFirstRender={setFirstRender}
+                  maxHeight="250px"
```
Comment (Amit91848) [inline packages/features/eventtypes/components/CreateEventTypeDialog.tsx:257]: This isn't needed, dialog shouldn't break even if you extend the height of textarea beyond 250px. We should focus on fixing that issue and not limiting here.

Comment (thefcraft) [reply packages/features/eventtypes/components/CreateEventTypeDialog.tsx:257]: no this is for making the initial height to be fixed only i mean when we initially write something then don't grow it very long and we can overwrite it by the resize icon at bottom left.

Comment (thefcraft) [reply packages/features/eventtypes/components/CreateEventTypeDialog.tsx:257]: and i use this css <DialogFooter showDivider className="-ml-1 -mr-1 border-l-4 border-r-4"> to hide/fix the issue

**Comment by thefcraft** [comment]
> anikdhab

`DialogFooter showDivider className="-ml-1 -mr-1 border-l-4 border-r-4"` this line does 

Screenshot 2024-08-16 152215

**Comment by thefcraft** [comment]
https://github.com/user-attachments/assets/887759c8-e115-4eef-a6dd-58b6219f835c

have a look

File: packages/ui/components/dialog/Dialog.tsx [hunk 4]
```diff
@@ -190,8 +192,10 @@ export function DialogFooter(props: DialogFooterProps) {
       <div
         className={classNames(
           "flex justify-end space-x-2 pb-4 pt-4 rtl:space-x-reverse",
-          !props.showDivider && "pb-8"
-        )}>
+          !props.showDivider && "pb-8",
+          props.className
+        )}
+        style={{ borderColor: props.borderColor ? props.borderColor : "transparent" }}>
```
Comment (Amit91848) [inline packages/ui/components/dialog/Dialog.tsx:198]: Revert this as well, no need to pass it as props

File: packages/ui/components/dialog/Dialog.tsx [hunk 5]
```diff
@@ -190,8 +192,10 @@ export function DialogFooter(props: DialogFooterProps) {
       <div
         className={classNames(
           "flex justify-end space-x-2 pb-4 pt-4 rtl:space-x-reverse",
```
Comment (Amit91848) [inline packages/ui/components/dialog/Dialog.tsx:194]:
```suggestion
          "flex justify-end space-x-2 pb-4 pt-4 rtl:space-x-reverse bg-default -mx-8",
```

We can do this for now to expand the footer, like it is done in divider. Instead of hardcoding borderColor, you can add bg-default className to get desired background

**Review by Amit91848 — DISMISSED** [review]
Unit tests are failing @thefcraft, please look into it. Also suggested some changes which would solve the problem for all the Dialogs

File: packages/ui/components/dialog/Dialog.tsx [hunk 6]
```diff
@@ -190,6 +190,7 @@ export function DialogFooter(props: DialogFooterProps) {
...
+          "bg-default -ml-1 -mr-1",
```
Comment (anikdhabal) [inline packages/ui/components/dialog/Dialog.tsx:193]: It's works, but definitely not pixel perfect. My question is, for one dialog or a simple issue, why do other dialogs suffer?

Screenshot 2024-08-16 193625

People often don't provide as much description when creating an event, which causes the editor to go off-screen. I suggest adding an optional max-height property to the editor to ensure it doesn't go off-screen.

**Review by anikdhabal — CHANGES_REQUESTED** [review]

**Review by anikdhabal — APPROVED** [review]
LGTM!!
