### PR TITLE
fix: Disable cancel button for past bookings

### LINKED ISSUE #22370: Past call bookings shouldn’t have the cancel event option.
## Proposal

Currently, users are able to see and use the "Cancel Event" option even for past call bookings. This behavior is misleading, as canceling an event that has already occurred has no practical effect and may lead to confusion or misuse.

### Suggested Solution

- Disable or hide the "Cancel Event" button for any call bookings that are in the past (i.e., where the event end time is earlier than the current time).
- Ensure the UI reflects this change consistently across all relevant views (e.g., booking details page, event list, etc.).
- Optionally, provide a tooltip or status indicator to explain that past events cannot be cancelled.

### Benefits

- Improves user experience by preventing actions that are no longer valid.
- Reduces potential for errors or misunderstandings around event management.
- Maintains a clearer distinction between past and upcoming bookings in terms of available actions.

### Notes

If cancellation of past events is currently being logged or triggering backend workflows, ensure this logic is updated accordingly to prevent unnecessary processing.

### PR DESCRIPTION
**Pull request by husniabad**
## What does this PR do?

- Fixes #22370 (GitHub issue number)
- Fixes CAL-6072 (Linear issue number - should be visible at the bottom of the GitHub issue description)

This PR prevents users from canceling past bookings by hiding cancel buttons in the UI and adding server-side checks to block API bypass attempts. It keeps the existing cancellation flow and user experience unchanged for valid future bookings.

## Visual Demo (For contributors especially)

A visual demonstration is strongly recommended, for both the original and new change **(video / image - any one)**.

#### Video Demo (if applicable):

- Show screen recordings of the issue or feature.
- Demonstrate how to reproduce the issue, the behavior before and after the change.

#### Image Demo (if applicable):

- Add side-by-side screenshots of the original and updated change.
- Highlight any significant change(s).

image
<br><br>
image
<br><br>
<div align="center">
  image
</div>

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

### CODE REVIEW

**Comment by anikdhabal** [comment]
@husniabad pls fix the conflicts

**Comment by husniabad** [comment]
Hi @anikdhabal I have fixed the conflicts and updated the PR to fit the latest design, there could be some failed tests but none of them related to my PR
Please review and approve🙏

File: packages/platform/examples/base/src/pages/[bookingUid].tsx [hunk 1]
```diff
@@ -27,6 +27,7 @@ export default function Bookings(props: { calUsername: string; calEmail: string
     const year = dayjs(booking?.start).year();
     const day = dayjs(date).format("dddd");
     const month = dayjs(date).format("MMMM");
+    const isBookingInPast = new Date(booking?.end) < new Date();
```
Comment (kart1ka) [inline packages/platform/examples/base/src/pages/[bookingUid].tsx]: There is a type error here. Can you please fix that?

image

**Review by kart1ka — CHANGES_REQUESTED** [review]
Left a comment

**Comment by husniabad** [comment]
Hi @kart1ka I have fixed the issue and the suggested coderabbitai changes, can you please check

**Review by kart1ka — CHANGES_REQUESTED** [review]
Looks good to me! Before I approve, could you also add a test for the backend changes?

**Comment by husniabad** [comment]
Hi @kart1ka I have added the required tests for the disabled cancellation action, please check it out!

**Review by kart1ka — DISMISSED** [review]
LGTM! Thanks for your contributions.

**Comment by husniabad** [comment]
> LGTM! Thanks for your contributions.

Thank you @kart1ka for the review and approval. I appreciate your time.

File: apps/web/components/booking/BookingListItem.tsx [hunk 2]
```diff
@@ -686,19 +686,43 @@ function BookingListItem(booking: BookingItemProps) {
...
-                        data-testid={cancelEventAction.id}
-                        className={cancelEventAction.disabled ? "text-muted" : undefined}>
-                        {cancelEventAction.label}
-                      </DropdownItem>
+                      disabled={cancelEventAction.disabled && !isBookingInPast}
+                      onSelect={
+                        cancelEventAction.disabled && isBookingInPast ? (e) => e.preventDefault() : undefined
+                      }>
+                      {cancelEventAction.disabled && isBookingInPast ? (
+                        <Tooltip content={t("cannot_cancel_booking")}>
```
Comment (anikdhabal) [inline apps/web/components/booking/BookingListItem.tsx]: Let's keep it simple. Let's disable it instead of doing so many changes here. And we already tackled it inside booking Actions

File: packages/platform/examples/base/src/pages/[bookingUid].tsx [hunk 3]
```diff
@@ -27,6 +27,7 @@ export default function Bookings(props: { calUsername: string; calEmail: string
     const year = dayjs(booking?.start).year();
     const day = dayjs(date).format("dddd");
     const month = dayjs(date).format("MMMM");
+    const isBookingInPast = booking?.end ? dayjs(booking?.end).isBefore(dayjs()) : false;
```
Comment (anikdhabal) [inline packages/platform/examples/base/src/pages/[bookingUid].tsx]: Is it related? Let tackle it later

File: packages/features/bookings/lib/handleCancelBooking.ts [hunk 4]
```diff
@@ -120,6 +120,14 @@ async function handler(input: CancelBookingInput) {
     });
   }
 
+  // Block cancellation attempts for bookings that have already ended
```
Comment (anikdhabal) [inline packages/features/bookings/lib/handleCancelBooking.ts]: Remove Commet, as it is understandable from the code

File: apps/web/modules/bookings/views/bookings-single-view.tsx [hunk 5]
```diff
@@ -814,7 +814,8 @@ export default function Success(props: PageProps) {
                       (!needsConfirmation || !userIsOwner) &&
                       isReschedulable &&
                       !isRerouting &&
-                      canCancelOrReschedule &&
+                      ((!isBookingInPast && canCancelOrReschedule) ||
+                        ((!isBookingInPast || eventType.allowReschedulingPastBookings) && canReschedule)) &&
```
Comment (anikdhabal) [inline apps/web/modules/bookings/views/bookings-single-view.tsx]: It's not needed; our aim is to hide the cancel button. And we already tackling it

**Review by anikdhabal — DISMISSED** [review]
Looks good

**Review by anikdhabal — APPROVED** [review]

**Review by volnei — APPROVED** [review]
