### PR TITLE
fix: Transform Google API Key [CAL-1749]

### LINKED ISSUE #9079: [CAL-1749] Adding gCal via /admin/apps fails when parsing back
* As an admin on a new install, enable via Google Calendar via admin UI in  `/settings/admin/apps`
* As a non-admin user, install Google Calendar
* Calendars on /apps/installed never finish loading

This is the error in the console

The issue it that when we're saving `redirect_uris` we save it as a string when it should be an array of strings.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1749](https://linear.app/calcom/issue/CAL-1749/adding-gcal-via-adminapps-fails-when-parsing-back)</sub>

### PR DESCRIPTION
**Pull request by joeauyeung**
## What does this PR do?

This PR fixes when an admin is adding API credentials in the "Apps" section of the admin settings for GCal, it will parse the `redirect_uris` to an array of strings.

Fixes #9079 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Remove current Google Calendar (GCal) API keys from the database
- As an admin go to the "Apps" section under settings
- Add your valid Google API credentials
    - In your DB under GCal keys, `redirect_uris` should be an array
- Test this by adding a GCal to your account

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/app-store/googlecalendar/zod.ts [hunk 1]
```diff
@@ -5,5 +5,11 @@ export const appDataSchema = z.object({});
 export const appKeysSchema = z.object({
   client_id: z.string().min(1),
   client_secret: z.string().min(1),
-  redirect_uris: z.string().min(1),
+  redirect_uris: z.union([
+    z.string().url().array(),
+    z
+      .string()
+      .url()
+      .transform((url) => [url]),
```
Comment (joeauyeung) [inline packages/app-store/googlecalendar/zod.ts:13]: When submitting keys, we parse the input so it would automatically transform the `redirect_uris` to an array. So we either accept an array or a single string and transform it into an array.

**Review by emrysal — APPROVED** [review]
looking good
