### PR TITLE
fix: Broken 2 Factor Authentication

### LINKED ISSUE #9138: [CAL-1785] 2 Factor Authentication not working
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1785](https://linear.app/calcom/issue/CAL-1785/2-factor-authentication-not-working)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #9138
Regression from https://github.com/calcom/cal.com/pull/9020

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [x] Enable 2 Factor auth in pro account and try to sign into it.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: apps/web/pages/auth/login.tsx [hunk 1]
```diff
@@ -51,15 +51,17 @@ export default function Login({
...
-  });
+  const formSchema = z
+    .object({
+      email: z
+        .string()
+        .min(1, `${t("error_required_field")}`)
+        .email(`${t("enter_valid_email")}`),
+      password: z.string().min(1, `${t("error_required_field")}`),
+    })
+    // Passthrough other fields like totpCod
```
Comment (hariombalhara) [inline apps/web/pages/auth/login.tsx:62]:
```suggestion
    // Passthrough other fields like totpCode
```

**Comment by hariombalhara** [comment]
We need a 2 factor auth test to avoid this in future.

**Review by alishaz-polymath — APPROVED** [review]
🚀
