### PR TITLE
fix: Remove the right date override on removal

### LINKED ISSUE #13766: [CAL-3169] Wrong override being deleted
Wrong override being deleted  [https://www.loom.com/share/7eba7db6755742bab76f2a8bfc509a05https://www.loom.com/share/7eba7db6755742bab76f2a8bfc509a05](https://www.loom.com/share/7eba7db6755742bab76f2a8bfc509a05https://www.loom.com/share/7eba7db6755742bab76f2a8bfc509a05)

Created via Threads. See full discussion: [https://threads.com/messages/36061128-87fb-48a0-b9c1-fd67f9507c06?messageID=6c7ab873-5faf-4465-90d1-af2444f16da1](https://threads.com/messages/36061128-87fb-48a0-b9c1-fd67f9507c06?messageID=6c7ab873-5faf-4465-90d1-af2444f16da1)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3169](https://linear.app/calcom/issue/CAL-3169/wrong-override-being-deleted)</sub>

### PR DESCRIPTION
**Pull request by emrysal**
## What does this PR do?

* Fixes translations on the Weekday in the date override listing
* Deletes the right list item on delete
* Adds test to verify the delete behaviour
* Further tests to add verify text display client-side.

### CODE REVIEW

File: apps/web/pages/availability/[schedule].tsx [hunk 1]
```diff
@@ -83,11 +101,88 @@ const DateOverride = ({ workingHours }: { workingHours: WorkingHours[] }) => {
...
+}) => {
+  const { t } = useLocale();
+  const router = useRouter();
+  const utils = trpc.useUtils();
+  const { isPending, mutate } = trpc.viewer.availability.schedule.delete.useMutation({
+    onError: (err) => {
+      if (err instanceof HttpError) {
+        const message = `${err.statusCode}: ${err.message}`;
+        showToast(message, "error");
+      }
```
Comment (Udit-takkar) [inline apps/web/pages/availability/[schedule].tsx:123]: err could also be of type TRPCClientError. there is no toast message in case of Trpc error.

File: apps/web/playwright/availability.e2e.ts [hunk 2]
```diff
@@ -40,6 +40,51 @@ test.describe("Availablity tests", () => {
...
+
+    // always go to the next month so there's enough slots regardless of current time.
+    await page.getByTestId("incrementMonth").click();
+
+    await page.locator('[data-testid="day"][data-disabled="false"]').nth(2).click();
+    await page.getByTestId("date-override-mark-unavailable").click();
+    await page.getByTestId("add-override-submit-btn").click();
+    await page.getByTestId("dialog-rejection").click();
+
+    const dateOverrideList = page.locator('[data-testid="date-overrides-list"] > li');
```
Comment (Udit-takkar) [inline apps/web/playwright/availability.e2e.ts:70]: no await here ?

**Review by Udit-takkar — COMMENTED** [review]
Works fine. Just left some comments

File: apps/web/pages/availability/[schedule].tsx (hunk 1 above)
Comment (zomars) [reply apps/web/pages/availability/[schedule].tsx:123]: Made some fixes

File: apps/web/pages/availability/[schedule].tsx [hunk 3]
```diff
@@ -83,11 +102,85 @@ const DateOverride = ({ workingHours }: { workingHours: WorkingHours[] }) => {
...
+  disabled?: boolean;
+  onDeleteConfirmed?: () => void;
+  buttonClassName: string;
+  scheduleId: number;
+}) => {
+  const { t } = useLocale();
+  const router = useRouter();
+  const utils = trpc.useUtils();
+  const { isPending, mutate } = trpc.viewer.availability.schedule.delete.useMutation({
+    onError: withErrorFromUnknown((err) => {
```
Comment (zomars) [inline apps/web/pages/availability/[schedule].tsx:120]: Added this helper if you don't mind @emrysal

File: packages/lib/getClientErrorFromUnknown.ts
Comment (zomars) [inline packages/lib/getClientErrorFromUnknown.ts:1]: cc @emrysal

**Review by zomars — DISMISSED** [review]

**Review by zomars — APPROVED** [review]
