### PR TITLE
fix: guess correct timezone when onboarding

### LINKED ISSUE #6383: [CAL-743] Set-up Wizard not pulling correct timezone
When creating a new account, the timezone presented is "London," even when the user is not in London. If the user leaves the timezone as London, and then goes through the flow, when they finish the flow, they are prompted to change their timezone to the correct timezone. In my case, it was "LA"

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-743](https://linear.app/calcom/issue/CAL-743/set-up-wizard-not-pulling-correct-timezone)</sub>

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

Fixes #6383

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

File: apps/web/components/getting-started/steps-views/UserSettings.tsx [hunk 1]
```diff
@@ -19,7 +19,8 @@ interface IUserSettingsProps {
 const UserSettings = (props: IUserSettingsProps) => {
   const { user, nextStep } = props;
   const { t } = useLocale();
-  const [selectedTimeZone, setSelectedTimeZone] = useState(user.timeZone ?? dayjs.tz.guess());
+  const [selectedTimeZone, setSelectedTimeZone] = useState(dayjs.tz.guess());
```
Comment (G3root) [inline apps/web/components/getting-started/steps-views/UserSettings.tsx:22]: Default value of timezone is "London" so it is removed.

File: apps/web/pages/getting-started/[[...step]].tsx [hunk 2]
```diff
@@ -178,6 +178,10 @@ export const getServerSideProps = async (context: GetServerSidePropsContext) =>
     throw new Error("User from session not found");
   }
 
+  if (user.completedOnboarding) {
```
Comment (G3root) [inline apps/web/pages/getting-started/[[...step]].tsx:181]: redirect if the user is onboarded to prevent incorrect value in selected timezone.

**Review by emrysal — APPROVED** [review]
Works, LGTM
