### PR TITLE
fix: Add Guests dialog for Bookings

### LINKED ISSUE #21663: in local development tab fri=ezze and errored
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. setup local project
2. go to bookings then edit->add guests
3. in console infinite error poping up and whole page got stuck.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- page should not stuck made give warning not errors or limit them

### Expected Results

- This is an ideal result that the system should get after the tests are performed

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.
tested in chrome and safari
using Mac
### Evidence

Image

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

### PR DESCRIPTION
**Pull request by nerdberg792**
# Fix Infinite Rendering on Add Guests for Bookings 

* Fixes #21663
* Fixes CAL-5885

This PR fixes an issue encountered when going to the booking and clicking on add guests triggers infinite re-renders . 

The fix involves changing the multiMail component in AddGuestsDialog.tsx . 
In the cal.com/packages/ui/components/address/index.ts file : 
**Before:**
```
export { default as AddressInput } from "./AddressInputLazy";
export { default as MultiEmail } from "./MultiEmaiLazyl";
export { default as AddressInputNonLazy } from "./AddressInput";
```

**After:**
```
export { default as AddressInput } from "./AddressInputLazy";
export { default as MultiEmail } from "./MultiEmail";
export { default as AddressInputNonLazy } from "./AddressInput";

```

## Visual Demo (For contributors especially)
Video

https://github.com/user-attachments/assets/44733c39-724e-4f60-a655-fe03a4bd9e62

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a documentation change. If N/A, write N/A here and check the checkbox. **N/A**
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

*Login 
* Go to bookings 
* On an existing booking click on edit 
* Click on add guests 
* no error smooth execution 

### Notes:
* No additional environment variables are required.
* No specific test data is needed beyond a standard setup.

    

---

## Summary by cubic
Fixed an infinite re-render issue when adding guests to a booking by updating the MultiEmail import in the AddGuests dialog.

### CODE REVIEW

**Review by eunjae-lee — DISMISSED** [review]
Hi @nerdberg792 Thanks for the work. I see this change fixes the issue, but I wonder if you could dive a bit deeper and see if there's a root cause to this issue, and if it's somehow possible to fix it without replacing MultiEmailLazy with MultiEmail?

**Comment by nerdberg792** [comment]
> Hi @nerdberg792 Thanks for the work. I see this change fixes the issue, but I wonder if you could dive a bit deeper and see if there's a root cause to this issue, and if it's somehow possible to fix it without replacing MultiEmailLazy with MultiEmail?


Hey I have added some changes and now it even works with the Lazily loaded component 

btw I am interested in doing an internship w cal.com how can I reach out ? 

https://github.com/user-attachments/assets/b3eeec62-ea3f-4a9b-914b-9ea7c73e4b78

File: packages/ui/components/address/MultiEmailLazy.tsx [hunk 1]
```diff
@@ -1,6 +1,9 @@
 import dynamic from "next/dynamic";
 
 /** These are like 40kb that not every user needs */
-const MultiEmail = dynamic(() => import("./MultiEmail")) as unknown as typeof import("./MultiEmail").default;
+const MultiEmail = dynamic(() => import("./MultiEmail"), {
+  loading: () => <div>Loading...</div>,
```
Comment (eunjae-lee) [inline packages/ui/components/address/MultiEmailLazy.tsx]:
```suggestion
```

**Review by eunjae-lee — APPROVED** [review]

**Comment by eunjae-lee** [comment]
@nerdberg792 we will soon have a page where you can apply. I will let you know.
