### PR TITLE
fix: Broken navigation after booking creation in some cases

### LINKED ISSUE #15426: [CAL-3929] Embed: Open success page in the `top` and not in the `parent`
Open success page in top instead of parent. It mostly does the same thing unless embed is inside another iframe on the webpage which restricts navigation(in which case top.location.href works but not parent.location.href)

More details in private link about the user who reported it [https://app.campsite.co/cal/posts/1giz24q8pif8](https://app.campsite.co/cal/posts/1giz24q8pif8)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3929](https://linear.app/calcom/issue/CAL-3929/embed-open-success-page-in-the-top-and-not-in-the-parent)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

- Fixes #15426 (GitHub issue number)

Loom -  https://www.loom.com/share/2a509de688d2417381305df85cd1c584

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [x] N/A I confirm automated tests are in place that prove my fix is effective or that my feature works.

Pretty small change. No automation tests needed.

### CODE REVIEW

**Comment by hariombalhara** [comment]
* **#15664** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/15664?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hariombalhara and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: packages/lib/navigateInTopWindow.ts [hunk 1]
```diff
@@ -0,0 +1,5 @@
+export const navigateInTopWindow = (url: string) => {
+  // In some weird unknown case, window.top.location could be null as per typescript. In such case, we still do the redirect but in same window
+  const location = window.top ? window.top.location : window.location;
+  location.href = url;
```
Comment (supalarry) [inline packages/lib/navigateInTopWindow.ts:4]: As discussed in campsite, the problem is because our iframe with src=app.cal.com is nested in another iframe with src=xyz.com that is used on xyz.com domain page.

That means that our iframe is a cross-origin iframe - xyz.com loads iframe from app.cal.com, which means that `window.top` will be defined, but `window.top.location` is not accessible to cross-origin iframes, so our iframe won't have access to it and trying to access it might result in error.

So we need to update the check:
```
export const navigateInTopWindow = (url: string) => {
  try {
    if (window.top && window.top.location) {
      window.top.location.href = url;
    } else {
      window.location.href = url;
    }
  } catch (error) {
    window.location.href = url;
  }
};
```

**Review by supalarry — CHANGES_REQUESTED** [review]
Because our iframe is a cross-origin iframe, looks like we need to adjust the `navigateInTopWindow` function.

File: packages/lib/navigateInTopWindow.ts (hunk 1 above)
Comment (supalarry) [reply packages/lib/navigateInTopWindow.ts:4]: Cal iframe being cross-origin in the first place was the reason that `window.parent.location.href` was giving permission error:

Screenshot 2024-07-08 at 10 56 23

which is why when embed is used outside app.cal.com (which i guess is 100% of the times) we can only use `window.location.href` to only redirect the cal iframe itself, not the whole parent page, which as i understand is not possible.

Comment (supalarry) [reply packages/lib/navigateInTopWindow.ts:4]: Interesting, appreciate the loom and PR looks good !

**Review by supalarry — APPROVED** [review]
