### PR TITLE
fix: show email in outlook

### LINKED ISSUE #5836: [CAL-525] Installed Apps / Outlook Calendar - Connected calendar not showing email address
Currently shows:

Should show the email address?

Related

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-525](https://linear.app/calcom/issue/CAL-525/installed-apps-outlook-calendar-connected-calendar-not-showing-email)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
Fixes: https://github.com/calcom/cal.com/issues/5836

Screenshot 2022-12-06 at 5 44 17 PM

### CODE REVIEW

**Comment by mocherfaoui** [comment]
hey @Udit-takkar, I think using `owner.address` as an `externalId` will create issues with existing/new calendars connected to that email because `externalId` is used to know the destination calendar. So it will consider all the connected Outlook calendars as destination calendars, you can see "Adding events to" next to all Outlook calendars

**Comment by Udit-takkar** [comment]
@mocherfaoui  okay will make some changes to fix this.

**Comment by PeerRich** [comment]
hey @Udit-takkar whats missing so this leaves draft? looks good to me

**Comment by Udit-takkar** [comment]
@PeerRich  i would just have to test once with multiple outlook accounts connected.

File: packages/features/calendars/DestinationCalendarSelector.tsx [hunk 1]
```diff
@@ -102,7 +102,9 @@ const DestinationCalendarSelector = ({
     query.data.connectedCalendars.map((selectedCalendar) => ({
       key: selectedCalendar.credentialId,
       label: `${selectedCalendar.integration.title?.replace(/calendar/i, "")} (${
-        selectedCalendar.primary?.name
+        selectedCalendar.primary?.integration === "office365_calendar"
```
Comment (Udit-takkar) [inline packages/features/calendars/DestinationCalendarSelector.tsx:105]: Screenshot 2022-12-13 at 8 03 08 PM

this will also display email in the options

**Comment by Udit-takkar** [comment]
@joeauyeung can you review this PR?

File: apps/web/components/apps/CalendarListContainer.tsx [hunk 2]
```diff
@@ -168,7 +168,11 @@ function ConnectedCalendarsList(props: Props) {
                     slug={item.integration.slug}
                     title={item.integration.title}
                     logo={item.integration.logo}
-                    description={item.primary?.externalId || "No external Id"}
+                    description={
+                      (item.primary?.integration === "office365_calendar"
+                        ? item.primary?.email
+                        : item.primary?.externalId) ?? "No external Id"
```
Comment (PeerRich) [inline apps/web/components/apps/CalendarListContainer.tsx:174]: Do we wanna show just an untranslated english string: "No external Id" here? we can also just not show a description if there is none

File: packages/app-store/googlecalendar/lib/CalendarService.ts [hunk 3]
```diff
@@ -372,6 +372,7 @@ export default class GoogleCalendarService implements Calendar {
                 name: cal.summary ?? "No name",
                 primary: cal.primary ?? false,
                 readOnly: !(cal.accessRole === "reader" || cal.accessRole === "owner") && true,
+                email: cal.id ?? "No Email",
```
Comment (PeerRich) [inline packages/app-store/googlecalendar/lib/CalendarService.ts:375]: same here. do we wanna show "No Email"? or is this a non-visible error?

File: packages/app-store/larkcalendar/lib/CalendarService.ts [hunk 4]
```diff
@@ -319,6 +319,7 @@ export default class LarkCalendarService implements Calendar {
             integration: this.integrationName,
             name: cal.summary_alias || cal.summary || "No calendar name",
             primary: cal.type === "primary",
+            email: cal.calendar_id ?? "No Email",
```
Comment (PeerRich) [inline packages/app-store/larkcalendar/lib/CalendarService.ts:322]: same here

File: packages/app-store/larkcalendar/lib/CalendarService.ts [hunk 5]
```diff
@@ -339,6 +340,7 @@ export default class LarkCalendarService implements Calendar {
           integration: this.integrationName,
           name: cal.summary_alias || cal.summary || "No calendar name",
           primary: cal.type === "primary",
+          email: cal.calendar_id ?? "No Email",
```
Comment (PeerRich) [inline packages/app-store/larkcalendar/lib/CalendarService.ts:343]: same here

File: packages/app-store/office365calendar/lib/CalendarService.ts [hunk 6]
```diff
@@ -189,6 +189,7 @@ export default class Office365CalendarService implements Calendar {
         name: cal.name ?? "No calendar name",
         primary: cal.isDefaultCalendar ?? false,
         readOnly: !cal.canEdit && true,
+        email: cal.owner?.address ?? "No Address",
```
Comment (PeerRich) [inline packages/app-store/office365calendar/lib/CalendarService.ts:192]: same here with "No Address"

**Review by PeerRich — COMMENTED** [review]
left comments

File: apps/web/components/apps/CalendarListContainer.tsx (hunk 2 above)
Comment (Udit-takkar) [reply apps/web/components/apps/CalendarListContainer.tsx:174]: yeah we can show description but user won't be able to differentiate between multiple account ( like gmail).

File: packages/app-store/googlecalendar/lib/CalendarService.ts (hunk 3 above)
Comment (Udit-takkar) [reply packages/app-store/googlecalendar/lib/CalendarService.ts:375]: didn't find a response where cal.id ( email) is not being passed. "No Email" is just to make sure email type is string just like  name: cal.summary ?? "No name",

File: apps/web/components/apps/CalendarListContainer.tsx (hunk 2 above)
Comment (joeauyeung) [reply apps/web/components/apps/CalendarListContainer.tsx:174]: Can we move this logic to the app specific `listCalendars` call? I think this will help prevent future tech debt.

**Review by joeauyeung — COMMENTED** [review]
For Outlook, it's still not showing the most accurate email. It should be the email being used to connect Cal.
image

**Comment by Udit-takkar** [comment]
@joeauyeung idk why you are getting wrong email. let me check the docs once again.

**Comment by Udit-takkar** [comment]
@joeauyeung i now used another endpoint /me to get email address. can you try once again now ?

**Review by joeauyeung — APPROVED** [review]

File: packages/app-store/googlecalendar/lib/CalendarService.ts (hunk 3 above)
Comment (joeauyeung) [reply packages/app-store/googlecalendar/lib/CalendarService.ts:375]: Could we render an empty string then not to cause confusion?

Comment (Udit-takkar) [reply packages/app-store/googlecalendar/lib/CalendarService.ts:375]: ok . everywhere right?

Comment (Udit-takkar) [reply packages/app-store/googlecalendar/lib/CalendarService.ts]: done

**Review by joeauyeung — APPROVED** [review]
LGTM
