### PR TITLE
fix: create event type refresh bug

### LINKED ISSUE #16070: [CAL-4105] EventTypeInfiniteScroll Bug - When entire list is loaded(with multiple pages), creating an event-type resets the entire list.
When entire list is loaded, at that moment creating an event-type still resets the entire list and shows only the last page

_Originally posted by @hariombalhara in https://github.com/calcom/cal.com/issues/15949#issuecomment-2268586486_
            

<sub>[CAL-4105](https://linear.app/calcom/issue/CAL-4105/eventtypeinfinitescroll-bug-when-entire-list-is-loadedwith-multiple)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

- Fixes https://github.com/calcom/cal.com/issues/16070
- Fixes CAL-4105 (Linear issue number - should be visible at the bottom of the GitHub issue description)

1) 

https://github.com/user-attachments/assets/b8d60bd5-9281-4cb9-bd32-1c0e2f2ccf5d

2)

https://github.com/user-attachments/assets/4f0c0136-61f5-48fc-a527-6d7e393a526a

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] N/A I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

1) set isInfiniteScrollEnabled = true in L1623 in apps/web/modules/event-types/views/event-types-listing-view.tsx
2) Create a new event type

### CODE REVIEW

File: apps/web/modules/event-types/views/event-types-listing-view.tsx [hunk 1]
```diff
@@ -170,7 +170,8 @@ const InfiniteMobileTeamsTab: FC<InfiniteMobileTeamsTabProps> = (props) => {
     },
     {
       refetchOnWindowFocus: true,
-      staleTime: 1 * 60 * 60 * 1000,
+      refetchOnMount: true,
+      staleTime: 0,
```
Comment (Udit-takkar) [inline apps/web/modules/event-types/views/event-types-listing-view.tsx:174]: Need this to render new event type when user clicks back from event type and doesn't reload.

**Comment by CarinaWolli** [comment]
type check if failing, can you take a look please 🙏

**Review by CarinaWolli — APPROVED** [review]
Tested an works as expected 👍
