### PR TITLE
fix: add team model in prisma middleware

### LINKED ISSUE #3940: description missing on team events
CleanShot 2022-08-24 at 13 51 57@2x

even tho it's added:

CleanShot 2022-08-24 at 13 52 23@2x

### PR DESCRIPTION
**Pull request by Udit-takkar**
Fixes: #3940 
There were some changes made in prisma middleware to sanitise event description. user event type description were handled but /team/slug/type was using different query.  

Screenshot 2022-08-24 at 10 18 56 PM

### CODE REVIEW

File: packages/prisma/middleware/eventTypeDescriptionParseAndSanitize.ts [hunk 1]
```diff
@@ -20,7 +20,20 @@ function parseAndSanitize(description: string) {
...
+      const result = await next(params);
+      if (result?.eventTypes) {
+        const eventTypes = result.eventTypes;
+        const results = Array.isArray(eventTypes) ? eventTypes : [eventTypes];
+        const parsedResults = results.map((record) => ({
+          ...record,
+          descriptionAsSafeHTML: record.description ? parseAndSanitize(record.description) : null,
+        }));
+        /* If the original result was an array, return the parsed array, otherwise is a single record */
+        result.eventTypes = Array.isArray(eventTypes) ? parsedResults : parsedResults[0];
```
Comment (zomars) [inline packages/prisma/middleware/eventTypeDescriptionParseAndSanitize.ts:33]: Instead of duplicating this code, let's extract this logic into a reusable function and use it on both models

**Review by zomars — CHANGES_REQUESTED** [review]
Nice catch! Let's address some issues first tho 🙏🏽

File: packages/prisma/middleware/eventTypeDescriptionParseAndSanitize.ts (hunk 1 above)
Comment (Udit-takkar) [reply packages/prisma/middleware/eventTypeDescriptionParseAndSanitize.ts:33]: got it

**Review by zomars — APPROVED** [review]
Thank you for your contribution 🙏

File: packages/prisma/middleware/eventTypeDescriptionParseAndSanitize.ts [hunk 2]
```diff
@@ -14,22 +14,32 @@ function parseAndSanitize(description: string) {
   return parsedMarkdown;
 }
 
+function getParsedResults(eventTypes) {
```
Comment (zomars) [inline packages/prisma/middleware/eventTypeDescriptionParseAndSanitize.ts:17]: Let's type this correctly
image

**Review by zomars — CHANGES_REQUESTED** [review]

File: packages/prisma/middleware/eventTypeDescriptionParseAndSanitize.ts (hunk 2 above)
Comment (Udit-takkar) [reply packages/prisma/middleware/eventTypeDescriptionParseAndSanitize.ts]: done

**Comment by zomars** [comment]
Thank you for your contribution 🙏
