### PR TITLE
fix/availability-tz-offset

### LINKED ISSUE #3184: Slots availability not working for some timezones
Found a bug? Please fill out the sections below. 👍

### Issue Summary
There are rare cases when availability it's not being displayed correctly for some timezones.

clipboard1

clipboard1

### Steps to Reproduce

1. Availability for owner 9am-5pm in America/Chihuahua timezone
2. Go to any 60min long event for the owner account, change timezone to Europe/Belgrade
3. Sunday is being displayed as available but no slots appear, when Saturday it's displayed as not available but has slots inside of it if you go to that date via url.

Found by @zomars

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

Changes yyyymmdd(dayjs.toDate()) for a simplified dayjs.format(YYYY-MM-DD), since doing .toDate() always returns localised time and ignores any tz in the Date object. This was generating a conflict between doing .toDate() on server (UTC) and client .toDate() to user's selected TZ on input.

Fixes #3184

**Environment**: Staging(main branch) and Production

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
1. Setup an availability like this image -> https://user-images.githubusercontent.com/4461358/176308580-aeba174d-3db5-428d-abe3-b9ae5c3f4b37.png
2. Go to any 60min long event for the owner account, change timezone to Europe/Belgrade
3. Slots should display accordingly.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

File: apps/web/components/booking/pages/AvailabilityPage.tsx [hunk 1]
```diff
@@ -125,8 +124,8 @@ const useSlots = ({
       {
         eventTypeId,
         startTime: startTime?.toISOString() || "",
-        timeZone,
         endTime: endTime?.toISOString() || "",
+        timeZone,
```
Comment (alannnc) [inline apps/web/components/booking/pages/AvailabilityPage.tsx:128]: Just ordering parameters in object to have both startDate and endDate together.

File: apps/web/components/booking/pages/AvailabilityPage.tsx [hunk 2]
```diff
@@ -224,7 +222,7 @@ const SlotPicker = ({
       {selectedDate && (
         <AvailableTimes
           isLoading={isLoading}
-          slots={slots[yyyymmdd(selectedDate.toDate())]}
+          slots={slots[selectedDate.format("YYYY-MM-DD")]}
```
Comment (alannnc) [inline apps/web/components/booking/pages/AvailabilityPage.tsx:225]: Doing toDate() here returned client time locale and didn't match with what our server returned

File: apps/web/lib/slots.ts [hunk 3]
```diff
@@ -41,7 +41,8 @@ const getSlots = ({ inviteeDate, frequency, minimumBookingNotice, workingHours,
   const startOfDay = dayjs.utc().startOf("day");
   const startOfInviteeDay = inviteeDate.startOf("day");
   // checks if the start date is in the past
-  if (inviteeDate.isBefore(startDate, "day")) {
+
+  if (inviteeDate.isBefore(startDate, "hour")) {
```
Comment (alannnc) [inline apps/web/lib/slots.ts:45]: This was displaying a day as available as sometimes difference between two dates is < 24 hrs. But when doing timezones a available day for a owner can be 2 days available in other users tz.

File: apps/web/server/routers/viewer/slots.tsx [hunk 4]
```diff
@@ -198,8 +198,8 @@ export const slotsRouter = createRouter().query("getSchedule", {
         periodDays: eventType.periodDays,
       });
 
-    // AFAIK startTime and endTime already have timezone info on them
-    let time = dayjs(startTime);
+    let time = input.timeZone === "Etc/GMT" ? startTime.utc() : startTime.tz(input.timeZone);
```
Comment (alannnc) [inline apps/web/server/routers/viewer/slots.tsx:201]: @zomars Alex change here was right, as the timezone it's only being received in the input.

File: apps/web/server/routers/viewer/slots.tsx [hunk 5]
```diff
@@ -223,7 +222,7 @@ export const slotsRouter = createRouter().query("getSchedule", {
           )
         );
 
-      slots[yyyymmdd(time.toDate())] = filteredTimes.map((time) => ({
+      slots[time.format("YYYY-MM-DD")] = filteredTimes.map((time) => ({
```
Comment (alannnc) [inline apps/web/server/routers/viewer/slots.tsx:225]: Doing plain format to display available days for the input tz received.

**Review by zomars — APPROVED** [review]
Let's just fix the tests

File: apps/web/lib/slots.ts [hunk 6]
```diff
@@ -41,6 +41,13 @@ const getSlots = ({ inviteeDate, frequency, minimumBookingNotice, workingHours,
   const startOfDay = dayjs.utc().startOf("day");
   const startOfInviteeDay = inviteeDate.startOf("day");
   // checks if the start date is in the past
+
+  /**
+   *  TODO: change "day" for "hour" to stop displaying 1 day before today
+   * This is displaying a day as available as sometimes difference between two dates is < 24 hrs.
+   * But when doing timezones an available day for an owner can be 2 days available in other users tz.
+   *
+   * */
```
Comment (alannnc) [inline apps/web/lib/slots.ts:50]: Initially changed day for hours, since it was displaying an empty day as available. Had to revert it since test was failing because of this change. Test needs more investigation.

**Review by hariombalhara — COMMENTED** [review]
I can confirm that it fixes the issue locally. I see another error(hydration related), but that might not actually impact users. So, approving it and will track that error separately.

**Review by hariombalhara — APPROVED** [review]
