### PR TITLE
fix: Transform # character to - in slug

### LINKED ISSUE #10443: [CAL-2271] Can create event type with # in the slug, page visit = 404
image

<sub>[CAL-2271](https://linear.app/calcom/issue/CAL-2271/possible-to-create-an-event-type-with-a-in-the-slug-page-visit-=-404)</sub>

### PR DESCRIPTION
**Pull request by ujwalkumar1995**
## What does this PR do?

In slugs, # character was not being replaced by - which could lead to 404 page not found. Fixed this issue as part of this PR.

Fixes #10443 

https://github.com/calcom/cal.com/assets/20976813/6519d3b2-36ba-4fdf-8bc9-38a8a6685df3

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

Try to create an event type with # in the name. # will be replaced by -.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

I noticed couple of things as part of this change. Have added my observations as comments in the PR review section for better understanding.

### CODE REVIEW

File: packages/lib/slugify.ts [hunk 1]
```diff
@@ -5,10 +5,9 @@ export const slugify = (str: string) => {
     .normalize("NFD") // Normalize to decomposed form for handling accents
     .replace(/\p{Diacritic}/gu, "") // Remove any diacritics (accents) from characters
     .replace(/[^\p{L}\p{N}\p{Zs}\p{Emoji}]+/gu, "-") // Replace any non-alphanumeric characters (including Unicode) with a dash
-    .replace(/[\s_]+/g, "-") // Replace whitespace and underscores with a single dash
+    .replace(/[\s_#]+/g, "-") // Replace whitespace, # and underscores with a single dash
     .replace(/^-+/, "") // Remove dashes from start
-    .replace(/-+$/, "") // Remove dashes from end
-    .replace(/\+/g, "-"); // Transform all + to -
```
Comment (ujwalkumar1995) [inline packages/lib/slugify.ts:11]: This was not required as + was already being replaced as part of 'Replace any non-alphanumeric characters (including Unicode) with a dash' regex.
Have verified and added tests for it.

File: packages/lib/slugify.ts [hunk 2]
```diff
@@ -5,10 +5,9 @@ export const slugify = (str: string) => {
     .normalize("NFD") // Normalize to decomposed form for handling accents
     .replace(/\p{Diacritic}/gu, "") // Remove any diacritics (accents) from characters
     .replace(/[^\p{L}\p{N}\p{Zs}\p{Emoji}]+/gu, "-") // Replace any non-alphanumeric characters (including Unicode) with a dash
```
Comment (ujwalkumar1995) [inline packages/lib/slugify.ts:7]: I verified this regex, it should not have ideally allowed # character. I am not sure why it is doing so. Therefore had to add an explicit check to replace # character

**Review by Udit-takkar — APPROVED** [review]
LGTM. works fine now
