### PR TITLE
fix: add inline color in og image

### LINKED ISSUE #11219: Remove or replace text-emphasis from OG images
Found a bug? Please fill out the sections below. 👍

### Issue Summary

It seems like `text-emphasis` is not available in tailwind at the edge (where the OG images are being generated)

image

We should either include or remove those classnames.

https://github.com/calcom/cal.com/blob/main/packages/lib/OgImages.tsx#L142

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/11219

https://github.com/calcom/cal.com/pull/11226/files#r1320105537

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/lib/OgImages.tsx [hunk 1]
```diff
@@ -139,7 +139,11 @@ export const Meeting = ({ title, users = [], profile }: MeetingImageProps) => {
       <div tw="h-full flex flex-col justify-start">
         <div tw="flex items-center justify-center" style={{ fontFamily: "cal", fontWeight: 300 }}>
           <img src={`${CAL_URL}/${LOGO}`} width="350" alt="Logo" />
-          {avatars.length > 0 && <div tw="font-bold text-[92px] mx-8 bottom-2">/</div>}
+          {avatars.length > 0 && (
+            <div style={{ color: "#111827" }} tw="font-bold text-[92px] mx-8 bottom-2">
```
Comment (Udit-takkar) [inline packages/lib/OgImages.tsx:143]: color: #11827 is text-emphasis

**Review by PeerRich — APPROVED** [review]
