### PR TITLE
fix: change localhost:3000 to Gitpod workspace URL

### LINKED ISSUE #10391: Gitpod instance uses localhost:3000 as NEXT_PUBLIC_WEBAPP_URL when in an external tab
### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.
After creating an instance on Gitpod and opening the preview in a new tab (outside of Gitpod), clicking signup/login... will redirect you to localhost:3000 when it should be that Gitpod instance's URL. This is only applicable if you open it in a separate tab.
If you open it on that same Gitpod tab, you will be redirected to a blank grey page, and for it to work correctly, you need to reload the tab with the preview (not the entire Gitpod tab).

### Steps to Reproduce

1. Create a Gitpod instance of the project
2. Sign up for a new account or log in to your account after opening the link in a new tab
3. You should be redirected to localhost:3000 as shown in the BEB recording below

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
This is not a critical bug but should improve the developer experience for people wanting to contribute through Gitpod.

### Actual Results

- After signing up or logging in from a new tab (while running your project on Gitpod), you will be using localhost:3000 which is not the NEXT_PUBLIC_WEBAPP_URL for Gitpod projects.

### Expected Results

- Use Gitpod's assigned URL instead of localhost

### Technical details

- Browser version: Brave [Version 1.56.11 Chromium: 115.0.5790.102 (Official Build) (64-bit)](https://brave.com/latest/)
- Bird Eats Bug Recording: [Click here](https://app.birdeatsbug.com/sessions/Fw2KePZr2yIJYhwwPojNCPACdnD7-TrPxigmY71TFzvx?networkPane=true)
- Node.js version: Gitpod's node version is v18.16.1

### Evidence

- Please check the Bird Eats Bug recording above

(This is my first issue here and I am still trying to get familiar with everything, so please excuse me if I misunderstood something.)

### PR DESCRIPTION
**Pull request by annleefores**
## What does this PR do?

Fixes #10391 

- Updates localhost:3000 to the Gitpod workspace URL in Gitpod.
- Added a fix for URL overflow on the signup page for multi-level subdomains, as shown below.

cal-gitpod-url-fix (2)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

Open in Gitpod, try signing up and signing in. Gets redirected to the correct Gitpod URL instead of localhost.

### CODE REVIEW

File: apps/web/pages/signup.tsx [hunk 1]
```diff
@@ -130,9 +130,8 @@ export default function Signup({ prepopulateFormValues, token, orgSlug }: Signup
                 <div className="space-y-4">
                   <TextField
                     addOnLeading={
-                      orgSlug
-                        ? getOrgFullDomain(orgSlug, { protocol: true })
-                        : `${process.env.NEXT_PUBLIC_WEBSITE_URL}/`
+                      orgSlug ? getOrgFullDomain(orgSlug, { protocol: false }) : subdomainSuffix()
+
                     }
```
Comment (PeerRich) [inline apps/web/pages/signup.tsx:135]: can you explain whats going on here?

Comment (annleefores) [reply apps/web/pages/signup.tsx:135]: Instead of displaying the entire Gitpod subdomain on the signup page, I used  `subdomainSuffix` in `orgDomains.ts` to get the root domain and display it as shown in the PR description.

Comment (PeerRich) [reply apps/web/pages/signup.tsx]: i would remove this here in this PR and only fix the gitpod file

**Review by PeerRich — APPROVED** [review]

File: apps/web/pages/signup.tsx (hunk 1 above)
Comment (annleefores) [reply apps/web/pages/signup.tsx]: Okay, thanks for taking care of that and merging the PR
