### PR TITLE
fix: update-stripe-presented-currency

### LINKED ISSUE #11374: [CAL-2471] Ability to change stripe currency to different from default.
This probably need some investigation but we should be able to change currency on stripe payment configuration.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2471](https://linear.app/calcom/issue/CAL-2471/ability-to-change-stripe-currency-to-different-from-default)</sub>

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

-  Allows for stripe edit currency to be presented in booking page, this also changes the charge currency but owners should only receive payouts in their available account supported currency.

Fixes #11374 

## Requirement/Documentation

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

## How should this be tested?

- Are there environment variables that should be set? No
- What are the minimal test data to have? Calcom account with installed stripe app and one event type linked.
- What is expected (happy path) to have (input and output)? Allow to edit stripe currency and only fallback to default_currency from account.
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- ~~I haven't added tests that prove my fix is effective or that my feature works~~

### CODE REVIEW

File: packages/app-store/stripepayment/lib/currencyConvertions.ts [hunk 1]
```diff
@@ -0,0 +1,37 @@
+/**
+ * Docs: https://stripe.com/docs/currencies#zero-decimal
+ * */
+const zeroDecimalCurrencies = [
```
Comment (alannnc) [inline packages/app-store/stripepayment/lib/currencyConvertions.ts:4]: Special cases where we shouldn't convert to * 100.

**Review by zomars — DISMISSED** [review]
Code LGTM. Can we provide testing evidence before merging?

**Comment by alannnc** [comment]
@zomars Simple test added

**Review by zomars — APPROVED** [review]
