### PR TITLE
fix: Make routing-form a preinstalled app

### LINKED ISSUE #9351: [CAL-1869] Make Routing Form a core component.
We are going to support creating a Routing Form for a team.

After that, it would require all team members to be able to access a Routing Form(even if the Routing Form App isn't installed by that user). 

So, it makes even more sense to move it to core now.  

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1869](https://linear.app/calcom/issue/CAL-1869/make-routing-form-a-core-component)</sub>

### LINKED ISSUE #10372: [CAL-2257] Orgs: Routing forms can't be installed for the Org.
We need to install Routing Forms by default for all orgs. Right now I can install Routing Forms for a team, but it still won't show up in my sidebar.

No other user will see the routing forms until they install it for themselves.

[39653e83-50cf-41b8-9902-70d065a6f5db](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/207d7193-e5eb-40c2-9de2-06ab089161a4/39653e83-50cf-41b8-9902-70d065a6f5db)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2257](https://linear.app/calcom/issue/CAL-2257/orgs-routing-forms-cant-be-installed-for-the-org)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #10372
Fixes #9351

Routing Forms is a Default app now, globally installed.
image

It will remain accessible at` /apps/routing-forms `but will be referred to as `/routing-forms` throughout the app.

[Demo Loom](https://www.loom.com/share/6d64832e8ff242a78b4aa338fa0be3ee)

## Type of change
- Improvement

## How should this be tested?
- See the loom
- You simply need to create a new account and you would see Routing Forms App preinstalled.
## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist
- I haven't checked if my changes generate no new warnings

### CODE REVIEW

File: packages/features/shell/Shell.tsx [hunk 1]
```diff
@@ -626,17 +622,9 @@ const Navigation = () => {
 };
 
 function useShouldDisplayNavigationItem(item: NavigationItemType) {
-  const { status } = useSession();
```
Comment (hariombalhara) [inline packages/features/shell/Shell.tsx:629]: No condition needed now.

File: packages/features/shell/Shell.tsx [hunk 2]
```diff
@@ -539,9 +539,7 @@ const navigation: NavigationItemType[] = [
     isCurrent: ({ router, item }) => {
       const path = router.asPath.split("?")[0];
       // During Server rendering path is /v2/apps but on client it becomes /apps(weird..)
-      return (
-        (path.startsWith(item.href) || path.startsWith("/v2" + item.href)) && !path.includes("routing-forms/")
```
Comment (hariombalhara) [inline packages/features/shell/Shell.tsx:543]: We would be accessing routing-forms as /routing-forms now instead of /apps/routing-forms

File: apps/web/next.config.js [hunk 3]
```diff
@@ -278,6 +278,10 @@ const nextConfig = {
           source: "/cancel/:path*",
           destination: "/booking/:path*",
         },
+        {
+          source: "/routing-forms/:slug*",
```
Comment (hariombalhara) [inline apps/web/next.config.js:282]: Routing Forms is now system app. So, allow accessing it directly. This also allows us to never have to move Routing Forms app outside AppStore unless needed for some other reason.

File: packages/app-store/routing-forms/config.json [hunk 4]
```diff
@@ -2,13 +2,15 @@
   "/*": "Don't modify slug - If required, do it using cli edit command",
   "name": "Routing Forms",
   "title": "Routing Forms",
+  "isGlobal": true,
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/config.json:5]: Make Routing Forms app preinstalled.

File: .github/workflows/e2e-app-store.yml [hunk 5]
```diff
@@ -39,4 +39,4 @@ jobs:
         uses: actions/upload-artifact@v2
         with:
           name: app-store-results-${{ matrix.shard }}_${{ strategy.job-total }}
-          path: app-store-results
+          path: test-results
```
Comment (hariombalhara) [inline .github/workflows/e2e-app-store.yml:42]: app-store-results isn't the correct path. CI isn't showing the artifacts for embed and app-store tests right now.

File: apps/web/middleware.ts [hunk 6]
```diff
@@ -76,15 +75,34 @@ const middleware: NextMiddleware = async (req) => {
   });
 };
 
+const routingForms = {
+  handle: (url: URL) => {
+    // Next.config.js Redirects don't handle Client Side navigations and we need that.
+    // So, we add the rewrite here instead.
+    if (url.pathname.startsWith("/routing-forms/")) {
+      url.pathname = url.pathname.replace(/^\/routing-forms\//, "/apps/routing-forms/");
```
Comment (hariombalhara) [inline apps/web/middleware.ts:83]: Made the replacement very specific using RegExp so that any other instance of `routing-forms `isn't replaced accidentally

File: apps/web/middleware.ts [hunk 7]
```diff
@@ -76,15 +75,34 @@ const middleware: NextMiddleware = async (req) => {
...
+    }
+
+    // Don't 404 old routing_forms links
+    if (url.pathname.startsWith("/apps/routing_forms")) {
+      url.pathname = url.pathname.replace(/^\/apps\/routing_forms\//, "/apps/routing-forms/");
+      return NextResponse.rewrite(url);
+    }
+  },
+  // Matcher paths that are required by the handle function to work
+  paths: ["/apps/routing_forms/:path*", "/routing-forms/:path*"],
```
Comment (hariombalhara) [inline apps/web/middleware.ts:94]: There shouldn't be many requests to these paths.
The path that would get the most traffic is the actual Routing Form publically available at /forms

File: apps/web/playwright/webhook.e2e.ts [hunk 8]
```diff
@@ -409,13 +409,6 @@ test.describe("FORM_SUBMITTED", async () => {
 
     await page.waitForLoadState("networkidle");
 
-    // Install Routing Forms App
-    await page.goto(`/apps/routing-forms`);
-    // eslint-disable-next-line playwright/no-conditional-in-test
-
-    await page.click('[data-testid="install-app-button"]');
-    await page.click('[data-testid="install-app-button-personal"]');
-
```
Comment (hariombalhara) [inline apps/web/playwright/webhook.e2e.ts:418]: No installation for Routing Form App needed now.

File: apps/web/playwright/webhook.e2e.ts [hunk 9]
```diff
@@ -428,7 +421,7 @@ test.describe("FORM_SUBMITTED", async () => {
     expect(page.locator(`text='${webhookReceiver.url}'`)).toBeDefined();
 
     await page.waitForLoadState("networkidle");
-    await page.goto("/apps/routing-forms/forms");
```
Comment (hariombalhara) [inline apps/web/playwright/webhook.e2e.ts:431]: Though this URL would still work, changed the reference to something that would be normally accessed.

File: packages/app-store/routing-forms/config.json [hunk 10]
```diff
@@ -2,17 +2,19 @@
...
   "slug": "routing-forms",
   "type": "routing-forms_other",
   "logo": "icon-dark.svg",
   "url": "https://cal.com/resources/feature/routing-forms",
   "variant": "other",
   "categories": ["automation"],
   "publisher": "Cal.com, Inc.",
+  "simplePath": "/routing-forms",
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/config.json:13]: See App.d.ts for definition

File: packages/app-store/routing-forms/playwright/tests/basic.e2e.ts [hunk 11]
```diff
@@ -17,7 +17,7 @@ test.describe("Routing Forms", () => {
 
       const formId = await addForm(page);
 
-      await page.click('[href="/apps/routing-forms/forms"]');
+      await page.click('[href*="/forms"]');
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/playwright/tests/basic.e2e.ts:20]: Made it to support both /apps and without /apps.

File: packages/app-store/routing-forms/playwright/tests/basic.e2e.ts [hunk 12]
```diff
@@ -183,11 +183,7 @@ test.describe("Routing Forms", () => {
         }
       );
       await user.apiLogin();
-      // Install app
-      await page.goto(`/apps/routing-forms`);
-      await page.click('[data-testid="install-app-button"]');
-      (await page.waitForSelector('[data-testid="install-app-button-personal"]')).click();
-      await page.waitForURL((url) => url.pathname === `/apps/routing-forms/forms`);
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/playwright/tests/basic.e2e.ts:190]: No installation for Routing Form App needed now.

File: packages/app-store/routing-forms/playwright/tests/basic.e2e.ts [hunk 13]
```diff
@@ -203,28 +199,17 @@ test.describe("Routing Forms", () => {
...
       const user = await users.create(
         { username: "routing-forms" },
         { seedRoutingForms: true, hasTeam: true }
       );
       await user.apiLogin();
-      // Install app
-      await page.goto(`/apps/routing-forms`);
-      await page.click('[data-testid="install-app-button"]');
-      (await page.waitForSelector('[data-testid="install-app-button-personal"]')).click();
-      await page.waitForURL((url) => url.pathname === `/apps/routing-forms/forms`);
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/playwright/tests/basic.e2e.ts:222]: No installation for Routing Form App needed now.

File: packages/app-store/typeform/config.json [hunk 14]
```diff
@@ -10,6 +10,5 @@
   "publisher": "Cal.com, Inc.",
   "email": "help@cal.com",
   "description": "Adds a link to copy Typeform Redirect URL",
-  "__createdUsingCli": true,
-  "dependencies": ["routing-forms"]
```
Comment (hariombalhara) [inline packages/app-store/typeform/config.json:14]: Routing form is preinstalled now, so this isn't needed.

File: packages/app-store/typeform/playwright/tests/basic.e2e.ts [hunk 15]
```diff
@@ -17,10 +17,6 @@ const installApps = async (page: Page, users: Fixtures["users"]) => {
     }
   );
   await user.login();
-  await page.goto(`/apps/routing-forms`);
-  await page.click('[data-testid="install-app-button"]');
-  (await page.waitForSelector('[data-testid="install-app-button-personal"]')).click();
-  await page.waitForURL((url) => url.pathname === `/apps/routing-forms/forms`);
```
Comment (hariombalhara) [inline packages/app-store/typeform/playwright/tests/basic.e2e.ts:23]: No installation for Routing Form App needed now.

File: packages/features/shell/Shell.tsx [hunk 16]
```diff
@@ -551,9 +549,7 @@ const navigation: NavigationItemType[] = [
           const path = router.asPath.split("?")[0];
           // During Server rendering path is /v2/apps but on client it becomes /apps(weird..)
           return (
-            (path.startsWith(item.href) || path.startsWith("/v2" + item.href)) &&
-            !path.includes("routing-forms/") &&
-            !path.includes("/installed")
```
Comment (hariombalhara) [inline packages/features/shell/Shell.tsx:556]: Same reason as above to remove routing-forms from here

File: packages/types/App.d.ts [hunk 17]
```diff
@@ -115,6 +115,11 @@ export interface App {
    * Used to show Connect/Disconnect buttons in App Store
    * */
   isGlobal?: boolean;
+  /**
+   * For apps that are accessible on an alternate UR(which is simpler and shorter), this can be set.
```
Comment (hariombalhara) [inline packages/types/App.d.ts:119]:
```suggestion
   * For apps that are accessible on an alternate URL(which is simpler and shorter), this can be set.
```

**Review by hariombalhara — COMMENTED** [review]
Self review done

File: packages/app-store/routing-forms/config.json (hunk 4 above)
Comment (CarinaWolli) [reply packages/app-store/routing-forms/config.json:5]: Would that mean that this URL should work? Or am I misunderstanding this?
Screenshot 2023-07-26 at 12 14 59

File: packages/app-store/routing-forms/config.json (hunk 10 above)
Comment (CarinaWolli) [reply packages/app-store/routing-forms/config.json:13]: Would that mean that this URL should work? Or am I misunderstanding this? 
Screenshot 2023-07-26 at 12 16 48

File: apps/web/middleware.ts (hunk 6 above)
Comment (CarinaWolli) [reply apps/web/middleware.ts:83]: `/apps/routing_forms` worked before now it doesn't anymore. Why did we need that before and why don't we need it anymore?

File: packages/app-store/routing-forms/config.json (hunk 10 above)
Comment (zomars) [reply packages/app-store/routing-forms/config.json:13]: Agreed with @CarinaWolli it's kinda confusing as I also expected that URL to work. But it only works when you go to `/routing-forms/forms`. Not a blocker IMO.

**Review by zomars — APPROVED** [review]
Looks good enough to ship. We might depart from all [...pages] and [...appPages] in the future and give it a proper location in their respective directories.

Ship it

File: packages/app-store/routing-forms/config.json (hunk 10 above)
Comment (hariombalhara) [reply packages/app-store/routing-forms/config.json:13]: Fixed it here https://github.com/calcom/cal.com/pull/10412. Certainly a bug.

File: apps/web/middleware.ts [hunk 18]
```diff
@@ -76,15 +75,34 @@ const middleware: NextMiddleware = async (req) => {
...
+const routingForms = {
+  handle: (url: URL) => {
+    // Next.config.js Redirects don't handle Client Side navigations and we need that.
+    // So, we add the rewrite here instead.
+    if (url.pathname.startsWith("/routing-forms/")) {
+      url.pathname = url.pathname.replace(/^\/routing-forms\//, "/apps/routing-forms/");
+      return NextResponse.rewrite(url);
+    }
+
+    // Don't 404 old routing_forms links
```
[the remark this answers is not in the document]
Comment (hariombalhara) [reply apps/web/middleware.ts:87]: Fixed it here. https://github.com/calcom/cal.com/pull/10412. Should have worked
