### PR TITLE
fix: rescheduling round robin events (emails and calendar events)

### LINKED ISSUE #11547: [CAL-2528] Round Robin Rescheduling reschedules to the previous user's calendar instead of to the new user.
Rescheduling a round-robin booking(which has a calendar Event in User-1’s calendar and User-1 has been chosen for the booking) changes the attendee from User-1 to User-2 in the existing calendar event(which is actually User-1’s calendar). 
This way the Calendar event is still blocking the slot for User-1 and thus rescheduling a round-robin to a particular slot effectively blocks that timeslot for both users - I observed this behavior with Google Calendar.

Ideally the calendar event should be moved to User-2’s calendar. 

																								

<sub>[CAL-2528](https://linear.app/calcom/issue/CAL-2528/round-robin-rescheduling-reschedules-to-the-previous-users-calendar)</sub>

### LINKED ISSUE #12341: [CAL-2704] Round robin rescheduling issues
There are some issues when rescheduling round-robin bookings. Still needs investigation but what has been found so far:

* Missing emails
* Calendar events not updating

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2704](https://linear.app/calcom/issue/CAL-2704/round-robin-rescheduling-issues)</sub>

### LINKED ISSUE #12350: [CAL-2708] Google Meet link not saved in metadata
Google Meet link is not saved in booking metadata (videoCallUrl)

Steps to reproduce:

* Install Google Meet
* Create event type with Google Meet as location
* Book event type
* Bug: videoCallUrl in booking metadata is empty

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2708](https://linear.app/calcom/issue/CAL-2708/google-meet-link-not-saved-in-metadata)</sub>

### PR DESCRIPTION
**Pull request by CarinaWolli**
## What does this PR do?

Fixes issues with rescheduling round-robin events when they are assigned to a new host. 

1. Emails 
- Old rr host will get cancelation email 
- New rr host will get scheduling emails 
- Other fixed hosts and attendees that stay the same receive rescheduling email

2. Calendar events
- If the organizer of the event changes: Old event gets deleted and a new event gets created with adapted event title 
- If only rr host changed but there is a fixed host as the organizer event just gets rescheduled 

4. Organizer's default location
- If location of event type is oragnizer's default location, it will take the default location of the new rr host

Also fixes that Google Meet link wasn't saved in metadata (videoCallUrl)

Fixes #12350
Fixes #11547
Fixes #12341

 Loom Video: https://www.loom.com/share/e8964cbd58d44877a138c9c0b4a9f4e0

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Create round robin event and assign user1 and user2 as round-robin hosts. 
- Set location as 'organizer's default'
- Make user2's default location Google Meet 
- Connect calendars for both users
- Book rr 
- Check if calendar event is correctly created 
- Reschedule booking (make sure the other user is available, so it will be assigned to a new user)
- Check if calendar event is removed from original booking and new event is created on the new organizer's calendar 
- Check Emails: 
  - previous host -> cancellation email 
  - new host -> scheduling email 
  - attendee -> rescheduling email

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 1]
```diff
@@ -2373,7 +2581,7 @@ async function handler(
 
   const metadata = videoCallUrl
     ? {
-        videoCallUrl: getVideoCallUrlFromCalEvent(evt),
+        videoCallUrl: getVideoCallUrlFromCalEvent(evt) || videoCallUrl,
```
Comment (CarinaWolli) [inline packages/features/bookings/lib/handleNewBooking.ts:2584]: This makes sure that Google Meet links is saved in metadata

File: packages/features/bookings/lib/handleNewBooking/test/reschedule.test.ts [hunk 2]
```diff
@@ -1224,230 +1683,141 @@ describe("handleNewBooking", () => {
...
-              ],
             },
           });
 
-          expectWorkflowToBeTriggered();
-
-          expectBookingRequestedEmails({
-            booker,
-            organizer,
+          expectSuccessfulRoudRobinReschedulingEmails({
```
Comment (CarinaWolli) [inline packages/features/bookings/lib/handleNewBooking/test/reschedule.test.ts:1695]: Expects that roundRobinHost1 receives cancelation email and roundRobinHost2 to receive scheduling email

File: packages/features/bookings/lib/handleNewBooking/test/reschedule.test.ts [hunk 3]
```diff
@@ -1469,76 +1839,13 @@ describe("handleNewBooking", () => {
...
-                }),
-              ]),
             },
-            uid: "MOCK_ID",
           });
 
-          expectSuccessfulBookingRescheduledEmails({
-            booker,
-            organizer,
+          expectSuccessfulRoudRobinReschedulingEmails({
```
Comment (CarinaWolli) [inline packages/features/bookings/lib/handleNewBooking/test/reschedule.test.ts:1845]: Expects that round roundRobinHost1 recieves rescheduling email

File: packages/core/EventManager.ts [hunk 4]
```diff
@@ -376,32 +377,37 @@ export default class EventManager {
...
-        const [updatedEvent] = Array.isArray(result.updatedEvent)
-          ? result.updatedEvent
-          : [result.updatedEvent];
-
-        if (updatedEvent) {
-          evt.videoCallData = updatedEvent;
-          evt.location = updatedEvent.url;
+      if (changedOrganizer) {
+        log.debug("RescheduleOrganizerChanged: Deleting Event and Meeting for previous booking");
+        await this.deleteEventsAndMeetings({ booking, event });
```
[the remark this answers is not in the document]
Comment (joeauyeung) [reply packages/core/EventManager.ts:382]: Once this is merged, we should consider the effect on #12122. Since a completely new calendar event is being created.

File: packages/core/EventManager.ts [hunk 5]
```diff
@@ -376,32 +377,37 @@ export default class EventManager {
...
-      if (isDedicated) {
-        const result = await this.updateVideoEvent(evt, booking);
-        const [updatedEvent] = Array.isArray(result.updatedEvent)
-          ? result.updatedEvent
-          : [result.updatedEvent];
-
-        if (updatedEvent) {
-          evt.videoCallData = updatedEvent;
-          evt.location = updatedEvent.url;
+      if (changedOrganizer) {
```
Comment (joeauyeung) [inline packages/core/EventManager.ts:380]: I'm not sure how I feel about calling the event manager reschedule and the create methods back to back. How do we feel about calling only one event manager method and handling the deletion and creation of the calendar events?

**Review by joeauyeung — COMMENTED** [review]
Changes are looking good. 

I just had a question about saving the Google Meet links in the metadata. I thought we were trying to move away from relying on metadata. Should the new Meet link be saved as a `bookingReference`?

**Review by zomars — APPROVED** [review]
LGTM

File: packages/core/EventManager.ts (hunk 5 above)
Comment (zomars) [reply packages/core/EventManager.ts:380]: Agreed. IMO reschedule should handle event recreation. But could be done in a follow up

**Comment by CarinaWolli** [comment]
> Agreed. IMO reschedule should handle event recreation. But could be done in a follow up

Totally agree with that, I will do a follow-up. 

> I just had a question about saving the Google Meet links in the metadata. I thought we were trying to move away from relying on metadata. Should the new Meet link be saved as a bookingReference?

@joeauyeung We should have it in both booking reference and metadata. I know we are trying to move away from metadata but right now we are still using it for getting the videocall url in  webhooks, workflows, etc. 
But I do see that the bookingReference isn't saved correctly when booking a round-robin event, I will revisit that as well in the follow-up
