### PR TITLE
fix: Make layout of booker not overflow in safari

### LINKED ISSUE #9586: 🚨 Booking form buttons not visible in safari
### Issue Summary

When on the an event public booking form in Safari
The Back and Confirm buttons are not visible
They are rendered for a few milliseconds, but then are pushed way off screen
image
image

Works fine in Chromium browsers

### Steps to Reproduce

1. Use safari and navigate to an event page
2. Select a timeslot and wait for form to render
3. Check css for buttons

--
This only happens on the default booking view, not the new cool views

### Technical details
 Safari Version 16.5 (18615.2.9.11.4)

### PR DESCRIPTION
**Pull request by JeroenReumkens**
## What does this PR do?

* Tweaks to booker grid sizing to prevent buttons from overflow booker wrapper in Safari
* Also fixes another issue where in the weekview layout the overflow wasn't scrollable

Fixes #9586

CleanShot 2023-06-19 at 10 26 03@2x

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Verify that the booker layout doesn't overflow without being scrollable in Safari. Test in other browsers as well.
- [ ] Verify mobile also still looks okay. 

## Mandatory Tasks
- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: packages/features/bookings/Booker/Booker.tsx [hunk 1]
```diff
@@ -139,12 +139,12 @@ const BookerComponent = ({
             <StickyOnDesktop
               key="meta"
               className={classNames(
-                "relative z-10 flex",
+                "relative z-10 flex [grid-area:meta]",
```
Comment (JeroenReumkens) [inline packages/features/bookings/Booker/Booker.tsx:142]: This wrapper div was the cause of the week view not being scrollable, because the grid area was actually defined in the child. Setting that on the parent makes the grid function like it should.

File: packages/features/bookings/Booker/components/AvailableTimeSlots.tsx [hunk 2]
```diff
@@ -73,7 +73,7 @@ export const AvailableTimeSlots = ({ extraDays, limitHeight, seatsPerTimeslot }:
     <div
       className={classNames(
         limitHeight && "flex-grow md:h-[400px]",
-        !limitHeight && "flex w-full flex-row gap-4"
+        !limitHeight && "flex h-full w-full flex-row gap-4"
```
Comment (JeroenReumkens) [inline packages/features/bookings/Booker/components/AvailableTimeSlots.tsx:76]: Extend busy day blocks full height in column view.

File: packages/features/bookings/Booker/config.ts [hunk 3]
```diff
@@ -70,7 +70,7 @@ export const resizeAnimationConfig: ResizeAnimationConfig = {
       "meta main main"
       `,
       gridTemplateColumns: "var(--booker-meta-width) var(--booker-main-width)",
-      gridTemplateRows: "auto",
+      gridTemplateRows: "1fr 0fr",
```
Comment (JeroenReumkens) [inline packages/features/bookings/Booker/config.ts:73]: This fixes the safari issue. 0fr for second row, because the 2 rows show the exact same template areas. So content will still be visible. Having 2 rows is needed (even though they are the same), to make the animations animate to the proper places. They would space out if suddenly a second row got added.

**Review by sean-brydon — APPROVED** [review]
Man css sucks at times! Nice fix
