### PR TITLE
fix: Org: Any team URL with slug starting with `d` is 404

### LINKED ISSUE #12334: [CAL-2697] A team with slug `designer` is 404 for an org
In an org **/designer** path gives 404.

e.g. app.cal.local:3000/**d**esigner is 404 always

Note that app.cal.local:3000/team/designer still works

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2697](https://linear.app/calcom/issue/CAL-2697/a-team-with-slug-designer-is-404-for-an-org)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #12334

The reason behind the issue was that /d is a existing route for private links. The same issue would come if team slug starts with any of the registered routes names e.g /apps-something, /auth-something

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
- Create a team with slug `dsomething` in an org
- Visit the team profile link i.e. app.cal.local:3000/dsomething. Notice that it is 404 in main but not in this branch

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by hariombalhara** [comment]
Current dependencies on/for this PR:
* main
  * **PR #12302** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/12302?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/calcom/cal.com/12302?utm_source=stack-comment).

File: apps/web/pagesAndRewritePaths.js [hunk 1]
```diff
@@ -27,11 +23,26 @@ let subdomainRegExp = (exports.subdomainRegExp = getSubdomainRegExp(
...
-exports.orgUserTypeRoutePath = `/:user((?!${beforeRewriteExcludePages.join(
-  "/|"
-)}|_next/|public/)[^/]+)/:type((?!avatar\.png)[^/]+)`;
-exports.orgUserTypeEmbedRoutePath = `/:user((?!${beforeRewriteExcludePages.join(
-  "/|"
-)}|_next/|public/)[^/]+)/:type/embed`;
+/**
+ * Returns a regex that matches all existing routes, virtual routes (like /forms, /router, /success etc) and nextjs special paths (_next, public)
+ */
+function getRegExpMatchingAllReservedRoutes(suffix) {
```
Comment (hariombalhara) [inline apps/web/pagesAndRewritePaths.js:29]: Abstract out the logic here so that we could reuse suffix easily.

File: apps/web/pagesAndRewritePaths.js [hunk 2]
```diff
@@ -27,11 +23,26 @@ let subdomainRegExp = (exports.subdomainRegExp = getSubdomainRegExp(
...
+  // Following routes don't exist but they work by doing rewrite. Thus they need to be excluded from matching the orgRewrite patterns
+  // Make sure to keep it upto date as more nonExistingRouteRewrites are added.
+  const otherNonExistingRoutePrefixes = ["forms", "router", "success", "cancel"];
+  const nextJsSpecialPaths = ["_next", "public"];
+
+  let beforeRewriteExcludePages = pages.concat(otherNonExistingRoutePrefixes).concat(nextJsSpecialPaths);
```
Comment (hariombalhara) [inline apps/web/pagesAndRewritePaths.js:35]: + suffix ensures that the last item is followed by suffix but not a pipe symbol.

**Review by zomars — APPROVED** [review]
Nice work @hariombalhara 🙏🏽
