### PR TITLE
fixed app bar on mobile

### LINKED ISSUE #4193: mobile: AppBar issues
- [x] it seems like the AppBar has mx on mobile and is not full-width

CleanShot 2022-09-06 at 08 57 09@2x

- [x] the search logo is too big / odd hover
CleanShot 2022-09-06 at 08 58 03@2x

- [x] the height is too much, see figma:
CleanShot 2022-09-06 at 08 58 41@2x

### PR DESCRIPTION
**Pull request by PeerRich**
before

CleanShot 2022-09-06 at 18 31 33@2x

after

CleanShot 2022-09-06 at 18 30 57@2x

### CODE REVIEW

**Review by sean-brydon — APPROVED** [review]
LGTM

File: packages/ui/v2/core/Shell.tsx [hunk 1]
```diff
@@ -138,7 +138,7 @@ const Layout = (props: LayoutProps) => {
       <div className="flex h-screen overflow-hidden" data-testid="dashboard-shell">
         {props.SidebarContainer || <SideBarContainer />}
         <div className="flex w-0 flex-1 flex-col overflow-hidden">
-          <UserV2OptInBanner />
+          {/* <UserV2OptInBanner /> */}
```
Comment (PeerRich) [inline packages/ui/v2/core/Shell.tsx:141]:
```suggestion
          <UserV2OptInBanner />
```

**Review by sean-brydon — APPROVED** [review]
LGTM :)
