### PR TITLE
Fixing admin wizard translations

### LINKED ISSUE #2579: [CAL-89] use language from user agent when onboarding
if not available use english

### PR DESCRIPTION
**Pull request by leog**
## What does this PR do?

Wizard was not correctly translated in order to be shown with the correct locale for the admin onboarding wizard using browsers' language

| Before      | After |
| ----------- | ----------- |
| image       | image       |

Fixes #2579

**Environment**: Staging(main branch) / Production

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

Go to the app deleting all users to trigger the admin onboarding. Switch language from browser and see its content language adapt accordingly.

### CODE REVIEW

**Review by pumfleet — APPROVED** [review]
Awesome

File: packages/ui/v2/core/WizardForm.tsx [hunk 1]
```diff
@@ -65,7 +67,7 @@ function WizardForm<T extends DefaultStep>(props: {
                   onClick={() => {
                     setStep(step + 1);
                   }}>
-                  {step < steps.length ? "Next" : "Finish"}
+                  {step < steps.length ? t("next_step_text") : t("finish")}
```
Comment (zomars) [inline packages/ui/v2/core/WizardForm.tsx:70]: Instead of introducing useLocale here. These strings should come directly form a prop.
