### PR TITLE
fix: Momentary flash of non-transparent background with different color-schemes of embed and embedding document

### LINKED ISSUE #10226: [CAL-2199] Handle momentary flash of non-transparent background when conflicting color-schemes are there.
_Originally posted by @hariombalhara in https://github.com/calcom/cal.com/pull/10033#discussion_r1266826003_
            

<sub>[CAL-2199](https://linear.app/calcom/issue/CAL-2199/handle-momentary-flash-of-non-transparent-background-when-conflicting)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #10226
The momentary flash is more visible in production because the document takes more time than local to respond there(TTFB is higher there)

Before:
https://www.loom.com/share/15252a81b1ca43b7b9723c0ee36fca96

After:
https://www.loom.com/share/4786fcc17dd248f5934ae5498cd42c72

Improvement over #10033 
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
See the loom

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/embeds/embed-core/src/embed.ts [hunk 1]
```diff
@@ -459,10 +474,6 @@ class CalApi {
 
     config.embedType = "inline";
 
-    // Note that by the time, the server responds with html having appropriate color-scheme, there might be a flash of non-transparent(white/black) background(for a few 100 milliseconds)
-    // There is no quick way know to fix it.
-    // An approach might be to add a temporary neutral iframe(with no src) whose html can be directly modified synchronously and let the iframe with calLink src respond,
-    // once the iframe responds, we can replace the neutral iframe with the calLink iframe
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed.ts:465]: This is now handled so removed the comment

**Review by keithwillcode — APPROVED** [review]
