### PR TITLE
Check app-store types on CI

### LINKED ISSUE #7189: [CAL-1109] Add type-check for app-store
InstallAppButton file doesn't exist. It was there unnecessarily, which means Typechecks are not working on app-store. Need to add that,

_Originally posted by @hariombalhara in https://github.com/calcom/cal.com/pull/7188#discussion_r1110834025_
            

<sub>[CAL-1109](https://linear.app/calcom/issue/CAL-1109/add-type-check-for-app-store)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
Adds "type-check" script to package.json so that type check for app-store runs on CI. Also, fixes the issues found.

Fixes #7189

### CODE REVIEW

File: packages/app-store/closecom/test/globals.ts [hunk 1]
```diff
@@ -13,3 +13,5 @@ jest.mock("@calcom/lib/crypto", () => ({
       "userApiKey": "test"
     }`,
 }));
+
+export {};
```
Comment (hariombalhara) [inline packages/app-store/closecom/test/globals.ts:17]: Make it work with --isolatedModules flag

File: packages/app-store/tsconfig.json [hunk 2]
```diff
@@ -18,8 +18,6 @@
     "../types/*.d.ts",
     "../types/next-auth.d.ts",
     "**/*.ts",
-    "**/*.tsx",
-    "../../apps/web/server/**/*.ts",
```
Comment (hariombalhara) [inline packages/app-store/tsconfig.json:22]: This isn't needed and also not recommended to directly import from a`pps/web`

**Review by zomars — APPROVED** [review]
