### PR TITLE
fix: make SSR-safe and fix ESLint warning for Beacon in UserDropdown

### LINKED ISSUE #24183: Unhandled access to window.Beacon in UserDropdown.tsx
### Issue Summary

In the `UserDropdown.tsx` component, the `useEffect` hook directly accesses `window.Beacon` without proper error handling. If `window` or `window.Beacon` is undefined in certain environments (such as during server-side rendering or restricted environments), this can throw an error and break the application.

### Steps to Reproduce

1. Run the application in an environment where `window` is not available (e.g., server-side rendering or testing environments).
2. Navigate to a page that renders `UserDropdown.tsx`.
3. Observe that the component attempts to access `window.Beacon` without checking for its existence.

### Actual Results

- The application crashes or throws an uncaught error when `window` or `window.Beacon` is not defined.

### Expected Results

- The component should safely handle cases where `window.Beacon` is not available, ideally by adding a conditional check or wrapping the access in a try/catch block to prevent runtime errors.

### Technical details

- Browser version: Any browser where `window.Beacon` is not defined.
- Node.js version: (Please specify your environment’s Node.js version here)
- Console logs: Error indicating that `window.Beacon` is undefined.
- Network requests: N/A

### Evidence

- Tested by running the component in an environment without `window` defined (e.g., server-side rendering).
- Error reproduced consistently with uncaught TypeError: `Cannot read properties of undefined (reading 'Beacon')`.

### PR DESCRIPTION
**Pull request by albin-baby-2002**
## What does this PR do?

This PR updates the UserDropdown component to be safe for server-side rendering (SSR) and addresses an ESLint warning related to a conditional expression.

- Added a guard `if (typeof window === "undefined") return;` to ensure `window.Beacon` is only accessed in the browser, preventing SSR errors.
- Replaced the `Beacon && Beacon(...)` expression with a proper `if (Beacon) { ... }` statement to satisfy ESLint rules (`@typescript-eslint/no-unused-expressions`).
- Added proper `BeaconFunction` type definition to the Window interface instead of using `@ts-ignore`.

- Fixes #24183 
- Fixes CAL-6493

## Updates since last revision

- **Merged upstream/main**: The `UserDropdown.tsx` file was moved from `packages/features/shell/user-dropdown/` to `apps/web/modules/shell/user-dropdown/` as part of an upstream refactor. This PR now targets the new file location.
- **Added dependency array to Beacon useEffect**: Per reviewer feedback, added `[user?.username]` as the dependency array to prevent the effect from running on every render while still updating session data when the username changes.
- **Added automated tests**: Created `UserDropdown.test.tsx` with 8 tests covering:
  - Beacon session-data calls with correct payload
  - Handling of undefined Beacon (no errors)
  - Lazy-loaded Beacon detection via polling
  - Username change triggering useEffect re-run
  - Component rendering states (loading, user available, no user)
- **Cleaned up test file** (per keithwillcode and Cubic feedback):
  - Removed redundant comments above vi.mock calls
  - Removed misleading SSR safety test that provided false coverage (jsdom always has window defined)
  - Removed unused `@ts-expect-error` directives (Window interface augmentation makes them unnecessary)
- **Fixed Beacon lazy loading issue** (per Cubic feedback): Implemented polling mechanism that checks every second for Beacon availability. When Beacon loads lazily after component mount, the polling detects it and sends session data, then clears the interval.

**Link to Devin run:** https://app.devin.ai/sessions/58c887a6e4f34d5dad0eaa09a212d733
**Requested by:** unknown ()

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [N/A] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set? N/A
- What are the minimal test data to have? N/A
- What is expected (happy path) to have (input and output)? N/A
- Any other important info that could help to test that PR: Run `yarn test apps/web/modules/shell/user-dropdown/UserDropdown.test.tsx` to execute the automated tests.

## Human Review Checklist

- [ ] Verify the polling mechanism (1-second interval) is appropriate for detecting lazy-loaded Beacon
- [ ] Confirm the interval cleanup on unmount prevents memory leaks
- [ ] Confirm the changes are correctly applied to `apps/web/modules/shell/user-dropdown/UserDropdown.tsx`
- [ ] Review that tests adequately cover the Beacon functionality including lazy loading scenario

### CODE REVIEW

File: packages/features/shell/user-dropdown/UserDropdown.tsx [hunk 1]
```diff
@@ -44,15 +44,19 @@ export function UserDropdown({ small }: UserDropdownProps) {
   const isPlatformPages = pathname?.startsWith("/settings/platform");
 
   useEffect(() => {
+    // guard added to make SSR safe
```
Comment (pallava-joshi) [inline packages/features/shell/user-dropdown/UserDropdown.tsx]: remove comment

**Review by pallava-joshi — CHANGES_REQUESTED** [review]
dropped suggestions

**Comment by pallava-joshi** [comment]
also implement code rabbit suggestions

**Comment by albin-baby-2002** [comment]
@Pallava-Joshi yeah will make the changes today itself

**Comment by albin-baby-2002** [comment]
@Pallava-Joshi  added the required changes. please look into it and tell if any other changes needed

**Review by pallava-joshi — DISMISSED** [review]
there's one more suggestion to fix useEffect's dependency.

**Comment by albin-baby-2002** [comment]
> there's one more suggestion to fix useEffect's dependency.

@Pallava-Joshi The issue is that if the useEffect runs before Beacon fully loads, the session data might not be sent. To handle this without affecting performance, I propose using a setInterval that periodically checks if Beacon is available. Once Beacon is ready, the session data is sent, and the interval is immediately cleared to avoid unnecessary calls. If the dependency user?.username changes later, the useEffect will trigger again, restarting the interval to ensure the updated session data is sent. This approach guarantees that session data is always sent when Beacon is ready while avoiding repeated or redundant calls.

**Comment by albin-baby-2002** [comment]
> > there's one more suggestion to fix useEffect's dependency.
> 
> @Pallava-Joshi The issue is that if the useEffect runs before Beacon fully loads, the session data might not be sent. To handle this without affecting performance, I propose using a setInterval that periodically checks if Beacon is available. Once Beacon is ready, the session data is sent, and the interval is immediately cleared to avoid unnecessary calls. If the dependency user?.username changes later, the useEffect will trigger again, restarting the interval to ensure the updated session data is sent. This approach guarantees that session data is always sent when Beacon is ready while avoiding repeated or redundant calls.

@Pallava-Joshi  can you give a reply on this , so that i can make necessary changes

**Comment by albin-baby-2002** [comment]
@Pallava-Joshi can you give a reply on this or @CarinaWolli

**Comment by albin-baby-2002** [comment]
@CarinaWolli  @Pallava-Joshi  please look into this and if any changes needed please mention

File: apps/web/modules/shell/user-dropdown/UserDropdown.test.tsx [hunk 2]
```diff
@@ -0,0 +1,246 @@
+import { render, waitFor } from "@testing-library/react";
+import React from "react";
+import { vi, describe, it, expect, beforeEach, afterEach } from "vitest";
+
+// Mock next-auth/react
```
Comment (keithwillcode) [inline apps/web/modules/shell/user-dropdown/UserDropdown.test.tsx]: DevinAI remove these useless comments

**Review by keithwillcode — APPROVED** [review]
