### PR TITLE
Fixes formatted description in email 

### LINKED ISSUE #7686: [CAL-1237] html formatting in E-Mail wrong (description)
The Event description in E-Mails is wrongly formatted, as you can see in this screenshot

2023-03-13 10_49_27-Webmail - ALL-INKL COM - tom@stfu at – Mozilla Firefox

Also I see that cal.com is sending E-Mail from "hello@cal.com", when a customer blindly answers these E-Mails they will end in nirvana... is there a chance to set the sender E-Mail Address to direct them to an E-Mail which is read? My fear is that customers ask something and they'll never get an answer because of that.

<sub>[CAL-1237](https://linear.app/calcom/issue/CAL-1237/html-formatting-in-e-mail-wrong-description)</sub>

### PR DESCRIPTION
**Pull request by CarinaWolli**
## What does this PR do?

Adds formatting to event-type description in email: 

Screenshot 2023-03-13 at 12 03 15

Fixes #7686

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by roae — APPROVED** [review]
LGTM! 👍

**Comment by CarinaWolli** [comment]
converted to draft as some more adjustments are needed 

lists in email need to be fixed: 
Screenshot 2023-03-14 at 11 41 17

File: apps/web/pages/[user].tsx [hunk 1]
```diff
@@ -352,9 +352,12 @@ export const getServerSideProps = async (context: GetServerSidePropsContext) =>
       })
     : [];
 
+  const safeBio = parseAndSanitize(user.bio || "");
```
Comment (hariombalhara) [inline apps/web/pages/[user].tsx:355]: nit: `markdownAndSanitize` gives more accurate description.

File: apps/web/components/eventtype/EventTypeDescriptionSafeHTML.tsx [hunk 2]
```diff
@@ -1,11 +1,14 @@
...
   eventType: { description: string | null };
 };
 
 export const EventTypeDescriptionSafeHTML = ({ eventType }: EventTypeDescriptionSafeProps) => {
   const props: JSX.IntrinsicElements["div"] = { suppressHydrationWarning: true };
-  // @ts-expect-error: @see packages/prisma/middleware/eventTypeDescriptionParseAndSanitize.ts
-  if (eventType.description) props.dangerouslySetInnerHTML = { __html: eventType.descriptionAsSafeHTML };
+  if (eventType.description)
+    // @ts-expect-error: @see packages/prisma/middleware/eventTypeDescriptionParseAndSanitize.ts
+    props.dangerouslySetInnerHTML = { __html: addListFormatting(eventType.descriptionAsSafeHTML) };
```
Comment (hariombalhara) [inline apps/web/components/eventtype/EventTypeDescriptionSafeHTML.tsx:11]: I think addListFormatting should be part of markdownAndSanitize only as it's working with the generated HTML.


I don't know why bio doesn't support lists, but if it does it would also automatically show lists with right styles

File: apps/web/components/team/screens/Team.tsx [hunk 3]
```diff
@@ -2,13 +2,12 @@ import Link from "next/link";
...
 import { WEBAPP_URL } from "@calcom/lib/constants";
 import { useLocale } from "@calcom/lib/hooks/useLocale";
-import { md } from "@calcom/lib/markdownIt";
 import type { TeamWithMembers } from "@calcom/lib/server/queries/teams";
 import { Avatar } from "@calcom/ui";
 
 type TeamType = NonNullable<TeamWithMembers>;
 type MembersType = TeamType["members"];
-type MemberType = MembersType[number];
+type MemberType = MembersType[number] & { safeBio?: string };
```
Comment (hariombalhara) [inline apps/web/components/team/screens/Team.tsx:10]: safeBio shouldn't be optional here(as I can see it is passed properly). We should do the changes required that don't allow it to be required here.

File: apps/web/pages/[user]/[type].tsx [hunk 4]
```diff
@@ -153,7 +153,7 @@ async function getUserPageProps(context: GetStaticPropsContext) {
     metadata: EventTypeMetaDataSchema.parse(eventType.metadata || {}),
     recurringEvent: parseRecurringEvent(eventType.recurringEvent),
     locations: privacyFilteredLocations(locations),
-    descriptionAsSafeHTML: eventType.description ? addListFormatting(md.render(eventType.description)) : null,
+    descriptionAsSafeHTML: eventType.description ? parseAndSanitize(eventType.description) : null,
```
Comment (hariombalhara) [inline apps/web/pages/[user]/[type].tsx:156]: There is unused variable md due to this change now.

File: apps/web/pages/team/[slug]/[type].tsx [hunk 5]
```diff
@@ -171,6 +172,7 @@ export const getServerSideProps = async (context: GetServerSidePropsContext) =>
       hideBranding,
       timeZone,
     })),
+    descriptionAsSafeHTML: eventType.description ? parseAndSanitize(eventType.description) : null,
```
Comment (hariombalhara) [inline apps/web/pages/team/[slug]/[type].tsx:175]: Maybe we can simplify all these instances to `parseAndSanitize(eventType.description || "")`

**Comment by hariombalhara** [comment]
I am not sure why but the bundle size has increased by 9.5% for all pages. So, if it's not urgent to merge we should look into that.

**Comment by hariombalhara** [comment]
Found the reason for bundle size increase. The import at this line is adding to the bundle size
https://github.com/calcom/cal.com/pull/7696/files#diff-099bcb1562bae2d81367bf7190fb46ab24832f9031480a4781e9879c44dff919R1

**Review by hariombalhara — CHANGES_REQUESTED** [review]
Bundle size problem is the blocker here,

**Comment by CarinaWolli** [comment]
Thank you for our review @hariombalhara 🙏 I implemented your feedback and bundle size looks good now as well

File: apps/web/package.json [hunk 6]
```diff
@@ -67,6 +67,7 @@
     "accept-language-parser": "^1.5.0",
     "async": "^3.2.4",
     "bcryptjs": "^2.4.3",
+    "canvas": "^2.11.0",
```
Comment (hariombalhara) [inline apps/web/package.json:70]: It doesn't seem to be used.
```suggestion
```

File: apps/web/pages/[user]/[type].tsx [hunk 7]
```diff
@@ -125,8 +125,6 @@ async function getUserPageProps(context: GetStaticPropsContext) {
     },
   });
 
-  const md = new MarkdownIt("default", { html: true, breaks: true, linkify: true });
```
Comment (hariombalhara) [inline apps/web/pages/[user]/[type].tsx:128]: It's still leaving the undefined variable MarkdownIt on line 62

File: apps/web/components/eventtype/EventTypeDescriptionSafeHTML.tsx [hunk 8]
```diff
@@ -1,12 +1,11 @@
 export type EventTypeDescriptionSafeProps = {
-  eventType: { description: string | null };
+  eventType: { description: string | null; descriptionAsSafeHTML: string | null };
 };
 
 export const EventTypeDescriptionSafeHTML = ({ eventType }: EventTypeDescriptionSafeProps) => {
   const props: JSX.IntrinsicElements["div"] = { suppressHydrationWarning: true };
   if (eventType.description)
-    // @ts-expect-error: @see packages/prisma/middleware/eventTypeDescriptionParseAndSanitize.ts
```
Comment (hariombalhara) [inline apps/web/components/eventtype/EventTypeDescriptionSafeHTML.tsx]: cc @CarinaWolli Removed this now, as descriptionAsSafeHTML is provided from every place in your PR.

File: apps/web/pages/[user]/[type].tsx (hunk 7 above)
Comment (hariombalhara) [reply apps/web/pages/[user]/[type].tsx:128]: Fixed it.

File: packages/lib/markdownAndSanitizeClientSide.ts [hunk 9]
```diff
@@ -0,0 +1,21 @@
+import DOMPurify from "dompurify";
```
Comment (hariombalhara) [inline packages/lib/markdownAndSanitizeClientSide.ts:1]: I think we can remove this duplicate by call markdownAndSanitize in tRPC calls and avoiding to do it on client side.

**Comment by hariombalhara** [comment]
Calendar Invite still has the similar problem as email. It shows markdown, we can fix that in a followup.
Screenshot 2023-03-22 at 9 41 19 AM

**Review by hariombalhara — APPROVED** [review]
Looks good to merge now.  Left some comments that can be addressed as a followup.
Also, fixed 1-2 ts issues.

File: apps/web/package.json (hunk 6 above)
Comment (CarinaWolli) [reply apps/web/package.json:70]: Not sure why, but without canvas, it was throwing an error. I think it is required with jsdom

**Comment by CarinaWolli** [comment]
I think it needs @zomars approval as a code owner before it can be merged

**Comment by hariombalhara** [comment]
@CarinaWolli It needs review from UI team which would be @sean-brydon @PeerRich or @baileypumfleet

**Review by PeerRich — APPROVED** [review]
