### PR TITLE
fix: Future Limit Calculations

### LINKED ISSUE #15320: [CAL-3861] Wrong slots shown with future limit
### Issue Summary

> [Just tested this and found it to be an existing behaviour before the future limit improvements](https://www.loom.com/share/6b5f42cb33054b6ebf727cd82ea59fbb). I can take it up as a follow up.

From comment: https://github.com/calcom/cal.com/pull/15288#issuecomment-2145527840

<sub>[CAL-3861](https://linear.app/calcom/issue/CAL-3861/wrong-slots-shown-with-future-limit)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?
- Fixes #15320
- Fixes CAL-3861

https://www.loom.com/share/bba5e3a7e82d466e81db67d63455a9fc

## In Main(Before)
**IST(Same Booker Timezone as the event schedule)**
image
**Pago/Pago(16:30 earlier than IST)**
Earliest Bookable time of 00:30 on 26th translates to 17:00 of 26th in IST which shouldn't be bookable
image

## NOW

**Pago/Pago(16:30 earlier than IST)**
Earliest bookable time of 16:30 on 26th translates to 09:00 of 27th in IST which should have the been the first bookable timeslot. So, now it is correct
image
Notice that 28th is also open now with just 2 timeslots. Last timeslot 01:30 translates to 18:00 which is the last possible bookable timeslot for 28th in IST. So, this is also correct.
image

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?
See the loom

### CODE REVIEW

**Comment by hariombalhara** [comment]
* **#15825** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/15825?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hariombalhara and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: packages/lib/isOutOfBounds.tsx [hunk 1]
```diff
@@ -59,121 +63,142 @@ export function calculatePeriodLimits({
...
   );
 
   switch (periodType) {
     case PeriodType.ROLLING: {
+      // We use booker's timezone to calculate the end of the rolling period(for both ROLLING and ROLLING_WINDOW). This is because we want earliest possible timeslot to be available to be booked which could be on an earlier day(compared to event timezone) as per booker's timezone.
+      // So, if 2 day rolling period is set and 2024-07-24T8:30:00 slot is available in event timezone, the corresponding slot in GMT-11 would be 2024-07-24T21:30:00. So, 24th should be bookable for that timeslot, which could only be made available if we consider things in booker timezone.
       const rollingEndDay = periodCountCalendarDays
-        ? currentTime.add(periodDays, "days")
-        : currentTime.businessDaysAdd(periodDays);
+        ? currentTimeInBookerTz.add(periodDays, "days")
```
Comment (hariombalhara) [inline packages/lib/isOutOfBounds.tsx:75]: No change here. Just a variable name change to describe the time better.

File: packages/lib/isOutOfBounds.tsx [hunk 2]
```diff
@@ -45,11 +46,14 @@ export function calculatePeriodLimits({
   EventType,
   "periodType" | "periodDays" | "periodCountCalendarDays" | "periodStartDate" | "periodEndDate"
 > & {
-  allDatesWithBookabilityStatus: Record<string, { isBookable: boolean }> | null;
-  utcOffset: number;
+  allDatesWithBookabilityStatusInBookerTz: Record<string, { isBookable: boolean }> | null;
+  eventUtcOffset: number;
+  bookerUtcOffset: number;
```
Comment (hariombalhara) [inline packages/lib/isOutOfBounds.tsx:51]: `bookerUtcOffset` is what was `utcOffset` earlier.

File: packages/trpc/server/routers/viewer/slots/util.ts [hunk 3]
```diff
@@ -765,15 +769,17 @@ export async function getAvailableSlots({ input, ctx }: GetScheduleOptions): Pro
   const allDatesWithBookabilityStatus = getAllDatesWithBookabilityStatus(availableDates);
   loggerWithEventDetails.debug(safeStringify({ availableDates }));
 
-  const utcOffset = input.timeZone ? getUTCOffsetByTimezone(input.timeZone) ?? 0 : 0;
+  const eventUtcOffset = getUTCOffsetByTimezone(eventTimeZone) ?? 0;
+  const bookerUtcOffset = input.timeZone ? getUTCOffsetByTimezone(input.timeZone) ?? 0 : 0;
```
Comment (hariombalhara) [inline packages/trpc/server/routers/viewer/slots/util.ts:773]: `utcOffset` got renamed to `bookerUtcOffset`

File: packages/lib/isOutOfBounds.tsx [hunk 4]
```diff
@@ -59,121 +63,142 @@ export function calculatePeriodLimits({
...
-        ? currentTime.add(periodDays, "days")
-        : currentTime.businessDaysAdd(periodDays);
+        ? currentTimeInBookerTz.add(periodDays, "days")
+        : currentTimeInBookerTz.businessDaysAdd(periodDays);
       // The future limit talks in terms of days so we take the end of the day here to consider the entire day
-      return { rollingEndDay: rollingEndDay.endOf("day"), rangeStartDay: null, rangeEndDay: null };
+      return {
+        endOfRollingPeriodEndDayInBookerTz: rollingEndDay.endOf("day"),
+        startOfRangeStartDayInEventTz: null,
+        endOfRangeEndDayInEventTz: null,
```
Comment (hariombalhara) [inline packages/lib/isOutOfBounds.tsx:81]: Variable names cahnged

File: packages/lib/isOutOfBounds.tsx [hunk 5]
```diff
@@ -45,11 +46,14 @@ export function calculatePeriodLimits({
   EventType,
   "periodType" | "periodDays" | "periodCountCalendarDays" | "periodStartDate" | "periodEndDate"
 > & {
-  allDatesWithBookabilityStatus: Record<string, { isBookable: boolean }> | null;
-  utcOffset: number;
+  allDatesWithBookabilityStatusInBookerTz: Record<string, { isBookable: boolean }> | null;
```
Comment (hariombalhara) [inline packages/lib/isOutOfBounds.tsx:49]: Renamed to convey the timezone

File: packages/lib/isOutOfBounds.tsx [hunk 6]
```diff
@@ -59,121 +63,142 @@ export function calculatePeriodLimits({
...
 
     case PeriodType.RANGE: {
-      // The future limit talks in terms of days so we take the start of the day for starting range and endOf the day for ending range
-      const rangeStartDay = dayjs(periodStartDate).utcOffset(utcOffset).startOf("day");
-      const rangeEndDay = dayjs(periodEndDate).utcOffset(utcOffset).endOf("day");
+      // We take the start of the day for the start of the range and endOf the day for end of range, so that entire days are covered
+      // We use organizer's timezone here(in contrast with ROLLING/ROLLING_WINDOW where number of days is available and not the specific date objects).
+      // This is because in case of range the start and end date objects are determined by the organizer, so we should consider the range in organizer/event's timezone.
+      const startOfRangeStartDayInEventTz = dayjs(periodStartDate).utcOffset(eventUtcOffset).startOf("day");
+      const endOfRangeEndDayInEventTz = dayjs(periodEndDate).utcOffset(eventUtcOffset).endOf("day");
```
Comment (hariombalhara) [inline packages/lib/isOutOfBounds.tsx:117]: This is what changed. It is using event timezone instead of booker timezone now.

File: packages/lib/isOutOfBounds.tsx [hunk 7]
```diff
@@ -59,121 +63,142 @@ export function calculatePeriodLimits({
...
 
 export function getRollingWindowEndDate({
-  startDate,
+  startDateInBookerTz,
   daysNeeded,
-  allDatesWithBookabilityStatus,
+  allDatesWithBookabilityStatusInBookerTz,
   countNonBusinessDays,
 }: {
   /**
```
Comment (hariombalhara) [inline packages/lib/isOutOfBounds.tsx:140]: No logical change in this function. Just a bit of cleanup and variable renames

File: packages/lib/isOutOfBounds.tsx [hunk 8]
```diff
@@ -219,19 +240,30 @@ export function isTimeViolatingFutureLimit({
...
 }) {
   const log = logger.getSubLogger({ prefix: ["isTimeViolatingFutureLimit"] });
-  const date = dayjs(time);
-  if (periodLimits.rollingEndDay) {
-    const isAfterRollingEndDay = date.isAfter(periodLimits.rollingEndDay);
-    log.debug({
-      formattedDate: date.format(),
+  // Because we are just going to compare times, we need not convert the time to a particular timezone
+  // date.isAfter/isBefore are timezone neutral
+  const dateInSystemTz = dayjs(time);
```
Comment (hariombalhara) [inline packages/lib/isOutOfBounds.tsx:245]: Just renamed `date` to convey the tz and added comment as to why the timezone doesn't matter in this function

File: packages/lib/isOutOfBounds.tsx [hunk 9]
```diff
@@ -219,19 +240,30 @@ export function isTimeViolatingFutureLimit({
...
-      rollingEndDay: periodLimits.rollingEndDay.format(),
+      endOfRollingPeriodEndDayInBookerTz: periodLimits.endOfRollingPeriodEndDayInBookerTz.format(),
     });
     return isAfterRollingEndDay;
   }
 
-  if (periodLimits.rangeStartDay && periodLimits.rangeEndDay) {
-    return date.isBefore(periodLimits.rangeStartDay) || date.isAfter(periodLimits.rangeEndDay);
+  if (periodLimits.startOfRangeStartDayInEventTz && periodLimits.endOfRangeEndDayInEventTz) {
+    const isBeforeRangeStart = dateInSystemTz.isBefore(periodLimits.startOfRangeStartDayInEventTz);
```
Comment (hariombalhara) [inline packages/lib/isOutOfBounds.tsx:257]: As explained in the comment in the code, we can compare system tz date object with event timezone date object.

File: packages/lib/isOutOfBounds.tsx [hunk 10]
```diff
@@ -202,15 +227,11 @@ export function isTimeOutOfBounds({
...
+  endOfRangeEndDayInEventTz: dayjs.Dayjs | null;
 };
 
-/**
- * To be used when we work on just Dates(and not specific timeslots) to check boundaries
- * e.g. It checks for Future Limits which operate on dates and not times.
- */
 export function isTimeViolatingFutureLimit({
   time,
   periodLimits,
```
Comment (hariombalhara) [inline packages/lib/isOutOfBounds.tsx:237]: No logical change in this function as well.

**Review by hariombalhara — COMMENTED** [review]
Self review done

**Comment by CarinaWolli** [comment]
@hariombalhara For me booking limits with date ranges doesn't work correctly in America/New_York. It's also not working in production, but if possible I think we should fix that in this PR as well

- Limit future booking date range: July 30 - July 31
- Availability: Mo-Fr 9am-7pm, America/New_York
- Booker tz America/New_York --> It shows the days July 29 and 30 as available

**Comment by hariombalhara** [comment]
> @hariombalhara For me booking limits with date ranges doesn't work correctly in America/New_York. It's also not working in production, but if possible I think we should fix that in this PR as well
> 
> * Limit future booking date range: July 30 - July 31
> * Availability: Mo-Fr 9am-7pm, America/New_York
> * Booker tz America/New_York --> It shows the days July 29 and 30 as available
It depends on which timezone the user was in while selecting the date range. If the user is in same timezone as the schedule while selecting the date range, it isn't a problem. This is normally the case I would assume.

I think we can fix it by adjusting the time as per the event scheduler's timezone. But it might be a breaking change and we might have to make it very clear in UI while selecting the dates. I would like to tackle it in a separate PR. Another approach could be having new columns for the new date range, in that way it won't break any existing date ranges.



https://www.loom.com/share/9a613308dcf44e04b11511df9f29a0ad

**Comment by CarinaWolli** [comment]
Thanks for the loom! 

I definlty think we should to save the `periodStartDate` and `periodEndDate` in UTC T00:00:00.000Z always. Then, the availability logic needs to be adjusted to that. But it sounds like we should do that in a follow-up

**Review by sean-brydon — COMMENTED** [review]
I have tested this and it works well nice job @hariombalhara. 

Will wait for code approval from @emrysal @CarinaWolli

**Review by CarinaWolli — COMMENTED** [review]
Tested and looks good 🙏 We can handle the other issue in a separate PR! 
Just left one small comment

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 11]
```diff
@@ -295,6 +294,8 @@ async function handler(
     })
   );
 
+  const eventTimeZone = eventType.schedule?.timeZone ?? null;
```
[the remark this answers is not in the document]
Comment (hariombalhara) [reply packages/features/bookings/lib/handleNewBooking.ts:297]: I don't think there is a case where it happens now. If that would have been the case, handleNewBooking would have failed for them right already?

[the remark this answers is not in the document]
Comment (CarinaWolli) [reply packages/features/bookings/lib/handleNewBooking.ts:297]: I know in checkBookingLimits we also just did `eventType.schedule?.timeZone` before, but I am wondering if this maybe was a bug? In `getUserAvailability` which is (indirectly) called in `handleNewBooking` we do that: 

`  const schedule = !useHostSchedulesForTeamEvent && eventType?.schedule ? eventType.schedule : userSchedule;`

[the remark this answers is not in the document]
Comment (CarinaWolli) [reply packages/features/bookings/lib/handleNewBooking.ts:297]: Can confirm I am getting this error when schedule is null for the event type:
Screenshot 2024-07-31 at 3 59 12 PM

When I set a schedule in the db it works

[the remark this answers is not in the document]
Comment (hariombalhara) [reply packages/features/bookings/lib/handleNewBooking.ts:297]: Let's tackle it in a different PR then? Also, the question is if the issue practically occurs in production or not.

**Review by CarinaWolli — APPROVED** [review]
Great work fixing that bug @hariombalhara 🙏

I created another issue for the two other bugs I found when reviewing: https://linear.app/calcom/issue/CAL-4091/issues-with-booking-limits

File: packages/features/bookings/lib/handleNewBooking.ts (hunk 11 above)
[the remark this answers is not in the document]
Comment (CarinaWolli) [reply packages/features/bookings/lib/handleNewBooking.ts:297]: In a normal scenario the `scheduleId` shouldn't be null in production. However, we definitely need to handle the case where it is null, I am sure we have some cases in the db where the schedule is null
