### PR TITLE
fix: fixed the padding at the footer in /signup

### LINKED ISSUE #15393: Padding should be fixed at bottom of screen in signup page in mac-air m1 13' inch device.
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Just go to /signup 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- Padding is negligible at footer

### Expected Results

- It should have proper distance from the footer.

### Technical details

- chrome , mac - m1 air
- Node.js version
- Anything else that you think could be an issue.
Screenshot 2024-06-10 at 18 35 11

### PR DESCRIPTION
**Pull request by Neon-20**
## What does this PR do?

- Fixes #15393

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [x] N/A I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [x] N/A I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

Screenshot 2024-06-10 at 18 41 16

### CODE REVIEW

File: apps/web/pages/signup.tsx [hunk 1]
```diff
@@ -529,11 +529,13 @@ export default function Signup({
...
             {/* Already have an account & T&C */}
-            <div className="mt-10 flex h-full flex-col justify-end text-xs">
+            <div className="mt-10 flex h-full flex-col justify-end pb-6 text-xs">
               <div className="flex flex-col text-sm">
                 <div className="flex gap-1">
                   <p className="text-subtle">{t("already_have_account")}</p>
-                  <Link href="/auth/login" className="text-emphasis hover:underline">
+                  <Link
+                    href="/auth/login"
+                    className="text-emphasis text-muted-foreground hover-effect cursor-pointer tracking-wide hover:animate-pulse dark:bg-transparent dark:bg-clip-text">
```
Comment (Udit-takkar) [inline apps/web/pages/signup.tsx:538]: we don't want these changes

Comment (Neon-20) [reply apps/web/pages/signup.tsx:538]: Ahh ok sure I will revert this style.

File: apps/web/pages/signup.tsx [hunk 2]
```diff
@@ -561,7 +561,7 @@ export default function Signup({
               </div>
             </div>
           </div>
-          <div className="border-subtle lg:bg-subtle mx-auto mt-24 w-full max-w-2xl flex-col justify-between rounded-l-2xl pl-4 dark:bg-none lg:mt-0 lg:flex lg:max-w-full lg:border lg:py-12 lg:pl-12">
+          <div className="border-subtle lg:bg-subtle mx-auto mt-24 w-full max-w-2xl flex-col justify-between rounded-l-2xl pl-4 shadow-md backdrop-blur-md dark:bg-none lg:mt-0 lg:flex lg:max-w-full lg:border lg:py-12 lg:pl-12">
```
Comment (PeerRich) [inline apps/web/pages/signup.tsx:564]:
```suggestion
          <div className="border-subtle lg:bg-subtle mx-auto mt-24 w-full max-w-2xl flex-col justify-between rounded-l-2xl pl-4 dark:bg-none lg:mt-0 lg:flex lg:max-w-full lg:border lg:py-12 lg:pl-12">
```

**Review by PeerRich — APPROVED** [review]
