### PR TITLE
fix: layout for settings/teams

### LINKED ISSUE #12947: `/settings/teams` layout is wrong
### Steps to Reproduce

1. go to /settings/teams and notice the layout

### Evidence

[Screencast from 26-12-23 03:53:37 PM IST.webm](https://github.com/calcom/cal.com/assets/32706411/60353e17-50d9-47df-bb0d-693b344b279a)

### PR DESCRIPTION
**Pull request by PeerRich**
not sure if this fixes #12947

### CODE REVIEW

File: packages/features/settings/layouts/SettingsLayoutAppDir.tsx [hunk 1]
```diff
@@ -105,7 +105,7 @@ const tabs: VerticalTabItemProps[] = [
   },
   {
     name: "teams",
-    href: "/settings/teams",
+    href: "/teams",
```
Comment (Udit-takkar) [inline packages/features/settings/layouts/SettingsLayoutAppDir.tsx:108]: we already have this in next-config redirects

     {
        source: "/settings/teams",
        destination: "/teams",
        permanent: true,
      },

Comment (PeerRich) [reply packages/features/settings/layouts/SettingsLayoutAppDir.tsx:108]: yeah but i think this redirect is causing issues with the layout (dir="") getting screwed up

**Review by Udit-takkar — APPROVED** [review]
