### PR TITLE
fix: header overlaps in month view on short viewport

### LINKED ISSUE #18476: [CAL-4978] UI elements (Overlay my calendar, Calendar Settings button) overlap the calendar view on 1366x768 resolution
### Issue Summary

This has been bugging me for months. On my Windows laptop (display resolution: 1366x768, landscape), the overlay my calendar and the calendar settings cog button overlap the monthly view.

spacing issue

If I zoom out 10%, the UI seems okay.

### Technical details

**Device**: Windows
**Display Resolution**: 1366x768
**Chrome**: 131.0.6778.205 (Official Build) (64-bit)
**Firefox Developer Edition**: 134.0b10 (64-bit)

### Evidence

overlay my calendar spacing

<sub>[CAL-4978](https://linear.app/calcom/issue/CAL-4978/ui-elements-overlay-my-calendar-calendar-settings-button-overlap-the)</sub>

### PR DESCRIPTION
**Pull request by evan-liu**
## Summary by mrge
Added vertical margin to the month view layout to prevent header overlap on short viewports, fixing the initial loading appearance while maintaining the designed scroll behavior.

## What does this PR do?

- Fixes #18476 (GitHub issue number)
- Fixes CAL-4978 (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Visual Demo (For contributors especially)

Live Preview: [Before](https://evanliu.dev/cal.com/storybook/iframe.html?id=booker--long-form&viewMode=story&duration=15&month=2025-05&slot=2025-04-30T13%3A00%3A00.000Z&layout=month_view) -> [After](https://evanliu.dev/cal.com/pr-2/iframe.html?id=booker--long-form&viewMode=story&duration=15&month=2025-05&slot=2025-04-30T13%3A00%3A00.000Z&layout=month_view)

The header still overlaps on the UI when scrolling up, which is by design. This PR added a margin on the main UI so that the UI does not look buggy on first load. 

image

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox. N/A
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

File: packages/features/bookings/Booker/Booker.tsx [hunk 1]
```diff
@@ -324,6 +324,7 @@ const BookerComponent = ({
           // In a popup embed, if someone clicks outside the main(having main class or main tag), it closes the embed
           "main",
           "text-default flex min-h-full w-full flex-col items-center",
+          layout === BookerLayouts.MONTH_VIEW && "my-20",
           layout === BookerLayouts.MONTH_VIEW ? "overflow-visible" : "overflow-clip",
```
Comment (retrogtx) [inline packages/features/bookings/Booker/Booker.tsx:328]: can we not combine this into one single line?

**Review by retrogtx — COMMENTED** [review]
Thanks for the PR, left a comment 🙏

File: packages/features/bookings/Booker/Booker.tsx (hunk 1 above)
Comment (evan-liu) [reply packages/features/bookings/Booker/Booker.tsx:328]: Yes sure. It was one line at first, but then I moved it up to separate concerns and keep the cohesion of 

`layout === BookerLayouts.MONTH_VIEW ? "overflow-visible" : "overflow-clip"`

Which could be like `overflow-${layout === BookerLayouts.MONTH_VIEW ? "visible" : "clip"}`, if not due to limitation of Tailwind. 

Will merge it into the line. Thanks for the feedback 🙏

Comment (retrogtx) [reply packages/features/bookings/Booker/Booker.tsx]: thank you 🙏

**Review by retrogtx — DISMISSED** [review]

**Comment by TusharBhatt1** [comment]
@evan-liu test failing

**Comment by evan-liu** [comment]
> @evan-liu test failing

Thanks for the reminder, it is now fixed.

**Review by retrogtx — APPROVED** [review]
