### PR TITLE
fix: join subteam as their respective organization role

### LINKED ISSUE #11732: organization - org owners and admins should show their respective badge when they join a sub-team
### this is my organization members page
Screenshot from 2023-10-06 17-17-07
* as you can see i have temp1 as admin and somay and somay2  as owners
### this is one the teams under my organizations
Screenshot from 2023-10-06 17-22-20
* as you can see all of them are joined as members but temp1, somay and somay2 all have the admin access to these teams i.e. they can add and remove members from teams so they should show owner/admin instead of member

PS: this is just a suggestion however, I may be wrong here.

### PR DESCRIPTION
**Pull request by ibex088**
Fixes #11732

[Screencast from 03-11-23 12:29:02 PM IST.webm](https://github.com/calcom/cal.com/assets/32706411/fa5856b4-2169-4d30-86d2-be832c2471bd)

- [ ] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts [hunk 1]
```diff
@@ -373,7 +377,7 @@ export async function createAndAutoJoinIfInOrg({
       userId: invitee.id,
       teamId: team.id,
       accepted: true,
-      role: role,
+      role: currentRole,
```
[the remark this answers is not in the document]
Comment (ThyMinimalDev) [reply packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts:380]: actually cam't we just consider that if orgMembership role exists we should just set that ?

[the remark this answers is not in the document]
Comment (SomayChauhan) [reply packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts:380]: no, because lets say i have a user in my organization as `MEMBER` now I want to make that user as a admin/owner of this team

[the remark this answers is not in the document]
Comment (SomayChauhan) [reply packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts:380]: > what do you think about just doing this here:
> 
> `orgMembership.role !== MembershipRole.MEMBER ? orgMembership.role : role ` ?

this I can do

**Review by hariombalhara — DISMISSED** [review]

File: packages/trpc/server/routers/viewer/teams/inviteMember/inviteMember.handler.ts [hunk 2]
```diff
@@ -105,12 +106,18 @@ export const inviteMemberHandler = async ({ ctx, input }: InviteMemberOptions) =
...
-          accepted: true,
-          role: input.role,
-        })),
+        data: autoJoinUsers.map((userToAutoJoin) => {
+          const organizationRole = userToAutoJoin?.teams?.[0]?.role;
+          return {
+            userId: userToAutoJoin.id,
+            teamId: team.id,
+            accepted: true,
+            role:
```
Comment (SomayChauhan) [inline packages/trpc/server/routers/viewer/teams/inviteMember/inviteMember.handler.ts:115]: this is to handle normal non pending members

[Screencast from 10-12-23 02:09:29 PM IST.webm](https://github.com/calcom/cal.com/assets/32706411/b2fe2c6a-2381-4199-8fa5-2c0d69d47101)

File: packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts [hunk 3]
```diff
@@ -286,12 +286,16 @@ export async function createProvisionalMemberships({
...
     await prisma.membership.createMany({
       data: invitees.flatMap((invitee) => {
+        const organizationRole = invitee?.teams?.[0]?.role;
         const data = [];
         // membership for the team
         data.push({
           teamId: input.teamId,
           userId: invitee.id,
-          role: input.role as MembershipRole,
+          role:
```
Comment (SomayChauhan) [inline packages/trpc/server/routers/viewer/teams/inviteMember/utils.ts:295]: this is to join the pending members as their respective org role

[Screencast from 10-12-23 02:10:03 PM IST.webm](https://github.com/calcom/cal.com/assets/32706411/d431e62c-8d44-4e32-9363-8353d49e5a44)

File: packages/trpc/server/routers/viewer/organizations/updateUser.handler.ts [hunk 4]
```diff
@@ -72,6 +90,21 @@ export const updateUserHandler = async ({ ctx, input }: UpdateUserOptions) => {
     }),
   ]);
 
+  if (input.role === MembershipRole.ADMIN || input.role === MembershipRole.OWNER) {
```
Comment (SomayChauhan) [inline packages/trpc/server/routers/viewer/organizations/updateUser.handler.ts:93]: When we make someone an admin in the organization, let's also make them an admin in all the teams they're part of. But, only do this when they go from being a regular member to an admin, We don't want to accidentally strip admin privileges of this user from sub-teams if we have explicitly defined it

[Screencast from 10-12-23 02:14:02 PM IST.webm](https://github.com/calcom/cal.com/assets/32706411/49c4400e-ef49-4145-9ea2-092eb18667cb)

File: packages/trpc/server/routers/viewer/organizations/updateUser.handler.ts [hunk 5]
```diff
@@ -72,6 +90,21 @@ export const updateUserHandler = async ({ ctx, input }: UpdateUserOptions) => {
...
+          in: requestedMember.team.children.map((sub_team) => {
+            return sub_team.members.find((item) => item.userId === input.userId).teamId;
+          }),
+        },
+      },
+      data: {
+        role: input.role,
+      },
+    });
+  }
```
Comment (hariombalhara) [inline packages/trpc/server/routers/viewer/organizations/updateUser.handler.ts:107]: How about abstracting this in a separate function `applyRoleToAllTeams` ? It would make the code easy to understand and testable if needed.

Comment (SomayChauhan) [reply packages/trpc/server/routers/viewer/organizations/updateUser.handler.ts:107]: Absolutely

File: packages/trpc/server/routers/viewer/teams/inviteMember/inviteMember.handler.ts [hunk 6]
```diff
@@ -105,12 +106,18 @@ export const inviteMemberHandler = async ({ ctx, input }: InviteMemberOptions) =
...
     if (autoJoinUsers.length) {
       await prisma.membership.createMany({
-        data: autoJoinUsers.map((userToAutoJoin) => ({
-          userId: userToAutoJoin.id,
-          teamId: team.id,
-          accepted: true,
-          role: input.role,
-        })),
+        data: autoJoinUsers.map((userToAutoJoin) => {
+          const organizationRole = userToAutoJoin?.teams?.[0]?.role;
```
Comment (hariombalhara) [inline packages/trpc/server/routers/viewer/teams/inviteMember/inviteMember.handler.ts:110]:
```suggestion
          const organizationRole = userToAutoJoin.teams?.[0]?.role;
```

**Review by hariombalhara — DISMISSED** [review]
Great work @SomayChauhan !!

File: packages/trpc/server/routers/viewer/organizations/updateUser.handler.ts (hunk 5 above)
Comment (hariombalhara) [reply packages/trpc/server/routers/viewer/organizations/updateUser.handler.ts:107]: Approved it for now and it's ready to merge. You can push it in a separate PR, would be a quick merge.

**Comment by hariombalhara** [comment]
@SomayChauhan There is a type error 
image

**Comment by SomayChauhan** [comment]
@hariombalhara
Made the suggested changes.

**Comment by hariombalhara** [comment]
@SomayChauhan another TS error 
image

**Comment by SomayChauhan** [comment]
My bad, forgot to change that one too.

**Review by hariombalhara — APPROVED** [review]
