### PR TITLE
Fixes public apps page

### LINKED ISSUE #2420: cal.com/apps is blank for unauthed users
### Issue Summary

Seems like a recent change is prevented the /apps page to be publicly accessible.

### Steps to Reproduce

1. Logout if you're logged in
2. Go to https://cal.com/apps
3. See the blank page

### PR DESCRIPTION
**Pull request by zomars**
## What does this PR do?

Fixes #2420

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Logout if you're logged in
- [ ] Go to /apps
- [ ] You should be able to see the apps page

### CODE REVIEW

**Review by sean-brydon — APPROVED** [review]
LGTM

File: apps/web/components/Shell.tsx [hunk 1]
```diff
@@ -57,9 +57,10 @@ function useRedirectToLoginIfUnauthenticated() {
   const { data: session, status } = useSession();
   const loading = status === "loading";
   const router = useRouter();
+  const shouldDisplayUnauthed = router.pathname.startsWith("/apps");
```
Comment (alannnc) [inline apps/web/components/Shell.tsx:60]: shouldDisplayUnauthorised or shouldDisplayUnauthorized

**Review by alannnc — APPROVED** [review]
Just a const name update before merging

File: apps/web/components/Shell.tsx (hunk 1 above)
Comment (afzalsayed96) [inline apps/web/components/Shell.tsx:60]: instead of hard-coding`/apps` we can introduce a prop on `Shell` to determine whether it should render when unauth or not

Comment (afzalsayed96) [reply apps/web/components/Shell.tsx:60]: Proposed #2437 for your reference

Comment (zomars) [reply apps/web/components/Shell.tsx:60]: As for now we don't plan to add any more public apps. We can do that when that changes.
