### PR TITLE
Fix Outlook & Zoom creating events in UTC

### LINKED ISSUE #6927: Office 365 Calendar Meeting being booked in UTC
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Office 365 Calendar Meeting being booked in UTC.
My profile is set to use EST, but meeting are being set in UCT. However, the time is correct.

### Steps to Reproduce

1. Connect to O365 Calendar
2. Book a meeting

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

may be related to https://github.com/calcom/cal.com/issues/6928

### Technical details
image

### LINKED ISSUE #6928: Zoom being being set to UTC (wrong time), after confirming a meeting.
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Availability is set to require confirmation when booking within 90 min. Using the Zoom App for conferencing.
Without confirmation, the zoom meeting time is correct in EST. When it needs to be confirmed, the zoom meeting get's set to the UTC time, even though I'm in EST.

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details
may be linked to https://github.com/calcom/cal.com/issues/6927

image

### PR DESCRIPTION
**Pull request by joeauyeung**
## What does this PR do?

This PR fixes events being created in UTC on Outlook & Zoom.

Fixes #6928, fixes #6927 

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- Connect Outlook & Zoom
- Create an event
- On Outlook & Zoom the events should have been made in your set timezone

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by joeauyeung — COMMENTED** [review]
When we would pass event start & end times it would be formatted as `2023-02-22T18:00:00Z`. The `Z` at the end would overwrite any time zones we would pass.

**Review by zomars — APPROVED** [review]

File: packages/app-store/zoomvideo/lib/VideoApiAdapter.ts [hunk 1]
```diff
@@ -196,11 +196,12 @@ const ZoomVideoApiAdapter = (credential: CredentialPayload): VideoApiAdapter =>
     };
 
     const recurrence = getRecurrence(event);
+    const utcOffset = dayjs(event.startTime, event.organizer.timeZone).utcOffset() / 60;
```
Comment (lottamus) [inline packages/app-store/zoomvideo/lib/VideoApiAdapter.ts:199]: @zomars @joeauyeung I believe this code `dayjs(event.startTime, event.organizer.timeZone)` is resulting in `NaN`, which is setting the `start_time` on L204 to be the current time.

I can reproduce this consistently:

https://github.com/calcom/cal.com/issues/6928#issuecomment-1470975620

I just tried it again today at 2:47pm with the following parameters:

Scheduled the meeting for 3/18 at 11am.

image

And the zoom meeting was scheduled for today at 2:47pm.

image

Comment (joeauyeung) [reply packages/app-store/zoomvideo/lib/VideoApiAdapter.ts:199]: Thanks for finding this @lottamus. I'll look into it
