### PR TITLE
fix: whatsapp message body sometimes editable (Issue #16067)

### LINKED ISSUE #16067: [CAL-4104] Whatsapp message body sometimes editable
WhatsApp only allows predefined templates, so the input field for the WhatsApp message body shouldn't be editable. 

How to reproduce? 

* Create a new workflow
* Change action to 'Send WhatsApp message to attendee'
* Now you the text from for text message can be edited

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4104](https://linear.app/calcom/issue/CAL-4104/whatsapp-message-body-sometimes-editable)</sub>

### PR DESCRIPTION
**Pull request by Flash-Shivam**
## What does this PR do?

- Fixes #16067 (GitHub issue number)
- Fixes CAL-4104 (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A-I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

https://drive.google.com/file/d/1KqoS5ZKzknPo7Bms45mRwHCnyqECt0zt/view?usp=sharing

Please refer the video above 👆

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

### CODE REVIEW

File: packages/features/ee/workflows/components/WorkflowStepContainer.tsx [hunk 1]
```diff
@@ -919,9 +918,31 @@ export default function WorkflowStepContainer(props: WorkflowStepProps) {
...
+                      variables={DYNAMIC_TEXT_VARIABLES}
+                      height="200px"
+                      updateTemplate={updateTemplate}
+                      firstRender={firstRender}
+                      setFirstRender={setFirstRender}
+                      editable={false}
+                    />
+                  </>
+                )}
+                {isEmailSubjectNeeded && (
```
Comment (anikdhabal) [inline packages/features/ee/workflows/components/WorkflowStepContainer.tsx:945]: This is not optimal to use a similar editor and render it conditionally. Instead, make it non-editable when certain conditions are met

**Review by anikdhabal — CHANGES_REQUESTED** [review]

**Comment by anikdhabal** [comment]
@Flash-Shivam also pls sign the CLA

File: packages/features/ee/workflows/components/WorkflowStepContainer.tsx (hunk 1 above)
Comment (Flash-Shivam) [reply packages/features/ee/workflows/components/WorkflowStepContainer.tsx:945]: The issue with the code is `!props.readOnly && !isWhatsappAction(step.action)` value is `false` still I am able to edit the text box. Hence I separated it out and set it to false.

I can create a new reusable component called EditorComponent and take isEditable as param which will be set true for email case and false for Whatsapp

Comment (Flash-Shivam) [reply packages/features/ee/workflows/components/WorkflowStepContainer.tsx:945]: Something of this sort 

```

const editorComponent = ({ isEditable }) => {
      return (
        <>
          <div className="mb-2 flex items-center pb-[1.5px]">
            <Label className="mb-0 flex-none ">
              {isEmailSubjectNeeded ? t("email_body") : t("text_message")}
            </Label>
          </div>
          <Editor
            getText={() => {
              return props.form.getValues(`steps.${step.stepNumber - 1}.reminderBody`) || "";
            }}
            setText={(text: string) => {
              props.form.setValue(`steps.${step.stepNumber - 1}.reminderBody`, text);
              props.form.clearErrors();
            }}
            variables={DYNAMIC_TEXT_VARIABLES}
            height="200px"
            updateTemplate={updateTemplate}
            firstRender={firstRender}
            setFirstRender={setFirstRender}
            editable={isEditable}
          />
        </>
      );
    };







               
          
      {!isEmailSubjectNeeded && !isSenderIsNeeded && <editorComponent isEditable={false} />}
      {isEmailSubjectNeeded && <editorComponent isEditable={true} />}

Comment (anikdhabal) [reply packages/features/ee/workflows/components/WorkflowStepContainer.tsx:945]: Hey @Flash-Shivam, I've tested it locally, and currently, there is very weird behavior. If you hardcode isEditable to false, it’s not editable, but when it's set using a variable or certain conditions, it’s still editable. Let me investigate why this is happening, and then I will suggest a fix.

Comment (Flash-Shivam) [reply packages/features/ee/workflows/components/WorkflowStepContainer.tsx]: I feel if we can't resolve the issue of why it is editable when set false using a variable or certain conditions, we should for time being use my approach of creating a editor component and use the conditions outside it and pass the isEditable value as true or false instead of conditions.

File: packages/features/ee/workflows/components/WorkflowStepContainer.tsx [hunk 2]
```diff
@@ -300,6 +299,33 @@ export default function WorkflowStepContainer(props: WorkflowStepProps) {
       value: trigger,
     };
 
+    const editorComponent = ({ isEditable }) => {
```
Comment (Amit91848) [inline packages/features/ee/workflows/components/WorkflowStepContainer.tsx:302]:
```suggestion
    const EditorComponent = ({ isEditable }) => {
```
Also add proper types @Flash-Shivam

File: packages/features/ee/workflows/components/WorkflowStepContainer.tsx [hunk 3]
```diff
@@ -919,32 +945,9 @@ export default function WorkflowStepContainer(props: WorkflowStepProps) {
...
-                      updateTemplate={updateTemplate}
-                      firstRender={firstRender}
-                      setFirstRender={setFirstRender}
-                      editable={!props.readOnly && !isWhatsappAction(step.action)}
-                    />
-                  </>
-                ) : (
+                {!isEmailSubjectNeeded && !isSenderIsNeeded && <editorComponent isEditable={false} />}
+                {isEmailSubjectNeeded && <editorComponent isEditable={true} />}
+                {isSenderIsNeeded && (
```
Comment (Amit91848) [inline packages/features/ee/workflows/components/WorkflowStepContainer.tsx:950]: Seems to me like an issue with the Editor Component, you can render it the way it is done in other places


https://github.com/calcom/cal.com/blob/b09b32b121adb50f903bcfdadf62a39ae1a6f68b/apps/web/components/eventtype/EventSetupTab.tsx#L114

https://github.com/calcom/cal.com/blob/b09b32b121adb50f903bcfdadf62a39ae1a6f68b/apps/web/components/eventtype/EventSetupTab.tsx#L28-L45

**Review by Amit91848 — DISMISSED** [review]
Left some suggestions @Flash-Shivam

File: packages/features/ee/workflows/components/WorkflowStepContainer.tsx (hunk 2 above)
Comment (anikdhabal) [inline packages/features/ee/workflows/components/WorkflowStepContainer.tsx:302]: This could be present after line 375

File: packages/features/ee/workflows/components/WorkflowStepContainer.tsx [hunk 4]
```diff
@@ -300,6 +299,33 @@ export default function WorkflowStepContainer(props: WorkflowStepProps) {
...
     };
 
+    const editorComponent = ({ isEditable }) => {
+      return (
+        <>
+          <div className="mb-2 flex items-center pb-[1.5px]">
+            <Label className="mb-0 flex-none ">
+              {isEmailSubjectNeeded ? t("email_body") : t("text_message")}
+            </Label>
+          </div>
```
Comment (anikdhabal) [inline packages/features/ee/workflows/components/WorkflowStepContainer.tsx:309]: Also, don't add this or any conditions; only the editor.

**Comment by anikdhabal** [comment]
https://github.com/calcom/cal.com/blob/b09b32b121adb50f903bcfdadf62a39ae1a6f68b/apps/web/components/eventtype/EventSetupTab.tsx#L28-L45

This couldn't fix the issue. There is a problem in the editor component, tested it. So, we may need to set a hardcoded boolean value somehow, or we need to fix the issue.

File: packages/features/ee/workflows/components/WorkflowStepContainer.tsx (hunk 2 above)
Comment (Flash-Shivam) [reply packages/features/ee/workflows/components/WorkflowStepContainer.tsx:302]: My latest commit code is working , I just need to edit the nit picks.

**Comment by Flash-Shivam** [comment]
> https://github.com/calcom/cal.com/blob/b09b32b121adb50f903bcfdadf62a39ae1a6f68b/apps/web/components/eventtype/EventSetupTab.tsx#L28-L45
> 
> This couldn't fix the issue. There is a problem in the editor component, tested it. So, we may need to set a hardcoded boolean value somehow, or we need to fix the issue.

My latest commit code is working , I just need to edit the nit picks.

File: packages/features/ee/workflows/components/WorkflowStepContainer.tsx (hunk 3 above)
Comment (anikdhabal) [inline packages/features/ee/workflows/components/WorkflowStepContainer.tsx:950]: We could simply add `!props.readOnly && !isWhatsappAction(step.action) ?` instead of these checks. Pls remove and update

**Comment by anikdhabal** [comment]
> My latest commit code is working , I just need to edit the nit picks.

Please address the comments and make the necessary changes. Tagging @CarinaWolli for some thoughts on the issue

**Comment by anikdhabal** [comment]
I fixed the issue in the editor component, there’s no need to do any extra work now.

**Review by anikdhabal — DISMISSED** [review]
LGTM!!

File: packages/ui/components/editor/Editor.tsx [hunk 5]
```diff
@@ -89,7 +90,6 @@ export const Editor = (props: TextEditorProps) => {
               contentEditable={
                 <ContentEditable
                   data-testid="editor-input"
```
Comment (Amit91848) [inline packages/ui/components/editor/Editor.tsx:92]:
```suggestion
                  data-testid="editor-input"
                  readOnly={!editable}
```

**Review by anikdhabal — DISMISSED** [review]

**Review by Amit91848 — DISMISSED** [review]
LGTM! Great stuff @Flash-Shivam @anikdhabal

File: packages/ui/components/editor/Editor.tsx [hunk 6]
```diff
@@ -70,7 +71,7 @@ export const Editor = (props: TextEditorProps) => {
   const editable = props.editable ?? true;
   return (
     <div className="editor rounded-md">
-      <LexicalComposer initialConfig={{ ...editorConfig, editable }}>
```
Comment (anikdhabal) [inline packages/ui/components/editor/Editor.tsx:73]: Not needed

File: packages/ui/components/editor/Editor.tsx [hunk 7]
```diff
@@ -88,7 +89,6 @@ export const Editor = (props: TextEditorProps) => {
             <RichTextPlugin
               contentEditable={
                 <ContentEditable
-                  data-testid="editor-input"
```
Comment (anikdhabal) [inline packages/ui/components/editor/Editor.tsx:91]: Same here

**Comment by anikdhabal** [comment]
I forgot to add a test for the plugin and also removed unnecessary things. Fixed it, and now everything is fine

**Review by anikdhabal — APPROVED** [review]
Looks good now!
