### PR TITLE
Fix MS Teams missing refresh token

### LINKED ISSUE #3854: Microsoft Teams No invite link in email - Self Hosted
### Issue Summary

We are using Cal.com on a self hosted instance. 

The email invites do not have any MS Teams invite or URL. The location shown is "Office365_Video". 

### Steps to Reproduce

1. Cal.com self hosted
2. Add Office365 Teams app
3. Create an event with location as MS Teams
4. Book a meeting and receive invite with no MS Teams link

### PR DESCRIPTION
**Pull request by joeauyeung**
## What does this PR do?

This PR adds the "offline_access" scope when connecting to MS Teams. Having this scope gives us the refresh token that was missing from our credentials.

Fixes #3854 #2818 #2946

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Connect to MS Teams
    - Ensure that the refresh token is included in the responseBody
- In the DB change the expiration date to the past
- Create a booking with MS Teams as the location. The tokens should have refreshed. 

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/app-store/office365video/api/add.ts [hunk 1]
```diff
@@ -6,7 +6,7 @@ import { WEBAPP_URL } from "@calcom/lib/constants";
 import { encodeOAuthState } from "../../_utils/encodeOAuthState";
 import getAppKeysFromSlug from "../../_utils/getAppKeysFromSlug";
 
-const scopes = ["OnlineMeetings.ReadWrite"];
+const scopes = ["OnlineMeetings.ReadWrite", "offline_access"];
```
Comment (joeauyeung) [inline packages/app-store/office365video/api/add.ts:9]: The `offline_access` scope is needed to receive a refresh token along with the access token

File: packages/app-store/office365video/lib/VideoApiAdapter.ts [hunk 2]
```diff
@@ -49,14 +49,17 @@ const o365Auth = async (credential: Credential) => {
       method: "POST",
       headers: { "Content-Type": "application/x-www-form-urlencoded" },
       body: new URLSearchParams({
-        scope: "User.Read OnlineMeetings.ReadWrite",
```
Comment (joeauyeung) [inline packages/app-store/office365video/lib/VideoApiAdapter.ts:52]: Scope is optional in this call so let's remove

File: packages/app-store/office365video/lib/VideoApiAdapter.ts [hunk 3]
```diff
@@ -49,14 +49,17 @@ const o365Auth = async (credential: Credential) => {
...
         refresh_token: refreshToken,
         grant_type: "refresh_token",
         client_secret,
       }),
     });
     const responseBody = await handleErrorsJson(response);
+    if (responseBody.error) {
+      console.error(responseBody);
+      throw new HttpError({ statusCode: 500, message: "Error contacting MS Teams" });
+    }
```
Comment (joeauyeung) [inline packages/app-store/office365video/lib/VideoApiAdapter.ts:62]: If there is an error, this avoids replacing the keys with that error

**Review by alannnc — APPROVED** [review]
Code looks good.
On another topic, what happens when a credential expires? Do we have a way to tell the user that his credential/expired and he should reconnect?
