### PR TITLE
fix: Skeleton Padding and Width Issue

### LINKED ISSUE #9309: [CAL-1858] refactor: fix skeleton for side bar
see:

[https://github.com/calcom/cal.com/assets/8019099/c8ecb3c1-291e-46cd-be18-6efb14b70159](https://github.com/calcom/cal.com/assets/8019099/c8ecb3c1-291e-46cd-be18-6efb14b70159)

issues:

* layout shift (different heights)
* skeleton has no padding left to the icon
* hover should be disabled while loading

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1858](https://linear.app/calcom/issue/CAL-1858/refactor-fix-skeleton-for-side-bar)</sub>

### PR DESCRIPTION
**Pull request by piyushgarg-dev**
## What does this PR do?
This PR fixes the padding issue of the skeleton text in the sidebar and makes the width of the skeleton adapt to the text size.

Fixes #9309
/claim #9309

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Screenshots
Screenshot 2023-06-04 at 1 30 57 AM

https://github.com/calcom/cal.com/assets/44976328/6e3b7c9e-b8ab-43d7-9c39-e97910364bfb

### CODE REVIEW

**Comment by PeerRich** [comment]
there is still a layout shift (the icons bouncing)

**Comment by piyushgarg-dev** [comment]
@PeerRich  Fixed Bounce Issue 🙌🏻

### Recording
https://github.com/calcom/cal.com/assets/44976328/f75164ed-b234-49a2-8b11-66547b820ae5

**Comment by PeerRich** [comment]
perfect! will merge today!

File: packages/features/shell/Shell.tsx [hunk 1]
```diff
@@ -667,7 +668,7 @@ const NavigationItem: React.FC<{
               {item.badge && item.badge}
             </span>
           ) : (
-            <SkeletonText className="h-3 w-32" />
+            <SkeletonText style={{ width: `${item.name.length * 10}px` }} className="h-[20px]" />
```
Comment (PeerRich) [inline packages/features/shell/Shell.tsx:671]: that's a great idea!

**Review by PeerRich — APPROVED** [review]
