### PR TITLE
fix: v2 booking confirmation emails not sent

### LINKED ISSUE #17315: [CAL-4756] Issue with missing email notifications for Attendees and Organizer when creating a booking via Cal.com API
Hello Support Team,

We are encountering an issue with the Creating a Booking API (Path: **_/api-reference/v2/bookings/create-a-booking_**). Despite successfully booking events via the API, neither the attendees nor the organizer are receiving email notifications.

This is a critical problem as email notifications are essential to ensure that all participants are informed about their scheduled events. We have verified that the email addresses for both attendees and the organizer are correct and the event creation process works as expected, except for the lack of notification emails. (We check the spam folder too)

Could you please investigate this issue and provide guidance on how to ensure email notifications are triggered when using the mentioned path?
Thank you for your support.

Best regards,

Armand Jensen-Bennet

Evidence:

cal com screenshot
cal com screenshot headers
GTM-05:00
cal com screenshot booked

<sub>[CAL-4756](https://linear.app/calcom/issue/CAL-4756/issue-with-missing-email-notifications-for-attendees-and-organizer)</sub>

### PR DESCRIPTION
**Pull request by supalarry**
Linear [CAL-4761](https://linear.app/calcom/issue/CAL-4761/platform-fix-booking-confirmation-emails-not-sent)
Fixes #17315

### CODE REVIEW

File: packages/features/bookings/lib/handleNewRecurringBooking.ts [hunk 1]
```diff
@@ -44,7 +44,7 @@ export const handleNewRecurringBooking = async (
       thirdPartyRecurringEventId,
       numSlotsToCheckForAvailability,
       currentRecurringIndex: 0,
-      noEmail: false,
+      noEmail: req.noEmail !== undefined ? req.noEmail : false,
```
Comment (supalarry) [inline packages/features/bookings/lib/handleNewRecurringBooking.ts:47]: I think it makes sense to not always have `noEmail: false` if platform emails are disabled.

**Review by ThyMinimalDev — APPROVED** [review]
