### PR TITLE
fix: Invalid options for Select and MultiSelect when both legacy and new options(i.e. with and without id are present)

### LINKED ISSUE #16495: [CAL-4265] moving answers order in routing form duplicates the answer.
When I add an option and move it along the order, other options duplicate and whatever i click also results in duplication

[Vídeo sin título.mp4](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/8052d88f-efde-451c-8c81-e2644419ec17/c1a584a1-c30c-4a55-aca6-b4f291ca34b8)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4265](https://linear.app/calcom/issue/CAL-4265/moving-answers-order-in-routing-form-duplicates-the-answer)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

- Fixes #16495 
- Fixes CAL-4265
- Fixes CAL-4278

Regression from #15706

- Fixes the following issue:
The error was coming because Other had a non null id(because it was created later) but rest of the options in the list didn't have id set. This made `getUIOptionsForSelect` become faulty
image - [Demo for Fix](https://www.loom.com/share/f63b83804e604458a5a250f2a1a490ef)
- Fixes the CSV download as it had option's id instead of label for newly created options - Fix is verified by e2e.
- Fix issue with options getting duplicated sometimes when moving them.
- Fixes a frustrating experience on local(by Hydration error) for reporting page.

## Mandatory Tasks (DO NOT REMOVE)
- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?
- Go to pro user's Seeded Routing Form
- Add 2 more options to existing options of MultiSelect fields
- Try selecting those newly added option while submitting the form.

### CODE REVIEW

File: packages/app-store/routing-forms/lib/selectOptions.ts [hunk 1]
```diff
@@ -35,14 +35,28 @@ export const getFieldWithOptions = <T extends Field>(field: T) => {
...
+) {
+  const options = field.options || [];
+  return !!options.find((option) => !option.id);
+}
+
 export function getUIOptionsForSelect(field: Field) {
-  return getFieldWithOptions(field).options?.map((option) => {
+  const fieldWithOptions = getFieldWithOptions(field);
+  const options = fieldWithOptions.options || [];
+  const areOptionsInLegacyFormat = areSelectOptionsInLegacyFormat(
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/lib/selectOptions.ts:51]: We are supposed to fallback to label for all options if the options are in legacy format.

This caused options to the select to be not matching the value provided.

File: packages/app-store/routing-forms/lib/selectOptions.ts [hunk 2]
```diff
@@ -35,14 +35,28 @@ export const getFieldWithOptions = <T extends Field>(field: T) => {
   }
   return {
     ...field,
-  };
+  } as typeof field & z.BRAND<"FIELD_WITH_OPTIONS">;
 };
 
+export function areSelectOptionsInLegacyFormat(
+  field: Pick<Field, "options"> & z.BRAND<"FIELD_WITH_OPTIONS">
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/lib/selectOptions.ts:42]: Using brand to ensure that field have `options` property even for legacy field with `selectText`.

File: packages/app-store/routing-forms/lib/getQueryBuilderConfig.ts [hunk 3]
```diff
@@ -1,9 +1,9 @@
-import { FieldTypes } from "../pages/form-edit/[...appPages]";
 import type { QueryBuilderUpdatedConfig, RoutingForm } from "../types/types";
+import { FieldTypes } from "./FieldTypes";
 import { InitialConfig } from "./InitialConfig";
 import { getUIOptionsForSelect } from "./selectOptions";
 
-export function getQueryBuilderConfig(form: RoutingForm, forReporting = false) {
+export function getQueryBuilderConfig(form: Pick<RoutingForm, "fields">, forReporting = false) {
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/lib/getQueryBuilderConfig.ts:6]: Be specific. Helps with the tests.

File: packages/app-store/routing-forms/lib/getQueryBuilderConfig.ts [hunk 4]
```diff
@@ -22,20 +22,21 @@ export function getQueryBuilderConfig(form: RoutingForm, forReporting = false) {
...
+      const widget = InitialConfig.widgets[fieldType];
       const widgetType = widget.type;
 
       fields[field.id] = {
         label: field.label,
         type: widgetType,
         valueSources: ["value"],
         fieldSettings: {
-          listValues: options,
+          // IMPORTANT: listValues must be undefined for non-select/multiselect fields otherwise RAQB doesn't like it. It ends up considering all the text values as per the listValues too which could be empty as well making all values invalid
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/lib/getQueryBuilderConfig.ts:37]: Verified in unit test

File: packages/app-store/routing-forms/lib/reportingUtils.ts [hunk 5]
```diff
@@ -0,0 +1,41 @@
+import type { z } from "zod";
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/lib/reportingUtils.ts:1]: Refactored out from reporting endpoint to be able to use in csv endpoint.

File: apps/web/playwright/lib/pageObject.ts [hunk 6]
```diff
@@ -0,0 +1,19 @@
+import type { Page } from "@playwright/test";
```
Comment (hariombalhara) [inline apps/web/playwright/lib/pageObject.ts:1]: Plan to add more such interactions that could be shared across all types of Playwright tests for our app.

File: apps/web/playwright/fixtures/users.ts [hunk 7]
```diff
@@ -455,11 +459,36 @@ export const createUsersFixture = (
...
+                type: "select",
+                label: "Select",
+                identifier: "test-select-new-format",
+                options: [
+                  {
+                    id: selectOption1Uuid,
+                    label: "Option-1",
+                  },
+                  {
+                    id: selectOption2Uuid,
```
Comment (hariombalhara) [inline apps/web/playwright/fixtures/users.ts:491]: Testing all these in playwright

File: packages/app-store/routing-forms/api/responses/[formId].ts [hunk 8]
```diff
@@ -6,15 +6,30 @@ import { entityPrismaWhereClause, canEditEntity } from "@calcom/lib/entityPermis
...
+}) {
+  if (field.options) {
+    const optionIds = ensureStringOrStringArray(value);
+    return getLabelsFromOptionIds({ options: field.options, optionIds });
+  } else {
+    return (value instanceof Array ? value : [value]).map(String);
+  }
+}
+
+async function* getResponses(formId: string, fields: Fields) {
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/api/responses/[formId].ts:32]: headerFields -> fields .More appropriate name

File: packages/app-store/routing-forms/api/responses/[formId].ts [hunk 9]
```diff
@@ -34,16 +49,12 @@ async function* getResponses(
...
+        const fieldResponse = fieldResponses[field.id];
         const value = fieldResponse?.value || "";
-        let serializedValue = "";
-        if (value instanceof Array) {
-          serializedValue = value.map((val) => escapeCsvText(val)).join(" | ");
-        } else {
-          // value can be a number as well for type Number field
-          serializedValue = escapeCsvText(String(value));
-        }
+        const serializedValue = getHumanReadableFieldResponseValue({ field, value })
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/api/responses/[formId].ts:55]: Ensure that label is returned even for options which has id saved.

File: packages/app-store/routing-forms/lib/FieldTypes.ts [hunk 10]
```diff
@@ -0,0 +1,30 @@
+export const FieldTypes = [
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/lib/FieldTypes.ts:1]: Was needed because it was used by getQueryBuilderConfig and the tests were failing for it due to it being imported from a page component.

File: packages/app-store/routing-forms/pages/reporting/[...appPages].tsx [hunk 11]
```diff
@@ -184,13 +184,22 @@ export default function ReporterWrapper({
...
+  }, []);
+
   return (
     <SingleForm
       form={form}
       appUrl={appUrl}
       Page={({ form }) => (
-        <div className="route-config">
-          <Reporter form={form} />
+        <div className="route-config bg-default fixed inset-0 w-full overflow-scroll pt-12 ltr:mr-2 rtl:ml-2 sm:pt-0">
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/pages/reporting/[...appPages].tsx:201]: Moved the classes here to avoid flash of unwanted content

File: packages/app-store/routing-forms/playwright/tests/basic.e2e.ts [hunk 12]
```diff
@@ -259,11 +261,17 @@ test.describe("Routing Forms", () => {
...
+        "Select",
+      ]);
       expect(responses).toEqual([
-        ["event-routing", "", ""],
-        ["external-redirect", "", ""],
-        ["custom-page", "", ""],
+        ["event-routing", "Option-2", "Option-2", "Option-2", "Option-2"],
+        ["external-redirect", "Option-2", "Option-2", "Option-2", "Option-2"],
+        ["custom-page", "Option-2", "Option-2", "Option-2", "Option-2"],
       ]);
```
Comment (hariombalhara) [inline packages/app-store/routing-forms/playwright/tests/basic.e2e.ts:275]: Verifying data submission for both multiseelct and select in old and new options format.

File: packages/prisma/seed-app-store.ts [hunk 13]
```diff
@@ -131,17 +132,17 @@ async function seedAppData() {
...
         {
-          id: "d4292635-9f12-17b1-9153-c3a854649182",
+          id: multiSelectLegacyFieldId,
           type: "multiselect",
           label: "Multi Select(with legacy `selectText`)",
           identifier: "multi",
           selectText: "Option-1\nOption-2",
           required: false,
         },
         {
```
Comment (hariombalhara) [inline packages/prisma/seed-app-store.ts:144]: Changed Ids. They were accidentally same, causing issues.

**Review by CarinaWolli — APPROVED** [review]
LGTM 👍
