### PR TITLE
fix: Namespaced react embeds not working with Floating and Element Click Popups

### LINKED ISSUE #12983: [CAL-3366] Avoid duplication of inline embed for same namespace
### Issue Summary

On my website (https://disigner.nl/) I've implemented the Cal.com inline embed in a popup. The website is build with Wordpress and Elementor. In Elementor Popup builder the embed looks fine https://gyazo.com/0e6d4325c996ee662eef5d9e4bf21d96. But when I try it on the frontend on top of the embed there is a loading animation https://gyazo.com/3ec607bab36272e305750c44bd677f8c. When I go to the code it looks like the <cal-inline> loads 2 times. 

### Steps to Reproduce

Here is a video: https://gyazo.com/069619a002c97612ee4be32e2d2a8f2d

1. Pressed the yellow phone button in the header
2. A popup shows with 2 loading animations
3. The bottom animation loads but the top does not, which should not be there in the first place.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- 2 loading animations. It seems that somehow the <cal-inline> is implemented 2 times when looking at it in the front-end.

### Expected Results

- When pressing the popup the inline embed should load only 1 time.

### Technical details

- Wordpress 6.4.2
- Elementor 3.18.2
- Elementor Pro 3.18.1
- WP Rocket 3.15.6
- PHP version: 8.1.24

### Evidence
https://gyazo.com/069619a002c97612ee4be32e2d2a8f2d

<sub>[CAL-3366](https://linear.app/calcom/issue/CAL-3366/avoid-duplication-of-inline-embed-for-same-namespace)</sub>

### LINKED ISSUE #13388: [CAL-3012] Fix embed behaviour with soft navigations when namespaces are used
1. If the element added by inline embed is removed, re-executing the  **inline** instruction is ignored.
2. If a namespace is created after embed.js has executed it doesn't work at all
3. Repeat execution of **init** instruction causes the namespace to stop executing further instructions

Also, we need to add Unit/E2E tests to verify that the API keeps working in all these cases.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3012](https://linear.app/calcom/issue/CAL-3012/fix-embed-behaviour-with-soft-navigations-when-namespaces-are-used)</sub>

### LINKED ISSUE #13458: [CAL-3052] Floating Button Popup and Element Click Popup don't work with namespaces
Initially reported on Intercom.
Private Link: [https://app.intercom.com/a/inbox/z9l4o9ru/inbox/conversation/5409?view=List](https://app.intercom.com/a/inbox/z9l4o9ru/inbox/conversation/5409?view=List)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3052](https://linear.app/calcom/issue/CAL-3052/floating-button-popup-and-element-click-popup-dont-work-with)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #13388 
Fixes #13458
Fixes #12983

- `getCalApi` didn't have support for namespace. So, floating and element-click popup code for React which uses `getCalApi` wasn't working with namespaces. - Support has been added to `getCalApi` for namespace now in a backward compatible fashion.  Added e2e tests as well for floating and element-click popup in embed-react. The issue wasn't caught because we were just having automation tests for inline embed in embed-react.
- The case where a namespace was created after embed.js was loaded, wasn't working. It wasn't part of playground. So, added the flow in playground  and added an e2e test as well.
- The case where someone re-initializes a namespace and gives repeat instruction for 'inline' embed is now handled.  We won't add inline embed twice now. Added e2e as well to test this scenario for both default and non-default namespace.

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
See the loom https://www.loom.com/share/f627dfba74b8477aa4e88ea85eebf748

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by hariombalhara** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #13386** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/13386?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/calcom/cal.com/13386?utm_source=stack-comment).

File: packages/embeds/embed-react/src/index.ts [hunk 1]
```diff
@@ -1,14 +1,20 @@
...
+import type { GlobalCal, GlobalCalWithoutNs } from "@calcom/embed-core";
 import EmbedSnippet from "@calcom/embed-snippet";
 
 import Cal from "./Cal";
 
-export const getCalApi = (embedJsUrl?: string): Promise<GlobalCal> =>
-  new Promise(function tryReadingFromWindow(resolve) {
-    EmbedSnippet(embedJsUrl);
-    const api = window.Cal;
+export const getCalApi = (options?: {
```
Comment (hariombalhara) [inline packages/embeds/embed-react/src/index.ts:8]: We are changing the API here in a breaking fashion. 

Users who are using older version of embed-react, would use the old API(but that won't support namespacing) and those moving to new versions would have to use the new API which supports namespacing.

File: packages/embeds/embed-react/src/index.ts [hunk 2]
```diff
@@ -1,14 +1,20 @@
...
+  embedJsUrl?: string;
+  namespace?: string;
+}): Promise<GlobalCal | GlobalCalWithoutNs> => {
+  options = options || {};
```
Comment (hariombalhara) [inline packages/embeds/embed-react/src/index.ts:12]: We might also support options as a string as well which is backward compatible. 🤔

File: packages/embeds/embed-core/src/embed.ts [hunk 3]
```diff
@@ -415,8 +415,17 @@ class CalApi {
...
 
   init(namespaceOrConfig?: string | InitArgConfig, config = {} as InitArgConfig) {
+    let namespace = "";
     if (typeof namespaceOrConfig !== "string") {
       config = (namespaceOrConfig || {}) as Config;
+    } else {
+      namespace = namespaceOrConfig;
+    }
+
+    if (!globalCal.ns[namespace].instance && namespace !== this.cal.namespace) {
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed.ts:425]: If a namespace encounters the instruction for some other namespace, create an instance for that namespace and that would handle related work.

Ideally this should happen with default namespace encountering other namespace instruction. We can explicitly confirm that here I think.

File: packages/embeds/embed-core/index.html [hunk 4]
```diff
@@ -51,6 +51,8 @@
               const namespace = ar[1];
               api.q = api.q || [];
               typeof namespace === "string" ? (cal.ns[namespace] = api) && p(api, ar) : p(cal, ar);
+              // Also send init to the default namespace queue so that the namespace instance can be created which will then take care of it's own queue
+              p(cal, arguments)
```
Comment (hariombalhara) [inline packages/embeds/embed-core/index.html:55]: Need to put this change in embed-snippet as well and other places where we show Cal Snippet.

File: packages/embeds/embed-core/src/embed.ts [hunk 5]
```diff
@@ -458,6 +480,12 @@ class CalApi {
       },
     });
 
+    // If someone re-executes inline embed instruction, we want to ensure that duplicate inlineEl isn't added to the page per namespace
+    if (this.cal.inlineEl && document.body.contains(this.cal.inlineEl)) {
+      console.warn("Inline embed already exists. Ignoring this call");
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed.ts:485]: Adding it back what I reverted here https://github.com/calcom/cal.com/pull/13637/files#diff-e895c26df52266ecfd6334060b1dc6fa05cac4106eee7f713d0a07472cc08d07

Now I am checking for the presence of inlineEl in DOM instead of just checking the property which could be out-of-sync with DOM. So, it seems safe to add it back.

File: apps/web/playwright/fixtures/embeds.ts [hunk 6]
```diff
@@ -43,14 +48,18 @@ export const createEmbedsFixture = (page: Page) => {
               // eslint-disable-next-line @typescript-eslint/ban-ts-comment
               //@ts-ignore
               api = window.Cal.ns[calNamespace];
+              console.log("Using api from namespace-", { calNamespace, api });
             }
-            console.log("PlaywrightTest:", `Adding listener for __iframeReady on namespace:${calNamespace}`);
             if (!api) {
-              throw new Error(`namespace "${calNamespace}" not found`);
+              console.log(`namespace "${calNamespace}" not found yet - Trying again`);
+              setTimeout(tryAddingListener, 500);
```
Comment (hariombalhara) [inline apps/web/playwright/fixtures/embeds.ts:55]: Handle the case when namespace is created after a CTA is clicked and not on page load.

File: packages/embeds/embed-react/src/index.ts [hunk 7]
```diff
@@ -1,14 +1,32 @@
...
 
-export const getCalApi = (embedJsUrl?: string): Promise<GlobalCal> =>
-  new Promise(function tryReadingFromWindow(resolve) {
-    EmbedSnippet(embedJsUrl);
-    const api = window.Cal;
+export function getCalApi(options?: {
+  embedJsUrl?: string;
+  namespace?: string;
+}): Promise<GlobalCal | GlobalCalWithoutNs>;
+export function getCalApi(embedJsUrl: string): Promise<GlobalCal | GlobalCalWithoutNs>;
```
Comment (hariombalhara) [inline packages/embeds/embed-react/src/index.ts:12]: This is backward compatible signature.

File: packages/embeds/embed-core/src/embed.ts [hunk 8]
```diff
@@ -211,7 +211,7 @@ export class Cal {
     return instruction;
   }
 
-  processQueue(queue: IArguments[]) {
+  processQueue(queue: Queue) {
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed.ts:214]: Using custom type here.

File: packages/embeds/embed-core/src/embed.ts [hunk 9]
```diff
@@ -766,13 +795,16 @@ class CalApi {
   }
 }
 
+// eslint-disable-next-line @typescript-eslint/no-explicit-any
+export type Queue = any[];
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed.ts:799]: A queue basically holds the arguments to all the instruction functions, so it could be anything.

File: packages/embeds/embed-core/src/preview.ts [hunk 10]
```diff
@@ -7,41 +9,7 @@ if (!bookerUrl || !embedLibUrl) {
...
-        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
-        //@ts-ignore
-        typeof namespace === "string" ? (cal.ns[namespace] = api) && p(api, ar) : p(cal, ar);
-        return;
-      }
-      p(cal, ar);
-    };
-})(window, embedLibUrl, "init");
-
+EmbedSnippet();
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/preview.ts:12]: Reuse embed snippet

**Review by sean-brydon — APPROVED** [review]
Tested this - can confirm it fixes the issues mentioned. 

Thanks for the loom and tests were helpful <3

File: packages/embeds/embed-core/src/preview.ts [hunk 11]
```diff
@@ -26,22 +29,25 @@ if (!bookerUrl || !embedLibUrl) {
...
+          // Make sure that even after re-execution of the snippet, the namespace is not overridden
+          cal.ns[namespace] = cal.ns[namespace] || api;
+          p(cal.ns[namespace], ar);
+          p(cal, ["initNamespace", namespace]);
+        } else p(cal, ar);
         return;
       }
       p(cal, ar);
     };
-})(window, embedLibUrl, "init");
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/preview.ts:43]: It caused the previews to break :(
