### PR TITLE
Fix/event type clone

### LINKED ISSUE #5504: [CAL-364] Event Type clone defaults location to Cal Video
When you clone an event type it doesn't clone the location for some reason and always defaults to Cal Video, when it should ideally carry over the location data as well.

_And even after I manually set a cloned event type location to Zoom, it reverts to cal video after saving :\ After going back in to edit the new event and setting it to zoom again, it seems to stick_

> From [SyncLinear.com](https://synclinear.com) | [CAL-364](https://linear.app/calcom/issue/CAL-364/event-type-clone-defaults-location-to-cal-video)

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?
Follow up from PR https://github.com/calcom/cal.com/pull/5540
 
When duplicating event type, input locations shouldn't be override by default location in event type create trpc.

Fixes #5504 

**Environment**: Staging(main branch) / Production

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/trpc/server/routers/viewer/eventTypes.tsx [hunk 1]
```diff
@@ -360,7 +360,8 @@ export const eventTypesRouter = router({
     };
 
     const appKeys = await getAppKeysFromSlug("daily-video");
-    if (typeof appKeys.api_key === "string") {
+    // Shouldn't override input locations
+    if (rest.locations?.length === 0 && typeof appKeys.api_key === "string") {
```
Comment (alannnc) [inline packages/trpc/server/routers/viewer/eventTypes.tsx:364]: When creating new locations are empty array []

**Review by leog — APPROVED** [review]
LGTM
