### PR TITLE
fix: restricting platform user from creating another regular org

### LINKED ISSUE #20797: [CAL-5557] Restrict users part of platform team or platform org from creating regular organizations
We don't support multiple profiles for a user, so a user can't be in multiple organizations.

Just remember that we already assert the organization [creator can't be part of another organization](https://github.com/calcom/cal.com/blob/e01a6f16af15b055466efe337bed0148b483c4c2/packages/features/ee/organizations/lib/server/orgCreationUtils.ts#L207) and it didn't error in this case because we [intentionally return a non-org profile for Platform organization ](https://github.com/calcom/cal.com/blob/e01a6f16af15b055466efe337bed0148b483c4c2/packages/lib/server/repository/user.ts#L373)member intentionally and thus the issue.

I think we would have to use a Platform compatible method to check being part of organization, that could be checking membership

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-5557](https://linear.app/calcom/issue/CAL-5557/restrict-users-part-of-platform-team-or-platform-org-from-creating)</sub>

### PR DESCRIPTION
**Pull request by romitg2**
## What does this PR do?

- Fixes #20797  (GitHub issue number)
- Fixes CAL-5557 (Linear issue number - should be visible at the bottom of the GitHub issue description)

### how I Fixed?

- we had access of which team orgOwner(user trying to create org)  is part of, using that i checked weather it belongs to an team with isOrganization flag enabled

[type of orgOwner](https://github.com/calcom/cal.com/blob/80f2e61189f5855232af3f933a0147c0690d1f6b/packages/features/ee/organizations/lib/server/orgCreationUtils.ts#L68)

[orgOwner data coming from here](https://github.com/calcom/cal.com/blob/80f2e61189f5855232af3f933a0147c0690d1f6b/packages/features/ee/organizations/lib/server/orgCreationUtils.ts#L247)

#### NOTE:
- i haven't tested it, but i've checked code and it's supposed to work fine.

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

    

---

## Summary by mrge
Prevented users who are already part of another organization from creating a new regular organization.

- **Bug Fixes**
  - Added a check to block org creation if the user belongs to a team marked as an organization.

### CODE REVIEW

**Comment by romitg2** [comment]
@hariombalhara

**Review by TusharBhatt1 — COMMENTED** [review]
LGTM

File: packages/features/ee/organizations/lib/server/orgCreationUtils.ts [hunk 1]
```diff
@@ -204,7 +204,8 @@ export async function assertCanCreateOrg({
   });
 
   // Let slug verification be done before it as that gives better error message if the user creating the org is already a part of the org(i.e. the org exist and he is a member)
-  if (orgOwner.profile?.organizationId) {
+  const isPartOfAnotherOrg = orgOwner.teams.some((team) => team.team.isOrganization);
+  if (isPartOfAnotherOrg) {
```
Comment (hariombalhara) [inline packages/features/ee/organizations/lib/server/orgCreationUtils.ts:208]: Lets improve the message to inform clearly that it is a Platform or Organizastion

'You are part of Platform organization'

'You are part of Organization'

Also, we need to ensure that membership is in accepted state. Plus, let's add comments as to why we aren;t checking for profile.organizationId.

**Review by hariombalhara — CHANGES_REQUESTED** [review]
Thanks @romitg2 for the PR 🙏

Left a comment

**Comment by romitg2** [comment]
@TusharBhatt1 @hariombalhara

**Comment by supalarry** [comment]
@hariombalhara I created PR https://github.com/calcom/cal.com/pull/20972 that has the check in frontend - see linear ticket with screenshots.

1. platform customers can't create orgs
2. and org customers can't create platform -> something that this PR doesn't handle so IMO we can go with my PR above

**Comment by hariombalhara** [comment]
@supalarry I think we need both. Have approved your PR as that is better UX wise.

We need this PR as well as it restricts in backend, to avoid this kind of scenario through some API call in future

**Review by hariombalhara — APPROVED** [review]
