### PR TITLE
fix: #10553 - "Apps" child items not highlighted when selected

### LINKED ISSUE #10553: [Bug]: Selected section not highlighted (App Store and Installed Apps)
Found a bug? Please fill out the sections below. 👍

### Issue Summary

App Store and Installed Apps not highlighted(selected) when it gets clicked unlike the other ones.

### Steps to Reproduce

1. Go to cal.com
2. Clicked on Apps Section on the left side navigation bar.
3. Click on the Installed Apps or App Store.

### Actual Results

bug cal com

Installed Apps is selected in the above image but it is not highlighted in the navigation bar.

### PR DESCRIPTION
**Pull request by devnadeemashraf**
## What does this PR do?

Fixes #10553

Loom Link: https://www.loom.com/share/4b9be712bfd1432dbaf0e893e1779b3c?sid=fbb2afed-3a6a-4742-9ef8-5c6d707172e9
## Type of change

- [x]  Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
I have provided a Loom link with both the issue and the Fix. 

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist
- I have tested the fix and its working as expected.

### CODE REVIEW

File: packages/features/shell/Shell.tsx [hunk 1]
```diff
@@ -655,9 +655,11 @@ const NavigationItem: React.FC<{
           href={item.href}
           aria-label={t(item.name)}
           className={classNames(
-            "[&[aria-current='page']]:bg-emphasis  text-default group flex items-center rounded-md px-2 py-1.5 text-sm font-medium",
+            item.child
+              ? `text-default group flex items-center rounded-md px-2 py-1.5 text-sm font-medium [&[aria-current='page']]:bg-transparent`
+              : `[&[aria-current='page']]:bg-emphasis  text-default group flex items-center rounded-md px-2 py-1.5 text-sm font-medium`,
```
Comment (Udit-takkar) [inline packages/features/shell/Shell.tsx:660]:
```suggestion
         "text-default group flex items-center rounded-md px-2 py-1.5 text-sm font-medium " ,
            item.child
              ? `[&[aria-current='page']]:bg-transparent`
              : `[&[aria-current='page']]:bg-emphasis`,
```

**Review by Udit-takkar — APPROVED** [review]
LGTM
