### PR TITLE
fix: make delete confirmation consistent across schedules

### LINKED ISSUE #26299: Delete confirmation missing in Availability page for schedules
### Issue Summary

Deleting a schedule from the detailed view shows a confirmation dialog, but deleting it from the list view (Availability page) does not. For consistency, both actions should show the same confirmation dialog.

### Steps to Reproduce

1. Go to availability page and click on the delete button. The schedule gets deleted without a confirmation.
2. Open the detailed view of a schedule and try to delete it. A confirmation dialog is opened for deletion.

### Actual Results

- Deleting a schedule from the detailed view shows a confirmation dialog, but deleting it from the availability page deletes the schedule immediately without any confirmation.

### Expected Results

- Deleting a schedule from both the detail view and the list view should show a confirmation dialog for consistent behavior and to prevent accidental deletions.

### Evidence
 
https://github.com/user-attachments/assets/cdce4993-8311-414d-a82f-e46173c93806

### PR DESCRIPTION
**Pull request by Manas-Kenge**
## What does this PR do?

Deleting a schedule from both the detail view and the list view shows a confirmation dialog for consistent behavior and to prevent accidental deletions.

- Fixes #26299 
- Fixes CAL-6995

#### Video Demo (if applicable):

- Before

https://github.com/user-attachments/assets/0b3f0ddd-0cfc-412e-8f5d-08c232acb45d

- After

https://github.com/user-attachments/assets/f2615035-fbd7-490d-839c-dd85e71457d4

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). N/A 
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

File: packages/features/schedules/components/ScheduleListItem.tsx [hunk 1]
```diff
@@ -66,8 +69,8 @@ export function ScheduleListItem({
                 )
                 // sort the availability strings as per user's weekstart (settings)
                 .sort(sortAvailabilityStrings(i18n.language, displayOptions?.weekStart))
-                .map((availabilityString, index) => (
-                  <Fragment key={index}>
+                .map((availabilityString) => (
```
Comment (dhairyashiil) [inline packages/features/schedules/components/ScheduleListItem.tsx]: 'availabilityString' has 'any' type, please use proper types

Comment (dhairyashiil) [reply packages/features/schedules/components/ScheduleListItem.tsx]: line number 63: availability also have any type, please fix that as well

**Review by dhairyashiil — CHANGES_REQUESTED** [review]
Left some comments

**Review by dhairyashiil — DISMISSED** [review]
LGTM

**Review by emrysal — DISMISSED** [review]
Looks good to me, lgtm 👏 

Thank you for your contribution.

**Review by emrysal — APPROVED** [review]
Made some changes to tests, re-approved.
