### PR TITLE
fix: system default theme for dashboard and booking page

### LINKED ISSUE #15284: [CAL-3917] Dashboard Theme: system default not working
### Issue Summary

The `System default` theme setting in the appearance settings doesn't work.

### Steps to Reproduce

1. go to https://app.cal.com/settings/my-account/appearance
2. if OS theme is dark, set cal.com theme to `light`, then set it again to `system default`
3. notice it doesn't change

### Actual Results

- `system default` is `light` even though OS is dark

### Expected Results

- `system default` should be `dark` because OS is dark

### Technical details

- Browser version: chrome 125, macOS 14.3.1

### Evidence

OS is dark:

https://github.com/calcom/cal.com/assets/34947993/c57d778b-37fd-49d0-9a2e-2698866863b4

<sub>[CAL-3917](https://linear.app/calcom/issue/CAL-3917/dashboard-theme-system-default-not-working)</sub>

### PR DESCRIPTION
**Pull request by DeepaPrasanna**
## What does this PR do?

- Fixes #15284 (GitHub issue number)

Summary:

Fixes the theme to get updated to system default for both dashboard and the booking page.

Changes added:

- Whenever the system default option was selected, the `theme` and `appTheme` value was always "" instead of null. The code `values.appTheme ?? null`  always evaluates to "".  Updated it to be null now.
- When `themeToSet` is null, it's value is supposed to be "system", but it was not happening. Fixed that too.

 Please provide a loom video for visual changes to speed up reviews
 Loom Video: https://www.loom.com/share/0c7310b06ccd42698d3dc7ebd3a32ad7?sid=908e416a-949d-47d2-ba16-e9460e0a8017

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [x] N/A-I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [x] N/A-I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

Visit [here](https://app.cal.com/settings/my-account/appearance) and update the dashboard and booking page to be system default. The respective theme should effectively be applied.

### CODE REVIEW

**Review by anikdhabal — COMMENTED** [review]
Great work @DeepaPrasanna

Actually, after v7 in react-hook-form, if we provide null or undefined to an input field, it coalesces to an empty string when the form is submitted.

**Review by anikdhabal — CHANGES_REQUESTED** [review]
Please fix this in the other two places as well (team and org appearance) and instead of explicitly performing this operation
 
`values.appTheme === "" ? null : values.appTheme`, could you find a way to update the input in the `ThemeLabel` component?

 I think we can do it using the `setValueAs`option of the register field in react-hook-form.

**Comment by DeepaPrasanna** [comment]
> Please fix this in the other two places as well (team and org appearance) and instead of explicitly performing this operation
> 
> `values.appTheme === "" ? null : values.appTheme`, could you find a way to update the input in the `ThemeLabel` component?
> 
> I think we can do it using the `setValueAs`option of the register field in react-hook-form.

The `setValueAs`option only applies to text input.

File: packages/lib/hooks/useTheme.tsx [hunk 1]
```diff
@@ -11,6 +11,7 @@ import { useEmbedTheme } from "@calcom/embed-core/embed-iframe";
  */
 // eslint-disable-next-line @typescript-eslint/ban-types
 export default function useTheme(themeToSet: "system" | (string & {}) | undefined | null, getOnly = false) {
+  themeToSet = themeToSet ? themeToSet : "system";
```
Comment (anikdhabal) [inline packages/lib/hooks/useTheme.tsx:14]: I don't think this is best practice, there are certain checks and conditions when themeToSet is undefined or null.

Instead of resetting it, can we handle this when calling this hook? For example, when calling this hook from the appearance component, can we not do it like this: `useTheme(user?.appTheme ?? "system")`?

**Review by anikdhabal — CHANGES_REQUESTED** [review]

**Review by anikdhabal — APPROVED** [review]
LGTM

File: packages/features/ee/teams/pages/team-appearance-view.tsx [hunk 2]
```diff
@@ -92,7 +92,7 @@ const ProfileView = ({ team }: ProfileViewProps) => {
             handleSubmit={(values) => {
               mutation.mutate({
                 id: team.id,
-                theme: values.theme || null,
+                theme: values.theme === "" ? null : values.theme,
```
Comment (DeepaPrasanna) [inline packages/features/ee/teams/pages/team-appearance-view.tsx:95]: same here too, i dont understand why the change was required

File: packages/features/ee/organizations/pages/settings/appearance.tsx [hunk 3]
```diff
@@ -80,7 +80,7 @@ const OrgAppearanceView = ({
         form={themeForm}
         handleSubmit={(value) => {
           mutation.mutate({
-            theme: value.theme ?? null,
+            theme: value.theme === "" ? null : value.theme,
```
[the remark this answers is not in the document]
Comment (anikdhabal) [reply packages/features/ee/organizations/pages/settings/appearance.tsx:83]: Can you explain a bit? So it means your changes was wrong?

Comment (DeepaPrasanna) [reply packages/features/ee/organizations/pages/settings/appearance.tsx:83]: It seems i misunderstood. sorry, my bad!
