### PR TITLE
fix: incorrect booking title for diff users

### LINKED ISSUE #16392: [CAL-4191] Wrong text for team admin that is not part of booking
A team admin or owner can view all the teams' bookings, even when they are not part of the bookings.  When visiting the details of the booking (/booking/uid) as an admin it says 'You are meeting with Attendee Name' instead of 'Host Name is meeting with Attendee Name'

User is not part of this booking and it looks like that:

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4191](https://linear.app/calcom/issue/CAL-4191/wrong-text-for-team-admin-that-is-not-part-of-booking)</sub>

### PR DESCRIPTION
**Pull request by anikdhabal**
## What does this PR do?

- Fixes #16392 
- Fixes [CAL-4191](https://linear.app/calcom/issue/CAL-4191/wrong-text-for-team-admin-that-is-not-part-of-booking)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A-I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] N/A-I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

### CODE REVIEW

File: apps/web/modules/bookings/views/bookings-single-view.tsx [hunk 1]
```diff
@@ -315,8 +315,23 @@ export default function Success(props: PageProps) {
...
+        });
+      }
+      if (isAttendee) {
+        return t(`${titlePrefix}emailed_you_and_attendees${titleSuffix}`, {
+          user: host,
+        });
+      }
+      return t(`${titlePrefix}emailed_host_and_attendee${titleSuffix}`, {
+        host,
+        attendee,
```
Comment (anikdhabal) [inline apps/web/modules/bookings/views/bookings-single-view.tsx:334]: For guests: You are meeting with Host Name
For Hosts: You are meeting with Guest name
For Admins/Owners and for any user that are not part of the booking: Host Name is meeting with Guest Name

**Review by Praashh — APPROVED** [review]
