### PR TITLE
fix: insights - avoid using in conditional when fetching data

### LINKED ISSUE #10068: [CAL-2147] Insights getTotalRescheduledEvents goes wrong for large booking counts
Insights getTotalRescheduledEvents goes wrong for large booking counts. - probably same for getTotalCanceledEvents. Looks like we crash when there's a large amount of bookings due to a limit of 32767 on the Prisma `in` clause. 

 

<sub>[CAL-2147](https://linear.app/calcom/issue/CAL-2147/insights-gettotalrescheduledevents-goes-wrong-for-large-booking-counts)</sub>

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

Fixes #10068 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] Chore (refactoring code, technical debt, workflow improvements)

## How should this be tested?

- Are there environment variables that should be set? No.
- What are the minimal test data to have? Using yarn seed-insights from packages/prisma can help.
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/features/insights/server/events.ts [hunk 1]
```diff
@@ -75,45 +75,36 @@ class EventsInsights {
     return result;
   };
 
-  static getBaseBookingForEventStatus = async (where: Prisma.BookingTimeStatusWhereInput) => {
-    const baseBookings = await prisma.bookingTimeStatus.findMany({
+  static getBaseBookingCountForEventStatus = async (where: Prisma.BookingTimeStatusWhereInput) => {
+    const baseBookings = await prisma.bookingTimeStatus.count({
```
Comment (alannnc) [inline packages/features/insights/server/events.ts:79]: Converted to return count from DB.

File: packages/features/insights/server/events.ts [hunk 2]
```diff
@@ -75,45 +75,36 @@ class EventsInsights {
...
-      select: {
-        id: true,
-      },
     });
 
     return baseBookings;
   };
 
-  static getTotalCompletedEvents = async (bookingIds: number[]) => {
+  static getTotalCompletedEvents = async (whereConditional: Prisma.BookingTimeStatusWhereInput) => {
```
Comment (alannnc) [inline packages/features/insights/server/events.ts:86]: Receiving whereConditional should be better than looking up many ids.

**Review by emrysal — APPROVED** [review]
Great fix 🚀
