### PR TITLE
fix: improve Insights empty state responsive design at 320px

### LINKED ISSUE #25797: Insights header Background misaligned with Text
The background is not aligned perfectly in the insights section ( 320 px ) the text is overflowing as we can see in the image below
Current State:- 
Image

### PR DESCRIPTION
**Pull request by Recxsmacx**
fixes https://github.com/calcom/cal.com/issues/25797

---
## Summary by cubic
Improved the Insights empty state layout at 320px for better readability on small screens. Fixes cal.com issue #25797.

- **UI Improvements**
  - Set picture/img to min-h-full to match container height on narrow viewports.
  - Adjusted padding: px-4 (mobile), sm:px-8, md:px-14.
  - Made title and description font sizes responsive: text-2xl/sm:text-3xl and text-sm/sm:text-base.

<sup>Written for commit 5a87e72f020a3eae01bbbe950f516bd483338392. Summary will update automatically on new commits.</sup>

### CODE REVIEW

**Comment by Recxsmacx** [comment]
@Pallava-Joshi Created a new pr because merge conflicts were a mess this is completely able top merge with no merge conflicts need your approval

**Review by pallava-joshi — DISMISSED** [review]
working, LGTM.

File: apps/web/modules/shell/UpgradeTip.tsx [hunk 1]
```diff
@@ -45,18 +45,18 @@ export function UpgradeTip({
   return (
     <>
       <div className="relative flex min-h-[295px] w-full items-center justify-between overflow-hidden rounded-lg pb-10">
-        <picture className="absolute min-h-[295px] w-full rounded-lg object-cover">
-          <source srcSet={imageSrc} media="(prefers-color-scheme: dark)" />
+ <picture className="absolute min-h-full w-full rounded-lg object-cover">
```
Comment (keithwillcode) [inline apps/web/modules/shell/UpgradeTip.tsx]:
```suggestion
         <picture className="absolute min-h-full w-full rounded-lg object-cover">
```

**Comment by Recxsmacx** [comment]
@keithwillcode it's cool now?

**Review by keithwillcode — APPROVED** [review]
