### PR TITLE
Fixing add button in Installed Calendars list

### LINKED ISSUE #5778: [CAL-501] Add calendar select is visually broken on /apps/installed/calendar
### Issue Summary

image

<sub>[CAL-501](https://linear.app/calcom/issue/CAL-501/add-calendar-select-is-broken-on-appsinstalledcalendar)</sub>

### PR DESCRIPTION
**Pull request by leog**
## What does this PR do?

The add button for installed calendars was broken. Fixing it.

Before:
image

After:
image

Fixes #5778 

**Environment**: Staging(main branch) / Production

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

Go to http://app.cal.dev/apps/installed/calendar and see the "+ Add" button with correct styles.

### CODE REVIEW

File: apps/web/components/apps/AdditionalCalendarSelector.tsx [hunk 1]
```diff
@@ -80,11 +78,16 @@ const AdditionalCalendarSelector = ({ isLoading }: AdditionalCalendarSelectorPro
                 width: "max-content",
                 right: "0",
               }),
+              indicatorSeparator: (defaultStyles) => ({
+                ...defaultStyles,
+                display: "none",
+              }),
```
Comment (sean-brydon) [inline apps/web/components/apps/AdditionalCalendarSelector.tsx:84]: We can actually just no render this component by passing in null component  into react select

```
 components={{
        IndicatorSeparator: () => null,
      }}
```

**Review by sean-brydon — APPROVED** [review]

File: apps/web/components/apps/AdditionalCalendarSelector.tsx (hunk 1 above)
Comment (sean-brydon) [reply apps/web/components/apps/AdditionalCalendarSelector.tsx:84]: NIT and not needed just as a heads up :)
