### PR TITLE
fix: Snippet path in preview

### LINKED ISSUE #14831: [CAL-3598] Embed Previews not working
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3598](https://linear.app/calcom/issue/CAL-3598/embed-previews-not-working)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #14831 
Fixes CAL-3598

Regression from https://github.com/calcom/cal.com/pull/13386/files#r1586013449

Added a regression test as well. The tests were there for preview flow but the bug caused the localhost:3000 to be hardcoded, they were all running fine as localhost:3000 is setup properly in CI as well but not in production.

Added a test now to ensure that `embedLibUrl` is being used.

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
Pretty straightforward revert. So, nothing to test. Added an automation scenario as well.
Also, it can't be replicated easily locally.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by hariombalhara** [comment]
* **#14830** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/14830?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hariombalhara and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: packages/embeds/embed-core/src/preview.ts [hunk 1]
```diff
@@ -47,7 +47,7 @@ if (!bookerUrl || !embedLibUrl) {
       }
       p(cal, ar);
     };
-})(window, "//localhost:3000/embed/embed.js", "init");
+})(window, embedLibUrl, "init");
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/preview.ts:50]: It was an accidental change that got committed.
https://github.com/calcom/cal.com/pull/13386/files#r1586013449

**Review by keithwillcode — APPROVED** [review]

**Review by sean-brydon — APPROVED** [review]
Tested - LGTM 

thanks for tests <3
