### PR TITLE
fix: layout of dialog (edit location) on bookings page

### LINKED ISSUE #20267: Fix layout for edit location dialog in bookings page
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. (for example) Went to ...
2. Clicked on...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

Image

- What's happening right now that is different from what is expected

### Expected Results

Image

- This is an ideal result that the system should get after the tests are performed

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

### PR DESCRIPTION
**Pull request by krakenftw**
…ponent

## What does this PR do?

- Fixes #20267 (GitHub issue number)
- Fixes CAL-XXXX (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Visual Demo (For contributors especially)

Before - 
image

After -
image

A visual demonstration is strongly recommended, for both the original and new change **(video / image - any one)**.

#### Video Demo (if applicable):

- Show screen recordings of the issue or feature.
- Demonstrate how to reproduce the issue, the behavior before and after the change.

#### Image Demo (if applicable):

- Add side-by-side screenshots of the original and updated change.
- Highlight any significant change(s).

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

### CODE REVIEW

**Comment by retrogtx** [comment]
hey @krakenftw a test is failing

**Comment by retrogtx** [comment]
Cant seem to commit to your PR

The test is just prettier failing, to fix it just run this in your terminal:

 npx prettier --write \
  apps/web/components/apps/AdditionalCalendarSelector.tsx \
  apps/web/components/apps/AppPage.tsx \
  apps/web/components/dialog/RerouteDialog.tsx \
  apps/web/components/dialog/RescheduleDialog.tsx \
  apps/web/components/getting-started/components/AppConnectionItem.tsx \
  apps/web/components/getting-started/steps-views/ConnectCalendars.tsx \
  apps/web/components/getting-started/steps-views/ConnectedVideoStep.tsx \
  apps/web/components/getting-started/steps-views/SetupAvailability.tsx \
  apps/web/components/getting-started/steps-views/UserSettings.tsx \
  apps/web/components/security/DisableUserImpersonation.tsx \
  apps/web/components/security/EnableTwoFactorModal.tsx \
  apps/web/components/settings/platform/oauth-clients/OAuthClientCard.tsx \
  apps/web/components/setup/EnterpriseLicense.tsx \
  apps/web/components/ui/UsernameAvailability/UsernameTextfield.tsx \
  apps/web/components/ui/form/DatePicker.tsx




And then push the changes!

File: apps/web/components/dialog/EditLocationDialog.tsx [hunk 1]
```diff
@@ -328,25 +328,25 @@ export const EditLocationDialog = (props: ISetLocationDialog) => {
...
+              setEditingLocationType?.("");
+              locationFormMethods.unregister(["locationType", "locationLink"]);
+            }}
+            type="button"
+            color="secondary">
+            {t("cancel")}
+          </Button>
+          <Button data-testid="update-location" type="submit" disabled={isLocationUpdating}>
+            {t("update")}
+          </Button>
```
Comment (anikdhabal) [inline apps/web/components/dialog/EditLocationDialog.tsx:348]: It is now outside of the Form

Comment (krakenftw) [reply apps/web/components/dialog/EditLocationDialog.tsx]: Moved `Form` below the Footer but i have another option where i can remove the Form and directly handle using `onClick`. Let me know if that would be a better choice.

A few other tests are failing but ig thats just my local setup.

File: apps/web/components/dialog/EditLocationDialog.tsx [hunk 2]
```diff
@@ -223,55 +223,55 @@ export const EditLocationDialog = (props: ISetLocationDialog) => {
...
+                "locationPhoneNumber",
+              ]);
+            } catch (error) {
+              // Let the user retry
+              setIsLocationUpdating(false);
+            }
+          }}>
+          <div className="flex flex-row space-x-3">
+            <div className="bg-subtle mx-auto flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-full sm:mx-0 sm:h-10 sm:w-10">
+              <Icon name="map-pin" className="text-emphasis h-6 w-6" />
```
Comment (TusharBhatt1) [inline apps/web/components/dialog/EditLocationDialog.tsx:261]: use `size-6 , size-12 , sm:size-10` instead of `h-6 w-6` `h-12 w-12` and `sm:size-10`

**Comment by krakenftw** [comment]
@TusharBhatt1 @anikdhabal Anything left to merge here?

**Comment by krakenftw** [comment]
@retrogtx I cant run the linting check  (`yarn lint`) on my end, it also seems to be failing on the action? am i missing something

**Comment by retrogtx** [comment]
🤔

image

**Comment by krakenftw** [comment]
@retrogtx reverted `size` to `h,w` since size was causing issues with layout and sizing

**Review by retrogtx — APPROVED** [review]
