### PR TITLE
fix: reduce abnormal spacing in calendar invite

### LINKED ISSUE #18734: [CAL-5050] Reduce spaces in calendar invite description.
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-5050](https://linear.app/calcom/issue/CAL-5050/reduce-spaces-in-calendar-invite-description)</sub>

### PR DESCRIPTION
**Pull request by retrogtx**
## What does this PR do?

- Fixes #18734 (GitHub issue number)
- Fixes CAL-[5050](https://linear.app/calcom/issue/CAL-5050/reduce-spaces-in-calendar-invite-description) (Linear issue number - should be visible at the bottom of the GitHub issue description)

https://www.loom.com/share/1709011d33e2442186efbde38ebdd56d?sid=ae9c2e7a-e9e5-4740-acad-c12a9825b222

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

You can run -> `yarn test packages/lib/CalEventParser.test.ts`

image

or watch the loom to book meetings manually and check the spacing (requires google calendar to be connected) -> https://www.loom.com/share/1709011d33e2442186efbde38ebdd56d?sid=ae9c2e7a-e9e5-4740-acad-c12a9825b222

### CODE REVIEW

File: packages/lib/CalEventParser.ts [hunk 1]
```diff
@@ -50,42 +41,32 @@ export const getWho = (
...
+        .join("\n")
     : [];
 
-  return `
-${t("who")}:
-${organizer + attendees + teamMembers.join("")}
-  `;
+  return `${t("who")}:\n${organizer}${attendees ? `\n${attendees}` : ""}${
+    teamMembers.length ? `\n${teamMembers}` : ""
+  }`;
```
Comment (TusharBhatt1) [inline packages/lib/CalEventParser.ts:62]: Can we use `&& ` instead of `? :`

File: packages/lib/CalEventParser.ts [hunk 2]
```diff
@@ -336,39 +316,33 @@ export const getRichDescription = (
...
+    `${t("where")}:\n${getLocation(calEvent)}`,
+    getDescription(calEvent, t),
+    getAdditionalNotes(calEvent, t),
+    getUserFieldsResponses(calEvent),
+    includeAppStatus ? getAppsStatus(calEvent, t) : "",
+    // TODO: Only the original attendee can make changes to the event
+    // Guests cannot
+    calEvent.seatsPerTimeSlot ? "" : getManageLink(calEvent, t),
+    calEvent.paymentInfo ? `${t("pay_now")}:\n${calEvent.paymentInfo.link}` : "",
+  ]
```
Comment (TusharBhatt1) [inline packages/lib/CalEventParser.ts:334]: same

**Comment by retrogtx** [comment]
if teamMembers.length is 0, using && would actually insert "0" into the string instead of an empty string, which is probably not what we want

That space should be empty as it is because it might be optional

adding && will return the value itself if it's false etc

**Review by TusharBhatt1 — APPROVED** [review]
