### PR TITLE
feat: skip onboarding and fix UI for redirect apps

### LINKED ISSUE #16707: [CAL-4364] for redirect apps, rename "Install App" to "Visit" and skip "App Onboarding"
for these apps:

CleanShot 2024-09-18 at 19 28 07@2x

lets change the "Install" button to an external link

we should **not** go through the app onboarding flow

<sub>[CAL-4364](https://linear.app/calcom/issue/CAL-4364/for-redirect-apps-rename-install-app-to-visit-and-skip-app-onboarding)</sub>

### PR DESCRIPTION
**Pull request by keerthikumanduri**
## What does this PR do?

- Fixes #16707 
- Fixes CAL-4364

Before: 
This PR changes the Install Button in the app store page to Visit for redirect apps, and skips onboarding.
Screenshot 2025-08-14 at 7 18 02 PM

After:
https://www.loom.com/share/1c6aa8e7279b4e3faf62dd47f3811159?sid=3bdcdc93-7e69-4a2a-8181-37871a073847

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't checked if my changes generate no new warnings

### CODE REVIEW

File: apps/web/components/apps/AppPage.tsx [hunk 1]
```diff
@@ -112,7 +113,12 @@ export const AppPage = ({
   });
 
   const handleAppInstall = () => {
-    setIsLoading(true);
+    if (isRedirectApp(slug)) {
```
Comment (keerthikumanduri) [inline apps/web/components/apps/AppPage.tsx:116]: Added the rediret logic here, we skip the onboarding flow and let backend handle the redirect.

File: apps/web/components/apps/AppPage.tsx [hunk 2]
```diff
@@ -185,6 +191,19 @@ export const AppPage = ({
...
+          onClick={() => handleAppInstall()}
+          className="mt-2"
+          StartIcon="external-link"
+          loading={isLoading}
+          disabled={isLoading}>
+          {t("APPSTORE_VISIT")}
+        </Button>
+      );
+    }
+
```
Comment (keerthikumanduri) [inline apps/web/components/apps/AppPage.tsx:206]: early return for redirect apps that shows "Visit" , since the redirect apps dont need to follow same installation flow as regular apps.

File: packages/features/apps/components/AppCard.tsx [hunk 3]
```diff
@@ -148,7 +153,9 @@ export function AppCard({ app, credentials, searchText, userAdminTeams }: AppCar
                       loading: mutation.isPending,
                     };
                   }
-                  return <InstallAppButtonChild paid={app.paid} {...props} />;
+                  return (
+                    <InstallAppButtonChild paid={app.paid} isRedirect={isRedirectApp(app.slug)} {...props} />
+                  );
```
Comment (keerthikumanduri) [inline packages/features/apps/components/AppCard.tsx:158]: the isRedirect prop is necessary since all apps go through the same component.

**Review by anikdhabal — APPROVED** [review]
Looks good
