### PR TITLE
Fix/office365 api call

### LINKED ISSUE #3310: BUG Availability and Prefetch not working on M365
### Issue Summary

Microsoft prefetch and calendar checkup does not work. 

image

I am not available at 10. I checked it with 2 different cal.com accounts. With gsuite it works. With MS it does not. 

### Steps to Reproduce

Availability prefetch and check does not work on MS.

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

Properly handle all Microsoft api graph statuses.

- Status 429 retry-after header.
- A case where an html was returned in response body.
- Status 200 with odata.nextLink with next page data url.

Fixes #3310 

**Environment**: Staging(main branch) / Production

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Test A: You need to create several busy events on your office calendar so it can handle multiple result pages, each page its 10 items size.
- [ ] Test B: Create a duplicate selected calendar which ID doesn't exist on your calendar. Now it should handle an error while getting a 404 calendar.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/app-store/office365calendar/lib/CalendarService.ts [hunk 1]
```diff
@@ -21,11 +21,33 @@ import { O365AuthCredentials } from "../types/Office365Calendar";
...
+    "Retry-After": string;
+    "Content-Type": string;
+  };
+  body: Record<string, any>;
+}
+
+interface IBatchResponse {
+  responses: ISettledResponse[];
+}
+
```
Comment (alannnc) [inline packages/app-store/office365calendar/lib/CalendarService.ts:43]: New interfaces for any object used on office calendar service.

File: packages/app-store/office365calendar/lib/CalendarService.ts [hunk 2]
```diff
@@ -21,11 +21,33 @@ import { O365AuthCredentials } from "../types/Office365Calendar";
...
 export default class Office365CalendarService implements Calendar {
   private url = "";
   private integrationName = "";
   private log: typeof logger;
+  private accessToken: string | null = null;
```
Comment (alannnc) [inline packages/app-store/office365calendar/lib/CalendarService.ts:48]: Made this a private value so it can be access while using any private function without passing it as parameter.

File: packages/app-store/office365calendar/lib/CalendarService.ts [hunk 3]
```diff
@@ -130,31 +153,28 @@ export default class Office365CalendarService implements Calendar {
...
           url: `/me/calendars/${calendarId}/calendarView${filter}`,
         }));
-        const response = await fetch("https://graph.microsoft.com/v1.0/$batch", {
-          method: "POST",
-          headers: {
-            Authorization: "Bearer " + accessToken,
-            "Content-Type": "application/json",
-          },
-          body: JSON.stringify({ requests }),
-        });
```
Comment (alannnc) [inline packages/app-store/office365calendar/lib/CalendarService.ts:140]: Nos this await its a reusable function.

File: packages/app-store/office365calendar/lib/CalendarService.ts [hunk 4]
```diff
@@ -257,4 +277,154 @@ export default class Office365CalendarService implements Calendar {
       location: event.location ? { displayName: getLocation(event) } : undefined,
     };
   };
+
+  private fetchResponseNextLink = async (
+    settledResponses: ISettledResponse[]
+  ): Promise<ISettledResponse[]> => {
+    const alreadySuccess = [] as ISettledResponse[];
+    const newLinkRequest = [] as IRequest[];
+    settledResponses?.forEach((response) => {
```
Comment (alannnc) [inline packages/app-store/office365calendar/lib/CalendarService.ts:286]: Separate already responses with new requests to be called later.

File: packages/lib/errors.ts [hunk 5]
```diff
@@ -11,13 +11,17 @@ export function getErrorFromUnknown(cause: unknown): Error & { statusCode?: numb
 }
 
 export function handleErrorsJson(response: Response) {
+  if (response.headers.get("content-encoding") === "gzip") {
+    return response.text();
+  }
```
Comment (alannnc) [inline packages/lib/errors.ts:16]: When microsoft api graph request it's to large it gets here as gzip compressed. We should then use response.text(). It shouldn't affect other services.

File: packages/app-store/office365calendar/lib/CalendarService.ts [hunk 6]
```diff
@@ -130,31 +153,28 @@ export default class Office365CalendarService implements Calendar {
...
+
+        if (retryAfter && responseBatchApi.responses) {
+          responseBatchApi = await this.fetchRequestWithRetryAfter(requests, responseBatchApi.responses, 2);
+        }
+
+        // Recursively fetch nextLink responses
+        alreadySuccessResponse = await this.fetchResponsesWithNextLink(responseBatchApi.responses);
+
+        const result = alreadySuccessResponse ? this.processBusyTimes(alreadySuccessResponse) : [];
+        return result;
```
Comment (alannnc) [inline packages/app-store/office365calendar/lib/CalendarService.ts:177]: @TODO: avoid const and return directly

**Review by zomars — APPROVED** [review]

File: packages/app-store/office365calendar/lib/CalendarService.ts [hunk 7]
```diff
@@ -257,4 +276,153 @@ export default class Office365CalendarService implements Calendar {
...
+    const newResponse = await this.apiGraphBatchCall(newLinkRequest);
+    let newResponseBody = await handleErrorsJson(newResponse);
+
+    if (typeof newResponseBody === "string") {
+      newResponseBody = this.handleTextJsonResponseWithHtmlInBody(newResponseBody);
+    }
+
+    // Going recursive to fetch next link
+    const newSettledResponses = await this.fetchResponsesWithNextLink(newResponseBody.responses);
+    return [...alreadySuccess, ...newSettledResponses];
```
Comment (joeauyeung) [inline packages/app-store/office365calendar/lib/CalendarService.ts:319]: This is so cool!

**Review by joeauyeung — APPROVED** [review]
This is such an awesome PR, great job @alannnc! 

Context for anyone else reviewing. Here are the request limits for Outlook
image

**Comment by alannnc** [comment]
@joeauyeung 
> Context for anyone else reviewing. Here are the request limits for Outlook 
I think we should be using Microsoft API Graph limits and also batching has its own throttling.
image

**Review by zomars — CHANGES_REQUESTED** [review]
Made some legibility fixes. Code looking good, other than that. Since we're changing `handleJsonError` build is breaking on other VideoApiAdapters. Let's fix those before merging.

**Comment by zomars** [comment]
image

**Review by zomars — APPROVED** [review]
