### PR TITLE
fix: sucess page time

### LINKED ISSUE #10735: [CAL-2342] Wrong Time on Success Screen
### Issue Summary
After the organizer successfully reschedules a booking, they see the time info of the booker instead their own. Other places show the correct timezone info.

### Steps to Reproduce

1. Book a meeting with a user.
2. Reschedule the meeting as an Organizer.

### Evidence
[Video link](https://youtu.be/F5TRd7GfEHM)

<sub>[CAL-2342](https://linear.app/calcom/issue/CAL-2342/wrong-time-on-success-screen)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/10735

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: apps/web/pages/booking/[uid].tsx [hunk 1]
```diff
@@ -113,7 +113,8 @@ export default function Success(props: SuccessProps) {
   const attendeeTimeZone = props?.bookingInfo?.attendees.find(
     (attendee) => attendee.email === email
   )?.timeZone;
-  const tz = isSuccessBookingPage && attendeeTimeZone ? attendeeTimeZone : props.tz ? props.tz : timeZone();
+
+  const tz = props.tz ? props.tz : isSuccessBookingPage && attendeeTimeZone ? attendeeTimeZone : timeZone();
```
Comment (Udit-takkar) [inline apps/web/pages/booking/[uid].tsx:117]: props.tz is the timezone obtained from user session

**Review by shivamklr — COMMENTED** [review]
Tested, lgtm.

**Review by hariombalhara — APPROVED** [review]
