### PR TITLE
fix: remove event type URL for managed event types

### LINKED ISSUE #23355: Remove event type url for managed event types
The correct booking links for managed event types are `/username/eventTypeSlug`. `/teamSlug/eventTypeSlug` should not load and return 404 instead. Also, we need to make sure to not sure this link anywhere in the app

### PR DESCRIPTION
**Pull request by sahitya-chandra**
## What does this PR do?

- Fixes #23355 
- Fixes CAL-6321 (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Visual Demo (For contributors especially)

[Screencast from 2025-08-26 17-16-59.webm](https://github.com/user-attachments/assets/9d4a99d2-004d-4105-9c0d-7e842a45ac45)

[Screencast from 2025-08-26 18-48-53.webm](https://github.com/user-attachments/assets/3b2533f3-8430-4c47-88fb-080aece84981)

A visual demonstration is strongly recommended, for both the original and new change **(video / image - any one)**.

#### Video Demo (if applicable):

- Show screen recordings of the issue or feature.
- Demonstrate how to reproduce the issue, the behavior before and after the change.

#### Image Demo (if applicable):

- Add side-by-side screenshots of the original and updated change.
- Highlight any significant change(s).

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

### CODE REVIEW

File: apps/web/modules/event-types/views/event-types-listing-view.tsx [hunk 1]
```diff
@@ -176,13 +177,11 @@ const Item = ({
         data-testid={`event-type-title-${type.id}`}>
         {type.title}
       </span>
-      {group.profile.slug ? (
+      {group.profile.slug && type.schedulingType !== SchedulingType.MANAGED ? (
```
Comment (anikdhabal) [inline apps/web/modules/event-types/views/event-types-listing-view.tsx:180]: But doesn’t it also remove it from the child user event?

Comment (kart1ka) [reply apps/web/modules/event-types/views/event-types-listing-view.tsx:180]: I think child user events do not have SchedulingType.MANAGED only parent managed event does. Verified in the ui as well.

**Review by kart1ka — DISMISSED** [review]
LGTM

File: apps/web/modules/event-types/views/event-types-listing-view.tsx (hunk 1 above)
Comment (sahitya-chandra) [reply apps/web/modules/event-types/views/event-types-listing-view.tsx:180]: One more thing, should we completly hide url in teams tab for managed events or 

this type of url is ok

Screenshot from 2025-08-26 22-50-13

Comment (sahitya-chandra) [reply apps/web/modules/event-types/views/event-types-listing-view.tsx:180]: @anikdhabal sir, currently the url is completly removed from the managed event type in team tab

managed event in user tab(url shown)

Screenshot from 2025-08-26 22-43-53

managed event in teams tab (url removed)

Screenshot from 2025-08-26 22-44-41

Comment (kart1ka) [reply apps/web/modules/event-types/views/event-types-listing-view.tsx:180]: I think as per the issue description we should not show the managed url in the teams tab. We are good.

File: apps/web/lib/team/[slug]/[type]/getServerSideProps.tsx [hunk 2]
```diff
@@ -12,7 +12,7 @@ import { shouldHideBrandingForTeamEvent } from "@calcom/lib/hideBranding";
 import slugify from "@calcom/lib/slugify";
 import prisma from "@calcom/prisma";
```
Comment (volnei) [inline apps/web/lib/team/[slug]/[type]/getServerSideProps.tsx:13]: nit: let's start to use non default exports 
``` import { prisma } from "@calcom/prisma"; ```

**Review by volnei — DISMISSED** [review]

File: apps/web/lib/team/[slug]/[type]/getServerSideProps.tsx [hunk 3]
```diff
@@ -54,6 +54,11 @@ export const getServerSideProps = async (context: GetServerSidePropsContext) =>
 
   const eventData = team.eventTypes[0];
 
+  // Check for managed event type and return 404
```
Comment (keithwillcode) [inline apps/web/lib/team/[slug]/[type]/getServerSideProps.tsx]: Nit: This comment is not useful because the code says exactly this

Comment (sahitya-chandra) [reply apps/web/lib/team/[slug]/[type]/getServerSideProps.tsx]: done @keithwillcode sir, comment removed

**Review by volnei — APPROVED** [review]

**Comment by sahitya-chandra** [comment]
@anikdhabal sir can you have a look at this also
