### PR TITLE
fix: use useTeamsPlan hook

### LINKED ISSUE #8675: [CAL-1618] Show Upgrade button instead of download button when user has not subscribed to teams plan
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Downloading recordings is a teams plan user and if a user is not part of an active team we show upgrade button instead of download button. for some reason download button is displayed to users who are not part of an active team

Reported here https://calendso.slack.com/archives/C01NXDSRY9W/p1683141049329079

### Steps to Reproduce

1. Go to past bookings 
2 open any booking which has recording

<sub>[CAL-1618](https://linear.app/calcom/issue/CAL-1618/show-upgrade-button-instead-of-download-button-when-user-has-not)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/8675

**Environment**: Staging(main branch) / Production

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/features/ee/video/ViewRecordingsDialog.tsx [hunk 1]
```diff
@@ -157,7 +157,7 @@ export const ViewRecordingsDialog = (props: IViewRecordingsDialog) => {
   const { t, i18n } = useLocale();
   const { isOpenDialog, setIsOpenDialog, booking, timeFormat } = props;
 
-  const { hasPaidPlan, isLoading: isTeamPlanStatusLoading } = useHasPaidPlan();
+  const { hasTeamPlan, isLoading: isTeamPlanStatusLoading } = useHasTeamPlan();
```
Comment (Udit-takkar) [inline packages/features/ee/video/ViewRecordingsDialog.tsx:160]: useHasPaidPlan hook checks for premium username or active team member but we only want to check if user is part of an active team

File: packages/ui/components/tooltip/Tooltip.tsx [hunk 2]
```diff
@@ -33,7 +33,7 @@ export function Tooltip({
           className={classNames(
             side === "top" && "-mt-7",
             side === "right" && "ml-2",
-            "bg-inverted text-inverted relative relative z-20 rounded-md px-2 py-1 text-xs font-semibold shadow-lg"
+            "bg-inverted text-inverted relative relative z-50 rounded-md px-2 py-1 text-xs font-semibold shadow-lg"
```
Comment (Udit-takkar) [inline packages/ui/components/tooltip/Tooltip.tsx:36]: tooltip was not visible on DialogContent

**Review by CarinaWolli — APPROVED** [review]
LGTM!
