### PR TITLE
fix: meeting link fails when host requests to reschedule

### LINKED ISSUE #20746: [CAL-5522] Zoom link fails to update when host requests reschedule
@milospuac said:

> @anik Problem with rescheduling zoom link - When host sends "request reschedule" to attende zoom link fails, isn't added. They need to update the location again in the upcoming bookings to zoom. This is an edge case ony with "Request reschedule" as normal rescheduling from the attendee and host works fine. I was able to reproduce this. [https://app.plain.com/workspace/w_01JEVB6H9RQ02E46X9Q4XKP7R5/thread/th_01JPNHDPAQH6HMKF9DP4JPXCMM/](https://app.plain.com/workspace/w_01JEVB6H9RQ02E46X9Q4XKP7R5/thread/th_01JPNHDPAQH6HMKF9DP4JPXCMM/)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-5522](https://linear.app/calcom/issue/CAL-5522/zoom-link-fails-to-update-when-host-requests-reschedule)</sub>

### PR DESCRIPTION
**Pull request by anikdhabal**
Fixes CAL-5522
Fixes https://github.com/calcom/cal.com/issues/20746
## Summary by mrge
Fixed an issue where meeting links failed when a host requested to reschedule, ensuring meetings are updated or deleted correctly during rescheduling.

### CODE REVIEW

File: packages/lib/EventManager.ts [hunk 1]
```diff
@@ -516,7 +520,7 @@ export default class EventManager {
         updatedBookingReferences.push(...createdEvent.referencesToCreate);
       } else {
         // If the reschedule doesn't require confirmation, we can "update" the events and meetings to new time.
-        if (isLocationChanged) {
+        if (isLocationChanged || isBookingRequestedReschedule) {
```
Comment (anikdhabal) [inline packages/lib/EventManager.ts:523]: Updating the location with the new context, as the previous one is deleted

**Review by Udit-takkar — COMMENTED** [review]
I am not sure if this should create new duplicate references

Screenshot 2025-04-28 at 1 34 10 PM

**Comment by anikdhabal** [comment]
> I am not sure if this should create new duplicate references
> 
> Screenshot 2025-04-28 at 1 34 10 PM

Oh i've missed it. Updated it
image

File: packages/trpc/server/routers/viewer/bookings/requestReschedule.handler.ts [hunk 2]
```diff
@@ -251,7 +251,7 @@ export const requestRescheduleHandler = async ({ ctx, input }: RequestReschedule
           })
         );
         return calendar?.deleteEvent(bookingRef.uid, builder.calendarEvent, bookingRef.externalCalendarId);
-      } else if (bookingRef.type.endsWith("_video") && bookingRef.type !== "daily_video") {
```
Comment (anikdhabal) [inline packages/trpc/server/routers/viewer/bookings/requestReschedule.handler.ts:254]: This was a workaround

**Review by zomars — APPROVED** [review]
