### PR TITLE
fix: make actions column sticky in members list

### LINKED ISSUE #17553: [CAL-4677] [member list] make actions column sticky
[CleanShot 2024-11-04 at 15.16.24.mp4](https://uploads.linear.app/e86bf957-d82f-465e-b205-135559f4b623/a903d4e1-95ba-422c-84af-1ee940ad214b/8a0d9e64-63d9-4973-84fc-6c2d23db303a)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4677](https://linear.app/calcom/issue/CAL-4677/make-actions-column-sticky)</sub>

### PR DESCRIPTION
**Pull request by eunjae-lee**
## What does this PR do?

- Fixes #17553 (GitHub issue number)
- Fixes CAL-4677 (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

The right-most column for the action buttons is now sticky to the right in Organization Members list.

https://github.com/user-attachments/assets/067b4eac-e867-4e1b-8591-3b355d798eb6

### CODE REVIEW

File: packages/types/tanstack-table.d.ts [hunk 1]
```diff
@@ -2,6 +2,9 @@ import "@tanstack/react-table";
 
 declare module "@tanstack/table-core" {
   interface ColumnMeta<TData extends RowData, TValue> {
-    hasPermissions?: (data?: TData) => boolean; // We can conditionally render a column based on this callback -> User doesnt have admin for example.
```
Comment (eunjae-lee) [inline packages/types/tanstack-table.d.ts:5]: `hasPermissions` seems to be un-used in the repo

**Review by keithwillcode — APPROVED** [review]
