### PR TITLE
fix: seated event type public id cancels/reschedule entire booking without auth

### LINKED ISSUE #11660: [CAL-2567] Booking with seats can be fully cancelled without user permission
Found a bug? Please fill out the sections below. 👍

### Issue Summary

All of [cal.com](http://cal.com) bookings can be cancelled using their public booking.uid. This shouldn't be the case for seated events as we send "/booking/\[uid\]?=seatReferenceUId", there may be some browser plugins that remove all data after ?= thus meaning an attendee can cancel the booking for everyone else.

### Steps to Reproduce

1. Create booking with seats.
2. Add 2 or more attendees to any given time.
3. From the success page or email from those attendees, you can remove the ?=seatReferenceUId query param and using a browser in a incognito mode or without a user logged in and entirely cancel the booking for everyone there.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

* Booking gets entirely cancelled

### Expected Results

* Cancel button shouldn't be displayed when going to "booking/\[uid\]" on a seated event and no user logged in data found.
* Also api/cancel should validate that user cancelling it's host in that eventType that uses seats but now receiving seatsReferenceUid parameter.

### Evidence

* This was reported on out support channels, since replication was easy and it makes sense on our public/privacy settings config for all bookings.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2567](https://linear.app/calcom/issue/CAL-2567/booking-with-seats-can-be-fully-cancelled-without-user-permission)</sub>

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

- Requires for session when cancelling booking with seats event type, this is due to the nature of cal.com that only requires uid to cancel bookings. In this case only the owner or host will be able to cancel entire booking.
- Requires for session too when rescheduling with seats event type as an owner.

Fixes #11660 

https://www.loom.com/share/af68791121af4be0b83541c6e6ad6d15
*~~missing some fixes on the video~~ _Already fixed_ (description wasn't showing at the end and we should show host data when he is rescheduling)

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: apps/web/pages/[user]/[type].tsx [hunk 1]
```diff
@@ -43,6 +44,7 @@ export default function Type({
         hideBranding={isBrandingHidden}
         isSEOIndexable={isSEOIndexable ?? true}
         entity={entity}
+        bookingData={booking}
```
Comment (alannnc) [inline apps/web/pages/[user]/[type].tsx:47]: Here bookingData was required since we were displaying in page title "Reschedule" with just rescheduleUid param

File: apps/web/pages/[user]/[type].tsx [hunk 2]
```diff
@@ -96,7 +99,7 @@ async function getDynamicGroupPageProps(context: GetServerSidePropsContext) {
 
   let booking: GetBookingType | null = null;
   if (rescheduleUid) {
-    booking = await getBookingForReschedule(`${rescheduleUid}`);
+    booking = await getBookingForReschedule(`${rescheduleUid}`, session?.user?.id);
```
Comment (alannnc) [inline apps/web/pages/[user]/[type].tsx:102]: Now we need session here to know if user rescheduling is kind of an owner.

File: apps/web/pages/[user]/[type].tsx [hunk 3]
```diff
@@ -168,7 +172,7 @@ async function getUserPageProps(context: GetServerSidePropsContext) {
...
```
Comment (alannnc) [inline apps/web/pages/[user]/[type].tsx:175]: same as above

File: apps/web/pages/booking/[uid].tsx [hunk 4]
```diff
@@ -146,7 +146,7 @@ export default function Success(props: SuccessProps) {
   const shouldAlignCentrallyInEmbed = useEmbedNonStylesConfig("align") !== "left";
   const shouldAlignCentrally = !isEmbed || shouldAlignCentrallyInEmbed;
   const [calculatedDuration, setCalculatedDuration] = useState<number | undefined>(undefined);
-
+  const { requiresLoginToUpdate } = props;
```
Comment (alannnc) [inline apps/web/pages/booking/[uid].tsx:149]: Created this new flag to know if login is required to cancel/reschedule booking. This will only happen if booking is seated event.

File: apps/web/pages/booking/[uid].tsx [hunk 5]
```diff
@@ -532,36 +532,59 @@ export default function Success(props: SuccessProps) {
...
+                {requiresLoginToUpdate && (
+                  <>
+                    <hr className="border-subtle mb-8" />
+                    <div className="text-center">
+                      <span className="text-emphasis ltr:mr-2 rtl:ml-2">{t("need_to_make_a_change")}</span>
+                      {/* Login button but redirect to here */}
+                      <span className="text-default inline">
+                        <span className="underline" data-testid="reschedule-link">
+                          <Link
+                            href={`/auth/login?callbackUrl=${encodeURIComponent(
```
Comment (alannnc) [inline apps/web/pages/booking/[uid].tsx:544]: New link to login for getting the cancel/reschedule buttons

File: apps/web/pages/booking/[uid].tsx [hunk 6]
```diff
@@ -1009,7 +1032,7 @@ export async function getServerSideProps(context: GetServerSidePropsContext) {
   const session = await getServerSession(context);
   let tz: string | null = null;
   let userTimeFormat: number | null = null;
-
+  let requiresLoginToUpdate = false;
```
Comment (alannnc) [inline apps/web/pages/booking/[uid].tsx:1035]: Default to false for everything expect new scenario

File: apps/web/pages/reschedule/[uid].tsx [hunk 7]
```diff
@@ -53,14 +74,41 @@ export async function getServerSideProps(context: GetServerSidePropsContext) {
...
+    });
+
+    const userIsOwnerOfEventType = booking?.eventType.owner?.id === userId;
+
+    if (!userIsHost && !userIsOwnerOfEventType) {
+      return {
+        notFound: true,
+      } as {
+        notFound: true;
+      };
```
Comment (alannnc) [inline apps/web/pages/reschedule/[uid].tsx:108]: If everything goes bad we throw 404

File: packages/features/bookings/Booker/components/BookEventForm/BookEventForm.tsx [hunk 8]
```diff
@@ -492,12 +493,18 @@ function useInitialFormValues({
...
-          : parsedQuery["email"] || session.data?.user?.email || "",
-        name: rescheduleUid
-          ? bookingData?.attendees[0].name
-          : parsedQuery["name"] || session.data?.user?.name || "",
+        email:
+          rescheduleUid && bookingData && bookingData.attendees.length > 0
+            ? bookingData?.attendees[0].email
+            : !!parsedQuery["email"]
+            ? parsedQuery["email"]
+            : session.data?.user?.email ?? "",
```
Comment (alannnc) [inline packages/features/bookings/Booker/components/BookEventForm/BookEventForm.tsx:501]: added scenario that owner rescheduling and we displaying their email on book form.

File: packages/features/bookings/Booker/components/BookEventForm/BookEventForm.tsx [hunk 9]
```diff
@@ -521,22 +528,20 @@ function useInitialFormValues({
         setDefaultValues(defaults);
       }
 
-      if ((!rescheduleUid && !bookingData) || !bookingData?.attendees.length) {
-        return {};
-      }
-      const primaryAttendee = bookingData.attendees[0];
-      if (!primaryAttendee) {
+      if (!rescheduleUid && !bookingData) {
```
Comment (alannnc) [inline packages/features/bookings/Booker/components/BookEventForm/BookEventForm.tsx:531]: Updated this code since primaryAttendee is not always mandatory now.

File: packages/features/bookings/components/BookerSeo.tsx [hunk 10]
```diff
@@ -29,7 +41,7 @@ export const BookerSeo = (props: BookerSeoProps) => {
   const title = event?.title ?? "";
   return (
     <HeadSeo
-      title={`${rescheduleUid ? t("reschedule") : ""} ${title} | ${profileName}`}
+      title={`${rescheduleUid && !!bookingData ? t("reschedule") : ""} ${title} | ${profileName}`}
```
Comment (alannnc) [inline packages/features/bookings/components/BookerSeo.tsx:44]: rely on valid rescheduleUid that should return some bookingData to display title

File: apps/web/playwright/booking-seats.e2e.ts [hunk 11]
```diff
@@ -143,6 +144,19 @@ test.describe("Booking with Seats", () => {
...
+      await page.goto(`/booking/${booking.uid}`);
+
+      await expect(page.locator('[data-testid="cancel"]')).toHaveCount(0);
+    });
+
+    await test.step("Attendee #2 shouldn't be able to cancel booking using randomString for seatReferenceUId", async () => {
+      await page.goto(`/booking/${booking.uid}?seatReferenceUid=${randomString(10)}`);
+
+      // expect cancel button to don't be in the page
+      await expect(page.locator('[data-testid="cancel"]')).toHaveCount(0);
```
Comment (keithwillcode) [inline apps/web/playwright/booking-seats.e2e.ts:157]: This test will continue passing if someone updates the component to render a cancel button that doesn't have this exact `data-testid`. What do you think about making this selector more general? e.g. Look for any button with the text `Cancel`

Comment (alannnc) [reply apps/web/playwright/booking-seats.e2e.ts:157]: Sure!

**Review by keithwillcode — APPROVED** [review]
