### PR TITLE
Fix dropdown focus + public dark mode buttons 

### LINKED ISSUE #4303: new <Button> has no dark mode
since we use the v2 Button component on some public booking pages, that have dark mode, we need dark buttons for primary and secondary 

CleanShot 2022-09-08 at 18 23 23@2x

also, focus is broken:

image

### PR DESCRIPTION
**Pull request by sean-brydon**
Fixes issues in slack convo:

Partially Fixes: #4303 - Will go into this issue in more detail when we create full-site darkmode.

Dropdown focus now uses radix focus state (this was the only place I could find that issue was present) Everywhere else uses the default styles on our dropdown component
CleanShot 2022-09-16 at 14 53 06

Fixes dark-mode buttons on public page - note I picked the worst brand color to test this out. 

https://user-images.githubusercontent.com/55134778/190656630-fecd520a-76ef-42d4-9260-86a7798e9827.mp4

### CODE REVIEW

File: apps/web/components/booking/pages/BookingPage.tsx [hunk 1]
```diff
@@ -595,9 +595,7 @@ const BookingPage = ({
                       required
                       className={classNames(
                         inputClassName,
-                        bookingForm.formState.errors.email
-                          ? "border-red-700 focus:ring-red-700"
-                          : " border-gray-300  dark:border-gray-900"
+                        bookingForm.formState.errors.email && "!focus:ring-red-700 !border-red-700"
```
Comment (sean-brydon) [inline apps/web/components/booking/pages/BookingPage.tsx:598]: This was causing issues so just adding important if there is errors (how it should be imho)

File: packages/ui/v2/modules/event-types/CreateEventType.tsx [hunk 2]
```diff
@@ -153,7 +153,11 @@ export default function CreateEventTypeButton(props: CreateEventTypeBtnProps) {
       ) : (
         <Dropdown>
           <DropdownMenuTrigger asChild>
-            <Button EndIcon={Icon.FiChevronDown}>{t("new")}</Button>
+            <Button
+              EndIcon={Icon.FiChevronDown}
+              className="radix-state-open:bg-brand-500 radix-state-open:ring-2 radix-state-open:ring-brand-500 ring-offset-2">
```
Comment (sean-brydon) [inline packages/ui/v2/modules/event-types/CreateEventType.tsx:158]: Use radix-tailwind to get styles

**Review by PeerRich — APPROVED** [review]
great job

**Review by pumfleet — APPROVED** [review]
