### PR TITLE
fix: use outline none

### LINKED ISSUE #5481: [PRO-28] Sidebar profile dropdown - Weird hover states
Weird (blue outline?) hover states on the items in the sidebar profile dropdown. And it's also being chopped off oddly on the top & bottom border radius

**Currently**

Should be

There's also an issue with the trigger

* no border radius
* wrong background colour on hover 
* public link looks like it's the wrong gray
* profile image should be 32px not 36px

> From [SyncLinear.com](https://synclinear.com) | [PRO-28](https://linear.app/calcom/issue/PRO-28/sidebar-profile-dropdown-weird-hover-states)

### PR DESCRIPTION
**Pull request by Udit-takkar**
Fixes: #5481 , #5484 

https://user-images.githubusercontent.com/53316345/201367756-788f121a-5087-418a-a680-e4417ef3e841.mov

### CODE REVIEW

File: packages/ui/Dropdown.tsx [hunk 1]
```diff
@@ -53,7 +53,7 @@ type DropdownMenuItemProps = ComponentProps<typeof DropdownMenuPrimitive["Checkb
 export const DropdownMenuItem = forwardRef<HTMLDivElement, DropdownMenuItemProps>(
   ({ className = "", ...props }, forwardedRef) => (
     <DropdownMenuPrimitive.Item
-      className={`text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900 ${className}`}
+      className={`text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900 focus:outline-none	 ${className}`}
```
Comment (Udit-takkar) [inline packages/ui/Dropdown.tsx:56]: idk very weird behaviour focus:outline-none fixes this somehow.

Comment (zomars) [inline packages/ui/Dropdown.tsx:56]:
```suggestion
      className={`text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900 focus:outline-none ${className}`}
```

**Review by zomars — APPROVED** [review]
LGTM
