### PR TITLE
feat: Column View Available Slots Fix

### LINKED ISSUE #9593: [CAL-1979] column view: only show available times
for example: I have a weekly recurring office hours: [https://cal.com/peer/office-hours?date=2023-06-22](https://cal.com/peer/office-hours?date=2023-06-22) and I wanna show all fridays (its only on fridays)

right now in column view we show unavailable days:

[https://github.com/calcom/cal.com/assets/8019099/20fab7d3-8fe9-4775-80f8-cf43dba56d0b](https://github.com/calcom/cal.com/assets/8019099/20fab7d3-8fe9-4775-80f8-cf43dba56d0b)

instead, we should show only days with availability:

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1979](https://linear.app/calcom/issue/CAL-1979/column-view-only-show-available-times)</sub>

### PR DESCRIPTION
**Pull request by VinoV1999**
## What does this PR do?

Shows only available slots in a column view. Jumps forward and back to the next available 6 slots, on click of left and right arrow respectively.

Fixes #9593
/claim #9593

https://github.com/calcom/cal.com/assets/123581387/cc3c6306-5b62-4247-ad35-6322953702a9

## Type of change

- Increased the extraDaysConfig of column view from 4 to 6.
- Implemented the logic to calculate the no of days in between continuous slots. And passed the required arguments to child pages.
- Modified the format of header.
- Assorted the available slots.
- Added useSlotsForAvailableDates function to filter out the required data.

### CODE REVIEW

**Comment by PeerRich** [comment]
wow this is really cool!

File: packages/features/bookings/Booker/components/AvailableTimeSlots.tsx [hunk 1]
```diff
@@ -21,11 +25,14 @@ type AvailableTimeSlotsProps = {
  * will also fetch the next `extraDays` days and show multiple days
  * in columns next to each other.
  */
-export const AvailableTimeSlots = ({ extraDays, limitHeight, seatsPerTimeslot }: AvailableTimeSlotsProps) => {
+export const AvailableTimeSlots = ({ extraDays, limitHeight, seatsPerTimeslot, sliceFrom, sliceTo}: AvailableTimeSlotsProps) => {
+  const reserveSlotMutation = trpc.viewer.public.slots.reserveSlot.useMutation();
```
Comment (PeerRich) [inline packages/features/bookings/Booker/components/AvailableTimeSlots.tsx:29]: missing trpc import here @sean-brydon

Comment (PeerRich) [reply packages/features/bookings/Booker/components/AvailableTimeSlots.tsx:29]: or maybe @emrysal ?

File: packages/features/schedules/lib/use-schedule/useSchedule.ts [hunk 2]
```diff
@@ -20,9 +21,11 @@ export const useSchedule = ({
   eventId,
   prefetchNextMonth,
   duration,
+  monthCount
 }: UseScheduleWithCacheArgs) => {
+  console.log(monthCount);
```
Comment (Udit-takkar) [inline packages/features/schedules/lib/use-schedule/useSchedule.ts:26]:
```suggestion
```

File: packages/features/schedules/lib/use-schedule/useSlotsForDate.ts [hunk 3]
```diff
@@ -29,3 +33,15 @@ export const useSlotsForMultipleDates = (dates: (string | null)[], slots?: Slots
...
 };
+
+export const useSlotsForAvailableDates = (slots: slot[]) => {
+  const slotsForDates = useMemo(() => {
+    if (typeof slots === "undefined") return [];
+    return slots.map((slot) => ({
+      date: dayjs(slot[0].time).format("YYYY-MM-DD"),
+      slots: slot
+    }));
+  }, [slots]);
```
Comment (Udit-takkar) [inline packages/features/schedules/lib/use-schedule/useSlotsForDate.ts:44]: getting this warning 
Screenshot 2023-06-29 at 12 39 23 AM

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
responsive bugs

Screenshot 2023-06-29 at 12 40 36 AM

File: packages/features/bookings/Booker/Booker.tsx [hunk 4]
```diff
@@ -64,7 +66,17 @@ const BookerComponent = ({
     shallow
   );
 
-  const extraDays = isTablet ? extraDaysConfig[layout].tablet : extraDaysConfig[layout].desktop;
+  const date = dayjs(selectedDate).format("YYYY-MM-DD");
+  const schedule = useScheduleForEvent({prefetchNextMonth: true});
+  const nonEmptyScheduleDays = useNonEmptyScheduleDays(schedule?.data?.slots);
+  const sliceFrom =  nonEmptyScheduleDays.indexOf(date)!= -1? nonEmptyScheduleDays.indexOf(date): 0;
```
Comment (Udit-takkar) [inline packages/features/bookings/Booker/Booker.tsx:72]: Always prefer this

```suggestion
  const sliceFrom =  nonEmptyScheduleDays.indexOf(date)!== -1? nonEmptyScheduleDays.indexOf(date): 0;
```

**Comment by Jaibles** [comment]
Nice work!!

I just have one request. Can we change the date format in the top left. The way it is now it we have `Month Day` - `Day Month` and it kinda looks like it's the date of the same month.

CleanShot 2023-06-28 at 20 42 50@2x

Can we change it to `Month Day` - `Month Day`?
CleanShot 2023-06-28 at 20 47 38@2x

File: packages/features/bookings/Booker/Booker.tsx (hunk 4 above)
Comment (VinoV1999) [reply packages/features/bookings/Booker/Booker.tsx:72]: got it

File: packages/features/schedules/lib/use-schedule/useSlotsForDate.ts (hunk 3 above)
Comment (VinoV1999) [reply packages/features/schedules/lib/use-schedule/useSlotsForDate.ts:44]: it's bcz of frequent change in extraDays, it seems.

**Comment by VinoV1999** [comment]
Screenshot 2023-06-29 at 11 39 33 PM

@Jaibles  FYI

**Comment by Jaibles** [comment]
> Screenshot 2023-06-29 at 11 39 33 PM
> 
> 
> 
> @Jaibles  FYI

@VinoV1999 Thank you 🙏 great work

File: packages/features/bookings/Booker/Booker.tsx (hunk 4 above)
Comment (VinoV1999) [reply packages/features/bookings/Booker/Booker.tsx]: @Udit-takkar upated..

File: packages/features/schedules/lib/use-schedule/useSchedule.ts (hunk 2 above)
Comment (VinoV1999) [reply packages/features/schedules/lib/use-schedule/useSchedule.ts]: Removed

File: packages/features/schedules/lib/use-schedule/useSlotsForDate.ts (hunk 3 above)
Comment (VinoV1999) [reply packages/features/schedules/lib/use-schedule/useSlotsForDate.ts:52]: https://github.com/calcom/cal.com/assets/123581387/0469c292-0146-40cd-9742-bd6c49d11ea6

@Udit-takkar FYI, Analysed and fixed that issue

**Comment by VinoV1999** [comment]
Dear @Udit-takkar / @Jaibles, All the issues reported were cleared. Kindly review it and let me know any further changes required. Thank u 🙏

**Review by Udit-takkar — DISMISSED** [review]
https://github.com/calcom/cal.com/assets/53316345/cbb2bd06-8ffc-41d3-a180-a12dbc38a764

Why am i getting slots for other days when i click on a specific date in monthly view

File: packages/features/bookings/Booker/components/AvailableTimeSlots.tsx [hunk 5]
```diff
@@ -34,30 +44,31 @@ export const AvailableTimeSlots = ({ extraDays, limitHeight, seatsPerTimeslot }:
...
-
+  
+  const slotsPerDay = schedule?.data?.slots 
+    ? useSlotsForAvailableDates(dates, isColumnView 
+      ? Object.values(schedule.data.slots).slice(sliceFrom, sliceTo) 
+      : nonEmptyScheduleDays.includes(date) 
+        ? Object.values(schedule.data.slots).slice(nonEmptyScheduleDays.indexOf(date)) 
+        : [] ) 
+    : useSlotsForAvailableDates(dates, []);
+
```
Comment (Udit-takkar) [inline packages/features/bookings/Booker/components/AvailableTimeSlots.tsx:71]: can you simplify this code? This uses a lot of ternary operators

Comment (VinoV1999) [reply packages/features/bookings/Booker/components/AvailableTimeSlots.tsx:71]: since month view and column view uses same function. And we need to differentiate those. so these much is required..

**Comment by VinoV1999** [comment]
https://github.com/calcom/cal.com/assets/123581387/1c4debbc-f6a1-43c9-9ed2-081cb556d28a

@Udit-takkar FYI

File: packages/features/bookings/Booker/components/AvailableTimeSlots.tsx (hunk 5 above)
Comment (VinoV1999) [reply packages/features/bookings/Booker/components/AvailableTimeSlots.tsx]: Hope the update make sense.

File: packages/features/bookings/Booker/components/AvailableTimeSlots.tsx [hunk 6]
```diff
@@ -34,30 +44,30 @@ export const AvailableTimeSlots = ({ extraDays, limitHeight, seatsPerTimeslot }:
...
-  const slotsPerDay = useSlotsForMultipleDates(dates, schedule?.data?.slots);
-
+  
+  const monthViewSlots = schedule?.data?.slots  && nonEmptyScheduleDays.includes(date) ? Object.values(schedule.data.slots).slice(nonEmptyScheduleDays.indexOf(date), nonEmptyScheduleDays.indexOf(date) + 1) : [];
+  const slotsPerDay = schedule?.data?.slots 
+    ? useSlotsForAvailableDates(dates, isColumnView 
+      ? Object.values(schedule.data.slots).slice(sliceFrom, sliceTo) 
+      : monthViewSlots ) 
+    : useSlotsForAvailableDates(dates, []);
+
```
Comment (Udit-takkar) [inline packages/features/bookings/Booker/components/AvailableTimeSlots.tsx:70]: you can't use useSlotsForAvailableDates hook conditonally
Screenshot 2023-07-03 at 3 28 29 PM

Comment (VinoV1999) [reply packages/features/bookings/Booker/components/AvailableTimeSlots.tsx:70]: Ok let me add all the conditions in hook itself.

Comment (VinoV1999) [reply packages/features/bookings/Booker/components/AvailableTimeSlots.tsx]: Updated dude

File: packages/features/bookings/Booker/components/AvailableTimeSlots.tsx [hunk 7]
```diff
@@ -34,30 +44,20 @@ export const AvailableTimeSlots = ({ extraDays, limitHeight, seatsPerTimeslot }:
...
+    monthCount,
   });
+  const nonEmptyScheduleDays = useNonEmptyScheduleDays(schedule?.data?.slots);
 
   // Creates an array of dates to fetch slots for.
   // If `extraDays` is passed in, we will extend the array with the next `extraDays` days.
-  const dates = useMemo(
-    () =>
-      !extraDays
+  const dates = !extraDays
```
Comment (VinoV1999) [inline packages/features/bookings/Booker/components/AvailableTimeSlots.tsx:54]: https://github.com/calcom/cal.com/assets/123581387/1f0cedbb-4b4c-4697-868c-df9008167fe4

Because of using useMemo sometimes the data isn't fetching properly. since `[date, extraDays, nonEmptyScheduleDays]` are same. After removal it's working as expected.


https://github.com/calcom/cal.com/assets/123581387/4d8b3f85-7abb-41c9-8404-9554b5ca5272

Note : make sure u have 1 slot available per week.

**Comment by VinoV1999** [comment]
@Udit-takkar  kindly review the code. And let me know if there is any changes required

**Review by shivamklr — DISMISSED** [review]
@VinoV1999 Kindly resolve the conflicts.

**Comment by VinoV1999** [comment]
Done @shivamklr

File: packages/features/bookings/Booker/Booker.tsx [hunk 8]
```diff
@@ -59,6 +61,7 @@ const BookerComponent = ({
   // In Embed we give preference to embed configuration for the layout.If that's not set, we use the App configuration for the event layout
   // But if it's mobile view, there is only one layout supported which is 'mobile'
   const layout = isEmbed ? (isMobile ? "mobile" : validateLayout(embedUiConfig.layout) || _layout) : _layout;
+  const newExtraDays = useRef<number>(isTablet ? extraDaysConfig[layout].tablet : extraDaysConfig[layout].desktop);
```
Comment (alannnc) [inline packages/features/bookings/Booker/Booker.tsx:64]: Would this constant conflict with extraDays declared later? Or is this the one we should this instead of the other one?
Can we find a better name for this? I'm not sure what it does by it's name.

File: packages/features/bookings/Booker/Booker.tsx [hunk 9]
```diff
@@ -72,9 +75,20 @@ const BookerComponent = ({
...
   const extraDays = isTablet ? extraDaysConfig[layout].tablet : extraDaysConfig[layout].desktop;
   const bookerLayouts = event.data?.profile?.bookerLayouts || defaultBookerLayoutSettings;
   const animationScope = useBookerResizeAnimation(layout, bookerState);
+  const addonDays = nonEmptyScheduleDays.length < extraDays ? (extraDays - nonEmptyScheduleDays.length + 1) * 7  : 0;
+  const availableSlots = nonEmptyScheduleDays.slice(0,  extraDays + 1);
+  if(nonEmptyScheduleDays.length !==0 )
+    newExtraDays.current =  Math.abs(dayjs(selectedDate).diff(availableSlots[availableSlots.length - 2],'day')) + addonDays;
+  const prefetchNextMonth = dayjs(date).month() !== dayjs(date).add(newExtraDays.current, "day").month();
+  const monthCount = dayjs(date).add(1,"month").month() !== dayjs(date).add(newExtraDays.current, "day").month() ? 2 : undefined
+  const nextslots = Math.abs(dayjs(selectedDate).diff(availableSlots[availableSlots.length - 1],'day')) + addonDays;
```
Comment (alannnc) [inline packages/features/bookings/Booker/Booker.tsx:91]:
```suggestion
  const nextSlots = Math.abs(dayjs(selectedDate).diff(availableSlots[availableSlots.length - 1],'day')) + addonDays;
```
Following name convention

File: packages/features/bookings/Booker/components/AvailableTimeSlots.tsx [hunk 10]
```diff
@@ -53,29 +61,18 @@ export const AvailableTimeSlots = ({ extraDays, limitHeight, seatsPerTimeSlot }:
   };
 
   const schedule = useScheduleForEvent({
-    prefetchNextMonth: !!extraDays && dayjs(date).month() !== dayjs(date).add(extraDays, "day").month(),
+    prefetchNextMonth,
+    monthCount,
   });
+  const nonEmptyScheduleDays = useNonEmptyScheduleDays(schedule?.data?.slots).filter((slot)=>dayjs(selectedDate).diff(slot,'day')<=0);
```
Comment (alannnc) [inline packages/features/bookings/Booker/components/AvailableTimeSlots.tsx:67]:
```suggestion
  const somethingThatDescribesWhatFilterDoes = schedule?.data?.slots).filter((slot)=>dayjs(selectedDate).diff(slot,'day')<=0;
  const nonEmptyScheduleDays = useNonEmptyScheduleDays(somethingThatDescribesWhatFilterDoes);
```
Increasing script by 1 line but it will become more readable. 😄

File: packages/features/bookings/Booker/components/Header.tsx [hunk 11]
```diff
@@ -16,10 +16,12 @@ export function Header({
   extraDays,
   isMobile,
   enabledLayouts,
+  nextslots,
```
Comment (alannnc) [inline packages/features/bookings/Booker/components/Header.tsx:19]:
```suggestion
  nextSlots,
```

File: packages/features/bookings/Booker/components/Header.tsx [hunk 12]
```diff
@@ -16,10 +16,12 @@ export function Header({
...
 }: {
   extraDays: number;
   isMobile: boolean;
   enabledLayouts: BookerLayouts[];
+  nextslots: number;
```
Comment (alannnc) [inline packages/features/bookings/Booker/components/Header.tsx:24]:
```suggestion
  nextSlots: number;
```

File: packages/features/bookings/Booker/components/Header.tsx [hunk 13]
```diff
@@ -71,14 +76,14 @@ export function Header({
             color="minimal"
             StartIcon={ChevronLeft}
             aria-label="Previous Day"
-            onClick={() => addToSelectedDate(-extraDays - 1)}
+            onClick={() => addToSelectedDate(layout === BookerLayouts.COLUMN_VIEW ? (-nextslots) : (-extraDays - 1))}
```
Comment (alannnc) [inline packages/features/bookings/Booker/components/Header.tsx:79]:
```suggestion
            onClick={() => addToSelectedDate(layout === BookerLayouts.COLUMN_VIEW ? (-nextSlots) : (-extraDays - 1))}
```

File: packages/features/bookings/Booker/components/Header.tsx [hunk 14]
```diff
@@ -71,14 +76,14 @@ export function Header({
...
           />
           <Button
             variant="icon"
             color="minimal"
             StartIcon={ChevronRight}
             aria-label="Next Day"
-            onClick={() => addToSelectedDate(extraDays + 1)}
+            onClick={() => addToSelectedDate(layout === BookerLayouts.COLUMN_VIEW ? nextslots : (extraDays + 1))}
```
Comment (alannnc) [inline packages/features/bookings/Booker/components/Header.tsx:86]:
```suggestion
            onClick={() => addToSelectedDate(layout === BookerLayouts.COLUMN_VIEW ? nextSlots : (extraDays + 1))}
```

**Review by alannnc — DISMISSED** [review]
Missing some prettier lint, I will push fixable changes but we still missing some readability on some code.

File: packages/features/bookings/Booker/Booker.tsx [hunk 15]
```diff
@@ -72,9 +77,28 @@ const BookerComponent = ({
...
+  const nonEmptyScheduleDays = useNonEmptyScheduleDays(schedule?.data?.slots).filter(
+    (slot) => dayjs(selectedDate).diff(slot, "day") <= 0
+  );
+
   const extraDays = isTablet ? extraDaysConfig[layout].tablet : extraDaysConfig[layout].desktop;
   const bookerLayouts = event.data?.profile?.bookerLayouts || defaultBookerLayoutSettings;
   const animationScope = useBookerResizeAnimation(layout, bookerState);
+  const addonDays =
+    nonEmptyScheduleDays.length < extraDays ? (extraDays - nonEmptyScheduleDays.length + 1) * 7 : 0;
+  const availableSlots = nonEmptyScheduleDays.slice(0, extraDays + 1);
```
Comment (alannnc) [inline packages/features/bookings/Booker/Booker.tsx:91]:
```suggestion
  const extraDaysOffset = extraDays + 1; // Reason why this offset it's needed or what it does.
  const availableSlots = nonEmptyScheduleDays.slice(0, extraDaysOffset);
```
Seeing a lot of + 1's we are better of declaring a name for that and a comment will help others in the future.

File: packages/features/bookings/Booker/Booker.tsx [hunk 16]
```diff
@@ -72,9 +75,20 @@ const BookerComponent = ({
...
   );
 
+  const date = dayjs(selectedDate).format("YYYY-MM-DD");
+  const schedule = useScheduleForEvent({prefetchNextMonth: true});
+  const nonEmptyScheduleDays = useNonEmptyScheduleDays(schedule?.data?.slots).filter((slot)=>dayjs(selectedDate).diff(slot,'day')<=0);;
+  
   const extraDays = isTablet ? extraDaysConfig[layout].tablet : extraDaysConfig[layout].desktop;
   const bookerLayouts = event.data?.profile?.bookerLayouts || defaultBookerLayoutSettings;
   const animationScope = useBookerResizeAnimation(layout, bookerState);
+  const addonDays = nonEmptyScheduleDays.length < extraDays ? (extraDays - nonEmptyScheduleDays.length + 1) * 7  : 0;
```
[the remark this answers is not in the document]
Comment (VinoV1999) [reply packages/features/bookings/Booker/Booker.tsx]: ahh, it refers no of days in a week (weekdays + weekend) :blush:

File: packages/features/bookings/Booker/Booker.tsx (hunk 8 above)
Comment (VinoV1999) [reply packages/features/bookings/Booker/Booker.tsx]: The reason it was created is to calculate the no of days in between the available slots that's currently visible on screen. 
Screenshot 2023-07-14 at 8 57 46 AM

And it's only used for ColumnView. So we can keep **ColumnViewExtraDays**

File: packages/features/bookings/Booker/components/AvailableTimeSlots.tsx (hunk 10 above)
Comment (VinoV1999) [reply packages/features/bookings/Booker/components/AvailableTimeSlots.tsx:67]: Basically this filters returns available dates from selected date till the end.

File: packages/features/bookings/Booker/Booker.tsx (hunk 9 above)
Comment (VinoV1999) [reply packages/features/bookings/Booker/Booker.tsx]: need to use same name in `Header.tsx` too. No issues I'll do ✌️

File: packages/features/bookings/Booker/Booker.tsx (hunk 15 above)
Comment (VinoV1999) [reply packages/features/bookings/Booker/Booker.tsx:91]: extraDays + 1 is used only once in the whole code. I though if it's used more than one, then it's obvious to declare a variable. I feel it's better to go with comment line describing the purpose.

**Review by shivamklr — CHANGES_REQUESTED** [review]
Consider resolving the conflicts. And thank you for the contribution @VinoV1999

**Comment by VinoV1999** [comment]
Resolved ✌️

**Review by shivamklr — DISMISSED** [review]
Tested, works. Feel free to review the code team.

**Review by keithwillcode — DISMISSED** [review]
@VinoV1999 Could you fix the conflicts please?

**Comment by zomars** [comment]
We have some type errors. Can we fix those?

**Review by zomars — APPROVED** [review]
Looks good to merge. Thank you for your contribution 🙏
