### PR TITLE
Fix "User Added Question" Label in Email and Calendar Invite

### LINKED ISSUE #7493: Email shows question name instead of question label for a User added question
For a user added question, email shows the question `name` as label. It should be the question label only.
Screenshot 2023-03-03 at 5 41 05 PM

Email - Wrong
Screenshot 2023-03-03 at 5 40 47 PM

Success Page(booking/[uid]) - Correct
Screenshot 2023-03-03 at 5 40 55 PM

The behaviour is like this because we send same payload to Webhook and Email. Webhook needs to have name as the object key.

**The issue is only in main right now.**

### PR DESCRIPTION
**Pull request by hariombalhara**
Fixes #7493

## What does this PR do?

Fixes # (issue)

**Environment**:  Production

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [x] Simply add user field and check that label is shown in Email and Calendar Invite. Also check that webhook has both label and value

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/types/Calendar.d.ts [hunk 1]
```diff
@@ -165,10 +165,22 @@ export interface CalendarEvent {
   seatsPerTimeSlot?: number | null;
 
   // It has responses to all the fields(system + user)
-  responses?: Prisma.JsonObject | null;
+  responses?: Record<
```
Comment (hariombalhara) [inline packages/types/Calendar.d.ts:168]: Because CalendarEvent payload is common for Email, Calendar and Webhook, send it in this format. It would allow webhook payload to uniquely identify any field's response even if label changes. It also allows, Email and Calendars to show the current value of label instead of the name for the field

File: packages/emails/src/components/UserFieldsResponses.tsx [hunk 2]
```diff
@@ -4,13 +4,20 @@ import { Info } from "./Info";
 
 export function UserFieldsResponses(props: { calEvent: CalendarEvent }) {
   const { customInputs, userFieldsResponses } = props.calEvent;
-  const responses = userFieldsResponses || customInputs;
-  if (!responses) return null;
+  let labelValueMap: Record<string, string | string[]> = {};
```
Comment (emrysal) [inline packages/emails/src/components/UserFieldsResponses.tsx:7]: This should be within a function & reused. Easier typing too

**Review by emrysal — CHANGES_REQUESTED** [review]

**Review by emrysal — APPROVED** [review]
⚡ LGTM

**Comment by zomars** [comment]
We need to update E2E tests. [It is broken on main](https://github.com/calcom/cal.com/pull/6900/files#annotation_9489476712)
