### PR TITLE
Fix Impersonation Refresh Bug

### LINKED ISSUE #5625: [CAL-432] On impersonation, a blank page loads first.  You must refresh to see anything.
Found a bug? Please fill out the sections below. 👍

### Issue Summary

On first impersonating another user, a blank screen loads.  See video for dev console error.

### Steps to Reproduce

1. login with a user with admin permissions
2. click settings
3. click impersonate under admin
4. enter the person you wish to impersonate
5. click impersonate

Notice the page that loads is blank

similar behavior to this bug
[https://github.com/calcom/cal.com/issues/5382](https://github.com/calcom/cal.com/issues/5382)

### Technical details

Self hosted, v2.2.2

[https://user-images.githubusercontent.com/117048096/203171103-ffff935e-5ce8-4f59-b4f2-926d22dece4f.mp4](https://user-images.githubusercontent.com/117048096/203171103-ffff935e-5ce8-4f59-b4f2-926d22dece4f.mp4)

> From [SyncLinear.com](https://synclinear.com)

### PR DESCRIPTION
**Pull request by sean-brydon**
* The admin checker was redirecting to a page that didn't exist. Fixed this to redirect to the correct place 
* Also added the new top banner to replace the old impersonation banner.

CleanShot 2022-11-25 at 11 51 00@2x

Fixes: #5625

### CODE REVIEW

**Review by emrysal — APPROVED** [review]
🚀

File: packages/features/ee/impersonation/components/ImpersonatingBanner.tsx [hunk 1]
```diff
@@ -1,8 +1,7 @@
 import { useSession } from "next-auth/react";
-import { Trans } from "next-i18next";
 
 import { useLocale } from "@calcom/lib/hooks/useLocale";
-import { Alert } from "@calcom/ui";
+import { TopBanner } from "@calcom/ui";
```
Comment (zomars) [inline packages/features/ee/impersonation/components/ImpersonatingBanner.tsx:4]: Very nice

**Review by zomars — APPROVED** [review]
Ship it
