### PR TITLE
fix: Members count when `team` slug is same as `org` slug

### LINKED ISSUE #12123: [CAL-2656] A team with same slug as it's org - shows the members count as zero.
image
This is on org profile page i.e. calcom.cal.local:3000

Normally it won't happen but as we are migrating teams to orgs, it would be more common.

<sub>[CAL-2656](https://linear.app/calcom/issue/CAL-2656/a-team-with-same-slug-as-its-org-shows-the-members-count-as-zero)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?
Fixes #12123

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
- Create a team within an org
- Add a few members in it
- Rename the team slug to be same as org slug.
- Go to org profile page(calcom.cal.local:3000) and see that the team `calcom` shows 0 members. This bug is fixed here.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by hariombalhara** [comment]
Current dependencies on/for this PR:
* main
  * **PR #12095** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/12095" target="_blank">Graphite</a> 
    * **PR #12116** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/12116" target="_blank">Graphite</a> 
      * **PR #12124** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/12124" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/calcom/cal.com/12124?utm_source=stack-comment).

File: packages/lib/server/queries/teams/index.ts [hunk 1]
```diff
@@ -153,20 +154,20 @@ export async function getTeamWithMembers(args: {
...
+  const members = orgOrTeam.members.map((obj) => {
     const { credentials, ...restUser } = obj.user;
     return {
       ...restUser,
       role: obj.role,
       accepted: obj.accepted,
       disableImpersonation: obj.disableImpersonation,
       subteams: orgSlug
-        ? obj.user.teams.filter((obj) => obj.team.slug !== orgSlug).map((obj) => obj.team.slug)
+        ? obj.user.teams.filter((obj) => obj.team.id !== orgOrTeam.id).map((obj) => obj.team.slug)
```
Comment (hariombalhara) [inline packages/lib/server/queries/teams/index.ts:170]: This is the fix. Instead of skipping the same slug team, we want to skip the org because every member would be a part of it.

File: packages/lib/server/queries/teams/index.ts [hunk 2]
```diff
@@ -153,20 +154,20 @@ export async function getTeamWithMembers(args: {
     });
   }
 
-  const team = teams[0];
-  if (!team) return null;
+  const orgOrTeam = teams[0];
```
Comment (hariombalhara) [inline packages/lib/server/queries/teams/index.ts:157]: Renamed to better convey that it could be org or a regular team, depending on the params passed to fn.

File: packages/lib/server/queries/teams/index.ts [hunk 3]
```diff
@@ -153,20 +154,20 @@ export async function getTeamWithMembers(args: {
...
   const appDataMap = new Map();
-  const members = team.members.map((obj) => {
+  const members = orgOrTeam.members.map((obj) => {
     const { credentials, ...restUser } = obj.user;
     return {
       ...restUser,
       role: obj.role,
       accepted: obj.accepted,
       disableImpersonation: obj.disableImpersonation,
       subteams: orgSlug
```
Comment (hariombalhara) [inline packages/lib/server/queries/teams/index.ts:169]: When `orgSlug` is there, orgOrTeam is actually an `org`.

**Review by ThyMinimalDev — APPROVED** [review]
LGTM, we need to migrate org to its own data model at some point to avoid confusion like this where we have to create variables like teamOrOrg

**Comment by hariombalhara** [comment]
> LGTM, we need to migrate org to its own data model at some point to avoid confusion like this where we have to create variables like teamOrOrg

Agreed.
