### PR TITLE
fix: #15697 Assignment warning modal poping up ,even when hosts are added .

### LINKED ISSUE #15697: [CAL-4005] Assignment availability modal
Found a bug? Please fill out the sections below. 👍

### Issue Summary

https://www.loom.com/share/252e4a8d52ae417b980b2cb425561e46?sid=46024e8a-5954-47a2-bb06-f646fa1fca8f

### Steps to Reproduce

Uncomment the availability modal in `event-types-single-view.tsx:848` 
Use any team event type - assign users and try to leave the event type setup page. 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results
Modal pops up even with hosts or managed users assigned

### Expected Results

It only pops up for team events - when hosts is empty or managed users assigned is empty etc

We should extract this hook and make it testable to cover all edgecases

<sub>[CAL-4005](https://linear.app/calcom/issue/CAL-4005/assignment-availability-modal)</sub>

### PR DESCRIPTION
**Pull request by vijayraghav-io**
## What does this PR do?

- Fixes #15697 
- Fixes CAL-4005 (Linear issue number - should be visible at the bottom of the GitHub issue description)

After Changes:

https://www.loom.com/share/96a6c9c3cee543bcb716a3b01aa8306f?sid=10a77132-294d-4d3e-b25e-5a6901a40d5c

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A -  I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by sean-brydon — DISMISSED** [review]
Hi - we also need to take into consideration that assignedUsers can be empty for MANAGED event types. 

Also please refer to the issue - we should try and extract this logic out of the useEffect into a new hook that should be testable

**Comment by vijayraghav-io** [comment]
> Hi - we also need to take into consideration that assignedUsers can be empty for MANAGED event types.
> 
> Also please refer to the issue - we should try and extract this logic out of the useEffect into a new hook that should be testable

Yes this check is already done for ManagedEventType on line 413

**Comment by sean-brydon** [comment]
> > Hi - we also need to take into consideration that assignedUsers can be empty for MANAGED event types.
> > Also please refer to the issue - we should try and extract this logic out of the useEffect into a new hook that should be testable
> 
> Yes this check is already done for ManagedEventType on line 413

Good spot - we also want this extracted and tested. 

Thanks

**Comment by vijayraghav-io** [comment]
working on extracting the logic out of useEffect() and add tests

**Comment by vijayraghav-io** [comment]
in progress... will update once the extraction and tests are complete

**Comment by vijayraghav-io** [comment]
@sean-brydon , extracted out the logic to check if assignments are empty and added test cases, retained the route handler in useEffect. Please let me know if this is what expected.

File: apps/web/modules/event-types/views/event-types-single-view.tsx [hunk 1]
```diff
@@ -401,25 +402,24 @@ const EventTypePage = (props: EventTypeSetupProps & { allActiveWorkflows?: Workf
     formState: { isDirty: isFormDirty, dirtyFields },
   } = formMethods;
 
+  const assignedUsers = formMethods.watch("children");
+  const hosts = formMethods.watch("hosts");
+  const assignAllTeamMembers = formMethods.watch("assignAllTeamMembers");
+
```
Comment (anikdhabal) [inline apps/web/modules/event-types/views/event-types-single-view.tsx:408]: As we check values using the form watch method, the modal isn't shown if hosts or users are assigned, but the form isn't saved. Please fix this.

**Review by anikdhabal — CHANGES_REQUESTED** [review]

File: apps/web/modules/event-types/views/event-types-single-view.tsx (hunk 1 above)
Comment (vijayraghav-io) [reply apps/web/modules/event-types/views/event-types-single-view.tsx:408]: ack

Comment (vijayraghav-io) [reply apps/web/modules/event-types/views/event-types-single-view.tsx:418]: I had thought since we are allowing user to navigate away from the form without saving, so this should be ok.
Anyway, updated to handle this scenario also.

**Review by anikdhabal — COMMENTED** [review]
@vijayraghav-io pls fix the conflicts

**Comment by vijayraghav-io** [comment]
> @vijayraghav-io pls fix the conflicts

sure

**Comment by vijayraghav-io** [comment]
@anikdhabal , done

File: apps/web/components/eventtype/AssignmentWarningDialog.tsx [hunk 2]
```diff
@@ -39,7 +39,7 @@ const AssignmentWarningDialog = (props: AssignmentWarningDialogProps) => {
               router.replace(`/event-types/${id}?tabName=team`);
             }}
             color="minimal">
-            {t("go_back_and_assign")}
+            {t("go_back_assign_and_save")}
```
Comment (anikdhabal) [inline apps/web/components/eventtype/AssignmentWarningDialog.tsx:42]: I think we don't need to change it. In our app, we need to save maximum places in order to update, so it was understandable.

File: apps/web/modules/event-types/views/event-types-single-view.tsx [hunk 3]
```diff
@@ -400,40 +402,50 @@ const EventTypePage = (props: EventTypeSetupProps & { allActiveWorkflows?: Workf
...
+      isManagedEventType: eventType.schedulingType === SchedulingType.MANAGED,
+      isTeamEvent: !!team,
+    })
+  );
+
+  const assignedUsers = formMethods.watch("children");
+  const hosts = formMethods.watch("hosts");
+  const assignAllTeamMembers = formMethods.watch("assignAllTeamMembers");
+
+  useEffect(() => {
```
Comment (anikdhabal) [inline apps/web/modules/event-types/views/event-types-single-view.tsx:419]: As per issue we should try and extract this logic out of the useEffect into a new hook

File: apps/web/components/eventtype/AssignmentWarningDialog.tsx (hunk 2 above)
Comment (vijayraghav-io) [reply apps/web/components/eventtype/AssignmentWarningDialog.tsx]: Oh, ok!

File: apps/web/modules/event-types/views/event-types-single-view.tsx (hunk 3 above)
Comment (vijayraghav-io) [reply apps/web/modules/event-types/views/event-types-single-view.tsx:405]: watch was used to make form dynamic, since we rely on Saved State only, updated.

File: apps/web/lib/checkForEmptyAssignment.ts [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+// returns false: for all other scenarios.
+export function checkForEmptyAssignment({
+  assignedUsers,
+  hosts,
+  isManagedEventType,
+  assignAllTeamMembers,
+  isTeamEvent,
+}: {
+  assignedUsers: any;
+  hosts: any;
```
Comment (anikdhabal) [inline apps/web/lib/checkForEmptyAssignment.ts:12]: This is not good practice and would be better to avoid it. Instead, you can import the types `HOST` and `ChildrenEventType` from the main event-type component or declare them here.

Comment (vijayraghav-io) [reply apps/web/lib/checkForEmptyAssignment.ts]: updated

File: apps/web/lib/checkForEmptyAssignment.ts [hunk 5]
```diff
@@ -0,0 +1,30 @@
...
+  assignAllTeamMembers: boolean;
+  isTeamEvent: boolean;
+}): boolean {
+  if (isTeamEvent && assignAllTeamMembers) {
+    return false;
+  } else if (
+    isTeamEvent &&
+    // For managed eventtype check if assigned users are empty.
+    // For non-managed eventtype check if hosts are empty.
+    (isManagedEventType ? assignedUsers.length === 0 : hosts.length === 0)
```
Comment (anikdhabal) [inline apps/web/lib/checkForEmptyAssignment.ts:25]: Hey as @sean-brydon suggested that assignedUsers can be empty for ManagedEventType. So pls fix it

File: apps/web/modules/event-types/views/event-types-single-view.tsx [hunk 6]
```diff
@@ -144,6 +146,8 @@ const querySchema = z.object({
 
 export type EventTypeSetupProps = RouterOutputs["viewer"]["eventTypes"]["get"];
 export type EventTypeSetup = RouterOutputs["viewer"]["eventTypes"]["get"]["eventType"];
+export type EventTypeAssignedUsers = RouterOutputs["viewer"]["eventTypes"]["get"]["eventType"]["children"];
+export type EventTypeHosts = RouterOutputs["viewer"]["eventTypes"]["get"]["eventType"]["hosts"];
```
Comment (anikdhabal) [inline apps/web/modules/event-types/views/event-types-single-view.tsx:150]: "No need to declare it again; the type `Host` is already present in file. Please export it."

File: apps/web/lib/checkForEmptyAssignment.ts [hunk 7]
```diff
@@ -0,0 +1,30 @@
...
+  assignedUsers: EventTypeAssignedUsers;
+  hosts: EventTypeHosts;
+  isManagedEventType: boolean;
+  assignAllTeamMembers: boolean;
+  isTeamEvent: boolean;
+}): boolean {
+  if (isTeamEvent && assignAllTeamMembers) {
+    return false;
+  } else if (
+    isTeamEvent &&
```
Comment (anikdhabal) [inline apps/web/lib/checkForEmptyAssignment.ts:22]: No need to add `isTeamEvent` check here.

File: apps/web/lib/checkForEmptyAssignment.ts [hunk 8]
```diff
@@ -0,0 +1,30 @@
...
+  assignAllTeamMembers,
+  isTeamEvent,
+}: {
+  assignedUsers: EventTypeAssignedUsers;
+  hosts: EventTypeHosts;
+  isManagedEventType: boolean;
+  assignAllTeamMembers: boolean;
+  isTeamEvent: boolean;
+}): boolean {
+  if (isTeamEvent && assignAllTeamMembers) {
```
Comment (anikdhabal) [inline apps/web/lib/checkForEmptyAssignment.ts:19]: `isTeamEvent` should be an independent check and should be the first check there. No need to reuse it.

File: apps/web/test/lib/checkForEmptyAssignment.test.ts
Comment (anikdhabal) [inline apps/web/test/lib/checkForEmptyAssignment.test.ts:1]: Need to update the test case also for managed event type.

**Review by anikdhabal — CHANGES_REQUESTED** [review]
Left some blocking comments. Pls address them

File: apps/web/lib/checkForEmptyAssignment.ts (hunk 5 above)
Comment (vijayraghav-io) [reply apps/web/lib/checkForEmptyAssignment.ts:25]: No, he is trying to say to consider the scenario of ManagedEventType having empty assigned users.
Also , If we refer to current main branch code :
https://github.com/calcom/cal.com/blob/33e1abf4a7324b3bd2c9a0d5708379e51636234b/apps/web/modules/event-types/views/event-types-single-view.tsx#L412

Here warning dialog is shown if ManagedEventType and assignedusers are empty.

File: apps/web/modules/event-types/views/event-types-single-view.tsx (hunk 6 above)
Comment (vijayraghav-io) [reply apps/web/modules/event-types/views/event-types-single-view.tsx:150]: Yes , i tried using type - Host already defined in event-types-single-view.tsx.
Since the prop-priority is non-null, it is breaking other components.

File: apps/web/lib/checkForEmptyAssignment.ts (hunk 5 above)
Comment (anikdhabal) [reply apps/web/lib/checkForEmptyAssignment.ts:25]: Ahh, got it

File: apps/web/lib/checkForEmptyAssignment.ts (hunk 7 above)
Comment (vijayraghav-io) [reply apps/web/lib/checkForEmptyAssignment.ts:22]: Updated with more comments.

File: apps/web/lib/checkForEmptyAssignment.ts (hunk 8 above)
Comment (vijayraghav-io) [reply apps/web/lib/checkForEmptyAssignment.ts:19]: Updated

**Comment by anikdhabal** [comment]
@vijayraghav-io I think you committed two files mistakenly. And the component or file name is correct, no need to change.

File: apps/web/lib/hasEmptyAssignment.ts [hunk 9]
```diff
@@ -0,0 +1,43 @@
...
+  assignedUsers: EventTypeAssignedUsers;
+  hosts: EventTypeHosts;
+  schedulingType: SchedulingType | null;
+  assignAllTeamMembers: boolean;
+  isTeamEvent: boolean;
+}): boolean {
+  // if Non-Team event, no need to check for assignments.
+  if (!isTeamEvent) {
+    return false;
+  }
```
Comment (anikdhabal) [inline apps/web/lib/hasEmptyAssignment.ts:24]: @vijayraghav-io I suggested you make this independent test in the `handleRouteChange` function not here. Should be present above this `!leaveWithoutAssigningHosts.current &&`

**Comment by anikdhabal** [comment]
@vijayraghav-io pls revert the name back to `checkForEmptyAssignment` or something like `isAssignmentIncomplete`. Currently it does not feel good.

File: apps/web/lib/checkForEmptyAssignment.ts [hunk 10]
```diff
@@ -0,0 +1,35 @@
...
+
+  // For Managed EventType, check if assigned users are empty.
+  if (schedulingType === "MANAGED" && assignedUsers.length === 0) {
+    return true;
+  }
+
+  // For Non-Managed EventType (i.e RoundRobin or Collective), check if hosts are empty.
+  if ((schedulingType === "ROUND_ROBIN" || schedulingType === "COLLECTIVE") && hosts.length === 0) {
+    return true;
+  }
```
Comment (anikdhabal) [inline apps/web/lib/checkForEmptyAssignment.ts:32]:
```
if (isManagedEventType ? assignedUsers.length === 0 : hosts.length === 0)) {
    return true;
  }
```
This simply remove all the extra work and import. I donno why you changed it

File: apps/web/modules/event-types/views/event-types-single-view.tsx [hunk 11]
```diff
@@ -400,40 +403,35 @@ const EventTypePage = (props: EventTypeSetupProps & { allActiveWorkflows?: Workf
...
-  //   return () => {
-  //     router.events.off("routeChangeStart", handleRouteChange);
-  //   };
-  // }, [router]);
+  useEffect(() => {
+    const handleRouteChange = (url: string) => {
+      const paths = url.split("/");
+
+      if (
+        team &&
```
Comment (anikdhabal) [inline apps/web/modules/event-types/views/event-types-single-view.tsx:411]: change it to `!!team`

**Comment by anikdhabal** [comment]
@vijayraghav-io Left a few suggestions, please address them, and finally test all the conditions locally to ensure that everything is handled.

File: apps/web/lib/checkForEmptyAssignment.ts (hunk 10 above)
Comment (vijayraghav-io) [reply apps/web/lib/checkForEmptyAssignment.ts:32]: Both are doing exactly the same, i thought this will be more clearer and readable / understandable, because there was some confusion with ManagedEventType earlier.

Comment (vijayraghav-io) [reply apps/web/lib/checkForEmptyAssignment.ts:32]: Its the same earlier the check if SchedulingType === 'MANAGED' was done before calling the function, now SchedulingType is passed as argument. Also if new SchedulingType is added in future, we can still handle this inside this fn only

Comment (anikdhabal) [reply apps/web/lib/checkForEmptyAssignment.ts:32]: Yes, I know. However, it would be simpler. If we add the new SchedulingType in the future; we would need to update not only here but also in most of the places. PLs do it.

**Comment by anikdhabal** [comment]
@vijayraghav-io can you provide a loom video of the result. Make sure to test all the event types.

**Comment by vijayraghav-io** [comment]
@anikdhabal , just updated dependencies array for useEffect(), the edgecase (mentioned in prev comment) is also covered.

Tested once again for all EventTypes (RR, Collective, Managed) , working fine for all scenarios (including the edge case). Here is the video for same. Please check.

https://www.loom.com/share/96a6c9c3cee543bcb716a3b01aa8306f?sid=c4e8dc06-abe6-419f-9394-09ae4be08d8a

All Good to go!

**Comment by anikdhabal** [comment]
@vijayraghav-io good observation and great works. Tested it, works fine now.

**Review by anikdhabal — APPROVED** [review]
LGTM! Great works @vijayraghav-io
