### PR TITLE
fix: add missing title

### LINKED ISSUE #13241: [CAL-2974] Missing <title> on a bunch of pages.
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A lot of pages don't have a <HeadSeo> set and therefore default to Cal.com | Cal.com.
Pages are listed below.
Pages: 

- [ ] bookings, 
- [ ] availability, 
- [ ] teams, 
- [ ] apps, 
- [ ] routing-forms, 
- [ ] workflows and 
- [ ] insights.

### Steps to Reproduce

Go to any of the pages listed and look at the title, it's just Cal.com | Cal.com

### Actual Results

Cal.com | Cal.com

### Expected Results

Bookings | Cal.com
Availability | Cal.com 
etc...

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence

Just looking.

<sub>[CAL-2974](https://linear.app/calcom/issue/CAL-2974/missing-title-on-a-bunch-of-pages)</sub>

### PR DESCRIPTION
**Pull request by anikdhabal**
## What does this PR do?

Fixes #13241
/claim #13241

### CODE REVIEW

File: apps/web/components/apps/layouts/AppsLayout.tsx [hunk 1]
```diff
@@ -22,7 +22,8 @@ export default function AppsLayout({ children, actions, emptyStore, ...rest }: A
 
   if (session.status === "loading") return <></>;
   return (
-    <ShellMain {...rest} actions={actions?.("block")} hideHeadingOnMobile>
+    <ShellMain {...rest} actions={actions?.("block")} withoutSeo hideHeadingOnMobile>
+      <HeadSeo title="App Store" description="Connecting people, technology and the workplace." />
```
Comment (Udit-takkar) [inline apps/web/components/apps/layouts/AppsLayout.tsx:26]: I think we should use i18n here.

Comment (Udit-takkar) [reply apps/web/components/apps/layouts/AppsLayout.tsx:26]: and other pages as well

Comment (anikdhabal) [reply apps/web/components/apps/layouts/AppsLayout.tsx:26]: I was not using i18n, as @PeerRich suggested. Let me quickly fix that.

Comment (Udit-takkar) [reply apps/web/components/apps/layouts/AppsLayout.tsx:26]: Okay

Comment (hariombalhara) [reply apps/web/components/apps/layouts/AppsLayout.tsx:26]: I don't understand why we are passing withoutSeo to ShellMain? Doesn't ShellMain support for SEO work correctly?

File: apps/web/pages/bookings/[status].tsx [hunk 2]
```diff
@@ -153,7 +153,8 @@ export default function Bookings() {
   const [animationParentRef] = useAutoAnimate<HTMLDivElement>();
 
   return (
-    <ShellMain hideHeadingOnMobile heading={t("bookings")} subtitle={t("bookings_description")}>
+    <ShellMain withoutSeo hideHeadingOnMobile heading={t("bookings")} subtitle={t("bookings_description")}>
```
Comment (hariombalhara) [inline apps/web/pages/bookings/[status].tsx:156]: It looks like ShellMain doesn't support  adding HeadSeo at all(which seems like a bug that creeped in later). Shouldn't we simply support HeadSeo there and avoid import HeadSeo everywhere ShellMain is already used

**Review by hariombalhara — DISMISSED** [review]
Thanks @anikdhabal 🙏 Left some comments.

File: apps/web/components/apps/layouts/AppsLayout.tsx (hunk 1 above)
Comment (anikdhabal) [reply apps/web/components/apps/layouts/AppsLayout.tsx:26]: @hariombalhara ShellMain doesn't support SEO, and if we don't provide withoutSeo, then ShellMain uses the heading as the title and the subtitle as the description. So basically, withoutSeo is preventing that.

File: apps/web/pages/bookings/[status].tsx (hunk 2 above)
Comment (anikdhabal) [reply apps/web/pages/bookings/[status].tsx:156]: It's pretty cool idea to support HeadSeo there and avoid import it everywhere.

**Comment by anikdhabal** [comment]
> Thanks @anikdhabal 🙏 Left some comments.

Thanks for your review. Let me fix that quickly.

File: apps/web/components/apps/layouts/AppsLayout.tsx (hunk 1 above)
Comment (anikdhabal) [reply apps/web/components/apps/layouts/AppsLayout.tsx:26]: @hariombalhara yeah that's useless.

**Comment by anikdhabal** [comment]
@hariombalhara update the code.

**Review by Udit-takkar — COMMENTED** [review]
The title keeps changing back to Cal.com | Cal.com on other pages

https://github.com/calcom/cal.com/assets/53316345/7fb6421f-ca43-4546-a350-a190810f339a

**Comment by anikdhabal** [comment]
> The title keeps changing back to Cal.com | Cal.com on other pages
> 
>  Screen.Recording.2024-01-23.at.4.39.03.PM.mov

Thanks for the review. I've updated the code, and now everything is working fine.

File: apps/web/pages/insights/index.tsx [hunk 3]
```diff
@@ -47,7 +46,12 @@ export default function InsightsPage() {
 
   return (
     <div>
-      <ShellMain heading="Insights" subtitle={t("insights_subtitle")}>
+      <Shell
+        withoutMain={false}
+        heading="Insights"
+        subtitle={t("insights_subtitle")}
+        title="Insights"
+        description="View booking insights across your events.">
```
Comment (Udit-takkar) [inline apps/web/pages/insights/index.tsx:54]: @anikdhabal what is the difference between heading and title? description and subtitle?

Comment (anikdhabal) [reply apps/web/pages/insights/index.tsx:54]: Hey @Udit-takkar Thanks for the review. 
Screenshot 2024-01-30 142620
297650212-bdebd4b7-57ef-40ba-8bd9-94df0d79d0ea

Comment (anikdhabal) [reply apps/web/pages/insights/index.tsx:54]: We offer the functionality to set the page title and description. Currently, if the page title and description are not explicitly set, the values of the heading and subtitle are used as the default page title and subtitle.

**Review by Udit-takkar — COMMENTED** [review]
LGTM.

**Comment by Udit-takkar** [comment]
@anikdhabal there are some merge conflicts

**Comment by anikdhabal** [comment]
> @anikdhabal there are some merge conflicts

Yeah, Let me fix that quickly.

**Comment by anikdhabal** [comment]
> @anikdhabal there are some merge conflicts

Fix it.

**Comment by keithwillcode** [comment]
Looks like this one consistently fails tests

**Comment by anikdhabal** [comment]
> Looks like this one consistently fails tests

So what am I going to do now? Also, those tests are not related to the changes.

**Comment by keithwillcode** [comment]
@anikdhabal No, no worries. We'll look into getting the tests fixed.

**Comment by anikdhabal** [comment]
> @anikdhabal No, no worries. We'll look into getting the tests fixed.

Thank you.

**Comment by Udit-takkar** [comment]
this test "login flow user & logout using dashboard" is only failing in this PR. I see two sidebar when i run this E2E test locally on this branch. 

Screenshot 2024-02-06 at 11 54 12 PM

**Comment by anikdhabal** [comment]
> this test "login flow user & logout using dashboard" is only failing in this PR. I see two sidebar when i run this E2E test locally on this branch.
> 
> Screenshot 2024-02-06 at 11 54 12 PM

Thanks for the review. I am on it.

**Comment by anikdhabal** [comment]
Hey @Udit-takkar @keithwillcode  the error is showing in future version.

Screenshot 2024-02-08 002649
Screenshot 2024-02-08 002631

**Comment by anikdhabal** [comment]
Screenshot 2024-02-08 010822
The reason for having two layouts in future mode is that we wrap the component with getLayout. Therefore, we either have to ensure that all components in future mode are wrapped with shellmain, or we have to make getLayout optional there. So that we can use shell as a parent.

I will update the code by today and ensure that everything is perfect in both the default and future modes.

**Comment by anikdhabal** [comment]
I've fixed the double layout issue.

**Review by keithwillcode — APPROVED** [review]

**Comment by anikdhabal** [comment]
@keithwillcode Finally. Thanks for your review.
