### PR TITLE
fix: require confirmation cal video bug

### LINKED ISSUE #16371: [CAL-4176] BUG: Booking confirmation failed
When the event type doesn't have a location set, and is set as an event type that requires confirmation for bookings, when confirming a booking in the [https://app.cal.com/bookings/upcoming](https://app.cal.com/bookings/upcoming) page, the confirmation request fails. The reason is:

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4176](https://linear.app/calcom/issue/CAL-4176/bug-booking-confirmation-failed)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

- Fixes  https://github.com/calcom/cal.com/issues/16371 (GitHub issue number)
- Fixes CAL-4176 (Linear issue number - should be visible at the bottom of the GitHub issue description)

Fixes    

Screenshot 2024-08-28 at 12 31 13 AM

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

1) Remove location from event type
2) Turn on require confirmation in advance settings.
3) Submit a book and accept it.

### CODE REVIEW

File: packages/core/EventManager.ts [hunk 1]
```diff
@@ -186,9 +186,12 @@ export default class EventManager {
...
         if (evt.location && evt.responses) {
-          evt.responses["location"].value = {
-            optionValue: "",
-            value: evt.location,
+          evt.responses["location"] = {
+            ...(evt.responses["location"] ?? {}),
+            value: {
+              optionValue: "",
+              value: evt.location,
+            },
```
Comment (Udit-takkar) [inline packages/core/EventManager.ts:194]: When an event type doesn't have any location set and user submits booking form there is no location field in responses causing Type error "Cannot set properties of undefined"

**Review by emrysal — APPROVED** [review]
Good fix, also happy with the new test :)
