### PR TITLE
fix: clicking on previous step navigates to correct step instead of next

### LINKED ISSUE #22140: Bug: Clicking on previous step indicator navigates to next step instead of selected step
### Issue Summary

While interacting with the step progress bar component (as shown in the attached video), clicking on a previous step's white progress bar unexpectedly navigates the user to the next step, rather than taking them back to the clicked step.

### Steps to Reproduce

1. Go to https://app.cal.com/getting-started/connected-video
2. Click on the progress bar segment representing Step 1 or Step 2.
3. Observe that instead of navigating to Step 1/2, the flow incorrectly advances to Step 4 (next step).

### Actual Results

- Clicking on any previous step bar (e.g., Step 1 or Step 2) causes the flow to skip forward to the next step (Step 5), regardless of which step was clicked.

### Expected Results

- Clicking on a previous step segment (e.g., Step 2) should take the user back to that specific step.

### Technical details

- Browser: Google Chrome Version 137.0.7151.120 (Official Build) (64-bit)

### Evidence

https://github.com/user-attachments/assets/e3102c03-6108-4332-af26-519840c2d5ba

### PR DESCRIPTION
**Pull request by subediDarshan**
## What does this PR do?

This PR ensures that when a user clicks on a previous step's progress bar segment (white bar), they are navigated to that specific step, rather than the next step. This aligns with expected user behavior.

- Fixes #22140

### Before:

https://github.com/user-attachments/assets/295c8042-b07a-486d-8a7d-3c441e178c2a

### After:

https://github.com/user-attachments/assets/0eaa908f-0168-48b5-9a47-b7e695fb9c62

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). (N/A here)
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?
- Run app locally
- Navigate to `http://localhost:3000/getting-started/connected-video`.
- Click on a white progress bar segment representing a previous step (eg: step 2 or 3).
- Confirm that you are taken to the correct step, not the next one.

## Checklist
- ~~I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)~~
- ~~My code doesn't follow the style guidelines of this project~~
- ~~I haven't commented my code, particularly in hard-to-understand areas~~
- ~~I haven't checked if my changes generate no new warnings~~
    

---

## Summary by cubic
Clicking on a previous step in the progress bar now takes users to that exact step, instead of moving them to the next step. This makes navigation match what users expect.

### CODE REVIEW

**Review by Devanshusharma2005 — DISMISSED** [review]
Hey @subediDarshan thanks for the pr , can you please fix the issues suggested by cubic. and also can you make a loom for making sure that the steps only go to previous adjacent one or any step in the previous ?

**Review by kart1ka — DISMISSED** [review]
LGTM

File: packages/ui/components/form/wizard/WizardForm.tsx [hunk 1]
```diff
@@ -63,7 +63,7 @@ function WizardForm<T extends DefaultStep>(props: {
             <Steps
               maxSteps={steps.length}
               currentStep={step}
-              nextStep={noop}
+              navigateToStep={noop}
```
[the remark this answers is not in the document]
Comment (subediDarshan) [reply packages/ui/components/form/wizard/WizardForm.tsx]: 'goToStep' function is now added and passed instead of passing noop to navigateToStep.

File: packages/ui/components/layout/WizardLayout.tsx [hunk 2]
```diff
@@ -58,7 +58,7 @@ export function WizardLayout({
                   </>
                 )}
               </header>
-              <Steps maxSteps={maxSteps} currentStep={currentStep} nextStep={noop} />
+              <Steps maxSteps={maxSteps} currentStep={currentStep} navigateToStep={noop} />
```
[the remark this answers is not in the document]
Comment (subediDarshan) [reply packages/ui/components/layout/WizardLayout.tsx]: Replaced 'navigateToStep={noop}' with disableNavigation.

**Comment by subediDarshan** [comment]
Hey @Devanshusharma2005 
I have addressed issues suggested by cubic.
And here's the video demo showing steps only go to previous adjacent one or any step in the previous and not to the upcoming ones:


https://github.com/user-attachments/assets/79da32b9-e360-4037-8338-c28338777e0a

File: packages/ui/components/form/wizard/WizardForm.tsx (hunk 1 above)
[the remark this answers is not in the document]
Comment (subediDarshan) [reply packages/ui/components/form/wizard/WizardForm.tsx]: Check Commit: 974041fd69a51b3fa600f3664eecb210737963a0

File: packages/ui/components/layout/WizardLayout.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (subediDarshan) [reply packages/ui/components/layout/WizardLayout.tsx]: Check Commit: 974041fd69a51b3fa600f3664eecb210737963a0

**Review by kart1ka — DISMISSED** [review]
LGTM

**Review by sean-brydon — DISMISSED** [review]

**Comment by anikdhabal** [comment]
@subediDarshan pls fix the conflicts

File: packages/ui/components/form/wizard/useWizardState.ts [hunk 3]
```diff
@@ -25,7 +25,7 @@ export function useWizardState(defaultStep = 1, maxSteps: number) {
 
   const goToStep = useCallback(
     (newStep: number) => {
-      setStep(Math.min(Math.max(newStep, 1), maxSteps));
+      setStep(Math.min(Math.max(newStep + 1, 1), maxSteps));
```
Comment (subediDarshan) [inline packages/ui/components/form/wizard/useWizardState.ts:29]: In 'Steps' component (where this 'goToStep' function is passed as prop), 
0-based indexes are passed in goToFunction as newStep,
but 1-based indexes is being used in URL query param (?step=1),
So, +1 conversion is needed here

Comment (kart1ka) [reply packages/ui/components/form/wizard/useWizardState.ts:29]: pls add a comment in the code mentioning the same

**Review by kart1ka — DISMISSED** [review]
Looks good. Thanks for the PR.

File: packages/ui/components/form/wizard/WizardForm.tsx [hunk 4]
```diff
@@ -71,10 +71,9 @@ export function WizardForm({
             <Steps
               maxSteps={maxSteps}
               currentStep={currentStep}
-              nextStep={nextStep}
+              navigateToStep={goToStep}
               stepLabel={stepLabel}
               data-testid="wizard-step-component"
-              disableNavigation={disableNavigation}
```
Comment (anikdhabal) [inline packages/ui/components/form/wizard/WizardForm.tsx:77]: What is the reason for removal of this props?

Comment (subediDarshan) [reply packages/ui/components/form/wizard/WizardForm.tsx:77]: By not passing this prop, disableNavigation=false is set by default (default parameter set in Steps component), which is what we need since we are navigating between previous steps here through 'navigateToStep' function.

File: packages/ui/components/form/wizard/useWizardState.ts (hunk 3 above)
Comment (subediDarshan) [reply packages/ui/components/form/wizard/useWizardState.ts:29]: Comment added c999b7e92a8daaa8cb4dd492e57b36595a9712c3

File: packages/app-store/googlecalendar/lib/CalendarService.ts [hunk 5]
```diff
@@ -677,7 +677,7 @@ export default class GoogleCalendarService implements Calendar {
     const fromDate = new Date(dateFrom);
     const toDate = new Date(dateTo);
     const oneDayMs = 1000 * 60 * 60 * 24;
-    const diff = Math.floor((toDate.getTime() - fromDate.getTime()) / (oneDayMs));
+    const diff = Math.floor((toDate.getTime() - fromDate.getTime()) / oneDayMs);
```
Comment (anikdhabal) [inline packages/app-store/googlecalendar/lib/CalendarService.ts]: Unrelated to this pr. Pls revert

File: apps/web/modules/getting-started/[[...step]]/onboarding-view.tsx [hunk 6]
```diff
@@ -124,6 +124,13 @@ const OnboardingPage = (props: PageProps) => {
   };
   const currentStepIndex = steps.indexOf(currentStep);
 
+  const goToStep = (step: number) => {
+    const newStep = steps[step];
+    startTransition(() => {
+      router.push(`/getting-started/${stepTransform(newStep)}`);
+    });
+  };
```
[the remark this answers is not in the document]
Comment (anikdhabal) [reply apps/web/modules/getting-started/[[...step]]/onboarding-view.tsx:133]: @subediDarshan can you pls verify this?

[the remark this answers is not in the document]
Comment (subediDarshan) [reply apps/web/modules/getting-started/[[...step]]/onboarding-view.tsx:133]: The step parameter can’t be out of bounds because its value is limited by maxSteps, which equals steps.length.
(argument passed for step parameter is actually an iterator of steps array)

File: packages/app-store/googlecalendar/lib/CalendarService.ts (hunk 5 above)
Comment (subediDarshan) [reply packages/app-store/googlecalendar/lib/CalendarService.ts]: This change no longer exists in the current PR.

**Review by anikdhabal — APPROVED** [review]

**Review by volnei — APPROVED** [review]
