### PR TITLE
Fix/infinite booking list

### LINKED ISSUE #2928: Duplicated event list on upcoming tab
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Looks there some inconsistency when loading bookings from the upcoming tab.

### Steps to Reproduce

1. Go to Pro demo account that has recurring events, add some future events to it.
2. Go to upcoming list
3. See some duplicated events among recurring ones.

Something in the prisma findMany broke when recurring events where added.

### Technical details

- Latest Firefox
-Recording:
https://www.loom.com/share/b61ff048ba824efbb92ff056bc7c78eb

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

It looks like our booking list does some custom filtering and it wasn't handling all event cases for our infiniteQuery cursor, skip and take parameters.

Fixes #2928 

**Environment**:  Production

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] When your booking list is below 10 (default take/limit it's 10) your load more events should be disabled.
- [ ] When your booking list is equal or more than 10 it shouldn't load any duplicates and not miss anyone.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: apps/web/server/routers/viewer.tsx [hunk 1]
```diff
@@ -466,9 +466,9 @@ const loggedInViewerRouter = createProtectedRouter()
       }
 
       let nextCursor: typeof skip | null = skip;
-
-      if (bookingsFetched > take) {
-        bookings.shift();
+      if (input.cursor === undefined && bookings.length + groupedRecurringBookings.length < take) {
```
Comment (alannnc) [inline apps/web/server/routers/viewer.tsx:469]: With these we handle 3 scenarios

- First fetch, when cursor its undefined and results length are lower than page size (take prop)
- Normal pagination
- End of page

**Review by zomars — APPROVED** [review]

**Review by hariombalhara — APPROVED** [review]
