### PR TITLE
fix/cannot-duplicate-and-event-type-teams

### LINKED ISSUE #6091: [CAL-617] Cannot Duplicate an Event Type
From a customer:

*Cannot Duplicate an Event Type*

See link below for a quick video of me reproducing the bug along with other helpful debugging resources :slightly_smiling_face:

[https://app.birdeatsbug.com/sessions/-XcUAmWVwceUue0HIcCHY7LeuTVyZQH5zO-Vk88L8lsi](https://app.birdeatsbug.com/sessions/-XcUAmWVwceUue0HIcCHY7LeuTVyZQH5zO-Vk88L8lsi)

[Cannot Duplicate an Event Type](https://app.birdeatsbug.com/sessions/-XcUAmWVwceUue0HIcCHY7LeuTVyZQH5zO-Vk88L8lsi)

Reprod Steps

1. Create an event type
2. Open event type menu and select duplicate
3. Change any details for the new event type
4. Press “Continue”
   Expected
   When user presses continue, a duplicate event type is created with any changes made during duplication.
   Actual
   Dead click when pressing continue.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-617](https://linear.app/calcom/issue/CAL-617/cannot-duplicate-an-event-type)</sub>

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

- Change type of createEventTypeInput to createEventTypeUncheckedInput.
- Add try catch to whole duplicate trpc function

Fixes # (issue)

**Environment**: Staging(main branch) / Production

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Use teampro account and try to duplicate an event team
- [ ] Should work now

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/trpc/server/routers/viewer/eventTypes.tsx [hunk 1]
```diff
@@ -622,111 +622,114 @@ export const eventTypesRouter = router({
...
-      include: {
-        customInputs: true,
-        schedule: true,
-        users: true,
-        team: true,
-        workflows: true,
-        webhooks: true,
-      },
-    });
+    try {
```
Comment (alannnc) [inline packages/trpc/server/routers/viewer/eventTypes.tsx:625]: Look like everything changed but just wrapped entire function in try/catch

File: packages/trpc/server/routers/viewer/eventTypes.tsx [hunk 2]
```diff
@@ -622,111 +622,114 @@ export const eventTypesRouter = router({
...
+        descriptionAsSafeHTML: _descriptionAsSafeHTML,
+        ...rest
+      } = eventType;
+
+      const data: Prisma.EventTypeUncheckedCreateInput = {
+        ...rest,
+        title: newEventTitle,
+        slug: newSlug,
+        locations: locations ?? undefined,
+        teamId: team ? team.id : undefined,
```
Comment (alannnc) [inline packages/trpc/server/routers/viewer/eventTypes.tsx:686]: here we changed team: to teamId

**Review by leog — APPROVED** [review]
LGTM
