### PR TITLE
fix: /event-type /apps - doesn't match designs (CALCOM-9180)

### LINKED ISSUE #9180: [CAL-1813] /event-type /apps - doesn't match designs
Spacing, padding, margins is all over the place.

Check Figma

[Event type / Apps \[active\] - 2. Cal - Live (Figma)](https://www.figma.com/file/xk4HOxtSI82J0F7enMxeak/2.-Cal---Live?type=design&node-id=4876%3A157420&t=sYFxEjRy2rlPuKmG-1)

There are components we should be reusing here.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1813](https://linear.app/calcom/issue/CAL-1813/event-type-apps-doesnt-match-designs)</sub>

### PR DESCRIPTION
**Pull request by gitstart-calcom**
Fixes #9180 

## Demo
https://www.loom.com/share/7f4f0c1f67644983adccc8745ff5f3bc

This PR is to fix the following issues we noticed after [this](https://github.com/calcom/cal.com/pull/9317) PR was merged:
- no description below Available Apps
- Apps available should be Available Apps (lowercase),
- No card type next to the app name
- Install button should be Add
- Some paddings and margins wrong

### CODE REVIEW

File: packages/app-store/fathom/components/EventTypeAppCardInterface.tsx [hunk 1]
```diff
@@ -25,6 +25,7 @@ const EventTypeAppCard: EventTypeAppCardComponent = function EventTypeAppCard({
       }}
       switchChecked={enabled}>
       <TextField
+        className="mb-0 leading-4"
```
Comment (PeerRich) [inline packages/app-store/fathom/components/EventTypeAppCardInterface.tsx:28]: @gitstart-calcom instead of adding this to every single app, can we maybe add this outside of the component so it applies to every app, also future apps?

Comment (gitstart-calcom) [reply packages/app-store/fathom/components/EventTypeAppCardInterface.tsx:28]: Sure, we are working on it 😄

File: apps/web/components/eventtype/EventAppsTab.tsx [hunk 2]
```diff
@@ -106,9 +108,21 @@ export const EventAppsTab = ({ eventType }: { eventType: EventType }) => {
       {!shouldLockDisableProps("apps").disabled && (
         <div className="bg-muted rounded-md p-8">
           {!isLoading && notInstalledApps?.length ? (
-            <h2 className="text-emphasis text-lg font-semibold">{t("available_apps")}</h2>
+            <>
+              <h2 className="text-emphasis mb-2 text-xl font-semibold leading-5 tracking-[0.01em]">
+                {t("available_apps_lower_case")}
+              </h2>
+              <p className="mb-6 text-sm font-normal text-gray-600">
```
Comment (Udit-takkar) [inline apps/web/components/eventtype/EventAppsTab.tsx:115]: you have use color tokens here instead of text-gray-600 because this is how it looks in dark mode

Screenshot 2023-06-19 at 3 08 06 PM

Comment (Udit-takkar) [reply apps/web/components/eventtype/EventAppsTab.tsx:115]: i think text-default would work fine here

File: apps/web/components/eventtype/EventAppsTab.tsx [hunk 3]
```diff
@@ -106,9 +108,21 @@ export const EventAppsTab = ({ eventType }: { eventType: EventType }) => {
...
+                  You have no apps installed. View popular apps below and explore more in our &nbsp;
+                  <Link className="cursor-pointer underline" href="/apps">
+                    App Store
+                  </Link>
+                </Trans>
+              </p>
+            </>
           ) : null}
-          <div className="before:border-0">
+          <div className="bg-default divide-y rounded-md border before:border-0">
```
Comment (Udit-takkar) [inline apps/web/components/eventtype/EventAppsTab.tsx:125]: Screenshot 2023-06-19 at 3 16 16 PM

border color should be same as you see around Qr code app in screenshot

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
Left few comments. rest looks fine

**Comment by gitstart-calcom** [comment]
Hi @Udit-takkar, PR has been updated please take a look

**Review by Udit-takkar — DISMISSED** [review]

**Review by keithwillcode — DISMISSED** [review]
@gitstart-calcom The E2E tests are failing now

**Comment by Udit-takkar** [comment]
@keithwillcode can you check why deployment failed?

**Comment by Jaibles** [comment]
This looks great 👏

**Review by Udit-takkar — APPROVED** [review]
LGTM

**Comment by gitstart-calcom** [comment]
@PeerRich @Jaibles we would love if you take a look here, this PR was approved 😄
