### PR TITLE
fix: videoCallUrl is not saved in metadata after rescheduling

### LINKED ISSUE #7604: After rescheduling a booking with a Zoom meeting attachment, `videoCallUrl` no longer present in API response metadata
### Issue Summary

After rescheduling a booking with a Zoom meeting attachment within the cal.com web interface, `videoCallUrl` no longer present in API response metadata.

### Steps to Reproduce

1. I have an existing booking scheduled in cal.com. 
2. Using the booking API, I'm able to see the `videoCallUrl` within the metadata response of `GET` `https://api.cal.com/v1/bookings/{id}?apiKey={apiKey}`.  Response below:
```
{"attendees": [{"email": "XXX", "locale": "en", "name": "Name", "timeZone": "America/New_York"}], "description": "", "endTime": "2023-03-22T15:30:00.000Z", "eventTypeId": XXXXX, "id": XXXXX, "metadata": {"videoCallUrl": "https://us05web.zoom.us/j/XXXX"}, "startTime": "2023-03-22T15:00:00.000Z", "status": "ACCEPTED", "title": "XXX", "uid": "XXX", "user": {"email": "XXX", "locale": null, "name": "XXX", "timeZone": "Etc/GMT"}, "userId": XXX}
```
3. I rescheduled the booking for a different date and time within the web interface at `https://app.cal.com/<username>/appointment?rescheduleUid=<uid>`.
4. I made the same `GET` request as in step 2, but now `videoCallUrl` no longer present in API response metadata. Response below:
```
{"attendees": [{"email": "XXX", "locale": "en", "name": "Name", "timeZone": "America/New_York"}], "description": "", "endTime": "2023-03-23T14:30:00.000Z", "eventTypeId": XXXXX, "id": XXXXX, "metadata": {}, "startTime": "2023-03-23T14:00:00.000Z", "status": "ACCEPTED", "title": "XXX", "uid": "XXX", "user": {"email": "XXX", "locale": null, "name": "XXX", "timeZone": "Etc/GMT"}, "userId": XXX}
```
### Technical details

- Cal.com API Version: v1
- In the reschedule confirmation email, I was able to access the updated `videoCallUrl`. However, it is not present in the API response.

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

Fixes #7604 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 1]
```diff
@@ -1669,7 +1669,10 @@ async function handler(
           metadata.conferenceData = updatedEvent.conferenceData;
           metadata.entryPoints = updatedEvent.entryPoints;
           handleAppsStatus(results, booking);
-          videoCallUrl = metadata.hangoutLink || videoCallUrl;
+          // @ts-expect-error - safe to ignore the below error as we are parsing the data with zod
+          const parseUpdatedEventUrl = z.string().safeParse(updatedEvent?.url);
```
Comment (hariombalhara) [inline packages/features/bookings/lib/handleNewBooking.ts:1673]: I don't think we need to use zod here as it's just a string. Instead, we need to fix the type for `updatedEvent` to include url in it.

**Review by hariombalhara — CHANGES_REQUESTED** [review]
Left comments

**Review by hariombalhara — APPROVED** [review]

**Review by hariombalhara — CHANGES_REQUESTED** [review]
Type checks are failing

**Review by hariombalhara — APPROVED** [review]
