### PR TITLE
fix: email update bug

### LINKED ISSUE #9961: Public page link doesn't update when user changes the username
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Suppose a user creates a Cal account and changes the username during onboarding. After onboarding, the public page link shown in the bottom left corner does not update with the new username.

### Steps to Reproduce

1. Created a new account on Cal.com
2. During onboarding, in step-1, updated the username from default one to some custom one
3. Finished onboarding, and checked the bottom-left corner for my Cal public page link
4. The public page link contains the default username instead of custom one, clicking on which takes to a non-existent page.
5. On replacing the username in the link, the correct page is visible.

The public page link in UI should already get updated with the new custom username.
Since the correct link actually works, the only bug to fix is to display the correct link.

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/). - Microsoft Edge Version 114.0.1823.67 (Official build) (64-bit)
- Node.js version
- Anything else that you think could be an issue.

### LINKED ISSUE #10155: Changing email address leads to weird behaviour
### Issue Summary

After changing your email address, you're not able to access anything in Cal dashboard, and everything sort of glitches out.

### Steps to Reproduce

1. Go to My account -> Profile
2. Change your email address to something else
3. Enter the password when prompted, and then submit
4. Refresh the page

### Actual Results

- You're unable to access any section of the dashboard, and everything errors out with "Something went wrong" with no clear indication as to what went wrong, and probable ways of fixing it.
- There's a "Verify your email address" banner on the top of the screen, but clicking on the "Resend email" link only results in a TRPC Unauthorized error.
- There is no email verification mail sent to the new address, and yet I was able to login with my new email address just fine without verification (even new booking emails are being sent to the new email).

This leads to confusion for the user, as it was for me.

### Expected Results

- After changing the email, it'd be a good idea to redirect the user to login.
- New emails should be verified before old ones are invalidated.
- The "Resend email" should send a verification email. Either require verification or don't show the link?

### Technical details

  - Browser version: Version 1.52.126 Chromium: 114.0.5735.133 (Official Build)  (64-bit)
  - Screen recording, console logs, network requests:

https://github.com/calcom/cal.com/assets/38887390/e9413341-e02f-4a6d-853c-04783d86e5fe

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/10155
Fixes https://github.com/calcom/cal.com/issues/9961

- Added https://next-auth.js.org/getting-started/client#updating-the-session to update the email and other profile in the user session. Now user won't be required to re login even when email has been updated

- set user.emailVerified to null when email is update from /settings/my-account/profile

BEFORE:-

Screenshot 2023-07-23 at 1 11 11 AM

AFTER:-
Screenshot 2023-07-23 at 1 08 36 AM

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: apps/web/components/ui/UsernameAvailability/PremiumTextfield.tsx [hunk 1]
```diff
@@ -96,7 +96,7 @@ const PremiumTextfield = (props: ICustomUsernameProps) => {
   const updateUsername = trpc.viewer.updateProfile.useMutation({
     onSuccess: async () => {
       onSuccessMutation && (await onSuccessMutation());
-      await update();
+      await update({ username: inputUsernameValue });
```
Comment (Udit-takkar) [inline apps/web/components/ui/UsernameAvailability/PremiumTextfield.tsx:99]: the update did not pass the new username value to update the session ( https://github.com/calcom/cal.com/pull/10019 )

File: packages/features/auth/lib/next-auth-options.ts [hunk 2]
```diff
@@ -350,6 +350,14 @@ export const AUTH_OPTIONS: AuthOptions = {
...
   callbacks: {
     async jwt({ token, user, account, trigger, session }) {
+      if (trigger === "update") {
+        return {
+          ...token,
+          name: session?.name ?? token.name,
+          username: session?.username ?? token.username,
+          email: session?.email ?? token.email,
+        };
+      }
```
Comment (Udit-takkar) [inline packages/features/auth/lib/next-auth-options.ts:360]: when update() is called. session contains the object passed to update function

**Review by sean-brydon — APPROVED** [review]
LGTM :) Nice work - i didnt even know next-auth had an update trigger :P
