### PR TITLE
fix: not able to click start recording button when transcription enabled

### LINKED ISSUE #15242: [CAL-3822] Not able to click stop recording
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

Screenshot 2024-05-29 at 4 26 53 PM

### Actual Results

<sub>[CAL-3822](https://linear.app/calcom/issue/CAL-3822/not-able-to-click-stop-recording)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

- Fixes https://github.com/calcom/cal.com/issues/15242
- Fixes CAL-3822 (Linear issue number - should be visible at the bottom of the GitHub issue description)

BEFORE:- 

Transcription text was overlapping with recording buttons.

Screenshot 2024-05-29 at 4 56 19 PM

AFTER:-

Screenshot 2024-05-29 at 5 34 06 PM

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [x] NA I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [x] NA I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

### CODE REVIEW

File: packages/lib/constants.ts [hunk 1]
```diff
@@ -157,3 +157,11 @@ export const ORG_MINIMUM_PUBLISHED_TEAMS_SELF_SERVE = 2;
...
  */
 export const ROLLING_WINDOW_PERIOD_MAX_DAYS_TO_CHECK = 30 + 31;
+
+export const TRANSCRIPTION_STARTED_ICON = IS_PRODUCTION
+  ? `${WEBAPP_URL}/sparkles-red.svg`
+  : `https://app.cal.com/sparkles-red.svg`;
+
+export const TRANSCRIPTION_STOPPED_ICON = IS_PRODUCTION
+  ? `${WEBAPP_URL}/sparkles.svg`
+  : `https://app.cal.com/sparkles.svg`;
```
Comment (Udit-takkar) [inline packages/lib/constants.ts:167]: Not related to bug but just to load icons locally. (we can only pass https url so localhost url won't work locally)

File: apps/web/modules/videos/views/videos-single-view.tsx [hunk 2]
```diff
@@ -87,7 +88,7 @@ export default function JoinCall(props: PageProps) {
         <meta property="twitter:description" content={t("quick_video_meeting")} />
       </Head>
       <DailyProvider callObject={daily}>
-        <div className="mx-auto" style={{ zIndex: 2, position: "absolute", bottom: 60, width: "100%" }}>
+        <div className="mx-auto" style={{ zIndex: 2, position: "absolute", bottom: 100, width: "100%" }}>
```
Comment (Udit-takkar) [inline apps/web/modules/videos/views/videos-single-view.tsx:91]: moved the transcription text

**Review by PeerRich — APPROVED** [review]
