### PR TITLE
fix: Form Builder Name Field Shows Default Label When Custom Label is Empty

### LINKED ISSUE #24200: Name Field Shows Raw Identifier Instead of Default Label When Custom Label is Empty
Found a bug? Please fill out the sections below. 👍

## Issue Summary

In the Event Types form builder, when creating custom questions, the "name" field does not show a proper fallback label when the custom label is removed or empty. Instead of showing "Name" as the default label (like the email field shows "Email address"), it either shows an empty label or the raw field identifier (e.g., "your_name").

This creates inconsistent UX compared to other system fields like email, which properly fall back to their translated default labels when no custom label is set.

## Steps to Reproduce

1. Navigate to Event Types and create or edit an event type
2. Go to the "Advanced" tab or form builder section
3. Locate the existing "Name" question field in the form builder
4. Clear the "Label" field value completely (make it empty or just whitespace)
5. Observe that the field label becomes empty or shows the raw identifier instead of "Name"
6. For comparison, check the "Email" field behavior - it shows "Email address" even when label is empty

## Actual Results

- When the custom label for the name field is removed/empty, the field shows no label or shows the raw field identifier (like "your_name")
- The form builder UI becomes confusing as users cannot identify what the field is for
- Inconsistent behavior compared to other system fields like email

## Expected Results

- When the custom label for the name field is empty, it should fall back to showing "Name" (translated) as the default label
- This should match the behavior of the email field, which correctly shows "Email address" when its label is empty
- Consistent UX across all system fields in the form builder

### PR DESCRIPTION
**Pull request by kartik-212004**
## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/24200
Fixes [CAL-6498](https://linear.app/calcom/issue/CAL-6498/name-field-shows-raw-identifier-instead-of-default-label-when-custom)

- Fixes form builder name field showing raw identifier instead of default label when custom label is empty
- Ensures consistent UX across all system fields in the form builder
- Updates `FieldLabel` component to properly handle empty or meaningless labels

**Problem**: In the Event Types form builder, when the custom label for the "name" field is removed or empty, it shows no label or the raw field identifier (like "your_name") instead of falling back to "Name" like the email field correctly shows "Email address".

**Solution**: Updated the `FieldLabel` component to check if a label is meaningful (not empty and not the same as the field name) before using it, otherwise fall back to the translated default label.

## Visual Demo (For contributors especially)
Before:

https://github.com/user-attachments/assets/f226ad2e-a576-4e3a-8e47-01ef5a6e9769

After:

https://github.com/user-attachments/assets/f359900c-bc68-44e5-913e-826302305b2a

#### Image Demo:

**Before**:
- Name field with empty label shows nothing
- Inconsistent behavior compared to email field

**After**:
- Name field with empty label shows "Name" 
- Consistent behavior across all system fields
- Better UX for form builders

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write **N/A** here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## Steps to Reproduce

1. Navigate to Event Types and create or edit an event type
2. Go to the "Advanced" tab or form builder section
3. Locate the existing "Name" question field in the form builder
4. Clear the "Label" field value completely
5. Observe that the field label now shows Name when no label is there
6. For comparison, check the "Email" field behavior - it shows "Email address" even when label is empty

---

<a href="https://app.devin.ai/review/calcom/cal.com/pull/24201" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

File: packages/features/form-builder/FormBuilder.tsx [hunk 1]
```diff
@@ -698,7 +697,7 @@ function FieldEditDialog({
                       />
                     ) : null}
 
-                    {!!fieldType?.supportsLengthCheck ? (
+                    {fieldType?.supportsLengthCheck ? (
```
Comment (pallava-joshi) [inline packages/features/form-builder/FormBuilder.tsx:712]: keep the !!

File: apps/web/modules/event-types/components/tabs/advanced/FormBuilder.tsx [hunk 2]
```diff
@@ -900,6 +898,15 @@ function FieldLabel({ field }: { field: RhfFormField }) {
   }
   const label =
     variantsConfigVariants?.[variant as keyof typeof fieldTypeConfigVariants]?.fields?.[0]?.label || "";
+
```
Comment (pallava-joshi) [inline apps/web/modules/event-types/components/tabs/advanced/FormBuilder.tsx]: remove comments

**Review by pallava-joshi — COMMENTED** [review]
left suggestions

File: apps/web/modules/event-types/components/tabs/advanced/FormBuilder.tsx (hunk 2 above)
Comment (kartik-212004) [reply apps/web/modules/event-types/components/tabs/advanced/FormBuilder.tsx]: > remove comments

removed comments and resolved all suggestions.

**Review by pallava-joshi — DISMISSED** [review]
tested locally, working fine.

File: packages/features/form-builder/FormBuilder.tsx [hunk 3]
```diff
@@ -900,6 +898,14 @@ function FieldLabel({ field }: { field: RhfFormField }) {
   }
   const label =
     variantsConfigVariants?.[variant as keyof typeof fieldTypeConfigVariants]?.fields?.[0]?.label || "";
+
+  if (!label) {
+    const fieldName =
+      variantsConfigVariants?.[variant as keyof typeof fieldTypeConfigVariants]?.fields?.[0]?.name;
+    const defaultLabel = fieldTypeConfigVariants?.[variant]?.fieldsMap?.[fieldName as string]?.defaultLabel;
+    return <span>{t(defaultLabel || field.defaultLabel || "")}</span>;
```
Comment (anikdhabal) [inline packages/features/form-builder/FormBuilder.tsx]: I think we shouldn't allow the label to be empty in any condition

**Review by anikdhabal — DISMISSED** [review]

File: packages/features/form-builder/FormBuilder.tsx (hunk 3 above)
Comment (kartik-212004) [reply packages/features/form-builder/FormBuilder.tsx]: > I think we shouldn't allow the label to be empty in any condition

Sure, I will update it so the label can’t be empty.

**Comment by kartik-212004** [comment]
@anikdhabal, could you review this when you get a chance?

**Review by pallava-joshi — DISMISSED** [review]
your fix is a good thing to have, but as anik suggested:
- you need to add normalization when form fields are saved, converting empty strings to undefined or the default label value.

although, you could implement this in the UI layer too, but I'm not a very big fan of that:
-  when the user clears the label field, automatically restore it to the default label instead of saving an empty string

**Comment by pallava-joshi** [comment]
and we have a cubic suggestion too.

**Comment by kartik-212004** [comment]
> and we have a cubic suggestion too.

fixed the addressed issues

**Review by sahitya-chandra — DISMISSED** [review]

**Review by sahitya-chandra — APPROVED** [review]
