### PR TITLE
fix: teams are listed on insights but then you cant find them on settings page 11087 cal 2401

### LINKED ISSUE #11087: [CAL-2401] Teams are listed on insights but then you can't find them on settings page.
In an org enviroment this happened recently. Let's figure out where they should be listed on the settings page.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2401](https://linear.app/calcom/issue/CAL-2401/teams-are-listed-on-insights-but-then-you-cant-find-them-on-settings)</sub>

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

- Changes prisma query to fetch teams where membership relationship doesn't exist.
- Add invalidates for trpc when adding new members to other teams.

Fixes #11087 

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Are there environment variables that should be set? Orgs should be activated.
- What are the minimal test data to have? An org with 2 team members, 1 team with owner membership, other with no members and you should be logged in as owner of org.
- What is expected (happy path) to have (input and output)? Go to /settings/organizations/teams and you should have 1 team listed on My Teams and other team listed on Other teams.
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/features/ee/organizations/pages/components/OtherTeamList.tsx [hunk 1]
```diff
@@ -15,8 +14,6 @@ interface Props {
 export default function OtherTeamList(props: Props) {
   const utils = trpc.useContext();
 
-  const { t } = useLocale();
```
Comment (alannnc) [inline packages/features/ee/organizations/pages/components/OtherTeamList.tsx:18]: Both of these were not being used.

File: packages/features/ee/organizations/pages/components/OtherTeamListItem.tsx [hunk 2]
```diff
@@ -38,7 +37,7 @@ export default function OtherTeamListItem(props: Props) {
 
   const orgBranding = useOrgBranding();
 
-  const isOwner = props.team.role === MembershipRole.OWNER;
+  const isOwner = true; // Based on trpc auth procedures this endpoint is only accessible to org owners|admins
```
Comment (alannnc) [inline packages/features/ee/organizations/pages/components/OtherTeamListItem.tsx:40]: Probably I should remove this flag and then it's implementation as it no longer be conditional.

File: packages/features/ee/organizations/pages/settings/other-team-members-view.tsx [hunk 3]
```diff
@@ -38,6 +38,11 @@ function MembersList(props: MembersListProps) {
           })}
         </ul>
       ) : null}
+      {members?.length === 0 && (
+        <div className="flex flex-col items-center justify-center">
+          <p className="text-default text-sm font-bold">{t("no_members_found")}</p>
+        </div>
```
Comment (alannnc) [inline packages/features/ee/organizations/pages/settings/other-team-members-view.tsx:44]: Added message when no team members found.

File: packages/features/ee/organizations/pages/settings/other-team-members-view.tsx [hunk 4]
```diff
@@ -107,7 +112,13 @@ const MembersView = () => {
 
   const isLoading = isTeamLoading || isLoadingMembers || isOrgListLoading;
 
-  const inviteMemberMutation = trpc.viewer.teams.inviteMember.useMutation();
+  const inviteMemberMutation = trpc.viewer.teams.inviteMember.useMutation({
+    onSuccess: () => {
+      utils.viewer.organizations.listOtherTeams.invalidate();
+      utils.viewer.teams.list.invalidate();
+      utils.viewer.organizations.listOtherTeamMembers.invalidate();
```
Comment (alannnc) [inline packages/features/ee/organizations/pages/settings/other-team-members-view.tsx:119]: Invalidation so data behave accordingly.

File: packages/trpc/server/routers/viewer/organizations/listOtherTeams.handler.ts [hunk 5]
```diff
@@ -9,38 +9,20 @@ type ListOptions = {
 };
 
 export const listOtherTeamHandler = async ({ ctx }: ListOptions) => {
-  const teamsInOrgIamNotPartOf = await prisma.membership.findMany({
+  const teamsInOrgIamNotPartOf = await prisma.team.findMany({
     where: {
-      userId: {
-        not: ctx.user.id,
+      parent: {
+        id: ctx.user?.organization?.id,
```
Comment (alannnc) [inline packages/trpc/server/routers/viewer/organizations/listOtherTeams.handler.ts:15]: Here is the main issue I was looking first on memberships but when a team doesn't have memberships it wasn't listed.

File: packages/trpc/server/routers/viewer/organizations/listOtherTeams.handler.ts [hunk 6]
```diff
@@ -9,38 +9,20 @@ type ListOptions = {
...
-    distinct: ["teamId"],
   });
 
-  return teamsInOrgIamNotPartOf.map(({ team, ...membership }) => ({
-    role: membership.role,
-    accepted: membership.accepted,
-    userId: membership.userId,
-    isOrgAdmin: true,
-    ...team,
-  }));
```
Comment (alannnc) [inline packages/trpc/server/routers/viewer/organizations/listOtherTeams.handler.ts:43]: No longer required object manipulation.

File: packages/features/ee/organizations/pages/components/OtherTeamListItem.tsx (hunk 2 above)
Comment (leog) [reply packages/features/ee/organizations/pages/components/OtherTeamListItem.tsx:40]: I agree, it would simplify the code as well

**Review by leog — DISMISSED** [review]
Works great, just a nit agreeing on simplifying the code when possible 👍

File: packages/features/ee/organizations/pages/components/OtherTeamListItem.tsx (hunk 2 above)
Comment (hariombalhara) [reply packages/features/ee/organizations/pages/components/OtherTeamListItem.tsx:40]: Some observations:
- I think we should prefix `listOtherTeamMembers` with admin to make it very obvious. 
- `OtherTeamListItem` isn't aware how the data is fetched, so, we shouldn't take decision based on that here. Might be better to still keep `isOwner` flag so that the component can be reused for both Admin and Non admin members if needed.

File: packages/trpc/server/routers/viewer/organizations/listOtherTeams.handler.ts (hunk 5 above)
Comment (hariombalhara) [reply packages/trpc/server/routers/viewer/organizations/listOtherTeams.handler.ts:15]: Shouldn't a team always have atleast it's creator as the member?

File: packages/features/settings/layouts/SettingsLayout.tsx [hunk 7]
```diff
@@ -520,23 +520,9 @@ const SettingsSidebarContainer = ({
                                     alt={otherTeam.name || "Team logo"}
                                   />
                                   <p className="w-1/2 truncate">{otherTeam.name}</p>
-                                  {!otherTeam.accepted && otherTeam.userId === session.data?.user.id && (
```
Comment (hariombalhara) [inline packages/features/settings/layouts/SettingsLayout.tsx:523]: Don't we need to show this now?

**Review by hariombalhara — CHANGES_REQUESTED** [review]
Need confirmation on the reasoning behind the change https://github.com/calcom/cal.com/pull/11092/files#r1314477139
Otherwise looks good, Nice catch @alannnc

File: packages/features/settings/layouts/SettingsLayout.tsx (hunk 7 above)
Comment (alannnc) [reply packages/features/settings/layouts/SettingsLayout.tsx:523]: The thing is if you are invited to "other team" it will no longer appear on your Other team list.

File: packages/features/ee/organizations/pages/components/OtherTeamListItem.tsx (hunk 2 above)
Comment (alannnc) [reply packages/features/ee/organizations/pages/components/OtherTeamListItem.tsx]: Agree on rename listOtherTeamMembers, good call. Will address it on follow up PR.
About keeping isOwner flag: being owner of an other team listing will never happen as it then will be listed on your normal team list and then the component won't be required because if admin|owner of that team it will not be on other team list.

**Review by hariombalhara — APPROVED** [review]
