### PR TITLE
fix: Banner uploader fix error handling and reduce image size jump

### LINKED ISSUE #21895: Fix error message when saving new uploaded image
When updating the logo or banner image for an organization (/settings/organizations/profile), it throws a raw error if the file is too big. Show 'File too large' instead. Also ensure this is fixed in all other image upload places.

### LINKED ISSUE #21896: Improve image uploader
Uploading images causes issues with the size limit being reached.

### PR DESCRIPTION
**Pull request by alishaz-polymath**
## What does this PR do?

Adds support for JPEG images in base64 conversion, leading to better adjusted images. Earlier we were forcing base64 png even on jpeg uploads where it would result in a jump of even 30 times in size, in complex images.

- Fixes #21896  (GitHub issue number)
- Fixes https://github.com/calcom/cal.com/issues/21895
- Fixes CAL-5955 (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Visual Demo (For contributors especially)

A visual demonstration is strongly recommended, for both the original and new change **(video / image - any one)**.

#### Video Demo (if applicable):

- Show screen recordings of the issue or feature.
- Demonstrate how to reproduce the issue, the behavior before and after the change.

#### Image Demo (if applicable):

- Add side-by-side screenshots of the original and updated change.
- Highlight any significant change(s).

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

    

---

## Summary by cubic
Improved the banner image uploader to support JPEG images, reduce large file size jumps, and show clearer error messages when uploads fail.

- **Bug Fixes**
  - Preserves original image format (JPEG or PNG) during upload to prevent unnecessary file size increases.
  - Adds better error handling and user feedback for oversized images.

### CODE REVIEW

File: packages/features/ee/organizations/pages/settings/profile.tsx [hunk 1]
```diff
@@ -183,6 +183,11 @@ const OrgProfileForm = ({ defaultValues }: { defaultValues: FormValues }) => {
 
   const mutation = trpc.viewer.organizations.update.useMutation({
     onError: (err) => {
+      // Handle JSON parsing errors from body size limit exceeded
+      if (err.message.includes("Unexpected token") && err.message.includes("Body excee")) {
```
Comment (alishaz-polymath) [inline packages/features/ee/organizations/pages/settings/profile.tsx:187]: The unhandled error is: "Unexpected token 'B', "Body excee"... is not valid JSON"
So this takes care of that.

File: packages/ui/components/image-uploader/BannerUploader.tsx [hunk 2]
```diff
@@ -224,5 +230,6 @@ async function getCroppedImg(
     canvas.height
   );
 
-  return canvas.toDataURL("image/png");
+  // Use original format with quality setting for JPEG
+  return canvas.toDataURL(originalFormat, originalFormat === "image/jpeg" ? 0.6 : undefined);
```
Comment (alishaz-polymath) [inline packages/ui/components/image-uploader/BannerUploader.tsx:234]: We don't force convert to png, which was the primary cause for the crazy size jump.

**Review by anikdhabal — APPROVED** [review]
Looks Good

**Comment by heykandoi** [comment]
I may be wrong here, but doesn't this limit the image size to just 1mb?

**Comment by alishaz-polymath** [comment]
> I may be wrong here, but doesn't this limit the image size to just 1mb?

No, that part never changed. We've always had that limit, but here's what is happening behind the scenes:
1. A user uploads an image, the limit of the image selected by the user in terms of size there is 5mb. 
2. The uploaded image is then cropped (during upload) and encoded into base64. It automatically reduces in size considerably here now.
3. When we proceed with the mutation (click save), there the limit is 1mb and with these code changes, that should almost always satisfy.

**Comment by heykandoi** [comment]
> > I may be wrong here, but doesn't this limit the image size to just 1mb?
> 
> No, that part never changed. We've always had that limit, but here's what is happening behind the scenes:
> 
> 1. A user uploads an image, the limit of the image selected by the user in terms of size there is 5mb.
> 2. The uploaded image is then cropped (during upload) and encoded into base64. It automatically reduces in size considerably here now.
> 3. When we proceed with the mutation (click save), there the limit is 1mb and with these code changes, that should almost always satisfy.

Does this mean I can upload a 4.5mb PNG file without any issue? Does it get converted to JPEG?

**Review by emrysal — APPROVED** [review]
nice improvement

**Comment by alishaz-polymath** [comment]
> > > I may be wrong here, but doesn't this limit the image size to just 1mb?
> > 
> > 
> > No, that part never changed. We've always had that limit, but here's what is happening behind the scenes:
> > 
> > 1. A user uploads an image, the limit of the image selected by the user in terms of size there is 5mb.
> > 2. The uploaded image is then cropped (during upload) and encoded into base64. It automatically reduces in size considerably here now.
> > 3. When we proceed with the mutation (click save), there the limit is 1mb and with these code changes, that should almost always satisfy.
> 
> Does this mean I can upload a 4.5mb PNG file without any issue? Does it get converted to JPEG?

PNG will not be converted into JPEG. But it would still be compressed enough when cropping. So it would be worth a try 😅 
I'd recommend using JPEG though.

**Review by pumfleet — APPROVED** [review]
