### PR TITLE
fix: selectfield bug and min height

### LINKED ISSUE #8252: [CAL-1485] Custom styling to Select Field
### Issue Summary

Not able to override style of SelectField component like 

 classNames={{
              menuList: () => "h-25",
}}

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

<sub>[CAL-1485](https://linear.app/calcom/issue/CAL-1485/custom-styling-to-select-field)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/8252, add minimum height to select
Follow up of https://github.com/calcom/cal.com/pull/7734

@Jaibles suggested to not display scroll bar inside dropdown and display all options all at once ( https://threads.com/34455749521?s=9nKsam7Qo9LfMJrL8JrYmU )

Screenshot 2023-04-14 at 12 03 22 AM

**Environment**: Staging(main branch) / Production

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Chore (refactoring code, technical debt, workflow improvements)

### CODE REVIEW

File: packages/ui/components/form/select/Select.tsx [hunk 1]
```diff
@@ -62,33 +62,33 @@ export const Select = <
...
               ? state.isMulti
                 ? "[&>*:last-child]:rotate-180 [&>*:last-child]:transition-transform"
                 : "rotate-180 transition-transform"
               : "text-default" // Woo it adds another SVG here on multi for some reason
           ),
         multiValueRemove: () => "text-default py-auto ml-2",
-        ...props.classNames,
+        ...classNames,
       }}
-      {...props}
```
Comment (Udit-takkar) [inline packages/ui/components/form/select/Select.tsx:91]: passing classNames to props overrides all styles of classNames above even if wanted to override only one component.

**Review by zomars — APPROVED** [review]
LGTM
