### PR TITLE
fix: use `userPhone` instead of `phone` for switch case

### LINKED ISSUE #16382: (bug) Atoms Booker component does not hide phone number
### Issue Summary

When setting the `locations` to the following for an event type:
```
locations: [
  {
    type: "phone",
    phone: "+32 477777777", // will be the attendee phone number in the email links
    public: false,
  },
  {
    type: "link",
    link: "https://www.website.com", // will be the link to the video meeting in the emails
    public: false,
  },
],
```

One would expect that both fields in the `Booker` component would be hidden, and use the respective translations for the labels `Phone number` and `Link meeting`. You can see the response from the endpoint: `https://api.cal.com/v2/organizations/ORG/teams/TEAM/event-types/EVT` PATCH:

image

However on the Booker atom when providing the event type slug as options, we can see the only the `link` type location is correctly hidden:
image

**Note**: this does not happen on the Cal.com platform, only in the Atoms React component library.

### Steps to Reproduce

1. Create a team event type with the API (or on the platform via the UI) and use the following inputs:
```
lengthInMinutes: 30,
title: "Introduction meeting",
description: agencySlug,
schedulingType: "ROUND_ROBIN",
locations: [
  {
    type: "phone",
    phone: "+32 477777777",
    public: false,
  },
  {
    type: "link",
    link: "https://www.website.com",
    public: false,
  },
],
hosts: [],
assignAllTeamMembers: true,
slug: "intro_30_mins",
```

2. Use the `Booker` component in your app with the standard configuration, and these props:
```
<Booker
    entity={{
      considerUnpublished: false,
      teamSlug: agencySlug,
      name: agencySlug,
      orgSlug: null,
    }}
    eventSlug="intro_30_mins"
    username={agencySlug}
    isTeamEvent={true}
    teamId={teamId}
  />
```

### Expected behavior

See that the phone number is not hidden, even though the data from the api is correct:
image

The value for `hostPhoneNumber` should be empty string as per the information below: 👇 

### Other information

It looks like there might be an issue converting the location values here:
https://github.com/calcom/cal.com/blob/3c5ab5e8d24836311f913c358245d8b99dd63707/packages/lib/event-types/transformers/api-request.ts#L39-L44

However from the code the logic seems valid.

We're using the latest version of @calcom/atoms, "1.0.59"

### Screenshots

_No response_

### Environment

- [X] app.cal.com
- [ ] Self-hosted Cal

### Desktop (please complete the following information)

```markdown
- OS:Mac OS
- Node:20
- npm: 9.8.1
```

### PR DESCRIPTION
**Pull request by nicmosc**
Currently this switch case never gets to the last case ("phone") as the type expected is wrong.

Here the type may have value `userPhone` and not `phone`.

## What does this PR do?

The existing case to hide the location based on the `displayLocationPublicly` field and `type` never hid the phone number as the type expected was wrong. Instead of checking for `phone` it should have checked for `userPhone`

See issue below for context:

- Fixes #16382

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

### CODE REVIEW

File: packages/platform/atoms/event-types/atom-api-transformers/transformApiEventTypeForAtom.ts [hunk 1]
```diff
@@ -194,7 +194,7 @@ function getLocations(locations: EventTypeOutput_2024_06_14["locations"]) {
         return displayLocationPublicly ? location : { ...location, address: "" };
       case "link":
         return displayLocationPublicly ? location : { ...location, link: "" };
-      case "phone":
+      case "userPhone":
```
Comment (anikdhabal) [inline packages/platform/atoms/event-types/atom-api-transformers/transformApiEventTypeForAtom.ts:197]: Good observation. That's correct. I think the `case "address"` is also wrong; it should be `case "inPerson"`

**Review by anikdhabal — APPROVED** [review]
LGTM!
