### PR TITLE
fix: Empty spaces in text field do not trigger inline field error

### LINKED ISSUE #10028: Empty Spaces in Text Field Do Not Trigger Inline Field Error
Found a bug? Please fill out the sections below. 👍

### Issue Summary
I would like to report an issue regarding the behavior of a text field in my application. When I input empty spaces into the Your name field and submit, no inline field error is displayed to notify the user of the invalid input.
### Steps to Reproduce

1. Schedule any meeting
2. Give empty spaces in your name section 

### Screenshot
image
image

### PR DESCRIPTION
**Pull request by greatmaxy**
## What does this PR do?

Fixes - empty spaces in text field do not trigger inline field error

Fixes #10028

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Schedule any meeting
- Give empty spaces in your name section
- "Invalid input" error is displayed

## Mandatory Tasks

- [X] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: packages/prisma/zod-utils.ts [hunk 1]
```diff
@@ -113,7 +113,9 @@ export type BookingFieldType = typeof BookingFieldType extends z.Values<infer T>
 export const bookingResponses = z
   .object({
     email: z.string(),
-    name: z.string(),
+    name: z.string().refine((value : String) => value.trim().length > 0, {
+      message: "Name is required",
```
Comment (CarinaWolli) [inline packages/prisma/zod-utils.ts:117]: I don't think we need the message. It's not showing anywhere and 'Invalid Input' is fine as the error message 👍

Comment (greatmaxy) [reply packages/prisma/zod-utils.ts]: Thank You Carina. I have updated the same.

**Review by CarinaWolli — APPROVED** [review]
Looks good, thank your contribution 🙏
