### PR TITLE
fix: multiple duration getSchedule calls [CAL-2336]

### LINKED ISSUE #10707: [CAL-2336] getSchedule call fires twice
Found a bug? Please fill out the sections below. 👍

As getSchedule is our most resource intensive call we need to fix this urgently.

Additional context: seems to only happen on events with multiple durations

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2336](https://linear.app/calcom/issue/CAL-2336/getschedule-call-fires-twice)</sub>

### PR DESCRIPTION
**Pull request by leog**
## What does this PR do?

Due to the nature of multiple duration and recent changes that aimed to call as fast as possible the `getSchedule` result to populate the available slots, that call was made multiple times, first with an undefined duration and then the selected one.

Now we preemptively get the duration from query param if present, check if it's a possibility within the given event type options and return a valid duration if the event type has multiple duration configuration, either the query parameter value or the default duration if not valid. That duration is then passed down to the `getSchedule` call to effectively gain the performance optimization that was expected.

Fixes #10707 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

Go to `/pro/multiple-duration` event type and check in Dev Tools Network tab that `getSchedule` is called once when loading the page. Before this change it was called twice.

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: packages/features/bookings/lib/get-booking.ts [hunk 1]
```diff
@@ -224,3 +224,15 @@ export const getBookingForSeatedEvent = async (uid: string) => {
...
+  multipleDurationConfig: number[] | undefined,
+  queryDuration: string | string[] | undefined,
+  defaultValue: number
+) => {
+  return multipleDurationConfig
+    ? multipleDurationConfig.includes(Number(queryDuration))
+      ? Number(queryDuration)
+      : defaultValue
+    : null;
+};
```
Comment (zomars) [inline packages/features/bookings/lib/get-booking.ts:238]: Legibility nitpick

[Prefer Early Returns](https://handbook.cal.com/engineering/best-practices/prefer-early-returns) 

```suggestion
export const getMultipleDurationValue = (
  multipleDurationConfig: number[] | undefined,
  queryDuration: string | string[] | undefined,
  defaultValue: number
) => {
  if (!multipleDurationConfig) return null;
  if (multipleDurationConfig.includes(Number(queryDuration))) return Number(queryDuration);
  return defaultValue;
};
```

**Review by zomars — DISMISSED** [review]

**Review by zomars — APPROVED** [review]
