### PR TITLE
[CAL-1644] Fix delete icon background color in availability

### LINKED ISSUE #8807: Delete icon background color
Found a bug? Please fill out the sections below. 👍

### Issue Summary

on hovering

Screenshot 2023-05-10 at 2 53 27 PM

Expected

Screenshot 2023-05-10 at 2 54 29 PM

### Steps to Reproduce

1. Go to https://app.cal.com/availability
2. Open any availability

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### PR DESCRIPTION
**Pull request by asadath1395**
## What does this PR do?

[CAL-1644] Fix delete icon background color in availability

Fixes #8807 

Light Theme

https://github.com/calcom/cal.com/assets/37188392/19a62ff2-5292-4b7a-8787-3a83a050c78a

Dark theme

https://github.com/calcom/cal.com/assets/37188392/c8ef73ea-176f-4d0c-9c15-ba5920a47c30

**Environment**: Staging(main branch) / Production

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Navigate to `/availability`
- Click on any availability
- Add new time slot
- Then hover over the delete icon

## Checklist

- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Udit-takkar — APPROVED** [review]
@asadath1395 LGTM. Thanks for your contribution

File: packages/features/schedules/components/Schedule.tsx [hunk 1]
```diff
@@ -197,7 +197,7 @@ export const DayRanges = <TFieldValues extends FieldValues>({
                 }}
               />
             )}
-            {index !== 0 && <RemoveTimeButton index={index} remove={remove} className="text-default mx-2" />}
+            {index !== 0 && <RemoveTimeButton index={index} remove={remove} className="text-default mx-2 border-none" />}
```
Comment (hariombalhara) [inline packages/features/schedules/components/Schedule.tsx:200]: Border width seems to be 0, so I don't think it matters.

**Review by hariombalhara — APPROVED** [review]
LGTM
