### PR TITLE
fix: webhooks for events with seats

### LINKED ISSUE #7950: [CAL-1343] Webhooks and workflows not always firing with events with seats
I tested the "Booking created" and "Booking cancelled" trigger for webhooks and both are not always firing for events with seats. I think "Booking created" is only firing when the first slot is booked

Same with workflows, "booking created" triggers only when the first seat is booked

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1343](https://linear.app/calcom/issue/CAL-1343/webhooks-and-workflows-not-always-firing-with-events-with-seats)</sub>

### LINKED ISSUE #8644: [CAL-1613] Issues with webhook for multi-seat meetings
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1613](https://linear.app/calcom/issue/CAL-1613/issues-with-webhook-for-multi-seat-meetings)</sub>

### PR DESCRIPTION
**Pull request by CarinaWolli**
## What does this PR do?

Fixes that when an event with seats was booked webhooks didn't trigger.

Fixes #7950
Fixes #8644

## Type of change

  - [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

  1. Create user webhook
  2. Go to [webhook.site](webhook.site)
  3.  Copy URL and paste as the subscriber URL 
  4.  Save webhook 
  5. Create an event with seats
  6. Book a seat => check if the webhook triggered
  8. Cancel seat => check if webhook triggered
  9. Now book two seats in the same slot (make sure you are not logged in as organizer) => check if the second one also triggers
  10. Cancel the second seat => check if it triggers

## Mandatory Tasks

  - [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 1]
```diff
@@ -1135,6 +1135,40 @@ async function handler(
...
+  subscriberOptions.triggerEvent = eventTrigger;
+
+  const subscriberOptionsMeetingEnded = {
+    userId: organizerUser.id,
+    eventTypeId,
+    triggerEvent: WebhookTriggerEvents.MEETING_ENDED,
+    teamId,
+  };
+
+  const subscribersMeetingEnded = await getWebhooks(subscriberOptionsMeetingEnded);
```
Comment (CarinaWolli) [inline packages/features/bookings/lib/handleNewBooking.ts:1170]: This is the same code that code removed below, just moved it up here

File: packages/features/bookings/lib/handleCancelBooking.ts [hunk 2]
```diff
@@ -126,9 +127,25 @@ async function handler(req: CustomRequest) {
...
+  const eventTypeInfo: EventTypeInfo = {
+    eventTitle: bookingToDelete?.eventType?.title || null,
+    eventDescription: bookingToDelete?.eventType?.description || null,
+    requiresConfirmation: bookingToDelete?.eventType?.requiresConfirmation || null,
+    price: bookingToDelete?.eventType?.price || null,
+    currency: bookingToDelete?.eventType?.currency || null,
+    length: bookingToDelete?.eventType?.length || null,
+  };
+
+  const webhooks = await getWebhooks(subscriberOptions);
```
Comment (CarinaWolli) [inline packages/features/bookings/lib/handleCancelBooking.ts:147]: That's the code that got removed below. Brought it up here so I can reuse it for seated events

**Review by alannnc — APPROVED** [review]
Code looks good!
