### PR TITLE
fix: trigger guest no show bug

### LINKED ISSUE #18163: Guest no show was triggered even when guest joined the call
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

https://app.campsite.com/cal/posts/auujgvb9x5ye#comment-xvvpdpqgu5ko

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Expected Results

The 'Guest No Show' webhook should be triggered only when guests either join late or do not join at all.

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

- Fixes https://github.com/calcom/cal.com/issues/18163 (GitHub issue number)
- Fixes CAL-4889 (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

https://github.com/calcom/cal.com/pull/16727#issue-2536552256

### CODE REVIEW

File: packages/features/tasker/tasks/triggerNoShow/common.ts [hunk 1]
```diff
@@ -215,7 +215,7 @@ export const prepareNoShowTrigger = async (
   const numberOfHostsThatJoined = hosts.length - hostsThatDidntJoinTheCall.length;
 
   const didGuestJoinTheCall = meetingDetails.data.some(
-    (meeting) => meeting.max_participants < numberOfHostsThatJoined
+    (meeting) => meeting.max_participants > numberOfHostsThatJoined
```
Comment (Udit-takkar) [inline packages/features/tasker/tasks/triggerNoShow/common.ts:218]: This was the logic that caused the issue.

`max_participants` represents the peak number of concurrent participants in a meeting session and If `max_participants` is greater than numberOfHostsThatJoined, it means there must have been at least one guest present

**Review by CarinaWolli — APPROVED** [review]
