### PR TITLE
fix toast dimensions issues

### LINKED ISSUE #6492: [CAL-793] tooltip too low height when text too long
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-793](https://linear.app/calcom/issue/CAL-793/tooltip-too-low-height-when-text-too-long)</sub>

### PR DESCRIPTION
**Pull request by mocherfaoui**
## What does this PR do?

Fixes #6492

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/ui/components/toast/showToast.tsx [hunk 1]
```diff
@@ -11,43 +11,51 @@ type IToast = {
 export const SuccessToast = ({ message, toastVisible }: IToast) => (
   <div
     className={classNames(
-      "data-testid-toast-success bg-brand-500 mb-2 flex h-9 items-center space-x-2 rounded-md p-3 text-sm font-semibold text-white shadow-md rtl:space-x-reverse",
+      "data-testid-toast-success bg-brand-500 mb-2 flex h-auto items-center space-x-2 rounded-md p-3 text-sm font-semibold text-white shadow-md rtl:space-x-reverse md:max-w-sm",
```
Comment (mocherfaoui) [inline packages/ui/components/toast/showToast.tsx:14]: I used `md:max-w-sm` because there is a case if the toast message is long(like in errors), the toast takes the full with of the viewport by default.

File: packages/ui/components/toast/showToast.tsx [hunk 2]
```diff
@@ -11,43 +11,51 @@ type IToast = {
...
       toastVisible && "animate-fade-in-up"
     )}>
-    <Icon.FiCheck className="h-4 w-4" />
+    <span>
+      <Icon.FiCheck className="h-4 w-4" />
+    </span>
```
Comment (mocherfaoui) [inline packages/ui/components/toast/showToast.tsx:19]: following the `md:max-w-sm` fix, the message pushes the icon. the icon then loses its width. wrapping it in a `span` to preserve its dimensions

**Comment by PeerRich** [comment]
@Udit-takkar can you test and approve?

**Review by Udit-takkar — APPROVED** [review]
LGTM
Screenshot 2023-01-18 at 2 42 14 AM
