### PR TITLE
fix: settings layout for org admin

### LINKED ISSUE #14722: [CAL-3521] [CAL-3520] Settings layout displays multiple "other teams" for org admin
image

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3521](https://linear.app/calcom/issue/CAL-3521/[cal-3520]-settings-layout-displays-multiple-other-teams-for-org-admin)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/14722
Fixes CAL-3520

Before:-
image

After:- 
Screenshot 2024-04-24 at 1 13 16 AM

How to reproduce the bug?
1) Login as org admin and go to settings

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is a UI/UX design document, please, share it here.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/features/settings/layouts/SettingsLayout.tsx [hunk 1]
```diff
@@ -391,17 +398,6 @@ const SettingsSidebarContainer = ({
...
-    const teamsIndex = tabsWithPermissions.findIndex((tab) => tab.name === "teams");
-
-    tabsWithPermissions.splice(teamsIndex + 1, 0, {
-      name: "other_teams",
-      href: "/settings/organizations/teams/other",
-      icon: "users",
-      children: [],
-    });
-  }
-
```
Comment (Udit-takkar) [inline packages/features/settings/layouts/SettingsLayout.tsx:404]: re rendering bug

**Review by PeerRich — APPROVED** [review]
