### PR TITLE
fix: enable block calendar slots by default for required confirmations

### LINKED ISSUE #25238: Enable "Unconfirmed bookings still block calendar slots." by default
Enable the setting "Unconfirmed bookings still block calendar slots." by default. 

This shouldn’t affect existing event types using this setting. Only when enabling “Requires confirmation”, this box should be checked by default.

### PR DESCRIPTION
**Pull request by kartik-212004**
## What does this PR do?

Enables the "Unconfirmed bookings still block calendar slots" checkbox by default when enabling "Requires confirmation" on event types.

- Fixes #25238
- Fixes [CAL-6777](https://linear.app/calcom/issue/CAL-6777/enable-unconfirmed-bookings-still-block-calendar-slots-by-default)

## Visual Demo (For contributors especially)

Before:
Screenshot from 2025-11-18 14-38-45

After:
Screenshot from 2025-11-18 14-38-39

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox. **N/A**
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

1. Create a new event type or edit one without "Requires confirmation" enabled
2. Go to the Advanced tab
3. Enable the "Requires confirmation" toggle
4. Verify that the "Unconfirmed bookings still block calendar slots" checkbox is checked by default

## Checklist

- [x] I have read the contributing guide
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have checked if my changes generate no new warnings

### CODE REVIEW

**Review by dhairyashiil — DISMISSED** [review]
LGTM 👍🏼 , Thank you for the contribution

**Comment by dhairyashiil** [comment]
tested locally, from next time please attach working videos as well 🙏🏼

File: packages/features/eventtypes/components/tabs/advanced/RequiresConfirmationController.tsx [hunk 1]
```diff
@@ -110,11 +109,14 @@ export default function RequiresConfirmationController({
...
               LockedIcon={requiresConfirmationLockedProps.LockedIcon}
               onCheckedChange={(val) => {
+                const wasEnabled = formMethods.getValues("requiresConfirmation");
                 formMethods.setValue("requiresConfirmation", val, { shouldDirty: true });
                 // If we uncheck requires confirmation, we also uncheck these checkboxes
                 if (!val) {
                   formMethods.setValue("requiresConfirmationWillBlockSlot", false, { shouldDirty: true });
                   formMethods.setValue("requiresConfirmationForFreeEmail", false, { shouldDirty: true });
+                } else if (!wasEnabled) {
+                  formMethods.setValue("requiresConfirmationWillBlockSlot", true, { shouldDirty: true });
```
Comment (anikdhabal) [inline packages/features/eventtypes/components/tabs/advanced/RequiresConfirmationController.tsx]: why do we need the else if here? Aren't we make it more simpler? Pls check

**Comment by kartik-212004** [comment]
> tested locally, from next time please attach working videos as well 🙏🏼

Sorry for the inconvenience. I will include the video next time.

**Review by pallava-joshi — APPROVED** [review]
tested locally.

**Review by dhairyashiil — APPROVED** [review]
LGTM 👍🏼 , thank you for the contribution
