### PR TITLE
HotFix: Admin Apps Listing

### LINKED ISSUE #6280: [CAL-684] Admin apps console - broken navigation
A PR was introduced that broke the navigation for the `AdminAppsList` component.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-684](https://linear.app/calcom/issue/CAL-684/admin-apps-console-broken-navigation)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
Fix broken Admin apps listing

Fixes #6280

See loom where it all works now. https://www.loom.com/share/d7e138220a8742f2bf93937f49a5215b

### CODE REVIEW

File: packages/features/apps/AdminAppsList.tsx [hunk 1]
```diff
@@ -187,7 +187,7 @@ const AdminAppsList = ({ baseURL, className }: { baseURL: string; className?: st
       <AppCategoryNavigation
         baseURL={baseURL}
         fromAdmin
-        containerClassname="w-full xl:ml-5 max-h-97 overflow-scroll"
+        containerClassname="w-full xl:mx-5 xl:w-2/3 xl:pr-5"
```
Comment (hariombalhara) [inline packages/features/apps/AdminAppsList.tsx:190]: Reverted to previous values

File: packages/app-store/_utils/getAppCategories.ts [hunk 2]
```diff
@@ -1,10 +1,13 @@
...
 
 function getHref(baseURL: string, category: string, useQueryParam: boolean) {
-  return useQueryParam ? `${baseURL}&category=${category}` : `${baseURL}/${category}`;
+  const baseUrlParsed = new URL(baseURL, WEBAPP_URL);
+  baseUrlParsed.searchParams.set("category", category);
+  return useQueryParam ? `${baseUrlParsed.toString()}` : `${baseURL}/${category}`;
 }
 
-const getAppCategories = (baseURL: string, useQueryParam = false) => {
+const getAppCategories = (baseURL: string, useQueryParam = true) => {
```
Comment (hariombalhara) [inline packages/app-store/_utils/getAppCategories.ts:10]: Use query params so that apps listing and category filtering can work on both auth/setup and settings/admin

File: packages/app-store/_utils/getAppCategories.ts [hunk 3]
```diff
@@ -1,10 +1,13 @@
+import { WEBAPP_URL } from "@calcom/lib/constants";
 import { Icon } from "@calcom/ui";
 
 function getHref(baseURL: string, category: string, useQueryParam: boolean) {
-  return useQueryParam ? `${baseURL}&category=${category}` : `${baseURL}/${category}`;
+  const baseUrlParsed = new URL(baseURL, WEBAPP_URL);
+  baseUrlParsed.searchParams.set("category", category);
```
Comment (hariombalhara) [inline packages/app-store/_utils/getAppCategories.ts:6]: &category can only be suffixed if there is a query param already. So, handle it in a better way

**Review by JeroenReumkens — APPROVED** [review]
