### PR TITLE
fix: Location Change to Organizer Default Conferencing App

### LINKED ISSUE #16366: [CAL-4175] Changing the location for a booking to 'Organizer's default App' makes it literally just the text
It doesn't actually generate the link as per the Organizer's default App.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4175](https://linear.app/calcom/issue/CAL-4175/changing-the-location-for-a-booking-to-organizers-default-app-makes-it)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

- Fixes #16366 
- Fixes CAL-4175

## Changes
- Allow ADMIN/OWNER of a team to change the location of the booking
- In case of an error from the editLocation request, show an error toast
- Wait for the request to complete before closing Location Change Dialog. Ensures, that user knows the waits for the status of the location change before going away. Important because location change request can take good number of seconds.
- A refactor of editLocation.handler.ts. Moved queries to respective repositories
- Deletion of unused code in EditLocationDialog(where booking is assumed to be not set sometimes)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?
- Try change a team booking's  location to 'Organizer Default App'

### CODE REVIEW

**Comment by hariombalhara** [comment]
* **#16379** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/16379?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hariombalhara and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 1]
```diff
@@ -1396,7 +1396,7 @@ async function handler(
         safeStringify({ error, results })
       );
     } else {
-      const metadata: AdditionalInformation = {};
+      const additionalInformation: AdditionalInformation = {};
```
Comment (hariombalhara) [inline packages/features/bookings/lib/handleNewBooking.ts:1399]: Better name, avoids confusion with another metadata variable in the function but in different scope.

File: packages/trpc/server/routers/viewer/bookings/editLocation.handler.ts [hunk 2]
```diff
@@ -24,124 +31,230 @@ type EditLocationOptions = {
...
+     * - Phone Number for Organizer Phone
+     * - Meeting Link for Link Meeting Type
+     * - {OrganizerDefaultConferencingAppType} for Organizer Default Conferencing App
+     */
+    newLocation,
+    credentialId,
+  } = input;
+  const { booking, user: loggedInUser } = ctx;
 
-  try {
```
Comment (hariombalhara) [inline packages/trpc/server/routers/viewer/bookings/editLocation.handler.ts:31]: Removing global try catch. Should add only where needed

File: apps/web/components/dialog/EditLocationDialog.tsx [hunk 3]
```diff
@@ -204,25 +207,6 @@ export const EditLocationDialog = (props: ISetLocationDialog) => {
               as="p"
             />
           </div>
-          {!booking && (
```
Comment (hariombalhara) [inline apps/web/components/dialog/EditLocationDialog.tsx:207]: There is no case in this component where booking isn't set. Params types also updated to reflect that.

File: apps/web/components/dialog/EditLocationDialog.tsx [hunk 4]
```diff
@@ -242,91 +226,45 @@ export const EditLocationDialog = (props: ISetLocationDialog) => {
...
-                    ...details,
-                    displayLocationPublicly,
-                  };
+                  newLocation = values.locationAddress || values.locationLink || values.locationPhoneNumber;
+                } else {
+                  newLocation = newLocationType;
                 }
 
-                if (values.credentialId) {
-                  details = {
```
Comment (hariombalhara) [inline apps/web/components/dialog/EditLocationDialog.tsx:302]: We don't need all this logic. Requirement is to just send what is set out of the three options

**Review by hariombalhara — COMMENTED** [review]
Self review done

File: packages/app-store/locations.ts [hunk 5]
```diff
@@ -14,6 +14,7 @@ export type DefaultEventLocationType = {
   label: string;
   messageForOrganizer: string;
   category: "in person" | "conferencing" | "other" | "phone";
+  linkType: "static";
```
Comment (hariombalhara) [inline packages/app-store/locations.ts:17]: All default apps are static linkType apps. Set this explicitly so that we can access `linkType` property easily on a union of DefaultLocation and LocationFromApp

File: apps/web/components/dialog/EditLocationDialog.tsx [hunk 6]
```diff
@@ -241,91 +229,51 @@ export const EditLocationDialog = (props: ISetLocationDialog) => {
...
-                if (
-                  newLocation === LocationType.Link ||
-                  (!eventLocationType?.default && eventLocationType?.linkType === "static")
-                ) {
-                  details = { link: values.locationLink };
-                }
-
-                if (newLocation === LocationType.UserPhone) {
-                  details = { hostPhoneNumber: values.locationPhoneNumber };
-                }
```
Comment (hariombalhara) [inline apps/web/components/dialog/EditLocationDialog.tsx:291]: Use the eventLocationType.variable instead of hardcoding stuff

File: apps/web/components/dialog/EditLocationDialog.tsx [hunk 7]
```diff
@@ -241,91 +229,51 @@ export const EditLocationDialog = (props: ISetLocationDialog) => {
...
-
+                const { locationType: newLocationType } = values;
+                let newLocation;
+                // For, the locations that require organizer to type-in some values, we need the value
                 if (eventLocationType?.organizerInputType) {
-                  details = {
-                    ...details,
-                    displayLocationPublicly,
-                  };
-                }
```
Comment (hariombalhara) [inline apps/web/components/dialog/EditLocationDialog.tsx:298]: Not needed

File: packages/app-store/locations.ts [hunk 8]
```diff
@@ -247,21 +255,21 @@ for (const [appName, meta] of Object.entries(appStoreMetadata)) {
   }
 }
 
-const locationsTypes = [...defaultLocations, ...locationsFromApps];
-export const getStaticLinkBasedLocation = (locationType: string) =>
-  locationsFromApps.find((l) => l.linkType === "static" && l.type === locationType);
+const locations = [...defaultLocations, ...locationsFromApps];
```
Comment (hariombalhara) [inline packages/app-store/locations.ts:258]: Rename

File: packages/app-store/locations.ts [hunk 9]
```diff
@@ -247,21 +255,21 @@ for (const [appName, meta] of Object.entries(appStoreMetadata)) {
   }
 }
 
-const locationsTypes = [...defaultLocations, ...locationsFromApps];
-export const getStaticLinkBasedLocation = (locationType: string) =>
-  locationsFromApps.find((l) => l.linkType === "static" && l.type === locationType);
```
Comment (hariombalhara) [inline packages/app-store/locations.ts:252]: Unused

File: packages/app-store/locations.ts [hunk 10]
```diff
@@ -247,21 +255,21 @@ for (const [appName, meta] of Object.entries(appStoreMetadata)) {
...
+const locations = [...defaultLocations, ...locationsFromApps];
 
-export const getEventLocationTypeFromApp = (locationType: string) =>
+export const getLocationFromApp = (locationType: string) =>
```
Comment (hariombalhara) [inline packages/app-store/locations.ts:260]: Renamed

File: packages/core/EventManager.ts [hunk 11]
```diff
@@ -7,7 +7,7 @@ import type { z } from "zod";
 import { getCalendar } from "@calcom/app-store/_utils/getCalendar";
 import { FAKE_DAILY_CREDENTIAL } from "@calcom/app-store/dailyvideo/lib/VideoApiAdapter";
 import { appKeysSchema as calVideoKeysSchema } from "@calcom/app-store/dailyvideo/zod";
-import { getEventLocationTypeFromApp, MeetLocationType } from "@calcom/app-store/locations";
+import { getLocationFromApp, MeetLocationType } from "@calcom/app-store/locations";
```
Comment (hariombalhara) [inline packages/core/EventManager.ts:10]: Rename

File: packages/trpc/server/routers/viewer/bookings/editLocation.handler.ts [hunk 12]
```diff
@@ -1,147 +1,287 @@
...
+  }
+
+  const appLink = defaultConferencingApp.appLink;
+  if (!appLink) {
+    throw new SystemError(`Default conferencing app ${defaultConferencingAppSlug} has no app link`);
+  }
+  return appLink;
+}
+
+export async function editLocationHandler({ ctx, input }: EditLocationOptions) {
```
Comment (hariombalhara) [inline packages/trpc/server/routers/viewer/bookings/editLocation.handler.ts:245]: Heavily reduced the size of this function

File: packages/trpc/server/routers/viewer/bookings/editLocation.handler.ts [hunk 13]
```diff
@@ -1,147 +1,289 @@
...
 import type { CredentialPayload } from "@calcom/types/Credential";
+import type { Ensure } from "@calcom/types/utils";
 
 import { TRPCError } from "@trpc/server";
 
 import type { TrpcSessionUser } from "../../../trpc";
 import type { TEditLocationInputSchema } from "./editLocation.schema";
 import type { BookingsProcedureContext } from "./util";
 
+// #region EditLocation Types and Helpers
```
Comment (hariombalhara) [inline packages/trpc/server/routers/viewer/bookings/editLocation.handler.ts:30]: Makes all the local functions a region to be able to easily fold them in VSCode

File: packages/trpc/server/routers/viewer/bookings/editLocation.handler.ts [hunk 14]
```diff
@@ -1,147 +1,289 @@
...
+    throw new SystemError(`Default conferencing app ${defaultConferencingAppSlug} has no app link`);
+  }
+  return appLink;
+}
+
+export async function editLocationHandler({ ctx, input }: EditLocationOptions) {
+  const { newLocation, credentialId: conferenceCredentialId } = input;
+  const { booking, user: loggedInUser } = ctx;
+
+  const organizer = await UserRepository.findByIdOrThrow({ id: booking.userId || 0 });
```
Comment (joeauyeung) [inline packages/trpc/server/routers/viewer/bookings/editLocation.handler.ts:251]: When would the `booking.userId` not be defined? Should we instead throw an error?

File: packages/lib/buildCalEventFromBooking.ts [hunk 15]
```diff
@@ -0,0 +1,106 @@
...
+  attendees: Attendee[];
+  eventType: EventType | null;
+};
+
+export const buildCalEventFromBooking = async ({
+  booking,
+  organizer,
+  location,
+  conferenceCredentialId,
+}: {
```
Comment (joeauyeung) [inline packages/lib/buildCalEventFromBooking.ts:59]: I'm seeing that the result of this is being passed into the `EventManager`. Should we add team members to the result object?

File: packages/trpc/server/routers/viewer/bookings/editLocation.handler.ts [hunk 16]
```diff
@@ -1,147 +1,289 @@
...
+  const evt = await buildCalEventFromBooking({
+    booking,
+    organizer,
+    location: newLocationInEvtFormat,
+    conferenceCredentialId,
+  });
+
+  const eventManager = new EventManager({
+    ...ctx.user,
+    credentials: await getAllCredentials({ user: ctx.user, conferenceCredentialId }),
```
Comment (joeauyeung) [inline packages/trpc/server/routers/viewer/bookings/editLocation.handler.ts:268]: The result of `getAllCredentials` returns a duplicate of the conference credential. It works fine for now but I'm worried about any side effects in the future.

**Review by joeauyeung — DISMISSED** [review]
Great work @hariombalhara. I'm curious what exactly was causing this bug? I also have a few comments as well.

**Comment by hariombalhara** [comment]
The root cause was that location=conferencing, needs special handling which wasn't there

File: packages/trpc/server/routers/viewer/bookings/editLocation.handler.ts [hunk 17]
```diff
@@ -1,147 +1,289 @@
...
-          translate: await getTranslation(attendee.locale ?? "en", "common"),
-          locale: attendee.locale ?? "en",
-        },
-      };
+  if (conferenceCredentialId) {
+    conferenceCredential = await CredentialRepository.findFirstByIdWithKeyAndUser({
+      id: conferenceCredentialId,
     });
+  }
+  return [...(credentials ? credentials : []), ...(conferenceCredential ? [conferenceCredential] : [])];
```
[the remark this answers is not in the document]
Comment (hariombalhara) [reply packages/trpc/server/routers/viewer/bookings/editLocation.handler.ts:140]: But `keys` would be there in both cases. `getUsersCredentials` returned value also has `keys`

File: packages/trpc/server/routers/viewer/bookings/editLocation.handler.ts (hunk 16 above)
Comment (hariombalhara) [reply packages/trpc/server/routers/viewer/bookings/editLocation.handler.ts:268]: I don't see any issues at the moment but should be handled though as it isn't expected to have duplicate credentials.  Can take it up in a followup.

Also, this is same as what was happening earlier just clubbed into `getAllCredentials`.

File: packages/trpc/server/routers/viewer/bookings/editLocation.handler.ts (hunk 14 above)
Comment (hariombalhara) [reply packages/trpc/server/routers/viewer/bookings/editLocation.handler.ts:251]: Yeah, certainly that is the best way.  Added a followup ticket

File: packages/lib/buildCalEventFromBooking.ts (hunk 15 above)
Comment (hariombalhara) [reply packages/lib/buildCalEventFromBooking.ts:59]: If team members are passed at other places, then we should pass those here too.

**Review by joeauyeung — DISMISSED** [review]
Comments have been addressed in a follow up issue. @hariombalhara up to you if you want to merge or wait for another review.

**Comment by hariombalhara** [comment]
@joeauyeung Fixed a merge conflict. Please reapprove.

**Review by alishaz-polymath — APPROVED** [review]
🚀 🚀 🚀
