### PR TITLE
fix/payment-status-message-on-booking-cancelled

### LINKED ISSUE #7259: [CAL-1128] Fix booking payment message
Check if message display only when required.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1128](https://linear.app/calcom/issue/CAL-1128/fix-booking-payment-message)</sub>

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

- Adds conditional to only render payment related message when booking it's cancelled/rejected.

Fixes #7259 

**Environment**: Staging(main branch) 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Any booking that required payment should display message about payment refund status when cancelled/rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: apps/web/pages/booking/[uid].tsx [hunk 1]
```diff
@@ -442,17 +442,19 @@ export default function Success(props: SuccessProps) {
...
-                        t("booking_with_payment_cancelled")}
-                      {props.paymentStatus.success &&
-                        !props.paymentStatus.refunded &&
-                        t("booking_with_payment_cancelled_already_paid")}
-                      {props.paymentStatus.refunded && t("booking_with_payment_cancelled_refunded")}
-                    </h4>
-                  )}
+                  {props.paymentStatus &&
+                    (bookingInfo.status === BookingStatus.CANCELLED ||
+                      bookingInfo.status === BookingStatus.REJECTED) && (
```
Comment (alannnc) [inline apps/web/pages/booking/[uid].tsx:447]: Only display when booking it's cancelled

**Review by CarinaWolli — APPROVED** [review]
LGTM!

**Review by roae — APPROVED** [review]

**Review by zomars — APPROVED** [review]
