### PR TITLE
fix: improve cross button alignment and spacing in FormBuilder Options

### LINKED ISSUE #24245: Fix misaligned cross buttons and improve spacing in FormBuilder Options component
## Issue Summary

The cross (delete) buttons in the booking question form's radio/checkbox/select option input fields are misaligned and the options list appears too congested with insufficient spacing. The delete buttons are positioned too close to the right edge of input fields and get cut off, while the vertical spacing between options is too tight, creating a cramped user experience.

## Steps to Reproduce

1. Navigate to Event Types → Advanced tab
2. Click on "Add a booking question"
3. Select "Radio Group" or "Checkbox Group" as the field type
4. In the Options section, add multiple options (more than 2)
5. Observe the cross (X) buttons on the right side of each input field
6. Notice the tight spacing between option input fields

## Actual Results

- Cross buttons are misaligned and positioned too close to the right edge of input fields
- Some cross buttons appear cut off or partially hidden
- Vertical spacing between option input fields is too tight (only 4px gap)
- No spacing between the options list and the "+ Add an Option" button
- Overall cramped and unprofessional appearance

https://github.com/user-attachments/assets/2aaf25ff-37e3-4caf-8c71-debfe8bac627

## Expected Results

- Cross buttons should be properly aligned within the input field boundaries
- Adequate spacing should be provided around the cross buttons
- Comfortable vertical spacing between option input fields (12px+)
- Proper spacing between the options list and the add button
- Clean, professional appearance that works on both mobile and desktop

https://github.com/user-attachments/assets/5266a6d2-8e6f-4b63-b513-446162cd27f0

## Technical Details

- **Component**: `packages/features/form-builder/FormBuilder.tsx` - `Options` component
- **Issue Location**: Lines 463-544 in the Options component
- **Root Cause**: 
  - Cross buttons using negative left margin (`-ml-8`) causing misalignment
  - Insufficient gap between list items (`gap-1` = 4px)
  - No spacing between options list and add button
- **Affected Field Types**: Radio Group, Checkbox Group, Select, MultiSelect
- **Browser**: All browsers (responsive design issue)

### Before Fix:
- Cross buttons positioned with `className="-ml-8 mb-2"` causing misalignment
- List items with `className="flex flex-col gap-1"` (4px spacing)
- No spacing between options list and add button

### After Fix:
- Cross buttons positioned absolutely within input container: `className="absolute right-2 top-1/2 -translate-y-1/2"`
- Input field padding adjusted: `className={value.length > 2 && !readOnly ? "pr-8" : ""}`
- Increased list spacing: `className="flex flex-col gap-3"` (12px spacing)
- Added button spacing: `className="mt-3"` on add button

### PR DESCRIPTION
**Pull request by KartikLabhshetwar**
## What does this PR do?

- Fixes #24245
- Fixes [CAL-6513](https://linear.app/calcom/issue/CAL-6513/fix-misaligned-cross-buttons-and-improve-spacing-in-formbuilder)

## Visual Demo (For contributors especially)

A visual demonstration is strongly recommended, for both the original and new change **(video / image - any one)**.

#### Video Demo (if applicable):
before:

https://github.com/user-attachments/assets/1737b137-6f2f-4874-92a4-5b0e037ed316

after:

https://github.com/user-attachments/assets/3f3e0c14-514c-4930-ad15-44ef544c01cd

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

### CODE REVIEW

File: packages/features/form-builder/FormBuilder.tsx [hunk 1]
```diff
@@ -606,7 +608,7 @@ function FieldEditDialog({
   const variantsConfig = fieldForm.watch("variantsConfig");
 
   const fieldTypes = Object.values(fieldTypesConfigMap);
-  const fieldName = fieldForm.getValues("name");
+  const _fieldName = fieldForm.getValues("name");
```
Comment (KartikLabhshetwar) [inline packages/features/form-builder/FormBuilder.tsx]: eslint fix

File: packages/features/form-builder/FormBuilder.tsx [hunk 2]
```diff
@@ -426,7 +426,7 @@ export const FormBuilder = function FormBuilder({
 function Options({
   label = "Options",
   value,
-  // eslint-disable-next-line @typescript-eslint/no-empty-function
+
```
Comment (KartikLabhshetwar) [inline packages/features/form-builder/FormBuilder.tsx]: same issue as this

https://github.com/user-attachments/assets/6c09c07d-70ec-4f31-b87f-c6b93cb431b7

**Comment by KartikLabhshetwar** [comment]
@Udit-takkar @Devanshusharma2005

File: packages/features/form-builder/FormBuilder.tsx [hunk 3]
```diff
@@ -881,7 +883,6 @@ function FieldLabel({ field }: { field: RhfFormField }) {
     if (fieldsThatSupportLabelAsSafeHtml.includes(field.type)) {
       return (
         <span
-          // eslint-disable-next-line react/no-danger
```
Comment (KartikLabhshetwar) [inline packages/features/form-builder/FormBuilder.tsx:884]: same here

https://github.com/user-attachments/assets/39e54b10-d74b-4c38-a490-ef73d336d869

File: packages/features/form-builder/FormBuilder.tsx [hunk 4]
```diff
@@ -480,7 +480,23 @@ function Options({
...
+                      StartIcon="x"
+                      onClick={() => {
+                        if (!value) return;
+                        const newOptions = [...(value || [])];
+                        newOptions.splice(index, 1);
+                        onChange(newOptions);
+                      }}
+                    />
+                  )}
                 </div>
```
Comment (Devanshusharma2005) [inline packages/features/form-builder/FormBuilder.tsx:500]: Curious to know the reason behind this change.

File: packages/features/form-builder/FormBuilder.tsx [hunk 5]
```diff
@@ -698,7 +700,7 @@ function FieldEditDialog({
                       />
                     ) : null}
 
-                    {!!fieldType?.supportsLengthCheck ? (
+                    {fieldType?.supportsLengthCheck ? (
                       <FieldWithLengthCheckSupport containerClassName="mt-6" fieldForm={fieldForm} />
```
Comment (Devanshusharma2005) [inline packages/features/form-builder/FormBuilder.tsx:704]: this too.

**Review by Devanshusharma2005 — COMMENTED** [review]
Thank you for the pr . Let's wait for @anikdhabal review too.

File: packages/features/form-builder/FormBuilder.tsx (hunk 5 above)
Comment (KartikLabhshetwar) [reply packages/features/form-builder/FormBuilder.tsx:704]: eslint fix.

File: packages/features/form-builder/FormBuilder.tsx (hunk 4 above)
Comment (KartikLabhshetwar) [reply packages/features/form-builder/FormBuilder.tsx:500]: Hi, @Devanshusharma2005 these are my reasons.

- The negative-margin hack caused the delete icon to sit outside the input’s bounds and misalign on different breakpoints/zoom levels. Wrapping the input in a `relative` container and absolutely positioning the icon guarantees stable right-edge alignment across sizes and browsers.
- Adding right padding (`pr-8`) prevents text/caret overlap with the icon, reducing accidental clicks and improving readability and accessibility.
- Vertically centering the icon (`top-1/2 -translate-y-1/2`) keeps it aligned regardless of input density/size variants.
- Increasing gaps (`gap-3`, `mt-3`) improves scannability and touch targets on mobile.

File: packages/features/form-builder/FormBuilder.tsx (hunk 5 above)
Comment (KartikLabhshetwar) [reply packages/features/form-builder/FormBuilder.tsx:704]: https://github.com/user-attachments/assets/e0a1df43-e34f-4df6-a426-169dfa42c487

**Comment by KartikLabhshetwar** [comment]
@dhairyashiil

**Review by Udit-takkar — APPROVED** [review]
