### PR TITLE
Fixing issues around workflows

### LINKED ISSUE #6905: [CAL-999] Asking for reschedule doesn’t cancel SMS reminders
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-999](https://linear.app/calcom/issue/CAL-999/asking-for-reschedule-doesnt-cancel-sms-reminders)</sub>

### LINKED ISSUE #6956: [CAL-1018] Workflow data lost when clicking outside of app
### Issue Summary

When clicking somewhere outside of the app while editing a workflow all new data is lost

<sub>[CAL-1018](https://linear.app/calcom/issue/CAL-1018/workflow-data-lost-when-clicking-outside-of-app)</sub>

### LINKED ISSUE #6973: [CAL-1026] Reminder still shows up for cancelled events
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Any email reminder set via workflow still gets sent for cancelled events

### Steps to Reproduce

1. Create a couple of **email** reminder workflows for the host and attendee.
2. Book an event
3. Cancel the event
4. At your set workflow execution time, you will still get the reminder email

**Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?**

When the event was cancelled, it was removed from the calendar and is no longer valid. Thus, any email or similar reminders related to this should not be sent. Otherwise, the user will get confused and misled.

### Technical details

Not applicable

<sub>[CAL-1026](https://linear.app/calcom/issue/CAL-1026/reminder-still-shows-up-for-cancelled-events)</sub>

### PR DESCRIPTION
**Pull request by CarinaWolli**
## What does this PR do?

Fixes issue that workflow email reminders of canceled bookings were still sent. 
Fixes issue that bookings that requested rescheduling still sent SMS and email reminders. 
Also, fixes the issue that when editing a workflow the data gets lost when clicking outside of the workflow. 

Fixes #6973
Fixes #6905
Fixes #6956

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/trpc/server/routers/viewer/bookings.tsx [hunk 1]
```diff
@@ -472,6 +479,30 @@ export const bookingsRouter = router({
           },
         });
 
+        // delete scheduled jobs of cancelled bookings
+        cancelScheduledJobs(bookingToReschedule);
```
Comment (CarinaWolli) [inline packages/trpc/server/routers/viewer/bookings.tsx:483]: cancel scheduledJobs and all workflow reminders for the booking if rescheudling is requested

**Review by emrysal — APPROVED** [review]
Nice, simple fixes 👍
