### PR TITLE
fix: add belongsToActiveTeam

### LINKED ISSUE #7884: [CAL-1315] belongs to Active team is not set for google sign in
Found a bug? Please fill out the sections below. 👍

### Issue Summary

[https://threads.com/34454702096?s=efVDCvYtY35GbWZmashtof](https://threads.com/34454702096?s=efVDCvYtY35GbWZmashtof)

Due to this bug some users are getting 403 error while downloading recordings

### Technical details

* Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
* Node.js version
* Anything else that you think could be an issue.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1315](https://linear.app/calcom/issue/CAL-1315/belongs-to-active-team-is-not-set-for-google-sign-in)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/7884

Screenshot 2023-03-23 at 2 26 50 AM

for google sign-in the belongsToActiveTeams property was not set

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

File: packages/features/auth/lib/next-auth-options.ts [hunk 1]
```diff
@@ -391,16 +391,35 @@ export const AUTH_OPTIONS: AuthOptions = {
...
+            },
           },
         });
 
         if (!existingUser) {
           return token;
         }
 
+        // Check if the existingUser has any active teams
+        const belongsToActiveTeam =
```
Comment (hariombalhara) [inline packages/features/auth/lib/next-auth-options.ts:407]: Let's abstract out the code from line 160 into a fn in this module and reuse that here.

**Review by hariombalhara — DISMISSED** [review]
Left a comment

File: packages/features/auth/lib/next-auth-options.ts [hunk 2]
```diff
@@ -391,16 +391,35 @@ export const AUTH_OPTIONS: AuthOptions = {
...
+          existingUser.teams.filter((m: { team: { metadata: unknown } }) => {
+            if (!IS_TEAM_BILLING_ENABLED) return true;
+            const metadata = teamMetadataSchema.safeParse(m.team.metadata);
+            if (metadata.success && metadata.data?.subscriptionId) return true;
+            return false;
+          }).length > 0;
+
         return {
-          ...existingUser,
+          id: existingUser.id,
```
Comment (hariombalhara) [inline packages/features/auth/lib/next-auth-options.ts:416]: cc @emrysal @zomars This is a critical place to change, looks good to me, but you should check too.

File: packages/features/auth/lib/next-auth-options.ts [hunk 3]
```diff
@@ -1,5 +1,6 @@
 import type { UserPermissionRole } from "@prisma/client";
```
Comment (emrysal) [inline packages/features/auth/lib/next-auth-options.ts:1]:
```suggestion
import type { UserPermissionRole, Membership, Team } from "@prisma/client";
```
NIT

File: packages/features/auth/lib/next-auth-options.ts (hunk 2 above)
Comment (emrysal) [reply packages/features/auth/lib/next-auth-options.ts:419]: I'm not sure why we shouldn't continue to just ...existingUser, belongsToActiveTeam will append. 💭

**Review by emrysal — CHANGES_REQUESTED** [review]
It works, but please keep this logic as consistent to before as possible.

**Comment by Udit-takkar** [comment]
@emrysal don't want to pass the teams field.

**Comment by emrysal** [comment]
> @emrysal don't want to pass the teams field with existingUser

Ah makes sense, use deconstructing 👍 

`const { teams, ...existingUser } = ...`

optionally then cleanup using
`delete teams;`

**Review by emrysal — APPROVED** [review]
LGTM, looking good 👍
