### PR TITLE
fixed yarn dx

### LINKED ISSUE #8292: [CAL-1500] insights icon filter too big
image

<sub>[CAL-1500](https://linear.app/calcom/issue/CAL-1500/insights-icon-filter-too-big)</sub>

### PR DESCRIPTION
**Pull request by PeerRich**
pair programming with @hariombalhara

### CODE REVIEW

**Review by hariombalhara — APPROVED** [review]

File: packages/prisma/seed-app-store.ts [hunk 1]
```diff
@@ -304,6 +303,7 @@ export default async function main() {
     if (generatedApp.isTemplate && process.argv[2] !== "seed-templates") {
       continue;
     }
+    console.log(`Creating app ${generatedApp.slug} with ${generatedApp.dirName}...`);
```
Comment (hariombalhara) [inline packages/prisma/seed-app-store.ts:306]:
```suggestion
```
