### PR TITLE
fix add endIconClassName in button

### LINKED ISSUE #3894: Tooltip requires TooltipProvider (Radix-UI upgrade)
Found a bug? Please fill out the sections below. 👍

### Issue Summary
When going to deployments in console
image
### Steps to Reproduce
Go to console > deployments, tooltip error pops.

### PR DESCRIPTION
**Pull request by agustif**
## What does this PR do?
- Adds support for endIconClassName in Button

Required for https://github.com/calcom/console/pull/30

Fixes #3894

### CODE REVIEW

**Review by pumfleet — APPROVED** [review]

File: packages/ui/Button.tsx [hunk 1]
```diff
@@ -130,7 +132,9 @@ export const Button = forwardRef<HTMLAnchorElement | HTMLButtonElement, ButtonPr
           </svg>
         </div>
       )}
-      {EndIcon && <EndIcon className="-mr-1 inline h-5 w-5 ltr:ml-2 rtl:mr-2" />}
+      {EndIcon && (
+        <EndIcon className={classNames("-mr-1 inline h-5 w-5 ltr:ml-2 rtl:mr-2", endIconClassName || "")} />
```
Comment (sean-brydon) [inline packages/ui/Button.tsx:136]: LGTM :) NIT this could follow the standard we have been using with 

`endIconClassName && endIconClassName`

**Review by sean-brydon — APPROVED** [review]

File: packages/ui/Button.tsx (hunk 1 above)
Comment (PeerRich) [reply packages/ui/Button.tsx:136]: @agustif do you wanna add this or nah?

alternatively, @sean-brydon can you use the "suggest" feature and offer a solution here?
