### PR TITLE
fix: type error in the `EventAvailabilityTabPlatformWrapper` component

### LINKED ISSUE #21981: Type error in the `EventAvailabilityTabPlatformWrapper` component
### Issue Summary

There's a type mismatch in `scheduleQueryData.schedule`.

### Steps to Reproduce

1. Open `EventAvailabilityTabPlatformWrapper`
2. Check on the line no. `61`

### Actual Results

Type mismatch error

### Expected Results

No error

### Evidence

Image

### PR DESCRIPTION
**Pull request by apsinghdev**
## What does this PR do?

- Fixes #21981 
- Fixes CAL-5971

## Visual Demo (For contributors especially)

Screenshot 2025-06-23 at 5 21 57 PM

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

Pls check the `Problems` section in the terminal.
    

---

## Summary by cubic
Fixed a type error in the `EventAvailabilityTabPlatformWrapper` component by updating the structure of the `schedule` prop. This ensures correct typing and prevents runtime errors.

### CODE REVIEW

File: packages/platform/atoms/event-types/wrappers/EventAvailabilityTabPlatformWrapper.tsx [hunk 1]
```diff
@@ -54,22 +53,21 @@ const EventAvailabilityTabPlatformWrapper = ({
...
-              ...acc,
-              {
-                startTime: new Date(avail.startTime),
-                endTime: new Date(avail.endTime),
-                days: avail.days,
-              },
-            ],
-            []
-          ) || [],
+        schedule: atomSchedule.schedule.map((avail: any) => ({
```
[the remark this answers is not in the document]
Comment (Devanshusharma2005) [reply packages/platform/atoms/event-types/wrappers/EventAvailabilityTabPlatformWrapper.tsx]: LGTM, please try to address this small cubic suggestion.

**Comment by apsinghdev** [comment]
@Devanshusharma2005 done. please take a look!

**Review by Devanshusharma2005 — DISMISSED** [review]
LGTM, thanks for the pr.

File: packages/platform/atoms/event-types/wrappers/EventAvailabilityTabPlatformWrapper.tsx [hunk 2]
```diff
@@ -54,22 +54,21 @@ const EventAvailabilityTabPlatformWrapper = ({
...
+        schedule: atomSchedule.schedule.map((avail: ScheduleQueryData["schedule"][number]) => ({
+          id: avail.id ?? null,
+          startTime: new Date(avail.startTime),
+          endTime: new Date(avail.endTime),
+          userId: avail.userId ?? null,
+          eventTypeId: avail.eventTypeId ?? null,
+          scheduleId: avail.scheduleId ?? null,
+          date: avail.date ? new Date(avail.date) : null,
+          days: avail.days,
+        })),
```
Comment (Udit-takkar) [inline packages/platform/atoms/event-types/wrappers/EventAvailabilityTabPlatformWrapper.tsx]: I think it should be (atomSchedule.schedule || []).map

Comment (apsinghdev) [reply packages/platform/atoms/event-types/wrappers/EventAvailabilityTabPlatformWrapper.tsx]: Make sense! This fallback can save runtime issues. Fixed it. Thanks!

Comment (Devanshusharma2005) [reply packages/platform/atoms/event-types/wrappers/EventAvailabilityTabPlatformWrapper.tsx]: > I think it should be (atomSchedule.schedule || []).map

ahh coz atomSchedule.schedule might be undefined or null if no schedule is present.

Comment (apsinghdev) [reply packages/platform/atoms/event-types/wrappers/EventAvailabilityTabPlatformWrapper.tsx]: Exactly!

**Review by Devanshusharma2005 — APPROVED** [review]
LGTM

**Review by Devanshusharma2005 — DISMISSED** [review]
@apsinghdev can you please fix the tests. Marking it draft until then.

**Review by kart1ka — APPROVED** [review]
LGTM

**Review by Ryukemeister — APPROVED** [review]
LGTM!

**Review by volnei — APPROVED** [review]

**Review by Devanshusharma2005 — APPROVED** [review]
LGTM
