### PR TITLE
fix: reject icon color

### LINKED ISSUE #8890: [CAL-1696] invisible icon - email
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When you get an email to confirm/reject, the icon of rejections is not visible due to its color: 
image

### Steps to Reproduce

1. Open your schedule, 
2. Set a slot that needs a confirmation 
3. Book a time with confirmation 
4. check your email

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Technical details

As a solution, this could be solved with 
```css
filter: invert(100%);
```
in the CSS but it's needed to be passed as props. 

The related code: https://github.com/calcom/cal.com/blob/main/packages/emails/src/templates/OrganizerRequestEmail.tsx

<sub>[CAL-1696](https://linear.app/calcom/issue/CAL-1696/invisible-icon-email)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes https://github.com/calcom/cal.com/issues/8890
Screenshot 2023-05-22 at 3 36 36 PM

**Environment**: Staging(main branch) / Production

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by a0m0rajab** [comment]
Have you thought about adding a short line explaining why you removed the previous image and added this one? @Udit-takkar this might save a few minutes for the reviewer from opening other tabs and going back and forth.

File: packages/emails/src/components/CallToActionIcon.tsx [hunk 1]
```diff
@@ -19,7 +11,6 @@ export const CallToActionIcon = ({
       height: "1rem",
       width: "1rem",
       marginLeft: "0.5rem",
-      ...(secondary && { filter: "brightness(50%)" }),
```
Comment (Udit-takkar) [inline packages/emails/src/components/CallToActionIcon.tsx:22]: filter property doesn't work in emails https://github.com/calcom/cal.com/issues/8890#issuecomment-1556293989

**Review by PeerRich — APPROVED** [review]
