### PR TITLE
fix: overflow text, ui bugs

### LINKED ISSUE #5024: [CAL-159] event-types/availability not mobile friendly
> From [Linear-GitHub Sync](https://synclinear.com)

### PR DESCRIPTION
**Pull request by Udit-takkar**
Fixes: #5024 #5083

Screenshot 2022-10-18 at 5 45 55 PM
Screenshot 2022-10-18 at 5 46 11 PM

### CODE REVIEW

**Comment by sean-brydon** [comment]
Looking good lil NIT - there still seems to be some padding issues on this edit button 
CleanShot 2022-10-18 at 13 34 30@2x

**Comment by PeerRich** [comment]
can you test with a longer title, too?

File: apps/web/components/v2/eventtype/AvailabilityTab.tsx [hunk 1]
```diff
@@ -134,6 +138,7 @@ export const AvailabilityTab = () => {
             color="minimal"
             EndIcon={Icon.FiExternalLink}
             target="_blank"
+            className="whitespace-nowrap"
```
Comment (JeroenReumkens) [inline apps/web/components/v2/eventtype/AvailabilityTab.tsx:141]: Perhaps we could put the edit link and the timezone underneath each other on mobile? `flex-col` vs `flex-row`. Because by using `whitespace-nowrap` the text still won't conform to the grid.

**Review by JeroenReumkens — CHANGES_REQUESTED** [review]

File: apps/web/components/v2/eventtype/AvailabilityTab.tsx (hunk 1 above)
Comment (Udit-takkar) [reply apps/web/components/v2/eventtype/AvailabilityTab.tsx:141]: Screenshot 2022-10-18 at 6 20 11 PM

is the ui fine ? without border doesn't look good

Comment (JeroenReumkens) [reply apps/web/components/v2/eventtype/AvailabilityTab.tsx:141]: I like it @Udit-takkar!

Comment (Udit-takkar) [reply apps/web/components/v2/eventtype/AvailabilityTab.tsx]: done

**Review by JeroenReumkens — APPROVED** [review]

**Comment by JeroenReumkens** [comment]
@Udit-takkar Did you also check Peer's comment? Apart from that all good to me!

**Comment by Udit-takkar** [comment]
@PeerRich you mean the booking title ? ok will also fix this

**Comment by Udit-takkar** [comment]
Screenshot 2022-10-19 at 5 36 26 PM

@Jaibles  can you suggest some design for this on mobile ?

**Comment by Jaibles** [comment]
@Udit-takkar https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=14750%3A110249

**Review by PeerRich — CHANGES_REQUESTED** [review]
blocked until new figma is implemented @Udit-takkar

**Review by PeerRich — APPROVED** [review]
