### PR TITLE
fix: increase edit location height

### LINKED ISSUE #5801: [CAL-510] Make the location select dropdown much higher
Right now it looks like there are no more options

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-510](https://linear.app/calcom/issue/CAL-510/make-the-location-select-dropdown-much-higher)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
Fixes: https://github.com/calcom/cal.com/issues/5801#issuecomment-1337455451

Screenshot 2022-12-06 at 1 17 31 AM

### CODE REVIEW

File: apps/web/components/eventtype/EditLocationDialog.tsx [hunk 1]
```diff
@@ -1,371 +0,0 @@
-import { ErrorMessage } from "@hookform/error-message";
```
Comment (Udit-takkar) [inline apps/web/components/eventtype/EditLocationDialog.tsx:1]: this file is not being used anywhere

**Review by PeerRich — APPROVED** [review]
