### PR TITLE
fix: meeting url variable in workflow notifitcations

### LINKED ISSUE #10758: [CAL-2518] {MEETING_URL} intermittently missing from some custom emails
### Issue Summary

I've noticed on some custom email workflows, the {MEETING_URL} doesn't seem to be populating

When enabling multiple custom workflows triggered by a new booking creation, I received 5 copies of each workflow email. This was an unrelated bug that I've been unable to reproduce but it did help me confirm that 4 copies of the emails came in without the meeting_url but the 5th one **_was correctly populated_**. This makes me think there's a race condition of the emails getting sent out before the meeting url is generated

### Steps to Reproduce

1. Create a new workflow for when a booking is created
2. Copy the html from [this gist](https://gist.github.com/kcrimi/0106b86992e78ea86ab6928e5bdcf69e) as the custom body of the email
3. Save the workflow to function on an event type
4. Create a booking for that event type

### Actual Results

- The email is delivered as expected but intermittently does not include the meeting url while all other variables are included
Screenshot 2023-08-14 at 2 40 58 PM

### Expected Results

- All variables are filled in, including the meeting url (below picture is from the same workflow)
Screenshot 2023-08-14 at 2 41 07 PM

### Technical details

- Using the cloud hosted application

### Evidence

- See above

<sub>[CAL-2518](https://linear.app/calcom/issue/CAL-2518/meeting-url-intermittently-missing-from-some-custom-emails)</sub>

### PR DESCRIPTION
**Pull request by CarinaWolli**
## What does this PR do?

Fixes that the {MEETING_URL} from custom workflow templates wasn't populated for event types that require confirmation or payment.

Also fixes that confirmation emails were still sent after they were confirmed even when the default confirmation emails were disabled. 

Fixes #10758

## Requirement/Documentation

Have Sendgrid set up to send workflow emails.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Create a workflow that triggers when new event is booked & sends email to attendees
- Add a custom emails template with {MEETING_URL} variable
- Set active on an event type that requires confrimation 
- Book event type 
- Confirm booking 
- Check if email has meeting url

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: packages/features/bookings/lib/handleConfirmation.ts [hunk 1]
```diff
@@ -54,16 +67,41 @@ export async function handleConfirmation(args: {
...
+        if (isHostConfirmationEmailsDisabled) {
+          isHostConfirmationEmailsDisabled = allowDisablingHostConfirmationEmails(workflows);
+        }
+
+        if (isAttendeeConfirmationEmailDisabled) {
+          isAttendeeConfirmationEmailDisabled = allowDisablingAttendeeConfirmationEmails(workflows);
+        }
+      }
+
+      await sendScheduledEmails(
```
Comment (CarinaWolli) [inline packages/features/bookings/lib/handleConfirmation.ts:99]: Make sure confirmation emails are not sent when disabled because of an existing workflow

File: packages/features/bookings/lib/handleConfirmation.ts [hunk 2]
```diff
@@ -169,6 +213,7 @@ export async function handleConfirmation(args: {
         references: {
           create: scheduleResult.referencesToCreate,
         },
+        metadata: { ...(typeof booking.metadata === "object" ? booking.metadata : {}), videoCallUrl },
```
Comment (CarinaWolli) [inline packages/features/bookings/lib/handleConfirmation.ts:216]: bookings that require confirmation never had the videoCallUrl added to metadata

File: packages/features/bookings/lib/handleConfirmation.ts [hunk 3]
```diff
@@ -218,8 +263,6 @@ export async function handleConfirmation(args: {
         const eventTypeSlug = updatedBookings[index].eventType?.slug || "";
 
         const isFirstBooking = index === 0;
-        const videoCallUrl =
```
Comment (CarinaWolli) [inline packages/features/bookings/lib/handleConfirmation.ts:221]: The original booking didn't have videoCallUrl in metadata, that's why it was missing in the workflow emails that trigger when a meeting was confirmed

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 4]
```diff
@@ -2524,7 +2524,7 @@ async function handler(
         ...evt,
         ...{ metadata: metadataFromEvent, eventType: { slug: eventType.slug } },
       },
-      isNotConfirmed: evt.requiresConfirmation || false,
+      isNotConfirmed: !isConfirmedByDefault,
```
Comment (CarinaWolli) [inline packages/features/bookings/lib/handleNewBooking.ts:2527]: also includes bookings with payments not just event types that require confirmation

**Review by emrysal — APPROVED** [review]
Looks good to me, but a add-on is needed soon to add tests to ensure emails aren't send when e.g. host confirmation emails are disabled.

**Review by kemilbeltre — APPROVED** [review]
