### PR TITLE
fix: Team Invite Email Text formatting

### LINKED ISSUE #14435: [CAL-3364] Team Invite Email weird formatting
As reported by @PeerRich internally,

image

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3364](https://linear.app/calcom/issue/CAL-3364/team-invite-email-weird-formatting)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #14435
Regression from #13139

**Before New Org Onboarding Schema**
image

**Current Production**
image

**This PR**
image

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
- Simply invite a new or existing user of an org to a team

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by hariombalhara** [comment]
* **#14434** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/14434?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hariombalhara and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: packages/emails/src/templates/TeamInviteEmail.tsx [hunk 1]
```diff
@@ -227,19 +227,17 @@ export const TeamInviteEmail = (
     if (typeOfInvite === "TO_SUBTEAM") {
       return (
         <>
-          (
```
Comment (hariombalhara) [inline packages/emails/src/templates/TeamInviteEmail.tsx:230]: I thought I was in JS land but it was in react component 😅

**Review by alishaz-polymath — APPROVED** [review]
