### PR TITLE
fix: avatar remove button

### LINKED ISSUE #12164: [CAL-2665] Remove button not displayed now in avatar upload ( Regression)
https://github.com/calcom/cal.com/pull/12143#pullrequestreview-1703557065

<sub>[CAL-2665](https://linear.app/calcom/issue/CAL-2665/remove-button-not-displayed-now-in-avatar-upload-regression)</sub>

### PR DESCRIPTION
**Pull request by MehulZR**
## What does this PR do?

Fixes #12164  (issue)

Sometimes there is a weird caching behavior(requires tab reload) which I have not been able to pin-down the root cause.
If someone is familiar with this and can point me to the right direction I would like to look into it more.
Apart from that it is working as expected.
 
https://github.com/calcom/cal.com/assets/86384652/d2d999d7-7250-4e35-a58b-449136ffaac1

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
~There are some issues in organization settings profile~

File: apps/web/pages/settings/my-account/profile.tsx [hunk 1]
```diff
@@ -72,32 +72,24 @@ interface DeleteAccountValues {
 
 type FormValues = {
   username: string;
-  avatar: string | null;
```
Comment (Udit-takkar) [inline apps/web/pages/settings/my-account/profile.tsx:75]: Why did you remove null ? Avatar would be null if we want to remove it

Comment (Udit-takkar) [reply apps/web/pages/settings/my-account/profile.tsx:75]: Okay you added this in updateProfile 
"input.avatar ? await getAvatarToSet(input.avatar) : null"

**Review by Udit-takkar — APPROVED** [review]
LGTM.

Tested on normal account and org account.

File: apps/web/pages/settings/my-account/profile.tsx (hunk 1 above)
Comment (MehulZR) [reply apps/web/pages/settings/my-account/profile.tsx:75]: I removed it because in case it is null
image
The *previewSrc* prop for OrganizationMemberAvatar component will be null, and it uses Avatar component under the hood.
image

Which if provided null value for previewSrc, will just fetch the current avatar of the user. 

But on the profile settings page we would like to show the default avatar svg. 
image

So using an empty string for that purpose work as a trick. I could do it to support null but dont want regression at some other place.
