### PR TITLE
fix: slots rescheduleUid

### LINKED ISSUE #21621: fix: slots rescheduleUid
`slots/util.ts` uses `rescheduleUid` allow people to pass it when rescheduling a booking. in slots controller we need to expose `rescheduleUid` and document in docs.

### PR DESCRIPTION
**Pull request by weknowyourgame**
## What does this PR do?

- Fixes #21621 (GitHub issue number)
- Fixes [CAL-5876](https://linear.app/calcom/issue/CAL-5876/fix-slots-rescheduleui)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.
    

---

## Summary by cubic
Added support for a rescheduleUid parameter to the slots API, allowing the original booking time to appear as available when rescheduling.

- **New Features**
  - Accepts rescheduleUid in slot queries to include the current booking’s slot in availability.
  - Updated API docs and tests to cover rescheduling scenarios.

### CODE REVIEW

File: apps/api/v2/src/modules/slots/slots-2024-09-04/controllers/slots.controller.ts [hunk 1]
```diff
@@ -173,6 +174,13 @@ export class SlotsController_2024_09_04 {
       2024-08-13 (will have hours 00:00:00 aka at very beginning of the date) or you can specify hours manually like 2024-08-13T09:00:00Z.`,
     example: "2050-09-05",
   })
+  @ApiQuery({
+    name: "rescheduleUid",
```
Comment (supalarry) [inline apps/api/v2/src/modules/slots/slots-2024-09-04/controllers/slots.controller.ts]: I think we can improve naming here. `rescheduleUid` is not specific enough - the name should include what are we rescheduling specifically. Although longer, I think I would rename it as `bookingUidToReschedule`.

Do the same in [get-slots.input.ts](https://github.com/calcom/cal.com/pull/21626/files#diff-d5eeca66586516982c5f317b7c9e26284851e3bffd6032c51096d1e2c0c2392c) and in the [slots-input.service.ts](https://github.com/calcom/cal.com/pull/21626/files#diff-b13009a519718aba36fa51f007ce9a3b904b2bb1571ac45f57866f4bf06ea67a) have:
```
rescheduleUid: query.bookingUidToReschedule || null,
```

File: apps/api/v2/src/modules/slots/slots-2024-09-04/controllers/slots.controller.ts [hunk 2]
```diff
@@ -173,6 +174,13 @@ export class SlotsController_2024_09_04 {
...
+    required: false,
+    description:
+      "The unique identifier of the booking being rescheduled. When provided, allows showing availability for rescheduling an existing booking by excluding the original booking's time slot from busy time calculations. This ensures that the original booking time appears as available when rescheduling.",
```
Comment (supalarry) [inline apps/api/v2/src/modules/slots/slots-2024-09-04/controllers/slots.controller.ts]: I think we can shorten it - people care about the outcome more:
```
The unique identifier of the booking being rescheduled. When provided will ensure that the original booking time appears within the returned available slots when rescheduling.
```

File: apps/api/v2/src/modules/slots/slots-2024-09-04/controllers/e2e/reschedule-uid-slots.controller.e2e-spec.ts [hunk 3]
```diff
@@ -0,0 +1,344 @@
...
+          slug: `reschedule-uid-event-type-${randomString()}`,
+          length: 60,
+        },
+        user.id
+      );
+      eventTypeId = event.id;
+      eventTypeSlug = event.slug;
+
+      // Create an existing booking that will be used for reschedule testing
+      const bookedStartTime = "2050-09-05T11:00:00.000Z";
```
Comment (supalarry) [inline apps/api/v2/src/modules/slots/slots-2024-09-04/controllers/e2e/reschedule-uid-slots.controller.e2e-spec.ts]: We can put `const bookedStartTime` more up on the level where we define `let user: User;` so that tests below dont have to hardcode `2050-09-05T11:00:00.000Z` but instead can re-use the variable `bookedStartTime`.

**Review by supalarry — CHANGES_REQUESTED** [review]
Great job! Thank you for the contribution and great job on the tests!

I have left couple small comments below. Let me know what you think.

**Comment by weknowyourgame** [comment]
@supalarry Thanks!
I've made the requested changes. Let me know if there's anything else you'd like me to change.

**Review by supalarry — APPROVED** [review]
Great work! Amazing tests and thank you for the contribution! : )

**Comment by weknowyourgame** [comment]
Hey @hbjORbj 
Are the test failures related to the changes I made? 
just noticed all the failures are in team event type management APIs (organizations-event-types.e2e-spec.ts)

**Comment by Devanshusharma2005** [comment]
> Hey @hbjORbj Are the test failures related to the changes I made? just noticed all the failures are in team event type management APIs (organizations-event-types.e2e-spec.ts)

they are v2 test, try to fix them.

**Comment by weknowyourgame** [comment]
@Devanshusharma2005 sometimes tests fail randomly 
i just updated the branch to re run tests 
passed now!

**Comment by weknowyourgame** [comment]
Thank you @keithwillcode ! Really appreciate it :)

**Comment by Devanshusharma2005** [comment]
> @Devanshusharma2005 sometimes tests fail randomly i just updated the branch to re run tests passed now!

thank you @weknowyourgame, will remember this.
