### PR TITLE
fix: It's hard to click on the last available Event Duration

### LINKED ISSUE #18459: [CAL-4967] It's hard to click on the last available Event Duration
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I got a client complaining that is hard to click on the largest available time slot for [my calendar](https://cal.com/wesleycoder/coffee).
I took the time to dig a bit and found that It should be easy to fix.

### Steps to Reproduce

1. Prepare a booking page with multiple event durations (5 or more)
2. Go to booking page
3. The last duration in the EventDuration field can not be selected easily.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- What's happening right now that is different from what is expected
The right arrow button stays at the top and doesn't allow us to select the last duration besides having a few pixels worth of clicable area.

### Expected Results

- This is an ideal result that the system should get after the tests are performed
We should be able to select the last duration easily even when we have a larger set of items (>5).

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
Arc on MacOS
- Node.js version
N/A
- Anything else that you think could be an issue.

I've noted that there is an implementation to handle the [right arrow becoming hidden](https://github.com/calcom/cal.com/blob/170feeae5e8eab500f5aa106c791983363bd6458/packages/ui/components/apps/AllApps.tsx#L42) when we reach the end of the list, but it seems not to work for some reason, while the left arrow logic works.
I made a local attempt by just increasing the `ul` right padding to `pr-6` and that made it possible to select.
I was making a PR for that but I believe the intended way would be to revise the scroll handling logic If I understood correctly.

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

https://github.com/user-attachments/assets/cb8ea1c4-ab28-43a9-b649-8887988b4a50

<sub>[CAL-4967](https://linear.app/calcom/issue/CAL-4967/its-hard-to-click-on-the-last-available-event-duration)</sub>

### PR DESCRIPTION
**Pull request by Amit91848**
## What does this PR do?

- Fixes #18459 (GitHub issue number)
- Fixes CAL-4967 (Linear issue number - should be visible at the bottom of the GitHub issue description)
/claim #18459

https://github.com/user-attachments/assets/a821b50d-81bb-4e6b-ba62-33b093ad6ba4

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

### CODE REVIEW

File: packages/ui/components/apps/AllApps.tsx [hunk 1]
```diff
@@ -32,14 +32,14 @@ export function useShouldShowArrows() {
         right: !isAtEnd,
       });
     }
-  }, []);
+  }, [ref.current?.scrollWidth, ref.current?.clientWidth]);
```
Comment (Amit91848) [inline packages/ui/components/apps/AllApps.tsx:35]: Also fixed another issue where arrows are not shown on initial page load unless you explicitly click on a duration and it scrolls


https://github.com/user-attachments/assets/8eecf339-ebc6-4f75-8aba-1821004bf122

**Review by anikdhabal — APPROVED** [review]
