### PR TITLE
fixed icon on booking page for link locations

### LINKED ISSUE #5632: link location wrong icon and doenst need a tool tip
CleanShot 2022-11-22 at 10 59 31@2x

### PR DESCRIPTION
**Pull request by PeerRich**
before
CleanShot 2022-11-22 at 11 36 41@2x

after
CleanShot 2022-11-22 at 11 36 01@2x

### CODE REVIEW

File: apps/web/components/booking/AvailableEventLocations.tsx [hunk 1]
```diff
@@ -15,14 +16,18 @@ export function AvailableEventLocations({ locations }: { locations: Props["event
...
-            <img
-              src={eventLocationType.iconUrl}
-              className={classNames(
-                "mr-[10px] ml-[2px] h-4 w-4 opacity-70 dark:opacity-100 ",
-                !eventLocationType.iconUrl?.includes("api") ? "dark:invert" : ""
-              )}
-              alt={`${eventLocationType.label} icon`}
-            />
+            {eventLocationType.iconUrl === "/link.svg" ? (
+              <Icon.FiLink className="dark:text-darkgray-600 mr-[10px] ml-[2px] h-4 w-4 opacity-70 dark:opacity-100 " />
```
Comment (PeerRich) [inline apps/web/components/booking/AvailableEventLocations.tsx:20]: had to introduce a component here because of dark mode

**Review by sean-brydon — APPROVED** [review]
