### PR TITLE
fix: Added relevant colors to preset and replaced with tailwind colors

### LINKED ISSUE #9507: [CAL-1943] [UI] - Implement checkbox design
For some reason our checkbox seems to use the default tailwind form colours

Figma : [Here](https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/Cal-DS---Components?type=design&node-id=381-25547)

We ideally have a

* Checkbox Field component
* Single Checkbox

Please update storybook if needed

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1943](https://linear.app/calcom/issue/CAL-1943/[ui]-implement-checkbox-design)</sub>

### PR DESCRIPTION
**Pull request by JaideepGuntupalli**
## What does this PR do?

I have added relevant colors to the tailwind preset which weren't present. Then I have updated the tailwind default colors to custom colors. Also fixed some focus state issues.

Fixes #9507 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Since I have updated the storybook too, you can go to the checkbox story to check the new added colors.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: packages/ui/components/form/checkbox/Checkbox.tsx [hunk 1]
```diff
@@ -56,11 +56,12 @@ const CheckboxField = forwardRef<HTMLInputElement, Props>(
                     disabled={disabled}
                     id={rest.id ? rest.id : id}
                     className={classNames(
-                      "text-primary-600 focus:ring-primary-500 border-default bg-default h-4 w-4 rounded ltr:mr-2 rtl:ml-2",
+                      "text-primary-600 focus:ring-primary-500 border-default bg-default focus:bg-default active:bg-default h-4 w-4 rounded checked:hover:bg-gray-600 focus:outline-none focus:ring-0 ltr:mr-2 rtl:ml-2",
```
Comment (sean-brydon) [inline packages/ui/components/form/checkbox/Checkbox.tsx:59]: I know this wasnt in the design file i sent you 

But i wonder if it makes sense for us to use the users brand colour here. We do the same for buttons and switches so i think it could fit in quiet nicely. 

I'm happy to pick this up if you dont have time <3

**Review by sean-brydon — APPROVED** [review]
Looks good - Left a suggestion about brand colour but deffo not blocking

File: packages/ui/components/form/checkbox/Checkbox.tsx (hunk 1 above)
Comment (JaideepGuntupalli) [reply packages/ui/components/form/checkbox/Checkbox.tsx:59]: ok sure i will make these changes. Currently on road.
