### PR TITLE
Fix - add team members to emails

### LINKED ISSUE #6456: Insert all attendees into mail
### Issue Summary

I have a meeting type that needs to be confirmed before the meeting is booked. When someone books a meeting, I get a message in which I have to confirm the meeting - there are all participants incl. guests listed. when I confirm the appointment, I get a message in which participants are missing.

### Steps to Reproduce

1. book a meeting with guests
2. check messages

### PR DESCRIPTION
**Pull request by joeauyeung**
## What does this PR do?

This PR fixes a bug where team members were not included in the email and calendar bodies. This PR allows sending team emails to the member's set language.

image

image

Fixes #6456

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Create both a collective and a round-robin event
    - For the round-robin event, set a fixed host
    - For one of the team members to a different language
- For both event types do the following actions and ensure that the emails contain team members
    - Request booking
    - Create booking
    - Reschedule
    - Delete 

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/core/EventManager.ts [hunk 1]
```diff
@@ -255,8 +255,10 @@ export default class EventManager {
       results.push(result);
     }
 
-    // Update all calendar events.
-    results.push(...(await this.updateAllCalendarEvents(evt, booking)));
+    // If there is a calendar reference, update all calendar events.
+    if (booking.references.some((reference) => reference.type.includes("_calendar"))) {
+      results.push(...(await this.updateAllCalendarEvents(evt, booking)));
+    }
```
Comment (joeauyeung) [inline packages/core/EventManager.ts:261]: I'm hoping this will also fix some rescheduling bugs. If there were no calendar references this was still throwing an error

File: packages/emails/email-manager.ts [hunk 2]
```diff
@@ -22,10 +25,12 @@ import OrganizerRequestReminderEmail from "./templates/organizer-request-reminde
 import OrganizerRequestedToRescheduleEmail from "./templates/organizer-requested-to-reschedule-email";
 import OrganizerRescheduledEmail from "./templates/organizer-rescheduled-email";
 import OrganizerScheduledEmail from "./templates/organizer-scheduled-email";
-import TeamInviteEmail, { TeamInvite } from "./templates/team-invite-email";
+import type { TeamInvite } from "./templates/team-invite-email";
+import TeamInviteEmail from "./templates/team-invite-email";
 
 export const sendScheduledEmails = async (calEvent: CalendarEvent) => {
   const emailsToSend: Promise<unknown>[] = [];
+  const clonedEvent = cloneDeep(calEvent);
```
Comment (joeauyeung) [inline packages/emails/email-manager.ts:33]: Since we need to alter the attendee emails to hide attendees if needed. Let's clone the event to pass to the organizer emails

File: packages/emails/email-manager.ts [hunk 3]
```diff
@@ -43,19 +48,37 @@ export const sendScheduledEmails = async (calEvent: CalendarEvent) => {
...
       }
     })
   );
 
+  if (clonedEvent.team) {
+    for (const teamMember of clonedEvent.team.members) {
+      emailsToSend.push(
+        new Promise((resolve, reject) => {
+          try {
+            const scheduledEmail = new OrganizerScheduledEmail(clonedEvent, undefined, teamMember);
```
Comment (joeauyeung) [inline packages/emails/email-manager.ts:64]: By passing a team member, we can extract their locale and translation for the email

File: packages/emails/src/components/WhoInfo.tsx [hunk 4]
```diff
@@ -35,6 +35,14 @@ export function WhoInfo(props: { calEvent: CalendarEvent; t: TFunction }) {
...
             />
           ))}
+          {props.calEvent.team?.members.map((member) => (
+            <PersonInfo
+              key={member.id || member.name}
+              name={member.name}
+              role={t("team_member")}
+              email={member.email}
+            />
+          ))}
```
Comment (joeauyeung) [inline packages/emails/src/components/WhoInfo.tsx:45]: If there are team members, loop through and display in the email

File: packages/emails/src/templates/OrganizerScheduledEmail.tsx [hunk 5]
```diff
@@ -26,10 +27,10 @@ export const OrganizerScheduledEmail = (
     title = "new_event_scheduled";
   }
 
-  const t = props.calEvent.organizer.language.translate;
+  const t = props.teamMember?.language.translate || props.calEvent.organizer.language.translate;
   return (
     <BaseScheduledEmail
-      timeZone={props.calEvent.organizer.timeZone}
+      timeZone={props.teamMember?.timeZone || props.calEvent.organizer.timeZone}
```
Comment (joeauyeung) [inline packages/emails/src/templates/OrganizerScheduledEmail.tsx:33]: By passing the team member we can personalize the language and time zone in the email

File: packages/emails/templates/attendee-scheduled-email.ts [hunk 6]
```diff
@@ -47,10 +48,18 @@ export default class AttendeeScheduledEmail extends BaseEmail {
...
+          name: attendee.name,
+          email: attendee.email,
+        })),
+        ...(this.calEvent.team?.members
+          ? this.calEvent.team?.members.map((member: Person) => ({
+              name: member.name,
+              email: member.email,
+            }))
+          : []),
+      ],
```
Comment (joeauyeung) [inline packages/emails/templates/attendee-scheduled-email.ts:62]: In the .ics file we just lump together attendees and team members

File: packages/features/bookings/lib/handleCancelBooking.ts [hunk 7]
```diff
@@ -76,6 +70,11 @@ async function handler(req: NextApiRequest & { userId?: number }) {
           price: true,
           currency: true,
           length: true,
+          hosts: {
+            select: {
+              user: true,
+            },
+          },
```
Comment (joeauyeung) [inline packages/features/bookings/lib/handleCancelBooking.ts:77]: Query for hosts to determine if the attendee is a part of the team

File: packages/features/bookings/lib/handleCancelBooking.ts [hunk 8]
```diff
@@ -120,8 +119,12 @@ async function handler(req: NextApiRequest & { userId?: number }) {
     },
   });
 
-  const attendeesListPromises = bookingToDelete.attendees.map(async (attendee) => {
-    return {
+  const teamMembersPromises = [];
+  const attendeesListPromises = [];
+  const hostsPresent = !!bookingToDelete.eventType?.hosts;
```
Comment (joeauyeung) [inline packages/features/bookings/lib/handleCancelBooking.ts:124]: If hosts are present then assume it is a team event

File: packages/features/bookings/lib/handleCancelBooking.ts [hunk 9]
```diff
@@ -120,8 +119,12 @@ async function handler(req: NextApiRequest & { userId?: number }) {
...
+
+  for (const attendee of bookingToDelete.attendees) {
+    const attendeeObject = {
```
Comment (joeauyeung) [inline packages/features/bookings/lib/handleCancelBooking.ts:127]: Since all team members are stored as attendees in the booking, we can create the attendee object now.

File: packages/features/bookings/lib/handleCancelBooking.ts [hunk 10]
```diff
@@ -157,7 +175,9 @@ async function handler(req: NextApiRequest & { userId?: number }) {
     location: bookingToDelete?.location,
     destinationCalendar: bookingToDelete?.destinationCalendar || bookingToDelete?.user.destinationCalendar,
     cancellationReason: cancellationReason,
+    ...(teamMembers && { team: { name: "", members: teamMembers } }),
```
Comment (joeauyeung) [inline packages/features/bookings/lib/handleCancelBooking.ts:178]: Team name isn't important here

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 11]
```diff
@@ -494,12 +495,23 @@ async function handler(req: NextApiRequest & { userId?: number | undefined }) {
...
   ];
-  const guests = (reqBody.guests || []).map((guest) => ({
-    email: guest,
-    name: "",
-    timeZone: reqBody.timeZone,
-    language: { translate: tGuests, locale: "en" },
-  }));
+
+  const guests = (reqBody.guests || []).reduce((guestArray, guest) => {
+    // If it's a team event, remove the team member from guests
```
Comment (joeauyeung) [inline packages/features/bookings/lib/handleNewBooking.ts:500]: On rescheduling, team members are stored as guests on the booking page. We need to remove them as guests and add them back as team members

**Review by joeauyeung — COMMENTED** [review]
This is a good fix for now but I think once we merge #6553 we can make this more efficient.

File: packages/emails/templates/organizer-scheduled-email.ts [hunk 12]
```diff
@@ -14,13 +15,15 @@ export default class OrganizerScheduledEmail extends BaseEmail {
   calEvent: CalendarEvent;
   t: TFunction;
   newSeat?: boolean;
+  teamMember?: Person;
 
-  constructor(calEvent: CalendarEvent, newSeat?: boolean) {
+  constructor(calEvent: CalendarEvent, newSeat?: boolean, teamMember?: Person) {
```
Comment (hariombalhara) [inline packages/emails/templates/organizer-scheduled-email.ts:20]: As there are 2 optional parameters now, it is highly recommended to use an object

```suggestion
  constructor({
  calEvent, 
  newSeat, 
  teamMember
  }:{
  calEvent: CalendarEvent, newSeat?: boolean, teamMember?: Person
  }) {
```

File: packages/core/EventManager.ts (hunk 1 above)
Comment (hariombalhara) [reply packages/core/EventManager.ts:261]: If `updateAllCalendarEvents` is supposed to have calendar references then instead of erroring shouldn't it ignore and early return? It seems hackish to do it outside of the fn when it's the functions requirement.

File: packages/core/builders/CalendarEvent/class.ts [hunk 13]
```diff
@@ -16,7 +16,7 @@ class CalendarEventClass implements CalendarEvent {
   organizer!: Person;
   attendees!: Person[];
   description?: string | null;
-  team?: { name: string; members: string[] };
+  team?: { name: string; members: Person[] };
```
Comment (hariombalhara) [inline packages/core/builders/CalendarEvent/class.ts:19]: Person has a lot of other props that we don't provide to `team.members`, so I think we should create another type for it. Maybe `TeamMember`. I quickly did it and it told me about a dead code branch.

We are accessing `member.id `which doesn't exist and thus member.name would be used always

File: packages/emails/email-manager.ts (hunk 2 above)
Comment (hariombalhara) [inline packages/emails/email-manager.ts:33]: Why are we cloning it? Asking because deepClone might be a bit slow plus require lodash.

File: packages/emails/email-manager.ts [hunk 14]
```diff
@@ -43,19 +48,37 @@ export const sendScheduledEmails = async (calEvent: CalendarEvent) => {
...
+            resolve(scheduledEmail.sendEmail());
+          } catch (e) {
+            reject(console.error("OrganizerScheduledEmail.sendEmail failed", e));
+          }
+        })
+      );
+    }
```
Comment (hariombalhara) [inline packages/emails/email-manager.ts:71]:
```suggestion
const sendMail = (prepare ) => {
  return new Promise((resolve, reject) => {
    try {
      const email = prepare();
      resolve(email.sendEmail());
    } catch (e) {
      reject(console.error("sendEmail failed", e));
    }
  });
};
      emailsToSend.push(sendMail(()=>new OrganizerScheduledEmail(clonedEvent, undefined, teamMember)))
```

File: packages/emails/email-manager.ts [hunk 15]
```diff
@@ -73,14 +96,29 @@ export const sendRescheduledEmails = async (calEvent: CalendarEvent) => {
...
+      emailsToSend.push(
+        new Promise((resolve, reject) => {
+          try {
+            const scheduledEmail = new OrganizerRescheduledEmail(clonedEvent, undefined, teamMember);
+            resolve(scheduledEmail.sendEmail());
+          } catch (e) {
+            reject(console.error("OrganizerRescheduledEmail.sendEmail failed", e));
+          }
+        })
+      );
```
Comment (hariombalhara) [inline packages/emails/email-manager.ts:118]:
```suggestion
emailsToSend.push(sendEmail(()=>new OrganizerRescheduledEmail(clonedEvent, undefined, teamMember)))
```

File: packages/emails/email-manager.ts [hunk 16]
```diff
@@ -118,14 +156,35 @@ export const sendScheduledSeatsEmails = async (
...
+  emailsToSend.push(
+    new Promise((resolve, reject) => {
+      try {
+        const organizerRequestEmail = new OrganizerRequestEmail(calEvent);
+        resolve(organizerRequestEmail.sendEmail());
+      } catch (e) {
+        reject(console.error("OrganizerRequestEmail.sendEmail failed", e));
+      }
+    })
+  );
```
Comment (hariombalhara) [inline packages/emails/email-manager.ts:170]:
```suggestion
 emailsToSend.push(sendEmail(()=>new OrganizerRequestEmail(calEvent)))
```

File: packages/emails/src/components/WhoInfo.tsx [hunk 17]
```diff
@@ -35,6 +35,14 @@ export function WhoInfo(props: { calEvent: CalendarEvent; t: TFunction }) {
               email={attendee.email}
             />
           ))}
+          {props.calEvent.team?.members.map((member) => (
```
Comment (hariombalhara) [inline packages/emails/src/components/WhoInfo.tsx:38]: I think we should show team members before attendees so that it is shown along with the organizer who is also a team member. All team members would be together.

File: packages/features/bookings/lib/handleCancelBooking.ts [hunk 18]
```diff
@@ -130,9 +133,24 @@ async function handler(req: NextApiRequest & { userId?: number }) {
...
       },
     };
-  });
+
+    // Check for the presence of hosts to determine if it is a team event type
+    if (hostsPresent) {
+      // If the attendee is a host then they are a team member
+      const teamMember = bookingToDelete.eventType?.hosts.some((host) => host.user.email === attendee.email);
+      if (teamMember) {
+        teamMembersPromises.push(attendeeObject);
```
Comment (hariombalhara) [inline packages/features/bookings/lib/handleCancelBooking.ts:142]: Why are these being considered promises?

**Review by hariombalhara — CHANGES_REQUESTED** [review]
Left somet comments

File: packages/emails/templates/organizer-scheduled-email.ts (hunk 12 above)
Comment (roae) [reply packages/emails/templates/organizer-scheduled-email.ts:20]: This form is easier for others to understand.

File: packages/emails/email-manager.ts (hunk 2 above)
Comment (joeauyeung) [reply packages/emails/email-manager.ts:33]: WIth the attendee emails, we sometimes have to filter `calEvent.attendees` when it is a seats booking and the organizer wants to hide other attendees from each other.

File: packages/core/EventManager.ts (hunk 1 above)
Comment (zomars) [reply packages/core/EventManager.ts:261]: Agreed with @hariombalhara. Let's find the root cause and fix it properly.

File: packages/core/EventManager.ts [hunk 19]
```diff
@@ -435,14 +437,14 @@ export default class EventManager {
   private async updateAllCalendarEvents(
     event: CalendarEvent,
     booking: PartialBooking
-  ): Promise<Array<EventResult<NewCalendarEventType>>> {
+  ): Promise<Array<EventResult<NewCalendarEventType>> | []> {
```
Comment (zomars) [inline packages/core/EventManager.ts:440]:
```suggestion
  ): Promise<Array<EventResult<NewCalendarEventType>>> {
```

No need to update the signature. An empty array is a valid array for the current signature.

File: packages/emails/email-manager.ts (hunk 14 above)
Comment (joeauyeung) [reply packages/emails/email-manager.ts]: I really liked this idea so I created a separate PR #7270

File: packages/emails/src/components/WhoInfo.tsx (hunk 17 above)
Comment (joeauyeung) [reply packages/emails/src/components/WhoInfo.tsx]: https://github.com/calcom/cal.com/pull/7207/commits/25a3d97751ca3cbc0b6711aba0024b955404f7f9

File: packages/core/builders/CalendarEvent/class.ts (hunk 13 above)
Comment (joeauyeung) [reply packages/core/builders/CalendarEvent/class.ts:19]: https://github.com/calcom/cal.com/pull/7207/commits/5288feca7a182d3e1779124ed58e69e8a2151e68

File: packages/emails/templates/organizer-scheduled-email.ts (hunk 12 above)
Comment (joeauyeung) [reply packages/emails/templates/organizer-scheduled-email.ts]: https://github.com/calcom/cal.com/pull/7207/commits/8f3f17b2997ea67f1417be64e15ca4b71a736917

File: packages/features/bookings/lib/handleCancelBooking.ts (hunk 18 above)
Comment (joeauyeung) [reply packages/features/bookings/lib/handleCancelBooking.ts:142]: It's because `getTranslation` needs to run for each attendee object on line 132

**Comment by joeauyeung** [comment]
@hariombalhara implemented your type suggestions from #7270

File: packages/features/bookings/lib/handleCancelBooking.ts (hunk 18 above)
Comment (hariombalhara) [reply packages/features/bookings/lib/handleCancelBooking.ts:142]: Screenshot 2023-02-24 at 10 00 16 AM
I think there is some confusion. `attendeeObject` doesn't have any promise in it. By using await in front of `getTranslation` the result is already a resolved value.

File: packages/core/EventManager.ts (hunk 1 above)
Comment (hariombalhara) [reply packages/core/EventManager.ts:261]: @joeauyeung This one is still pending for merge.

File: packages/core/EventManager.ts [hunk 20]
```diff
@@ -255,7 +255,6 @@ export default class EventManager {
       results.push(result);
     }
 
-    // Update all calendar events.
     results.push(...(await this.updateAllCalendarEvents(evt, booking)));
```
Comment (joeauyeung) [inline packages/core/EventManager.ts:258]: No longer checking for calendar references here

File: packages/core/EventManager.ts [hunk 21]
```diff
@@ -442,7 +441,7 @@ export default class EventManager {
       // Bookings should only have one calendar reference
       calendarReference = booking.references.filter((reference) => reference.type.includes("_calendar"))[0];
       if (!calendarReference) {
-        throw new Error("bookingRef");
+        return [];
```
Comment (joeauyeung) [inline packages/core/EventManager.ts:444]: Instead of throwing an error if no calendar references, we just return an empty array

**Review by joeauyeung — COMMENTED** [review]
@hariombalhara fix for this comment

> If `updateAllCalendarEvents` is supposed to have calendar references then instead of erroring shouldn't it ignore and early return? It seems hackish to do it outside of the fn when it's the functions requirement.

**Review by zomars — APPROVED** [review]
LGTM

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 22]
```diff
@@ -539,7 +554,7 @@ async function handler(req: NextApiRequest & { userId?: number | undefined }) {
 
   const teamMembers = await Promise.all(teamMemberPromises);
 
-  const attendeesList = [...invitee, ...guests, ...teamMembers];
```
Comment (zomars) [inline packages/features/bookings/lib/handleNewBooking.ts:542]: This is causing collective events to not add all team members to the created calendar event.

Comment (joeauyeung) [reply packages/features/bookings/lib/handleNewBooking.ts:542]: In #7756 team members are added to the `attendeesList` on line 1442 before creating the booking in the DB & sending it to the event manager to create the calendar event. 

I tested this locally and the db record, email, and calendar event description have the team members included.

Comment (zomars) [reply packages/features/bookings/lib/handleNewBooking.ts:542]: Yeah, that data is not the same one being sent to the EventManager. It is passed directly to the DB only:

image
