### PR TITLE
fix: use LOGO_DARK constant for generic OG image instead of hardcoded value

### LINKED ISSUE #27355: [Bug] OG Image for "generic" type ignores custom LOGO constant, always shows Cal.com logo
### Issue Summary

Self-hosted Cal.com instances with custom logos display the Cal.com default logo instead of their custom logo on OG (Open Graph) images for "generic" type pages (login, generic pages, etc.). This is caused by the `generic` type in `OG_ASSETS` hardcoding `"cal-logo-word-black.svg"` instead of using the `LOGO` constant like `meeting` and `app` types do.

In `packages/lib/OgImages.tsx`:
- `meeting` type uses `LOGO` constant ✅
- `app` type uses `LOGO` constant ✅
- `generic` type hardcodes `"cal-logo-word-black.svg"` ❌

### Steps to Reproduce

1. Self-host Cal.com (Docker or any method)
2. Replace `/apps/web/public/logo.png` with a custom logo
3. Set `NEXT_PUBLIC_WEBAPP_URL` to your domain
4. Share a login page URL (e.g., `https://your-domain.com/auth/login`) on WhatsApp, Slack, or Mastodon
5. Observe that the OG image preview shows "Cal.com" logo instead of your custom logo
6. Compare with sharing a meeting booking page URL (e.g., `https://your-domain.com/username/30min`) which correctly shows the custom logo

### Actual Results

- Generic pages (login, etc.) show "Cal.com" branding in OG image previews on social media platforms
- Meeting booking pages correctly show the custom logo
- This creates inconsistent branding for self-hosted instances

### Expected Results

- All OG image types (meeting, app, generic) should use the custom logo defined in the `LOGO` constant
- Self-hosted instances should have consistent branding across all page types when shared on social media

### Technical details

- Cal.com version: 6.1.6 / 6.1.7
- Self-hosted on Docker (Debian 12)
- Node.js version: 20
- The `LOGO` constant is already imported at the top of `OgImages.tsx` and used correctly for `meeting` and `app` types

**Suggested fix** in `packages/lib/OgImages.tsx` line ~70:
```diff
  generic: {
    id: "generic-og-image-v1",
-   logo: "cal-logo-word-black.svg",
+   logo: LOGO,
    logoWidth: "350",
    variant: "light" as const,
  },
```

### Evidence

**Screenshot: WhatsApp preview of login page showing Cal.com logo instead of custom logo:**

Image

**OG image generated for generic type showing wrong logo:**

Image

**Code evidence - OG_ASSETS in packages/lib/OgImages.tsx:**
```typescript
const OG_ASSETS = {
  meeting: {
    logo: LOGO,  // ✅ Uses constant
    // ...
  },
  app: {
    logo: LOGO,  // ✅ Uses constant
    // ...
  },
  generic: {
    logo: "cal-logo-word-black.svg",  // ❌ Hardcoded - BUG
    // ...
  },
};
```

### PR DESCRIPTION
**Pull request by hbjORbj**
## What does this PR do?

- Fixes #27355

Self-hosted Cal.com instances display the default Cal.com logo on OG images for "generic" type pages (login, etc.) because the `generic` entry in `OG_ASSETS` hardcoded `"cal-logo-word-black.svg"` as a raw string instead of referencing a constant.

This PR:
1. Introduces a new `LOGO_DARK` constant in `packages/lib/constants.ts` pointing to `/cal-logo-word-black.svg` — preserving the darker logo for generic OG images on light backgrounds.
2. Updates `generic` in `OG_ASSETS` to use `LOGO_DARK ?? LOGO` instead of the hardcoded string, so the file reference is a discoverable, replaceable constant.
3. Adds 11 unit tests for the `OgImages` module covering `getOGImageVersion`, `constructMeetingImage`, `constructAppImage`, `constructGenericImage`, and branding consistency.

**Logo strategy per OG type:**
| Type | Logo constant | Default file | Background |
|---------|---------------|------------------------------|------------|
| meeting | `LOGO` | `calcom-logo-white-word.svg` | dark |
| app | `LOGO` | `calcom-logo-white-word.svg` | light |
| generic | `LOGO_DARK ?? LOGO` | `cal-logo-word-black.svg` | light |

Self-hosters who want full branding consistency should replace both `calcom-logo-white-word.svg` and `cal-logo-word-black.svg`.

## Visual Demo

To demonstrate the fix, `cal-logo-word-black.svg` (the file referenced by `LOGO_DARK`) was replaced with a custom logo to simulate a self-hosted instance.

#### Default generic OG image (no custom logo):

Default generic OG

#### After replacing `cal-logo-word-black.svg` with custom logo — generic OG picks up the change:

Generic OG with custom logo

#### Meeting OG remains unaffected (uses `LOGO`, not `LOGO_DARK`):

Meeting OG still uses LOGO

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). N/A
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

File: packages/lib/OgImages.tsx [hunk 1]
```diff
@@ -67,7 +67,7 @@ const OG_ASSETS = {
   },
   generic: {
     id: "generic-og-image-v1", // Bump version when changing Generic component structure/styling
-    logo: "cal-logo-word-black.svg",
+    logo: LOGO_DARK ?? LOGO, // Fallback approach because self-hosters might leave the dark logo empty.
```
Comment (eunjae-lee) [inline packages/lib/OgImages.tsx]: do you mean the possibility that self-hosters removing the value of LOGO_DARK in constants.ts? If they're touching the variable, they should be already mindful of checking its callers. So I think we don't even need a fallback. WDYT? 🤔

Comment (hbjORbj) [reply packages/lib/OgImages.tsx]: makes sense, removing!

**Review by eunjae-lee — APPROVED** [review]
