### PR TITLE
fix: no show webhook triggers not updating

### LINKED ISSUE #18955: [CAL-5092] Schedule webhook triggers for older bookings
After creating a webhook event, only bookings submitted **after** the webhook schedule will trigger the event. 

This means that bookings already scheduled for a future time but created **before** the webhook was set up will not be processed or recognized by the webhook.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-5092](https://linear.app/calcom/issue/CAL-5092/schedule-webhook-triggers-for-older-bookings)</sub>

### PR DESCRIPTION
**Pull request by kart1ka**
## What does this PR do?

The webhook triggers like Meeting Started and Meeting Ended are correctly updating for existing bookings when a webhook is created or updated. However, the No Show (Hosts/Guests) triggers were not being updated in the same way.
This PR fixes that issue.

- Fixes #18955 (GitHub issue number)
- Fixes CAL-5092 (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Visual Demo (For contributors especially)

Could not reproduce the bug for webhook triggers such as Meeting started and Meeting ended.
https://www.loom.com/share/393185653d73437ca95523267b53f961?sid=363c0f88-42c2-4c84-874d-3dcbb342035f

No show webhook triggers fixed:
https://www.loom.com/share/73a5f001faa64b5099072ef4e3e63ea4?sid=de73daec-169c-4ff6-bbed-0836708c7967

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

    

---

## Summary by mrge
Fixed an issue where No Show webhook triggers were not updating for existing bookings when a webhook was created or updated.

- **Bug Fixes**
  - No Show (Hosts/Guests) triggers now update correctly for existing bookings.
  - Canceling or rescheduling a booking now removes related No Show tasks.
  - Disabling a webhook now cancels all associated No Show tasks.

### CODE REVIEW

File: packages/features/webhooks/lib/scheduleTrigger.ts [hunk 1]
```diff
@@ -546,3 +578,82 @@ export async function listOOOEntries(
...
+      await tasker.cancelWithReference(bookingUid, "triggerHostNoShowWebhook");
+    } else if (triggerEvent === WebhookTriggerEvents.AFTER_GUESTS_CAL_VIDEO_NO_SHOW) {
+      await tasker.cancelWithReference(bookingUid, "triggerGuestNoShowWebhook");
+    } else {
+      await prisma.task.deleteMany({
+        where: {
+          referenceUid: bookingUid,
+        },
+      });
+    }
```
Comment (Udit-takkar) [inline packages/features/webhooks/lib/scheduleTrigger.ts:604]: Why is this needed?

File: packages/features/webhooks/lib/scheduleTrigger.ts [hunk 2]
```diff
@@ -546,3 +578,82 @@ export async function listOOOEntries(
...
+    const shouldContain = `"webhookId":"${webhookId}"`;
+
+    await prisma.task.deleteMany({
+      where: {
+        payload: {
+          contains: shouldContain,
+        },
+      },
+    });
+  }
```
Comment (Udit-takkar) [inline packages/features/webhooks/lib/scheduleTrigger.ts:615]: This would be very slow in production environment

File: packages/features/webhooks/lib/scheduleTrigger.ts [hunk 3]
```diff
@@ -546,3 +578,82 @@ export async function listOOOEntries(
...
+  if (!webhook.time || !webhook.timeUnit || !booking.startTime || !booking.location) return;
+
+  const isCalVideoLocation = booking.location === DailyLocationType || booking.location?.trim() === "";
+  if (!isCalVideoLocation) return;
+
+  if (
+    triggerEvent !== WebhookTriggerEvents.AFTER_HOSTS_CAL_VIDEO_NO_SHOW &&
+    triggerEvent !== WebhookTriggerEvents.AFTER_GUESTS_CAL_VIDEO_NO_SHOW
+  )
+    return;
```
Comment (Udit-takkar) [inline packages/features/webhooks/lib/scheduleTrigger.ts:632]: Should this be OR?

File: packages/features/bookings/lib/handleNewBooking/scheduleNoShowTriggers.ts [hunk 4]
```diff
@@ -93,7 +94,7 @@ const _scheduleNoShowTriggers = async (args: ScheduleNoShowTriggersArgs) => {
             // Prevents null values from being serialized
             webhook: { ...webhook, time: webhook.time, timeUnit: webhook.timeUnit },
           },
-          { scheduledAt }
+          { scheduledAt, referenceUid: booking.uid }
```
Comment (Udit-takkar) [inline packages/features/bookings/lib/handleNewBooking/scheduleNoShowTriggers.ts:97]: I saw that one of the task didn't had this `referenceUid` property set

**Review by Udit-takkar — DISMISSED** [review]
Left comments

File: packages/features/webhooks/lib/scheduleTrigger.ts (hunk 3 above)
Comment (kart1ka) [reply packages/features/webhooks/lib/scheduleTrigger.ts:644]: No. We are checking if the trigger is not the host no-show event and also not the guest no-show event → then return.

File: packages/features/webhooks/lib/scheduleTrigger.ts (hunk 2 above)
Comment (kart1ka) [reply packages/features/webhooks/lib/scheduleTrigger.ts]: Yeah, I had the same thought — but then I saw a similar pattern being used [here](https://github.com/calcom/cal.com/blob/bda963b851a0a8946b035caa3d4ad7b3022c48c7/packages/features/webhooks/lib/scheduleTrigger.ts#L352) so I went with that initially.

Anyway, I’ve updated the logic now to match how we handle it in `updateTriggerForExistingBookings`.

**Review by Udit-takkar — DISMISSED** [review]
LGTM

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 5]
```diff
@@ -2298,12 +2306,14 @@ async function handler(
       }
     }
 
-    await Promise.all([deleteWebhookScheduledTriggerPromise, ...scheduleTriggerPromises]).catch((error) => {
-      loggerWithEventDetails.error(
-        "Error while scheduling or canceling webhook triggers",
-        JSON.stringify({ error })
-      );
-    });
+    await Promise.all([...deleteWebhookScheduledTriggerPromises, ...scheduleTriggerPromises]).catch(
```
Comment (emrysal) [inline packages/features/bookings/lib/handleNewBooking.ts]: This should be an allSettled

Comment (kart1ka) [reply packages/features/bookings/lib/handleNewBooking.ts]: Done.

**Review by volnei — APPROVED** [review]
LGTM
