### PR TITLE
fix: Minimum fix for N Calendar Invites

### LINKED ISSUE #14580: [CAL-3412] a collective event of N people sends N invites
apparently the person booking receives N emails and N calendar invites

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3412](https://linear.app/calcom/issue/CAL-3412/a-collective-event-of-n-people-sends-n-invites)</sub>

### PR DESCRIPTION
**Pull request by joeauyeung**
## What does this PR do?

Right now attendees are being spammed by emails from the calendar provider because we were creating calendar events on EACH team member's calendars. So if we have 4 members in a collective event, we were creating 4 different calendar events and the attendee was receiving an email for each event.

This PR is a minimum fix for this bug by only creating one calendar event on the first destination calendar that appears. 

I tested this with a collective event and all team members are still on the single calendar event and is pointing to the  member's destination calendar.

We should follow up with the changes found in this PR https://github.com/calcom/cal.com/pull/14610 once tests are created for the `EventManager` class.

Fixes https://github.com/calcom/cal.com/issues/14580 Fixes CAL-3412 Fixes CAL-3468

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is a UI/UX design document, please, share it here.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Create a collective team event with each team member having Outlook as a destination calendar
- Create a booking under the collective event
- The attendee should receive one email from Outlook and all team members should be invited to the event

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

File: packages/core/EventManager.ts [hunk 1]
```diff
@@ -554,6 +555,7 @@ export default class EventManager {
         [] as DestinationCalendar[]
       );
       for (const destination of destinationCalendars) {
```
Comment (joeauyeung) [inline packages/core/EventManager.ts:557]: This `for ... of ` loop was the cause of creating multiple calendar events.

File: packages/core/EventManager.ts [hunk 2]
```diff
@@ -554,6 +555,7 @@ export default class EventManager {
...
+        if (eventCreated) break;
```
Comment (joeauyeung) [inline packages/core/EventManager.ts:558]: If a calendar event was created then set `eventCreated` to `true`. If the event was created on the first destination calendar then break out of the loop.

**Review by zomars — APPROVED** [review]
Way way clearer. Thanks a ton @joeauyeung 

Ship it
