### PR TITLE
fix: Set user's timezone as fallback to event's timezone

### LINKED ISSUE #16019: Issues with Booking limits
* In handleNewBooking we need to set the user's default schedule if eventType.schedule is null. More context here: [https://github.com/calcom/cal.com/pull/15825#discussion_r1698258149](https://github.com/calcom/cal.com/pull/15825#discussion_r1698258149)

### PR DESCRIPTION
**Pull request by Souptik2001**
## What does this PR do?

- Partially fixes #16019 

https://www.loom.com/share/29c3e7dec4844d1086402508e63c8f4c?sid=c30e795b-a884-43ed-99ba-52df87057633

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A- I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [x] N/A-I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

Please check the above video 👆

### CODE REVIEW

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 1]
```diff
@@ -294,7 +294,13 @@ async function handler(
     })
   );
 
-  const eventTimeZone = eventType.schedule?.timeZone ?? null;
+  const user = eventType.users.filter((user) => user.id === eventType.userId)[0];
+
+  const userSchedule = user.schedules.filter(
+    (schedule) => !user?.defaultScheduleId || schedule.id === user?.defaultScheduleId
+  )[0];
```
Comment (anikdhabal) [inline packages/features/bookings/lib/handleNewBooking.ts:301]: Using filter here is unnecessary; please use the `find` method instead.

**Review by anikdhabal — CHANGES_REQUESTED** [review]

File: packages/features/bookings/lib/handleNewBooking.ts (hunk 1 above)
Comment (Souptik2001) [reply packages/features/bookings/lib/handleNewBooking.ts]: Yes! Thanks @anikdhabal !

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 2]
```diff
@@ -325,10 +331,14 @@ async function handler(
...
-      message: `EventType '${eventType.eventName}' cannot be booked at this time.`,
+      message: `EventType '${
+        eventType.eventName ? eventType.eventName : eventType.title
+      }' cannot be booked at this time.`,
     };
     loggerWithEventDetails.warn({
-      message: `NewBooking: EventType '${eventType.eventName}' cannot be booked at this time.`,
+      message: `NewBooking: EventType '${
+        eventType.eventName ? eventType.eventName : eventType.title
+      }' cannot be booked at this time.`,
```
[the remark this answers is not in the document]
Comment (anikdhabal) [reply packages/features/bookings/lib/handleNewBooking.ts:341]: Hey @Souptik2001 pls remove these changes, it shouldn't be appropriate to show the event type tile instead of the event name

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 3]
```diff
@@ -294,7 +294,13 @@ async function handler(
     })
   );
 
-  const eventTimeZone = eventType.schedule?.timeZone ?? null;
+  const user = eventType.users.find((user) => user.id === eventType.userId);
+
+  const userSchedule = user?.schedules.find(
+    (schedule) => !user?.defaultScheduleId || schedule.id === user?.defaultScheduleId
+  );
+
```
Comment (anikdhabal) [inline packages/features/bookings/lib/handleNewBooking.ts:302]: Why you add this check `!user?.defaultScheduleId`? it means that  defaultScheduleId is falsy, this part of the condition evaluates to true. I don't think it's needed. The task is to set user's default timezone as fallback. pls remove it

Comment (Souptik2001) [reply packages/features/bookings/lib/handleNewBooking.ts:302]: @anikdhabal It would mean that if user's default schedule ID is null (which in the first place is not possible), but still if it becomes possible, then it will just consider the first schedule of the user and it's timezone.

If we remove this condition, then suppose the default schedule ID of the user is null, then none of the schedule will be selected and we will not be able to retrieve the timezone.

Please let me know what do you think.

Comment (anikdhabal) [reply packages/features/bookings/lib/handleNewBooking.ts:302]: Yeah, I understand why you added this, but our task here is to set defaultscheduleid as the fallback. There is very little chance that both the event type schedule timezone and the user’s default schedule ID is null at the same time. Also, we don't want to set any of the user’s schedule timezones other than default. So for now, please remove it; we will think about it later.

Comment (Souptik2001) [reply packages/features/bookings/lib/handleNewBooking.ts]: Ok @anikdhabal ! Done! 👍

**Review by anikdhabal — APPROVED** [review]
LGTM !! thanks for you work @Souptik2001
