### PR TITLE
fix: use actual event duration mins for templated event names

### LINKED ISSUE #21261: The event duration variable on the event type name does not work when there are multiple durations. It will display the default duration of the event.
The event duration variable on the event type name does not work when there are multiple durations. It will display the default duration of the event.<br> This is a 25-minute duration:

### PR DESCRIPTION
**Pull request by jamiedavenport**
## What does this PR do?

- Fixes #21261

## Setup

CleanShot 2025-05-13 at 06 39 48@2x

- Event with multiple durations (`15` and `60` mins in the examples).
- Event with default duration (`15` mins in the examples).
- Event with name `Event Duration: {Event duration}`.

### Before

- Uses the default duration in the event name.

https://github.com/user-attachments/assets/1de6cc63-fd28-482c-9f2a-df91f4cfb29c

### After

- Uses the default actual duration in mins.

https://github.com/user-attachments/assets/a5d1489f-831b-4b78-bce7-38ea56f78979

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

### CODE REVIEW

**Comment by jamiedavenport** [comment]
Couple of points for discussion:

1. Does anyone know if we shouldn't just pass in the start and end dates to `getEventName` and always generate the accurate `{Event duration}` from the diff?
2. To support `{HOST/ATTENDEE}` (personally I'd love to understand the use-case for that and the adoption numbers) we have to use `getEventName` in a few places instead of relying on the stored title. Would it actually be better to store both the `hostTitle` (what `title` is already) and `attendeeTitle` in the DB?

**Comment by retrogtx** [comment]
Hey @jamiedavenport can you please add before and after for the PR? Thanks for the PR 🙏

**Comment by jamiedavenport** [comment]
Morning @retrogtx. Added before & after videos.

**Review by TusharBhatt1 — DISMISSED** [review]
LGTM

File: apps/web/modules/bookings/views/bookings-single-view.tsx [hunk 1]
```diff
@@ -236,14 +236,15 @@ export default function Success(props: PageProps) {
...
+
   const eventNameObject = {
     attendeeName: bookingInfo.responses.name as z.infer<typeof nameObjectSchema> | string,
     eventType: eventType.title,
     eventName: evtName,
     host: props.profile.name || "Nameless",
     location: location,
     bookingFields: bookingInfo.responses,
-    eventDuration: eventType.length,
+    eventDuration: dayjs(bookingInfo.endTime).diff(dayjs(bookingInfo.startTime), "minutes"),
```
Comment (emrysal) [inline apps/web/modules/bookings/views/bookings-single-view.tsx:247]:
```suggestion
    eventDuration: dayjs(bookingInfo.endTime).diff(bookingInfo.startTime, "minutes"),
```

Same for others.

Comment (TusharBhatt1) [reply apps/web/modules/bookings/views/bookings-single-view.tsx:247]: @jamiedavenport can you address it - rest IG it’s good to take ahead

**Review by TusharBhatt1 — APPROVED** [review]

**Review by emrysal — APPROVED** [review]

**Comment by emrysal** [comment]
LGTM! thank you @jamiedavenport
