### PR TITLE
fix: wrong reschedule link for an org member for a booking on event outside the org

### LINKED ISSUE #14832: [CAL-3599] Reschedule link in app is wrong for an org member if the booking happened for an event outside the organization.
Right now reschedule link is generated by using the organization of logged in user. It should actually use the organization of the event.

So a member of [i.cal.com](http://i.cal.com) when booking a regular user like john's 30min will get the URL as [app.cal.com/john/30min](http://app.cal.com/john/30min) instead of [i.cal.com/john/30min](http://i.cal.com/john/30min).

Steps:

1. Login as an acme org member
2. Book pro/30min
3. Go to /bookings page and find that booking
4. Try to reschedule

[Internal link](https://app.campsite.co/cal/posts/cp8wu4md6985#comment-id9x6pks98c6) that shows the issue in a Loom

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3599](https://linear.app/calcom/issue/CAL-3599/reschedule-link-in-app-is-wrong-for-an-org-member-if-the-booking)</sub>

### PR DESCRIPTION
**Pull request by kart1ka**
## What does this PR do?

- Fixes #14832 
- Fixes CAL-3599 (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected)
- [x] I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com)
- [ ] I have added or modified automated tests that prove my fix is effective or that my feature works (PRs might be rejected if logical changes are not properly tested)

## How should this be tested?

- Login as an acme org member
- Book pro/30min
- Go to /bookings page and find that booking
- Try to reschedule
- Correct reschedule link is shown

### CODE REVIEW

File: apps/web/components/booking/BookingListItem.tsx [hunk 1]
```diff
@@ -179,7 +178,7 @@ function BookingListItem(booking: BookingItemProps) {
           id: "reschedule",
           icon: "clock" as const,
           label: t("reschedule_booking"),
-          href: `${bookerUrl}/reschedule/${booking.uid}${
+          href: `${WEBAPP_URL}/reschedule/${booking.uid}${
```
Comment (Udit-takkar) [inline apps/web/components/booking/BookingListItem.tsx:181]: this probably won't work for organization booking urls

Comment (Udit-takkar) [reply apps/web/components/booking/BookingListItem.tsx:181]: because they have custom domains

Comment (kart1ka) [reply apps/web/components/booking/BookingListItem.tsx:181]: When the user visits `${WEBAPP_URL}/reschedule/...`, if the org booking url has custom domain, the user gets redirected to the appropriate org domain. See below Loom Link.

https://www.loom.com/share/06519395de4a498f9b822eb3ef64b04e?sid=5778459a-2995-441a-a794-c48128ff5598

**Comment by kart1ka** [comment]
Hi @hariombalhara @Udit-takkar 
Just wanted to check in on the status of this PR. Could you please review this PR. If there are any changes I need to make, please let me know.
Thanks!

File: apps/web/modules/bookings/views/bookings-single-view.test.tsx [hunk 2]
```diff
@@ -11,6 +11,13 @@ import { HeadSeo } from "@calcom/ui";
 
 import Success from "./bookings-single-view";
 
+vi.mock("@calcom/lib/constants", async () => {
+  return {
+    WEBAPP_URL: "http://localhost:3000",
+    APP_NAME: "Cal.com",
+  };
+});
+
```
Comment (Udit-takkar) [inline apps/web/modules/bookings/views/bookings-single-view.test.tsx:20]: WEBAPP_URL should be http://app.cal.local:3000 here

File: apps/web/components/booking/BookingListItem.tsx (hunk 1 above)
Comment (Udit-takkar) [reply apps/web/components/booking/BookingListItem.tsx:191]: Nope. just tested on prod and the original code works fine here

**Review by Udit-takkar — CHANGES_REQUESTED** [review]
We can't use WEBAPP_URL here


https://github.com/calcom/cal.com/assets/53316345/978c03c9-2519-459d-8737-3614c83e2ef0

File: apps/web/components/booking/BookingListItem.tsx (hunk 1 above)
Comment (hariombalhara) [reply apps/web/components/booking/BookingListItem.tsx:191]: Yeah. That is true only for the users that have been migrated.


So, a brand new org user won't have this behaviour for his bookings.

Comment (hariombalhara) [reply apps/web/components/booking/BookingListItem.tsx:191]: We would probably need to use `getBookerBaseUrl` that accepts organizationId and organizationId has to be derived from booking like this probably

https://github.com/calcom/cal.com/blob/c5b8ad89157beaceb7db65f7113f6e35fd2c3ef1/packages/features/bookings/lib/handleNewBooking.ts#L1612

**Review by hariombalhara — DISMISSED** [review]
@kart1ka Thanks for the PR 🙏

Left a comment suggesting what could be done to fix the issue properly.

**Comment by kart1ka** [comment]
> @kart1ka Thanks for the PR 🙏
> 
> Left a comment suggesting what could be done to fix the issue properly.

On it.

File: apps/web/modules/bookings/views/bookings-single-view.test.tsx (hunk 2 above)
Comment (kart1ka) [reply apps/web/modules/bookings/views/bookings-single-view.test.tsx]: Made the required changes.

**Comment by kart1ka** [comment]
Hi @hariombalhara 
I have made the changes as per the request. Please review and let me know if any other changes need to be made.

**Comment by kart1ka** [comment]
> We can't use WEBAPP_URL here
> 
>  Screen.Recording.2024-06-13.at.1.56.20.PM.mov

Fixed.

**Review by Udit-takkar — DISMISSED** [review]
LGTM. I'll wait for hariom's approval before merging

File: packages/trpc/server/routers/viewer/bookings/get.handler.ts [hunk 3]
```diff
@@ -391,11 +398,14 @@ export async function getBookings({
...
     })
-  ).map((booking) => {
+  ).map(async (booking) => {
     // If seats are enabled and the event is not set to show attendees, filter out attendees that are not the current user
     if (booking.seatsReferences.length && !booking.eventType?.seatsShowAttendees) {
       booking.attendees = booking.attendees.filter((attendee) => attendee.email === user.email);
     }
+    const bookerBaseUrl = booking.eventType?.team?.parentId
+      ? await getBookerBaseUrl(booking.eventType?.team?.parentId)
+      : await getBookerBaseUrl(booking.user?.movedToProfile?.organizationId ?? null);
```
Comment (hariombalhara) [inline packages/trpc/server/routers/viewer/bookings/get.handler.ts:408]: Let's abstract it out something like this
```suggestion
    const bookerBaseUrl = getBookerBaseUrl(getOrganizationIdOfBooking() ?? null);
```

File: apps/web/pages/reschedule/[uid].tsx [hunk 4]
```diff
@@ -130,7 +138,7 @@ export async function getServerSideProps(context: GetServerSidePropsContext) {
       ? `team/${eventType.team.slug}`
       : dynamicEventSlugRef
       ? booking.dynamicGroupSlugRef
-      : booking.user?.username || "rick" /* This shouldn't happen */
+      : booking.user?.movedToProfile?.username || booking.user?.username || "rick" /* This shouldn't happen */
```
Comment (hariombalhara) [inline apps/web/pages/reschedule/[uid].tsx:141]: It needs to be handled in a better way.

`movedToProfile.username` should always be accessible on org domain(like acme.cal.local) and `booking.user.username` should be accessed on non org domain(like app.cal.local).

So, earlier it seems that we were always accessing this route through `app.cal.com` due to which  it was always working.

But now, we have done a fix that causes `acme.cal.local` to be used for a reschedule of an org booking but there could be some existing links accessing the reschedule through app.cal.com which will get broken.


I think we should choose the redirect domain based on what we got.

So, if `user.movedToProfile.username` **is not nullish** and the request host is **not the org domain** then the redirect URL should be absolute using the org domain, else we just keep using the non-absolute URL for redirects. This is really important because `user.movedToProfile.username` only exists in org context which requires org domain.

**Review by hariombalhara — CHANGES_REQUESTED** [review]
@kart1ka Thanks for addressing the feedback. I have a found a potential bug in the code and suggested a way to handle it.

File: packages/trpc/server/routers/viewer/bookings/get.handler.ts (hunk 3 above)
Comment (kart1ka) [reply packages/trpc/server/routers/viewer/bookings/get.handler.ts]: Done

File: apps/web/pages/reschedule/[uid].tsx (hunk 4 above)
Comment (kart1ka) [reply apps/web/pages/reschedule/[uid].tsx:146]: Made the changes as per the request.

**Comment by kart1ka** [comment]
@hariombalhara I have made the changes as per the suggestion.

File: apps/web/pages/reschedule/[uid].tsx (hunk 4 above)
Comment (hariombalhara) [reply apps/web/pages/reschedule/[uid].tsx:146]: @kart1ka I found a few more issues with what I suggested and I am working on a different approach here 
https://github.com/calcom/cal.com/pull/15736

I will take care of fixing reschedule/[uid] endpoint as it has higher priority. 

I will take care of merging this PR after that.

File: apps/web/components/booking/BookingListItem.tsx [hunk 5]
```diff
@@ -183,7 +181,7 @@ function BookingListItem(booking: BookingItemProps) {
       id: "reschedule",
       icon: "clock" as const,
       label: t("reschedule_booking"),
-      href: `${bookerUrl}/reschedule/${booking.uid}${
+      href: `/reschedule/${booking.uid}${
```
Comment (hariombalhara) [inline apps/web/components/booking/BookingListItem.tsx:184]: We don't need to provide full URL now.

**Review by hariombalhara — APPROVED** [review]
