### PR TITLE
fix: backward compatibility for old cal rooms

### LINKED ISSUE #15608: [CAL-3988] Two record icon in cal video in some cases
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Go to any cal video room created before yesterday's release in which you are organizer 

Screenshot 2024-06-28 at 12 53 52 PM

Affected users:-
- only organizer of the cal video meeting rooms created before 4.2.3 release 

### Expected Results

- This is an ideal result that the system should get after the tests are performed

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence

<sub>[CAL-3988](https://linear.app/calcom/issue/CAL-3988/two-record-icon-in-cal-video-in-some-cases)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

- Fixes https://github.com/calcom/cal.com/issues/15608
- Fixes CAL-3988 (Linear issue number - should be visible at the bottom of the GitHub issue description)

Backward compatibility

- As previously created meeting token for organizer doesn't have `enable_recording_ui: false` set https://github.com/calcom/cal.com/pull/15588/files#r1657094882 so it display recording ui button as well as custom tray recording button.

https://github.com/calcom/cal.com/assets/53316345/53a65838-99ee-492c-8b4e-b0c64a730f46

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x]  N/A I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [x]  N/A I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

File: packages/app-store/dailyvideo/lib/VideoApiAdapter.ts [hunk 1]
```diff
@@ -116,6 +116,38 @@ export const generateGuestMeetingTokenFromOwnerMeetingToken = async (meetingToke
...
+
+  // Update the meetingPassword in the database
+  await prisma.bookingReference.update({
+    where: {
+      id: bookingReferenceId,
+    },
+    data: {
+      meetingPassword: organizerMeetingToken.token,
+    },
+  });
```
Comment (Udit-takkar) [inline packages/app-store/dailyvideo/lib/VideoApiAdapter.ts:146]: update the token so we don't have to generate it every time

**Review by sean-brydon — APPROVED** [review]
Good catch! 

Code looks good to me - wasnt 100% sure how to create old cal rooms but tested new ones and it seemed to work fine
