### PR TITLE
fix: multiple bookings created on verify-email

### LINKED ISSUE #12860: [CAL-2828] Multiple events are created
### Issue Summary

Some settings lead to multiple bookings getting created.

### Steps to Reproduce

1. Setup an event with "Require booker email verification" toggled true
2. Enable "Requires confirmation" with the setting "always"
3. Schedule an event

### Actual Results

* Multiple bookings are created

### Expected Results

* Only one event should be created

### Technical details

Tested on Arc Browser.

image

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2828](https://linear.app/calcom/issue/CAL-2828/multiple-events-are-created)</sub>

### PR DESCRIPTION
**Pull request by ibex088**
## What does this PR do?

Fixes #12860

## Before

[Screencast from 19-12-23 11:53:48 AM IST.webm](https://github.com/calcom/cal.com/assets/32706411/1453728c-121b-4b14-aa16-efd66d41e7ea)

## After

[Screencast from 19-12-23 11:56:03 AM IST.webm](https://github.com/calcom/cal.com/assets/32706411/797cf489-ac3a-4bda-a3e2-9842abc8952f)

### CODE REVIEW

File: packages/features/bookings/components/VerifyCodeDialog.tsx [hunk 1]
```diff
@@ -25,6 +25,7 @@ export const VerifyCodeDialog = ({
   const [isLoading, setIsLoading] = useState(false);
   const [error, setError] = useState("");
   const [value, setValue] = useState("");
+  const [hasVerified, setHasVerified] = useState(false);
```
Comment (SomayChauhan) [inline packages/features/bookings/components/VerifyCodeDialog.tsx:28]: the reason for multiple bookings was that verifyCode was being called multipe times, so create a flag and setting it to true once the function has been visited

**Review by CarinaWolli — APPROVED** [review]
Tested and works, nice fix 👏🏻
