### PR TITLE
fix mapping for cancel webhook (#1554)

### LINKED ISSUE #1554: BOOKING_CANCELLED webhook has different payload values (`type`, `startTime`, `endTime`)
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue. This needs to be a clear detailed-rich summary.

### Steps to Reproduce

1. Book an appointment (I only tested non secret, without metadata, prefilled email and name)
2. Cancel the booking by visiting the manage link in the email and click `Cancel`

BOOKING_CREATED Webhook:
```json
{
  "triggerEvent": "BOOKING_CREATED",
  "createdAt": "2022-01-18T21:19:23.298Z",
  "payload": {
    "type": "Secret Meeting",
    "title": "Secret Meeting between Colin Busch and email@example.com",
    "description": "",
    "startTime": "2022-01-28T00:00:00+01:00",
    "endTime": "2022-01-28T00:15:00+01:00",
    "organizer": {
      "name": "Colin Busch",
      "email": "email@example.com",
      "timeZone": "Europe/London"
    },
    "attendees": [
      {
        "email": "email@example.com",
        "name": "email@example.com",
        "timeZone": "Europe/Berlin"
      }
    ],
    "location": "",
    "destinationCalendar": {
      "id": <number>,
      "integration": "apple_calendar",
      "externalId": "https://caldav.icloud.com/<number>/calendars/home/",
      "userId": <number>,
      "bookingId": null,
      "eventTypeId": null
    },
    "uid": "kMQepS4DCAAR17jtPMwq3B",
    "metadata": {}
  }
}
```

BOOKING_CANCELLED Webhook:
```json
{
  "triggerEvent": "BOOKING_CANCELLED",
  "createdAt": "2022-01-18T21:20:41.610Z",
  "payload": {
    "type": "Secret Meeting between Colin Busch and email@example.com",
    "title": "Secret Meeting between Colin Busch and email@example.com",
    "description": "",
    "startTime": "Thu Jan 27 2022 23:00:00 GMT+0000 (Coordinated Universal Time)",
    "endTime": "Thu Jan 27 2022 23:15:00 GMT+0000 (Coordinated Universal Time)",
    "organizer": {
      "email": "email@example.com",
      "name": "Colin Busch",
      "timeZone": "Europe/London"
    },
    "attendees": [
      {
        "name": "email@example.com",
        "email": "email@example.com",
        "timeZone": "Europe/Berlin"
      }
    ],
    "uid": "kMQepS4DCAAR17jtPMwq3B",
    "location": "",
    "destinationCalendar": {
      "id": <number>,
      "integration": "apple_calendar",
      "externalId": "https://caldav.icloud.com/<number>/calendars/home/",
      "userId": <number>,
      "bookingId": null,
      "eventTypeId": null
    }
  }
}
```

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

It seems like `type` is used for `title` in the Cancel webhook:
A:
```json
"type": "Secret Meeting",
"title": "Secret Meeting between Colin Busch and email@example.com",
```

B:
```json
"type": "Secret Meeting between Colin Busch and email@example.com",
"title": "Secret Meeting between Colin Busch and email@example.com",
```

Also very strange ist the different Format of the two dates:
A:
```json
"startTime": "Thu Jan 27 2022 23:00:00 GMT+0000 (Coordinated Universal Time)",
"endTime": "Thu Jan 27 2022 23:15:00 GMT+0000 (Coordinated Universal Time)",
```
B:
```json
"startTime": "2022-01-28T00:00:00+01:00",
"endTime": "2022-01-28T00:15:00+01:00",
```

### Technical details

- [Browser version:](https://www.whatsmybrowser.org/b/OQ7GJ)
- Node.js version: none
- Anything else that you think could be an issue.

### PR DESCRIPTION
**Pull request by buschco**
## What does this PR do?

The mapping and date format was different for the CANCEL Webhook, so I aligned the payloads.

Fixes #1554 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [x] Test A
Book an appointment and cancel it. The weebhook payloads should both have the same `title`, `type`, `startTime` and `endTime`

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code and corrected any misspellings
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: pages/api/cancel.ts [hunk 1]
```diff
@@ -89,11 +89,11 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
   const t = await getTranslation(req.body.language ?? "en", "common");
 
   const evt: CalendarEvent = {
-    type: bookingToDelete?.title,
+    type: bookingToDelete?.type,
```
Comment (alishaz-polymath) [inline pages/api/cancel.ts:92]: `type: bookingToDelete?.eventType?.title as string,`

Comment (alishaz-polymath) [reply pages/api/cancel.ts:92]: Same for line 155

**Review by alishaz-polymath — CHANGES_REQUESTED** [review]
Needs changes as mentioned

File: pages/api/cancel.ts (hunk 1 above)
Comment (alishaz-polymath) [reply pages/api/cancel.ts:92]: add at line 61
```
      eventType: {
        select: {
          title: true,
        },
      },
```

Comment (alishaz-polymath) [reply pages/api/cancel.ts:92]:
```suggestion
    type: bookingToDelete?.eventType?.title as string,
```

Comment (alishaz-polymath) [reply pages/api/cancel.ts:92]: ^Same for line 155

**Review by alishaz-polymath — CHANGES_REQUESTED** [review]

**Comment by buschco** [comment]
@alishaz-polymath thanks for the review.

[I added the requested changes](307e6aaaa280f5f10b69a1712fc414c85a2e2840). Can you please have another look? 🙏

File: pages/api/cancel.ts [hunk 2]
```diff
@@ -89,11 +94,11 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
...
 
   const evt: CalendarEvent = {
-    type: bookingToDelete?.title,
     title: bookingToDelete?.title,
+    type: bookingToDelete?.eventType?.title as string,
     description: bookingToDelete?.description || "",
-    startTime: bookingToDelete?.startTime.toString(),
-    endTime: bookingToDelete?.endTime.toString(),
+    startTime: bookingToDelete?.startTime.toISOString(),
+    endTime: bookingToDelete?.endTime.toISOString(),
```
Comment (alishaz-polymath) [inline pages/api/cancel.ts:101]: toISOString returns something of the format as :
`2022-01-21T09:00:00.000Z` and that isn't the desired outcome either. 
toString returns the following in my local test:
`Fri Jan 21 2022 14:00:00 GMT+0530 (India Standard Time)`
Which is the desired result. Hence, I'd suggest to explore this further and figure out why you're getting incorrect return for `startTime` and `endTime` on Cancel booking, as this is not the right solution yet, unless we standardize toISOString everywhere

**Review by alishaz-polymath — CHANGES_REQUESTED** [review]
Thank you for the changes. Can you please remove the `toISOString` changes and explore the reason behind incorrect/unexpected values of `startTime` & `endTime` if possible, as that would be the way to go in my opinion.

File: pages/api/cancel.ts (hunk 2 above)
Comment (buschco) [reply pages/api/cancel.ts:101]: Makes sense 💡 

By testing i figured, the reschedule and create and reschedule webhook, where in the `2022-01-21T09:00:00.000Z` (iso) format.
Now, knowing that create and reschedule, are the same place, the exception could also be in the creation rescheduling route. 

If you wish  `toString` (`Fri Jan 21 2022 14:00:00 GMT+0530 (India Standard Time)`) "everywhere", I can change https://github.com/calendso/calendso/blob/main/pages/api/book/event.ts#L298-L299 to match the format:
```
    startTime: new Date(reqBody.start).toString(),
    endTime: new Date(reqBody.end).toString(),
```

Do you think this change is quite safe?

Comment (alishaz-polymath) [reply pages/api/cancel.ts:101]: Hmm... Nice catch... In that case, I think toISOString change at `cancel` should be fine here. The different dates mentioned in the issue report is flipped (i know right?) which is why I was confused as to what's going on. I think toISOString at cancel webhook is actually the right way to go, sorry about the confusion

**Review by alishaz-polymath — APPROVED** [review]
Looks good now. Thanks for the PR :)

File: pages/api/cancel.ts (hunk 2 above)
Comment (buschco) [reply pages/api/cancel.ts:101]: Sorry if i confused you. Just to clarify, my goal is to have the same format for all webhooks:

Before PR:
```
  "triggerEvent": "BOOKING_CREATED", // or "BOOKING_RESCHEDULED"
  "payload": {
    "startTime": "2022-01-28T00:00:00+01:00",
    "endTime": "2022-01-28T00:15:00+01:00",
```
```
  "triggerEvent": "BOOKING_CANCELLED",
  "payload": {
    "startTime": "Thu Jan 27 2022 23:00:00 GMT+0000 (Coordinated Universal Time)",
    "endTime": "Thu Jan 27 2022 23:15:00 GMT+0000 (Coordinated Universal Time)",
```
With this PR:
```
  "triggerEvent": "BOOKING_CREATED", // or "BOOKING_RESCHEDULED"
  "payload": {
    "startTime": "2022-01-28T00:00:00+01:00",
    "endTime": "2022-01-28T00:15:00+01:00",
```
```
  "triggerEvent": "BOOKING_CANCELLED",
  "payload": {
    "startTime": "2022-01-28T00:00:00+01:00",
    "endTime": "2022-01-28T00:15:00+01:00",
```

---

But I think `bookingToDelete?.endTime.toISOString()` is indeed not right here, because it would remove the offset. Instead `dayjs(bookingToDelete?.endTime).format()` will format it correctly:

```
dayjs().format()         // "2022-01-21T12:22:16+01:00"
new Date().toISOString() // "2022-01-21T12:22:16.889Z"
```

Sorry for possible further confusion 🙈
I will change it, so it will use the `dayjs` - `format`ters format, like so:

```suggestion
    startTime: bookingToDelete?.startTime ? dayjs(bookingToDelete.startTime).format() : undefined,
    endTime: bookingToDelete?.endTime ? dayjs(bookingToDelete.endTime).format() : undefined,
```

Comment (alishaz-polymath) [reply pages/api/cancel.ts:101]: Sounds good!

Comment (alishaz-polymath) [reply pages/api/cancel.ts:101]: Once these changes are set, it should be good to go!

**Review by alishaz-polymath — CHANGES_REQUESTED** [review]

**Comment by buschco** [comment]
@alishaz-polymath Thank you 🙏 
After fighting with git (I am not used to fork an pull request) I found out that an [old version](https://github.com/calendso/calendso/commit/7737164bbff118b13fc897a540c2f04bf503ccb0) of my changes in this (#1556) PR where already merged into `calendso/calendso`'s `main` 😱 

Unfortunately the changes of https://github.com/calendso/calendso/pull/1557 are lost now. I reopen a new PR for these changes. -> https://github.com/calendso/calendso/pull/1584

This PR is now rebased and sqashed and can be merged.

I am really sorry. Opening a PR form `main` to `main` is not good 🙈

**Review by alishaz-polymath — APPROVED** [review]
