### PR TITLE
fix: bookings request reschedule UI badge

### LINKED ISSUE #7433: [CAL-1160] /bookings - Request reschedule UI notification is broken
Currently

Should be

**Make sure to use the existing badge component**

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1160](https://linear.app/calcom/issue/CAL-1160/bookings-request-reschedule-ui-notification-is-broken)</sub>

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

Fixes #7433 

things done in this PR
- [x] used `cva` for styling the Badge component
- [x] updated `size` prop to adhere to the design system
- [x] some type changes in the props
- [x] camel cased `StartIcon` prop  
- [x] fixed bookings request reschedule UI badge

after:
Screenshot 2023-02-28 at 22-41-20 Bookings Cal com

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/ui/components/badge/Badge.tsx [hunk 1]
```diff
@@ -1,62 +1,58 @@
...
 
 export const Badge = function Badge(props: BadgeProps) {
-  const {
-    variant = "default",
-    className,
-    size = "default",
-    rounded,
-    StartIcon,
-    withDot,
-    bold,
```
Comment (keithwillcode) [inline packages/ui/components/badge/Badge.tsx:40]: The `bold` prop got removed but there is still a caller using it in `[uid].tsx` (It's currently preventing the build from passing). Was the removal intentional and we can clean up that `bold` or do we need it still?

**Review by keithwillcode — COMMENTED** [review]
Changes look solid but we need to decide on the `bold` prop fix.

File: packages/ui/components/badge/Badge.tsx (hunk 1 above)
Comment (G3root) [reply packages/ui/components/badge/Badge.tsx:40]: > Changes look solid but we need to decide on the `bold` prop fix.

i think it's good to go by removing the bold prop because in the DS there isn't a variation with font weights. also fixed the build error.

cc: @calcom/ui

**Review by keithwillcode — APPROVED** [review]
Changes look good!

**Review by keithwillcode — APPROVED** [review]
