### PR TITLE
fix: remove mt

### LINKED ISSUE #3735: UI Bug: On /book page calendar icon isn't properly aligned with text
Alignment isn't correct for Calendar Icon with the text.
https://capture.dropbox.com/eujcPRTsyMeHMPTI

Sample page http://localhost:3000/free/book?type=14&date=2022-08-08T14%3A00%3A00%2B05%3A30&slug=30min&count=

### PR DESCRIPTION
**Pull request by Udit-takkar**
Fixes #3735 

Screenshot 2022-08-08 at 2 57 04 PM

### CODE REVIEW

File: apps/web/components/booking/pages/BookingPage.tsx [hunk 1]
```diff
@@ -608,7 +608,7 @@ const BookingPage = ({
                     {t("former_time")}
                   </p>
                   <p className="text-gray-500 line-through dark:text-white">
-                    <Icon.FiCalendar className="mr-[10px] ml-[2px] -mt-1 inline-block h-4 w-4 text-gray-400" />
+                    {/* <Icon.FiCalendar className="mr-[10px] ml-[2px] -mt-1 inline-block h-4 w-4 text-gray-400" /> */}
```
Comment (leog) [inline apps/web/components/booking/pages/BookingPage.tsx:611]: I was just wondering why you left out this icon here, maybe you forgot to uncomment?

**Review by leog — DISMISSED** [review]
Hey @Udit-takkar. Thanks again for contributing to this project! I left a comment before considering merging. Fix looks good!

File: apps/web/components/booking/pages/BookingPage.tsx (hunk 1 above)
Comment (Udit-takkar) [reply apps/web/components/booking/pages/BookingPage.tsx]: yeah fixed now. was just testing something

**Review by hariombalhara — APPROVED** [review]
