### PR TITLE
fix: switch bg when default checked

### LINKED ISSUE #8122: [CAL-1422] Checked switch sometimes wrong design
### Issue Summary

Sometimes the checked switch looks like that: 
Screenshot 2023-04-06 at 14 23 53

Should look like that: 
Screenshot 2023-04-06 at 14 28 03

For example in http://localhost:3000/settings/security/impersonation or http://localhost:3000/settings/developer/webhooks

It's because `props.checked` is undefined when `defaultChecked` is used like it is here: https://github.com/calcom/cal.com/blob/main/packages/features/webhooks/components/WebhookListItem.tsx#L79

<sub>[CAL-1422](https://linear.app/calcom/issue/CAL-1422/checked-switch-sometimes-wrong-design)</sub>

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

Fixes #8122 

after:
Screenshot 2023-04-06 at 22-05-13 Impersonation Cal com

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/ui/components/form/switch/Switch.tsx [hunk 1]
```diff
@@ -37,17 +37,17 @@ const Switch = (
         )}>
         <PrimitiveSwitch.Root
           className={cx(
-            props.checked ? "bg-inverted" : "bg-emphasis",
+            props.checked || props.defaultChecked ? "bg-inverted" : "bg-emphasis",
             primitiveProps.disabled && "cursor-not-allowed",
-            "focus:ring-brand-default h-5 w-[34px] rounded-full shadow-none",
+            "focus:ring-brand-default h-5 w-[34px] rounded-full shadow-none ",
```
Comment (emrysal) [inline packages/ui/components/form/switch/Switch.tsx:42]:
```suggestion
            "focus:ring-brand-default h-5 w-[34px] rounded-full shadow-none",
```

**Review by emrysal — APPROVED** [review]
