### PR TITLE
fix: Dynamic group booking  org-migration redirect

### LINKED ISSUE #13224: [CAL-2929] Dynamic Group Link - Org Migration Redirection support
app.cal.com/peer+bailey should redirect to i.cal.com/peer+bailey or i.cal.com/new-peer+new-bailey

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2929](https://linear.app/calcom/issue/CAL-2929/dynamic-group-link-org-migration-redirection-support)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #13224

- Fixes the issue where two users who are moved to an org has broken dynamic group booking links with old slugs.
So, for  teampro -> tpro-org1 and teamfree -> tfree-org1,  the old link app.cal.local:3000/teamfree+teampro would correctly redirect to org1.cal.local:3000/tfree-org1+tpro-org1

- Updated existing unit tests and added more.

## Demo
https://www.loom.com/share/55d2e364d8be448bb5115c6f8e54237b

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
1. Create org1
2. Migrate teampro -> tpro-org1 and teamfree -> tfree-org1
3. Access the old group booking link at app.cal.local:3000/teampro+teamfree and see that it correctly redirects to new usernames in org1.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by hariombalhara** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #13223** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/13223?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/calcom/cal.com/13223?utm_source=stack-comment).

File: apps/web/pages/[user].tsx [hunk 1]
```diff
@@ -318,7 +318,7 @@ export const getServerSideProps: GetServerSideProps<UserPageProps> = async (cont
   const isOrgContext = isValidOrgDomain && currentOrgDomain;
   const dataFetchStart = Date.now();
   let outOfOffice = false;
-
+  const isDynamicGroup = usernameList.length > 1;
```
Comment (hariombalhara) [inline apps/web/pages/[user].tsx:321]: This is consistent with [user]/[type] page now.

File: apps/web/pages/[user].tsx [hunk 2]
```diff
@@ -377,28 +400,6 @@ export const getServerSideProps: GetServerSideProps<UserPageProps> = async (cont
...
-      slug: usernameList[0],
-      redirectType: RedirectType.User,
-      eventTypeSlug: null,
-      currentQuery: context.query,
-    });
-
-    if (redirect) {
-      return redirect;
-    }
-  }
```
Comment (hariombalhara) [inline apps/web/pages/[user].tsx:400]: Moved it above users query.

File: apps/web/lib/getTemporaryOrgRedirect.ts [hunk 3]
```diff
@@ -7,45 +7,65 @@ import type { RedirectType } from "@calcom/prisma/client";
...
+  const currentQueryString = stringify(currentQuery);
+  if (!redirects.length) {
+    return null;
   }
-  return null;
+
+  // Use the first redirect origin as the new origin as we aren't supposed to handle different org usernames in a group
+  const newOrigin = new URL(redirects[0].toUrl).origin;
+  const query = currentQueryString ? `?${currentQueryString}` : "";
+  // Use the same order as in input slugs - It is important from Dynamic Group perspective as the first user's settings are used for various things
```
Comment (sean-brydon) [inline apps/web/lib/getTemporaryOrgRedirect.ts:49]: Nice spot 👨‍🍳

**Review by PeerRich — APPROVED** [review]
