### PR TITLE
fix: embed non-transparent dark background on success page

### LINKED ISSUE #9084: [CAL-1752] Dark instead of transparent background on success page in embed.
It would look really bad in an inline embed.
https://www.loom.com/share/da6707443dde43efb9f536ed4a7a612f

<sub>[CAL-1752](https://linear.app/calcom/issue/CAL-1752/dark-instead-of-transparent-background-on-success-page-in-embed)</sub>

### LINKED ISSUE #9173: [CAL-1678] color-scheme dark in embed when going from team events list to team event page.
The issue is that the query params aren't forwarded from listing to individual event page in case of teams.

Solution would be to use CalEmbed variable to get CalEmbedNamespace

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1678](https://linear.app/calcom/issue/CAL-1678/color-scheme-dark-in-embed-when-going-from-team-events-list-to-team)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Makes sure that embed is detected correctly on success page which would automatically remove color-scheme dark on that page.

Also, fixes a possible case of theme flicker.

Fixes #9084
Fixes #9173
Loom for [bug demo](https://www.loom.com/share/da6707443dde43efb9f536ed4a7a612f)

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

See [loom ](https://www.loom.com/share/99ceb5c699984a51aac418b3c6a3ae7b)

## Followup
- [ ] A testcase for this https://github.com/calcom/cal.com/issues/9086. Would pick it up on dedicated automation day.
## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: apps/web/components/Embed.tsx [hunk 1]
```diff
@@ -1133,12 +1133,7 @@ export const EmbedDialog = () => {
   const router = useRouter();
   const embedUrl: string = router.query.embedUrl as string;
   return (
-    <Dialog
-      name="embed"
-      clearQueryParamsOnClose={queryParamsForDialog}
-      onOpenChange={(open) => {
-        if (!open) window.resetEmbedStatus();
```
Comment (hariombalhara) [inline apps/web/components/Embed.tsx:1140]: `resetEmbedStatus` is not needed now as we haven't been using sessionStorage to detect embed mode. As sessionStorage was common for Embed Code Generator preview window and the app, it was to remove the side effect.

File: packages/embeds/embed-core/embed-iframe-init.ts [hunk 2]
```diff
@@ -1,34 +1,38 @@
...
-  /* Iframe Name */
-  window.name.includes("cal-embed");
+  // Namespace is initially set in query param `embed` but the query param might get lost during soft navigation
+  // So, we also check for the namespace in `window.name` which is set when iframe is created by embed.ts and persists for the duration of iframe's life
+  // Note that, window.name isn't lost during hard navigation as well. Though, hard navigation isn't something that would happen in the app, but it's critical to be able to detect embed mode even after that(just in case)
+  // We might just use window.name but if just in case something resets the `window.name`, we will still have the namespace in query param
+  const embedNamespace =
+    typeof embedNameSpaceFromQueryParam === "string"
+      ? embedNameSpaceFromQueryParam
+      : window.name.replace(/cal-embed=(.*)/, "$1").trim();
```
Comment (hariombalhara) [inline packages/embeds/embed-core/embed-iframe-init.ts:17]: It is set here https://github.com/calcom/cal.com/pull/9085/files#diff-e895c26df52266ecfd6334060b1dc6fa05cac4106eee7f713d0a07472cc08d07R218

File: packages/embeds/embed-core/embed-iframe-init.ts [hunk 3]
```diff
@@ -1,34 +1,38 @@
...
     const url = new URL(document.URL);
-    return url.searchParams.get("theme") as "light" | "dark" | null;
+    return url.searchParams.get("theme") as EmbedThemeConfig | null;
   };
 
   window.getEmbedNamespace = () => {
-    const url = new URL(document.URL);
-    const namespace = url.searchParams.get("embed");
-    return namespace;
+    return embedNamespace;
```
Comment (hariombalhara) [inline packages/embeds/embed-core/embed-iframe-init.ts:35]: Now namespace and embed mode are both derives from the same variable.

File: packages/embeds/embed-core/playground.ts [hunk 4]
```diff
@@ -1,14 +1,13 @@
...
-type A = GlobalCalWithoutNs;
 const Cal = window.Cal as GlobalCal;
 const callback = function (e) {
   const detail = e.detail;
   console.log("Event: ", e.type, detail);
 };
 
 const searchParams = new URL(document.URL).searchParams;
-const only = window.only;
+const only = searchParams.get("only");
```
Comment (hariombalhara) [inline packages/embeds/embed-core/playground.ts:10]: Get only param from here directly instead of relying on window.only which is set by playground index.html

File: packages/embeds/embed-core/src/embed-iframe.ts [hunk 5]
```diff
@@ -434,7 +434,7 @@ if (isBrowser) {
   // Exposes certain global variables/fns that are used by the app to get interface with the embed.
   embedInit();
   const url = new URL(document.URL);
-  embedStore.theme = window?.getEmbedTheme?.() as UiConfig["theme"];
+  embedStore.theme = window?.getEmbedTheme?.();
```
Comment (hariombalhara) [inline packages/embeds/embed-core/src/embed-iframe.ts:437]: Remove type assertion.

**Review by zomars — APPROVED** [review]
LGTM
