### PR TITLE
Fixes localisation of {EVENT_DATE} in workflows

### LINKED ISSUE #6733: [CAL-938] Localisation of {EVENT_DATE} in workflows
### Issue Summary

There is no localisation of {EVENT_DATE} variable in email / SMS workflows. All our users are French and they recieve email / SMS notifications in French with an event date in English. Examples below:
image
image

<sub>[CAL-938](https://linear.app/calcom/issue/CAL-938/localisation-of-event-date-in-workflows)</sub>

### PR DESCRIPTION
**Pull request by CarinaWolli**
## What does this PR do?

Adds correct translations of the dynamic text variable {EVENT_DATE} for custom workflow templates. The workflow actions 'send SMS to attendee' and 'send Email to attendee' are now using the attendee's language to translate the event date. 

Fixes #6733

German: 
Screenshot 2023-02-06 at 13 54 21

English:
Screenshot 2023-02-06 at 13 55 59

**Environment**: Staging(main branch) / Production

### CODE REVIEW

File: packages/trpc/server/routers/viewer/workflows.tsx [hunk 1]
```diff
@@ -903,72 +918,72 @@ export const workflowsRouter = router({
     }
 
     if (isSMSAction(step.action) /*|| step.action === WorkflowActions.EMAIL_ADDRESS*/ /*) {
-      const hasTeamPlan = (await ctx.prisma.membership.count({ where: { userId: user.id } })) > 0;
-      if (!hasTeamPlan) {
-        throw new TRPCError({ code: "UNAUTHORIZED", message: "Team plan needed" });
-      }
-    }
+const hasTeamPlan = (await ctx.prisma.membership.count({ where: { userId: user.id } })) > 0;
```
Comment (CarinaWolli) [inline packages/trpc/server/routers/viewer/workflows.tsx:921]: Nothing was changed in all these commented lines

File: packages/features/ee/workflows/lib/reminders/templates/customTemplate.ts [hunk 2]
```diff
@@ -17,7 +18,12 @@ export type VariablesType = {
 };
 
 const customTemplate = async (text: string, variables: VariablesType, locale: string) => {
-  const timeWithTimeZone = `${variables.eventTime?.locale(locale).format("HH:mm")} (${variables.timeZone})`;
+  const translate = await getTranslation(locale ?? "en", "common");
+  const day = translate(dayjs(variables.eventDate).format("dddd").toLowerCase());
```
Comment (emrysal) [inline packages/features/ee/workflows/lib/reminders/templates/customTemplate.ts:22]: I suggest using Intl instead of our own translations for weekdays/months 👍 - have a look at the booking page for examples of this

**Review by emrysal — CHANGES_REQUESTED** [review]

File: packages/features/ee/workflows/lib/reminders/templates/customTemplate.ts [hunk 3]
```diff
@@ -17,7 +17,14 @@ export type VariablesType = {
 };
 
 const customTemplate = async (text: string, variables: VariablesType, locale: string) => {
-  const timeWithTimeZone = `${variables.eventTime?.locale(locale).format("HH:mm")} (${variables.timeZone})`;
+  const translatedDate = new Intl.DateTimeFormat(locale, {
```
Comment (CarinaWolli) [inline packages/features/ee/workflows/lib/reminders/templates/customTemplate.ts:20]: using Intl now for date translations: 

English: 
Screenshot 2023-02-08 at 10 25 32

German:
Screenshot 2023-02-08 at 10 25 35

**Review by emrysal — APPROVED** [review]
Amazing!
