### PR TITLE
fix: v1 api payments endpoint fix

### LINKED ISSUE #9895: [CAL-2084] Payment API endpoint needs better error handling
Found a bug? Please fill out the sections below. 👍

### Issue Summary

Currently, we return a 404 suggesting a payment with the provided ID doesn't exist, however, it does exist. It is returned fine from within the /bookings endpoint.  The problem seems to be that there's another issue causing the failure but it is incorrectly categorized as a 404.

The example error report is here:

```
{
    "message": "Payment with id: 3185 not found",
    "error": {
        "issues": [
            {
                "code": "invalid_union",
                "unionErrors": [
                    {
                        "issues": [
                            {
                                "code": "invalid_union",
                                "unionErrors": [
                                    {
                                        "issues": [
                                            {
                                                "code": "invalid_type",
                                                "expected": "string",
                                                "received": "object",
                                                "path": [
                                                    "data"
                                                ],
                                                "message": "Expected string, received object"
                                            }
                                        ],
                                        "name": "ZodError"
                                    },
                                    {
                                        "issues": [
                                            {
                                                "code": "invalid_type",
                                                "expected": "number",
                                                "received": "object",
                                                "path": [
                                                    "data"
                                                ],
                                                "message": "Expected number, received object"
                                            }
                                        ],
                                        "name": "ZodError"
                                    },
                                    {
                                        "issues": [
                                            {
                                                "code": "invalid_type",
                                                "expected": "boolean",
                                                "received": "object",
                                                "path": [
                                                    "data"
                                                ],
                                                "message": "Expected boolean, received object"
                                            }
                                        ],
                                        "name": "ZodError"
                                    }
                                ],
                                "path": [
                                    "data"
                                ],
                                "message": "Invalid input"
                            }
                        ],
                        "name": "ZodError"
                    },
                    {
                        "issues": [
                            {
                                "code": "invalid_type",
                                "expected": "array",
                                "received": "object",
                                "path": [
                                    "data"
                                ],
                                "message": "Expected array, received object"
                            }
                        ],
                        "name": "ZodError"
                    },
.........
                ],
                "path": [
                    "data"
                ],
                "message": "Invalid input"
            }
        ],
        "name": "ZodError"
    }
}
```

### Steps to Reproduce

We can use the **Admin API key** and try:

1. Call the GET request on /v1/bookings/370788
This should contain the payment ID of 3188 in response.
2. Call the GET request on /v1/payments/3188
This would contain the aforementioned error. 

The similar pattern can be used for more bookings and payment IDs. From what I could see, pretty much any payment ID is returning this error, but if you put a number way down the line, the response body changes enough to be able to make out that that's the real 404 response body.

<sub>[CAL-2084](https://linear.app/calcom/issue/CAL-2084/payment-api-endpoint-needs-better-error-handling)</sub>

### PR DESCRIPTION
**Pull request by alishaz-polymath**
## What does this PR do?

Fixes our V1 Payment endpoint which showed a mountain of zod errors. The endpoint works after this fix with relevant data returned from the endpoints

- `api/v1/payments`
- `api/v1/payments[id]
`
- Fixes #9895 
- Fixes CAL-2084

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

Just check the two endpoints and they should return error free valid response

### CODE REVIEW

File: apps/api/v1/lib/validations/payment.ts [hunk 1]
```diff
@@ -1,5 +1,12 @@
 import { _PaymentModel as Payment } from "@calcom/prisma/zod";
 
-// FIXME: Payment seems a delicate endpoint, do we need to remove anything here?
-export const schemaPaymentBodyParams = Payment.omit({ id: true });
```
Comment (alishaz-polymath) [inline apps/api/v1/lib/validations/payment.ts:4]: There is no POST here, so we don't need this.

File: apps/api/v1/lib/validations/payment.ts [hunk 2]
```diff
@@ -1,5 +1,12 @@
...
+export const schemaPaymentPublic = Payment.pick({
+  id: true,
+  amount: true,
+  success: true,
+  refunded: true,
+  fee: true,
+  paymentOption: true,
+  currency: true,
+  bookingId: true,
+});
```
Comment (alishaz-polymath) [inline apps/api/v1/lib/validations/payment.ts:12]: Explicit properties pick

**Review by keithwillcode — APPROVED** [review]
