### PR TITLE
fix: rescheduled value DB update on reschedule and insights view cancelleds

### LINKED ISSUE #10486: Several bugs in insights
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I found bugs in the insights section. Today, I created two team meetings: one was scheduled, and the other was canceled. However, the insights section is showing that 2 events were created and 0 events were canceled.
Screenshot 2023-07-31 212150

Today is the 31st, but I noticed that the trace graph's end date varies when using different filters.
Screenshot 2023-07-31 211352

Screenshot 2023-07-31 211003

Screenshot 2023-07-31 210644

### Steps to Reproduce

1. Go to insights

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

- When rescheduling a non-seats booking we flag DB field reschedule = true
- Update BookingTimeStatus view with correct value for cancelled bookings.
- Add many insights test!

### CODE REVIEW

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 1]
```diff
@@ -2068,6 +2068,7 @@ async function handler(
           id: originalRescheduledBooking.id,
         },
         data: {
+          rescheduled: true,
```
Comment (alannnc) [inline packages/features/bookings/lib/handleNewBooking.ts:2071]: We here validate that the event type has no seats enabled.

File: packages/features/insights/filters/TeamAndSelfList.tsx [hunk 2]
```diff
@@ -22,6 +22,11 @@ export const TeamAndSelfList = () => {
   const { data, isSuccess } = trpc.viewer.insights.teamListForUser.useQuery(undefined, {
     // Teams don't change that frequently
     refetchOnWindowFocus: false,
+    trpc: {
+      context: {
+        skipBatch: true,
+      },
+    },
```
Comment (alannnc) [inline packages/features/insights/filters/TeamAndSelfList.tsx:29]: Skip batching since now we delay rendering everything waiting for this to end.

File: packages/prisma/migrations/20230921002822_fix_booking_time_status/migration.sql [hunk 3]
```diff
@@ -0,0 +1,35 @@
...
+    "Booking".location,
+    "Booking".paid,
+    "Booking".status,
+    "Booking".rescheduled,
+    "Booking"."userId",
+    "et"."teamId",
+	  "et"."length" as "eventLength",
+      CASE
+          WHEN "Booking".rescheduled IS TRUE THEN 'rescheduled'::text
+          WHEN "Booking".status = 'cancelled'::"BookingStatus" AND "Booking".rescheduled IS NULL THEN 'cancelled'::text
```
Comment (alannnc) [inline packages/prisma/migrations/20230921002822_fix_booking_time_status/migration.sql:24]: The main change here is we were looking for "Booking".rescheduled IS FALSE which was incorrect

Comment (alannnc) [reply packages/prisma/migrations/20230921002822_fix_booking_time_status/migration.sql:24]: Views need to be recreated since cannot be updated

File: apps/web/playwright/insights.e2e.ts [hunk 4]
```diff
@@ -0,0 +1,276 @@
...
+      .nth(1)
+      .click();
+    await page.waitForLoadState("networkidle");
+
+    // press escape button to close the filter
+    await page.keyboard.press("Escape");
+
+    await page.getByRole("button", { name: "Clear" }).click();
+
+    expect(page.url()).not.toContain("memberUserId=");
```
Comment (Udit-takkar) [inline apps/web/playwright/insights.e2e.ts:271]: @alannnc tests are failing probably because it takes some time for the url to update after clicking "Clear"

File: packages/prisma/migrations/20230921002822_fix_booking_time_status/migration.sql (hunk 3 above)
Comment (zomars) [reply packages/prisma/migrations/20230921002822_fix_booking_time_status/migration.sql:24]: Nice SQL-fu in here

Noice

**Review by zomars — CHANGES_REQUESTED** [review]
Blocking to fix tests first

**Review by zomars — APPROVED** [review]
Nice work @alannnc. Does the included test serves the purpose to prevent regression? And if not, can we add it in a follow up?

**Comment by alannnc** [comment]
> Nice work @alannnc. Does the included test serves the purpose to prevent regression? And if not, can we add it in a follow up?

@zomars Tests expect the frontend to work like it's meant to be. If regression happens test will complain now, we didn't have them when I implemented org changes here so we couldn't tell if something broke.
