### PR TITLE
fix: toggle alignment, spacing, square btn

### LINKED ISSUE #4273: /event-type-detail /advanced - multiple UI issues
- [ ] toggle alignment is off
- [ ] label spacing above select is off
- [ ] make the suffix on the input a square or remove that background altogether

Image

### PR DESCRIPTION
**Pull request by Udit-takkar**
Fixed: #4273 

Edit: Updated image

Screenshot 2022-09-08 at 6 19 42 PM

### CODE REVIEW

File: packages/ui/v2/core/form/fields.tsx [hunk 1]
```diff
@@ -204,11 +204,11 @@ const InputField = forwardRef<HTMLInputElement, InputFieldProps>(function InputF
               "h-9 border border-gray-300",
               addOnFilled && "bg-gray-100",
               addOnLeading && "rounded-l-md border-r-0",
-              addOnSuffix && "rounded-r-md border-l-0"
+              addOnSuffix && "border-l-0"
```
Comment (Udit-takkar) [inline packages/ui/v2/core/form/fields.tsx:207]: the field have to square everywhere right ?

**Comment by PeerRich** [comment]
hey @Udit-takkar, thank you!

https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS-v2.0?node-id=1413%3A66594


 the alignment of the switch doesn't seem right yet 

CleanShot 2022-09-08 at 13 52 00@2x

**Review by PeerRich — APPROVED** [review]
