### PR TITLE
fix: double bookings on seated event

### LINKED ISSUE #13360: [CAL-2996] Double bookings created on multi-seat events
### Issue Summary

A background to our use-case: We send out calcom links to our customers via email and they use those to book events with us.

This means we have multiple users receive the link at the same time which means there are multiple people opening the bookings page at roughly the same time.

If two users attempt to book a multi-seat at similar times then the first person gets their own booking and each person after that gets added to a second booking.

### Steps to Reproduce

1. Create a multi-seat event
2. Open two tabs of the booking page and select a timeslot but do not fully confirm yet.
3. The first person clicking on the slot does not see "5 / 5 Slots Left"
4. Confirm both bookings
5. Observe you will have 2 separate bookings. Each booking after the fact will be fine.

### Actual Results

* The first person booking gets a separate booking
* Each consecutive booking is added to the seats

### Expected Results

The booking page should be checking in the background to see if there is an existing bookingUID that it can use.

### Technical details

* You can observe the URLs to confirm.
* First person booking sees [booking.com/event/timeslot](http://booking.com/event/timeslot)
* Each person afterwards sees [booking.com/event/timeslot/bookingUID](http://booking.com/event/timeslot/bookingUID)
* So if multiple people click the timeslot at the same time then nobody will have a bookingUID in the URL

### Evidence

Event Page with seats enabled

1-event-page

2-double-booking

* Open two tabs
* Your URLs will look similar to this [http://localhost:3000/seats/seats-test?date=2024-01-22&month=2024-01&slot=2024-01-22T14%3A30%3A00.000Z](http://localhost:3000/seats/seats-test?date=2024-01-22&month=2024-01&slot=2024-01-22T14%3A30%3A00.000Z)
* Book the first tab
* Notice the second URL is still the same.
* Expecting the URL to update to [http://localhost:3000/seats/seats-test?date=2024-01-22&month=2024-01&slot=2024-01-22T14%3A30%3A00.000Z&bookingUid=iMoknvL9pcB8VxmiEu6z8B](http://localhost:3000/seats/seats-test?date=2024-01-22&month=2024-01&slot=2024-01-22T14%3A30%3A00.000Z&bookingUid=iMoknvL9pcB8VxmiEu6z8B)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2996](https://linear.app/calcom/issue/CAL-2996/double-bookings-created-on-multi-seat-events)</sub>

### PR DESCRIPTION
**Pull request by MehulZR**
## What does this PR do?

Fixes #13360  (issue)

https://github.com/calcom/cal.com/assets/86384652/f8ae01a2-9275-448f-8358-d3cbeec070b0

https://github.com/calcom/cal.com/assets/86384652/1066625e-021b-4c31-90b7-cb020413da26

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by joeauyeung — DISMISSED** [review]
Thanks for your contribution @MehulZR. I think this is a good case for when a wave of people are trying to sign up for a seated event.  

I don't think we should remove `reqBookingUid` as I'm not sure if this will break for self-hosters. I also added a test for a new attendee when `bookingUid` is not present in the request.

File: packages/features/bookings/lib/handleSeats/handleSeats.ts [hunk 1]
```diff
@@ -17,7 +17,6 @@ const handleSeats = async (newSeatedBookingObject: NewSeatedBookingObject) => {
     eventType,
     reqBodyUser,
     rescheduleUid,
-    reqBookingUid,
```
Comment (CarinaWolli) [inline packages/features/bookings/lib/handleSeats/handleSeats.ts:20]: we are using reqBookingUid below: https://github.com/calcom/cal.com/pull/13406/files#diff-c5f121133ff58fad7910d8fb79c72ea3157cf8d2be2522dadf16fa39894c84aeR41

File: packages/features/bookings/lib/handleSeats/handleSeats.ts [hunk 2]
```diff
@@ -41,9 +40,10 @@ const handleSeats = async (newSeatedBookingObject: NewSeatedBookingObject) => {
         {
           uid: rescheduleUid || reqBookingUid,
         },
+
         {
           eventTypeId: eventType.id,
-          startTime: evt.startTime,
+          startTime: new Date(evt.startTime),
```
Comment (CarinaWolli) [inline packages/features/bookings/lib/handleSeats/handleSeats.ts:46]: So that's what caused the double bookings, right? @joeauyeung

**Review by CarinaWolli — CHANGES_REQUESTED** [review]
There are issues with `reqBookingUid`, I left some comments

File: packages/features/bookings/lib/handleSeats/handleSeats.ts (hunk 2 above)
Comment (joeauyeung) [reply packages/features/bookings/lib/handleSeats/handleSeats.ts:47]: Double bookings were caused when a `bookingId` wasn't present in the booking request. This would happen when a booking link was sent en mass and multiple people were booking at the same time. I created a test for this scenario in this PR.

**Review by CarinaWolli — APPROVED** [review]
Nice fix 🙌🏻
