### PR TITLE
fix: back button in settings updated to use window history

### LINKED ISSUE #24937: Hovering over “Back” button in Webhook form throws React error
### Issue Summary

When hovering over the Back button in the Webhook Update Form, a React error is thrown.
This occurs immediately upon hovering the button and after clicking it. It appears to be caused by a conditional hook call or component re-render issue triggered by the hover event.

### Steps to Reproduce

Go to Dashboard → Developer → Webhooks.

Open any existing webhook to reach the Webhook Update Form page.

Hover/Click the mouse over the Back button in the top-left corner.

Observe the browser console — a error appears like (Error: React has blocked a javascript: URL as a security precaution).

### why this is a bug?

Hovering a UI button should only trigger visual effects (hover color, cursor change, etc.), not React errors or runtime exceptions.

### Actual Results

On hover, a React error is thrown in the console.

The UI sometimes becomes unresponsive or stops re-rendering correctly.

Error trace mentions “React has blocked a javascript: URL as a security precaution”

### Expected Results

No errors or warnings should appear in the console after hovering or clicking on the button

### Evidence

https://github.com/user-attachments/assets/e7686dbd-e457-4cfa-aae0-244380bd4604

### PR DESCRIPTION
**Pull request by Spandan-Mishra**
## What does this PR do?

- Fixes #24937 
- Fixes CAL-6701
- updated the back button in `SettingsHeader.tsx` to use window history back function, instead of javascript history back function which was causing the error.

## Visual Demo (For contributors especially)

A visual demonstration is strongly recommended, for both the original and new change **(video / image - any one)**.

#### Video Demo (if applicable):

Before:

https://github.com/user-attachments/assets/e0e5e785-ad6d-41bf-91e8-3b12f2ace825

After:

https://github.com/user-attachments/assets/23224a44-4726-4e70-a78e-51d16b984d4e

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox. - N/A
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Go to any page which uses the SettingsHeader component (Add Webhook page in the issue)
- Hover over the back button
- See that the error doesn't appear on it anymore

### CODE REVIEW

File: packages/features/settings/appDir/SettingsHeader.tsx [hunk 1]
```diff
@@ -33,9 +33,14 @@ export default function Header({
         <div className="flex w-full items-center justify-between gap-2">
           <div className="flex items-center">
             {backButton && (
-              <a href="javascript:history.back()">
+              <button
+                type="button"
+                onClick={() => window.history.back()}
+                aria-label="Go back"
```
[the remark this answers is not in the document]
Comment (dhairyashiil) [reply packages/features/settings/appDir/SettingsHeader.tsx]: @Spandan-Mishra  instead of removing the label, you should use 'go_back' key from translations, you can check here 'apps/web/public/static/locales/en/common.json', we already have key

File: packages/features/settings/appDir/SettingsHeader.tsx [hunk 2]
```diff
@@ -33,9 +33,13 @@ export default function Header({
         <div className="flex w-full items-center justify-between gap-2">
           <div className="flex items-center">
             {backButton && (
-              <a href="javascript:history.back()">
+              <button
```
Comment (dhairyashiil) [inline packages/features/settings/appDir/SettingsHeader.tsx]: Use Button component, refer : [code](https://github.com/calcom/cal.com/blob/main/packages/features/shell/Shell.tsx#L137C13-L148C15)

File: packages/features/settings/appDir/SettingsHeader.tsx [hunk 3]
```diff
@@ -33,9 +33,13 @@ export default function Header({
...
+                type="button"
+                onClick={() => window.history.back()}
```
Comment (dhairyashiil) [inline packages/features/settings/appDir/SettingsHeader.tsx]: instead of window.history.back(), you can import useRouter from next/navigation and use router.back() for consistency

**Review by dhairyashiil — CHANGES_REQUESTED** [review]
Please address the comments, making it draft until then

dont forget to add aria-label with translation key, refer : [comment](https://github.com/calcom/cal.com/pull/24952#discussion_r2496478195)

**Comment by Spandan-Mishra** [comment]
Updated the code based on the comments, ready for review @dhairyashiil

**Review by dhairyashiil — APPROVED** [review]
LGTM 👍🏼 , Thank you for the contribution
