### PR TITLE
fix: fixes organization table UI flickers and adds sticky search & filter + table header

### LINKED ISSUE #11213: [CAL-2423] Org/team members table flicks columns width
### Issue Summary

Org/team members table flicks columns width, causing a weird state when position of table is in a certain point.

### Steps to Reproduce

1. Create an org
2. Invite a lot of people
3. Scroll the members table

### Actual Results

Column width changes and in certain point causes the UI to flick

### Expected Results

Show table members correctly even when scrolling

### Evidence

https://github.com/calcom/cal.com/assets/467258/d7b57fdc-0021-4574-b055-df2451378f9b

<sub>[CAL-2423](https://linear.app/calcom/issue/CAL-2423/orgteam-members-table-flicks-columns-width)</sub>

### PR DESCRIPTION
**Pull request by siddharth-movaliya**
## What does this PR do?

The organizations members table UI flickering is solved. Made the search & filter and table header sticky for better access. Fixed the table not scrolling on mobile device issue by making the table height to be auto.

Fixes #11213 #11215 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

Create a new organization and add a lot of members. Scroll through page to see the changes.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: packages/ui/components/data-table/DataTableToolbar.tsx [hunk 1]
```diff
@@ -36,10 +36,10 @@ export function DataTableToolbar<TData>({
   const isFiltered = table.getState().columnFilters.length > 0;
 
   return (
-    <div className="flex items-center justify-end space-x-2">
+    <div className="bg-darkgray-50 sticky top-[3rem] z-10 flex items-center justify-end space-x-2 py-4 md:top-0">
```
Comment (sean-brydon) [inline packages/ui/components/data-table/DataTableToolbar.tsx:39]:
```suggestion
    <div className="bg-default sticky top-[3rem] z-10 flex items-center justify-end space-x-2 py-4 md:top-0">
```

**Review by sean-brydon — APPROVED** [review]
Tested - made a quick fix so we use the bg-default so we easily support light and dark mode on the search bar 

Thank you
