### PR TITLE
fix: rescheduling recurring events

### LINKED ISSUE #12461: [CAL-2741] Rescheduling one of the bookings of a recurring event reschedules the booking plus creates other bookings as well.
* Book an event with 3 recurrence
* Reschedule Booking-3
* Notice that Booking-3 is rescheduled correctly. But there are 2 new bookings as well, Booking-4 and Booking-5.\\
* In total there is 5 bookings now.

This is what I see after doing the reschedule

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2741](https://linear.app/calcom/issue/CAL-2741/rescheduling-one-of-the-bookings-of-a-recurring-event-reschedules-the)</sub>

### PR DESCRIPTION
**Pull request by ibex088**
## What does this PR do?

an attempt to fix #12461

## Before

[Screencast from 28-11-23 12:22:58 PM IST.webm](https://github.com/calcom/cal.com/assets/32706411/67046b69-e25e-41a9-8bfa-5107cba8f2ca)

1. Create a recurring event.
2. Book the recurring event, choosing to repeat every week for 2 occurrences.
3. Observe how two bookings appear on the table for the user and in the upcoming bookings page.
4. Attempt to reschedule the second booking. However, instead of only rescheduling that specific booking, it shows a recurrence every week for 12 occurrences. Additionally, selecting a time attempts to reschedule/book the entire 12 weeks, whereas the intention was to reschedule only that one booking.
5. Notice the creation of new bookings in the upcoming bookings page and in the database as well

## After

[Screencast from 28-11-23 11:48:51 AM IST.webm](https://github.com/calcom/cal.com/assets/32706411/1f4e3985-dd75-4948-9ac5-c76590ff71bd)

The fix ensures that rescheduling a single booking in recurring-bookings behaves like rescheduling a normal booking.

Not confident if this is the right approach

### CODE REVIEW

File: packages/features/bookings/components/event-meta/Details.tsx [hunk 1]
```diff
@@ -108,7 +109,11 @@ export const EventMetaBlock = ({
  * const MyCustomBlock = () => <div>Something nice</div>;
  * <EventDetails event={event} blocks={[EventDetailBlocks.LOCATION, MyCustomBlock]} />
  */
-export const EventDetails = ({ event, blocks = defaultEventDetailsBlocks }: EventDetailsProps) => {
+export const EventDetails = ({
+  event,
+  blocks = defaultEventDetailsBlocks,
+  rescheduleUid,
```
Comment (zomars) [inline packages/features/bookings/components/event-meta/Details.tsx:115]: Can't we just use 

```
const rescheduleUid = useBookerStore((state) => state.rescheduleUid);
```

In here instead of doing prop-drilling?

https://handbook.cal.com/engineering/best-practices/avoid-prop-drilling

**Review by CarinaWolli — COMMENTED** [review]
I tested it and it looked pretty good. The only thing I found was that the old rescheduled booking is still showing up on the booking detail page of the recurring event (booking/<id>). @SomayChauhan Could you take a look at that?

**Review by ibex088 — COMMENTED** [review]
changed it from `toDateString` to `toString` because `toDateString` disregards the time component of the date.

Screenshot from 2023-11-30 17-14-15

So, if I reschedule to a different time on the same day, observe the tooltip below. I rescheduled from 9 am to 10 am on December 18th (notice both times are struck through, and it shows 2 events remaining).

Screenshot from 2023-11-30 17-15-08

[Screencast from 30-11-23 05:05:10 PM IST.webm](https://github.com/calcom/cal.com/assets/32706411/0bee2277-8dd1-409f-a079-5175f9b9e390)

## after

Screenshot from 2023-11-30 17-26-35

**Review by CarinaWolli — APPROVED** [review]
Great fix, thank you 🙏
