### PR TITLE
fix: overflow issue in event type form builder and booking page

### LINKED ISSUE #7551: Option to scroll is missing
There is no option to scroll at the booking questions anymore. Firstly in the dashboard when creating longer lists of radio buttons, checklists, dropdowns, etc. On the other hand, the appointment booking pages themselves are also affected.

Bildschirm­foto 2023-03-07 um 03 42 03

Bildschirm­foto 2023-03-07 um 03 48 53

### PR DESCRIPTION
**Pull request by G3root**
## What does this PR do?

Fixes #7551 

after:

Screenshot 2023-03-07 12:48:17

Screenshot 2023-03-07 12:48:37

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/features/form-builder/FormBuilder.tsx [hunk 1]
```diff
@@ -368,7 +368,7 @@ export const FormBuilder = function FormBuilder({
             fieldIndex: -1,
           })
         }>
-        <DialogContent>
+        <DialogContent enableOverflow>
```
Comment (hariombalhara) [inline packages/features/form-builder/FormBuilder.tsx:371]: @G3root Why would we not want this to be enabled always?

Comment (G3root) [reply packages/features/form-builder/FormBuilder.tsx:371]: i think enabling this by default broke some modals 🤔 
cc: @Udit-takkar

Comment (hariombalhara) [reply packages/features/form-builder/FormBuilder.tsx:371]: Even if that is the case, I think we should disable it if needed. But this behaviour is something that should be enabled by default.

**Review by hariombalhara — APPROVED** [review]
