### PR TITLE
fix: Credential Syncing Improvements

### LINKED ISSUE #13903: [CAL-3427] [CAL-3236] Credential syncing - Fix parsing for minimum token response schema for all apps
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3236](https://linear.app/calcom/issue/CAL-3236/credential-syncing-fix-parsing-for-minimum-token-response-schema-for)</sub>

<sub>[CAL-3427](https://linear.app/calcom/issue/CAL-3427/[cal-3236]-credential-syncing-fix-parsing-for-minimum-token-response)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes CAL-3350
Fixes #13903
- Adds an example-app that becomes the source of truth for credentials. It makes it much easier to test out credential syncing.
- Google Calendar, Zoom App, Office365Calendar and Office365Video now accept just the `access_token` in token. Nothing else is required.
- Adds OAuthManager and is in use by Google Calendar and Zoom.

## Type of change
- Bug fix (non-breaking change which fixes an issue)

## Setup
1. Configure `example-apps/credential-sync` app .env and check README
2. Run the dev server for `credential-sync` example app
3. Configure CREDENTIAL related env variables in prisma/.env 
Screenshot 2024-04-24 at 2 46 34 PM
### Without Credential Sync Enabled
- Video Apps -> Test Zoom and Office365Video
  -  Install the app
  - Add to an event
  - Book that event and make sure that location has correct video link.
  - Manually expire the token in DB and then re-test the booking flow - Link would still work
  - Make the access_token invalid manually in DB and then check that the token is automatically refreshed.
  - Make the refresh_token invalid manually in DB and then check that token is marked invalid
- Calendar Apps -> Test Google Calendar and Office365Calendar
 -  Install the app
  - Add to an event
  - Book Event and check calendar and repeat above tests.
  - Also, go to apps/installed/calendar pages and repeat the same tests above and notice that the token is automatically refreshed. 

### With Credential Sync Enabled
Repeat the same tests as above and observe that instead of marking token as invalid TOKEN Sync call will go.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Comment by hariombalhara** [comment]
* **#14588** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/14588?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hariombalhara and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: apps/web/pages/api/webhook/app-credential.ts [hunk 1]
```diff
@@ -24,7 +24,12 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
     return res.status(403).json({ message: "Invalid credential sync secret" });
   }
 
-  const reqBody = appCredentialWebhookRequestBodySchema.parse(req.body);
+  const reqBodyParsed = appCredentialWebhookRequestBodySchema.safeParse(req.body);
```
Comment (hariombalhara) [inline apps/web/pages/api/webhook/app-credential.ts:27]: Let's not crash in case the body is invalid. Let's report back with the error.

File: packages/app-store/googlecalendar/lib/CalendarService.ts [hunk 2]
```diff
@@ -614,24 +640,27 @@ export default class GoogleCalendarService implements Calendar {
...
-            integration: this.integrationName,
-            name: cal.summary ?? "No name",
-            primary: cal.primary ?? false,
-            readOnly: !(cal.accessRole === "writer" || cal.accessRole === "owner") && true,
-            email: cal.id ?? "",
-          } satisfies IntegrationCalendar)
-      );
-    } catch (error) {
-      this.log.error("There was an error getting calendars: ", safeStringify(error));
-      throw error;
```
Comment (hariombalhara) [inline packages/app-store/googlecalendar/lib/CalendarService.ts:633]: Earlier we were throwing error but now no error is being thrown as `request` method captures uncaught error from google cal api.

File: yarn.lock
Comment (hariombalhara) [inline yarn.lock:1]: Fix yarn.lock

File: packages/app-store/_utils/oauth/OAuthManager.ts [hunk 3]
```diff
@@ -0,0 +1,451 @@
...
+    resourceOwner,
+    appSlug,
+    currentTokenObject,
+    fetchNewTokenObject,
+    updateTokenObject,
+    isTokenObjectUnusable,
+    isAccessTokenUnusable,
+    invalidateTokenObject,
+    expireAccessToken,
+    credentialSyncVariables,
```
Comment (joeauyeung) [inline packages/app-store/_utils/oauth/OAuthManager.ts:87]: Since the credential syncing variables are taken from the `.env` file do we need to pass these in the constructor every time?

File: packages/app-store/zoomvideo/api/callback.ts [hunk 4]
```diff
@@ -28,7 +28,9 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
     try {
       const responseBody = await result.json();
       errorMessage = responseBody.error;
-    } catch (e) {}
+    } catch (e) {
+      errorMessage = await result.clone().text();
```
Comment (joeauyeung) [inline packages/app-store/zoomvideo/api/callback.ts:32]: Why do we need to clone here?

**Review by joeauyeung — COMMENTED** [review]
@hariombalhara I love your approach to this. It was a genuine joy to read through.

I left a couple of comments that aren't blocking. Two things as well:
- It would also be great if we could add a small README to the example app
- Can you take a look at the `api/v1/credential-sync` endpoints to see if they align with the changes you made

File: example-apps/credential-sync/pages/index.tsx [hunk 5]
```diff
@@ -0,0 +1,65 @@
+import { useRouter } from "next/router";
```
[the remark this answers is not in the document]
Comment (sean-brydon) [reply example-apps/credential-sync/pages/index.tsx:1]: I actually think we should be using use search params here from next/navigation

File: packages/app-store/googlecalendar/lib/CalendarService.ts [hunk 6]
```diff
@@ -64,80 +75,109 @@ function handleMinMax(min: string, max: string) {
...
-        googleCredentials.expiry_date = token.expiry_date;
-        const parsedKey: ParseRefreshTokenResponse<typeof googleCredentialSchema> = parseRefreshTokenResponse(
-          googleCredentials,
-          googleCredentialSchema
-        );
-        await prisma.credential.update({
-          where: { id: credential.id },
-          data: { key: { ...parsedKey } as Prisma.InputJsonValue },
+  private initGoogleAuth = (credential: CredentialPayload) => {
+    const currentTokenObject = getTokenObjectFromCredential(credential);
```
[the remark this answers is not in the document]
Comment (hariombalhara) [reply packages/app-store/googlecalendar/lib/CalendarService.ts:100]: OAuthManager isn't aware of application logic. So, it doesn't know what a credential look like in Cal.com. But yeah we can optimize it by setting it on CalendarService instance during creation.

File: packages/app-store/zoomvideo/api/callback.ts (hunk 4 above)
Comment (hariombalhara) [reply packages/app-store/zoomvideo/api/callback.ts:32]: Response is really strict about consuming it. So, text() or json() consume it and it can't be re-consumed.

So, we have to be sure that we aren't re-consuming.

File: packages/app-store/googlecalendar/lib/CalendarService.ts [hunk 7]
```diff
@@ -613,25 +655,29 @@ export default class GoogleCalendarService implements Calendar {
...
-    }
+    const { json } = await this.oAuthManagerInstance.request(
+      async () =>
+        new AxiosLikeResponseToFetchResponse(
+          await calendar.calendarList.list({ fields: "items(id,summary,primary,accessRole)" })
+        )
+    );
+
+    const cals = json;
+
```
[the remark this answers is not in the document]
Comment (hariombalhara) [reply packages/app-store/googlecalendar/lib/CalendarService.ts:668]: It was safer to add it here initially as it is called inside the dashboard and not during the booking. But I think I should use it in all function calls now.

File: packages/app-store/_utils/oauth/OAuthManager.ts (hunk 3 above)
Comment (hariombalhara) [reply packages/app-store/_utils/oauth/OAuthManager.ts:87]: I made this change mainly to be able to toggle credential sync status in unit tests. 
 
But I think it is fine also as I wanted OAuthManager to be completely unaware of Application logic. So, it doesn't know what env variables or where exactly these constants should be imported from.

File: packages/app-store/_utils/oauth/OAuthManager.ts [hunk 8]
```diff
@@ -0,0 +1,451 @@
...
+          }),
+        });
+      } catch (e) {
+        myLog.error("Could not refresh the token.", safeStringify(e));
+        throw new Error(
+          `Could not refresh the token due to connection issue with the endpoint: ${CREDENTIAL_SYNC_ENDPOINT}`
+        );
+      }
+
+      const clonedResponse = response.clone();
```
[the remark this answers is not in the document]
Comment (hariombalhara) [reply packages/app-store/_utils/oauth/OAuthManager.ts:349]: Same reason of re-consumption of response.

File: example-apps/credential-sync/pages/index.tsx (hunk 5 above)
[the remark this answers is not in the document]
Comment (hariombalhara) [reply example-apps/credential-sync/pages/index.tsx:1]: Yeah I guess next/navigation is better.

File: packages/app-store/googlecalendar/lib/CalendarService.ts (hunk 2 above)
Comment (hariombalhara) [reply packages/app-store/googlecalendar/lib/CalendarService.ts:633]: We are throwing the error back
1. To keep the behaviour same
2. Error was caught to manage the tokenStatus correctly. That is now being done by catching the error, handling the tokenStatus and then throwing again.

File: packages/app-store/googlecalendar/lib/CalendarService.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (hariombalhara) [reply packages/app-store/googlecalendar/lib/CalendarService.ts]: Decided to still not add it in more calls. Just added it in `getAvailability` as well. 
More calls means all those scenarios need to be tested. So, that can be done later.

By not using request we are missing out on correctly marking the credential as invalid or not expiring the token(possibly) which was the case earlier as well.

File: example-apps/credential-sync/pages/index.tsx (hunk 5 above)
[the remark this answers is not in the document]
Comment (hariombalhara) [reply example-apps/credential-sync/pages/index.tsx]: Done

File: packages/core/videoClient.ts [hunk 9]
```diff
@@ -109,7 +109,11 @@ const createMeeting = async (credential: CredentialPayload, calEvent: CalendarEv
     log.debug("created Meeting", safeStringify(returnObject));
   } catch (err) {
     await sendBrokenIntegrationEmail(calEvent, "video");
-    log.error("createMeeting failed", safeStringify({ err, calEvent: getPiiFreeCalendarEvent(calEvent) }));
+    log.error(
+      "createMeeting failed",
+      safeStringify(err),
```
Comment (hariombalhara) [inline packages/core/videoClient.ts:114]: `err` doesn't stringify well when nested.

File: packages/app-store/_utils/getParsedAppKeysFromSlug.ts [hunk 10]
```diff
@@ -1,8 +1,12 @@
 import type Zod from "zod";
+import type z from "zod";
 
 import getAppKeysFromSlug from "./getAppKeysFromSlug";
 
-export async function getParsedAppKeysFromSlug(slug: string, schema: Zod.Schema) {
+export async function getParsedAppKeysFromSlug<T extends Zod.Schema>(
```
Comment (hariombalhara) [inline packages/app-store/_utils/getParsedAppKeysFromSlug.ts:6]: Fixes the `any` type return value

File: packages/app-store/office365video/lib/VideoApiAdapter.test.ts [hunk 11]
```diff
@@ -0,0 +1,282 @@
+import prismaMock from "../../../../tests/libs/__mocks__/prismaMock";
```
Comment (hariombalhara) [inline packages/app-store/office365video/lib/VideoApiAdapter.test.ts:1]: We should add similar tests for all integrations as and when we add OAuthManager to them

File: packages/app-store/office365video/lib/VideoApiAdapter.ts [hunk 12]
```diff
@@ -123,40 +87,38 @@ const TeamsVideoApiAdapter = (credential: CredentialPayload): VideoApiAdapter =>
...
+        .then(handleErrorsRaw);
 
       const resultObject = JSON.parse(resultString);
 
       return Promise.resolve({
         type: "office365_video",
         id: resultObject.id,
         password: "",
-        url: resultObject.joinUrl,
+        url: resultObject.joinWebUrl || resultObject.joinUrl,
```
Comment (hariombalhara) [inline packages/app-store/office365video/lib/VideoApiAdapter.ts:106]: `createMeeting` does the same

File: packages/app-store/office365video/lib/VideoApiAdapter.ts [hunk 13]
```diff
@@ -123,40 +87,38 @@ const TeamsVideoApiAdapter = (credential: CredentialPayload): VideoApiAdapter =>
...
       return Promise.resolve([]);
     },
     createMeeting: async (event: CalendarEvent): Promise<VideoCallData> => {
-      const accessToken = await (await auth).getToken();
-
-      const resultString = await fetch("https://graph.microsoft.com/v1.0/me/onlineMeetings", {
-        method: "POST",
-        headers: {
-          Authorization: `Bearer ${accessToken}`,
-          "Content-Type": "application/json",
```
Comment (hariombalhara) [inline packages/app-store/office365video/lib/VideoApiAdapter.ts:156]: These headers are automatically needed

File: packages/lib/errors.ts [hunk 14]
```diff
@@ -34,7 +35,7 @@ export function handleErrorsRaw(response: Response) {
     console.error({ response });
     return "{}";
   }
-  if (!response.ok && response.status < 200 && response.status >= 300) {
+  if (!response.ok || response.status < 200 || response.status >= 300) {
```
Comment (hariombalhara) [inline packages/lib/errors.ts:38]: status can't be simulatenously less than 200 and greater than 300. It should have been an OR.

Also, response.ok can independently decide error response.

File: packages/app-store/office365calendar/api/add.ts [hunk 15]
```diff
@@ -1,7 +1,7 @@
 import type { NextApiRequest, NextApiResponse } from "next";
 import { stringify } from "querystring";
 
-import { WEBAPP_URL } from "@calcom/lib/constants";
+import { WEBAPP_URL_FOR_OAUTH } from "@calcom/lib/constants";
```
Comment (hariombalhara) [inline packages/app-store/office365calendar/api/add.ts:4]: This is similar to other apps that have strict checks for redirect_URI because we use app.cal.com now for running local web app and we can only use https://localhost or a public domain(no app.cal.local), we use http://localhost:3000 for specifying the redirect URI.

**Review by joeauyeung — APPROVED** [review]
Tested locally for Zoom and GCal. All previous review comments were resolved as well. Honestly such a great approach @hariombalhara!
