### PR TITLE
/booking v2 fixes

### LINKED ISSUE #4094: Missing Design for Wipe Today button
Screenshot 2022-09-01 at 22 20 28

### LINKED ISSUE #4106: Reschedule request dialog still in old design
Screenshot 2022-09-01 at 16 58 57

### LINKED ISSUE #4108: Remove the ‘yet’ in ‘No upcoming bookings, yet’?
CleanShot 2022-09-02 at 09 24 15@2x

now:
Screenshot 2022-09-01 at 16 59 15

### LINKED ISSUE #4109: Bookings list still has the old buttons
Screenshot 2022-09-01 at 16 57 52

### LINKED ISSUE #4116: /booking: skeleton loader has wrong margin (too wide)
https://user-images.githubusercontent.com/8019099/188099054-dbbe371d-b92d-41ae-aadb-bada791085ff.mp4

### PR DESCRIPTION
**Pull request by PeerRich**
closes https://github.com/calcom/cal.com/issues/4116

closes https://github.com/calcom/cal.com/issues/4094

closes https://github.com/calcom/cal.com/issues/4106

closes https://github.com/calcom/cal.com/issues/4109

closes https://github.com/calcom/cal.com/issues/4108

### CODE REVIEW

File: apps/web/pages/v2/bookings/[status].tsx [hunk 1]
```diff
@@ -84,15 +84,15 @@ export default function Bookings() {
...
-      <WipeMyCalActionButton bookingStatus={status} bookingsEmpty={isEmpty} />
       <div className="flex w-full flex-1 flex-col">
         {query.status === "error" && (
           <Alert severity="error" title={t("something_went_wrong")} message={query.error.message} />
         )}
         {(query.status === "loading" || query.status === "idle") && <SkeletonLoader />}
         {query.status === "success" && !isEmpty && (
           <div className="pt-2 xl:mx-6 xl:pt-0">
-            <p className="pb-3 text-xs font-medium leading-4 text-gray-500">Today</p>
+            <WipeMyCalActionButton bookingStatus={status} bookingsEmpty={isEmpty} />
```
Comment (leog) [inline apps/web/pages/v2/bookings/[status].tsx:94]: Wouldn't be better in the same line as "Today" and at the right?

image

**Review by leog — APPROVED** [review]
LGTM!

File: apps/web/pages/v2/bookings/[status].tsx (hunk 1 above)
Comment (PeerRich) [reply apps/web/pages/v2/bookings/[status].tsx:94]: yeah but doesnt make a huge difference since not many people use wipe my cal yet
