### PR TITLE
Fixes: [CAL-644] Caches are not cleared when changing locations or recurring event settings

### LINKED ISSUE #6166: [CAL-644] Caches are not cleared when changing locations or recurring event settings
### Issue Summary

Changes to events are not reflected on the public event type pages immediately.

### Steps to Reproduce

1. Enable/disable recurrence, or add/remove/amend a location on an event type.
2. Visit the event's public page and observe the old settings in the sidebar. Wait several hours and observe the same old settings.
3. Select an available time, then return to the event page to see the cache has been updated.

<sub>[CAL-644](https://linear.app/calcom/issue/CAL-644/caches-are-not-cleared-when-changing-locations-or-recurring-event)</sub>

### PR DESCRIPTION
**Pull request by roae**
## What does this PR do?

Revalidate event type page on update

Fixes #6166

https://www.loom.com/share/adc62ee4fc5e44be80db6bad2b59927b

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/trpc/server/routers/viewer/eventTypes.ts [hunk 1]
```diff
@@ -700,7 +701,10 @@ export const eventTypesRouter = router({
       where: { id },
       data,
     });
-
+    const res = ctx.res as NextApiResponse;
```
Comment (emrysal) [inline packages/trpc/server/routers/viewer/eventTypes.ts:704]: @KATT The typings for CreateContextOptions are defined first in https://github.com/juliusmarminge/cal.com/commit/c28d800aa98b91cec5fdf9dc27085595c9a4c5ee - are these correct?

**Review by emrysal — APPROVED** [review]
