### PR TITLE
Hotfix: fixed callback URL for team invite email

### LINKED ISSUE #2974: Incorrect redirect URL in team invite email
### Issue Summary

Accepting an invite to a team leads to a 404 page after creating account (has happened 2 of 2 times)Steps to repro:

### Steps to Reproduce

1.     I add a new user via “Team” -> “Members” -> “+ New Member”
2.     New member clicks the “Accept Invitation” button in invite email.
3.     New member creates url slug and password.
4.     New member gets routed to https://app.cal.com/https:/app.cal.com/settings/teams which is a 404 page.

I then click “Go back home” to route to https://app.cal.com/getting-started and go through the 4-step onboarding flow
Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

Reported by Jeffrey Li on Slack

### PR DESCRIPTION
**Pull request by alishaz-polymath**
## What does this PR do?

Fixes the callback URL for team invitation email

Fixes #2974 

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Invite a user to a team who doesn't have a cal account yet. Once the user accepts the invitation in th email, adds the essential signup details, they should be redirected to the correct URL.

### CODE REVIEW

**Review by sean-brydon — APPROVED** [review]
LGTM

File: apps/web/pages/api/teams/[team]/invite.ts [hunk 1]
```diff
@@ -90,7 +90,7 @@ export default async function handler(req: NextApiRequest, res: NextApiResponse)
         from: session.user.name,
         to: usernameOrEmail,
         teamName: team.name,
-        joinLink: `${BASE_URL}/auth/signup?token=${token}&callbackUrl=${BASE_URL + "/settings/teams"}`,
+        joinLink: `${BASE_URL}/auth/signup?token=${token}&callbackUrl=/settings/teams}`,
```
Comment (hariombalhara) [inline apps/web/pages/api/teams/[team]/invite.ts:93]: To further avoid it altogether, we should have a method to generate a full link so that it can validate that absolute URL is wrong and relative URL is required.

```
getSignupLink({callbackUrl:`/settings/teams`, token})
```

**Review by hariombalhara — APPROVED** [review]
