### PR TITLE
fix: Add refresh token to refresh-token request response

### LINKED ISSUE #23939: Refresh token cannot be renewed
### Conculsion
We decided to extend the refresh token lifetime to 1 year. To support this securely, we will also start rotating the refresh token on every access-token refresh.

### Issue Summary

I previously asked Cal.com support about the lifetime of the refresh token and was told that it does not expire. However, after ~30 days my refresh token expired, and when I tried to refresh the access token via `POST https://app.cal.com/api/auth/oauth/refreshToken` I received a 401 Unauthorized response

I looked into the Cal.com source code and noticed this:
In `apps/web/app/api/auth/oauth/token/route.ts` the refresh token is generated with an explicit expiry of 30 days:
```
const refresh_token = jwt.sign(payloadRefreshToken, secretKey, {
  expiresIn: 30 * 24 * 60 * 60, // 30 days
});
```

In `apps/web/app/api/auth/oauth/refreshToken/route.ts` the code verifies the JWT and always returns `401 Unauthorized` if verification fails:
```
try {
  const refreshToken = req.headers.get("authorization")?.split(" ")[1] || "";
  decodedRefreshToken = jwt.verify(refreshToken, secretKey) as OAuthTokenPayload;
} catch {
  return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
}
```
This means the refresh token is actually limited to 30 days

### Steps to Reproduce

1. Obtain access and refresh token from Cal.com
2. Wait for 30 days
3. Try to refresh the access token via POST /api/auth/oauth/refreshToken

### Suggested fix
It would be helpful if one of the following changes could be made:

1. Generate refresh tokens without `expiresIn` (make them truly long-lived)
2. Don’t return 401 if the refresh token is invalid only due to expiration
3. Sign a new refresh token when refreshing the access token and include it in the response body

### PR DESCRIPTION
**Pull request by crrobinson14**
## What does this PR do?

This change addresses an issue reported in https://github.com/calcom/cal.com/issues/23939#issuecomment-3443480099 in which a new refresh token is not included in the OAuth2 refresh-token endpoint response.

- Fixes #23939

## Mandatory Tasks (DO NOT REMOVE)

- [X] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [X] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [-] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

Issue a refresh-token request. You should be provided with both an `access_token` and a `refresh_token` in the response body.

NOTE: I did not add an automated test for this path because I couldn't find any tests actually wired to the OAuth flow in the first place. The OAuth2 workflow is not implemented in the main API; it's done in `apps/web/api`. There don't appear to be any tests there for any of the OAuth2 flows, and it felt out of scope to add that here because there aren't any tracks to follow/mimic on how you'd want that section mocked/handled/etc.

Given that the other pieces of the flow (like the initial `authorization_code` request) also do not have any tests, perhaps that contribution rule could be relaxed here?

### CODE REVIEW

**Review by pallava-joshi — DISMISSED** [review]
hey, can you address the failing type checks

**Comment by crrobinson14** [comment]
Apologies, I missed a push. They should be resolved, except for the prisma deprecation warning that should be out of scope here - it's the same pattern used in the `authorization_code` side.

**Review by anikdhabal — APPROVED** [review]
Looks good

File: apps/web/app/api/auth/oauth/refreshToken/route.ts [hunk 1]
```diff
@@ -50,19 +50,31 @@ async function handler(req: NextRequest) {
...
+  const access_token = jwt.sign(payloadAuthToken, secretKey, {
     expiresIn: 1800, // 30 min
   });
 
-  return NextResponse.json({ access_token }, { status: 200 });
+  const refresh_token = jwt.sign(payloadRefreshToken, secretKey, {
+    expiresIn: 30 * 24 * 60 * 60, // 30 days
+  });
+
+  return NextResponse.json({ access_token, refresh_token }, { status: 200 });
```
Comment (supalarry) [inline apps/web/app/api/auth/oauth/refreshToken/route.ts:77]: This code is new to me so I have a question - if we are passing oAuth client's secret to this handler and then returning `refresh_token`, then we should update `oAuthClient.clientSecret` by setting it to the new `refresh_token` on line 73, right? aka current "clientSecret" is passed to handler, we create new one and we have to store it in database so that next time this call happens with the new "refresh_token" the clientSecret call does not fail
```
const client = await prisma.oAuthClient.findFirst({
    where: {
      clientId: client_id,
      clientSecret: hashedSecret,
    },
    select: {
      redirectUri: true,
    },
  });
```
?

**Review by supalarry — COMMENTED** [review]
@CarinaWolli can you tell me if what i wrote below is correct - this code is new to me

File: apps/web/app/api/auth/oauth/refreshToken/route.ts (hunk 1 above)
Comment (crrobinson14) [reply apps/web/app/api/auth/oauth/refreshToken/route.ts:77]: No, in an OAuth2 flow like this, `clientId`/`clientSecret` are static and assigned to the "application". They (almost) never change (unless deliberately rotated by the developer, and many apps don't even provide for that) and are only used for server-to-server calls. The expectation is that these are like database passwords - never exposed to the front-end, and kept safe/secret by the developer.

Comment (supalarry) [reply apps/web/app/api/auth/oauth/refreshToken/route.ts:77]: @crrobinson14 thanks for the walk through.
