### PR TITLE
fix: prefill avatar when signing up

### LINKED ISSUE #13426: [CAL-3036] prefill avatar when signing up with Google
example: https://github.com/dubinc/dub/blob/main/apps/web/lib/auth/options.ts#L195

<sub>[CAL-3036](https://linear.app/calcom/issue/CAL-3036/prefill-avatar-when-signing-up-with-google)</sub>

### PR DESCRIPTION
**Pull request by neo773**
## What does this PR do?
prefills avatar when signing up if it exists

Fixes #13426

## Type of change

- Bug fix (non-breaking change which fixes an issue)

/claim #13426

### CODE REVIEW

File: packages/features/auth/lib/next-auth-options.ts [hunk 1]
```diff
@@ -788,6 +788,7 @@ export const AUTH_OPTIONS: AuthOptions = {
             username: orgId ? slugify(orgUsername) : usernameSlug(user.name),
             emailVerified: new Date(Date.now()),
             name: user.name,
+            ...(user.image && { avatarUrl: user.image }),
```
Comment (PeerRich) [inline packages/features/auth/lib/next-auth-options.ts:791]: this would save the google URL right? I wonder if we should convert this to base64 and save on our server? 🤔 @emrysal

Comment (neo773) [reply packages/features/auth/lib/next-auth-options.ts:791]: yeah, I think saving the URL should be fine as it's static and never expires

**Review by PeerRich — APPROVED** [review]
