### PR TITLE
Fix weekStart passThrough + allow all days

### LINKED ISSUE #3102: Monday as first day of week ignored
### Issue Summary

While this has been working until version 1.6.3, with version 1.7.1 the given date range of events is ignored when scheduling.

### Steps to Reproduce

1. Set Monday as first day of week in the backend
2. Go to scheduling 
3. The date pickers starts with sunday

### Technical details

- Browser version: Firefox 101.0.1
- Node.js version: v14.19.3
- cal.com selfhosted (1.7.1)

### PR DESCRIPTION
**Pull request by emrysal**
## What does this PR do?

* Fixes weekStart not being applied
* Implements Tuesday, Wednesday, Thursday, Friday and Saturday as alternative weekStarts for

Fixes #3102 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

Profile page shows all days as options, and the DatePicker should change accordingly.

### CODE REVIEW

File: apps/web/components/booking/pages/AvailabilityPage.tsx [hunk 1]
```diff
@@ -664,6 +664,13 @@ const AvailabilityPage = ({ profile, eventType }: Props) => {
                   )*/}
               </div>
               <SlotPicker
+                weekStart={
+                  typeof profile.weekStart === "string"
+                    ? (["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"].indexOf(
+                        profile.weekStart
+                      ) as 0 | 1 | 2 | 3 | 4 | 5 | 6)
+                    : profile.weekStart /* Allows providing weekStart as number */
```
Comment (emrysal) [inline apps/web/components/booking/pages/AvailabilityPage.tsx:672]: We really should store weekStart as a number in the DB (Or DB type) so this will allow that backwards compatibility when we get to it.

**Review by zomars — APPROVED** [review]

**Review by leog — APPROVED** [review]
LGTM
