### PR TITLE
fix: DST issue in the month of DST change

### LINKED ISSUE #10517: [CAL-2282] wrong slots shown in november after dst change
### Issue Summary

My availability starts at 9:00AM America/New_York. Only November (after 5th - the day of dst change) shows slots available starting at 8:00AM. December slots are starting at 9am again. 

When trying to book these slots I am getting an error:
Screenshot 2023-08-01 at 18 06 19

<sub>[CAL-2282](https://linear.app/calcom/issue/CAL-2282/wrong-slots-shown-in-november-after-dst-change)</sub>

### PR DESCRIPTION
**Pull request by CarinaWolli**
## What does this PR do?

Fixes issue that availability was shown wrong in month of dst change. 

Fixes #10517

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Create availability in NY timezone 
- Go to booking page also set NY timezone
- Go to November. All days should start at the time defined in the availability (before and after 5th of november)
- Change time to Europe/Amsterdam on booking page
- See that on oktober 28 availability starts on defined time but after oktober 28 until nov 5 availability starts 1 hour earlier 
- Test other timezones

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

File: packages/lib/date-ranges.ts [hunk 1]
```diff
@@ -23,12 +23,21 @@ export function processWorkingHours({
 }) {
   const results = [];
   for (let date = dateFrom.tz(timeZone).startOf("day"); dateTo.isAfter(date); date = date.add(1, "day")) {
-    if (!item.days.includes(date.day())) {
+    const dateInTz = date.tz(timeZone);
```
Comment (CarinaWolli) [inline packages/lib/date-ranges.ts:26]: date is always in the timezone that dateFrom is

File: packages/lib/date-ranges.ts [hunk 2]
```diff
@@ -23,12 +23,21 @@ export function processWorkingHours({
...
     }
 
-    const start = date.hour(item.startTime.getUTCHours()).minute(item.startTime.getUTCMinutes()).second(0);
-    const end = date.hour(item.endTime.getUTCHours()).minute(item.endTime.getUTCMinutes()).second(0);
+    let start = dateInTz.hour(item.startTime.getUTCHours()).minute(item.startTime.getUTCMinutes()).second(0);
+
+    let end = dateInTz.hour(item.endTime.getUTCHours()).minute(item.endTime.getUTCMinutes()).second(0);
+
+    const offsetBeginningOfDay = dayjs(start.format("YYYY-MM-DD hh:mm")).tz(timeZone).utcOffset();
+    const offsetDiff = start.utcOffset() - offsetBeginningOfDay; // there will be 60 min offset on the day day of DST change
```
Comment (CarinaWolli) [inline packages/lib/date-ranges.ts:37]: For example, DST change for NY timezone is nov 5th 2AM. `dateInTz` is the beginning of the day, so if start time is after 2AM then the timezone needs to be adjusted

**Review by zomars — APPROVED** [review]
Nice job @CarinaWolli Code LGTM. Waiting for tests before merging 🙏🏽
