### PR TITLE
fix: Error during booking when default app is a Static Link Video App and Event has Organizer default location selected.

### LINKED ISSUE #9732: [CAL-2033] Selecting campfire as location fails booking for team event
It happens when campfire is selected as default conferencing app and in the team event, 'Use Organizer's default conferencing App' is chosen
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2033](https://linear.app/calcom/issue/CAL-2033/selecting-campfire-as-location-fails-booking-for-team-event)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

It happens when campfire or any other static link based video app is selected as default conferencing app and in the team event, 'Use Organizer's default conferencing App' is chosen.

Fixes #9732

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [x] Test teampro+pro - When **teampro** has Campfire as default conferencing app set. The booking should have a valid campfire link.
- [x] Test a team event that  is using Organizer's default App in location. The booking should have valid campfire link
- [x] Test a dynamic link based video location like Zoom or CalVideo. The booking should succeed with valid link in booking.
- [x] Test a non video based location like Phone Number and see that the booking has the phone number avaiable.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

## Followup
- [ ] A few tests for Organizer's default conferencing app.

### CODE REVIEW

File: packages/core/videoClient.ts [hunk 1]
```diff
@@ -23,9 +23,17 @@ const getVideoAdapters = async (withCredentials: CredentialPayload[]): Promise<V
...
   for (const cred of withCredentials) {
     const appName = cred.type.split("_").join(""); // Transform `zoom_video` to `zoomvideo`;
-    const app = await appStore[appName as keyof typeof appStore]();
+    const appImportFn = appStore[appName as keyof typeof appStore];
 
-    if (app && "lib" in app && "VideoApiAdapter" in app.lib) {
+    // Static Link Video Apps don't exist in packages/app-store/index.ts(it's manually maintained at the moment) and they aren't needed there anyway.
+    const app = appImportFn ? await appImportFn() : null;
+
+    if (!app) {
```
Comment (hariombalhara) [inline packages/core/videoClient.ts:31]: This was the reason the booking was failing. So, it would gracefully handle this flow now.

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 2]
```diff
@@ -877,7 +883,11 @@ async function handler(
   const seed = `${organizerUser.username}:${dayjs(reqBody.start).utc().format()}:${new Date().getTime()}`;
   const uid = translator.fromUUID(uuidv5(seed, uuidv5.URL));
 
-  const bookingLocation = getLocationValueForDB(locationBodyString, eventType.locations);
+  // For static link based video apps, it would have the static URL value instead of it's type(e.g. integrations:campfire_video)
+  // This ensures that createMeeting isn't called for static video apps as bookingLocation becomes just a regular value for them.
+  const bookingLocation = organizerOrFirstDynamicGroupMemberDefaultLocationUrl
```
Comment (hariombalhara) [inline packages/features/bookings/lib/handleNewBooking.ts:888]: It was the reason why getVideoAdapters fn was being called. We shouldn't have entered the createMeeting flow for static link based apps.

**Review by hariombalhara — COMMENTED** [review]
Self reviewed

**Review by zomars — APPROVED** [review]
Code LGTM
