### PR TITLE
Fix: avatar group buggy with +0

### LINKED ISSUE #7032: [CAL-1038] avatar group buggy with +0
see here: [https://cal.com/peer+bailey+ciaran+seanbrydon ](https://cal.com/peer+bailey+ciaran+seanbrydon)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1038](https://linear.app/calcom/issue/CAL-1038/avatar-group-buggy-with-0)</sub>

### PR DESCRIPTION
**Pull request by amirfakhrullah**
## What does this PR do?

Fix `AvatarGroups` component to follow: https://www.figma.com/file/9MOufQNLtdkpnDucmNX10R/%E2%9D%96-Cal-DS?node-id=1573%3A77871&t=I8UQXj6AtCkQ0f0E-0

Fixes #7032
Screenshot 2023-02-11 at 4 18 03 AM

In-case the truncated avatars are more that 1 digits
Screenshot 2023-02-11 at 4 18 45 AM

For this video, behind the scenes (on my IDE) I'm changing the `truncatedAfter` prop value from 3 -> 1 -> 2 -> 3 -> 4. You can see the behaviour as below:

https://user-images.githubusercontent.com/73758525/218243781-b0fd6985-0607-434b-9924-28fd389e75a5.mov

**Environment**: Staging(main branch) / Pr

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Run locally and open a dynamic collective event booking page

### CODE REVIEW

File: packages/ui/components/avatar/AvatarGroup.tsx [hunk 1]
```diff
@@ -16,48 +16,45 @@ export type AvatarGroupProps = {
...
+            accepted={props.accepted}
+            size={props.size}
+            href={item.href}
+          />
+        </li>
+      ))}
+      {numTruncatedAvatars > 0 && (
+        <li
+          className={classNames(
+            "relative -mr-[4px] mb-1 inline-flex justify-center overflow-hidden rounded-full bg-black",
```
Comment (PeerRich) [inline packages/ui/components/avatar/AvatarGroup.tsx:46]:
```suggestion
            "relative -mr-[4px] mb-1 inline-flex justify-center overflow-hidden rounded-full bg-darkgray-300",
```

File: packages/ui/components/avatar/AvatarGroup.tsx [hunk 2]
```diff
@@ -16,48 +16,45 @@ export type AvatarGroupProps = {
...
+            href={item.href}
+          />
+        </li>
+      ))}
+      {numTruncatedAvatars > 0 && (
+        <li
+          className={classNames(
+            "relative -mr-[4px] mb-1 inline-flex justify-center overflow-hidden rounded-full bg-darkgray-300",
+            props.size === "sm" ? "min-w-6 h-6" : "min-w-16 h-16"
+          )}>
```
Comment (PeerRich) [inline packages/ui/components/avatar/AvatarGroup.tsx:48]: after seeing bg-black in action i decided to change it to bg-darkgray-300

**Review by PeerRich — APPROVED** [review]

File: packages/ui/components/avatar/AvatarGroup.tsx (hunk 2 above)
Comment (amirfakhrullah) [reply packages/ui/components/avatar/AvatarGroup.tsx]: @PeerRich I saw that the lint workflow failed due to the classname order rule, so I pushed a commit to fix that
