### PR TITLE
Fix request-reschedule for team events

### LINKED ISSUE #3668: Can't "Request reschedule" from a team event
### Issue Summary

This happened with a teams link. Not sure if it's the case with a regular event.

### Steps to Reproduce

1. Book an event from a teams link
2. Try request that the booker reschedule the event

https://user-images.githubusercontent.com/4536123/182721011-b9228c6d-0574-4551-80bb-effeaebd8d42.MOV

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

Validate that if a booking belongs to a team, user should have membership on that team. 
Also avoid throwing Unauthorised error if user its owner of the booking and booking belongs to a team.
Fixes #3668 

https://www.loom.com/share/2672ad6993274f40b36d4d368640ec48

**Environment**: Staging(main branch) / Production

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Try to request reschedule on any booking that belongs to a team. It shouldn’t throw any error now.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: apps/web/pages/api/book/request-reschedule.ts [hunk 1]
```diff
@@ -104,9 +106,18 @@ const handler = async (
       },
     });
 
-    if (bookingToReschedule.userId !== userOwner.id) throw new Error("UNAUTHORIZED");
+    const bookingBelongsToTeam = !!bookingToReschedule?.eventType?.teamId;
+    if (bookingBelongsToTeam && bookingToReschedule?.eventType?.teamId) {
```
Comment (hariombalhara) [inline apps/web/pages/api/book/request-reschedule.ts:110]: Nit: instead of putting so may ?s, we can check for `bookingToReschedule?.eventType` once in the beginning and throw error maybe

File: apps/web/pages/api/book/request-reschedule.ts [hunk 2]
```diff
@@ -104,9 +106,18 @@ const handler = async (
...
+      const userTeamIds = user.teams.map((item) => item.teamId);
+      if (userTeamIds.indexOf(bookingToReschedule?.eventType?.teamId) === -1) {
+        throw new Error("UNAUTHORIZED: booking.belongs.to.team");
```
Comment (hariombalhara) [inline apps/web/pages/api/book/request-reschedule.ts:113]: nit: possibly better message -> `User isn't a member of the team`

File: apps/web/pages/api/book/request-reschedule.ts [hunk 3]
```diff
@@ -209,49 +220,53 @@ const handler = async (
...
-          bookingToReschedule.attendees as unknown as PersonAttendeeCommonFields[],
-          tAttendees
-        ),
-        uid: bookingToReschedule?.uid,
-        location: bookingToReschedule?.location,
-        destinationCalendar:
-          bookingToReschedule?.destinationCalendar || bookingToReschedule?.destinationCalendar,
-        cancellationReason: `Please reschedule. ${cancellationReason}`, // TODO::Add i18-next for this
-      };
+      if (bookingToReschedule.userId) {
```
Comment (hariombalhara) [inline apps/web/pages/api/book/request-reschedule.ts:223]: nit: This check could also be moved very early in the code and we can return early

**Review by hariombalhara — DISMISSED** [review]
I think in request-reschedule case, emails are being sent only to the person who is cancelling and not other team members that are part of the booking.

File: apps/web/pages/api/book/request-reschedule.ts (hunk 1 above)
Comment (zomars) [reply apps/web/pages/api/book/request-reschedule.ts:110]: Agreed with @hariombalhara this also aligns with our [Prefer early returns](https://app.gitbook.com/o/6snd8PyPYMhg0wUw6CeQ/s/VXRprBTuMlihk37NQgUU/engineering/best-practices/prefer-early-returns) style

**Comment by alannnc** [comment]
@hariombalhara @zomars Suggestion changes has been applied. Also about Hariom's comment about cancellation email, every attendee should receive cancellation email but only main attendee should be able to reschedule booking.

**Review by zomars — APPROVED** [review]
