### PR TITLE
fix: event type filter in Mobile view

### LINKED ISSUE #9616: [CAL-1981] mobile: hide event type filter
we only want these on desktop

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1981](https://linear.app/calcom/issue/CAL-1981/mobile-hide-event-type-filter)</sub>

### PR DESCRIPTION
**Pull request by manavsiddharthgupta**
## What does this PR do?

Fixes #9616

Before : 

image

After : 

image

## Type of change

- Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by sean-brydon — APPROVED** [review]

**Review by PeerRich — APPROVED** [review]

File: apps/web/pages/event-types/index.tsx [hunk 1]
```diff
@@ -799,7 +799,7 @@ const CTA = () => {
 
 const Actions = () => {
   return (
-    <div className="flex items-center">
+    <div className="hidden md:flex items-center">
```
Comment (PeerRich) [inline apps/web/pages/event-types/index.tsx:802]:
```suggestion
    <div className="hidden items-center md:flex">
```
