### PR TITLE
fix: Intercom app - regex valid url

### LINKED ISSUE #1490: [CAL-422] Intercom App
[https://developers.intercom.com/building-apps/docs/guidelines-tips](https://developers.intercom.com/building-apps/docs/guidelines-tips)

> From [SyncLinear.com](https://synclinear.com)

### PR DESCRIPTION
**Pull request by vachmara**
## What does this PR do?

The issue occurs because the regex does not account for enterprise subdomains and incorrectly matches `app.cal.com` instead of `cal.com`. As a result, users are experiencing problems when adding a custom link.

Users encountering this issue:
Screenshot 2025-03-12 at 1 35 38 PM

Fixes:

- Adjust regex to properly handle enterprise subdomains.
- Ensure cal.com URLs are correctly validated instead of app.cal.com.
- Improve error messages for better clarity.

fix #1490 

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

File: packages/app-store/intercom/lib/isValidCalURL.ts [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import { WEBAPP_URL } from "@calcom/lib/constants";
+import { CAL_URL } from "@calcom/lib/constants";
```
Comment (TusharBhatt1) [inline packages/app-store/intercom/lib/isValidCalURL.ts:1]: Why was this required

File: packages/app-store/intercom/lib/isValidCalURL.ts [hunk 2]
```diff
@@ -9,11 +9,14 @@ import type { TextComponent } from "../lib";
  * @returns IsValid
  */
 export async function isValidCalURL(url: string) {
-  const regex = new RegExp(`^${WEBAPP_URL}/`, `i`);
+  const regex = new RegExp(
+    `^https?://(?:[a-zA-Z0-9-]+\\.)?${CAL_URL.replace("https://", "")}/(team/)?(org/)?`,
+    "i"
```
Comment (TusharBhatt1) [inline packages/app-store/intercom/lib/isValidCalURL.ts:14]: Why are we giving a support for both http and https,

Comment (vachmara) [reply packages/app-store/intercom/lib/isValidCalURL.ts:14]: Yeah I forgot to remove it, but it should be only https

**Comment by TusharBhatt1** [comment]
Can you brief , why this change is required in the description (what issue it solves)

**Comment by vachmara** [comment]
> Can you brief , why this change is required in the description (what issue it solves)

Done

**Review by TusharBhatt1 — APPROVED** [review]
