### PR TITLE
fix: regex and id extraction for giphy media urls

### LINKED ISSUE #22275: Bug: Giphy URL Validation Fails for Media Links
Found a bug? Please fill out the sections below. 👍

### Issue Summary

The current Giphy URL validation logic fails for valid Giphy media URLs such as:

`https://media1.giphy.com/media/v1.Y2lkPTc.../ngDR1qZBUIIEwJGPx7/giphy.gif`

### Steps to Reproduce

1. go to event types
2. select a event 
3. add giphy app and add a gif using url 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

- What's happening right now that is different from what is expected

### Expected Results

- This is an ideal result that the system should get after the tests are performed

### Technical details

- Browser version, screen recording, console logs, network requests: You can make a recording with [Bird Eats Bug](https://birdeatsbug.com/).
- Node.js version
- Anything else that you think could be an issue.

### Evidence

- How was this tested? This is quite mandatory in terms of bugs. Providing evidence of your testing with screenshots or/and videos is an amazing way to prove the bug and a troubleshooting chance to find the solution.

Image

### PR DESCRIPTION
**Pull request by abhix4**
## What does this PR do?

Fixed the regular expression used for validation.
Correctly extracts the Giphy ID from the URL path.

- Fixes #22275 
- Fixes CAL-6046

## Visual Demo (For contributors especially)

before: 
Screenshot from 2025-07-04 22-51-26

after:
Screenshot from 2025-07-04 22-47-38

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

    

---

## Summary by cubic
Fixed Giphy URL validation and ID extraction to correctly handle different Giphy media URL formats.

- **Bug Fixes**
  - Updated the regex to support more Giphy URL patterns.
  - Fixed extraction logic to get the correct Giphy ID.

### CODE REVIEW

File: packages/app-store/giphy/api/get.ts [hunk 1]
```diff
@@ -26,10 +28,10 @@ async function handler(req: NextApiRequest, res: NextApiResponse) {
     const sanitisedUrl = parsedUrl.origin + parsedUrl.pathname;
     // Extract Giphy ID from embed url
     const matches = giphyUrlRegexp.exec(sanitisedUrl);
-    if (!matches || matches.length < 3) {
+    if (!matches || matches.length < 2) {
       return res.status(400).json({ message: "Giphy URL is invalid" });
     }
-    const giphyId = matches[2];
+    const giphyId = matches[1];
```
Comment (anikdhabal) [inline packages/app-store/giphy/api/get.ts:34]: Can you explain this change?

**Comment by kart1ka** [comment]
Making it draft. Feel free to rfr once the comments are addressed.

**Review by anikdhabal — DISMISSED** [review]

**Review by anikdhabal — APPROVED** [review]

**Comment by anikdhabal** [comment]
@coderabbitai review
