### PR TITLE
fix: booking_paid webhook and added new payment metadata

### LINKED ISSUE #10679: [CAL-2328] Add more data to booking_paid webhook
We can add { stripePaymentId, stripeCustomerId, providerId: "cal.com", userId, eventName, eventId }

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2328](https://linear.app/calcom/issue/CAL-2328/add-more-data-to-booking-paid-webhook)</sub>

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

- Implements webhook booking_paid
- Looks like it was implement a while a go but wasn't working right.
- Add payment data to webhook metadata
- Fixes a bug when saving app.metadata with 2 payment app credentials installed

Fixes #10679 

https://www.loom.com/share/c0a54a80063841d5947917934c8eee6c?sid=bf913ef1-1219-4c2d-aee1-f40f9ebd43b4

## Requirement/Documentation

- If there is a requirement document, please, share it here.
- If there is ab UI/UX design document, please, share it here.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Are there environment variables that should be set? No
- What are the minimal test data to have? Stripe installed and and event that uses it.
- What is expected (happy path) to have (input and output)? Pay the booking and we should receive webhook for BOOKING_PAID
- Any other important info that could help to test that PR

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/features/bookings/lib/handleConfirmation.ts [hunk 1]
```diff
@@ -338,7 +338,67 @@ export async function handleConfirmation(args: {
         );
       })
     );
+
     await Promise.all(promises);
+
+    if (paid) {
```
Comment (alannnc) [inline packages/features/bookings/lib/handleConfirmation.ts:344]: Added a whole section when receiving paid flag here

File: packages/features/bookings/lib/handleConfirmation.ts [hunk 2]
```diff
@@ -338,7 +338,67 @@ export async function handleConfirmation(args: {
...
+      let paymentExternalId: string | undefined;
+      const subscriberMeetingPaid = await getWebhooks({
+        userId: triggerForUser ? booking.userId : null,
+        eventTypeId: booking.eventTypeId,
+        triggerEvent: WebhookTriggerEvents.BOOKING_PAID,
+        teamId: booking.eventType?.teamId,
+      });
+      const bookingWithPayment = await prisma.booking.findFirst({
```
Comment (alannnc) [inline packages/features/bookings/lib/handleConfirmation.ts:352]: Gather all required information

File: packages/features/bookings/lib/handleConfirmation.ts [hunk 3]
```diff
@@ -338,7 +338,67 @@ export async function handleConfirmation(args: {
...
+      }
+
+      const paymentMetadata = {
+        identifier: "cal.com",
+        bookingId,
+        eventTypeId: booking.eventType?.id,
+        bookerEmail: evt.attendees[0].email,
+        eventTitle: booking.eventType?.title,
+        externalId: paymentExternalId,
+      };
```
Comment (alannnc) [inline packages/features/bookings/lib/handleConfirmation.ts:378]: Declare new metadata for payment

File: packages/features/bookings/lib/handleConfirmation.ts [hunk 4]
```diff
@@ -338,7 +338,67 @@ export async function handleConfirmation(args: {
...
+        }).catch((e) => {
+          console.error(
+            `Error executing webhook for event: ${WebhookTriggerEvents.BOOKING_PAID}, URL: ${sub.subscriberUrl}`,
+            e
+          );
+        })
+      );
+
+      // I don't need to await for this
+      Promise.all(bookingPaidSubscribers);
```
Comment (alannnc) [inline packages/features/bookings/lib/handleConfirmation.ts:400]: Don't await to complete this

File: packages/features/bookings/lib/handleConfirmation.ts (hunk 1 above)
Comment (hariombalhara) [reply packages/features/bookings/lib/handleConfirmation.ts:344]: How about refactoring it out to a `handlePaidEventConfirmation` function

File: packages/features/bookings/lib/handleConfirmation.ts (hunk 4 above)
Comment (hariombalhara) [reply packages/features/bookings/lib/handleConfirmation.ts:400]: We don't need to do a Promise.all I guess, if we aren't waiting for the results.

**Comment by hariombalhara** [comment]
I will be soon opening a PR to handle firing BOOKING_CREATED webhook and others for paid events as per https://github.com/calcom/cal.com/issues/7120. I was going to add BOOKING_PAYMENT_SUCCESSFUL as well event which you already handled here as BOOKING_PAID

**Comment by alannnc** [comment]
> I will be soon opening a PR to handle firing BOOKING_CREATED webhook and others for paid events as per #7120. I was going to add BOOKING_PAYMENT_SUCCESSFUL as well event which you already handled here as BOOKING_PAID

@hariombalhara Let me know if I need to close this PR if yours deprecate or supersede mine.

File: packages/trpc/server/routers/viewer/eventTypes/update.handler.ts [hunk 5]
```diff
@@ -241,13 +241,13 @@ export const updateHandler = async ({ ctx, input }: UpdateOptions) => {
...
-  if (input?.price || input.metadata?.apps?.stripe?.price) {
-    data.price = input.price || input.metadata?.apps?.stripe?.price;
+  if (input.metadata?.apps?.stripe?.price) {
+    data.price = input.metadata?.apps?.stripe?.price;
     const paymentCredential = await ctx.prisma.credential.findFirst({
       where: {
         userId: ctx.user.id,
         type: {
-          contains: "_payment",
+          equals: "stripe_payment",
```
Comment (zomars) [inline packages/trpc/server/routers/viewer/eventTypes/update.handler.ts:250]: Will this trigger for PayPal payments as well?

Comment (alannnc) [reply packages/trpc/server/routers/viewer/eventTypes/update.handler.ts:250]: See below, I didn't like this duplicated code but should work for a starter.

File: packages/features/bookings/lib/handleConfirmation.ts (hunk 4 above)
Comment (zomars) [reply packages/features/bookings/lib/handleConfirmation.ts:400]: > We don't need to do a Promise.all I guess, if we aren't waiting for the results.

It's ok, we want them to start in parallel instead of cascading even if we don't wait for the response

**Review by zomars — APPROVED** [review]
Seems to fix the issue. I feel this can be improved upon. But good enough for now. Nice job @alannnc 

Ship it

File: packages/features/bookings/lib/handleConfirmation.ts (hunk 4 above)
Comment (hariombalhara) [reply packages/features/bookings/lib/handleConfirmation.ts:400]: But calls would go in parallel already due to line 380. We don't need the result of any of those promises. So we don't need line number 400 at all.
