### PR TITLE
Fix: Send responses in confirm booking flow

### LINKED ISSUE #7810: [CAL-1287] Differing webhook responses when using "requires confirmation"
Hey guys not sure if you're aware of this issue with the booking creation webhook payload. Everything works great when a normal booking is completed, all custom input responses come through as expected. However, when I change the booking to "Required Confirmation" I don't get the same payload data and am missing some important custom input responses.

Please see the images below and you'll notice "responses" is completely missing when "Require Confirmation" is activated.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1287](https://linear.app/calcom/issue/CAL-1287/differing-webhook-responses-when-using-requires-confirmation)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #7810

**Environment**: Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
## How should this be tested?

- [x] Make a booking for an Event Type which requires confirmation. Accept the booking and notice that webhook payload has the `responses` and `userFieldsResponses` props.
- [x] Make a booking like the earlier test and before accepting the booking, delete the Event Type. Notice that `responses` and `userFieldsResponses` props are still there.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/features/bookings/lib/getBookingResponsesSchema.ts [hunk 1]
```diff
@@ -9,14 +9,28 @@ type EventType = Parameters<typeof preprocess>[0]["eventType"];
...
+  z.string(),
+  z.boolean(),
+  z.string().array(),
+  z.object({
+    optionValue: z.string(),
+    value: z.string(),
+  }),
+]);
+
+export const bookingResponsesDbSchema = z.record(bookingResponse);
```
Comment (hariombalhara) [inline packages/features/bookings/lib/getBookingResponsesSchema.ts:22]: It allows disconnecting current event type data from the responses collected. It thus fixes scenarios like
- Earlier, a  field was of type text and has value "Test" and when we changed the type to "checkbox" booking started showing the value as `false`
- Earlier, a field was there and was recorded in a booking but after removing that field/question, it stopped showing in existing bookings as well.

**Review by CarinaWolli — APPROVED** [review]
Nice! Works and code looks good as well 🙏
