### PR TITLE
fix: Reschedule URL for an org migrated/moved user's booking.

### LINKED ISSUE #15790: [CAL-4044] Reschedule not working for a migrate org member when done from the booking success page
Reported here [https://app.campsite.co/cal/posts/hm92k9ck9u3s](https://app.campsite.co/cal/posts/hm92k9ck9u3s)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4044](https://linear.app/calcom/issue/CAL-4044/reschedule-not-working-for-a-migrate-org-member-when-done-from-the)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes 404 for reschedule of a migrated/org user's booking if orgDomain is used for reschedule.
So, if acme.cal.com/reschedule/ endpoint is used it was 404, otherwise it was working.

Practically such a URL was used during reschedule when user tried to reschedule immediately after the booking.

[Loom(Before and After)](https://www.loom.com/share/42974aee333540f095f531ee18c7d39a)

Fixes CAL-4044
Fixes #15790

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A I have added a Docs issue [here](https://github.com/calcom/docs/issues/new) if this PR makes changes that would require a [documentation change](https://docs.cal.com). If N/A, write N/A here and check the checkbox.
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?
- For acme owner's event do a booking and then try to reschedule that immediately from the booking success page
	- It gives 404 on main and is fixed in the branch
- Test Team, Dynamic Group Booking and regular user bookings' reschedule as well because there is a refactor and change of logic involved.

### CODE REVIEW

**Comment by hariombalhara** [comment]
* **#15736** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/15736?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hariombalhara and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by Udit-takkar** [comment]
is this PR related to this issue https://github.com/calcom/cal.com/issues/14832?

**Comment by hariombalhara** [comment]
@Udit-takkar No. It is this one https://app.campsite.co/cal/posts/hm92k9ck9u3s

File: apps/web/pages/reschedule/[uid].tsx [hunk 1]
```diff
@@ -125,20 +131,23 @@ export async function getServerSideProps(context: GetServerSidePropsContext) {
...
-  const eventPage = `${
-    eventType.team
-      ? `team/${eventType.team.slug}`
-      : dynamicEventSlugRef
-      ? booking.dynamicGroupSlugRef
-      : booking.user?.username || "rick" /* This shouldn't happen */
-  }/${eventType?.slug}`;
+  const enrichedBookingUser = booking.user
+    ? await UserRepository.enrichUserWithItsProfile({ user: booking.user })
+    : null;
```
Comment (hariombalhara) [inline apps/web/pages/reschedule/[uid].tsx:136]: This user now has profile available with correct username depending on if he is in an org or not.

File: apps/web/pages/reschedule/[uid].tsx [hunk 2]
```diff
@@ -125,20 +131,23 @@ export async function getServerSideProps(context: GetServerSidePropsContext) {
...
+
+  const eventPage = await buildEventUrlFromBooking({
+    eventType,
+    dynamicGroupSlugRef: booking.dynamicGroupSlugRef ?? null,
```
Comment (hariombalhara) [inline apps/web/pages/reschedule/[uid].tsx:140]: Using just `dynamicGroupSlugRef` instead of checking for `dynamicEventSlugRef` nullish status and then using `dynamicGroupSlugRef`.


`dynamicGroupSlugRef` and `dynamicEventSlugRef` are set together. So, I don't see a different practically,

File: apps/web/playwright/reschedule.e2e.ts [hunk 3]
```diff
@@ -50,11 +56,11 @@ test.describe("Reschedule Tests", async () => {
     const user = await users.create();
     // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
     const booking = await bookings.create(user.id, user.username, user.eventTypes[0].id!, {
-      status: BookingStatus.CANCELLED,
+      status: BookingStatus.ACCEPTED,
```
Comment (hariombalhara) [inline apps/web/playwright/reschedule.e2e.ts:59]: CANCELLED booking can't be rescheduled through `reschedule/[uid]`. So, I changed it.

File: apps/web/playwright/reschedule.e2e.ts [hunk 4]
```diff
@@ -50,11 +56,11 @@ test.describe("Reschedule Tests", async () => {
...
       rescheduled: true,
     });
 
-    await page.goto(`/${user.username}/${user.eventTypes[0].slug}?rescheduleUid=${booking.uid}`);
+    await page.goto(`/reschedule/${booking.uid}`);
```
Comment (hariombalhara) [inline apps/web/playwright/reschedule.e2e.ts:63]: Using the endpoint that is accessed and not the URL it redirects to. This is more practical test.

File: apps/web/pages/reschedule/[uid].tsx [hunk 5]
```diff
@@ -125,20 +131,23 @@ export async function getServerSideProps(context: GetServerSidePropsContext) {
...
-      : dynamicEventSlugRef
-      ? booking.dynamicGroupSlugRef
-      : booking.user?.username || "rick" /* This shouldn't happen */
-  }/${eventType?.slug}`;
-  const destinationUrl = new URLSearchParams();
+  const enrichedBookingUser = booking.user
+    ? await UserRepository.enrichUserWithItsProfile({ user: booking.user })
+    : null;
+
+  const eventUrl = await buildEventUrlFromBooking({
```
Comment (hariombalhara) [inline apps/web/pages/reschedule/[uid].tsx:138]: Now we get the full URL so that it works no matter you access the booking on `app.cal.com` or `acme.cal.com`

File: apps/web/playwright/reschedule.e2e.ts [hunk 6]
```diff
@@ -331,4 +338,99 @@ test.describe("Reschedule Tests", async () => {
...
+        organizationId: org.id,
+        profileUsername: "username-inside-org",
+        roleInOrganization: MembershipRole.MEMBER,
+      });
+      const profileUsername = (await orgMember.getFirstProfile()).username;
+      const eventType = orgMember.eventTypes[0];
+      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
+      const orgSlug = org.slug!;
+      const getNonOrgUrlFromOrgUrl = (url: string) => url.replace(orgSlug, "app");
+      await test.step("Try rescheduling through org domain", async () => {
```
Comment (hariombalhara) [inline apps/web/playwright/reschedule.e2e.ts:371]: This was failing earlier.

File: apps/web/playwright/teams.e2e.ts [hunk 7]
```diff
@@ -321,6 +321,31 @@ testBothFutureAndLegacyRoutes.describe("Teams - NonOrg", (routeVariant) => {
   });
 
   todo("Create a Round Robin with different leastRecentlyBooked hosts");
-  todo("Reschedule a Collective EventType booking");
+  test("Reschedule a Collective EventType booking", async ({ users, page, bookings }) => {
```
Comment (hariombalhara) [inline apps/web/playwright/teams.e2e.ts:324]: Added team booking reschedule test as well as refactor might impact it.

**Review by hariombalhara — COMMENTED** [review]
Self review done

**Review by Udit-takkar — COMMENTED** [review]
E2E test " should create/remove scheduledWebhookTriggers for existing bookings " is failing. It's failing locally too.

**Comment by Udit-takkar** [comment]
@hariombalhara I was testing this on main and found that the reason the reschedule URL was throwing a 404 was that the username in the Profile table (owner1) did not match the username in the User table (owner1-dunder). why are we storing username on? and can we add we add a constraint on DB to make sure both are same?

**Comment by hariombalhara** [comment]
For a new user in an organisation, this doesn't happen.

But when an existing user is moved to an organization, the username in profile is always derived from email(This is a feature. If you know their email, you know their cal.com link). So, it would most probably change and thus this situation arises.

**Comment by hariombalhara** [comment]
The test is flaky. It just passed when I re-ran it.

**Review by sean-brydon — APPROVED** [review]
Tests seem to be passing now - watched loom and this branch deffo fixes the issue. Thanks @hariombalhara 

[approveyoda](https://app.graphite.dev//settings/meme-library?org=calcom)
