### PR TITLE
fix: incorrect slot duration when rescheduling bookings

### LINKED ISSUE #23284: incorrect slot length when changing event type length and then rescheduling it
1. Create an event type with length 15 minutes and then create a booking.
2. Change event type length to 60 minutes and try to reschedule it.
3. The slots length on the right side are still 15 minutes:
Image

So this is a problem when event type length changes between booking and rescheduling.

### PR DESCRIPTION
**Pull request by sahitya-chandra**
## What does this PR do?

- Fixes #23284 
- Fixes CAL-6307

## Visual Demo (For contributors especially)

[Screencast from 2025-08-23 02-59-22.webm](https://github.com/user-attachments/assets/c3628c35-d306-434c-851d-aa0c834c30bb)

A visual demonstration is strongly recommended, for both the original and new change **(video / image - any one)**.

#### Video Demo (if applicable):

- Show screen recordings of the issue or feature.
- Demonstrate how to reproduce the issue, the behavior before and after the change.

#### Image Demo (if applicable):

- Add side-by-side screenshots of the original and updated change.
- Highlight any significant change(s).

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

### CODE REVIEW

**Comment by sahitya-chandra** [comment]
@supalarry sir, I have found that `durationFromStore` in `packages/features/bookings/Booker/utils/event.ts` is responsible for setting the updated `duration` of the event-type and making the api call to fetch the slot related info for it but on changing the `event type length` the `durationFromStore` remains the same as `old event length` and it is not getting updated in `packages/features/bookings/components/event-meta/Duration.tsx` because of some conditional statements

So I have pushed the required code, can you have a look at the PR.
I have also added the video above at the start...

**Comment by sahitya-chandra** [comment]
@kart1ka @volnei sir can you review this PR also

**Review by Devanshusharma2005 — DISMISSED** [review]

File: packages/features/bookings/components/event-meta/Duration.tsx [hunk 1]
```diff
@@ -69,9 +69,16 @@ export const EventDuration = ({
...
+    // For multi-duration or dynamic events, set only once on mount and preserve user picks.
+    const hasMultiple = !!event.metadata?.multipleDuration;
+    if (selectedDuration == null && (hasMultiple || isDynamicEvent)) {
       setSelectedDuration(event.length);
+      return;
+    }
+    // For single-duration events, always sync to current event.length (reschedule case).
+    if (!hasMultiple && !isDynamicEvent && selectedDuration !== event.length) {
+      setSelectedDuration(event.length);
+    }
```
Comment (kart1ka) [inline packages/features/bookings/components/event-meta/Duration.tsx]: Since we’re calling `setSelectedDuration(event.length)` in both cases, we can simplify this into a single if statement.

**Review by kart1ka — DISMISSED** [review]
Left a comment

File: packages/features/bookings/components/event-meta/Duration.tsx (hunk 1 above)
Comment (sahitya-chandra) [reply packages/features/bookings/components/event-meta/Duration.tsx]: @kart1ka done sir

**Comment by sahitya-chandra** [comment]
@anikdhabal sir this is also fixed, please have a look at this also

**Comment by sahitya-chandra** [comment]
@anikdhabal sir is this code not working ??

**Review by anikdhabal — APPROVED** [review]
Looks good
