### PR TITLE
fix: Managed Event Type Webhooks

### LINKED ISSUE #10259: [CAL-2208] some webhooks for managed event types don't trigger
### Issue Summary

The webhooks  Booking canceled, Booking rejected and Booking confirmed don't trigger for managed event types (Team Webhooks).

The Booking created trigger for managed event types already got fixed here:
[https://github.com/calcom/cal.com/pull/10025](https://github.com/calcom/cal.com/pull/10025)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2208](https://linear.app/calcom/issue/CAL-2208/some-webhooks-for-managed-event-types-dont-trigger)</sub>

### PR DESCRIPTION
**Pull request by Pradumn27**
## What does this PR do?

This PR fixes the remaining webhook events not being triggered for managed team events, namely:  Booking canceled, Booking rejected, Booking confirmed, and Recording ready

Fixes #10259

Have used a similar approach to my previous pull request #10025 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Set Up a managed event type
- Subscribe to all webhook events.
- Perform booking creation, cancelation, rescheduling, confirmation, and rejection events
- Check that webhook is being triggered for all of them.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

### CODE REVIEW

**Review by Udit-takkar — DISMISSED** [review]
LGTM

File: apps/web/pages/api/recorded-daily-video.ts [hunk 1]
```diff
@@ -6,6 +6,7 @@ import { DailyLocationType } from "@calcom/app-store/locations";
 import { getDownloadLinkOfCalVideoByRecordingId } from "@calcom/core/videoClient";
 import { sendDailyVideoRecordingEmails } from "@calcom/emails";
 import { getServerSession } from "@calcom/features/auth/lib/getServerSession";
+import { getTeamId } from "@calcom/features/bookings/lib/handleNewBooking";
```
Comment (hariombalhara) [inline apps/web/pages/api/recorded-daily-video.ts:9]: nit: instead of importing getTeamId from handleNewBooking. It should be a utility in it's own maybe at packages/lib/getTeamId

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 2]
```diff
@@ -651,13 +651,17 @@ function getCustomInputsResponses(
   return customInputsResponses;
 }
 
-async function getTeamId({ eventType }: { eventType: Awaited<ReturnType<typeof getEventTypesFromDB>> }) {
+export async function getTeamId({
+  eventType,
+}: {
+  eventType: { team: { id: number | null } | null; parentId: number | null } | null;
```
Comment (hariombalhara) [inline packages/features/bookings/lib/handleNewBooking.ts:657]: nit: what's the need for allow **null** eventType

Also, even if we need to do that. A cleaner approach would be to just check eventType for nullishness and return early, so that later code need not use conditional chain on it.

**Review by hariombalhara — DISMISSED** [review]
LGTM !!

File: apps/web/pages/api/recorded-daily-video.ts (hunk 1 above)
Comment (Pradumn27) [reply apps/web/pages/api/recorded-daily-video.ts:9]: Yeah I also thought about this approach of a utility just wasn't sure about it, will. make the change.

File: packages/features/bookings/lib/handleNewBooking.ts (hunk 2 above)
Comment (Pradumn27) [reply packages/features/bookings/lib/handleNewBooking.ts:657]: yeah that's a good point will make the change

**Comment by Pradumn27** [comment]
Have made the nit changes @hariombalhara , thanks for the review !!

**Review by CarinaWolli — APPROVED** [review]
Looks good 👍
