### PR TITLE
fix: Prevent silent loss of changes in routing form when only one field exists

### LINKED ISSUE #25155: Fix "Leave without saving" modal (Routing Forms)
This modal isn't showing when there's only one form field. It works find where you add two new fields

How to reproduce:

1. Create a new routing form
2. Add a new field
3. Without saving go to the "Routing Form" tab
4. Modal doesn't show, and changes are lost

### PR DESCRIPTION
**Pull request by Zopsss**
## What does this PR do?

- Fixes #25155
- Fixes CAL-6748

Fixes a bug where the "unsaved changes" warning dialog doesn't appear when editing a routing form with only a single field, leading to silent data loss when switching tabs.

## Visual Demo (For contributors especially)

Before:

https://github.com/user-attachments/assets/4ed00e65-aa1f-468a-8b63-152737102a77

After:

https://github.com/user-attachments/assets/851c150a-1630-400c-ad1f-ae8d2f0980f5

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox. *N/A*
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Go to `/routing`
- Create a new routing form
- Add a new question
- Keep only one field and modify it
- Try going to the `Routing` tab.

---
## Summary by cubic
Fixes unsaved changes detection in Routing Forms so edits to a single field trigger the info-loss dialog when switching tabs, preventing silent loss. Fixes CAL-6748 and #25155.

- **Bug Fixes**
  - Subscribes to React Hook Form’s formState by destructuring isDirty, ensuring single-field edits are detected.
  - Shows the info-loss dialog when navigating to Route Builder if the form has unsaved changes.

<sup>Written for commit a7e13429ca2a22e1f8567fc065320bab02cff144. Summary will update automatically on new commits.</sup>

### CODE REVIEW

File: apps/web/components/apps/routing-forms/Header.tsx [hunk 1]
```diff
@@ -23,7 +23,7 @@ const useRoutingFormNavigation = (
 ) => {
   const pathname = usePathname();
   const router = useRouter();
-  const formContext = useFormContext<RoutingFormWithResponseCount>();
+  const { isDirty } = useFormContext<RoutingFormWithResponseCount>().formState;
```
Comment (Zopsss) [inline apps/web/components/apps/routing-forms/Header.tsx:26]: The issue was caused by how react-hook-form's Proxy subscription works.

Previously, we were accessing formContext.formState.isDirty directly in the if condition. According to [react-hook-form's documentation](https://react-hook-form.com/docs/useformstate#rules), formState is wrapped with a Proxy to improve performance and skip extra computation. However, the Proxy subscription only works if you destructure the properties at the component level before render.

image

By destructuring `isDirty` at the top level, we enable the Proxy subscription, ensuring the component re-renders when the form becomes dirty and the dialog appears as expected.

**Review by dhairyashiil — APPROVED** [review]
LGTM 👍🏼 , Thank you for the contribution

**Comment by dhairyashiil** [comment]
Thank you Mayuran for the info: [above comment](https://github.com/calcom/cal.com/pull/25197#discussion_r2533046695), 
While we’re on this, could you quickly go through the codebase and check whether we’re destructuring properties everywhere we’re supposed to? If not, please open a new PR to address it. Also, please create a new issue for that as well.

**Comment by Zopsss** [comment]
Sure, I will go through the codebase and if I will find similar cases then I will open an issue for it.

Just one question: Do I need to do anything for the automated tests checkbox, or can I leave it unchecked?

**Comment by dhairyashiil** [comment]
> Sure, I will go through the codebase and if I will find similar cases then I will open an issue for it.

Thank you 🙏🏼 

> Just one question: Do I need to do anything for the automated tests checkbox, or can I leave it unchecked?

We can leave it for now. If tests are failing due to the PR’s code change, we either have to fix the code (mostly) or update the tests (unlikely). If the tests are flaky, the team mostly takes care of it.

**Comment by Zopsss** [comment]
@dhairyashiil found some cases and opened an issue for them: https://github.com/calcom/cal.com/issues/25208. If it gets approved, I would love to work on it :D
