### PR TITLE
Fix for bad primary calendar check

### LINKED ISSUE #7517: Apple calendar not connecting or restoring.
### Issue Summary

Adding Apple Calendar presents:

image

Reloading the page now shows:

image

After some investigation it occured around the time of commit: #7428 and #6701 
b9064b1f7225d327c6ea74b6a749bc63be304e38
2a98ca4b9198e3dc64c6df9c61f679f382a01c47

### Steps to Reproduce

1. New instance
2. Add an apple calendar
3. Doesn't work

If I go back to using an older commit, one such as:
641301afabe77868ff54831dfd09943604a6f54b

Then it all works fine again, using the same info from the DB

### Technical details

- Latest Chrome
- Node.js 16

### PR DESCRIPTION
**Pull request by alishaz-polymath**
## What does this PR do?

This PR removes the bug introduced in PR #6701 which caused connected calendars to break in case of a missing primary calendar. It removed a fallback, which has now been re-introduced in this PR. There's also a minor code-quality improvement.

Fixes #7517 

**Environment**: Staging(main branch)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

File: packages/core/CalendarManager.ts [hunk 1]
```diff
@@ -57,12 +56,7 @@ export const getConnectedCalendars = async (
         const cals = await calendar.listCalendars();
         const calendars = _(cals)
           .map((cal) => {
-            if (cal.primary) {
-              primary = { ...cal, credentialId };
-            }
-            if (cal.externalId === destinationCalendarExternalId) {
-              destinationCalendar = cal;
-            }
+            if (cal.externalId === destinationCalendarExternalId) destinationCalendar = cal;
```
Comment (alishaz-polymath) [inline packages/core/CalendarManager.ts:59]: minor code improvement

File: packages/core/CalendarManager.ts [hunk 2]
```diff
@@ -73,11 +67,8 @@ export const getConnectedCalendars = async (
           })
           .sortBy(["primary"])
           .value();
-
-        if (primary && destinationCalendar) {
-          destinationCalendar.primaryEmail = primary.email;
-          destinationCalendar.integrationTitle = integration.title;
-        }
+        const primary!: IntegrationCalendar =
+          calendars.find((item) => item.primary) ?? calendars.find((cal) => cal !== undefined);
```
Comment (alishaz-polymath) [inline packages/core/CalendarManager.ts:71]: Added this as otherwise the fallback was missing causing the errors suggested in the related issue

File: packages/core/CalendarManager.ts [hunk 3]
```diff
@@ -87,6 +78,10 @@ export const getConnectedCalendars = async (
             },
           };
         }
+        if (destinationCalendar) {
+          destinationCalendar.primaryEmail = primary.email;
+          destinationCalendar.integrationTitle = integration.title;
+        }
```
Comment (alishaz-polymath) [inline packages/core/CalendarManager.ts:84]: Removed extra check by placing this check after !primary check, thus satisfying the condition with one less check. Minor improvement

**Review by alishaz-polymath — COMMENTED** [review]
Self review added, minor changes really. Should fix the bug.

**Review by emrysal — APPROVED** [review]
Approved 👍

**Review by joeauyeung — APPROVED** [review]
LGTM, thanks for catching this
