### PR TITLE
Fix lang and dir attributes not being set

### LINKED ISSUE #6237: [CAL-667] update lang="" in <html> when changing language
updating lang="<ISO>" is required so we can apply a different font for arabic. also helps with screen readers

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-667](https://linear.app/calcom/issue/CAL-667/update-lang=-in-html-when-changing-language)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #6237

**Environment**: Staging(main branch) / Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: packages/lib/i18n.ts [hunk 1]
```diff
@@ -17,33 +14,5 @@ export function getLocaleFromHeaders(req: IncomingMessage): string {
   return preferredLocale ?? i18n.defaultLocale;
 }
 
-export const getOrSetUserLocaleFromHeaders = async (req: IncomingMessage): Promise<string> => {
```
Comment (hariombalhara) [inline packages/lib/i18n.ts:20]: Wasn't being used anywhere

**Review by PeerRich — APPROVED** [review]
perfect! that works! 👏
