### PR TITLE
refactor: A improvement fix related to optional phone validation

### LINKED ISSUE #22225: Optional phone number booking question gives an error if we don't fill the question

### PR DESCRIPTION
**Pull request by Vansh5632**
## What does this PR do?
This ensure that for optional phone number fields it only validate the phone number if the field is not hidden and field is required or value is not empty

- Fixes #22225 
- Fixes CAL-6030

#### Image Demo (if applicable):
Screenshot from 2025-07-07 21-38-32
Screenshot from 2025-07-07 21-38-46

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox. N/A
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

    

---

## Summary by cubic
Fixed phone number validation so that optional phone fields are only validated if visible and either required or filled in.

- **Bug Fixes**
  - Prevented validation errors for empty optional phone fields that are not required.

### CODE REVIEW

**Review by anikdhabal — DISMISSED** [review]
Looks good

**Review by Udit-takkar — DISMISSED** [review]

File: packages/features/bookings/lib/getBookingResponsesSchema.ts [hunk 1]
```diff
@@ -276,8 +276,10 @@ function preprocess<T extends z.ZodType>({
         }
 
         if (bookingField.type === "phone") {
-          if (!bookingField.hidden && !(await phoneSchema.safeParseAsync(value)).success) {
-            ctx.addIssue({ code: z.ZodIssueCode.custom, message: m("invalid_number") });
+          if (!bookingField.hidden && (isRequired || (value && value.trim() !== ""))) {
```
Comment (hbjORbj) [inline packages/features/bookings/lib/getBookingResponsesSchema.ts]: it's difficult to understand what this conditional does here. I suggest:
1. extract `(isRequired || (value && value.trim() !== "")` into a new variable
2. leave explanatory comments

**Review by hbjORbj — DISMISSED** [review]
Thanks for the work! Left feedback.

File: packages/features/bookings/lib/getBookingResponsesSchema.ts (hunk 1 above)
Comment (Vansh5632) [reply packages/features/bookings/lib/getBookingResponsesSchema.ts]: completed this requirements

**Review by kart1ka — APPROVED** [review]
LGTM

**Comment by Vansh5632** [comment]
please would you approve this PR and merge it in or there are any changes in this tell me so that can i make changes into it

**Review by emrysal — APPROVED** [review]
Thank you for your contribution, looks good to me.  - looks like the hidden logic worked already but optional was not quite as optional.
