### PR TITLE
fix: credit balance issues

### LINKED ISSUE #21866: Credits assigned to wrong team
There's a bug where team credits are assigned to the wrong team's credit balance if the user is a member of more teams

### PR DESCRIPTION
**Pull request by CarinaWolli**
## What does this PR do?

Fixes some issues with credit balances and credit limit reached. More details can be found in the comments

- Fixes #21866
- Fixes CAL-5943

### CODE REVIEW

File: apps/web/pages/api/twilio/webhook.ts [hunk 1]
```diff
@@ -121,7 +121,7 @@ async function handler(req: NextApiRequest, res: NextApiResponse) {
 
   if (!orgId) {
     orgId = await getOrgIdFromMemberOrTeamId({
-      memberId: parsedUserId,
+      ...(!parsedTeamId ? { memberId: parsedUserId } : {}),
```
Comment (CarinaWolli) [inline apps/web/pages/api/twilio/webhook.ts:124]: If we have the teamId, we only want to know if the team is part of an organization. 

There is a possibility that the parsedUserId is part of a platform org, but the provided teamId is not from this org. This can cause team credits to be assigned wrongly to the platform org

File: packages/features/ee/billing/credit-service.ts [hunk 2]
```diff
@@ -157,12 +158,14 @@ export class CreditService {
...
           return true;
         }
+        // limtReachedAt is set and still no available credits
+        return false;
       }
 
       if (userId) {
         const teamWithAvailableCredits = await this._getTeamWithAvailableCredits({ userId, tx });
 
-        if (teamWithAvailableCredits && teamWithAvailableCredits?.availableCredits > 0) return true;
```
Comment (CarinaWolli) [inline packages/features/ee/billing/credit-service.ts:165]: This caused issues because `_getTeamWithAvailableCredits` could return a team with `limitReachedAt = null` but no available credits. In this case, we would not send the SMS and would send a fallback email instead, without ever setting  `limitReachedAt` and notifying the team.

File: packages/lib/server/repository/credits.ts [hunk 3]
```diff
@@ -161,8 +161,15 @@ export class CreditsRepository {
...
+    const { teamId, userId } = data;
+
+    if (!teamId && !userId) {
+      throw new Error("Team or user ID is required");
+    }
+
     return (tx ?? prisma).creditBalance.create({
-      data,
+      ...data,
+      ...(!teamId ? { userId } : {}),
```
Comment (CarinaWolli) [inline packages/lib/server/repository/credits.ts]: we should always only set either userId or teamId

File: packages/features/ee/billing/credit-service.ts [hunk 4]
```diff
@@ -127,6 +127,9 @@ export class CreditService {
       });
   }
 
+  /*
+    also returns true if team has no available credits but limitReachedAt is not yet set
```
Comment (CarinaWolli) [inline packages/features/ee/billing/credit-service.ts:131]: As long as limitReachedAt is not set, we keep allowing SMS sending. After an SMS is successfully sent, we charge the team and then set limitReachedAt if they are out of credits.

File: apps/web/pages/api/twilio/webhook.ts (hunk 1 above)
Comment (eunjae-lee) [reply apps/web/pages/api/twilio/webhook.ts:124]: Huh this is really tricky. I think this change makes sense, but if this pattern happens elsewhere more often, we could have another function that takes parameters like...

```
somethingSomething({
  type, // 'team' | 'user',
  id,    // number
})
```

then it will be exclusive and more readable. (Not suggesting we do this, but just sharing my chain of thought for future reference)

File: packages/lib/server/repository/credits.ts [hunk 5]
```diff
@@ -161,8 +161,17 @@ export class CreditsRepository {
   }
 
   static async createCreditBalance(data: Prisma.CreditBalanceUncheckedCreateInput, tx?: PrismaTransaction) {
+    const { teamId, userId } = data;
+
+    if (!teamId && !userId) {
```
[the remark this answers is not in the document]
Comment (eunjae-lee) [reply packages/lib/server/repository/credits.ts:166]: @CarinaWolli what do you think about this feedback? It makes sense to me, but I wonder if I'm missing something

**Review by eunjae-lee — APPROVED** [review]
I left one comment but it is not blocking. Feel free to merge, or make a commit and re-request for review 🙌🏻

File: packages/lib/server/repository/credits.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (CarinaWolli) [reply packages/lib/server/repository/credits.ts:166]: Was looking at it, but it's ok to have both passed. If we have both userId and teamId we should always use teamId
