### PR TITLE
fix: v1 API Teams access

### LINKED ISSUE #15852: Unintented access to all team bookings for a member of team via api ( update , cancel , e.t.c )
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A member of team is able to gain access to team bookings ( update , cancel , e.t.c ) in case of round robin event type , even if the user is not present as round robin host

- A team has A , B , C as its members
- Event Type X has scheduling type set to round robin with A , B as hosts 
- When a new user E books a meeting , one of A , B is assigned based on availabilty
- User C is not present in event type or booking in any form
- User C is able to cancel registered booking in above scenario via api

### Actual Results

- User is able to cancel a team booking , irrespective of involvement in the specific booking

### Expected Results

- User should only be able to cancel a team booking  , if the user is present in the booking ( as a host , attendee e.t.c )

### Evidence

Loom : [Video](https://www.loom.com/share/03416c6a934547748f9f948038e03cdb?sid=0fbc3d0b-2e1b-40fa-95b7-c1d246ebec98)

### PR DESCRIPTION
**Pull request by alishaz-polymath**
## What does this PR do?

Fixes Team access in V1 API:
- A user can't access or delete a team booking (with {id}) via API unless they're either host, or attendee, or they own the event-type/team that the event-type belongs to.
- A team admin can create and delete team event types via API

- Fixes #15852 , #16189 
- Fixes CAL-4204 (Linear issue number - should be visible at the bottom of the GitHub issue description)

## Mandatory Tasks (DO NOT REMOVE)

- [x] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [x] N/A
- [x] I confirm automated tests are in place that prove my fix is effective or that my feature works.

## How should this be tested?

- Are there environment variables that should be set?
- What are the minimal test data to have?
- What is expected (happy path) to have (input and output)?
- Any other important info that could help to test that PR

## Checklist

- I haven't read the [contributing guide](https://github.com/calcom/cal.com/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my changes generate no new warnings

Also special thanks to @Flash-Shivam for his PR #16207 which is considered in the fix in this PR.

### CODE REVIEW

File: apps/api/v1/pages/api/bookings/[id]/_auth-middleware.ts [hunk 1]
```diff
@@ -30,40 +30,51 @@ async function authMiddleware(req: NextApiRequest) {
...
+                owner: { id: userId },
+              },
+              {
+                team: {
+                  members: {
+                    some: { userId, role: { in: ["ADMIN", "OWNER"] } },
+                  },
+                },
+              },
+            ],
```
Comment (alishaz-polymath) [inline apps/api/v1/pages/api/bookings/[id]/_auth-middleware.ts:69]: It matches the booking id and any one of the following to satisfy:
1. User in Attendees
2. User owner of the event type
3. User admin/owner of the team that the event type of the booking belongs to

File: apps/api/v1/pages/api/bookings/[id]/_auth-middleware.ts [hunk 2]
```diff
@@ -30,40 +30,51 @@ async function authMiddleware(req: NextApiRequest) {
...
-    });
+      ],
+    },
+  });
 
-    if (!teamBookings) {
-      throw new HttpError({ statusCode: 403, message: "You are not authorized" });
-    }
-  }
+  if (!userIsHost && !teamBookingsAsOwnerOrAdmin)
```
Comment (alishaz-polymath) [inline apps/api/v1/pages/api/bookings/[id]/_auth-middleware.ts:76]: The booking doesn't belong to the user as a host, or as a team-booking Owner or Admin. So they have no access to it.

File: apps/api/v1/pages/api/event-types/[id]/_delete.ts [hunk 3]
```diff
@@ -49,8 +49,22 @@ async function checkPermissions(req: NextApiRequest) {
...
+      OR: [
+        { userId },
+        {
+          team: {
+            members: {
+              some: { userId, role: { in: ["ADMIN", "OWNER"] } },
+            },
+          },
+        },
+      ],
```
Comment (alishaz-polymath) [inline apps/api/v1/pages/api/event-types/[id]/_delete.ts:65]: Again, similar to the booking middleware check.

File: apps/api/v1/pages/api/teams/[teamId]/_auth-middleware.ts [hunk 4]
```diff
@@ -41,7 +41,7 @@ export async function canUserAccessTeamWithRole(
   /** If not ADMIN then we check if the actual user belongs to team and matches the required role */
   if (!isSystemWideAdmin) args.where = { ...args.where, members: { some: { userId, role } } };
   const team = await prisma.team.findFirst(args);
-  if (!team) throw new HttpError({ statusCode: 401, message: `Unauthorized: ${role.toString()} required` });
+  if (!team) throw new HttpError({ statusCode: 401, message: `Unauthorized: OWNER or ADMIN role required` });
```
Comment (alishaz-polymath) [inline apps/api/v1/pages/api/teams/[teamId]/_auth-middleware.ts:44]: `${role.toString()}` resulted in `[object] [object]` because of the value of role.

File: apps/api/v1/pages/api/bookings/[id]/_auth-middleware.ts [hunk 5]
```diff
@@ -30,40 +30,62 @@ async function authMiddleware(req: NextApiRequest) {
...
-      throw new HttpError({ statusCode: 403, message: "You are not authorized" });
-    }
-  }
+  const [resultOne, resultTwo, resultThree] = await Promise.all([
+    bookingsAsAttendee,
+    bookingsAsEventTypeOwner,
+    bookingsAsTeamOwnerOrAdmin,
+  ]);
+
+  const teamBookingsAsOwnerOrAdmin = [...resultOne, ...resultTwo, ...resultThree];
```
Comment (alishaz-polymath) [inline apps/api/v1/pages/api/bookings/[id]/_auth-middleware.ts:84]: This way cuz Bookings Table is gigantic and OR goes with the query engine doing `Seq Scan` instead of `Index Scan`

File: apps/api/v1/pages/api/event-types/_utils/checkParentEventOwnership.ts [hunk 6]
```diff
@@ -44,7 +40,8 @@ export default async function checkParentEventOwnership(req: NextApiRequest) {
     where: {
       teamId: parentEventType.teamId,
       userId: userId,
-      OR: [{ role: "OWNER" }, { role: "ADMIN" }],
+      role: { in: ["ADMIN", "OWNER"] },
```
Comment (alishaz-polymath) [inline apps/api/v1/pages/api/event-types/_utils/checkParentEventOwnership.ts:43]: Not sure why we opted for OR there in the first place, in should be a lot quicker, esp for a table of this size.

File: apps/api/v1/pages/api/event-types/_utils/checkTeamEventEditPermission.ts [hunk 7]
```diff
@@ -10,21 +10,17 @@ export default async function checkTeamEventEditPermission(
   req: NextApiRequest,
   body: Pick<z.infer<typeof schemaEventTypeCreateBodyParams>, "teamId" | "userId">
 ) {
-  const { isSystemWideAdmin } = req;
-  let userId = req.userId;
-  if (isSystemWideAdmin && body.userId) {
-    userId = body.userId;
-  }
```
Comment (alishaz-polymath) [inline apps/api/v1/pages/api/event-types/_utils/checkTeamEventEditPermission.ts:17]: We really don't need this check here again primarily because isSystemWideAdmin means it's all clear for the access, and we do that everywhere this is called. So it's actually never really succeeds here lol (because it only reaches here when isSystemWideAdmin is false) 🫠

File: apps/api/v1/pages/api/bookings/[id]/_auth-middleware.ts (hunk 5 above)
Comment (alishaz-polymath) [reply apps/api/v1/pages/api/bookings/[id]/_auth-middleware.ts:84]: This way is **much** faster

**Review by keithwillcode — DISMISSED** [review]
Changes looking good. Can we please add some tests to verify this functionality?

**Comment by alishaz-polymath** [comment]
> Changes looking good. Can we please add some tests to verify this functionality?

Will do 🙏

File: apps/api/v1/pages/api/event-types/[id]/_delete.ts [hunk 8]
```diff
@@ -49,9 +51,18 @@ async function checkPermissions(req: NextApiRequest) {
...
-  const eventType = await prisma.eventType.findFirst({ where: { id, userId } });
+
+  const eventType = await prisma.eventType.findFirst({ where: { id } });
+
   if (!eventType) throw new HttpError({ statusCode: 403, message: "Forbidden" });
+
+  /** Only event type owners or team owners for team events can delete it */
+  if (eventType.teamId) await checkTeamEventEditPermission(req, eventType);
+
+  if (eventType.parentId) await checkParentEventOwnership(req);
```
Comment (Amit91848) [inline apps/api/v1/pages/api/event-types/[id]/_delete.ts:62]:
```suggestion
  if (eventType.teamId) return await checkTeamEventEditPermission(req, eventType);

  if (eventType.parentId) return await checkParentEventOwnership(req);
```

Minor NIT: can add early returns

**Review by Amit91848 — COMMENTED** [review]
Changes look good apart from the tests 👍👌

**Review by zomars — DISMISSED** [review]
LGTM

**Review by zomars — APPROVED** [review]
Very nice improvements! Nice work @alishaz-polymath 🙏🏽
