### PR TITLE
Fixing Ghost Input

### LINKED ISSUE #2103: Ghost Input on Event Location
### Issue Summary

Whenever address is populated in the event location - editing any other field creates a ghost input or simply doesnt work.

### Steps to Reproduce

1. Add In person location
2. Add another location
3. Try and edit either
4. 
### Technical details

- [Birdseatbugs](https://app.birdeatsbug.com/sessions/vpjztaBdaovEGCYw5fopf)

### PR DESCRIPTION
**Pull request by sean-brydon**
## What does this PR do?

Fixes the ghost input being produced when either link meeting or in person meeting were used in conjunction with another location type.

Fixes #2103 

## Type of change

- [ X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Add In person location 
- [ ] Add link location
- [ ] Add Any other location 
- [ ] Try and edit any of the added locations

## Checklist

- I haven't commented my code, particularly in hard-to-understand areas
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: apps/web/pages/event-types/[type].tsx [hunk 1]
```diff
@@ -1610,6 +1616,8 @@ const EventTypePage = (props: inferSSRProps<typeof getServerSideProps>) => {
                         onChange={(val) => {
                           if (val) {
                             locationFormMethods.setValue("locationType", val.value);
+                            locationFormMethods.unregister("locationLink");
```
Comment (sean-brydon) [inline apps/web/pages/event-types/[type].tsx:1619]: Un register the input so that they are not present when you are trying to change any other location

File: apps/web/pages/event-types/[type].tsx [hunk 2]
```diff
@@ -660,7 +661,12 @@ const EventTypePage = (props: inferSSRProps<typeof getServerSideProps>) => {
                   <div className="flex">
                     <button
                       type="button"
-                      onClick={() => openLocationModal(location.type)}
+                      onClick={() => {
+                        locationFormMethods.setValue("locationType", location.type);
```
Comment (sean-brydon) [inline apps/web/pages/event-types/[type].tsx:665]: Set the location so we actually edit the right place. As previously you were trying to edit a location type that isn't the one you clicked

File: apps/web/pages/event-types/[type].tsx [hunk 3]
```diff
@@ -22,6 +22,7 @@ import timezone from "dayjs/plugin/timezone";
 import utc from "dayjs/plugin/utc";
 import { GetServerSidePropsContext } from "next";
 import { useRouter } from "next/router";
+import form from "pages/sandbox/form";
```
Comment (baileypumfleet) [inline apps/web/pages/event-types/[type].tsx:25]: Are we supposed to be using things from the sandbox?

Comment (sean-brydon) [reply apps/web/pages/event-types/[type].tsx:25]: Good Spot - Its not even being used... Will remove this

Comment (sean-brydon) [reply apps/web/pages/event-types/[type].tsx]: New commit added

**Review by alannnc — APPROVED** [review]

**Review by alannnc — APPROVED** [review]
Code looks good and the bug isn't happening anymore
