### PR TITLE
fix: google calendar busy times

### LINKED ISSUE #11688: [CAL-2575] [CAL-2574] Busy events from Google Calendar not reflected on the booking page
Screenshot 2023-10-04 at 10 39 15

When you try to book the slot that is not supposed to be there, the error shows
Screenshot 2023-10-04 at 10 44 52

https://www.loom.com/share/b3e5cd34f41b4fc5b95b06707df1bbf7?sid=866dd324-620d-4bc2-af62-96789daf44ef 

Created via Threads. See full discussion: [https://threads.com/34540603431](https://threads.com/34540603431)

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2574](https://linear.app/calcom/issue/CAL-2574/busy-events-from-google-calendar-not-reflected-on-the-booking-page)</sub>

<sub>[CAL-2575](https://linear.app/calcom/issue/CAL-2575/[cal-2574]-busy-events-from-google-calendar-not-reflected-on-the)</sub>

### PR DESCRIPTION
**Pull request by CarinaWolli**
## What does this PR do?

This PR fixes the following issue:
Busy times from Google Calendar didn't block out slots anymore after Nov 4. I could reproduce that with having everything set to NY timezone, but this probably also happens in other timezones.

The reason for that, is that the request `https://www.googleapis.com/calendar/v3/freeBusy` was throwing `The requested time range is too long`. 

Fixes #11688

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- Connect Google calendar
- Add a busy event to calendar
- Check if the slots are blocked off in the availability (test after Nov 4)

### CODE REVIEW

File: packages/features/bookings/Booker/Booker.tsx [hunk 1]
```diff
@@ -115,6 +115,7 @@ const BookerComponent = ({
     columnViewExtraDays.current =
       Math.abs(dayjs(selectedDate).diff(availableSlots[availableSlots.length - 2], "day")) + addonDays;
   const prefetchNextMonth =
```
Comment (CarinaWolli) [inline packages/features/bookings/Booker/Booker.tsx:117]: This change was made here: https://github.com/calcom/cal.com/pull/9815/files#diff-d8cdd443610a4483db45dcc4da6a02bcff302ad6c591aea6fa1ee8646a52aedbR116

We only need `prefetchNextMonth` for the COLUMN_VIEW. The error `The requested time range is too long.` can still happen in the column view if the timespan shown is too long

**Review by zomars — APPROVED** [review]
Nice find @CarinaWolli can we follow up with a test to prevent regression? 🙏

File: packages/features/bookings/Booker/Booker.tsx (hunk 1 above)
Comment (hariombalhara) [reply packages/features/bookings/Booker/Booker.tsx:117]: I think we can fix it for longer ranges completely by breaking down the range into multiple acceptable ranges and sending multiple requests? 

I saw someone did similar for Zoho Calendar

Comment (CarinaWolli) [reply packages/features/bookings/Booker/Booker.tsx:117]: Yes, I will make a follow-up PR 👍
