### PR TITLE
fix for showAttendees default value

### LINKED ISSUE #7262: [CAL-1129] showAttendees prop should be true in default.
A customer said he is having trouble since this feature was introduced, we need to validate that this props comes with a default value as true and add a test to make sure it works as expected.

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1129](https://linear.app/calcom/issue/CAL-1129/showattendees-prop-should-be-true-in-default)</sub>

### PR DESCRIPTION
**Pull request by alannnc**
## What does this PR do?

- Defaults showAttendees to true if seatsPerBooking its null

Fixes #7262 

**Environment**: Staging(main branch)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Create a booking and install google calendar.
- [ ] Make a booking to it and calendar event shouldn't have its attendees hidden if seats aren't enabled for that eventType.

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 1]
```diff
@@ -582,7 +582,8 @@ async function handler(req: NextApiRequest & { userId?: number | undefined }) {
     hideCalendarNotes: eventType.hideCalendarNotes,
     requiresConfirmation: requiresConfirmation ?? false,
     eventTypeId: eventType.id,
-    seatsShowAttendees: !!eventType.seatsShowAttendees,
+    // if seats are not enabled we should default true
+    seatsShowAttendees: !!eventType.seatsPerTimeSlot ? eventType.seatsShowAttendees : true,
```
Comment (alannnc) [inline packages/features/bookings/lib/handleNewBooking.ts:586]: As eventType.seatsPerTimeSlot was default null, it was hiding every attendee at every booking.

**Review by zomars — APPROVED** [review]
