### PR TITLE
fix: Speed up booking time

### LINKED ISSUE #14810: [CAL-3592] Booking timeouts with Outlook Calendar when Team has many members
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3592](https://linear.app/calcom/issue/CAL-3592/booking-timeouts-with-outlook-calendar-when-team-has-many-members)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #14810

[Loom](https://www.loom.com/share/fe8c707f6f7741c68c15b5ae442a753f) Take almost same amount of time to book as to load the availability
## Type of changef
- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?
- Create a team event with many members (say 3) with all of them connected to Outlook Calendar(or any other Calendar)
- Add a fake delay to `getAvailability` inside `CalendarService`. Something like this would work 
```Javascript
 await new Promise((resolve) => {
      setTimeout(resolve, 1000);
    });
    return [];
```
- Try booking the event. It would take more than 3*10 seconds in main. 
- In this branch it should take 10 seconds. 

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist
- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by hariombalhara** [comment]
* **#14809** <a href="https://app.graphite.dev/github/pr/calcom/cal.com/14809?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hariombalhara and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: packages/core/getUserAvailability.ts [hunk 1]
```diff
@@ -794,3 +794,43 @@ const _getOutOfOfficeDays = async ({
...
+type GetUserAvailabilityQuery = Parameters<typeof getUserAvailability>[0];
+type GetUserAvailabilityInitialData = NonNullable<Parameters<typeof getUserAvailability>[1]>;
+
+const _getUsersAvailability = async ({
+  users,
+  query,
+  initialData,
+}: {
+  users: (NonNullable<GetUserAvailabilityInitialData["user"]> & {
+    currentBookings?: GetUserAvailabilityInitialData["currentBookings"];
```
Comment (hariombalhara) [inline packages/core/getUserAvailability.ts:807]: currentBookings are per user so expecting it in user only.

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 2]
```diff
@@ -362,24 +362,25 @@ export async function ensureAvailableUsers(
     });
   }
 
-  for (const user of eventType.users) {
-    const { oooExcludedDateRanges: dateRanges, busy: bufferedBusyTimes } = await getUserAvailability(
-      {
+  (
+    await getUsersAvailability({
```
Comment (hariombalhara) [inline packages/features/bookings/lib/handleNewBooking.ts:366]: Use function that can operate on `users`

File: packages/trpc/server/routers/viewer/slots/util.ts [hunk 3]
```diff
@@ -456,44 +456,44 @@ export async function getAvailableSlots({ input, ctx }: GetScheduleOptions): Pro
     });
   }
 
+  const users = usersWithCredentials.map((currentUser) => {
+    return {
+      ...currentUser,
+      currentBookings: currentBookingsAllUsers
```
Comment (hariombalhara) [inline packages/trpc/server/routers/viewer/slots/util.ts:462]: Extract currentBookings out here as that is specific to user.

File: packages/features/bookings/lib/handleNewBooking.ts [hunk 4]
```diff
@@ -362,24 +362,25 @@ export async function ensureAvailableUsers(
...
+      initialData: {
         eventType,
         rescheduleUid: input.originalRescheduledBooking?.uid ?? null,
         busyTimesFromLimitsBookings: busyTimesFromLimitsBookingsAllUsers,
-      }
-    );
+      },
+    })
+  ).forEach(({ oooExcludedDateRanges: dateRanges, busy: bufferedBusyTimes }, index) => {
+    const user = eventType.users[index];
```
Comment (hariombalhara) [inline packages/features/bookings/lib/handleNewBooking.ts:383]: As userAvailabilities are returned in order of users, we could use the index to retrieve the current user from `users`.

File: packages/trpc/server/routers/viewer/slots/util.ts (hunk 3 above)
Comment (sean-brydon) [inline packages/trpc/server/routers/viewer/slots/util.ts:462]: I wonder if we can use a reduce here to make this even faster - we are filtering and then mapping which is 2 itterations - i think we can make it just one with something like 
(Note this will type error as we'd need to type the array in the reduce function and i didnt spend enough time to figure it out)
```
currentBookingsAllUsers.reduce((accumulator, booking) => {
  if (booking.userId === currentUser.id || booking.attendees?.some((a) => a.email === currentUser.email)) {
    const { attendees: _attendees, ...bookingWithoutAttendees } = booking;
    accumulator.push(bookingWithoutAttendees);
  }
  return accumulator;
}, []);
```

**Review by sean-brydon — COMMENTED** [review]
I have tested this in a fair few times and havent once ran into any issues - tests are passing. I think this is an amazing thing to ship well done bud!

Will wait for another approval since this seems like it could be high risk @emrysal @CarinaWolli

File: packages/trpc/server/routers/viewer/slots/util.ts (hunk 3 above)
Comment (hariombalhara) [reply packages/trpc/server/routers/viewer/slots/util.ts:462]: I didn't do that because even with 500 users, multiple iterations won't make a noticeable difference.

Plus reduce is less readable than map.

Comment (keithwillcode) [reply packages/trpc/server/routers/viewer/slots/util.ts:462]: Yeah great call, @hariombalhara. Scalars are removed in Big-O notation. i.e. O(2n) = O(n)

**Review by keithwillcode — APPROVED** [review]
Great change, @hariombalhara.

**Review by emrysal — APPROVED** [review]
