### PR TITLE
Fix RHF data on bg update

### LINKED ISSUE #5003: [CAL-154] Routing forms not saving if user moves too fast
[https://app.birdeatsbug.com/sessions/PROrB0lTha1yy1AtfzgyF6H_ExJFDwfoQ9D9IPJfYcxZ](https://app.birdeatsbug.com/sessions/PROrB0lTha1yy1AtfzgyF6H_ExJFDwfoQ9D9IPJfYcxZ)

> From [Linear-GitHub Sync](https://synclinear.com)

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #5003

**Environment**: Production

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] See the loom in the bug

### CODE REVIEW

File: packages/app-store/ee/routing-forms/components/SingleForm.tsx [hunk 1]
```diff
@@ -192,6 +192,10 @@ function SingleForm({ form, appUrl, Page }: SingleFormComponentProps) {
     defaultValues: form,
   });
 
+  useEffect(() => {
```
Comment (hariombalhara) [inline packages/app-store/ee/routing-forms/components/SingleForm.tsx:195]: When switching from 1 tab to another, hookForm get's initialized with current value of tRPC formQuery results. If a mutation has just happened, then an invalidation is in progress and hookForm initializes before that invalidation is complete. So, it's data not needs resetting

**Review by hariombalhara — COMMENTED** [review]
Self reviewed

File: packages/app-store/ee/routing-forms/components/SingleForm.tsx [hunk 2]
```diff
@@ -192,6 +192,10 @@ function SingleForm({ form, appUrl, Page }: SingleFormComponentProps) {
     defaultValues: form,
```
Comment (emrysal) [inline packages/app-store/ee/routing-forms/components/SingleForm.tsx:192]: I don't think you still need this line (probably setting it twice now)

**Review by PeerRich — APPROVED** [review]

**Review by emrysal — APPROVED** [review]
Approved with minor comment 🥇

File: packages/app-store/ee/routing-forms/components/SingleForm.tsx (hunk 2 above)
Comment (hariombalhara) [reply packages/app-store/ee/routing-forms/components/SingleForm.tsx:192]: Yeah, technically, I don't. But I still find it good to give `defaultValues` as it declaratively tells what value does the hookForm have. Makes the code more readable in a way.

Plus, I think SSR won't work. I will be back with testing results.

Comment (hariombalhara) [reply packages/app-store/ee/routing-forms/components/SingleForm.tsx:192]: Yeah, I am doing SSR for the pages and removing defaultValues would cause SSR to not work fully.
