### PR TITLE
fix: Routing Form, only last option of multiselect is forwarded to Booking Form.

### LINKED ISSUE #9329: [CAL-1865] Routing Form - Only the last option for Multi Select Field is forwarded to Booking Form
<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-1865](https://linear.app/calcom/issue/CAL-1865/routing-form-only-the-last-option-for-multi-select-field-is-forwarded)</sub>

### PR DESCRIPTION
**Pull request by hariombalhara**
## What does this PR do?

Fixes #9329 
Fixes Cal-1865

Before Fix:
https://www.loom.com/share/fb1692f1269d47ae934300001d3a8d3f
After Fix:
https://www.loom.com/share/4f0c31c391b24eb080596b89cbfa6aff

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

Bug-1: MultiSelect field has only last option in query string
- Create an Routing Form with multiple select type and choose all the options for the field.
- Notice that only last of the option is visible in  the query string.

Bug-2
- Simply submit a routing form that redirects to event-type
- Notice that submit button loader goes away and still nothing happens for a very significant amount of time

## Checklist

- I haven't added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: apps/web/lib/hooks/useRouterQuery.ts [hunk 1]
```diff
@@ -5,7 +5,19 @@ export default function useRouterQuery<T extends string>(name: T) {
   const existingQueryParams = router.asPath.split("?")[1];
 
   const urlParams = new URLSearchParams(existingQueryParams);
-  const query = Object.fromEntries(urlParams);
```
Comment (hariombalhara) [inline apps/web/lib/hooks/useRouterQuery.ts:8]: fromEntries returns Record<string,string> value and thus it ends up overriding existing keys.

**Review by emrysal — APPROVED** [review]
