### PR TITLE
fix: cancel workflows on cancel booking

### LINKED ISSUE #17806: [CAL-4779] cancelling in app.cal.com does not cancel workflow
we know cancelling outside of cal.com doesnt cancel workflows

however even cancelling inside app.cal.com still sends scheduled workflows

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-4779](https://linear.app/calcom/issue/CAL-4779/cancelling-in-appcalcom-does-not-cancel-workflow)</sub>

### PR DESCRIPTION
**Pull request by VK-RED**
## What does this PR do?

- Fixes #17806  
- Fixes CAL-4779 

Removed deleteScheduledSend function in scheduledEmailRemainder cron api, as this lead to removing the cancelled label on the scheduled emails, thus causing the users to receive emails for cancelled event.

According to sendGrid docs : 

> When a Batch is canceled, all messages associated with that batch will stay in your sending queue, but when their send_at value is reached, they will be discarded instead of attempting delivery.

Link to SendGrid [docs](https://www.twilio.com/docs/sendgrid/for-developers/sending-email/stopping-a-scheduled-send#3-cancel-or-pause-your-send)

#### Event Created

Screenshot from 2024-11-26 17-07-46

#### Event Cancelled

Screenshot from 2024-11-26 17-09-38

#### Simulated a Cron

Simulated a cron to execute deleteScheduledSend to delete emails in the queue.
https://github.com/calcom/cal.com/blob/main/packages/features/ee/workflows/api/scheduleEmailReminders.ts#L80

Ideally this cron action should have deleted the emails in the queue, and the users should not get any email regarding the cancelled booking

#### Email Received on Cancelled Booking

Screenshot from 2024-11-26 17-30-54

Did not received SMS or Whatsapp Reminder, but still received email on the cancelled booking.

#### Event Created
Screenshot from 2024-11-26 18-08-25

#### Event Cancelled
Screenshot from 2024-11-26 18-09-14

#### Again Simulated the cron
https://github.com/calcom/cal.com/blob/main/packages/features/ee/workflows/api/scheduleEmailReminders.ts#L80

#### No Emails received on Cancelled Booking
Screenshot from 2024-11-26 18-31-14

No emails , SMS or Whatsapp reminder is received.

## Mandatory Tasks (DO NOT REMOVE)

- [ ] I have self-reviewed the code (A decent size PR without self-review might be rejected).
- [ ] I have updated the developer docs in /docs if this PR makes changes that would require a [documentation change](https://cal.com/docs). If N/A, write N/A here and check the checkbox.
- [ ] I confirm automated tests are in place that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by Praashh — DISMISSED** [review]
@VK-RED would be great if you add a loom video.

**Comment by VK-RED** [comment]
Hi @Praashh here is a screen recording

### Screencast

https://github.com/user-attachments/assets/802c78fe-78d9-4407-aa0d-583f38c3baa2

#### No Emails Received 

image

**Comment by keithwillcode** [comment]
@CarinaWolli Can you please take a look at this one? 🙏

File: packages/features/ee/workflows/lib/reminders/emailReminderManager.ts [hunk 1]
```diff
@@ -377,6 +378,8 @@ export const deleteScheduledEmailReminder = async (reminderId: number, reference
         cancelled: true,
       },
     });
+
+    await cancelScheduledEmailSend(referenceId);
```
Comment (CarinaWolli) [inline packages/features/ee/workflows/lib/reminders/emailReminderManager.ts:382]: We need to do this in the cron job, there is a limit of canceled emails in the scheduled_sends queue which we will reach otherwise

File: packages/features/ee/workflows/api/scheduleEmailReminders.ts [hunk 2]
```diff
@@ -43,24 +38,6 @@ async function handler(req: NextApiRequest, res: NextApiResponse) {
...
-    deletePromises.push(deletePromise);
-  }
-
-  Promise.allSettled(deletePromises).then((results) => {
-    results.forEach((result) => {
-      if (result.status === "rejected") {
-        logger.error(`Error deleting batch id from scheduled_sends: ${result.reason}`);
-      }
-    });
-  });
```
Comment (CarinaWolli) [inline packages/features/ee/workflows/api/scheduleEmailReminders.ts:62]: > When a Batch is canceled, all messages associated with that batch will stay in your sending queue, but when their send_at value is reached, they will be discarded instead of attempting delivery.

Interesting, I thought we used to have an issue that they weren't deleted from the sending queue automatically. But also, this shouldn't effect workflow reminders because we would only delete them when they are already in the past

**Review by CarinaWolli — CHANGES_REQUESTED** [review]

**Comment by VK-RED** [comment]
Let's say an email is set to be triggerred at 10.30 But the user cancelled the booking at 10.05. At 10.15 A cron job would run this https://github.com/calcom/cal.com/blob/main/packages/features/ee/workflows/api/scheduleEmailReminders.ts#L80 and mark the status of the emails as cancelled. Again at 10.30 when the cron job would runs , this line https://github.com/calcom/cal.com/blob/main/packages/features/ee/workflows/api/scheduleEmailReminders.ts#L52 , it essentially removes the cancelled label from the email. As a result when the label is lifted the user receives an email for the cancelled event . Check out the answer of this thread for more details : https://stackoverflow.com/questions/71461746/unable-to-cancel-scheduled-sendgrid-email-with-batch-id

File: packages/features/ee/workflows/lib/reminders/emailReminderManager.ts (hunk 1 above)
Comment (VK-RED) [reply packages/features/ee/workflows/lib/reminders/emailReminderManager.ts:382]: Got it ! Will remove this ..

File: packages/features/ee/workflows/api/scheduleEmailReminders.ts (hunk 2 above)
Comment (VK-RED) [reply packages/features/ee/workflows/api/scheduleEmailReminders.ts:62]: https://github.com/calcom/cal.com/blob/main/packages/features/ee/workflows/lib/getWorkflowReminders.ts#L87 . lte also gets the current and past cancelled workflows

Comment (CarinaWolli) [reply packages/features/ee/workflows/api/scheduleEmailReminders.ts:62]: is the issue that we use `lte` instead of `lt`? Deleting the ones in the past shouldn't cause any issues, right?

Comment (VK-RED) [reply packages/features/ee/workflows/api/scheduleEmailReminders.ts:62]: Yeah `lt` should fix this as we will be only clearing the past events and not the current events.

**Comment by VK-RED** [comment]
@CarinaWolli any updates ..

File: packages/features/ee/workflows/api/scheduleEmailReminders.ts (hunk 2 above)
Comment (CarinaWolli) [reply packages/features/ee/workflows/api/scheduleEmailReminders.ts:62]: > Yeah lt should fix this as we will be only clearing the past events and not the current events.

Can we do that then instead? 

I was just trying to test it locally if a batch id gets deleted from` /scheduled_sends ` when the email is in the past. But for me that didn't happen and it seems like we do have to manually delete them when they are in the past

Comment (VK-RED) [reply packages/features/ee/workflows/api/scheduleEmailReminders.ts]: Yep ! done that !

**Review by CarinaWolli — APPROVED** [review]
Thank you 🙏
