### PR TITLE
fix: Email Embed for team event types

### LINKED ISSUE #13679: [CAL-3135] Email embed not showing available slots
Screenshot 2024-02-14 at 11 50 22
Screenshot 2024-02-14 at 11 50 29

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-3135](https://linear.app/calcom/issue/CAL-3135/email-embed-not-showing-available-slots)</sub>

### PR DESCRIPTION
**Pull request by Udit-takkar**
## What does this PR do?

Fixes  https://github.com/calcom/cal.com/issues/13679

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Tests (Unit/Integration/E2E or any other test)

### CODE REVIEW

File: packages/features/embed/Embed.tsx [hunk 1]
```diff
@@ -471,7 +486,8 @@ const EmailEmbedPreview = ({
               <div style={{ marginTop: "13px" }}>
                 <a
                   className="more"
-                  href={`${WEBSITE_URL}/${username}/${eventType.slug}`}
+                  data-testid="see_all_available_times"
+                  href={`${eventType.bookerUrl}/${calLink}`}
```
Comment (Udit-takkar) [inline packages/features/embed/Embed.tsx:490]: fixed preview url

File: packages/features/embed/Embed.tsx [hunk 2]
```diff
@@ -721,8 +739,9 @@ const EmbedTypeCodeAndPreviewDialogContent = ({
           {eventTypeData?.eventType && embedType === "email" ? (
             <EmailEmbed
               eventType={eventTypeData?.eventType}
-              username={data?.user.username as string}
+              username={teamSlug ?? (data?.user.username as string)}
```
Comment (Udit-takkar) [inline packages/features/embed/Embed.tsx:742]: Need to pass teamSlug and isTeamEvent to make useScheduledForEvent get event type details and slots

**Review by sean-brydon — APPROVED** [review]
CleanShot 2024-03-06 at 09 55 23
Works as expected- nice one bud!
